### PR TITLE
Use triggerLayoutAll() when updating the measure number property of section breaks

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #21621 

Due to the changes I made in #20141. This is a rare case where a layout of the whole score is actually necessary.

### CODE REVIEW

**Review by cbjeukendrup — APPROVED** [review]
It would be nice if we had more granularity; i.e. only calculate the new measure numbers and update the layout only where necessitated by these changes. (These changes are still spread over the entire score, but not all calculations for the entire score need to be redone.) 
I don't think we should do an ad-hoc solution for this specific case, but build a general system for that in the future.

**Comment by worldwideweary** [comment]
```cpp
if (propertyId == Pid::START_WITH_MEASURE_ONE) {
        triggerLayoutAll();
    } else {
```

I think there may be a problem here. That is, if a user has this "Start with measure one" enabled but then removes it, the rest of the score won't get updated afterwards, as that only happens when it *is* enabled, so there'll be a problem with the measure numbers not being updated until another score layout by the user.

P.S. I just said screw it and updated the score from that point onward to the end of the score instead of starting from the beginning via the actual score's `setLayout` method which takes begin/end tick arguments (start of the layout-break to the end of the score)... so it's kind of half-way efficient in that at least it doesn't start at the beginning of the score. YMMV

**Comment by Jojo-Schmitz** [comment]
>  if a user has this "Start with measure one" enabled but then removes it, the rest of the score won't get updated afterwards, as that only happens when it _is_ enabled, 

Well, as far as I can tell this code path is taken on setting as well as on unsetting that property

**Comment by Jojo-Schmitz** [comment]
There's still an issue with the 1st measure (and its number) after a section break, disabling "Reset measure numbers" doesn't bring it back if showing measure number 1 is disabled in Format > Style > Measure numbers

**Comment by worldwideweary** [comment]
> this code path is taken on setting as well as on unsetting that property.

Ah yeah. Must've been tired and interpreted it as "if on". Still, can consider using the start/end tick for requiring less work to update at break, but yet I didn't test if that exists or works in the Mu4 code.

**Comment by worldwideweary** [comment]
An example of the problem still remaining in the pr since it's not contingent upon that particular style when adding the section break:

https://github.com/musescore/MuseScore/assets/7139517/813eb1bd-5cf3-411f-b082-98b738f889b5

**Review by cbjeukendrup — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
As far as I can tell still the same issue with that score @worldwideweary used above

**Comment by Jojo-Schmitz** [comment]
And still the same issue with not returning the 1st measure number after the section break, when disabling that property of that break

**Review by oktophonie — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
So this got merged regardless of the issues mentioned?

**Comment by worldwideweary** [comment]
@Jojo-Schmitz To be fair, this code looks pretty decent. It seems to me that the problem encountered stems from #21149, iirc reverting it in 3.7 fixed the problem. Wouldn't put all my chips in for that statement just yet though...

**Comment by mike-spa** [comment]
> As far as I can tell still the same issue with that score @worldwideweary used above.

Can you _actually_ show me this issue in the latest version of this PR? Cause I have downloaded that file, tested for that issue, and found it to be fixed.

**Comment by Jojo-Schmitz** [comment]
Both issues?

**Comment by Jojo-Schmitz** [comment]
Hmm, OK, I can't reproduce either anymore

**Pull request merged**
