### PR TITLE
Some text wrap fixes

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #12774
Resolves: https://discord.com/channels/818804595450445834/818852942882275379/1007159359941394523

Enabling word wrap is nice, but when the width of the text field is not properly limited, it doesn't help much...

Also: we could consider replacing all uses of `Text.WordWrap` with `Text.Wrap`, because the latter allows wrapping in the middle of a word in "emergency" cases (word longer than available line length). The former would put words that are too long still on one line, and either clip them or let them just go outside the boundaries of the `StyledTextLabel`. I did not make this change here, but would be happy to do so if we decide it is desired.

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by abariska** [comment]
@cbjeukendrup I'm not sure it's a real case when word longer than current line length (after fix). So, I'd leave it as was fixed for now.

**Comment by abariska** [comment]
🟢 **TESTED**
Please, merge to master

**Comment by cbjeukendrup** [comment]
> @cbjeukendrup I'm not sure it's a real case when word longer than current line length (after fix). So, I'd leave it as was fixed for now.
> Please, add a note about what is the symbol limit for a line?

The maximum number of characters per line is not specified; instead, it is limited by the width. For tooltips, we specify a maximum width of 300px, for info/warning/error dialogs it is 420px.

**Comment by cbjeukendrup** [comment]
Rebased. @RomanPudashkin, I think this PR is already ready to go (reviewed & tested)

**Pull request merged**
