### PR TITLE
fix #281503 : enable compilation with make on macOS

### PR DESCRIPTION
**Pull request by AntonioBL**
Resolves: https://musescore.org/en/node/281503
This PR enables compilation of MuseScore under MacOS without installing the full XCode IDE, but only the command line tools.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ N/A ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by AntonioBL** [comment]
This PR adds two pairs of make commands:
release-cl  + install-cl  for release build
debug-cl  +  installdebug-cl for debug build

The compilation requirements are the same as usual Mac compilation, but instead of installing XCode one should run `xcode-select --install` and select not to install XCode (see for example http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/ )

**Comment by riaanvn** [comment]
For someone who already has Xcode installed, do you have instructions for switching from using Xcode to using command-line tools / make?
How would I know that it is safe to delete Xcode?

**Comment by AntonioBL** [comment]
I think you could use command-line tools and make even when keeping Xcode, by simply switching the target of xcode-select, see here:
https://macops.ca/developer-binaries-on-os-x-xcode-select-and-xcrun/
apparently, it seems possible to switch to using pure command-line tools by setting DEVELOPER_DIR environment variable to /Library/Developer/CommandLineTools, see at the bottom of that page. (I remember after deleting Xcode I had to use xcode-select to switch to the correct folder since it was keeping the old Xcode value).

**Comment by Jojo-Schmitz** [comment]
rebase needed (?)

**Comment by Jojo-Schmitz** [comment]
Maybe rebase to 3.x?

**Pull request merged**
