### PR TITLE
fixed #21657: Crash while typing in palettes search

### LINKED ISSUE #21657: Crash while typing in palettes search
### Issue type

Crash or freeze

### Bug description

Sometimes, while typing in the search bar in the palettes panel, MuseScore 4.3 crashes.

This has happened to me 5 or 6 times but I can't figure out exact steps to replicate it. It feels random but usually does not happen when using the search right after opening a score.

### Steps to reproduce

1. Have a score open for a while, do some engraving
2. Open palettes
3. Type in the search bar
4. Crash

### Screenshots/Screen recordings

_No response_

### MuseScore Version

MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: macOS 14.1, Arch.: x86_64

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #21657

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by zacjansheski** [comment]
I can still crash it

https://github.com/musescore/MuseScore/assets/69917893/7c787915-8981-4d5e-907f-3f0dbd9286a6

**Comment by zacjansheski** [comment]
[SearchCrash.zip](https://github.com/musescore/MuseScore/files/14450544/SearchCrash.zip)

**Comment by krasko78** [comment]
Note the **if-else** on lines 58-64. If a tooltip is already visible, it will enter the **else** and **connect** will not be executed. I'd move the **connect** before the **if**.

Also, **show()** overwrites **m_item** without disconnecting the old item first. If you start hovering over the palette items quickly before the 500ms elapse to display the tooltip, a lot of connects will accumulate eventually. So I'd also add this:

```
    if (!toolTipNotOpened) {
        disconnect(m_item, &QObject::destroyed, this, &QmlToolTip::doHideOnDestroyed);
    }
```
before
`    m_item = item;`

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/21657 FIXED

**Pull request merged**
