### PR TITLE
fix #291758 - [Musicxml Export] - Tbox and Vbox after measure 1 don't export

### PR DESCRIPTION
**Pull request by lvinken**
… export

Resolves: https://musescore.org/en/node/291758

Export text frames as MusicXML words and all vertical frames as MusicXML credit-words. Popular request, also required to better support Braille transcriptions.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by dmitrio95** [comment]
Could these new test files be added to `tst_mxml_io.cpp` to have the relevant tests running on Travis?

**Comment by lvinken** [comment]
I think that could indeed be done, although I am not quite sure yet how much effort would be required or when I could do that.

**Comment by dmitrio95** [comment]
Doesn't the existing [`mxmlMscxExportTestRef`](https://github.com/musescore/MuseScore/blob/981f114c36dd0eb598867e319131504df8d548ad/mtest/musicxml/io/tst_mxml_io.cpp#L296) already do what is needed for these tests?

**Comment by lvinken** [comment]
Indeed you are right, I had forgotten about that. In my defence, that function was implemented by Igevorse five years ago :-). Will make the required changes, squash the commits and do a forced push.

**Comment by lvinken** [comment]
Done, also included some cleanup and a rebase.

**Pull request merged**
