### PR TITLE
Musicxml pull parser 3

### PR DESCRIPTION
**Pull request by lvinken**
Initial implementation of MusicXML pull parser, to be merged a.s.a.p. after 2.0. Mostly works (91 out of 95 test cases pass). Grace notes after and user accidentals still to do. Recordare testfiles also show a few (minor ?) issues.

DOM parser still present in source code, but only pull parser is compiled in.

Will repair remaining issues after 2.0 and also do further code cleanup.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@lvinken: could you please also check #1887?

**Comment by lasconic** [comment]
Also I did some last minute fixes in export 
https://github.com/musescore/MuseScore/commits/master/mscore/exportxml.cpp

and import 
https://github.com/musescore/MuseScore/commits/master/mscore/importxml.cpp

That we might want to backport to this new implementation.

**Comment by Jojo-Schmitz** [comment]
Like 9fce6c0, 6a80e2e and 36b4f4f ...

**Comment by lvinken** [comment]
As the pull parser implementation is (of course) import only, that does not affect exportxml.cpp.

With respect to the changes listed:
- #51601 (=9fce6c0): the fix is in a part of code that was changed and is no longer applicable. The attached file crashes the pull parser with a null-pointer access, which I will fix later
- 6a80e2e: exportxml only, no issue
- 3b4f4f: fix is already partly present in the new code, I will add the remainder

After integration of the pull parser I will check that all recent changes in importxml are copied into it. Note that I will have to do bug hunting anyway: it is about 8000 lines of partly new code, these cannot be bug free.

**Comment by Jojo-Schmitz** [comment]
Seems a rebase is needed now?

**Comment by lvinken** [comment]
Looks like it, but I am afraid this exceeds my Git working knowledge, so I will have to leave it up to @lasconic to determine how to proceed.

Note that, as about 99.9% of this PR is in new files, I find it difficult to imagine a complicated merge.

**Comment by Jojo-Schmitz** [comment]
do a `git fetch upstream; git rebase upstream/master`, check and fix conflicts, if there were any and have been fixed to a `git rebase --continue`, then a 'git push -f`

**Comment by Jojo-Schmitz** [comment]
do a  git fetch upstream; git rebase upstream/master , check and fix conflicts, if there were any and have been fixed to a  git rebase --continue , then a 'git push -f`
My guess it it conflicts with 38eeee0

**Comment by lvinken** [comment]
Rebased (no conflicts), fixed part->instrument() calls and did a "push -f". Hope this is OK now, please contact me if not. Passes 92 out of 95 tests, remaining issues are minor. Failing tests commented out.

Code review note: I still need to do some cleanup (removing duplicate code, adding comments). Due to  the possibility of conflicts my strategy is to get it working correctly first, merge a.s.a.p. and cleanup later.

**Comment by lvinken** [comment]
Once again, Travis failed on a completely unrelated file:

make[3]: *** [mscore/CMakeFiles/mscore.dir/qrc_musescorefonts-Bravura.cpp.o] Error 4
make[3]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)

**Comment by Jojo-Schmitz** [comment]
you can get round that be `git commit --amend`, just exit the editor that comes up without changing the commit message, `git push -f`. May be needed multiple times until Travis is happy...

**Comment by lasconic** [comment]
Travis went through now and it fails on the tst_mxml_io. 
If it's expected, could you comment out the non working tests, or fix them, or comment the pullparser flag so that we still use the former parser?

**Comment by lvinken** [comment]
The tst_mxml_io failure is unexpected. Note that I only test using the iotest* scripts, simply because tst_mxml_io apparently goes into a busy wait forever on Mac (100% CPU load, never completes the first test case, stack trace shows it hanging while reading the MusicMXL schema). This never happened on Linux, but on Mac this means I cannot verify tst_mxml_io works at all and do not have a working Linux system anymore. Never found the solution for the hangup :-(.

My preferred scenario would be to fix tst_mxml_io, but I would need to get the detailed logging. For now Travis only tells me:
The following tests FAILED:
	 39 - tst_mxml_io (Failed)

Of course I can set the flag to compile the DOM parser, but while that allows merging in the code (which is useful in itself), it does not help me to reach the goal of obsoleting the DOM parser.

**Comment by lasconic** [comment]
OK. 
I ran the tests on Linux: https://gist.github.com/lasconic/20638b8be895df1d780c
On Mac OSX 10.10.2, I have no problem running tst_mxl_io within XCode 6.2, at least for master. Do you have the same config? I'll try to run the tests on your branch.

**Comment by lvinken** [comment]
Thanks. I am running on OSX 10.7.5, Xcode 4.6.3 (and no intention to upgrade on short notice). Running tst_mxml_io never worked for me (same issue). If I comment out XML schema validation, tst_mxml_io runs but I get a different result: all tests OK except TestMxmlIO::helloReadCompr() which cannot load the mxl file.

Am still investigating. No explanation yet for the "creator" issue.

**Comment by lvinken** [comment]
Suspect issue is caused by different order of evaluation of setMetaTag parameters between OS X and Linux (mscore/importmxmlpass1.cpp line 978: evaluation of _e.attributes() before _e.readElementText() works ok, the reverse order would lead to a missing "creator" tag). Waiting for Travis results.

**Comment by lasconic** [comment]
Relaunched travis... (twice...)
Tests are passing on Mac OSX and on Linux.

**Comment by lvinken** [comment]
:-) Thanks for your help. Let me know if there is anything else I can do.

**Pull request merged**
