### PR TITLE
Misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -I ../musescore-whitelist.txt --skip="./share/locale,./thirdparty"`  
Whitelist:  
```
cann
clas
dur
foto
nd
ois
ot
pres
possibile
snaped
strack
tage
te
thru
valu
```

### CODE REVIEW

**Comment by luzpaz** [comment]
Please also review f94ed4f (it has some source typos)

**Comment by Jojo-Schmitz** [comment]
See https://travis-ci.org/musescore/MuseScore/jobs/363258966#L2403-L2423 , there are more places where you need to fix that particular typo

**Comment by Jojo-Schmitz** [comment]
Seems you'd still need to sign the  [CLA](https://musescore.org/cla)

**Comment by lasconic** [comment]
Already signed as "Kunda1". So far, @luzpaz only contributed PR with typo fixing. I agree with @anatoly-os that it's more disturbing than useful. I close this PR.

**Comment by luzpaz** [comment]
fair enough

**Comment by Jojo-Schmitz** [comment]
I think regardless there's some merit to it.

**Pull request closed without merging**
