### PR TITLE
Remove showTours from advanced preferences

### PR DESCRIPTION
**Pull request by Howard-C**
Because it is already present in "General" tab.

### CODE REVIEW

**Comment by mike320** [comment]
This PR is a bad idea, see https://musescore.org/en/node/295618#comment-950914

**Comment by Jojo-Schmitz** [comment]
Why? I guess you're missunderstanding what this is about, it removes a setting from being shown in the Advanced preferences that is shown in the Common prefereces already. It is not about changing that setting in any form or shape.

**Comment by dmitrio95** [comment]
Actually, regarding this PR, I wonder why don't we show all preferences in the "Advanced" tab. It seems to have been suggested even in [the initial plan](https://musescore.org/en/node/264400) for implementation of this Advanced tab. So I am not sure whether it actually makes sense to remove settings from that tab.

**Comment by Jojo-Schmitz** [comment]
That's a fine idea too. So either remove this one, or add all others.

**Comment by Howard-C** [comment]
But advanced preferences doesn't really show settings that are clearly visible in other tabs, and I don't see the point of having the settings being duplicated.

**Comment by dmitrio95** [comment]
The point is to have a single place where you can adjust any settings that are adjustable at all, similarly to what does `about:config` page in Firefox. Usually people would use other places to change settings, but if some users want to fine-tune some parameters it would be not very natural to let them control some settings from this "Advanced" settings list and force them to search through other places to adjust another setting that happens to be exposed elsewhere. For example, this seems to be the case for colors already: one can adjust colors of voices and even some mysterious `score/defaultColor` which would paint all the new elements in a score to arbitrary color, but has to go to "Canvas" tab to adjust the background color for all this. This is not a serious issue, of course, but still it seems more logical to have a place which contains all settings rather than a place which contains settings which didn't happen to appear anywhere else.

**Comment by Howard-C** [comment]
Done.

**Comment by MarcSabatella** [comment]
My understanding is the downside of trying to put them *all* in was that some settings require more complex UI elements (eg, the shortcuts, MIDIremote control).  Of course, arguably those belong in a different dialog anyhow.  But at least, all simple values could be in advanced, that wouldn't bother me.

**Comment by Jojo-Schmitz** [comment]
**All** settings, no just all startup ones

**Comment by Howard-C** [comment]
> **All** settings, no just all startup ones

Are you sure? Change all `showInAdvanced = false` elements to `true`?

**Comment by Jojo-Schmitz** [comment]
It is either all or just those that are not available elsewhere.
If all, we can get rid of that `showInAdvancedList`altogether.
But as many of those are not fit (yet), better postpone that and go for the original plan for now and just remove that one that is available elsewhere?

**Comment by Howard-C** [comment]
> But as many of those are not fit (yet), better postpone that and go for the original plan for now and just remove that one that is available elsewhere?

I agree with that.

**Comment by Howard-C** [comment]
So it's removed from 3.3.3! What's the next move? Are we still going to remove showTours from advanced preferences? Or first improve the layout of advanced preferences page to make all preferences capable of displaying in it?

**Comment by Jojo-Schmitz** [comment]
rebase needed

**Comment by Jojo-Schmitz** [comment]
unfortunatly a new rebase (or restarted build) is needed

**Comment by Howard-C** [comment]
Since an overall code style change (and formatting) is imminent, I'm closing this one.
I'll create another one for only the "Remove showTours" change.

**Comment by Howard-C** [comment]
Superseded by #5903.

**Pull request closed without merging**
