### PR TITLE
Fix #302826: MusicXML export of compound articulations

### PR DESCRIPTION
**Pull request by dmitrio95**
Resolves: https://musescore.org/en/node/302826

Allows MusicXML export of those compound articulations that do not have direct MusicXML equivalent. This is done by exporting them as multiple single articulations, like it is proposed in the issue description.

Since there are no changes in import of such articulations (multiple articulations are not merged to compound ones here), a test case can be added after other MusicXML export tests are re-enabled (see #8513).

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@iveshenry18 wouldn't that be something for 3.6.2_backend too?

**Comment by Jojo-Schmitz** [comment]
It does collide with  #8190 though

**Comment by dmitrio95** [comment]
Yes, indeed it does, and that fix also covers merging articulations on import. Maybe it's better to cherry-pick that fix to master then? It would just be needed to add few more compound articulation types (types combined with `SoftAccent` are not present in #8190).

**Comment by iveshenry18** [comment]
@Jojo-Schmitz, we may not need this for 3.6.2_backend, since that branch is primarily concerned with importing. However, for porting to master, I do think cherry-picking #8190 and adding any compound articulations I may have missed would be a good strategy

**Comment by Jojo-Schmitz** [comment]
Like adding these to your PR?

            case SymId::articStaccatoSoftAccentAbove:
            case SymId::articStaccatoSoftAccentBelow:
                  return { "staccato", "soft-accent" };
                  break;
                  
            case SymId::articSoftAccentTenutoAbove:
            case SymId::articSoftAccentTenutoBelow:
                  return { "soft-accent", "tenuto" };
                  break;


            case SymId::articSoftAccentTenutoStaccatoAbove:
            case SymId::articSoftAccentTenutoStaccatoBelow:
                  return { "staccato", "soft-accent", "tenuto" };
                  break;

**Comment by iveshenry18** [comment]
Yep!

**Comment by dmitrio95** [comment]
OK, then I guess this pull request is not needed. I didn't know this had already been fixed in another branch.

**Comment by Jojo-Schmitz** [comment]
Would now also fix #16748

**Pull request closed without merging**
