### PR TITLE
fix mtests for PR #2202

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Hopefully got it all right...
Without PR #2202 being merged first those tests will of course fail, and the failure should look just the opposite of the failures of that PR

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Thanks for tackling this!  I've merged you branch into mine and pushed it back, which is not something I've done before but I think I did it right.  We'll see if Travis likes it.

**Comment by MarcSabatella** [comment]
Apparently so.  I'm on it.  Thanks again for the big head start!

**Comment by Jojo-Schmitz** [comment]
fixed them now, I hope

**Comment by MarcSabatella** [comment]
The fixed tests are now incorporated in my PF #2202, which is merged.

**Pull request closed without merging**
