### PR TITLE
fix #288474: Particular .mscz file crashes MuseScore

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Not sure at all this is the right way to fix this, but at least it does prevent the crash.
The root cause for the problem is probably somewhere else.

### CODE REVIEW

**Comment by dmitrio95** [comment]
Similar changes in layout.cpp (but not in measure.cpp) seem to have been done also in #4730, maybe this PR is better to be merged after that one.
And, of course, it would be good to find the reason of having tremolos without the second note, although having these checks to avoid crashes in such cases should still be good.

**Comment by Jojo-Schmitz** [comment]
OK, I see. Will retest and rebase this here then after that other PR got merged

**Comment by MarcSabatella** [comment]
FWIW, I had seen the same crash reported earlier (on the forum, I think), and I was able to verify that this change allowed the file to load, but I never submitted a PR because I had no confidence that the score would actually be OK after that.  On the other hand, the change is obviously harmless, so when I when found myself working on that same section of code for #4730, I decided to toss those checks in.

**Comment by Jojo-Schmitz** [comment]
I needed at least one further change (to libmscore/measure.cpp), but not another you seem to have added (to libmscore/layoutlinear.cpp).

**Comment by MarcSabatella** [comment]
No doubt your change to measure.cppis needed too, I added the checks I did because I was looking right at those lines and remembered it.  The layoutlinear change would presumably be needed if the score was saved in continuous view.

**Comment by Jojo-Schmitz** [comment]
OK, I'll 'steal' that one and add to this PR here, just for completeness, it shouldn't cause merge conflicts.

**Comment by Jojo-Schmitz** [comment]
All changes needed are now also in #4730, so let's close this one here

**Pull request closed without merging**
