### PR TITLE
fix #46736: spanner end cannot be set to note in voice > 1

### PR DESCRIPTION
**Pull request by MarcSabatella**
Ending a segment-based line (other than slur) at a note in voice > 1 hasn't worked properly for some time now.  The recent fix for http://musescore.org/en/node/28446 made the problem more apparent - the effect is that not only are these notes skipped while editing a line, but you also can't back up past a note in voice > 1.

The problem turns out to have two aspect:

1) When findCRinStaff() (called by computeEndElement() and nowhere else) looks for a chordrest in the specified staff at/before the specified tick, it returns the *first* chordrest it finds for that staff/segment (eg, preferring voice 1 over voice 2), rather than the *shortest*.  If the note in voice 1 is longer than a note in voice 2, the _endElement computed is thus too long, and the code added to fix 28446 "corrects" the length of this line, lengthening it to the full value of the voice 1 note.

2) Before that change, it was possible to move the end point through notes in voice 2, but the layout would still act as if the line needed to extend through the duration of the voice 1 note.  That's because linePos() relies on the value of track2() to help it calculate how far to extend the line, which is not meaningful for these types of lines (they always "belong" to voice 1).

I fixed both of these problems.  findCRinStaff() now returns the shortest chordrest it finds in the appropriate staff/segment.   And linePos() now find the correct end point for the line based on tick2(), rather than trying to deduce it from endElement() and track2().  I have verified it fixes the problem at hand, makes the layout work, and 28446 remains fixed.

EDIT: It appeared at first my code here may have crashed one of the vtests; I am investigating that but will have limited time today.  I am pretty sure I was wrong, though - I now believe there was no crash in the vtest, only one of those mysterious crashes on exit I occasionally see running in the debugger that left a crash report on my system.

Meanwhile, I am submitting the code and my commentary here.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
The crash was actually something I've been meaning to report formally - running MuseScore in converter mode crashes, every time - it has since the new help facility was added.  Will report separately.

Meanwhile, I've fixed a crash in computeEndElement(), seen in corrupt scores with bad tick2() values, and added a vtest for my change.  Everything should be good to go from my perspective.  But of course, I welcome review!

**Comment by lasconic** [comment]
I just restarted travis.

@wschweer spanner management :) Can you take a look to this PR ?

**Comment by lasconic** [comment]
A week as passed. This fix prevents a crash when importing MusicXML. I merge it. Let's see how it behaves in the wild.

**Comment by MarcSabatella** [comment]
FWIW, I was pretty confident about this change.  I saw a couple of other comments in forums that I am pretty sure are addressed by this as well.  @mgavioli : I am also wondering about a comment you made on IRC about a possible issue with the new glissando implementation, something about read() and maybe something about overlapping glissandi, but I wasn't sure of the context.  Anyhow, I wonder if maybe this also relates to that.

**Pull request merged**
