### PR TITLE
Fix the crash on launch on Windows

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #15235
Resolves: https://github.com/musescore/MuseScore/issues/17273
Resolves: https://github.com/musescore/MuseScore/issues/17454
Resolves: https://github.com/musescore/MuseScore/issues/17089
Resolves: https://github.com/musescore/MuseScore/issues/16947
Resolves: https://github.com/musescore/MuseScore/issues/16309
Resolves: #16950

Since the crash only occurred in builds with an installer, here is a build with an installer from this branch: https://github.com/musescore/MuseScore/actions/runs/4903046436 (not the portable but the other one)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
In the wasapi driver code, we work a lot with exceptions that are thrown and caught. But in builds with an installer, exceptions were never caught, even when they are properly wrapped in a try/catch block. This was not limited to exceptions from the wasapi driver, but experiments showed that it also happened with for example a std::runtime_exception. So somehow exception handling was broken. 

Since it seemed so strange that this was caused by the packaging, we (=me and two very helpful community members) looked at the build process, but really everything was identical between builds with and without installers. 

I also tried first packaging as a MSI installer and then packaging the same build as a zip file too, both in the same GitHub Actions run. The version from the zip file worked, so it was really not that the build itself was wrong. So the problem had to be in the packaging. I feared that WIX somehow broke the build when packing it into the MSI, so I even started looking at the source code of WIX, but decided to spend not too much time on that because I wasn't even really sure that it was the culprit. 

Then I tried to copy more things into the artifact; not only the WIX logs, but also other intermediate files. I found that in these intermediate files, it was broken, so the problem was _not_ the packaging into the MSI. 

So I scrutinised the packaging scripts once more, and then my attention was caught by that line about stripping. I removed it, and that did the job. 

Those NSIS files that I removed are unrelated, but they are unused so I cleaned them up.

**Review by igorkorsukov — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
@DmitryArefiev I'm not sure how much you can test about this PR, since IIRC you could not reproduce the crash initially. But I still wanted to inform you :)
In #15235 and #17273, some users who did experience the crash before, have reported that it seems to work well for them.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup It's great you found a solution! I tried an installer from https://github.com/musescore/MuseScore/actions/runs/4903046436 - all good on my side. But it's a TEST version. Let's merge it to master, then create a release version of installer (stable build mode) and ask reporters of related bugs to check it again.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Oh I see, that makes sense. But on the other hand they can have a build without crash in a regular location :) 
OK let's leave as it is now and create a stable build if users with crash will ask it.

**Pull request merged**
