### PR TITLE
Added connector lines for slurs

### PR DESCRIPTION
**Pull request by HemantAntony**
*(short description of the changes and the motivation to make the changes)*

This commit creates connector lines to the nearest object when you drag a slur from Palettes

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by HemantAntony** [comment]
@bkunda This implements a small part of #9964. This my first time doing things in engraving which is why I created this PR to know if there is anything I can improve on

**Comment by Jojo-Schmitz** [comment]
A rebase should fix the failing MusicXML tests

**Comment by Tantacrul** [comment]
This is very promising!

One thing that would massively elevate it and significantly reduce confusion is if objects only try to snap to things that are relevant.

For example, in this video, the slurs should avoid trying to attach to blank measures. I understand they are using the same logic as hairpins... but I think there will be a few items that will need tweaked logic to make sure they don't try to snap to too many things that will produce a null result.

https://user-images.githubusercontent.com/21022311/165522741-c4b7b3a7-4b27-40ee-a4da-c7e1c1f660e0.mov

**Comment by HemantAntony** [comment]
I did think of that. But I though hairpins also had wrong logic. It didn't make sense to me when I added a hairpin to a rest

**Comment by Jojo-Schmitz** [comment]
What about "open ended slurs"? Not every slur needs to start or end on a note/chord.

**Comment by HemantAntony** [comment]
> @HemantAntony - yes. perhaps we could remove the auto-snapping to empty measures across the board and see what that's like?

Okay, I'm working on a solution now. It should find the nearest element that can accept the required element (in this case, a slur)

**Comment by HemantAntony** [comment]
> @HemantAntony - yes. perhaps we could remove the auto-snapping to empty measures across the board and see what that's like?

Okay, I'm working on a solution now. It should find the nearest element that can accept the required element (in this case, a slur)

**Comment by HemantAntony** [comment]
I'm closing the PR as this issue is a bit difficult for me

**Pull request closed without merging**
