### PR TITLE
fix #116771: Note's dot's visibility is incorrect when toggling visibility with note and dot selected

### PR DESCRIPTION
**Pull request by mattmcclinch**
Resolves: https://musescore.org/en/node/116771.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I guess this replaces #2741

**Comment by dmitrio95** [comment]
Could you please add a comment indicating that note dots visibility are handled inside `Note::setProperty`? Otherwise I believe the purpose of this check may be misunderstood without knowing this issue's context.

**Comment by mattmcclinch** [comment]
@dmitrio95, I added the comment like you asked.

**Comment by Jojo-Schmitz** [comment]
Travis CI and AppVey fail due to a superfluous `;` in bb039d5.

**Comment by dmitrio95** [comment]
@mattmcclinch, thanks!

**Pull request merged**
