### PR TITLE
Home/Score/Publish tab width should be determined by text's width when bold (Draft Attempt)

### PR DESCRIPTION
**Pull request by daijingz**
Resolves: #22055 

Adding a font metric to the main toolbar. Have not been tested in my personal machine.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [ ] The title of the PR describes the problem it addresses
- [ ] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [ ] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ ] There are no unnecessary changes
- [ ] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by daijingz** [comment]
> Resolves: #22055
> 
> Adding a font metric to the main toolbar. Have not been tested on my personal machine. (Because of some strange individual compilation errors in my PC.)
> 
> * [ ]  I signed the [CLA](https://musescore.org/en/cla)
> * [ ]  The title of the PR describes the problem it addresses
> * [ ]  Each commit's message describes its purpose and effects, and references the issue it resolves
> * [ ]  If changes are extensive, there is a sequence of easily reviewable commits
> * [ ]  The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
> * [ ]  There are no unnecessary changes
> * [ ]  The code compiles and runs on my machine, preferably after each commit individually
> * [ ]  I created a unit test or vtest to verify the changes I made (if applicable)

**Comment by daijingz** [comment]
@cbjeukendrup I guess this is caused by the previous command `git rebase`, since at that time I saw some seems-abnormal behaviours. Now the code is on this PR, and you can see what is going on.

If you see there is no change or you observe any compilation errors, please inform me ASAP.

**Comment by daijingz** [comment]
> @daijingz Two things about Git usage:
> 
> * You still haven't managed to do a proper rebase, because there's still a lot of merge commits. Just run `git pull --rebase upstream master; git push -f`.
> * You're still creating PRs from your master branch, which is inconvenient if you want to work on multiple tasks. Best practice is to create a separate branch for every task you work on, and never commit to your master branch directly.

No problem, I am creating a branch now. Previously I created some branches, but there are some inconsistencies on displaying. May be there are some problems elsewhere.

**Comment by cbjeukendrup** [comment]
@daijingz About the build problems you were experiencing: turns out you were not the only one. There was a recent PR that probably fixes it: https://github.com/musescore/MuseScore/pull/22156
So if you rebase yet again using the command I told you about earlier, it should compile again on your machine!

**Comment by daijingz** [comment]
@cbjeukendrup I don't know why the MuseScore terminal terminates because there is no error message. 
This is the end of Application Output:
14:51:56.549 | INFO  | main_thread     | App::run        | activeThreadCount: 0
14:51:56.586 | ERROR | main_thread     | WasapiAudioClient::setStateAndNotify | 
14:51:56.587 | ERROR | 8432            | WasapiAudioClient::setStateAndNotify | 

14:51:56.606 | DEBUG | main_thread     | WinMidiOutPort::disconnect | Disconnected from -1

14:51:56.607 | WARN  | main_thread     | WinMidiInPort::stop | already stoped
14:51:56.607 | DEBUG | main_thread     | WinMidiInPort::disconnect | Disconnected from -1

14:51:56.675 | INFO  | main_thread     | main            | Goodbye!! code: -1
14:51:56: D:\MuscScore\MuseScore\builds\Desktop_Qt_5_15_2_MSVC2015_64bit-Debug\install\bin\MuseScore4.exe exited with code -1

**Comment by daijingz** [comment]
Sorry everyone, there are some non-personal issues taking place on my PC, and I am going to go to repair stores tomorrow. I will get back tomorrow.

**Comment by RomanPudashkin** [comment]
Unfortunately, this solution is a duplicate of https://github.com/musescore/MuseScore/pull/22132 (which was open before this PR). Let's keep only 1 PR per issue...

**Pull request closed without merging**
