### PR TITLE
fix #285174, fix #287283: add opengl32sw.dll as a (last) fallback

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
if hardware support is missing and angle fails

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Seems this issue comes up time and time again, often in disguise though.
Would be good to include this DLL in 3.1 IMHO, I guess Qt provides it for a reason ;-)

**Comment by Jojo-Schmitz** [comment]
Seems this is needed for AppImage too, see https://musescore.org/en/node/281616#comment-914202

**Comment by dmitrio95** [comment]
> Seems this is needed for AppImage

Isn't this library shipped only for Windows?

Also, could some builds of this branch be tested by people who were not able to launch MuseScore previously, to make sure adding this library really helps?

**Comment by Jojo-Schmitz** [comment]
Yes, Windows only. Sorry, I meant Portable App, not AppImage

**Comment by Jojo-Schmitz** [comment]
Yes, Windows only. Sorry, I meant PortableApp, not AppImage.
For testers we'd need to (re-) build this with artifacts creation switched on

**Comment by Jojo-Schmitz** [comment]
Yes, Windows only. Sorry, I meant PortableApp, not AppImage.
For testers we'd need to (re-) build this with artifacts creation switched on, but there have been reports from users (and @AntonioBL too), that adding this dll (manually) helped.

**Comment by AntonioBL** [comment]
To be precise, I found that in a vanilla Windows 7 virtual machine (  https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/  ), the tentative MuseScore Portable I built crashes as soon as the start center tries to open. With this dll the startcenter opens, but all the online content is simply a black frame. This happens also for the "save online" dialog (i.e. it opens only with this dll, but it shows as a black frame).
So in that environment it prevents the crash, but the online functionality is still not present.

**Pull request merged**
