### PR TITLE
fix #303426: Editable elements still edited after entering Note Entry mode

### PR DESCRIPTION
**Pull request by aufarg**
While the issue reported is about slur, the problem is actually not
specific to slur and it happens to any kind of elements with Editable
EditBehavior on normal mode. This happens if we click the element, which
makes the current EditElement to be the current ScoreView edit element,
and then immediately enter Note Entry mode. On startNoteEntry function,
the ScoreView edit element is not changed so previous edit input will
still edit the edit element.

This commit fixes the problem by setting the edit element to the
selected note upon entering Note Entry mode.

Resolves: https://musescore.org/en/node/303426

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/WorkflowAndGuidelines/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by vpereverzev** [comment]
Looking for rebase on 3.x

**Comment by Jojo-Schmitz** [comment]
Which is 'just' about the meanwhile removed revision.h, which should not have been part of this PR anyhow

**Comment by Jojo-Schmitz** [comment]
should be easy to cherry-pick that one-line change to master __and__ 3.x

**Comment by Jojo-Schmitz** [comment]
@vpereverzev If you pick it for master, I'll pick it for 3.x ;-) Deal?

**Comment by vpereverzev** [comment]
> Which is 'just' about the meanwhile removed revision.h, which should not have been part of this PR anyhow.
> Should be easy to cherry-pick that one-line change to master __and__ 3.x.
> @vpereverzev If you pick it for master, I'll pick it for 3.x ;-) Deal?

Heh, agreed

**Comment by vpereverzev** [comment]
> > Which is 'just' about the meanwhile removed revision.h, which should not have been part of this PR anyhow.
> > Should be easy to cherry-pick that one-line change to master **and** 3.x.
> > @vpereverzev If you pick it for master, I'll pick it for 3.x ;-) Deal?
> 
> Heh, agreed

Ah, it's no more actual for master because it touches old GUI code (scoreview.cpp)
So I'll just port it in 3.x directly

**Pull request closed without merging**
