### PR TITLE
Staff visibility

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
* Port of #8430, part 1, "Default HideMode::INSTRUMENT XML import":
    Since HideMode::AUTO behaves in uncommon ways for most scores (hiding empty staves in a grand staff), this changes the hideWhenEmpty to INSTRUMENT when creating the Staffs upon import. In the case that a score part has a variable number of staves, it uses this to infer that we do truly want HideMode::AUTO.

* Port of #8430, part 2, "Check spanners when assessing emptiness":
    Previously, a staff's emptiness was calculated based on its note and annotation content. Since this is evaluated before the system was laid out, the system did not have pointers to its SpannerSegments. This commit adds a way to include whether a staff has any spanners (particularly pedal markings and hanging slurs) in assessing emptiness, creating more consistent/expected hiding behavior in HideMode::AUTO.

* Port of #8527:
    This commit tweaks the changes from commit 54ebee4 (which checks for spanners when assessing staff emptiness) and ignores spanners that are "system" spanners (such as voltas or system text). This prevents a false-positive unhiding in the case of such system spanners. Also, it prevents another false positive that occurred when a spanner started on the first tick of the next system.

* Hide staff with subsequent empty measures after (de-)crescendo line (or hairpin) in measure before:
    A regression from the above 2 commits, apparently needed as a hairpin (that ends at a measure (and system) boundary) has its end being recorded in the **next** measure (and system) and, should it really go into the next system, 'harmless' to get ignored there (i.e. still getting hidden), as harpins on otherwise empty measures are pretty meaningless.

VTEST failure expected and demonstrating the need:
staffEmptiness-1 diff

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
As this is an engraving issue/fix, I'd like to summon @oktophonie for a review ;-)

**Comment by Jojo-Schmitz** [comment]
He also approved the PRs I'm porting here, together with @vpereverzev

**Comment by Jojo-Schmitz** [comment]
No opinions on this PR?

**Review by oktophonie — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
(no squashing needed)

**Pull request merged**
