### PR TITLE
percussion_crash

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/19516

### CODE REVIEW

**Comment by zacjansheski** [comment]
Stems are displayed on the wrong side of the noteheads

Screenshot 2023-10-23 at 5 26 08 PM

**Comment by zacjansheski** [comment]
Clicking "Edit Drumset" causes a crash

**Review by Eism — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
> Stems are displayed on the wrong side of the noteheads
> Screenshot 2023-10-23 at 5 26 08 PM

@zacjansheski I've logged that separately per Roman's request - #1981. 
Also, you can test the last PR's build briefly just to check I didn't miss anything. Thanks!

**Comment by DmitryArefiev** [comment]
Tested #19516 on Win10, Mac13.6, LinuxUbuntu 22.04 - **FIXED**  

Found another crash with Edit drumset invoke but it also happens in 4.0. Logged as #19812

**Comment by Gai-Luron** [comment]
Hello,
When are you going to fix this issue? It's not easy to work with the master version. Even though we shouldn't work with it, it's easier to find bugs and help the community.
Thanks in advance
Robert

**Comment by cbjeukendrup** [comment]
@Gai-Luron It should be fixed again with https://github.com/musescore/MuseScore/pull/20058 :)

**Pull request merged**
