### PR TITLE
Fix Courtesy Clef visibility for most (simple) cases

### PR DESCRIPTION
**Pull request by AntonioBL**
Resolves:
https://musescore.org/en/node/280584
https://musescore.org/en/node/298638
https://musescore.org/en/node/286497
https://musescore.org/en/node/151121

These commits resolve a couple of courtesy clef visualization bugs when "show courtesy" property is unchecked for the clef, namely clef change and visualization of non-courtesy clef. It also fixes the behavior of inspector for multiple selected clefs when "show courtesy" is checked/unchecked.
The case of multi-measure rest is not covered by this PR.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by AntonioBL** [comment]
Actually, regarding the point "I made sure there are no unnecessary changes in the code", visibleInt could be substituted by a simple bool with value false, changed (to true) only if at least a visible clef is present. However, I wanted to check with a debug message a case which in principle should never happen.

Additional note: I can't find where the position of a measure rest is set: With this PR there is still a minor quirk with a measure clef change in the middle of a system when the preceding measure (i.e. the one showing the clef) contains a measure rest. If the "show courtesy" is checked or not checked, the clef does not disappear as it should, but the measure rest is slightly horizontally shifted. There are no horizontal movements (as it should be) when other kind of notes or rests are present in that measure.

Additional note n. 2: I could not disable the courtesy segment for hidden courtesy clefs, to avoid hiding all clefs in the case of multiple staves and concurring clef changes (for example one staff with hidden courtesy and one staff with visible courtesy) and to avoid problem during file saving (disabled segments are not written to a file).

**Comment by MarcSabatella** [comment]
The code to center the measure rest is in Measure::stretchMeasure(), which is where the positions of segments and elements are set after calculating a target width for the measure.

I have looked at the code changes only briefly, they seem to be on the right track, but I would just urge some caution as this part of the code has proved particularly "fragile" - lots of fixes to one thing breaking something else etc.

**Comment by AntonioBL** [comment]
Thank you Marc. I found that the element shape was being updated, but not the shape list of the segment.
Now it works also in the measure rest case.

**Comment by AntonioBL** [comment]
Rebased on top of current master.

**Comment by AntonioBL** [comment]
And rebased again.

**Pull request merged**
