### PR TITLE
Update license headers

### PR DESCRIPTION
**Pull request by BrownianNotion**
Resolves: #18710  

Updated license headers. Wasn't sure about copyright year so I defaulted to 2024. Note that some files not listed in the original issue (eg. `sandbox/engraving/log.h`) have the correct license but an old copyright year.

TODO:
- [x] Remove `===` lines and replace `//` comments with `/**/`

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by cbjeukendrup — COMMENTED** [review]
For consistency with more recently added files, I suggest two things:
- remove those `=====================================================================` lines
- In `engraving/sandbox.h` and `tools/bww2html/mxmlwriter.h`, use `/* */` comments (like for example in `src/app/main.cpp`) instead of `//`. 
(This is useful because some IDEs recognise copyright comments at the top of a file, and when it's a `/* */` comment it is collapsed automatically.)

**Comment by BrownianNotion** [comment]
> For consistency with more recently added files, I suggest two things:
> 
> * remove those `=====================================================================` lines
> * In `engraving/sandbox.h` and `tools/bww2html/mxmlwriter.h`, use `/* */` comments (like for example in `src/app/main.cpp`) instead of `//`.
>   (This is useful because some IDEs recognise copyright comments at the top of a file, and when it's a `/* */` comment it is collapsed automatically.)

Changed! Have left the `===` lines in the .xml files to be consistent with the rest of the file.

**Review by cbjeukendrup — APPROVED** [review]
Thanks, that looks good!

**Comment by cbjeukendrup** [comment]
One more question: what username on MuseScore.org did you use to sign the CLA?

**Comment by BrownianNotion** [comment]
> One more question: what username on MuseScore.org did you use to sign the CLA?

Username was andrewwusyd (my [bio](https://musescore.com/user/67795273) has a url to this github :) ).

**Pull request merged**
