### PR TITLE
allow shortcuts for more ornaments

### PR DESCRIPTION
**Pull request by stevengj**
This PR makes it possible for the user to add shortcuts for many more single-note ornaments; previously, the only ornament one could assign a shortcut to was "trill".  (No new shortcut keys are assigned by default, however.)   The shortcuts preference panel now lists:

ornament-musescore-shortcuts

(The names are taken from the tooltips in the "Ornaments" palette.)

Background: When transcribing baroque music, ornaments are extremely common, and it greatly speeds entry if it is possible to set a keyboard shortcut.  In particular, I often need the "shake" ornament (+), sometimes on one or two notes every measure, and it was frustrating that it was not possible to assign this a shortcut.    But while I was adding a shortcut option for "shake", it seemed worthwhile to add shortcut options for all of the other single-note ornaments that seemed like they might show up frequently in a piece.

- [x] I signed the [CLA](https://musescore.org/en/cla) — user [stevengj](https://musescore.com/user/75936445)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually

(Not sure if there is a way to add tests for this sort of thing?  I didn't see any tests for the existing `add-trill` function, so I assume that they are not needed here.)

### CODE REVIEW

**Comment by stevengj** [comment]
bump?

**Comment by oktophonie** [comment]
Please do not 'bump' issues.

**Comment by cbjeukendrup** [comment]
...except that this is not an issue but a PR :)

From a technical POV it looks good! Now we need approval from the design team.

**Comment by avvvvve** [comment]
Thanks for working on this, @stevengj! There are a few issues I noticed detailed below. Let me know if you have any questions!

### 1. Ornaments added via the shortcut are showing "Articulation" properties rather than showing their specific "Ornament" properties
1. Add an ornament (i.e. a trill) by clicking on it in the palette
2. See that in properties, the section under general is called "Ornament" and there are options for changing the interval of the trill (expected behavior)
3. Now, add an ornament via the shortcut
4. See that in properties, the section under general is called "Articulation" and there are no options to configure the interval (incorrect behavior, see screenshot)

image


The properties need to be correct (i.e. show the "Ornaments" section) when adding ornaments via shortcut.

### 2. "Articulation" hover on palette
When hovering on ornaments in the "More..." popup in the ornaments palette, instead of showing the name, it just shows "Articulation"
Before this PR:
image

This PR:
image

### 3. "Articulation" in status bar
The format of the element name  in the status bar is incorrect (though it is also incorrect in the stable build).

It should be "Ornament: [Name of ornament]"

Before this PR (incorrect):
image

This PR (incorrect):
image

### 4. Naming in the shortcuts list
- For all, change "Add/remove ornament" to "Add ornament". I know it technically does both, but other shortcuts we have that work the same way follow that naming convention (i.e. "Add articulation")
     - Bonus: Do the same for the two "Add/remove bowing: ..." shortcuts. Do not change the "Add/remove" format for shortcuts ending in instruments, page break, section break, and system break(s)
- Change "...:tremblement (Couperin)" to "tremblement appuyé (Couperin)" to match the full element name

**Comment by stevengj** [comment]
@avvvvve, note that the "trill" shortcut existed before this PR.  Do all of the issues you note apply (on `master`) to the existing "trill" shortcut before this PR?  If so, it's an unrelated issue.

**Comment by avvvvve** [comment]
Good catch, it was indeed broken when using the original trill shortcut in master too:
- Properties shows "Articulation" instead of "Ornament"
- Status bar shows "Articulation: Trill" instead of "Ornament: Trill"

I think it's a serious enough bug since you're blocked from accessing the interval properties of ornaments entirely. So yes, it'd make sense to fix that in a different PR, but I'd say doing that first should block merging in all of these new shortcuts. @cbjeukendrup does that make sense to you?

**Comment by cbjeukendrup** [comment]
Yes, that makes sense. @stevengj would you have time to look into these issues first, so that we can revisit this PR after fixing those?

I think issue 2 is caused by the fact that this PR is three weeks old by now, because a while ago that was broken in the master branch too. So that should be fixed automatically after a rebase.

**Comment by stevengj** [comment]
I'm pretty busy over the next few days, but will try to look into it next week, though since I'm new to the musescore codebase I'm not sure how far I'll get.   Will definitely start with a rebase, however.

**Comment by stevengj** [comment]
Actually, it turned out to be pretty easy to fix.  The problem was that it was using `Score::toggleArticulation`, which called `Factory::createArticulation`, when apparently it should have been calling `Factory::createOrnament`.  I added a new `Score::toggleOrnament` function that fixes this, and it seems to fix the issues noted above.

(I also made the requested UI string changes.)

Questions:
* Do you want the new `toggleOrnament` function in a separate PR?
* `toggleOrnament` is almost identical to `toggleArticulation`.  `Ornament` is a subclass of `Articulation`, so in principle I could combine the two, but `Score::toggleArticulation` only knows the `SymId` of the attribute.  Is there a good way to look up whether it is an ornament just from the `SymId`?  (The only way I could think of was to use `nameForSymId` to get the corresponding string, and then check whether it begins with `"ornament"`.  But I didn't see any other code like this, so it didn't seem like an idiomatic technique in your codebase?)
* Is there any way to add a test for this functionality, and for the pre-existing issue with the `trill` shortcut noted above?

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
This is looking good now, thanks very much!

To answer your questions:
- It's fine to keep these commits in this PR. Actually, that makes testing easy, because everything is now (probably) correct all in one PR.
- Of course, code duplication is not ideal, but in this case it's small enough. Other solutions might be adding a `bool isOrnament` parameter, or an `ElementType` parameter, but I think that's not much more elegant. There is currently no central or elegant way to check if something is an ornament or other articulation. We could add that in the future, or perhaps we'll refactor it a bit more to introduce dedicated `ArticulationType` and `OrnamentType` enums instead of working with `SymId` directly (which is sometimes a bit fiddly anyway for SymIds that have `above` and `below` variants...)
- Unfortunately, we don't have automated tests at this level of the code. (We do have a suite of low-level tests in the engraving module, but this PR mostly operates on a higher level.) So there is not much you can do here w.r.t. regression tests, unfortunately.

**Comment by avvvvve** [comment]
@stevengj This looks great on my end! Thanks for turning this around so quickly!

**Review by avvvvve — APPROVED** [review]

**Pull request merged**
