### PR TITLE
Fixes for project properties / meta tags

### PR DESCRIPTION
**Pull request by cbjeukendrup**
- The "subtitle" tag was missing
- A few other tags like "workNumber", "movementTitle", "movementNumber" were lost because they were treated as "standard tags" but not stored in `ProjectMeta`.

Resolves: https://github.com/musescore/MuseScore/issues/17598
Resolves: https://github.com/musescore/MuseScore/issues/19867

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Why isn't this getting merged?

**Comment by cbjeukendrup** [comment]
I don't know, but right now we should not merge it anyway until #19138 is merged, to prevent conflicts

**Comment by Jojo-Schmitz** [comment]
Asking because it just came up again in https://musescore.org/de/node/354094

**Comment by RomanPudashkin** [comment]
Sorry for ignoring it

**Comment by zacjansheski** [comment]
"Movement Number" is cut off

Screen Shot 2023-10-20 at 2 47 01 PM

**Comment by Jojo-Schmitz** [comment]
Being standard tags they shouldn't habe that paper basket icon, or should they?
Also they should be translatable?

**Comment by cbjeukendrup** [comment]
The question is whether they _should_ be standard tags. In MS3, they were apparently, but in MS4 they didn't appear at all. I don't know if there is a reason for that, other than that they were just forgotten. What do we think about this?

**Comment by Jojo-Schmitz** [comment]
As poet is basically there just for backwards compatibility (it has been replace by lyricist a long time ago, IIRC in M2 already), I wouldn't mind loosing it, ot at least not making it a standard tag. Not the others though.

**Comment by Jojo-Schmitz** [comment]
BTW: `sourceRevisionId` is cut off too

**Comment by bkunda** [comment]
> The question is whether they should be standard tags. In MS3, they were apparently, but in MS4 they didn't appear at all. I don't know if there is a reason for that, other than that they were just forgotten. What do we think about this?

I'd say they should be standard tags (if this means they appear like the rest: un-editable by the user, and un-deletable).

**Comment by cbjeukendrup** [comment]
I guess rather unrenameable, right?

**Comment by Jojo-Schmitz** [comment]
Yeah, that makes sense. And translatable

**Comment by bkunda** [comment]
> I guess rather unrenameable, right?

Yes, that's what I meant. Thanks for clarifying @cbjeukendrup!

**Comment by zacjansheski** [comment]
Is it intentional that poet is not "unrenameable"?

Screenshot 2023-11-08 at 11 32 23 AM

**Comment by Jojo-Schmitz** [comment]
As long as Lyricist is unrenamable that's fine. Could also just get removed

**Comment by zacjansheski** [comment]
Tested on Mac OS 14, Ubuntu 20.04.6, Windows 11. Approved
https://github.com/musescore/MuseScore/issues/17598 FIXED
https://github.com/musescore/MuseScore/issues/19867 FIXED

**Comment by cbjeukendrup** [comment]
Yes, poet will no longer be there for new scores, and since it is obsolete, it is no longer considered a standard option, so we allow the user to remove it for existing scores.

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
