### PR TITLE
Change instrument short names—Trb. to Tbn. and Vlc. to Vc.

### PR DESCRIPTION
**Pull request by ZackTheCardshark**
Hi Thomas,

Thank you so much for giving me this opportunity. I did it! ;-)

### CODE REVIEW

**Comment by lasconic** [comment]
Thanks for taking care of the tests failure.
Could you check your git preferences to make sure you have a good email set up for git. If not the commits will not be linked to your account. See https://help.github.com/articles/setting-your-email-in-git/
Would be good if you could add isaacweiss@r123-27-171-108.wccnet.edu and isaacweiss@Isaacs-MacBook.local as emails to your account here https://github.com/settings/emails

**Comment by ZackTheCardshark** [comment]
Where did those email addresses come from? I do have a wccnet.edu address, but it doesn't look like that. And the other one—@Isaacs-MacBook.local—first of all is not a real email address, and second of all suddenly makes me very uncomfortable about my privacy.

**Comment by lasconic** [comment]
Sorry about your privacy. The two addresses were probably generated automatically on the computer where you installed the github client. I assume there is a way to set them in this client.

Also once you set them on github, you can get a private email and use this one. See https://help.github.com/articles/keeping-your-email-address-private/

**Comment by ZackTheCardshark** [comment]
Well, I'm doubtful that those addresses will serve any purpose, but I've done it. Thanks.

**Pull request merged**
