### PR TITLE
[MU3] Fix #316152: Some characters do not print from Leland on certain printer drivers on Mac

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: https://musescore.org/en/node/316152

Fix got confirmed by several users

This is for 3.x what #8853 is for master

### CODE REVIEW

**Comment by oktophonie** [comment]
The vtest diffs look as expected to me, given the added/modified symbols in Leland since 0.5

**Comment by Jojo-Schmitz** [comment]
Thanks.

Let me know if and when a version of this PR for master is needed or wanted.

Meanwhile it'd be great to get this merged into 3.x, to enable easy access for testers to a development build (like no need for a GitHub account).

**Comment by Jojo-Schmitz** [comment]
So far 3 positive reports from testers of the artifact.

**Comment by Jojo-Schmitz** [comment]
Is a counterpart PR for master wanted/needed?

**Comment by oktophonie** [comment]
It wouldn't hurt, though it will hopefully be supplanted by an 0.62 (or something) in the near future.

**Comment by Jojo-Schmitz** [comment]
Well, __I__ can wait for that to happen ;-)

**Comment by Jojo-Schmitz** [comment]
Actually I can't, see #8853

**Comment by Jojo-Schmitz** [comment]
See #9000

**Pull request closed without merging**
