### PR TITLE
Implemented Reset all styles to default button in EditStyle dialog

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #9464
Resolves: #9187

### CODE REVIEW

**Comment by AntonioBL** [comment]
Apparently, the utests and vtests fail because of the commit "Enable vertical justification of staves by default".
Indeed, in the "failing" vtests the vertical space between staves has changed with respect to the reference build (and meybe it has changed for the better; note that vtests just point out differences with respect to the ref branch, but they cannot automatically judge what is better).
In the utests, the ref file contain an additional
      `<enableVerticalSpread>1</enableVerticalSpread>`
which does not appear in the files created by this PR.

The other build failures are maybe a temporary "hiccup" in the virtual machines. You can try to rebase so that the build restart.

Ciao,
ABL

**Comment by Jojo-Schmitz** [comment]
So the utest ref files need to get adjusted, to not contain the new default setting.
While the vtest files might get 'corrected' to contain the old default setting. Or just ignore the failure 
Something is still wrong with the vtests though: I don't see the artifact.

**Comment by cbjeukendrup** [comment]
I do see the artifact at https://github.com/musescore/MuseScore/actions/runs/1399562015. (But apparently GitHub removed the link in the top right corner in the log view?)

**Comment by Jojo-Schmitz** [comment]
Ah, maybe that's just a change in the GutHub UI then?

**Comment by cbjeukendrup** [comment]
The unit tests should be fixed now. For the vtests, we probably need the `vtests` label.

But I don't understand why the Linux/MacOS/Windows builds are failing...

**Comment by Jojo-Schmitz** [comment]
Funny enough the vtests are fine now. I guess because they don't differ to the commit before. So as long as you don#t squash the cimmits the VTEST lable is not needed ;-)

**Comment by cbjeukendrup** [comment]
No, the Vtests use the base branch as their reference, so in this case the current master.

The culprit may have been that I made a mistake in the legacy style files (I wrote `enableVerticalSpreading` instead of `enableVerticalSpread`, don't know why I did that 😅).

**Comment by Jojo-Schmitz** [comment]
The build failures seem to be an issue for @igorkorsukov to investigate and solve?

**Comment by igorkorsukov** [comment]
problem due to quotation marks in the title of the PR
`if [ "pull_request" == "pull_request" ]; then PR_INFO="_9602_Implemented "Reset all styles to default" button in EditStyle dialog"; fi`

Unfortunately, the renaming and restarting did not solve, the old title was remembered.
At the moment, needs to do `push` to restart the build with a new title.

And later I will try to fix this problem.

**Comment by cbjeukendrup** [comment]
Thank you @igorkorsukov for investigating. I will fix it soon.

**Comment by cbjeukendrup** [comment]
That last commit should fix the problem for future PRs that have quotes in the title.

**Comment by DmitryArefiev** [comment]
Tested #9464 #9187 on master build on Win10, Mac11, LinuxMint 20 - PASS

**Pull request merged**
