### PR TITLE
fix #277016: Changing behavior of reading GTP file with incomplete measure

### PR DESCRIPTION
**Pull request by handrok**
Now when MS reads this type of measure it complements it with rests to fill up to full duration of measure.

### CODE REVIEW

**Comment by anatoly-os** [comment]
@handrok could you please add the mtest which indicates and checks the new behaviour for the future?

**Comment by Jojo-Schmitz** [comment]
That Travis CI failure on the 1st commit doesn't really make sense, or does it?

**Comment by anatoly-os** [comment]
It does. 4 tests are failed.

**Comment by handrok** [comment]
@anatoly-os  all checks have passed

**Pull request merged**
