### PR TITLE
fix #44956: staves with text are not empty

### PR DESCRIPTION
**Pull request by MarcSabatella**
Assuming others agree that staff text should make a staff appear not empty for the purpose of "hide empty staves", the following code accomplishes that.  The measure will still be considered empty for the purpose of multimeasure rests.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Added a second commit to implement an option to revert to 1.3 behavior with regard to multi-staff instruments: only hidden if all staves of the instrument are empty.  This is done by adding an "Instrument" entry to the "Hide when empty" drodown in Staff Properties.

**Comment by lasconic** [comment]
Some tests for these two would be welcome. Even vtests.
I'd tend to not merge them in 2.0.3 except if there are good arguments.

**Comment by MarcSabatella** [comment]
The second definitely cannot be merged except in a release that supports the new "Hide when empty" option - which is to say, master only.  The first commit *could* go either way.  I guess I combined them into one PR because the code overlapped so they wouldn't be mergeable separately, but of course it the changes are small and it would be simple enough to split them up if someone were to argue we should take the first of these for 2.0.3.

My vote is we don't though - it would potentially have an effect on existing scores, and I still am not completely sure everyone would agree the change is desirable in the first place.  Especially considering this recent forum thread: https://musescore.org/en/node/94561.

So I'm thinking, maybe I separate out the second commit to a new PR, add a test, and consider merging it for the master, but we don't do anything rash on the first commit.  Further forum discussion might be in order.

**Comment by lasconic** [comment]
Not sure I get the link with https://musescore.org/en/node/94561.
But I understand that you agree with my previous comment. Feel free to put the tests in and squash them with the matching commit. No need for a second PR.

**Comment by MarcSabatella** [comment]
My mistake.  I forgot that my code specifically does *not* change the behavior for mmrests, only for hide empty staves.  So it's actually not likely to be very controversial, and could be merged for 2.0.3 if someone thought it useful.  FWIW, I implemented this at the request of an associate who runs a composition program for schoolchildren that uses MuseScore and they use hide empty staves a lot to allow musicians to read directly from scores but still keep the scores a manageable size.  He's pretty versed in the workarounds, but as we has telling me about this, I thought it should be something we did automatically.  And now that I remember it only affects hide empty staves and not mmrests, I'm less concerned about bad effects on existing scores.  But I also have no issue with not merging for 2.0.3.

Ideally, I guess I would keep this PR, keep the two existing commits but add two more with appropriate tests and squash the test with the corresponding code.  That might tax my "git" abilities; we'll see :-)

**Comment by lasconic** [comment]
Hi Marc,
Revisiting this PR, I think I agree we should merge the first commit on both branches and the second in master only. I'm not really sure with what you mean with full measure rests since text do cut mmrest and it's a good thing but I do understand that your code doesn't change a thing to the handling of mmRest which is also a good thing.

Could you have another look to vtests? rebase -i will let you reorder and squash relevant commits together. http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by MarcSabatella** [comment]
Thanks, I will get on that.

My comment about text & mmrests was unclear.  What I mean is that while text elements do *break* an mmrest, they don't *prevent* a measure from being included within one.  This is as it should be, and my PR does not change this, so again, it should be good for 2.0.3.

**Comment by MarcSabatella** [comment]
First commit should now be good to go for 2.0.3 & master; it includes a vtest.

Second commit works and has a vtest, but the test generates error messages to console that I need to understand better, so it shouldn't be merged yet (and can only be merged to master once I fix whatever the issue is).

**Comment by MarcSabatella** [comment]
Fixed the spurious errors as part of this second commit.

**Comment by MarcSabatella** [comment]
It's not actually especially important to me, but we *did* tentatively agree to merge the first commit here for 2.0.3.

**Comment by lasconic** [comment]
[Except for freetype](https://musescore.org/en/developers-handbook/release-notes/release-notes-musescore-2.0.3) we don't have many things that would make a score look very different in 2.0.3 compared to 2.0.2. So I take my statement back and merge this on master only.

**Pull request merged**
