### PR TITLE
fix mtests, after PR #5674

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by Spire42** [comment]
Do we know that this change to the output `.mscx` file in PR #5674 was intentional and not a bug?

**Comment by Jojo-Schmitz** [comment]
I guess it was an undetected merge conflict with the chord playback feature

**Comment by Jojo-Schmitz** [comment]
But @njvdberg may know better

**Comment by njvdberg** [comment]
I think this was a kind of intentional bug (?). For some reason, after saving I always have to edit the <code>.mscx</code> files to be used in mtest. E.g. <code>synthi</code> have to be removed. So editing was intentional but in this case the too much was removed, that was a bug. Mea culpa, mea culpa, mea minima culpa.
Thanks for solving it while I was asleep.

**Comment by Jojo-Schmitz** [comment]
You need to edit those files either manually or using the -t option of MuseScore IIRC

**Comment by njvdberg** [comment]
Just test, the -t option indeed saves me the manual editing! Thanks for the hint.

**Pull request merged**
