### PR TITLE
fix #294076: Add Carillon instrument

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by Howard-C** [comment]
Carillion is before timpani?

**Comment by Jojo-Schmitz** [comment]
Does the order matter?

**Comment by Howard-C** [comment]
I'm afraid I haven't seen an exception of any pitched percussion written before timpani on an orchestral score... so shouldn't the order in MuseScore be the same? 
"R" in roto-toms is also before "T".

**Comment by Jojo-Schmitz** [comment]
I haven't seen a carillon in any orchestral score. it is pretty much a solo instrument, check https://en.wikipedia.org/wiki/Carillon to see why ;-)
There's just not enough space on a bell tower for a full orchestra ensemble.

**Comment by Jojo-Schmitz** [comment]
I can of course move it elsewhere, like to the end of pitched persussions, after Alto Kalimba.

**Comment by Jojo-Schmitz** [comment]
As this adds strings for translation, it should get merged before string freeze

**Pull request merged**
