### PR TITLE
fix #278721: text controls missing in Inspector

### PR DESCRIPTION
**Pull request by MarcSabatella**
Layout is a little different than Jojo had it, someone else might want to tweak further, but at least this works.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
...but the tab order isn't correct, a couple of other glitches, will fix those too

**Comment by MarcSabatella** [comment]
Tab order fixed.  There are also glitches in the "set as style" buttons, but I don't know that these weren't present before either, and in any event we should be looking at redesigning those.  So I won't worry about that.

**Comment by anatoly-os** [comment]
@MarcSabatella please squash the commits and remove "-" after `fix #XXXXXX` pattern.

**Comment by MarcSabatella** [comment]
Oops, fixed.

**Pull request merged**
