### PR TITLE
Update IntervalTree

### PR DESCRIPTION
**Pull request by PatrickNorton**
The version of [IntervalTree](https://github.com/ekg/intervaltree) we are using has received many upstream updates, however these have not been merged into here since 2013.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
The logs for the failing utests are wiped meanwhile, so no idea what they are failing on. Maybe a rebase is in order?

**Comment by vpereverzev** [comment]
@PatrickNorton could you rebase your branch onto the latest master? I'm not against of merging this. But we need to make sure that unit-tests are not failing

**Comment by Jojo-Schmitz** [comment]
As @PatrickNorton seems to have been inactive for quite a while, I `git cherry-pick`d the stuff on top of the current master, see #11279

**Comment by cbjeukendrup** [comment]
Closing as replaced by #11279

**Pull request closed without merging**
