### PR TITLE
fix #296190: Campania not rendering correctly on some macOS systems

### PR DESCRIPTION
**Pull request by MarcSabatella**
Resolves: https://musescore.org/en/node/296190

The version of Campania we just updated to (2.008) works fine on Windows
but apparently fails on macOS, at least on some systems in some cases.
The version of Campania incldued here is still built from the same 2.008 sources,
but it turns off the "Apple" option within FontForge.
This causes tables to be written in Adobe format,
which appears to fix the problem.

If this cannot be verified to work, and I don't figure anything else out quickly enough, I will submit a new PR reverting Campania to the same binary as used in RC2.  The code changes in #5390 should still be good to keep.

### CODE REVIEW

**Comment by mirabilos** [comment]
If Campania has sources (`*.sfd`?), I would _really_ like to __see__ them.

**Comment by Jojo-Schmitz** [comment]
at https://github.com/MarcSabatella/Campania

**Comment by MarcSabatella** [comment]
I have verified this works on macOS, but based on testing and discussion on Telegram, the consensus it will be best to regenerate the font again with the "Old-style kern" option enabled.  So I will do this and update the PR.

**Comment by MarcSabatella** [comment]
And yes, https://github.com/MarcSabatella/Campania is the official source for the font.  I want the font to be available outside of MuseScore, and I want people not associated with the MuseScore project (and who have thus not signed the CLA) to be able to contribute to it.  I also prefer not to have the source duplicated if at all possible - that is just asking for trouble with things getting out of sync.  I'm open to other arrangements but this was the consensus when I first embarked on this project several months ago.

**Comment by MarcSabatella** [comment]
Updated, font version 2.009, still same source (changed name of a glyph to eliminate a warning) but with Apple disabled, Old-style kern enabled.  The consensus is, this is the right way to do it.  Will still be good for someone to test an actual release build with this - ideally, we'd merge to master and check the nightlies on each OS before merging to 3.3

**Comment by mirabilos** [comment]
On Mon, 28 Oct 2019, Marc Sabatella wrote:

> And yes, https://github.com/MarcSabatella/Campania is the official
> source for the font.

OK.

> I also prefer not to have the source duplicated if at all possible -

I will, however, need to have the source in Debian if the source
exists. For this, I have the following two scenarios:

• install Campania system-wide and not bundle it in the musescore
  executable, allowing independent updates

• bundle Campania from your github as “second source tarball”

In both cases, you should do releases of Campania, so that the
git tree is tagged with the version number.

I’d prefer the former *because* you want people to use it outside
of MuseScore. It causes no small amount of trouble if the application
bundles a different version of the font from what is installed
system-wide. But what do you think?

**Comment by MarcSabatella** [comment]
What does it mean to "do releases of Campania"?  I guess you mean the release tagging facility on GitHub itself?  I see a "Create new release" button, I suppose that would be my starting point?

As for the question of installing the font system-wide versus bundling it, from what I understand it's a damned-if-you-do-damned-if-you-don't situation.  In the past people have managed to shoot themselves in the foot on Linux by getting their mscore fonts out of sync with their MuseScore releases, which is bad.  Also when people have a version of FreeSerif that doesn't support whatever it is we've added to it, which I think has happened too.  So it's no small amount of trouble if the application doesn't get some control over the version of a font it uses, at least for fonts where the application itself relies on particular font features.  But it's also bad when you can't just install an updated version of a font to use it with MuseScore, and right now this seems to be the case on Windows.

Anyhow, I don't know the technical or legal tradeoffs, so if you're happy with the problems that result from *not* bundling the font, that's fine with me.  I just need to know what "do releases" means.

Oh, and feel free to tell me what you meant elsewhere about copyright and italics..

**Comment by MarcSabatella** [comment]
Thanks for the info!  Here's what I take from all that:

- I get that you need to distribute the source for any binaries, and that ideally there would be an automated way to generate the binary form the source.  Feel free to write a script to generate OTF from SFD, I imagine it's just like the TTF script except I'm not really clear on the magic numbers (even after perusing the docs I'm not clear on which settings in the GUI "0x800" corresponds to, just that supposedly it makes Microsoft & Apple both happy.  I can tell you I am using defaults except that I make sure OpenType and Old-style kern are both on (meaning Apple is off).  I considered turning on the Round option but elected not to this time around as I didn't want to introduce another change.  But the non-integral coordinates are inherent in the glyphs I started with (mostly from Doulos).

- Packaging-wise, it sounds like we should do this like FreeSerif etc - don't compile in but instead install system-wide, for Debian anyhow, macOS has its own system so does Windows, and while someday we could revisit those I see no reason for this to be that day or for me to be the revisitor.  If you end up making a different choice for Debian, though, I can't say that I care.

- I need to make a "release" on GitHub so you can reliably grab from there.  I'm on that, will let you know when I think I have something.

- You are right that MuseScore doesn't rely on any particular aspects of Campania - we just assume it's a good choice that will render things the way you want if you type them the way you want

- To be honest, I'm not totally up on how the split between MsueJazz and MuseJazz Text is managed, but chord symbols in the "Jazz" style (as per Format / Style / Chord Symbols) do rely on the specifics of what used to be MuseJazz and is now MuseJazz Text in that it won't look at all reaosnable with any other font.  Not so much because of actual "code" (although there may be some small dependencies) but because of chords_jazz.xml.

- I see the error from FontForge about copyright strings if I open the OTF file.  I blame FontForge itself, because I don't see those errors when I open the SFD.  The copyright strings in the SFD look perfectly normal to me, no idea how FontForge screwed that up when writing or reading the OTF.

**Comment by mirabilos** [comment]
Marc Sabatella dixit:

>- I get that you need to distribute the source for any binaries, and
>  that ideally there would be an automated way to generate the binary

Yeah, but I’m trying to skip on the “ideally” for now; fontconfig is
notoriously hard to script.

>  clear on which settings in the GUI "0x800" corresponds to, just that

“old-style kern” (all other settings we use are 0-bits in that
function) and I will update the PR to explain this.

>- Packaging-wise, it sounds like we should do this like FreeSerif etc -
>  don't compile in but instead install system-wide, for Debian anyhow,

Interestingly enough, I’ve not yet separated out FreeSerif et al. even
in Debian yet. I probably should.

>  macOS has its own system so does Windows, and while someday we could
>  revisit those I see no reason for this to be that day or for me to be

True. Installing the fonts system-wide would be useful, but I don’t
know about the Macintosh, nor how/if it would work with portable apps…

>- I need to make a "release" on GitHub so you can reliably grab from
>  there. I'm on that, will let you know when I think I have something.

It works and I’ve uploaded Campania to Debian now, pending ftpmaster
review.

>- To be honest, I'm not totally up on how the split between MsueJazz
>  and MuseJazz Text is managed, but chord symbols in the "Jazz" style
>  (as per Format / Style / Chord Symbols) do rely on the specifics of
>  what used to be MuseJazz and is now MuseJazz Text in that it won't

Oh… but…

>  look at all reaosnable with any other font. Not so much because of

… yeah, but that’s the user’s fault then.

>  actual "code" (although there may be some small dependencies) but
>  because of chords_jazz.xml.

That lists codepoints and render strings, but not things like precise
widths of individual characters and anchor points for putting them to‐
gether, so I assume it would work equally well with any later version
of the same font (as long as the font designer takes care to retain
backwards compatibility… a given, since old scores are invalidated as
well, I think).

My point here is more about the system-wide font being updated relative
to the one (normally?) embedded into the application.

>- I see the error from FontForge about copyright strings if I open the
>  OTF file. I blame FontForge itself, because I don't see those errors
>  when I open the SFD. The copyright strings in the SFD look perfectly
>  normal to me, no idea how FontForge screwed that up when writing or
>  reading the OTF.

Writing, they are present in the OTF (the ttx program from fonttools is
useful in inspecting them). Eh, another fontforge mystery that can be
solved another day…

Thanks for the quick responses and working together to get at least
the most important issues solved, and in the sense of the users at that.

**Pull request merged**
