### PR TITLE
[MU4] Update notation styles live when changing them in style dialog

### PR DESCRIPTION
**Pull request by aaaeka**
Resolves: #7969 

A very simple fix.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
But isn't the issue that the notation should update directly when making changes and not only when clicking OK?

**Comment by aaaeka** [comment]
> But isn't the issue that the notation should update directly when making changes and not only when clicking OK?

True, will fix.

**Comment by vshalkevich** [comment]
Style applies only when I click OK button. 
It should be updated when I select another style at the same time (before user click OK)

**Comment by cbjeukendrup** [comment]
Maybe it's as simple as copying or moving the line you added, to `setStyleValue`.

**Comment by aaaeka** [comment]
I was searching on and off to find a way to fix this problem for a week now. I think I already tried the solution you suggested, but I can't remember for sure so I'll try it again.

**Comment by aaaeka** [comment]
Turns out it was simply because ```score()->update()``` was not called.

**Comment by cbjeukendrup** [comment]
Ah, nice spot! It works perfectly now!

**Review by cbjeukendrup — APPROVED** [review]

**Comment by vshalkevich** [comment]
Checked. Works good

**Comment by vshalkevich** [comment]
Also works fine on Windows 10 without this changes

**Comment by vshalkevich** [comment]
On Windows 10 feature works fine without fixes (without this PR)

**Comment by cbjeukendrup** [comment]
> On Windows 10 feature works fine without fixes (without this PR)

Are you sure? For me it does not, on Windows 10.

**Comment by Eism** [comment]
> > On Windows 10 feature works fine without fixes (without this PR)
> 
> Are you sure? For me it does not, on Windows 10.

it works on Windows 10 for me too

**Comment by vshalkevich** [comment]
> 
> 
> > On Windows 10 feature works fine without fixes (without this PR)
> 
> Are you sure? For me it does not, on Windows 10.

Yes, strange. 
@aaaeka What this code do? I can`t understand why it works withour this PR in some cases and doesn`t work for others?

**Comment by cbjeukendrup** [comment]
I mean, _with_ the PR it works perfectly for me on all platforms, but _without_ the PR it does not work, on Windows 10 just like on macOS.
So I am convinced this PR is okay and is needed.

**Comment by Eism** [comment]
> I mean, _with_ the PR it works perfectly for me on all platforms, but _without_ the PR it does not work, on Windows 10 just like on macOS.
> So I am convinced this PR is okay and is needed.

it is necessary to understand the problem. Please answer these questions
1. steps to reproduce the bug
2. Is the bug reproduced on the latest master?

**Comment by cbjeukendrup** [comment]
On the latest master, the following happens:
1. Create a score
2. Open the style dialog
3. Change (for example) the musical font from Leland to Emmentaler
4. You see _some_ things updating in the score view, but most things not.
5. When you press OK and drag the notation (to trigger redrawing), everything updates.

With this PR, number 4 is like this:
4. As soon as you make any change in the style dialog, you see the whole score updating correctly.

**Comment by Eism** [comment]
> 4. You see some things updating in the score view, but most things not.
can you give an example of non-updatable elements?

**Comment by cbjeukendrup** [comment]
This video shows what happens when changing the font. In fact, only the brackets are changing somewhat. 
When I click OK and move the notation a bit, you see the font changing (the G-clef is the most obvious). 

https://user-images.githubusercontent.com/48658420/118023912-5e943100-b35e-11eb-9ed6-228accecae6f.mov

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
