### PR TITLE
Fix crash when building with VST3 SDK v3.7.9

### PR DESCRIPTION
**Pull request by cbjeukendrup**
I got this crash when opening this score: https://github.com/musescore/MuseScore/files/13753150/Test.mscz.zip (from https://github.com/orgs/musescore/discussions/20631) in a local build, created with version 3.7.9 of the VST3 SDK.

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Apparently this `initialize()` method is not even existent yet in the version of the SDK that we are using on CI. So this would require us to update to the latest version in our CI builds, which is not trivial because who knows what other surprises the new version will have in store for us. Let's wait with this at least until @RomanPudashkin is back :)

**Review by RomanPudashkin — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
@DmitryArefiev About this PR: it switches to an updated VST SDK version, and makes some changes necessary to make that work properly. So, it needs to be verified that VST support works at least as good as before this PR.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup All seems to be fine on my side.

Tested on Win10, Mac13.6 - **PASS**

**Comment by RomanPudashkin** [comment]
@cbjeukendrup please rebase

**Comment by cbjeukendrup** [comment]
Done!

**Comment by bkunda** [comment]
@DmitryArefiev pls recheck this on the latest 4.3

**Comment by cbjeukendrup** [comment]
This is not included in 4.3, and doesn't strictly need to be included; the VST-related code in 4.3 was designed to work with an older version of the VST SDK, and caused a crash when used with the latest version. But since 4.3 still uses the old SDK, i.e. our code is in sync with the SDK version being used, there is no problem. The reason that we made this update in master is that it's generally not preferable to stick with old versions of things forever.
Anyway, quickly checking this in 4.3 just to be sure is not a bad idea.

**Comment by DmitryArefiev** [comment]
> Anyway, quickly checking this in 4.3 just to be sure is not a bad idea.

@cbjeukendrup Do you mean to test the issue from the description in 4.3 builds?

> 
I got this crash when opening this score: https://github.com/musescore/MuseScore/files/13753150/Test.mscz.zip (from https://github.com/orgs/musescore/discussions/20631) in a local build, created with version 3.7.9 of the VST3 SDK.

**Comment by cbjeukendrup** [comment]
No, just check that VST is working in 4.3 builds from GitHub Actions (or nightly builds). We don't need to worry too much about local builds for 4.3, since contributors should work on 4.4 anyway.

**Comment by cbjeukendrup** [comment]
Correct!

**Comment by DmitryArefiev** [comment]
Tested 4.3 builds on Win11/Mac13. **All good**

**Pull request merged**
