### PR TITLE
fix #95636 Spanner.tick() needs to correct spanner index

### PR DESCRIPTION
**Pull request by jeetee**
…in the SpannerMap

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Cool, I hope it really is that easy!  I was thinking there was a reason we weren't already doing that but were instead setting the "dirty" flag - like things might go wrong if you mess with map directly in this fashion.  But it's probably not worse than what is already happening :-)

**Comment by jeetee** [comment]
Did some more code digging and I don't see any place where it goes (more) wrong than before.
You're of course correct that deleting and inserting in a map can mess up things; but that is only true if you do it whilst looping through the map with an iterator (which is the case in ranged for loops). The iterator would become invalid and can lead (worst-case) to a segfault.

That being said, I've simply tested to extend a Volta to the left over 2 measures and could save and reopen without issues popping up in the debugger.

Other areas that could get messed up during that time, are areas that worked on the result of a find-action, as that resulting vector is no longer correctly sorted. But these were just as messed up before this fix.
They get the new order after an update has been triggered and a new find call is done, just like before.

**Comment by MarcSabatella** [comment]
I do know about the issues remove from loops while iterating on them, which is why fixing the issue in SpannerMap::update() was looking problematic.  But the type problem I was more concerned about regarding doing the remove/add directly while editing the slur is that perhaps elsewhere there is some sort of implicit assumption that spanners are not removed from the map except during doLayout().  I don't know that this is the case, but it was my concern.  Seems like it's probably not an issue here, but be sure to test other actions (not just slur editing) call Spanner::setTick().

**Comment by jeetee** [comment]
I think I ruled out the introduction of new bugs; not by looking into callers of Spanner::setTick(). But by looking into who/when a SpannerMap is used as a raw map and of those (limited) occurrences, check which ones depend on the order of elements within the map.
Functions that do that are only related to:
 * doLayout: which is fine, the map is up to date in this stage
 * renderMidi: which is fine, exporting of audio, no changes happen at that time, order of map is up to date
 * Exporting/Saving files, which is fine we're not changing the order of the map in this process

Some lookup functions also operate on the map itself (searchVolta in repeatlist.cpp for example), but they loop linear and ignore the index in the map. So no issues there either.

**Comment by lasconic** [comment]
After a hopefully complete tour around the code, I couldn't find a `setTick` while iterating on a `spannerMap` but it's probably because we are lucky... Would it be wrong to remove the `const` and do the tick management in `update`? Because, doing this in setTick, it will be impossible to write the following without a crash...

```
for (auto i : spannerMap)
    i.second->setTick(480);
```

**Comment by jeetee** [comment]
Possible approach:
1. rename the current function to updateSearchTree (and make it private?)
2. in a new public update function, do the following if the map is marked dirty:
  a. loop and remove all spanners from map where index is no longer correct
  b. loop over list of removed spanners and re-add them
  c. call updateSearchTree

Do we want to review all current calls to <code>update()</code> and see if they could be replaced with calls to <code>updateSearchTree()</code>?
I don't know how much overhead would be created by verifying the index on all current update calls, but I would expect them to be minor as its only performed on a dirty map.

**Comment by lasconic** [comment]
I  talked it through with Werner and he is happy with this PR. If Werner is happy, I'm happy too. So let's merge it.

**Comment by jeetee** [comment]
I'm not complaining if the big boss is happy. Perhaps I could add a simple comment warning to not call setTick from within a spannerMap loop?

**Comment by lasconic** [comment]
Please do.

**Comment by lasconic** [comment]
Thanks!

**Pull request merged**
