### PR TITLE
3.5.2_backend_porting

### PR DESCRIPTION
**Pull request by vpereverzev**
Ported the latest changes from 3.5.2_backend for musescore.com

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
That new commandline option needs to get added to the man-page too, https://github.com/musescore/MuseScore/blob/3.x/build/Linux%2BBSD/mscore.1.in

**Comment by Jojo-Schmitz** [comment]
Ignoring the vtest failures are not the right thing, if those are due to crashes!

**Comment by vpereverzev** [comment]
> Ignoring the vtest failures are not the right thing, if those are due to crashes!

it's not related to this PR

**Comment by Jojo-Schmitz** [comment]
Hmm, but to what then?

**Comment by vpereverzev** [comment]
> Hmm, but to what then?

dunno, but it's already in 3.x, I'm trying to fix it now

**Comment by Jojo-Schmitz** [comment]
Some stuff from #7218 ?

**Pull request merged**
