### PR TITLE
Fix #298955: Duplicate elements applied for each note in chord with range selection

### PR DESCRIPTION
**Pull request by IsaacWeiss**

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
See https://musescore.org/en/node/298955. For some palette elements, such as accidentals and noteheads, the current behavior (applying one for each note in the chord) *is* important to retain; are there other element types that should be excepted?

**Comment by dmitrio95** [comment]
Isn't this the same what #5437 is intended to fix? Anyway, I am honestly not fully happy with both of the proposed solutions. It seems to me that the ideal solution should try to avoid adding identical element to the same *parent* (drop target is often different to actual parent of the dropped element) without explicitly handling the respective elements' and their parents' types. Even if it happens so that the best way to implement this solution results in larger changes (it doesn't currently seem to be possible to easily figure out which type would a parent of an arbitrary element added to a score have) such solution would definitely be better to maintain in a long term.

**Comment by njvdberg** [comment]
[#5437 ](https://github.com/musescore/MuseScore/pull/5437) prevents multiple text elements when multiple notes are selected.

**Comment by IsaacWeiss** [comment]
> Even if it happens so that the best way to implement this solution results in larger changes (it doesn't currently seem to be possible to easily figure out which type would a parent of an arbitrary element added to a score have) such solution would definitely be better to maintain in a long term.

To be sure. In the shorter term, though, without those larger changes, are there any objections to this method of only adding to one note of each chord? This is a problem that very frequently annoys me when I write, and not only with text elements (as in #5437).

**Comment by IsaacWeiss** [comment]
Thanks!

**Pull request merged**
