### PR TITLE
Fix clicking FlatButton if you (accidentally) move the mouse between press and release

### PR DESCRIPTION
**Pull request by cbjeukendrup**
See https://github.com/musescore/MuseScore/issues/16012#issuecomment-1399656043

Resolves: #16012

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Tantacrul** [comment]
Hey @MarcSabatella & @bkunda 

When you get a chance can you test this and report back. I'm not near a PC right now (trackpad on MacOS) so can't test this.

**Comment by cbjeukendrup** [comment]
I don't think that a physical mouse or not will make much of a difference. Probably QML can't even see which kind of device you're using. This is really all at software level.

**Comment by Tantacrul** [comment]
> I don't think that a physical mouse or not will make much of a difference. Probably QML can't even see which kind of device you're using. This is really all at software level.

I'm just unable to practically notice a difference with my fancy Mac trackpad.

**Comment by bkunda** [comment]
Tested this on Windows and Mac as a side-by-side comparison with 4.0.1. I can confirm there is definitely a noticeable increase in the range of mouse cursor movement accepted by the app while still triggering the required action. So this fix has definitely addressed the problem (Incidentally, I tested it on all the UI elements identified in the YT video linked in #16012, plus a range of other elements too).

The only additional point I might flag - which was not highlighted in the abovementioned video - is that a similar kind of additional mouse cursor movement when clicking on a tabbed panel (palettes, properties, instruments) can very easily cause the panel to become undocked. 

Not sure if this could also be addressed in this same PR, but I imagine this could also cause similar frustration if a person unintentionally moved their mouse slightly when trying to switch to a different tab. 

Otherwise, this PR seems to have addressed the problem.

**Comment by Tantacrul** [comment]
So in other words, we need to increase the threshold for how much a user must move their mouse for these elements i order to undock them?

@RomanPudashkin - that seems like a sensible improvement. Is it easy to do?

**Comment by RomanPudashkin** [comment]
> Is it easy to do?

It seems so, but I'm not 100% sure :)

@cbjeukendrup try to play around with startDragDistance(), which is defined in Utils_p.h. Unfortunately, there is no public API for modifying this setting

**Comment by bkunda** [comment]
I've just tried this out at @Eism's request. If I'm honest, I can't really detect any change in behaviour here (when comparing to the current stable release): I.e. In this PR the **palettes**, **properties**, **instruments** and **filter selection** panels are still just as easy to undock with a very slight movement of the mouse (while mouse click is down) as they are in v.4.0.1.

**Comment by bkunda** [comment]
@cbjeukendrup I've just tested this (with @Eism's help) with a value of 40 (startDragDistance) and this seems to have solved the problem of unintended panel undocking nicely. I believe this PR will be ready to merge once this change has been applied to your PR 🙂.

Thanks!

**Comment by Eism** [comment]
I will merge it and fix the problem in separate PR

**Pull request merged**
