### PR TITLE
Minimum drag distance: use physical instead of logical

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #20743

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/20743 FIXED

**Comment by fernandomartin777** [comment]
I don't understand. After it was tested and working why was it not included in MU4.2.1?

**Comment by cbjeukendrup** [comment]
To reduce the risk of breaking things without noticing, we make patch releases as small as possible and ideally fix only critical problems. For 4.3, we have more time left for testing, so then we can include more things.

**Comment by fernandomartin777** [comment]
Oh no! +/- six months waiting for a new pointed release. Ok.

**Pull request merged**
