### PR TITLE
Check for straight quotes and other errors in translatable strings

### PR DESCRIPTION
**Pull request by shoogle**
The Linux CI build will fail when errors are found, but the Windows and macOS CI builds will proceed with warnings printed in the log.

### Sample output for [failed checks](https://github.com/musescore/MuseScore/actions/runs/6720729136/job/18264932033?pr=19900):
image

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Shouldn't that rather be part of the unit tests?

**Comment by Jojo-Schmitz** [comment]
Or the codestyle test?

**Comment by shoogle** [comment]
@Jojo-Schmitz, arguably yes, but:

- The unit tests build is the slowest CI build, so I don't want to slow it down further.
- The codestyle build doesn't have `lupdate`, which is needed to generate the `_en.ts` translation files used by the script.
    - It's a waste of resources to download Qt from S3 storage just to run the `lupdate` command.
    - I could install Ubuntu's `lupdate` (I think it's in [this package](https://packages.ubuntu.com/focal/qttools5-dev-tools)) but it might behave differently to ours.

The Linux CI build is the fastest build that has our Qt, and most testers are not on Linux anyway, so failing the Linux build is the least bad option in my opinion.

It's not expected to fail very often. When it does fail, it will do so within a couple of minutes, so there's not much time lost.

**Comment by Jojo-Schmitz** [comment]
@shoogle mind to take care of https://github.com/musescore/MuseScore/commit/97229a8fd1c5f7e123deec7124f5742637a42337#r131476847 too?

**Comment by Jojo-Schmitz** [comment]
OK, I did it, see 83cb5fa

**Comment by shoogle** [comment]
@Jojo-Schmitz, thanks! Please submit that in a separate PR to serve as a reference for how to solve that specific problem.

**Comment by Jojo-Schmitz** [comment]
done, see #19904

**Review by cbjeukendrup — APPROVED** [review]

**Pull request merged**
