### PR TITLE
fix capitalisation for shortcuts and more

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
see http://musescore.org/en/node/48776.

* Reg. "Note Entry" vs. "Note Input" see http://musescore.org/en/node/49321.
* Reg. "Screenshot" vs. "Image Capture", see http://musescore.org/en/handbook/foto-mode#comment-225451 ff.
* Reg. "Soundfont" vs. "SoundFont" see http://musescore.org/en/node/36171#comment-228186 ff.

### CODE REVIEW

**Comment by thomasbonte** [comment]
I would go for Image Capture instead of Mode.
As for Note Input vs Entry mode, I trust Marc's authority on this so I would go along with Marc.

**Comment by Jojo-Schmitz** [comment]
done

**Comment by Jojo-Schmitz** [comment]
Changed to "Image Capture Mode". @MarcSabatella seems to have changed his mind in  http://musescore.org/en/node/49321, from "Note Entry" to "Note Input", I think?

**Comment by Jojo-Schmitz** [comment]
Changed to "Image Capture Mode". @MarcSabatella seems to have changed his mind in http://musescore.org/en/node/49321, from "Note Input" to "Note Entry", I think?

**Comment by Jojo-Schmitz** [comment]
whatever, here it goes with "Note Input" ...

**Pull request merged**
