### PR TITLE
[MU4] Shortcuts

### PR DESCRIPTION
**Pull request by igorkorsukov**
Added shortcuts module.

There are several imperfections:
* Editing not implemented
* No keyboard layer dependency (no `shortcuts_AZERTY.xml` loading)
* Not correctly determine the current context for shortcuts

These issues will be fixed later.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Will this framework finally allow shortcuts to be assigned by the user for palette elements?  This capability was added as part of GSoC a few years ago but never merged.  To me it's one of the more glaring holes in our UI that I'd really love to see addressed.

The GSoC project basically adapted cloned the plugin shortcut system and adapted it for the palettes.  I think the better solution would have been to integrate them together.  See #3252 for reference.

**Comment by igorkorsukov** [comment]
> Will this framework finally allow shortcuts to be assigned by the user for palette elements? This capability was added as part of GSoC a few years ago but never merged. To me it's one of the more glaring holes in our UI that I'd really love to see addressed.
> 
> The GSoC project basically adapted cloned the plugin shortcut system and adapted it for the palettes. I think the better solution would have been to integrate them together. See #3252 for reference.

Yes, I see no reason for this to be a problem.
The new shortcuts system is based on two things:
* Actions - that is, the action to be sent
* Shortcuts context - that is, in what context are we now in order to send the desired action (for example, on press key `Left` if now is playing, then send `play-prev-chord`, and if not, then `prev-chord`)

In MuseScore 3 it was difficult to determine the context (at least difficult for me), in the new system it is relatively easy, but still not completely finished.

**Comment by MarcSabatella** [comment]
It's the tying of shortcuts to "actions" that has always been the limiter - that restricts us to a predefined, compiled-in list.  The plugin manager allows shortcuts to be assigned to plugins are loaded dynamically, and that's the key feature we also needed in order to allow the user to assign shortcuts to arbitrary palette elements, which are also be created dynamically.  So ideally, a new shortcut manager would handle both static action-based commands as well as dynamic ones like plugins and palettes elements.

**Comment by igorkorsukov** [comment]
> It's the tying of shortcuts to "actions" that has always been the limiter - that restricts us to a predefined, compiled-in list. The plugin manager allows shortcuts to be assigned to plugins are loaded dynamically, and that's the key feature we also needed in order to allow the user to assign shortcuts to arbitrary palette elements, which are also be created dynamically. So ideally, a new shortcut manager would handle both static action-based commands as well as dynamic ones like plugins and palettes elements.

In the new system, an action may have arguments. Therefore, there can be, for example, the action of `add-palette-element` and, as an argument, a palette element, the main thing is that there should be the possibility of somehow identifying them, but I think this is solved.

**Pull request merged**
