### PR TITLE
fix #308281 : Blank upload dialog on MacOS Catalina + collect_artifacts

### PR DESCRIPTION
**Pull request by AntonioBL**
Resolves: https://musescore.org/en/node/308281

Apparently, QtWebEngine requires additional permissions to run under MacOS 10.15, see https://forum.qt.io/post/526704

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/WorkflowAndGuidelines/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ N/A ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by BernardGreenberg** [comment]
I, the original plaintiff, have verified that Antonio's executable really does solve the problem I reported.

**Comment by AntonioBL** [comment]
( Thanks, BSG 😄 )

**Additional note for the developers running MacOS Catalina:**
I had to downgrade the XCode in the Github actions otherwise the artifacts would crash on start because of something Apple did to their version of OpenGL in 10.15 sdk.
See:
https://www.geeks3d.com/hacklab/20191214/geexlab-0-29-9-1-released-with-macos-10-15-catalina-support/
https://github.com/TheInfiniteKind/appbundler/issues/70
https://github.com/google/filament/pull/1959/files
So, at the moment, a build of MuseScore made with the latest XCode will most probably crash on startup because of the "OpenGL can be called from the main thread only" limitation.

**Comment by BernardGreenberg** [comment]
This (OpenGL) issue looks like a disaster; does that cripple all Qt development toward Catalina, or only 5.9?

**Comment by AntonioBL** [comment]
> 
> 
> This (OpenGL) issue looks like a disaster; does that cripple all Qt development toward Catalina, or only 5.9?

Well, I really don't know for sure. I *think* Qt 5.14 could have some improvements in this field, but I didn't test it.

**Comment by anatoly-os** [comment]
Manually merged to master (8f0f185f909d8bcdbb8e494233d56ccaab5a7949)

**Pull request merged**
