### PR TITLE
fix #303495: ABC plugin not working on macOS 10.14 or later + collect_artifacts

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
by making it using https. Hopefully solves https://musescore.org/en/node/303495
Switch to using https in some other places too.
wanted

### CODE REVIEW

**Comment by anatoly-os** [comment]
@Jojo-Schmitz thanks man. Downloading the .dmg... I have macOS 10.15.x. Let's see...

**Comment by Jojo-Schmitz** [comment]
first please check whether you can reproduce the issue ;-)

**Comment by anatoly-os** [comment]
ABC plugin works for me.

**Comment by Jojo-Schmitz** [comment]
3.4.3?

**Pull request merged**
