### PR TITLE
make revision is now a target handled by cmake and depended on by mscore

### PR DESCRIPTION
**Pull request by akdor1154**
make revision is now a target handled by cmake, which is depended on by the mscore target and always run when mscore is built. This means that if I 'git pull' and then 'make' in my build directory, the resulting build will have the correct revision. Likewise for if I do the above in Qt Creator.
The code also changes the revision to 'unknown' if it can't find Git -- according to the README in git/hooks, the repo is meant to have revision.h contain 'unknown' anyway, but it looks like an actual revision was committed by mistake last year. As the build script now generates revision.h automatically and in all cases, there is no need for revision.h to be in the repository at all, which should reduce the chance of it being accidentally committed in future.
The only user-facing change is that 'make revision' in the project directory no longer works, you have to call it in your build directory (though you should honestly never have to call it manually at all).

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Unless that relink on every run gets fixed, this should not get merged, linking, esp, on Windows, is way too expensive.

**Comment by akdor1154** [comment]
Try that? Seems to work here with both cmdline cmake and Qt Creator, on Linux.

**Comment by Jojo-Schmitz** [comment]
No, not tried, I just trusted you own words "currently this makes qt creator want to relink mscore every time it's run"

**Comment by akdor1154** [comment]
No, I mean try with the commit I just pushed, it should fix the problem. :)

**Comment by Jojo-Schmitz** [comment]
Ah, I didn't notice the newly added commit.

**Comment by Jojo-Schmitz** [comment]
Ah, I didn't notice the newly added commit.

@lasconic had other issues with it though, when we discussed it in IRC yesterday, along the lines of "if it ain't broke, don't fix it".

**Comment by akdor1154** [comment]
ah, ok. Well, my rationale is that it's again working towards the standard approach for CMake-built projects - that is, mkdir NewDir; cmake ..; make; . Currently this approach fails because there's still some essential logic in the main handwritten makefile. This means Qt Creator would not automatically build the revision as above, for example, and also is a further impediment to using MSVC on Windows (the second point is not an immediate concern, I am aware). Having logic split between different build systems negates a lot of the benefit of CMake.

**Comment by Jojo-Schmitz** [comment]
I'm still for that PR, and we do see occasions where this indeed is broken, so it does need fixing, there are numerous bug reports from Linux users with the wrong commit, 3543170, apparentle because the maintainer didn't have that post-checkout hook installed and/or also did not do a `make revision`
And it isn't just Linux, @jeetee had an issue with the post-checkout hook on Windows, using tortoisegit(?)

**Comment by jeetee** [comment]
My specific issue seems to have been given by some combination of TortoiseGit and QtCreator. I've added a simple echo statement to the hook to verify its execution; after switching back to one of my development branches and then back to master (+building again) the revision stamp is now correct.

**Comment by anatoly-os** [comment]
I cannot imagine why these changes were needed. @lasconic do you?
We still use git to extract revision, so this PR didn't survive through the time :)

**Comment by Jojo-Schmitz** [comment]
@anatoly-os see my comment from Oct 24 2016 on why this is (or was) needed

**Comment by anatoly-os** [comment]
Ah, I see. So, the issue is people checkout the repo, build MuseScore and then report the issues using about window. In this case revision is incorrect, isn't it?

**Comment by Jojo-Schmitz** [comment]
Worse: even distribution maintainers seem to have done this (too).
And every once in a while we see PRs that have this file committed too.

**Comment by shoogle** [comment]
The issue for some distributions is that they build from the tarball rather than from a Git checkout, so they can't call `make revision` since they are not in a git repository. I [solved this on Debian](https://salsa.debian.org/multimedia-team/musescore/blob/master/debian/repack) by using the GitHub API to retrieve the commit number of the tagged release and setting this in the mscore/revision.h file.

**Comment by shoogle** [comment]
More options which can replace/be used in combination with the two @Jojo-Schmitz just mentioned:

- Use the API method as a fallback to retrieve the revision number. Only do this if:
    - the build is marked stable (i.e. there is a matching tag on GitHub),
    - the revision number was not already set with `git` (not GitHub).
- Ignore the revision number entirely on stable builds and just use the version number.

**Comment by shoogle** [comment]
Another complication is the fact that some distributions build packages on virtual machines that do not have internet access. This is done deliberately to prevent precompiled code being fetched from the internet and injected into the build, but it also means that they won't be able to fetch the revision number via the GitHub API.

A more reliable solution might be:

- Commit a fixed revision number with stable builds.
  - Note: The act of committing changes the revision, so the reported revision would be from the commit before the actual tagged release commit, but that's not a big problem.
- Ignore the revision number entirely on stable builds and just use the version number.

I'm in favour of dropping the revision number for stable builds and just reporting the version number in the Help > About dialog.

Maybe @mirabilos (current maintainer on Debian) has something to say on the matter?

**Comment by mirabilos** [comment]
Peter Jonas dixit:

>Maybe @mirabilos (current maintainer on Debian) has something to say on the matter?

We’re generating mscore/revision.h as part of the download
process of the “orig tarball”, since we download straight
from git, remove a few non-free/precompiled files, and make
our own “repacked origtgz” from it.

**Comment by shoogle** [comment]
@mirabilos, yes I know (I wrote the repack script :wink:). But the point is that maintainers on other distributions probably won't bother writing a script to fetch the revision from GitHub, and we can't do it for them as part of the build process because builds are often done inside a chroot that lacks internet access (at least that is the case on Launchpad). I wondered if you had an opinion on whether `mscore/revision.h` should be used at all for stable builds?

My view is it's not necessary because stable builds have a version number anyway (e.g. 2.3.2) so we don't need anything else to identify them.

**Comment by mirabilos** [comment]
Peter Jonas dixit:

>@mirabilos, yes I know (I wrote the repack script :wink:). But the

Ah right ;-)

>@point is that maintainers on other distributions probably won't
>@bother writing a script to fetch the revision from GitHub, and we

Perhaps, yes. But I see the version number in e.g. the top-level
Makefile as “VERSION”. One could use that in the absence of a
more specific revision.h file.

>@can't do it for them as part of the build process because builds are
>@often done inside a chroot that lacks internet access (at least that

That’s not the primary problem. The primary problem is that
packagers normally work from tarballs or similar distfiles,
even when dealing with git snapshots, so git metadata won’t
be available.

With CVS we could just use RCS IDs, but… meh.

>@is the case on Launchpad). I wondered if you had an opinion on
>@whether `mscore/revision.h` should be used at all for stable builds?
>
>My view is it's not necessary because stable builds have a version
>number anyway (e.g. 2.3.2) so we don't need anything else to identify
>them.

The identifyer is part of the file format, so hmm, but that
could be changed of course. Plus, it’s perhaps not so much
relevant, because distro packagers often patch stuff anyway.

So, maybe, for stable releases use the release string, which
is in Makefile already anyway, and for non-stable releases,
use revision.h if it exists, and the VERSION string from
Makefile (like 2.3b) as a fallback.

**Comment by shoogle** [comment]
> But you don’t know, from an arbitrary checkout, which revision it corresponds to.

I don't anticipate anyone building a non-stable build from a tarball, and stable builds can be matched to tags. For unstable builds, the current `git --rev-parse` method would be used.

Anyway, it sounds like we are agreed that revision numbers are unnecessary for stable builds.

**Comment by lasconic** [comment]
*The issue for some distributions is that they build from the tarball rather than from a Git checkout*

Well, we do create a zip file with the correct revision.h. This is part of our release process.  By providing it, I thought that it would help distrib maintainers who can't access git or even the network but it seems it doesn't and instead they prefer to do their own (different) stuff themself.

My only concern if we don't provide SHA for stable is that "version number" will look different for our less tech inclined testers between stable and dev versions.

**Comment by shoogle** [comment]
> we do create a zip file with the correct revision.h

I didn't know that, so I doubt many maintainers did either. I've seen the "get source code" link on the downloads page, but I didn't know it was different to the tarball on GitHub. Maintainers might even avoid it specifically because it is different to the tarball.

Other reasons maintainers will avoid/not find the Zip download:

- Maintainers will follow standard procedure for their distribution.
- All maintainer tutorials going to feature an example of downloading from GitHub releases, so maintainers will probably look there first without thinking.
- Zip doesn't preserve file permissions whereas Tar does.

> My only concern if we don't provide SHA for stable is that "version number" will look different for our less tech inclined testers between stable and dev versions.

I personally find it more confusing that stable builds feature both a version and a revision number, as though the version isn't enough on its own.

We can avoid the confusion in development builds by just show the revision and the message "please quote the revision in bug reports". In stable builds just show the version.

**Comment by mirabilos** [comment]
Nicolas Froment dixit:

>Well, we do create a zip file with the correct revision.h. This is
>part of our release process.

That reduces the concerns about revision numbers for stable releases.
So if a distro doesn’t take your revision.h file, they’ll have to
generate it, “period”. No need to change the format.

For snapshots, things are a bit different, I guess. But people who
package snapshots have other things to deal with, so it’s not an
unexpected burden.

One caveat, though: PKZIP archives are not an accepted distfile
format in the Unix world. I suggest to provide gzip(1)-compressed
ustar archives (“.tar.gz”) as well.

>it seems it doesn't and instead they prefer to do their own
>(different) stuff themself.

Speaking for Debian, our infrastructure can only deal with
ustar archives, and we could use your provided release source
archive if it were one, but I prefer to use the same scripts
and methods to generate release tarballs for snapshots and
final releases, to lessen the surprise, so it’d be actually
*more* work for us to use it.

We have to repack it to remove precompiled and some other
files already anyway.

>My only concern if we don't provide SHA for stable is that "version
>number" will look different for our less tech inclined testers between
>stable and dev versions.

Hm.

Shoogle suggested to not use them, but from the Debian side
we actually don’t care. (That is, actually I do: anything you
change means I have to change our workflow too, which is work ☺)

I can’t very well speak *for* other distro packagers, just
assume things from my knowledge of having packaged for a
lot of distributions and BSDs.

Shoogle did mention Launchpad. I have plans for Launchpad for
nightly builds, none of which will have any problem with doing
the same revision.h creation dance that we do. (I just haven’t
any free time at the moment, and in fact am rather in need of
an actual holiday/vacation.)

**Comment by mirabilos** [comment]
Peter Jonas dixit:

>I personally find it more confusing that stable builds feature both a
>version and a revision number, as though the version isn't enough on
>its own.

It makes more sense if you think of it as: each build has a revision
number corresponding to the state of the source tree that it was built
from, and stable releases in addition have “tags” (version numbers).

**Comment by shoogle** [comment]
> It makes more sense if you think of it as: each build has a revision number corresponding to the state of the source tree that it was built from, and stable releases in addition have “tags” (version numbers).

I understand what the revisions are (which is why I know they are not necessary for stable builds), but I doubt the average user understands, and I don't think an explanation in terms of "source trees" and "tags" is going to help them.

I think it's much easier just to say "unstable builds don't have version numbers so we identify them using revision numbers instead".

**Comment by Jojo-Schmitz** [comment]
I'd still like this, as the issue with a wrong revision being reported comes up time and time again, but a rebase is needed meanwhile

**Comment by Jojo-Schmitz** [comment]
At least we should get back to the state of PR #188, which made revision.h to contain "unknown"

**Comment by Jojo-Schmitz** [comment]
With #6793 (and a port of that for the 3.x branch) I guess this can get closed?

**Pull request closed without merging**
