### PR TITLE
Improve tremolo layout

### PR DESCRIPTION
**Pull request by pgkos**
I would like to suggest the following improvements to the two-note tremolo layout:
* if the second note (chord) is lower than the first, then the tremolo's `QPainterPath` is mirrored,
* the tremolo's path is more visually centered horizontally between the two chords,
* the tremolo's path is centered vertically in case of stemless notes

I have taken care to support the case of cross-staff tremolos.

Before:
tremolo_before

After:
tremolo_after

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
This should fix [https://musescore.org/en/node/29686](issue #29686), unless I'm misunderstanding something?
I think you'd still need to sign the [CLA](https://musescore.org/cla)...

**Comment by lasconic** [comment]
Thank you for taking a look to this!
We have an issue open about this topic. https://musescore.org/en/node/29686
Ideally the tremolo should follow the beam angle but that's already a lot better

The last change *the tremolo's path is centered vertically in case of stemless notes* is not really standard apparently. Gould advise to position the tremolo beams as if the whole note were stemmed.

**Comment by Jojo-Schmitz** [comment]
"Center between stems" would also look better on those minim example

**Comment by Jojo-Schmitz** [comment]
"Center between stems" would also look better on those minim example (but in x direction, I think @lasconic meant y direction?)

**Comment by pgkos** [comment]
I have just signed the CLA (as pgkos).

Thank you for taking interest, I will fix the issues you mentioned (I will also try to make the tremolo follow the beam angle).

So please don't merge this PR yet!

**Comment by Jojo-Schmitz** [comment]
Maybe you find a solution for [issue #18897](https://musescore.org/en/node/18897) too?
Would require some preference/style setting though.

**Comment by lasconic** [comment]
Great actually if you are working on this, let me send you a couple of pages of Behind Bars via email.

**Comment by pgkos** [comment]
Okay, so this is what I have done so far:
tremolo_2

* the tremolos follow the beam angles (I just used a shear transform)
* (hopefully) all cross-staff cases are handled properly
* stemless tremolos behave as if the notes had stems of the default length
* the tremolos don't touch the stems &ndash; horizontal length of the tremolo lines is (now) calculated using the following formula: `tremoloLineHorizontalLength = 0.62 * horizontalDistanceBetweenStems`, which I think looks quite nice
* the tremolo is always ideally centered between the stems (not between the notehead centers)

I am open to any suggestions.

**Comment by pgkos** [comment]
Actually, I made a typo in `tremolo.cpp` (which I will correct in a minute), which caused the new tremolos to be thicker than before. In fact, the original thickness is too small in my opinion:
zaznaczenie_005
Probably we should make the tremolo's thickness match the beam thickness (via `StyleIdx::tremoloStrokeWidth`)?

**Comment by lasconic** [comment]
I would cap the tremoloLineHorizontalLength to a max constant. This constant can then be added as a style parameter. Idem for the the 0.62 magic value, we could put it in style later on. Maybe add a TODO comment.
I'm ok to change the default strokeWidth of tremolo in style to be closer or even equal to beam thickness.

**Comment by pgkos** [comment]
You mean the maximum horizontal length? Like this?
```c
tremoloLineHorizontalLength = 0.62 * horizontalDistanceBetweenStems;
if (tremoloLineHorizontalLength > MAXIMUM_TREMOLO_HORIZONTAL_LENGTH) {
    tremoloLineHorizontalLength = MAXIMUM_TREMOLO_HORIZONTAL_LENGTH;
}
```

**Comment by lasconic** [comment]
Yes I guess. I'm talking about "Beams for widely spaced tremolo notes may be uniformly shortened so as not to look ungainly" in Behind Bars.

**Comment by lasconic** [comment]
One more thing you might want to take a look. We have visual tests for behaviors that are hard to test programmatically http://vtest.musescore.org/f6959ace/vtest.html You can found them in the vtest directory of the source. Maybe you could add one or two based on the examples you already have.

**Comment by pgkos** [comment]
Correctly styled version:
zaznaczenie_007
The tremolo line thickness is exactly the same as the beam thickness.
The tremolo in the second system is shortened. I have added an upper bound of `12.0`. If you would like to adjust it, you can edit it [here](https://github.com/pgkos/MuseScore/blob/tremolo-layout/libmscore/tremolo.cpp#L291), or, if you decide to add the styles, [here](https://github.com/pgkos/MuseScore/blob/tremolo-layout/libmscore/style.cpp#L565).

**Comment by pgkos** [comment]
I have added a visual test.

**Comment by lasconic** [comment]
It's looking better and better. 
* Somehow the angle of single note tremolo has changed. The should always slant from bottom left to top right but the slant should be smaller. It's noticeable in the second measure of the vtest. I think there were correct before. 
* Regarding the single tremolo stroke width... Behind bars mentions that these tremolos (single note ones) should be a little thinner than a beam "this is so that the spaces between the strokes are slightly wider than between beams (the spacing of strokes between for both is the same)"
* The vertical position in measure 3 and 4 is weird if you consider page 227 of behind bars/

**Comment by Jojo-Schmitz** [comment]
You mean measure 3 and 5, don't you (measure 4 is empty)? I think all the tremolos between whole notes look strange (but have no ides what Behind bars recommends them to look), but indeed those in measures 3 and 5 don't seem to take the correct 'virtual' stem direction into account (first note stem down, 2nd note stem up, or vice versa, but surely not both up)

**Comment by pgkos** [comment]
Regarding bars 3 and 5, this is just an example test and I deliberately made **both notes' "virtual" stems go up** (using X key).

**Comment by MarcSabatella** [comment]
For whole notes, the statement is "position the beams as if the semibreves were stemmed", and she shows a picture with dotted lines indicating where the stems would be.  I agree the examples posted look odd, but they are also kind of odd cases - cross staff beaming, very large intervals, very wide spacing, etc.  The more usual cases would preusmably look fine.

I agree that somehow the single note tremolo in bar 2 has changed for the worse, though.

I'm mostly just chiming in to express my appreciation for the work you've done @pgkos !

**Comment by Jojo-Schmitz** [comment]
Ah, that (making virtual stems go up) certainly explains the strange look

**Comment by pgkos** [comment]
Thank you for your kind words, @MarcSabatella !

The single tremolos have bad angle because I have made another typo in the same line :smile:

**Comment by lasconic** [comment]
Some extreme cases that you might want to consider
capture d ecran 2015-06-23 21 13 05

1/ if the gap between the note is big, the shearing makes the "beam" look very small. We have the same problem with "normal" beams btw.

2/ Using a 4 stroke tremolo, there can be collision with the notehead and or the accidentals. Maybe the tremolo could be shorter in this case? It's quite extreme though

3/ There is a problem if the notes have opposite direction (first two beats here). I took this example from Behind Bars, page 226.

capture d ecran 2015-06-23 21 27 10

**Comment by pgkos** [comment]
Case 3 should be quite easy to improve, but cases 1 and 2 will be hard to implement correctly (we have to find a sensible workaround).

case 1. I could stretch the tremolo vertically so it would be thicker, but in case of very narrow space between two notes, it could become too stretched and extend beyond the notehead. Besides, if the beams thickness (as implemented now) also decreases when the shearing is big, it makes no sense to apply the thickening only to tremolos.

case 2. Unfortunately, there always is a chance that the accidental will collide with the tremolo (try the double flat for example). In that case, if I shortened the tremolo, it would almost disappear completely:
zaznaczenie_009

**Comment by MarcSabatella** [comment]
To me, case 2 is not worth solving by automatically right now, as long as manual adjustment of stem length and/or tremolo position can achieve the desired result.  Case 1 is interesting for sure, but as it is the exact same issue with beams, I don't see the need to solve it specially here.  Worth looking later for both beams and tremolo, though.

**Comment by lasconic** [comment]
I agree with both of you. I was just laying out the issues. It's more than fine by me if case 3 is the only one tackled.

**Comment by pgkos** [comment]
I have just implemented/improved the case 3.

I also did a small clean-up of code and fixed one issue: now the stem length is computed correctly. It seems that the method `Stem::stemLen()` does not return the actual stem length if it is modified by the user! So I had to use`Stem::p2().y()`.

**Comment by lasconic** [comment]
Could you update the vtest. I think second measure, bass clef will look different. Except this, I believe it's ready to merge.  Maybe you can squash some less interesting commits (or even all?) http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by lasconic** [comment]
mm actually one more thing.. Sorry... If you drag a tremolo, like the one in the second system of the vtest, you will see that the bbox is not correct and it leads to a trace one the screen.
tremolo

**Comment by pgkos** [comment]
Yeah, I was aware of these weird artifacts, they also sometimes show when you move the page &ndash; so I will just call `setbbox()` after modifying the tremolo's path.

**Comment by lasconic** [comment]
Thanks for the bounding box fix. It looks great now.
Could you squash the commits together? http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by pgkos** [comment]
Yes, sorry, I was quite busy. I will squash the commits shortly.

**Pull request merged**
