### PR TITLE
[MU3] Fix #18038: Change checkboxes to radio buttons for transpose dialog and page style groupboxes

### PR DESCRIPTION
**Pull request by IsaacWeiss**
Resolves: https://musescore.org/en/node/18038

Follow-up to #6989 using our custom radio button groupboxes, introduced in #5992.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
In the Transpose dialog is a similar situation. Maybe you could solve that one too!

**Comment by chenlung** [comment]
Thank you, Isaac!

**Comment by chenlung** [comment]
Can the title be changed to mention the issue number?

**Comment by Jojo-Schmitz** [comment]
And the "Resolves: none" getting corrected ;-)

**Comment by vpereverzev** [comment]
This mtest failure shouldn't be related with this PR, but could you rebase the branch on the latest 3.x, just to be sure

**Comment by Jojo-Schmitz** [comment]
Seems that [mtest failuter](https://github.com/musescore/MuseScore/pull/7037/checks?check_run_id=1512813274#step:5:778) is unrelated

**Comment by IsaacWeiss** [comment]
Rebased since #7154

**Pull request merged**
