### PR TITLE
Add Brass Band Templates

### PR DESCRIPTION
**Pull request by ChurchOrganist**
Fix for issue #31371 kindly supplied by no3333 - several templates added for UK Brass Band and Salvation Army Band brass formats

### CODE REVIEW

**Comment by lasconic** [comment]
I'm not sure we want to have all these anecdotic (?) templates in the package.
Also SA Truimphonic Collection.mscz should be SA Triumphonic Collection.mscz and the filename should feature underscores instead of spaces.
@wschweer @MarcSabatella any opinion?

**Comment by ChurchOrganist** [comment]
Do you mean anecdotal Nicolas?

I think you need at least one of each of these in the final release, as they represent the 2 variations of UK brass band - competition and Salvation Army.

As I've metnioned before I have virtually no experience of scroing for brass band but there is some information here which you may find helpful: http://www.bandsman.co.uk/writing.htm

**Comment by lasconic** [comment]
Indeed anecdotal is the word. So yes, having one or two of them, maybe the biggest ones since it's easier to remove instrument than adding some? Why not. But having a dedicated category for UK Brass Band and one for Salvation Army, it seems to much to me. Of course, I have no experience in scoring for Brass Band either.

**Comment by MarcSabatella** [comment]
If it were me, I'd have a generic "Band" cateogry and add all of them to
that.  At least, all the ones worth adding - I think having all those
subtlte variations is out of character (we don't have a thousand varieties
of orchestra, or jazz combo).  Within the "Band" category, I'd expect to
see one UK brass band template, one Salvation Army template, and then a
"Marching Band" (common US variety), "Symphonic Band", and "Wind Ensemble".

Of course already have a "Band" category, but I think it's poorly named.
 "Pop" might be a better name for the category.

**Comment by lasconic** [comment]
Bring on the templates :)

**Comment by ChurchOrganist** [comment]
Closing this will re-submit with UK and SA brass band templates

**Pull request closed without merging**
