### PR TITLE
fix #270496: Add missing elements to incomplete tuplets when reading …

### PR DESCRIPTION
**Pull request by mattmcclinch**
…from a file

See [issue 270496](https://musescore.org/en/node/270496).

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Better rebase to the new 2.3 branch ;-)

**Comment by anatoly-os** [comment]
@mattmcclinch could you please rebase it to 2.3 branch?

**Comment by anatoly-os** [comment]
@mattmcclinch @Jojo-Schmitz is this fix complete? I understood from the comment in the issue that this fix is not complete. Am I wrong?

**Comment by mattmcclinch** [comment]
Yes, this fix is complete. I apologize for the confusion brought on by my comment.

**Pull request merged**
