### PR TITLE
partial fix #121706: custom dashed options not working

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
and having bad defaults and backward compatibility issues,
esp. for dim./cresc. lines.
Also fix capitalisation of  "Set style" button and
accessibility info and buddies for inspector_line.ui

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Shouldn't those values of dash length and dash gap be expressed in sp?

**Comment by lasconic** [comment]
Definitely need to be in spatium indeed.

**Comment by Jojo-Schmitz** [comment]
how?

**Comment by Jojo-Schmitz** [comment]
Not quite there yet, but maybe this helps in finding where I go wrong?

**Comment by Jojo-Schmitz** [comment]
With this the dashes and gaps are way too wide and I don't get why, and hint would be appreciated

**Comment by lasconic** [comment]
So I was wrong, it doesn't need to be a spatium. Qt expects a factor of the "line width" for the dash gap and dash length. So it should already scale correctly with the spatium. Thank you for looking into it, Werner will use your code to make a proper fix.

**Pull request closed without merging**
