### PR TITLE
[MU4] Fix #69291 Fix #306387 - Stems are too long on small chords with beam…

### PR DESCRIPTION
**Pull request by njvdberg**
…s or flags

Resolves https://musescore.org/en/node/69291
Resolves https://musescore.org/en/node/306387

Shortens the stems of cue (small) notes by 1.0sp.

The 4 updates are intentional, there contains now the shortened stems.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/WorkflowAndGuidelines/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by njvdberg** [comment]
These images show the difference between the old situation:
old

Now the stems look like:
new

This PR is based on <code>master</code>, but if this PR should be included in the coming 3.5 (which I don't think because the beta is out already), I can make a PR based of <code>3.x</code>.

**Comment by Howard-C** [comment]
It can still be included in 3.5.1.

**Comment by njvdberg** [comment]
> It can still be included in 3.5.1.

That's  good idea :thumbsup:.
The PR itself isn't that difficult, I'll  make a dedicated PR for <code>3.x</code> soon.

**Comment by njvdberg** [comment]
CI_vtests  shows 3 differences:

<code>Comparison of chord-layout-16 gave result 224</code>
<code>Comparison of beams-9 gave result 4106</code>
<code>Comparison of slash-2 gave result 100</code>

These difference were expected and this PR contains the correct references.

**Comment by Jojo-Schmitz** [comment]
and bugs in 3.5 Beta can still get fixed to I guess, even if it isn't fixing a regression

**Comment by vpereverzev** [comment]
@njvdberg could you rebase it on current master?

**Comment by njvdberg** [comment]
> @njvdberg could you rebase it on current master?

Done

**Pull request merged**
