### PR TITLE
Slight changes to labels in Preferences dialog

### PR DESCRIPTION
**Pull request by IsaacWeiss**
Fixed all lowercase names of things normally capitalized and bad use of “style.”

### CODE REVIEW

**Comment by lasconic** [comment]
We don't use Title case but Sentence cases for checkboxes. See https://musescore.org/en/developers-handbook/design/user-interface-text-style-guide 
Theme is fine. I will add it in another commit.

**Comment by lasconic** [comment]
See 53f9f3f45df1ae13f8a2a1f5f6938fef6671e6d1

**Comment by IsaacWeiss** [comment]
@lasconic I was thinking that it's not simply the stand-alone checkbox here—it's actually referring to something else that has a specific name in the UI, documentation, and general use (forum discussions), and that name is capitalized. It's not the play panel, it's the Play Panel, the same way the program is not musescore, it's MuseScore. Is the sentence case guideline an overriding requirement?

**Comment by lasconic** [comment]
In other places we solved this by using `Show 'Play Panel'` ... I'm not huge fan... and I'm fine with the current texts in preferences.

**Pull request closed without merging**
