### PR TITLE
Breakpad integration

### PR DESCRIPTION
**Pull request by dmitrio95**
A work-in-progress PR to integrate Google Breakpad into MuseScore for handling crashes and sending crash reports.

### CODE REVIEW

**Comment by dschmidt** [comment]
Hey @dmitrio95,

regarding your license questions:
I recently relicensed the libcrashreporter-qt code itself to LGPL 2.1. Breakpad is BSD 3 clause iirc. You only need to be careful with the dr. konqi kde crash reporter integration. That imports GPL code, so you need to compile with `option(ENABLE_GPL_CODE OFF)` which also happens to be the default :-) 

Hope this helps,
Dominik

**Comment by dschmidt** [comment]
I usually do not recommend to fork libraries… if you can provide proper patches that make vanilla libcrashreporter-qt work for you without modifications and doesn't break anything for anyone else, I'm happy to merge them.

**Comment by mirabilos** [comment]
Please cherry-pick commit 8ba59492ab1ffbcd7c2dfedbe9319b43aa360051 from the https://github.com/google/breakpad repository, in order to retain all upstream licences (see [here](https://github.com/dschmidt/libcrashreporter-qt/commit/e97eee4ca59177170c566f7b3bbd63d49cf03ecb#commitcomment-32337062) for details if interested).

Thank you for making this optional. A phone-home functionality like this is not allowed in Debian, and this makes it easy for me to disable it in the packages.

**Comment by dmitrio95** [comment]
@dschmidt @mirabilos thanks for the legal reference, I'll add that license information commit then.

I'll try to get my changes to a state that would allow them to be merged into libcrashreporter-qt. Probably the most important change is a possiblility to disable the crash reporter GUI component which seems to require dr. konqi on Linux and requires a specific server configuration. Also I made an attempt to add CMake build scripts for `dump_syms` tool but I am not sure whether I go with that far enough.

**Comment by dschmidt** [comment]
A way to disable dr. konqi is certainly appreciated.

You could take my CMake script to build dump_syms, it's currently only part of a PR: https://github.com/KDE/craft/blob/a07807e286d6a8d815b282bf35481b188c66f9d5/blueprints/dev-utils/breakpad-tools/0001-Add-CMake-script-to-build-dump_syms.patch

Feel free to license it as any MIT or BSD license - I think there's a standard for CMake scripts, probably best to take that. In thend I don't care, pick whatever suits you best :-)

**Pull request merged**
