### PR TITLE
Update Wood Block in instruments.xml

### PR DESCRIPTION
**Pull request by zacjansheski**
Run instruments python script.
Change Wood Block Instrument program to (hopefully) fix https://github.com/musescore/MuseScore/issues/17104

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by zacjansheski** [comment]
Turns out this doesn't actually fix the issue.

@shoogle  do you have any guess why?  Changing the MS Basic instrument to the standard drum set gives the desired two pitches of woodblocks.  But my PR didn't get the selection to update.

Screen Shot 2023-08-25 at 5 12 14 PM

**Comment by zacjansheski** [comment]
Thank you!  Works as desired now.  @shoogle was there something else in the spreadsheet I was supposed to update?  I updated soundmapping.h manually

**Comment by shoogle** [comment]
@zacjansheski, nope! You've done all that is required in the spreadsheet and in the code.

However, we shouldn't see any 'merge' commits in the [PR branch history](https://github.com/musescore/MuseScore/pull/19171/commits).

image

To fix this in GitHub Desktop:

1. Change current branch to `master`.
2. Go to _Branch > Update from upstream/master_.
4. Change current branch to the one you are working on (i.e. `WoodBlock`).
5. Go to _Branch > Rebase current branch_ and choose `master`.
    - You'll see the message: _"This will update `WoodBlock` by applying its commits on top of `master`."_
6. Click "Rebase".
7. Force push to update the PR.

Never use the _Update from upstream/master_ option on a branch that isn't `master`. Always update `master` first then rebase your other branches on top of it.

**Comment by zacjansheski** [comment]
@shoogle done, thank you!

**Review by shoogle — APPROVED** [review]

**Pull request merged**
