### PR TITLE
Whitespace removal.

### PR DESCRIPTION
**Pull request by awelch83**
@Jojo-Schmitz This pull request should reflect the changes that I made to my local branch (the rebasing, etc..)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
No, it still has those 2 merge commits in it, You'd need to get rid of those. first get rid of those:
   git reset --hard 9f8763e
optionaly rebase:
   git fetch upstream ; git rebase upstream/master
then push again:
   git push -f

**Comment by awelch83** [comment]
@Jojo-Schmitz Done. Thanks again - I really appreciate your patience. I had just misread your instructions earlier, on #1690. Anyway, now it looks like I just need to await the outcome of the Travis CI build

**Comment by Jojo-Schmitz** [comment]
Yes, this looks clean now. Now patience with Travis ;-)
One way to get it thru is
   git commit --amend
save the file containing the commit message with or without changing
   git push -f
Repeat until Travis doesn't abort due to some resource shortages but either fails with a syntax error during compile or an error during test or succeeds.

**Comment by awelch83** [comment]
I've actually already done the git commit --amend step once, but I'll repeat after lunch if it hasn't gone through by then

Sent from my iPhone

On Jan 28, 2015, at 13:38, Joachim Schmitz <notifications@github.com> wrote:

Yes, this looks clean now. Now patience with Travis ;-)
One way to get it thru is
git commit --amend
save the file containing the commit message with or without changing
git push -f
Repeat until Travis doesn't abort due to some resource shortages but either fails with a syntax error during compile or an error during test or succeeds.

**Comment by Jojo-Schmitz** [comment]
Needed once more (at least)

**Comment by awelch83** [comment]
@Jojo-Schmitz The build failed due to a compilation error. This is due to an error somewhere on my part, right?

**Comment by Jojo-Schmitz** [comment]
No, it didn't.
c++: internal compiler error: Killed (program cc1plus)
basically means it ran out  resources.
same for an aborting ld

**Comment by awelch83** [comment]
@Jojo-Schmitz Finally, it finished :)

**Comment by Jojo-Schmitz** [comment]
Why close?

**Comment by awelch83** [comment]
@Jojo-Schmitz I was experimenting with the command line, and as a result wound up thoroughly making a mess of my pull request. Since I didn't know how to go back and undo all of my mistakes, I figured I'd just close the request and resubmit when I've fixed things.

**Pull request closed without merging**
