### PR TITLE
Moved edit* sources to separate dir

### PR DESCRIPTION
**Pull request by igorkorsukov**
To make the code more structured, I moved edit* sources to separate dir  

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue

### CODE REVIEW

**Comment by Howard-C** [comment]
I wonder whether this change can hide the files from being easily discovered by new contributors.

**Comment by igorkorsukov** [comment]
> I wonder whether this change can hide the files from being easily discovered by new contributors.



> I wonder whether this change can hide the files from being easily discovered by new contributors.

I hope the opposite, in the future, new contributors will clearly see what modules and subsystems there are in the project, and accordingly their source code. Now it is not at all clear what this or that source file belongs to.

**Comment by Howard-C** [comment]
But `edit` is an ambiguous name, probably `editdialogs`? It's long but it's clear.

**Comment by RobFog** [comment]
Rebase needed.

**Comment by anatoly-os** [comment]
@igorkorsukov rebase needed

**Comment by igorkorsukov** [comment]
> But `edit` is an ambiguous name, probably `editdialogs`? It's long but it's clear.

I agree.
In fact, I think that we need to more closely examine and structure these files. At the moment, I tried to reduce the complexity, and then investigate in detail.

**Comment by igorkorsukov** [comment]
I decided to close this PR, because all these files should be located in different places (should be grouped by subsystems, and not by actions)

**Pull request closed without merging**
