### PR TITLE
adjust new score template and my first score to new/changed defaults

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Some settings in General Style have changed their defaults, the empty new score template and "My First Score" don't reflect those changes

* Clef left margin, from 0.64sp to 0.80sp
* Clef/Key right margin, from 1.75sp to 0.80sp
* Pedal line, Position Below, from 0.00sp to 4.00sp
* Trill line, Position Below, from 0.00sp to -1.00sp
* Lyrics, Min. bottom margin, from 4.0sp to 3.0sp

### CODE REVIEW

**Comment by lasconic** [comment]
Can you list the changes?

**Comment by Jojo-Schmitz** [comment]
See above, I was on it already ;-)

**Comment by Jojo-Schmitz** [comment]
diffing the mscx files shows some surprising results, I see none of the changes mentioned above, but other changes instead. in addition to changing file format version it add a style for minMMRestWidth and text styles for Dynamics and Rehearsal Mark, loses a `pos="0"` on long and short instrument name, with both scores and changes duration tags from `<duration z="4" n="4"/>` to `<duration>4/4</duration>`and loses the paise property for layout breaks for My First Score.
I guess the latter changes are OK, the former are not?

**Comment by Jojo-Schmitz** [comment]
Same or similar changes need to be done for all templates at some point.

**Comment by Jojo-Schmitz** [comment]
note to myself: rebase needed

**Comment by Jojo-Schmitz** [comment]
Closer look revealed that this PR is not needed anymore

**Pull request closed without merging**
