### PR TITLE
   fix #108206: Add natural sharp and natural flat to accidentals palette

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
see also https://musescore.org/en/node/108191

Missing: support for these in Emmentaler and Gonville, as well as proper
vtests

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
In connection with this PR and the recent additions of 4-string Tab clefs it might make sense to make Bravura the default font?

**Comment by mgavioli** [comment]
Or add the missing glyphs in Emmentaler, if this is the problem (well, I greatly prefer Emmentaler look over Bravura's..., so I would prefer to keep it as a default..., but this is just my opinion, of course).

**Comment by Jojo-Schmitz** [comment]
@lasconic seems to prefer keeping Emmentaler as the Default too, sort of MuseScore's "Coprorate Identity". 
Adding the symbols to fonts as well as adding a fallback mechanism are beyond, my capabilities though.
Will split this PR into 3, one for each addition.
See #2826 and #2827

**Comment by lasconic** [comment]
To make it more clear, I kind of like the fact that MuseScore has a distinctive font compared to the other (commercial) software package. However bravura has a large coverage of symbols and in the past, it has been proven that it's hard to maintain several fonts at the same level (this problem will increase even more if we have a jazz font or more in the future). So I would indeed favor a fallback first instead of having Bravura as default.

**Comment by Jojo-Schmitz** [comment]
OK, fallback has just been implemented in 4b00406

**Comment by mgavioli** [comment]
As I said in https://github.com/musescore/MuseScore/pull/2826 , if nobody volunteers before, I can provide the missing glyphs in a few days.

**Comment by Jojo-Schmitz** [comment]
@mgavioli: see https://musescore.org/en/node/125546

**Comment by mgavioli** [comment]
@Jojo-Schmitz : thanks.

**Comment by mgavioli** [comment]
Added all missing glyphs in the SMuFL "Standard Accidentals" section:
addedaccidentals

Other additions will follow shortly (but up the end of week I am rather busy)

**Comment by lasconic** [comment]
Great. Not sure if the square brackets are needed, it would depend if the height of the accidentals are very different from Bravura.

**Pull request merged**
