### PR TITLE
[Test] Switch travis from 4.9 to 7.5 compiler

### PR DESCRIPTION
**Pull request by igorkorsukov**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
May need a newer distrubution? Like `xenial` rather than trusty` (as used for building the AppImages), or even `bionic` or `focal`?

**Comment by igorkorsukov** [comment]
> May need a newer distribution? Like `xenial` rather than `trusty` (as used for building the AppImages), or even `bionic` or `focal`?

Yes, I think it all needs to be updated.
Our DevOps is on vacation now, as he comes from vacation, we will do it. Or I'll do it later.

**Comment by shoogle** [comment]
Might be an opportunity to ditch Travis and switch to GitHub Actions exclusively.

**Comment by igorkorsukov** [comment]
> Might be an opportunity to ditch Travis and switch to GitHub Actions exclusively.

Could you write the pros and cons of both systems?

**Comment by shoogle** [comment]
@igorkorsukov, Travis does not have the ability to upload artifacts from a pull request (see travis-ci/travis-ci#5579). Otherwise they seem to offer basically the same set of features, but builds on GitHub Actions start sooner and finish faster.

There have been many occasions where the Travis build has:

- Triggered but stayed on "pending" for 30+ minutes before starting.
- Finished but waiting for 30+ minutes before marking itself successfully complete.
- Not been triggered at all.

The AppVeyor build seems more reliable, but even that spends a while on "pending" at peak times. So far the GitHub Actions builds all seem to have started immediately.

BTW, the current Travis build relies heavily on custom Bash scripts (in build/travis). If the CI system is changed then we should put as much code as possible in the CMake files rather than in custom scripts, to make it easier to run tests outside the CI environment. Also, I would run the tests in a Docker image to make it easier to switch CI system in the future.

**Comment by igorkorsukov** [comment]
with gcc 7.5 tst_scripting failed 

image

**Comment by igorkorsukov** [comment]
> @igorkorsukov, Travis does not have the ability to upload artifacts from a pull request (see [travis-ci/travis-ci#5579](https://github.com/travis-ci/travis-ci/issues/5579)). Otherwise they seem to offer basically the same set of features, but builds on GitHub Actions start sooner and finish faster.
> 
> There have been many occasions where the Travis build has:
> 
> * Triggered but stayed on "pending" for 30+ minutes before starting.
> * Finished but waiting for 30+ minutes before marking itself successfully complete.
> * Not been triggered at all.
> 
> The AppVeyor build seems more reliable, but even that spends a while on "pending" at peak times. So far the GitHub Actions builds all seem to have started immediately.
> 
> BTW, the current Travis build relies heavily on custom Bash scripts (in build/travis). If the CI system is changed then we should put as much code as possible in the CMake files rather than in custom scripts, to make it easier to run tests outside the CI environment. Also, I would run the tests in a Docker image to make it easier to switch CI system in the future.

**Comment by Jojo-Schmitz** [comment]
If you can't beat 'em, kill 'em ;-)

**Pull request closed without merging**
