### PR TITLE
[MU4] Fix #8109: Same shortcut for all items in "Recent Files" menu.

### LINKED ISSUE #8109: [MU4 Issue] Same shortcut for all items in "Recent Files" menu.
**Describe the bug**
When the `Recent Files` list contains several files, all files have the same shortcut:

**To Reproduce**
1. Start MuseScore
2. Open a few so the recent files list contains some data.
3. Open en Recent Files submenu.

**Expected behavior**
All items should have an unique shortcut, or no shortcut at all.

**Screenshots**

Screenshot_20210515_122555

**Desktop (please complete the following information):**
 - OS: Linux

### PR DESCRIPTION
**Pull request by JRYamasaki**
Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [x ] I signed [CLA](https://musescore.org/en/cla)
- [x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x ] I made sure the code compiles on my machine
- [ ] I made sure there are no unnecessary changes in the code
- [x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by JRYamasaki** [comment]
**The Bug**
Each menu item in the recently opened files list was given the action of "open-file" which had an associated shortcut

**The Fix**
Create a new action that does the same thing as the "open-file" action, but that has no shortcut

**Refactor**
Move around some variables or statements so that they accurately reflect the order of the action / menu items from the file menu

Below is a screenshot of what the fix looks like
image

**Comment by RobFog** [comment]
Please reference the issue this pull request fixes: https://github.com/musescore/MuseScore/issues/8109, both in the PR description and in the commit message.

**Comment by JRYamasaki** [comment]
@RobFog, Issue number has been added to the commit and PR

**Comment by Eism** [comment]
@JRYamasaki sorry for the late review

Better to create a new menu item instead of getting data from the action register

`        MenuItem item;
        item.code = "file-open";`
  instead of 
`MenuItem item = uiactionsRegister()->action("file-open-recent");`

And that's all you need to do

Then you won't need to create a new action with an empty shortcut

**Comment by JRYamasaki** [comment]
> @JRYamasaki sorry for the late review
> 
> Better to create a new menu item instead of getting data from the action register
> 
> ` MenuItem item; item.code = "file-open";`
> instead of
> `MenuItem item = uiactionsRegister()->action("file-open-recent");`
> 
> And that's all you need to do
> 
> Then you won't need to create a new action with an empty shortcut

I don't think I can do that. I tried to do that and the result was my OS opening up the file explorer for me to choose a file to open. Which makes sense because we are giving it the "file-open" item code. Do you mean

` MenuItem item; item.code = "file-open-recent";`?

That seems to work

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/8709

**Pull request closed without merging**
