### PR TITLE
3.0 spelling fixes

### PR DESCRIPTION
**Pull request by mirabilos**
Same as https://github.com/musescore/MuseScore/pull/3262 (cherry-picked) plus one additional set of fixes for master.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
The question is whether we should correct (minor) spelling mistakes in 3rd party code that are not user visible at all. Might just cause unneccessary merge conflicts when updating to newer versions of that 3rd party code.

**Comment by lasconic** [comment]
My vote is no

**Comment by RobFog** [comment]
Isn't it common practice in cases like this to submit a patch upstream?

**Comment by mirabilos** [comment]
@ submit a patch: probably, yes.

@ not merge: modern version control tools like CVS or even git make this easy enough, but since the 3rdparty stuff are just comments I can resubmit without those.

@ “possibile”: this should probably be done at SMuFL and just merged if they decide to change it; the flagged occurrences are for whole-words, so it’s only the glyph description which is in question, but if it’s correct as-is I can override the lintian warning.

**Comment by Jojo-Schmitz** [comment]
Reg `possibile`: see https://github.com/w3c/smufl/issues/74#issuecomment-320513315

**Comment by mirabilos** [comment]
OK, thanks @ possibile, I’ll override that in lintian then.

**Comment by lasconic** [comment]
I merge it manually, cherry picking  9e275eb from 2.2

**Pull request closed without merging**
