### PR TITLE
Fix #21593: Enable IME only when in text input

### LINKED ISSUE #21593: IME is always active, even when not in text input
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

The IME (Input Method Editor) is enabled even when not in text input.
When using shortcuts, the IME must be manually switched to alphabetical input mode, which is extremely inconvenient when using text and non-text input in succession.

### Steps to reproduce

0. Install an IME of any kind to your computer
1. Just open any score
2. See that the IME is active

### Screenshots/Screen recordings

_No response_

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11 23H2

### Additional context

I use [Google Japanese Input IME](https://www.google.co.jp/ime/).

In MuseScore 3, though the IME was enabled at first, it switched to disabled when some text input was completed.

### PR DESCRIPTION
**Pull request by bakajikara**
Resolves: #21593

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by bakajikara** [comment]
Yes, rebased!

**Comment by DmitryArefiev** [comment]
Tested #21593 on Win10, Mac13.6, LinuxUbuntu22.04. 
**FIXED** on **Win** and **Linux**
On **Mac** it's fine in master as well (it seems there is no bug because IME works in another way, as I can see)

@bakajikara Thanks for fixing!

**Comment by bakajikara** [comment]
@DmitryArefiev It should be OK now. Could you please check again?

**Comment by DmitryArefiev** [comment]
@bakajikara Yes, all good now. Thanks!

Tested #21593 on Win10, Mac13.6, LinuxUbuntu22.04. **FIXED**

**Pull request merged**
