### PR TITLE
allow using the system Poppler library to build with OMR

### PR DESCRIPTION
**Pull request by mirabilos**
This is necessary for distributions that forbid embedded convenience copies of libraries, such as Debian, usually for security reasons.

Because the system library is called `libpoppler-qt5`, rename the non-system statically built one to the same name, to reduce the amount of `if`s in the cmake rules.

### CODE REVIEW

**Comment by dmitrio95** [comment]
Would it perhaps be better to use something like `find_package(Poppler)` instead of just hardcoding include paths? I see Debian has the proper `FindPoppler.cmake` (in `extra-cmake-modules` package), using something like this might be better also for some other distributions. Or are these paths unlikely to vary?

**Comment by mirabilos** [comment]
They are **very** unlikely to vary, and developing against Poppler is tricky due to its weird library structure anyway (the Poppler maintainer had to help me out figuring this out). I had a look at the pkg-config `.pc` files and ran away.

**Comment by mirabilos** [comment]
Rebased on git master as of today (3.0.1 release equivalent), please apply now.

**Comment by mirabilos** [comment]
@anatoly-os ping?

**Pull request merged**
