### PR TITLE
#105436 #105471 save svg cleanup

### PR DESCRIPTION
**Pull request by sidewayss**
This is a replacement PR for 2542.  It is current with MuseScore/master as of today.

### CODE REVIEW

**Comment by lasconic** [comment]
Ok looks good.
Can you squash the commits?  http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html and make sure the commit message is "Fix #105436 Fix #105471: svg regressions"

**Comment by sidewayss** [comment]
I'll give it a try.  This warning gives me pause, as I have already pushed this to github as well as created this PR.
"A word of caution: Only do this on commits that haven’t been pushed an external repository. If others have based work off of the commits that you’re going to delete, plenty of conflicts can occur. Just don’t rewrite your history if it’s been shared with others."

I'll assume that "external repository" means external to my fork here on github and that I can do this, then push it, and everything will be OK in this PR.  You'll see the results if I succeed.

**Comment by lasconic** [comment]
yes, you can run `git push -f origin #105436-#105471-saveSVG-cleanup`

**Comment by sidewayss** [comment]
In case you are not notified of the change to the branch, I have completed the rebase and push as of about an hour ago.

**Comment by lasconic** [comment]
Thank you! Looks good.

**Comment by lasconic** [comment]
Well except the commit message... It really needs to read "Fix #XXXXX" for each issue but I will take care of it manually.

**Comment by sidewayss** [comment]
I copied and pasted the commit message you posted here, so it should have been correct.  There was a third issue, but it was flagged as the same as one of these in the MuseScore forums.  Anyway, it seems to have worked out OK.

**Comment by sidewayss** [comment]
Crap, I was confused by the fact that two of the issue numbers are almost identical, 105436 and 105336.  105336 is also fixed by the PR/merge!  I'll note in the musescore issue itself, and hopefully we can sort this out.

**Pull request merged**
