### PR TITLE
[engraving] replaced QList to std. Part 11

### PR DESCRIPTION
**Pull request by igorkorsukov**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
There's some overlap/potential collision with #11263, guess better get this one here in first

**Comment by igorkorsukov** [comment]
> There's some overlap/potential collision with #11263, guess better get this one here in first

I plan to finish my task to the end. 
I will merge your PR, and I ask you not to do anything in this context yet so that there are no conflicts

**Comment by Jojo-Schmitz** [comment]
OK, I'll hold my peace ;-)

**Comment by Jojo-Schmitz** [comment]
Huh?

**Comment by Jojo-Schmitz** [comment]
Ah, replaced by #11281

**Pull request closed without merging**
