### PR TITLE
[MU4] Added unit tests example

### PR DESCRIPTION
**Pull request by igorkorsukov**
At moment used 2 tests systems: 
* mtests - integration tests
* vtest - visual tests

`mtests` shows in the QtCreator, but unfortunately not running from QtCreator.
And they are not like unit tests, due to the current implementation, they are designed to test the entire loaded score from a file.

MuseScore 4 plans to use interfaces in many places, so it’s possible to create unit tests that test a single class or subsystem (a small set of classes).

For unit tests, we plan to use[ `gtest` with `gmock`](https://github.com/google/googletest).
Why not QTest?
Several reasons: 
* We try to get away from Qt wherever possible (something that is not a graphical interface).
* There is a very powerful framework for working with mocks - `gmock`. (it can be used separately, but better together with `gtest`)
* Most C ++ developers work with `gtest` (those that write use unit tests)
* In QtCreator, it’s convenient to turn off `mtests` or `unit tests` by just turning off `QTest` or `GTest`.

We do not plan to delete or do something with `mtests`, they will remain for testing Score (libmscore).

We plan to place unit tests in the folder with the module it is testing, and not create a common place for all tests.

Later I plan to write documentation on how to create unit tests.

### CODE REVIEW

**Comment by AntonioBL** [comment]
Speaking about tests, why was it necessary to change some of the references during the inspector redesign PR?
I mean this commit:
https://github.com/musescore/MuseScore/commit/8723178782
The changes involved guitarpro and MuseScore 1.x (compat114) file import, two voice exchange tests and one test script (renamed to "scriipt").

**Comment by RobFog** [comment]
> Speaking about tests, why was it necessary to change some of the references during the inspector redesign PR?
> I mean this commit:
> [8723178](https://github.com/musescore/MuseScore/commit/8723178782)
> The changes involved guitarpro and MuseScore 1.x (compat114) file import, two voice exchange tests and one test script (renamed to "scriipt").

Will there be an answer to this question?

**Comment by igorkorsukov** [comment]
> > Speaking about tests, why was it necessary to change some of the references during the inspector redesign PR?
> > I mean this commit:
> > [8723178](https://github.com/musescore/MuseScore/commit/8723178782)
> > The changes involved guitarpro and MuseScore 1.x (compat114) file import, two voice exchange tests and one test script (renamed to "scriipt").
> 
> Will there be an answer to this question?

I don’t know the answer.
And @vpereverzev  is now on vacation for 2 weeks, I turned his attention to this question.

**Comment by AntonioBL** [comment]
@vpereverzev :
Ciao, I hope your vacation went ok.
Can you please have a look at this comment https://github.com/musescore/MuseScore/pull/6226#issuecomment-645540752 ?

Thank you for your help.
Ciao,
ABL

**Comment by vpereverzev** [comment]
@AntonioBL
TY very much! :)

Yes, the fact is that the new inspector is entering a big redesign of the application as part of MU4 Craft. Many changes affected not only the visual part, but also the domain model, which of course affected the tests.

I am sure that we will return to these tests later, for example, when we'll work on a new format that should work with both the note editor mode and the sequencer mode.

And regarding the renaming the "script" to "scriipt"... this is just my annoying typo, which was noticed and fixed later)

**Comment by AntonioBL** [comment]
Ok. Thank you for the explanation.
So maybe instead of blindly pushing to Github a new ref file with probable errors, it is much better to temporarily disable those tests by commenting out their folder in the list of mtest subdirs:
https://github.com/musescore/MuseScore/blob/2869ca0e0698d20944d220de56fa59f00662d13b/mtest/CMakeLists.txt#L180
with a comment explaining that they will be revised later on, when the dust has settled on the inspector and UI revamping.
So that when they are reactivated the ref file were not tampered with the results of a partial implementation, as most probably will be the case with those currently changed ref files.

**Pull request merged**
