### PR TITLE
debug info for #281847 to see portmedia raw string

### PR DESCRIPTION
**Pull request by ericfont**
I'm only making a PR here to help debug a user's problem.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
So this can get closed again?

**Comment by ericfont** [comment]
I still think these debug info is useful.  I can imagine someone else running into a similar problem and needing to refer to the output...  This is the only way can help users far away debug a problem with would only happen on their machine.  Obviously they will need to download a nightly with debugging enabled and would have to set the relevant Q_DECLARE_LOGGING_CATEGORY environment variable for the portMidi category I made to see the debug statements, as they wouldn't appear by default.  So I would like this PR to get merged...would save time in the future if someone runs into a problem with portMidi.

**Comment by Jojo-Schmitz** [comment]
Fair enough, but different from the initial comments, that's why I asked

**Comment by dmitrio95** [comment]
There are conflicts here now so it is probably better now to close this.

**Pull request closed without merging**
