### PR TITLE
[MU4] fix #10103: Chord symbols are recognized (parsed) properly only in a just created scores

### LINKED ISSUE #10103: [MU4 Issue] Chord symbols are recognized (parsed) properly only in a just created scores
**To Reproduce**
1. Create a score
2. Add some notes
3. Save and close
4. Reopen
5. Select note and enter chord input mode
6. Type **am7** and hit Space - you see **m7** instead of Am7 

https://user-images.githubusercontent.com/90187801/146188507-31649f9d-ee89-439c-a47f-7f195b636184.mp4

**Expected behavior**

**Screenshots**

**Desktop:**
 - OS: all

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/10103

### CODE REVIEW

**Review by igorkorsukov — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
The vtest fails might not be intedned, before
image
and
image
after:
image
and
image

**Comment by DmitryArefiev** [comment]
@Jojo-Schmitz I don't see a difference between master build and PR's build..  Chord numbers are not superscripted in master build as well. Or do you mean another style of chords view?

**Comment by Jojo-Schmitz** [comment]
Well, we can see them in the vtests.

**Comment by njvdberg** [comment]
@DmitryArefiev I noticed I had a PR for which no vtests where executed and I guess there where more of them.
Is it possible one of these PR's caused this issue?

**Comment by Jojo-Schmitz** [comment]
If so that must have been quite a while ago. Your #9944 stems from 15 days ago and had vtests failing, That was before the vtests got fixed in #10057, #10009, #9992 and #9991

**Comment by njvdberg** [comment]
I'm afraid it can be quite a while ago. I noticed the issue with #9944 indeed but have no idea what PR caused vtest's to fail. I twas just the first time I noticed.
In other words, there might be a lot of PR's causing vtest violations without being noticed.

**Comment by Jojo-Schmitz** [comment]
Should not happen with any after those mentioned above

**Comment by njvdberg** [comment]
But what if the reference already??

**Comment by Jojo-Schmitz** [comment]
vtests are fine now.

**Comment by DmitryArefiev** [comment]
Tested #10103 on Win10, Mac12, LinuxMint 20.2 - FIXED      

Please merge into master

**Pull request merged**
