### PR TITLE
Build x86 AppImages on Ubuntu 12.04

### PR DESCRIPTION
**Pull request by shoogle**
This moves the AppImage builds from CentOS 6.7 to Ubuntu 12.04, and fixes a number of bugs in the AppImage and Docker builds. For example, the Travis AppImage build jobs will now be properly marked as "failed" if there are fatal errors.

The Ubuntu AppImages work on all of the same distros as the CentOS AppImages did, except they only work on CentOS 7 and not CentOS 6. They have been tested working on:
- Ubuntu 12.04, 16.04 and 16.10
- Debian 8
- Fedora 22
- OpenSuse 13.1

### CODE REVIEW

**Comment by shoogle** [comment]
@lasconic, the AppImage build tests failed because the Docker images are still CentOS rather than Ubuntu. This will be rectified automatically when the PR is merged. The first build will fail, but will trigger the Docker images to be rebuilt, so subsequent builds will pass.

You can see the build passes on my Travis [here](https://travis-ci.org/shoogle/MuseScore/builds/183179333).

**Comment by lasconic** [comment]
This PR is for the 2.1 branch right? What's your plan for the master branch?

**Comment by shoogle** [comment]
My plan is to make a plan ;)

The problem with master is that it uses Qt 5.6 and Qt don't provide a 32-bit version of anything beyond Qt 5.5. The choices are:
- Abandon 32-bit for MuseScore 3
- Use a distribution Qt (but even the distributions are starting to phase out 32-bit)
- Compile Qt myself

**Comment by shoogle** [comment]
Another thing to consider is that Qt don't release ARM builds either, so we face the same choice there too. I believe @ericfont uses the Debian Qt for the ARM AppImage builds.

**Pull request merged**
