### PR TITLE
Fix entering system lines with control modifier

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #18048

I had introduced that check in 6d933ae as part of a number of fixes related to system lines, but I think it turns out to be unnecessary now, given all the rest of the work that's been done to correct the behaviour of system lines in general.

### CODE REVIEW

**Comment by DmitryArefiev** [comment]
Tested on Win10. Found some things. All of them happen after parts are generated.

1. **Crash** when adding multiple tempo change lines and moving one of them in part 

https://github.com/musescore/MuseScore/assets/90187801/c5c0bc79-832a-4e62-81c6-a78d93556326

2. When adding multiple volta lines to score, that lines are duplicated in parts (the same duplicate issue in parts in **master**)

https://github.com/musescore/MuseScore/assets/90187801/20869fda-7775-4fed-82c8-65b5f5221acb

3. When adding single volta line on one instrument in score, it's duplicated to all parts. Not sure how it should work since in MS3 it won't copy to any part. 

https://github.com/musescore/MuseScore/assets/90187801/ed6a2a50-314d-4c5d-ae57-4847f3a00da0

**Comment by mike-spa** [comment]
@DmitryArefiev I think it works now. Let me know!

**Review by oktophonie — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
@mike-spa Yeah, all good now!

Tested #18048 on Win10, Mac13 - **FIXED**

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
(@mike-spa Assigning #18925 since you're already know that area)

**Pull request merged**
