### PR TITLE
fix #268122: Missing naturals when switching key

### PR DESCRIPTION
**Pull request by mattmcclinch**
See https://musescore.org/en/node/268122.

### CODE REVIEW

**Comment by mattmcclinch** [comment]
This fix is no longer included in #3608. I separated the pull requests when I realized I had to modify this one a bit.

**Comment by lasconic** [comment]
I probably miss something but loading the accidental-10.mscx file with this fix doesn't display the natural. Is the fix supposed to solve this problem?

**Comment by mattmcclinch** [comment]
I can't seem to find the accidental-10.mscx file, so I can't check for myself. Should the natural be displayed?

**Comment by mattmcclinch** [comment]
The score may not be updating because of the bug I addressed in #3608. Perhaps I shouldn't have split the PRs after all.

**Comment by lasconic** [comment]
You can find visual tests in the vtest directory.
https://github.com/musescore/MuseScore/raw/master/vtest/accidental-10.mscx
And how it should look
https://github.com/musescore/MuseScore/raw/master/vtest/accidental-10.png

**Comment by mattmcclinch** [comment]
It is indeed because of the other bug. Adding a note in the third measure will cause the accidentals to be displayed.

**Comment by mattmcclinch** [comment]
I see the bug still occurs when loading the score from a file. Recreate the score from scratch, and it should display correctly. And, as I was trying to say earlier, if you make a change that causes a layout of the third measure, the accidentals will suddenly appear.

**Comment by mattmcclinch** [comment]
Try it now. This was my original solution. I can't remember now why I thought I had to change it. Let me know if it fails any visual tests.

**Comment by mattmcclinch** [comment]
This has the opposite problem. When loading a score, naturals may be displayed when they should be hidden, until a change forces a layout of the measure.

**Comment by mattmcclinch** [comment]
I added a keysig layout where one was needed, and I rewrote the condition for hiding naturals. I believe it really fixes the issue this time.

**Comment by mattmcclinch** [comment]
I realized I was missing an important check and had to edit this on the fly. I will squash the commits when I get home.

**Pull request merged**
