### PR TITLE
Update Bravura and BravuraText to latest Steinberg version 1.32

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Plus the newly added LICENSE.txt and README.md.
As taken from https://github.com/steinbergmedia/bravura/

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
There are some more changes meanwhile, https://github.com/steinbergmedia/bravura/commits/master, but only an added (and subsequently chnaged) LICENSE.txt and possibly a changed README.md might be relevant for us

**Comment by anatoly-os** [comment]
@Jojo-Schmitz what is the reason to update the font?

**Comment by Jojo-Schmitz** [comment]
Just to stay up-todate and on par with Steinberg/Dorico. Also (as of 2 days) a user request: https://musescore.org/en/node/293790

**Comment by Marr11317** [comment]
There's been a new commit to Bravura a few days ago...

**Comment by Jojo-Schmitz** [comment]
Thanks, will integrate those

**Comment by Jojo-Schmitz** [comment]
Integrated/updated. Travis CI is acting up though, not the fault of this PR.

**Comment by dmitrio95** [comment]
@Jojo-Schmitz could you please force-push the changes again to trigger the new vtest jobs (#5748)? I don't seem to be able to restart the job which has never been triggered here.

**Comment by Jojo-Schmitz** [comment]
done

**Comment by AntonioBL** [comment]
Once again, the bot failed to comment.
There are very small and basically unnoticeable differences, see https://github.com/musescore/MuseScore/suites/516148100/artifacts/2824689

**Comment by Jojo-Schmitz** [comment]
The strange think is that it changes some Emmetaler, Gonville and MuseJazz vtests too?!? None of these have changed.

**Comment by AntonioBL** [comment]
Maybe because of fallback font?

**Comment by Jojo-Schmitz** [comment]
Possible. If so unavoidable and the vtests just need to get adjusted

**Comment by AntonioBL** [comment]
No need to update the vtests: the Github action automatically compares the PR and its parent base commit. I will expect only an automated message will be posted in the merge commit underlining the fact that vtests have changed.
(At least, I hope the message will be triggered, so that we have a confirmation that, at least for push commit, the bot is doing its work)

**Comment by Jojo-Schmitz** [comment]
Ah, OK, thanks.

**Pull request merged**
