### PR TITLE
Fix #35076: Automatic generation of repeat key and time signatures.

### PR DESCRIPTION
**Pull request by CombatCube**
Automatic generation of courtesy key signature before repeat barlines. Courtesy time signatures and clefs are not yet covered.

### CODE REVIEW

**Comment by lasconic** [comment]
Didn't look at the code yet but the history of your branch is messed up. Can you take look?

**Comment by CombatCube** [comment]
Fixed the history. I also added some code to do time signatures, too, but end-of-system courtesy signatures bug out when adding/removing measures (can be fixed by resetting the system break).

**Comment by mgavioli** [comment]
Courtesy signatures are already dealt with at https://github.com/musescore/MuseScore/blob/master/libmscore/layout.cpp#L2120 (and following) and at https://github.com/musescore/MuseScore/blob/master/libmscore/layout.cpp#L2864 (and following).

Is it absolutely necessary to add another place dealing with them?

**Comment by Jojo-Schmitz** [comment]
PR no longer needed, issue got fixed recenmtly (and probably different)

**Pull request closed without merging**
