### PR TITLE
[MU4] Fix #11151: Playback. Mapping issues in Percussion instruments

### LINKED ISSUE #11151: [MU4 Issue] Playback. Mapping issues in Percussions (Pitched) instruments
**Expected behavior**
All instruments have corresponding midi and sound mapping

**Screenshots**
See [Spreadsheed](https://docs.google.com/spreadsheets/d/1p544iRhT_kGtkQd0u2qdgEoKb0ZHggvUg8FARhhZNMY/edit?pli=1#gid=583645955) with the issues described 

**Platform information**
 - OS: [macOS, Windows]

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/10999
Resolves: https://github.com/musescore/MuseScore/issues/10948

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
A rebase should fix it

**Comment by cbjeukendrup** [comment]
@RomanPudashkin was the spreadsheet at https://docs.google.com/spreadsheets/d/1SwqZb8lq5rfv5regPSA10drWjUAoi65EuMoYtG-4k5s/edit#gid=516529997 (from which `instruments.xml` is generated using `update_instruments_xml.py`) updated accordingly?

**Review by vpereverzev — APPROVED** [review]

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

Please, merge to master

**Comment by Jojo-Schmitz** [comment]
I guess you should discuss this with @shoogle

**Comment by shoogle** [comment]
> most of us had no clue about it existence

We discussed the spreadsheet on multiple occasions and you even used it to create the instrument categories for MPE.

I guess there was a misunderstanding about the direction of the spreadsheet. I said I was creating one that would obey the existing instruments API as much as possible. Perhaps you thought that meant the spreadsheet was generated from instruments.xml, but it is actually the other way around. There are many advantages to doing it this way, though it's true that there are also disadvantages.

**Comment by Jojo-Schmitz** [comment]
Major disadvantage to me is that this spreadsheat is not in the repository

**Comment by Jojo-Schmitz** [comment]
The other disadvantage is that now the changes from ths PR need to get retrofitted into the spreadsheet.

**Comment by shoogle** [comment]
Leland and Edwin are also not edited in this repository. They are edited elsewhere and then the slot into an API within this repository.

I'm aware of the advantages and disadvantages of doing things this way and I'm happy to discuss them on a call.

**Comment by Jojo-Schmitz** [comment]
Leland and Edwin however are in **a** repository, a public one that accepts/enables PRs for example, unlike the spreadsheet.

**Comment by shoogle** [comment]
The spreadsheet has a permissions system that allows editing by other team members, just like a repository. Other people can leave comments with suggested changes, request edit access, or create a "fork" of the spreadsheet by making a copy in their own Google Drive and then updating the link in the Python script to point to their spreadsheet instead of the official one.

Please don't argue this here Jojo. Like I said, I already know the advantages and disadvantages. If you want to discuss them in more detail we can do so on a call.

**Pull request merged**
