### PR TITLE
[MU4] "Copy lyrics to clipboard" should extract lyrics above staff too

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Came up as a side track of https://musescore.org/en/node/330017, same issue in MuseScore 3 too.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
This one is more than a year old by now...

**Review by cbjeukendrup — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
@RomanPudashkin mind to review and merge?

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12 - now "Copy lyrics to clipboard"catches lyrics above staff too

**Comment by Jojo-Schmitz** [comment]
Thanks!

**Pull request merged**
