### PR TITLE
Adjust palette element size

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #20333

### CODE REVIEW

**Review by bkunda — CHANGES_REQUESTED** [review]
Looking fab.
Sorry to nitpick – can we pls set the alternate tuning element at 0.9 instead of 0.8? 
Then it'll be perfect 👍🏻

**Comment by bkunda** [comment]
@avvvvve @jessjwilliamson would be good for you to check this one out quickly too pls (on both Win and Mac if you have access). Michele and I have noticed some slight differences between different machines. Basically the palette should look like this: 

Screenshot 2023-12-07 at 9 55 50 am

**Comment by avvvvve** [comment]
@bkunda @mike-spa The four bend icons do indeed look larger on Windows than on Mac (see screenshot; Mac is overlayed on Windows).

It's strange—the scaling factor in the cell properties is the same on both OSs.

Not sure if we ever set different defaults for Mac/Windows, but I got the sizes to match by manually setting the scaling of the Windows Grace note bend to 0.9 and the other three to 1.1.

image

**Comment by mike-spa** [comment]
@cbjeukendrup do you have any idea why this scaling difference may be happening? Is there any different code that we run on each platform? Otherwise it sounds like a Qt bug

**Comment by mike-spa** [comment]
@bkunda @cbjeukendrup @avvvvve I've pushed some new code which _should_ guarantee that the palette icons are rendered at the same size everywhere. Please do try it out on the machines you have (great if you have both Mac and Windows, and @oktophonie perhaps you could try on Linux too). If this works, and if we're still in time, I think it would be great to put this in 4.2

**Review by oktophonie — APPROVED** [review]

**Review by bkunda — APPROVED** [review]
Looks good to me. Thanks @mike-spa!

**Pull request merged**
