### PR TITLE
Fix #272241: allow tab to go beyond 24 frets

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by mgavioli** [comment]
While I cannot think of any harm done, 100 frets correspond to about 8 octaves and I doubt any stringed instrument can be fingered at so a high position with any audible result (the finger would be placed at 1/256th of the string length, i.e. less than 1 cm from the bridge in the case of the guitar!). Is there a rationale for this change?

**Comment by Jojo-Schmitz** [comment]
@mgavioli : please see the lengthy discussion in the issue itself, here in a nutshell: 36 would be the minimum required, as there does exist such an instrument in the real world, now for quartertone fretting this might make up for 72 frets, which is also the max. other vendors allow for (Sibelius 59, Finale 68, Guitar Pro 72), 99 would be some more, without having effect on layout (i.e. staying double digit) and also is the max. the the edit string data dialog allows for.

**Comment by Jojo-Schmitz** [comment]
I can't imagine why there might be a performance impact

**Comment by RobFog** [comment]
The "review" lable should probably go now that the PR has been merged?

**Pull request merged**
