### PR TITLE
Move "Odd Page Margins" back before "Even Page Margins"

### PR DESCRIPTION
**Pull request by ZackTheCardshark**
Odd pages are encountered first. Think of page 1.

### CODE REVIEW

**Comment by ericfont** [comment]
Umm...I've tried out your PR, but I still see "Even Page Margins" on top of "Odd Page Margins".  I'm pretty sure I compiled correctly, since I see your commit # in About->revision.

**Comment by ericfont** [comment]
I know whats going on.  You change the *name* of the UI eleements, but you forgot to change the *text* of the UI elements!!!

**Comment by ZackTheCardshark** [comment]
Thank you!

**Comment by ZackTheCardshark** [comment]
Commits squashed, FWIW.

**Pull request merged**
