### PR TITLE
[MU4] New score wizard, key signature selector improvements and fixes

### PR DESCRIPTION
**Pull request by aaaeka**
Resolves: #7638 

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by RobFog** [comment]
Typo in the commit message: "overlaping" should be "overlapping".

**Comment by Eism** [comment]
You should have a warning because the column should not have top and bottom bindings for elements. They follow each other by default. 
I will assume that the problem is in the height of the TabBar. Perhaps the TabBar's height is always zero and the next item in the column(pagesStack) overlaps the TabBar.
Please test changing the height of the TabBar

**Comment by aaaeka** [comment]
Yes, my previous fix throws a warning. I tried changing the height and it seems to make no difference. Perhaps a way to fix this issue is to change ```column``` to ```item```, similar to how it's done in ```ChooseInstrumentsAndTemplatesPage.qml```?

**Comment by Mystic-Slice** [comment]
Do the grid view items disappear for you when you change tabs from Major to Minor and back again to major?

**Comment by Mystic-Slice** [comment]
> Do the grid view items disappear for you when you change tabs from Major to Minor and back again to major?

This is not related to the issue this PR is fixing btw.

**Comment by aaaeka** [comment]
Implemented saving key when changing modes. 

https://user-images.githubusercontent.com/36422478/114280448-ed511d80-9a41-11eb-9dd5-a25366b78cdb.mp4

**Review by RomanPudashkin — APPROVED** [review]

**Comment by vshalkevich** [comment]
This PR includes bug which doesn`t allow user to launch Windows and Linux versions of MU4
Need to rebuild it from the latest Master branch MU4 version

**Comment by aaaeka** [comment]
Rebased with latest master

**Comment by vshalkevich** [comment]
Seems fine

**Pull request merged**
