### PR TITLE
Removed white space from various files.

### PR DESCRIPTION
**Pull request by awelch83**
This is my first contribution to the project. I've been using musescore for a few years now. I hope to make more substantial contributions in the future.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Have you sighed the [CLA](http://museScore.org/cla)?

**Comment by Jojo-Schmitz** [comment]
And this kind of Travis error you could try to fix by "git commit --amend", close the editor that this brings up, with or without changing the commit message and then a "git push -f"

**Comment by awelch83** [comment]
@Jojo-Schmitz I'll get this things done later, when I get home from work. I looked for a contribute.md file, but must have looked right past it..

**Comment by awelch83** [comment]
@Jojo-Schmitz The site cannot be found. (https://musescore.com/cla)

**Comment by Jojo-Schmitz** [comment]
http://MuseScore.org/cla

**Comment by awelch83** [comment]
@Jojo-Schmitz This is what's happening every time I try:

1.) I go to musescore.org/cla
2.) I click the link at the bottom of the page, where it says "To sign this agreement, [register or login](http://musescore.org/user?destination=cla) first."
3.) I land on a page that states "Login You are redirected to musescore.com"
4.) Not seeing the space for username/password that I expected, I go to the upper-right corner of the page and click [Log In](https://musescore.com/user/login?destination=cla).
5.) I land on the "Page Not Found", and the address shown in my address bar is https://musescore.**com**/cla. There is a yellow banner here alerting me to the fact that I'm already logged in.
6.) Again, I manually try to go to [http://musescore.org/cla](http://musescore.org/cla), and again I'm prompted to log in.

How can I actually sign the agreement..?

**Comment by Jojo-Schmitz** [comment]
Do you have an account in musescore.{com,org}? It not you'd need one first. It you do and can't log in using it, we may need help from @thomasbonte

**Comment by awelch83** [comment]
Yeah, I do. I don't have github open in front if me right now, but in one of those steps I'd mentioned that I logged in an still couldn't sign the cla.

The page is simply invalid... Like I said

Sent from my iPhone

On Jan 27, 2015, at 23:32, Joachim Schmitz <notifications@github.com> wrote:

Do you have an account in musescore.{com,org}? It not you'd need one first. It you do and can't log in using it, we may need help from @thomasbonte

**Comment by thomasbonte** [comment]
@awelch83 I'm on it. Will let you know when it's fixed. However there is a workaround.

1. Go to http://musescore.org/cla
2. At the top of the page, click on Login

Just login from here and you will get back to the CLA page.

**Comment by thomasbonte** [comment]
@awelch83 Issue is fixed now. You may need to refresh your browser cache. Thanks again for reporting.

**Comment by awelch83** [comment]
Thanks, @thomasbonte. I'm going to go and sign that form now.

**Comment by awelch83** [comment]
@thomasbonte CLA form has been signed. Thanks again for your help

@Jojo-Schmitz I've done "git commit --amend", and "git push -f". Does everything look good now?

**Comment by Jojo-Schmitz** [comment]
oops, you did a merge, bad. Never do a merge, but a rebase instead

**Comment by Jojo-Schmitz** [comment]
oops, you also did a merge, bad. Never do a merge, but a rebase instead

First to a 
first to a git reset --hard 9f8763e 

then (and in general)
git fetch upstream; git rebase upstream/master

then
git push -f

**Comment by awelch83** [comment]
@Jojo-Schmitz Done. Thanks for taking the time to teach me a couple of things. I'm making notes as I go along so that I, hopefully, won't make the same mistake twice. Just to make sure I understand correctly, when I'm bringing my master branch up to date with the latest changes in upstream/master, I always want to rebase as opposed to merge?

**Comment by Jojo-Schmitz** [comment]
yes, never merge, always just rebase. Otherwise you screw up the commit history. I'm pretty sure this is mentioned in the developers' handbook, probably on the git workflow page

**Comment by Jojo-Schmitz** [comment]
And not just your master branch, this topic branch too. So far I don't see it being fixed.

**Comment by awelch83** [comment]
@Jojo-Schmitz I'm not sure what that means, and google isn't helping. I've followed the steps you outlined in your earlier message. Maybe I just need to close this pull request and resubmit...?

**Comment by Jojo-Schmitz** [comment]
Might be one way out, yes

**Pull request closed without merging**
