### PR TITLE
Fix #302849: hide chord symbol playback options in Inspector if Play is unchecked

### PR DESCRIPTION
**Pull request by IsaacWeiss**
<s>Also make grid layout and add colons to labels</s>

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Your changes to voicing_select.ui will collide with mine in #5852

**Comment by IsaacWeiss** [comment]
@Jojo-Schmitz thanks, I'll back those changes out.

**Comment by Jojo-Schmitz** [comment]
Or integrate mine

**Comment by IsaacWeiss** [comment]
> Or integrate mine

How can I do that?

**Comment by Howard-C** [comment]
Well, normally the connections for inspector widgets are done in C++, probably because they're better exposed this way (rather than hidden in a connection box at the corner of QtCreator/Designer.

**Comment by Jojo-Schmitz** [comment]
> Or integrate mine

Pull that file from my PR and add it to your's I think. Or manually apply the very same changes.

**Comment by IsaacWeiss** [comment]
> Well, normally the connections for inspector widgets are done in C++, probably because they're better exposed this way (rather than hidden in a connection box at the corner of QtCreator/Designer.

@Howard-C do you think this is necessary? I'll have time in the next day or two to polish up my current pull requests. I think this is ready, but I can change the location to "expose" these connections in the CPP if it's important to do so.

**Comment by IsaacWeiss** [comment]
Removed connections in the UI file, added CPP code instead.

**Pull request merged**
