### PR TITLE
Tag Pid::VOICE as always-sync property

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #23751

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Perhaps when testing it would be good to check that this doesn't have negative effects on parts with staves that don't show all voices (because in that situation, an item may for instance be in voice 2 in the full score, but mapped to voice 1 in the part score).

**Comment by oktophonie** [comment]
@cbjeukendrup @mike-spa It seems to work as expected, e.g. if you have a voice 2 dynamic, and you show only voice 2 in the part, it will be 'promoted' to voice 1 - and, dynamics belonging to other voices are not shown.

However, it is still possible to change the voice assignment of the dynamic in the part in such a situation. If you change the dynamic to apply to voice 2, it will go green; it would perhaps be better if nothing happened in this situation (if you change the _note_ to voice 2, nothing happens). Similarly, you can change the dynamic to voice 3, and its colour and placement will update; but it would perhaps be better if the dynamic wereto then disappear (if you change the note to voice 3, it will disappear). But this could be considered a separate issue.

(Testing this makes me realise how good it would be to have https://github.com/musescore/MuseScore/pull/23555 finished and merged)

**Review by miiizen — APPROVED** [review]
To fix the issue with voices hidden on staves, we'll need a method similar to but simpler than `Score::changeSelectedNotesVoice`.  This will clone the dynamic, change the voice, delete the old dynamic and add the clone again. This will make sure it is added to the staves with that voice visible and removed from ones it isn't needed in any more.

I really think the voices visible feature could do with a UX redesign _one day_.  The behaviour is pretty unclear and confusing right now.

**Review by avvvvve — APPROVED** [review]
@miiizen Agreed, I don't even know where to find the feature you're talking about!

Approved because the basic behavior is fixed.

**Comment by avvvvve** [comment]
_(Figured it out with @oktophonie's help)_

One relevant issue is that if I hide voice 1 in a part, all the "All" voice dynamics are hidden as well, but they should remain across all parts (that is, unless there's a single-voice dynamic at the same moment in time, in which case only the single-voice dynamic should remain). @mike-spa you merged as I was typing this so I can log separately :)

It strikes me as strange that, if I hide voice 1 in a part, voice 2 now appears in the voice 1 color. I get that it's so the notes can abide by voice 1 stem direction rules, but like James is getting at, it's confusing that the voice numbers are all off by one. Like, if I then add a note in voice 2, and then make voice 1 visible again, that note I just added is actually in voice 3 now.

**Pull request merged**
