### PR TITLE
fix #23187: Change UI in preferences for exporting musicxml

### PR DESCRIPTION
**Pull request by KuribohG**

### CODE REVIEW

**Comment by RobFog** [comment]
Typo: "prefrences" should read "preferences".

**Comment by anatoly-os** [comment]
@KuribohG could you please rebase the PR?

**Comment by Jojo-Schmitz** [comment]
oops, that merg commit shouldn't be there

**Comment by KuribohG** [comment]
Sorry for my wrong operation. Should I resolve the commit to pass the test, then rebase these commits?

**Comment by Jojo-Schmitz** [comment]
probably better to do a `git reset --hard 7ff0ae4` and do the rebase again.I use ` git pull --rebase musescore master` for that (you may need to use upstream rather than musescore)

**Comment by anatoly-os** [comment]
@KuribohG I'm preparing the 3.0.2 release and stopped the builds manually. I'll restart them again in a minute, sorry.

**Comment by anatoly-os** [comment]
@lvinken I would really appreciate your opinion about the changes made in this PR.

**Comment by lvinken** [comment]
This is a continuation of a PR I reviewed in the past (PR #4368). See my Dec 11 comment on that PR. I do agree with and appreciate the functional change, but I still have to verify the rework and make sure everything works as expected. Due to business and personal matters my time this week is limited. Will try to review again a.s.a.s.p., but that may take a few days.

**Comment by lvinken** [comment]
Wrt to MusicXML export this PR works exactly as it should. I have no comment on the coding of that part. Works like a charm, would like to see it merged.

I do have some comment on changes to mscore/prefsdialog.cpp:
- lines 337-343 have been removed (looks like a macOS specific fix)
- lines 1112-1116 have been removed (workspace related)
These removals seem unrelated to MusicXML export me, thus I do not expect them in this PR. Note that I am not familiar with that part of MuseScore, so I may be wrong here. It seems to me, though, that these removals should be reverted before merging the PR.

**Comment by anatoly-os** [comment]
@KuribohG should you are around, could you please rebase the PR and address the @lvinken's review?

**Comment by lvinken** [comment]
As it seems KuribohG has disappeared, the change is useful but the branch contains conflicts, I'll prepare a new PR with the equivalent changes.

**Comment by lvinken** [comment]
Once https://github.com/musescore/MuseScore/pull/5471 has been merged, this one can be closed.

**Comment by dmitrio95** [comment]
#5471 got merged so I close this PR.

**Pull request closed without merging**
