### PR TITLE
vst_pedal_fix_442

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/24273

### CODE REVIEW

**Comment by DmitryArefiev** [comment]
Tested #24273 on Win10, Mac13.6 - **FIXED**

**Comment by Ysabelle12** [comment]
> Tested #24273 on Win10, Mac13.6 - **FIXED**

Any build to test this out?

**Comment by cbjeukendrup** [comment]
See https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests for instructions how to download the test builds from this Pull Request. Alternatively, wait for the next Nightly Build, see https://musescore.org/en/nightly-builds.

**Comment by oktophonie** [comment]
@Ysabelle12 Yes, this one! Go to **Checks** at the top, choose **Build: Windows** or **MacOS** (as you need) and under **Artifacts** at the bottom there will be a link to download the build.

**Comment by Ysabelle12** [comment]
tested, works normally again.

**Review by mathesoncalum — APPROVED** [review]

**Pull request merged**
