### PR TITLE
fix #274204: Regression: Ambitus causes a crash just while clicking on it

### PR DESCRIPTION
**Pull request by mattmcclinch**
See https://musescore.org/en/node/274204.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Travis is not happy, but not due to the change in this PR, all meets passed

**Comment by mattmcclinch** [comment]
There is no corresponding option in the combo box for HEAD_CUSTOM, so it would have to be added to inspector_ambitus.ui as well. But do we even want to allow custom noteheads in Ambitus?

**Comment by Jojo-Schmitz** [comment]
I'm not sure why we allow different noteheads at all, after all this is for early music. But if we allow them, then I don't see why excluding some.
Then again that would add new strings to translate, so I don't think we want it for 2.3.2.

**Comment by mattmcclinch** [comment]
As I understand it, custom noteheads are only used for Drumset staves, and the ambitus is only meaningful for pitched instruments.

**Comment by Jojo-Schmitz** [comment]
We might want to discuss this for master, for 2.3.2 this PR is good as it is IMHO

**Pull request merged**
