### PR TITLE
fix #186706: export 7sus chord to MusicXML fails reimport

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
simpler alternative to #3123
Should go into 2.1 too

### CODE REVIEW

**Comment by MarcSabatella** [comment]
In principle I like this simpler version better.  But it will need testing to be sure there are no further regressions.

**Comment by Jojo-Schmitz** [comment]
It is adding that ` text=""` in exactly the same cases as before, just at 2 different (and as per Michael Good correct) places. The old place was wrong but apparently nobody stumbled accross it since it got added in 2.0.2, until 2.1-RC, so for 2 years.

**Comment by lasconic** [comment]
needs rebase.

**Comment by lasconic** [comment]
wait... I just saw the comment from the previous one... what a mess...

**Comment by Jojo-Schmitz** [comment]
Hmm, it was an alternative to #3123, that is Merger, so this here won't be needed anymore? It was prefered thoush by at least 3 reviewers.. I guess reverting #3123 and then morging this here should do?

**Comment by lasconic** [comment]
yes I saw that but too late.

**Comment by lasconic** [comment]
Done.

**Comment by Jojo-Schmitz** [comment]
Sorry, I though the comments to have been clear enough ;-)

**Pull request merged**
