### PR TITLE
fix #19528 wrong keysig on next system after undo

### LINKED ISSUE #19528: Adding Key signatures and Undo doesn't update key signatures change on the next system
### Issue type

Choose option...

### Bug description

_No response_

### Steps to reproduce

1. Open Classical Orchestra template
2. Select first measure
3. Add key signatures
4. Undo 

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/41dbbba7-2ea8-4ea7-a424-fe19ffb8144d

### MuseScore Version

4.2.0 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sammik**
Resolves: #19528 

add also Cmajor key sig to system header

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by cbjeukendrup — APPROVED** [review]
Looks fine to me!

**Comment by DmitryArefiev** [comment]
> Looks fine to me!

Thanks!

**Comment by DmitryArefiev** [comment]
Tested #19528 on Win10, Mac13, LinuxUbuntu 22.04 - **FIXED**

**Comment by DmitryArefiev** [comment]
@oktophonie Can you help with vtest please? Can we approve it?

**Comment by cbjeukendrup** [comment]
I think the vtest failures are because of rounding differences because now there are some (zero-width) C-major key signatures. Does that seem plausible?

**Comment by DmitryArefiev** [comment]
OK. I also don't see a difference in vtests on screen. Let's merge it then

**Pull request merged**
