### PR TITLE
make some html tags case insensitive

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
see https://musescore.org/en/node/61296#comment-281761 ff.

### CODE REVIEW

**Comment by lasconic** [comment]
For the record, these are NOT html

**Comment by Jojo-Schmitz** [comment]
Yeah, more XML. Or HTML inside XML. Which explains why there are case sensitive, still it won't harm here to treat them as case insensate, or would it?

**Comment by Jojo-Schmitz** [comment]
should I fix the commit message accordingly?

**Comment by lasconic** [comment]
That's fine. Just they are not html. <sym> is not HTML at all, nor <font>. And <font> even applies to all the text after it... and not the text in between...

**Comment by wschweer** [comment]
Please don't apply this PR. It's not html and supposed to be case sensitive.

**Comment by lasconic** [comment]
The problem is that more and more users are typing manually this non documented XML format in instrument names fields or in the footer/header fields to overcome the fact that there is no way to input rich text anymore in these fields as we can do for "in-score" texts... More often than not, this will result in corrupted files unfortunately.

**Comment by Jojo-Schmitz** [comment]
For Instrument names I don't see a real necessity at all, we do have several text styles to cover those (Instrumentname long, short, part), so there I'd simply disallow this (read: strip all html like stuff).
Header/Footer is different though.
We could split the footer/header text styles into even/odd, right/center/left, and then disallow html like stuff there too, but that'd be quite a lot additional text styles. And still no ability to change style inside one of those fields.
On top the issue with multiline copyright and the copyright symbol, where only copy/paste from some place else works...

**Comment by lasconic** [comment]
The copyright symbol is totally different thing and not linked with the XML we are talking about.. It's a system problem and/or user education problem. It works to type Alt +C on mac or Alt+0169 on Windows in any text field or text element in the score. It also works to get it from the Char Table on Windows.

It's basically the same for any other software out there. Does LibreOffice provide a special feature for entering the copyright symbol? Why would a score writer be different?

**Comment by Jojo-Schmitz** [comment]
I don't know LibreOffice, but Microsoft Office autocorrects (c) to &copy; and many other editor do too.
Yes, it is a different issue, but still related, after all header/footer is the place where a copy right messages is to appear and it is another usability issue that annoys users.

**Comment by MarcSabatella** [comment]
LibreOffice and most other programs provide a "special characters" dialog you can access to isnert the copyright symbol, or other symbols.  We provide such a dialog too, but it's not available in any of the places where you would actually want to enter the copyright symbol: the create new score wizard, the file / info dialog, or the header/footer dialog.  To me, simply adding a button to these three places to invoke the "special characters" dialog would be a possible way to go.  But so would making the header & footer be editable normally (double click, then edit as text, and then the "special charaters" dialog is available.  I understand the implementation is such that this might not be possible, or at least not straightforward.  But this would also address the mixed-formatting issue, and reduce the need for explicit markup.

**Comment by Jojo-Schmitz** [comment]
LibeOffice also does automagically convert (C) to &copy, see https://www.youtube.com/watch?v=l0dbO2lr088

**Pull request closed without merging**
