### PR TITLE
281592 musicxml trill export

### PR DESCRIPTION
**Pull request by lvinken**
Fixes #281592 - Trills not exported properly to musicxml

### CODE REVIEW

**Comment by RobFog** [comment]
Please change the pull request title and, more importantly, one of the commit messages to include "Fixes #281592" so that the issue gets automatically closed when the pull request is merged.

**Comment by Jojo-Schmitz** [comment]
Not "Fixes #281592", but "Fix #281592"

**Comment by RobFog** [comment]
Oh, I thought both works.

**Comment by lvinken** [comment]
Accidentally added a few commits containing unfinished work, will have to complete that before this PR can be merged.

**Comment by lvinken** [comment]
Finished work on second issue and squashed. Should be ready to merge now.

**Comment by anatoly-os** [comment]
@lvinken thanks for bringing the experience of using smart pointers! Hope to see more here and there in the code :)

**Pull request merged**
