### PR TITLE
fix #104171: crash when flipping articulation of grace note

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by MarcSabatella** [comment]
I can't reproduce the crash, but I can believe it happens, maybe something uninitialized that happens to have a harmless value for me but not for you.  However, I don't understand how the propsoed fix could have any impact on this.  This function isn't ever called when following the steps listed.  Can you explain how this is relevant?

**Comment by Jojo-Schmitz** [comment]
I'm not quite sure why we end up there either, but I've seen that we do, and have tested that with this change the crash does not happen.
Although on other occasions I don't end up at that place and it doesn't crash either (at some other place)
So I think while this change is good, it may not be the root cause

**Comment by lasconic** [comment]
I'm trying to track the root cause but I can't make it crash with a debug build on windows or mac. Only with a release build...

**Comment by Jojo-Schmitz** [comment]
I can reproduce when using -e and attaching the debugger to musescore after start. At least sometimes...
But yes, this PR, while surely fixing a protential crash, does not really solve the issue at hand, or if so, only 'by accident'

**Comment by lasconic** [comment]
I will merge the PR, it doesn't hurt... but there is something fishy...

**Pull request merged**
