### PR TITLE
Export excerpts for png in the way of pdf when -P

### PR DESCRIPTION
**Pull request by zhangchn**
Adding support for -P command-line argument to export all excerpts as PNG images, like exporting a PDF document.
A suffix of '__excerpt__%1', where the variable is the index number for the excerpt, is appended to the file name.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
A redo of #2557. The Travis failure seems to be due to  d42f0e1, and not causes by this PR

**Comment by Jojo-Schmitz** [comment]
A redo of #2557. The Travis failure seems to be due to  d42f0e1, and not causes by this PR

Still watch out for the formatting, you left out a couple spaces, where our coding style wants them.
e,g.:  `for (a : b) {`

Did you sign the [CLA](https://musescore.org/cla) yet?

**Comment by zhangchn** [comment]
yes, I did sign.

**Comment by lasconic** [comment]
For future reference, zhanchn username in musescorre.org is ttflee333

**Comment by lasconic** [comment]
@zhangchn Welcome in the MuseScore contributor community

**Pull request merged**
