### PR TITLE
Fix #22376

### LINKED ISSUE #22376: When adding notes to single whole note with shortcut, selection is removed after first action
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

_No response_

### Steps to reproduce

1. Add whole note
2. Select measure
3. Press Alt+3 several times to create chord - you **can add only one note at a time**

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/644a9f85-f668-449c-87f5-8406022da1e6

### MuseScore Version

4.4 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

all

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by XiaoMigros**
Resolves: #22376

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

**Review by cbjeukendrup — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested on Win10. Now the behavior is changed when using **Add interval** after **range selection** (comparing with 4.3 and 3.6.2). But it fixes another bug. 
@MarcSabatella What do you think about it? (I remember you logged something about inability adding intervals to multiple notes simultaneously)

https://github.com/musescore/MuseScore/assets/90187801/caf6db7b-279e-4440-bea8-e7be02796ba9

FYI @bkunda

**Comment by MarcSabatella** [comment]
I also thought I recalled having submitted - or at least commented on - an issue about adding intervals to range selections.  But I’m not actually finding that - just one about the command not actually playing the note when applied to single notes, and that was fixed long ago.

Anyhow, I definitely agree that it would be better if “add interval” preserved a range selection, so you could build chords over an entire selection, and based on the video it looks like this PR does accomplish that.  The behavior with “list selection” of multiple notes also seems good, although somehow I care less about that.

**Comment by XiaoMigros** [comment]
FWIW, retaining the range selection was principially introduced in #20980, aside from the whole note bug being fixed here

**Comment by DmitryArefiev** [comment]
> FWIW, retaining the range selection was principially introduced in #20980, aside from the whole note bug being fixed here

Got it. Thanks!


Tested #22376 on Win10, Mac13.6 - **FIXED**

**Pull request merged**
