### PR TITLE
Fix #11120: Added chromatic solfege noteheads to both solfege head sc…

### LINKED ISSUE #11120: [MU4 Task] Add Chromatic Solfege noteheads
**Task description**
Add chromatic solfege [noteheads](https://w3c.github.io/smufl/latest/tables/note-name-noteheads-supplement.html).  Copied over from this [issue](https://musescore.org/en/node/329930).
These will be added to the movable and fixed solfege notehead schemes.

I'm currently working on this!

### PR DESCRIPTION
**Pull request by miiizen**
…hemes

Resolves: #11120

### CODE REVIEW

**Comment by DmitryArefiev** [comment]
Hi @miiizen , can you help me  how can I add a note names instead of using plugin (Note Names)? 
The current version of Note Names (3.5) doesn't work now in MU4

**Comment by MarcSabatella** [comment]
The way note names works in MU3 is you simply select a "Notehead scheme" for the selected notes in the Inspector.  it appears this feature has been removed for MU4, unfortunately.  It really should be added back - many people rely on this.

Meanwhile, you can still access notehead schemes on a per-staff basis via Staff/part properties, Advanced Style properties.

**Comment by miiizen** [comment]
@DmitryArefiev can't believe I didn't check that so sorry! I'll sort that out.

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev can't believe I didn't check that so sorry! I'll sort that out.

@miiizen Oh, it was my bad! I see now, that only Movable scheme doesn't respond on Key Signatures (as it should!) 
but **Fixed Do solfege scheme works fine in that case**. Sorry for disturbing!

**Comment by DmitryArefiev** [comment]
Tested #11120 on Win10, Mac12, LinuxMint 20.2 - **FIXED**      

@RomanPudashkin @igorkorsukov Please review

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
