### PR TITLE
New shortcut L for loop

### PR DESCRIPTION
**Pull request by tomcucinotta**
just something I need quite often, and reaching out to the toolbar button with the mouse is not very handy

### CODE REVIEW

**Comment by MarcSabatella** [comment]
My recollection is there used to be a shortcut but it was deliberately removed because too many people were hitting it accidentally then wondering what those flags were for and how to get rid of them.  Not sure adding a default shortcut back for this function makes sense.  But of course if you personally use this feature a lot you can add a shortcut for your own use via Edit : Prefersnces / Shortcuts.

**Comment by Jojo-Schmitz** [comment]
It used to be  Shift+I for the In position and Shift+O for the Out position. Shift+L to activate/desactivate the loop feature.
It apparently got changed to Ctrl+Alt+[, Ctrl+Alt+] and nothing, respectively, in a0c7ab7.
Shift+L is now for 'relayout'.

**Comment by tomcucinotta** [comment]
I see, I didn't know these had been removed previously.
FYI, I'm just adding these (probably all 3, loop-in, loop-out and loop-toggle) to the MIDI remote controllable features as well! Might also be handy to be able to just move loop-in/out by 1 measure forward/backward, selecting a region for the loop using the mouse is just cumbersome while your hands are on the keyboard.

**Comment by tomcucinotta** [comment]
just to mention that I added my desired shortcuts straight to the MIDI remote:
https://github.com/tomcucinotta/MuseScore/commit/d007fce31129dd85a1d8173aa52b4a9773a29075

**Comment by lasconic** [comment]
Yes, direct letter for such a feature is a bit disturbing for the general user. And it's really easy to not understand what the two blue lines are for.

I close this PR.

**Pull request closed without merging**
