### PR TITLE
fix #91056: tempoLabel now changes appropriately

### PR DESCRIPTION
**Pull request by awelch83**

### CODE REVIEW

**Comment by awelch83** [comment]
Do I need to close this pull request and submit a new one?

Many months ago, I think showed me an alternative. It might've been <code>git push --force<code>

**Comment by Jojo-Schmitz** [comment]
No Need to close, see #1690, there is the explanation you refer to

**Comment by awelch83** [comment]
This is interesting. I literally just completed the changed that you had asked for, @Jojo-Schmitz, and when I came here to check on it I noticed that the pull request had already been merged. Did this happen automatically somehow, or did you just happen to be here the moment I pushed the update?

**Comment by Jojo-Schmitz** [comment]
It isn't merged, you closed the PR and deleted the branch

**Comment by awelch83** [comment]
What the hell... When I logged in and clicked the pull request, it said something along the lines of "Pull request has bee merged. You may safely delete the branch now"

I'll restore it then, I guess. I'm not sure what that was about.

**Comment by awelch83** [comment]
screen shot 2015-12-22 at 12 13 25 am

**Comment by awelch83** [comment]
Was it merged, or not? I'm confused... You're saying it wasn't, @Jojo-Schmitz, and github seems to be telling me it was (see screenshot posted above).

**Comment by awelch83** [comment]
Cool. No answer/explanation.

Not exactly the best way to encourage a motivated, new contributor to dig in and get involved. What's the point if their efforts (assuming the code is correct and passes tests) are going to be ignored? I'm receiving contradictory information and am trying to figure out what I need to do to get this pushed through. That knowledge, whenever someone chooses to impart it, is knowledge that I'll be able to utilize in the future with this project... @Jojo-Schmitz is telling me the pull request hasn't been merged. Github is telling me the pull request has been merged. Both can't be true.

**Comment by thomasbonte** [comment]
Hi Aaron, we appreciate your efforts as a first time contributor. Keep into
account it's holiday season, so there is less activity and support. That
said, we invite you to join us on irc at #musescore on freenode.net to get
in direct contact with other developers who can help you out.

**Comment by Jojo-Schmitz** [comment]
Also consider differences in timezone.
This PR has not been merged. Check the commit log, if you dont believe me.
It has been closed, by you, then you deleted and later restored the branch, at least that is what I see.

**Comment by lasconic** [comment]
I didn't follow the whole thing but currently this PR is closed and empty. There is 0 commits in it.
If I go to your branch https://github.com/awelch83/MuseScore/tree/91056-tempolabel  it's even with MuseScore master but doesn't contain any commit by you. So I assume github thinks that your branch has been merged because it's identical to master, but it's not the case. My guess is that you accidentally removed your commit from your branch.

**Pull request closed without merging**
