### PR TITLE
fix #197716 unable to upload file with custom sf

### PR DESCRIPTION
**Pull request by anatoly-os**
Fixed several tries code:
File was opened once so if statement is false (warning on opening already opened file) on second and further tries.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Need to rebase to 2.3?

**Comment by Jojo-Schmitz** [comment]
is this still needed?

**Comment by anatoly-os** [comment]
Let me revise the code. It has been done to allow multiple attempts. I cannot reproduce the case, btw. Maybe, switching off wi-fi will help.

**Comment by anatoly-os** [comment]
Uploading audio works great in 2.3.2.

**Pull request closed without merging**
