### PR TITLE
Fix #96451: Change orchestral percussion instruments to use orchestral percussion sounds

### PR DESCRIPTION
**Pull request by ZackTheCardshark**

### CODE REVIEW

**Comment by ZackTheCardshark** [comment]
Can anybody help me resolve this with the test files?

**Comment by jeetee** [comment]
From what I gather from the failed test, you'd probably have to update some 'expected end result' files.
Using your changed MuseScore version, import mtest\libmscore\midimapping\test18.mid and save the resulting score as test18-ref.mscx in that same folder.
The same should be true for the following files:
/mtest/importmidi/perc_triplet.mid -> /mtest/importmidi/perc_triplet.mscx
/mtest/importmidi/perc_respect_beat.mid -> /mtest/importmidi/perc_respect_beat.mscx

**Comment by ZackTheCardshark** [comment]
Thank you very much. I'll try that out (simply loading the changed
instruments.xml file into an existing MuseScore, because I haven't yet
figured out how to compile a working build from source).

**Comment by ZackTheCardshark** [comment]
What went wrong? I'm afraid I'm helpless.

**Comment by jeetee** [comment]
Comparing of the result files still fails. Reason being that the MuseScore version recorded in both files doesn't match (you've used 2.0.2 while travis uses your master-commit-version).
I'll try and fork your version, build it on my machine and see if I can create the expected end result files for you. Hopefully that happens somewhere today :)

Alternatively, now would be a good opportunity to figure out how to build from source yourself ;)

**Comment by AntonioBL** [comment]
Here are the files. In order to save test files, MuseScore should be run with -t option. However, these required additional manual editing since the files generated in the mtest are missing other elements (for example tempo texts in the importmidi, tuplet number style, and "originalFormat" tag).

However, there is something strange: during import the instrument changed after this PR, for example from 5-line drumset to 1-line snare drum (and vice versa for test18); is this expected?

Ciao,
ABL


[test-files.zip](https://github.com/musescore/MuseScore/files/124464/test-files.zip)

**Comment by ZackTheCardshark** [comment]
Thank you both for your help. I did learn to build, more or less (see https://musescore.org/en/node/91601#comment-407396), but though everything looked right, the resulting application simply immediately quit as soon as it was launched. I didn't have the patience to repeat the process.

And no, the difference in staff type is not expected—though perhaps it is correct? If not, I clearly did something wrong with instruments.xml, but I have no idea what.

**Comment by Jojo-Schmitz** [comment]
Seems there are quite a few commits in the PR that really shouldn't be there, probably all the ones where the commit message starts with "Merge", but surely those starting with "Merge remote-tracking branch"

**Comment by ZackTheCardshark** [comment]
Undoubtedly. Unfortunately, I know neither why those are showing up, nor how to get rid of them.

**Comment by Parker8283** [comment]
You can squash the commits with `git rebase` back down to one.

**Comment by ZackTheCardshark** [comment]
Hanging my head in shame—I really don't know how to do that. The PRs I've been successful with were one-file changes managed entirely through the website. Now I've got these forks and branches and I don't know how to handle them. I'm also totally not a programmer.

However, I'm going to experiment with interpreting the information at https://help.github.com/articles/about-git-rebase/ and see what I can do.

**Comment by Parker8283** [comment]
Everyone's been there at one point or another. Usually Git GUIs/IDEs have easier support for this, but just a quick Google of squashing commits with Git should get you on the right track.

**Comment by ZackTheCardshark** [comment]
Thank you. To get started, how do I specify the repository I want? If I begin with <code>git checkout master</code> like several sources seem to recommend, I get <code>fatal: Not a git repository (or any of the parent directories): .git</code> .

**Comment by lasconic** [comment]
You should cd in the directory. If you have no idea what i'm talking about, you can start here http://blog.teamtreehouse.com/introduction-to-the-mac-os-x-command-line

**Comment by ZackTheCardshark** [comment]
I'm trying to follow the instructions at https://davidwalsh.name/squash-commits-git. After the <code>git rebase -i master</code> step, I keep getting the terminal into some kind of state where typing doesn't work, and neither do things like [Enter] and [Esc].

**Comment by AntonioBL** [comment]
It should have opened a file in vi editor (command line editor), showing the commits.
You should navigate with the arrow keys and modify what is needed. See this for help:
https://www.cs.colostate.edu/helpdocs/vi.html
https://www.cs.rit.edu/~cslab/vi.html
Basically, go the "pick" word of the commit you want to squash, hit "cw" (without quotes) and write "squash" (w/o quotes) and then "Esc": it overwrites the word "pick". When finished, type ":x" (w/o quotes) to save and continue the rebase. A similar thing for the commit message.

**Comment by ZackTheCardshark** [comment]
Oy vey. It's not giving me a list of commits. Am I in the wrong branch or something?
screen shot 1

**Comment by Parker8283** [comment]
Here's what I do.
`git checkout ${name of branch that has your conmits}`
`git rebase -i HEAD~${number of commits to squash here}`
Change all commits after the first one to `squash`
Save and close the editor
Comment out all the other commit messages but the first one; modify it if you'd like
Save and close the editor
`git push -f` to force push your changes

Hopefully that helps.

**Comment by ZackTheCardshark** [comment]
Thank you! Now I got right up to the first "Save and close the editor"—but then it says <code>Cannot 'squash' without a previous commit</code>.

**Comment by Parker8283** [comment]
Make sure the first commit is still `pick`

**Comment by ZackTheCardshark** [comment]
VICTORY! Thank you so much! I don't know how I missed that.

**Comment by Parker8283** [comment]
Glad I could be of assistance!

**Comment by lasconic** [comment]
Thanks for the effort!

For anyone who wonders (like me) why the tests were failing: Since we change instruments.xml, we disturb [this code](https://github.com/musescore/MuseScore/blob/d1dd9c882d46546b2f176707c97000ba91a6f0f6/mscore/importmidi/importmidi_instrument.cpp#L164), the first file `perc_respect_beat.mid` for example has a program change == 51.

**Comment by Jojo-Schmitz** [comment]
And for fedfd74 (2.0.3) too

**Pull request merged**
