### PR TITLE
note brackets are actually parenthesis

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
Parenthesis is singular; parentheses is plural, for the pair.

**Comment by Jojo-Schmitz** [comment]
@wschweer was too quick

**Comment by Jojo-Schmitz** [comment]
See #2980

**Comment by Jojo-Schmitz** [comment]
@IsaacWeiss: thanks, I was actually wondering about that and tempted to append an apostrophe to indicate plural ;-)

**Pull request merged**
