### PR TITLE
Rephrase arrow accidentals as quarter tone offsets

### PR DESCRIPTION
**Pull request by rettinghaus**
This small PR improves the readability of cent offsets in the Gould arrow quartertone range.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Why Gould arrow quartertones only?

**Comment by Jojo-Schmitz** [comment]
And it isn't 'just' the redability of these offsets, it also is playback

**Comment by Jojo-Schmitz** [comment]
No idea why, but there's a vtest failing:
gliss-4-1 diff

**Comment by sammik** [comment]
As microtonal support is wery limited at the moment, all microtonal accidentals are (should be) interpreted as detuned "NATURAL".

**Comment by Jojo-Schmitz** [comment]
Yes, I agree

**Comment by Jojo-Schmitz** [comment]
A unit test fails, for braille, related to quarter tone accidentals, see https://github.com/musescore/MuseScore/actions/runs/6847965645/job/18617220769?pr=19805#step:9:1011

**Comment by Jojo-Schmitz** [comment]
and still the same vtest problem as mentioned above, now additionally another one:
guitarBend-8-1 diff

**Comment by Jojo-Schmitz** [comment]
Actually it seems accidentalWyschnegradsky6TwelfthsFlat and accidentalWyschnegradsky6TwelfthsSharp might have that issue too: https://github.com/musescore/MuseScore/blob/c94aa1bd42aca6f0cc080a0adc0d052663ed437f/src/engraving/dom/accidental.cpp#L177-L178

**Pull request closed without merging**
