### PR TITLE
[MU4] pedal_change

### PR DESCRIPTION
**Pull request by vpereverzev**
Resolves: https://github.com/musescore/MuseScore/issues/12869

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Tantacrul** [comment]
Just tested this for Fluid only. Working well on the scores I tested! Great stuff.

**Comment by Tantacrul** [comment]
@MarcSabatella - it seems that for both you and I, this is the final fix that makes a complex test score of mine now play back perfectly.

**Comment by MarcSabatella** [comment]
Is that horn change really relevant?  Anyhow, I tested, and unfortunately it isn't working for me on Reunion - I think because of the dynamics, because when I remove them, it works.  Also, the pedal markings now disappear on save/reload.  And the end hooks is missing if it crosses systems.

**Comment by MarcSabatella** [comment]
Actually, not just the end hook - the pedal line doesn't continue across syste,s at all, if there is another starting at the same place:

image

(note the missing continuation of the pedal line going into the last system)

**Comment by MarcSabatella** [comment]
More relevant info - if I add the pedal lines back using last night's build then load into the artifact from this one, it does mostly work even with the dynamics, but, the last note of the first measure of the pedal passage getds chopped off.  That happens in the nightly too, if I try shortening the line to not overlap.

**Comment by MarcSabatella** [comment]
Here's the actual score I am testing (just rename to ".mscz").  Unlike the "official" version on musescore.com, this one was created from scratch in a recent MU4 build.  You'll need to add the pedal lines back in because they were lost on the save again.
[Reunion-40-scratch.zip](https://github.com/musescore/MuseScore/files/9787850/Reunion-40-scratch.zip)

**Comment by Tantacrul** [comment]
I'm getting the strangest error @MarcSabatella 
image

**Comment by MarcSabatella** [comment]
This *is* the file, I just renamed it from msc to zip so GitHub would accept it.  Just rename it back - no need to use zip at all.

**Comment by Tantacrul** [comment]
> This _is_ the file, I just renamed it from msc to zip so GitHub would accept it. Just rename it back - no need to use zip at all.

I did rename it and I'm getting this bizarre error.

**Comment by MarcSabatella** [comment]
As I continue to experiment, I get all sorts of kind of randomy different results, but none of them amount ot it actually working correctly.  Mostly, I always see the non-continuation, I always hear the last two measure not pedal, and I usually hear the first measure cut off too soon.  Maybe the tempo changes also somehow get in the way?  Or the arpeggios, or the haripins, or the slurs.  Anyhow, if you're not hearing exactly what I described, no big surprise.

**Comment by Tantacrul** [comment]
I think I got the problem. It's the rallentando in Reunion. I've replicated it here:
https://www.dropbox.com/s/3pzst6nncxdhgly/TEMPO_LINE_VS_PEDAL_LINE.mscz?dl=0

**Comment by MarcSabatella** [comment]
Yep, I think you're right.  Since the pedal lines were lost on the save, I guessed on adding them back in (every half note?).

BTW, it's all but the last pedal line that gets lost on save.

**Comment by vpereverzev** [comment]
@MarcSabatella @Tantacrul  there is a new fix coming on. Please check it again

**Comment by MarcSabatella** [comment]
The more recent build fixes the engraving issue and the saving issue, but it still fails on playback using the score I attached earlier.

**Comment by vpereverzev** [comment]
> The more recent build fixes the engraving issue and the saving issue, but it still fails on playback using the score I attached earlier.

Yea, @Tantacrul was right. There was a separate issue whith gradual tempo change (which is a spanner) clashing with other spanners, like pedal line. Just pushed some changes here

**Comment by cbjeukendrup** [comment]
@vpereverzev I think all those other horns need to be adjusted as well, from `"a-horn"` up to `"c-horn"`. (Maybe others too? but those are already distinguished by SoundSubCategory::Alto or Bass.)

Another thought (this one is rather about semantics): since English Horn is a completely different instrument, and has `SoundId::Oboe` (which seems good to me), I suggest that simply `{ SoundId::Horn, SoundCategory::Winds, {}, {} }` should point to the (French) horn sound anyway. (Just like in real life: if you say simply "horn", you're much more likely to mean French horn than English horn.) But I don't know whether we can decide about this, or that it is part of the MPE standard.

**Comment by vpereverzev** [comment]
> @vpereverzev I think all those other horns need to be adjusted as well, from `"a-horn"` up to `"c-horn"`. (Maybe others too? but those are already distinguished by SoundSubCategory::Alto or Bass.)
> 
> Another thought (this one is rather about semantics): since English Horn is a completely different instrument, and has `SoundId::Oboe` (which seems good to me), I suggest that simply `{ SoundId::Horn, SoundCategory::Winds, {}, {} }` should point to the (French) horn sound anyway. (Just like in real life: if you say simply "horn", you're much more likely to mean French horn than English horn.) But I don't know whether we can decide about this, or that it is part of the MPE standard.

we'll be updating MuseSounds mappings separately, don't involve them in this discussion. That's entire different and bloody exhausting story :D

**Comment by MarcSabatella** [comment]
Getting closer for sure!

Still, though, on that same score, the last three notes of bar 17 (the first measure with the pedal), as well as the entirety of the last two bars, don't sustain.  Try setting the "meno mosso" marking in bar 17 to 60 BPM or so, and listen with headphones.  You can clearly hear the sustain stop aroiund when the fourth note "B" plays in the LH in bar 17 (and then resume in bar 18).  And again, there is no sustain whatsoever on the big cross-staff arpeggio.  That one works if I remove the pedal line in the previous bar, or if I remove the rallentando.

It's also still the case that if I delete the pedal lines and add them back, they don't play at all after the first three notes of bar 17 - none of the remaining bars sustain at all.  Not unless I then do something else to trigger the playback info to be recalculated, like select the passage then press Ctrl+Down followed by Ctrl+Up.  So it seems it (partially) works on score load, but not immediately on adding the pedal, unless you do something else to force it to happen.

Not sure if it's coincidence or not, but there is also an odd effect in bar 19 - again, best experienced at a slower tempo, and through headphones.  Although both bar 17 and 19 have diminuendos, there is a very noticeable *increase* in volume half way through bar 19.  I'm guessing that's about the samples themselves.  But somehow it seems to me they also increase the volume of the previously sustain notes, if the pedal is on.  Maybe somehow that relates to the dropping of the sustain in bar 17 too?

And - do the horn changes really have anything to do with this?  Just wondering why they are part of this PR.

**Comment by Tantacrul** [comment]
I've tested again using reunion and re-writing the passage myself to isolate the remaining issue. It is clear to me now that this happens when **the end of a tempo line meets the beginning of a pedal line**.

[Link to new score demonstrating the issue
](https://www.dropbox.com/s/pw7u5n9z5dhvhoh/TEMPO_LINE_VS_PEDAL_LINE_V2.mscz?dl=0)

It's a bit tricky to understand visually because the snapping works differently. Here the **rall** ends at the end of the measure and the pedal line initiates on the first beat.

So I'm not sure if they are on the same beat or not... or whether they're just really close together.
image

Regardless, we need to replace this entire system in future releases!

**Comment by vpereverzev** [comment]
> I've tested again using reunion and re-writing the passage myself to isolate the remaining issue. It is clear to me now that this happens when **the end of a tempo line meets the beginning of a pedal line**.
> 
> [Link to new score demonstrating the issue ](https://www.dropbox.com/s/pw7u5n9z5dhvhoh/TEMPO_LINE_VS_PEDAL_LINE_V2.mscz?dl=0)
> 
> It's a bit tricky to understand visually because the snapping works differently. Here the **rall** ends at the end of the first measure and the pedal line initiates on the first beat of the second measure.
> 
> So I'm not sure if they are on the same beat or not... or whether they're just really close together. image
> 
> Regardless, we need to replace this entire system in future releases!

Did you tested this on the latest build? There shouldn't be clash with tempo lines anymore. Although I've found an oppiste issue where lines can clash with other lines from **previous measures** because of the "anchors"

**Comment by MarcSabatella** [comment]
The most recent build I see is [MU4_3253434985_Lin_13759_[MU4]](https://github.com/musescore/MuseScore/suites/8786017110/artifacts/398963764).  Thus one definitely fails on Reunion.  Be sure to use the version I attach to the this thread - that's the one created within MuseScore 4 using gradual tempo changes.  The version on musecore.com was created in an older version and thus fakes the gradual tempo changes using normal tempo text.

For me it has exactly the problems I stated above:

1) the last three notes of bar 17 do not sustain
2) the last two bars do not sustain
3) if I delete the pedal lines and re-add them, they do not play at all after the first three notes of bar 17, until I do something to force playback info to be updated

I re-downloaded the score I attached earlier to be sure I'm testing the same score.  Here is the direct link:

https://github.com/musescore/MuseScore/files/9787850/Reunion-40-scratch.zip

**Comment by Tantacrul** [comment]
@vpereverzev I tested it on this PR this morning. I actually downloaded it twice to be sure. Unless there's something I'm missing?

**Comment by vpereverzev** [comment]
> @vpereverzev I tested it on this PR this morning. I actually downloaded it twice to be sure. Unless there's something I'm missing?

Just pushed the latest changes. The case with tempo lines should be fixed

**Comment by cbjeukendrup** [comment]
@vpereverzev Look at this annoying example... [Breaking_SpannersMetaParser_spannerDuration.mscz.zip](https://github.com/musescore/MuseScore/files/9802893/Breaking.SpannersMetaParser.spannerDuration.mscz.zip)
Scherm­afbeelding 2022-10-17 om 18 49 45

Of course, this is just an artificial example constructed to break the `SpannersMetaParser::spannerDuration` method, but maybe more natural examples would be broken too.

**Comment by vpereverzev** [comment]
> @vpereverzev Look at this annoying example... [Breaking_SpannersMetaParser_spannerDuration.mscz.zip](https://github.com/musescore/MuseScore/files/9802893/Breaking.SpannersMetaParser.spannerDuration.mscz.zip) Scherm­afbeelding 2022-10-17 om 18 49 45
> 
> Of course, this is just an artificial example constructed to break the `SpannersMetaParser::spannerDuration` method, but maybe more natural examples would be broken too.

There is still a number of issues which we can't really properly fix so far. As we discussed with @Tantacrul we'd make a fix for the originally mentioned problems in the issue attached. As for the rest of them.. there is a couple of dirty workarounds and ideas I'd try to implement later on, after all the high-priority issues

**Pull request merged**
