### PR TITLE
fix #298975: improve Parts dialog, New Part tool tip 

### PR DESCRIPTION
**Pull request by riaanvn**
Resolves: https://musescore.org/en/node/298975

*Use "x" letter to fill the checkboxes below like [x]*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [n/a] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by riaanvn** [comment]
Screenshot of Single Part tool tip

Single Part tool tip

**Comment by Howard-C** [comment]
3.4 isn't released yet, so maybe not post-3.4 ;-)

**Comment by riaanvn** [comment]
I did flag it WIP, assuming the release managers will put a "work in progress" label on it. I would not want it merged now and cause issues for translators, or the fact that the translations have already been extracted from Transifex. What would you suggest I call it or do instead?

**Comment by Howard-C** [comment]
Well, there're still three weeks before 3.4 official release, so if this is merged very soon, translators will still have enough time to translate. So I'd suggest simply get rid of the "post 3.4".

**Comment by riaanvn** [comment]
Thanks, am convinced. Removed references to post-3.4 and WIP. This PR can be merged

**Pull request merged**
