### PR TITLE
Add channel switch staff texts for SATB Closed Score and Barbershop

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
also useful for the 'instruments' Women and Men
As discussed on the developers' chat

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
What about this for 3.1? It does add 4 strings to the translations.

**Comment by anatoly-os** [comment]
I looked at the PR several times and didn't find it absolutely correct. The title mentions changes for the particular templates, but the real changes are more items to the palette. So, what is the actual goal of this PR?

**Comment by Jojo-Schmitz** [comment]
It adds staff text channel switch text for the use with those templates (and the Women/Men 'instruments'), similar to the mute, open, pizzicato, tremolo, arco texts

**Comment by Jojo-Schmitz** [comment]
A question is whether to set these texts to invisble by default?

**Comment by Jojo-Schmitz** [comment]
There was an error though, using `setChannelName()` on the wrong variables, fixed now.

**Comment by anatoly-os** [comment]
The question is why do we add specific purpose functionality to a general purpose palette. It is a part of another discussion anyway.

**Comment by Jojo-Schmitz** [comment]
See this also in connection with #5770

**Pull request merged**
