### PR TITLE
Fix #113811: Dynamics are positioned differently depending on stem direction, and horizontal offset is added on copy and paste

### PR DESCRIPTION
**Pull request by IsaacWeiss**

### CODE REVIEW

**Comment by lasconic** [comment]
The positioning of dynamics is now handled differently, through the "autoplace" feature.

**Comment by IsaacWeiss** [comment]
I don't understand—the relevant code was untouched, and the problem still persists exactly the same in nightly 3543170. Why did you close this?

**Comment by lasconic** [comment]
The PR needed rebase and Werner just touched the dynamics code so I expected this to be handled differently. Feel free to rebased and open again.

**Comment by IsaacWeiss** [comment]
See #2668.

**Pull request closed without merging**
