### PR TITLE
fix #273973: Playback cursor disappears after splitting then restoring the display

### PR DESCRIPTION
**Pull request by mattmcclinch**
See https://musescore.org/en/node/273973.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I guess this might be small and innocent enough to also make it into 2.3?

**Comment by mattmcclinch** [comment]
That was my hope as well. It really has nothing to do with the playback cursor. I don't think we want the "current view" to be one that isn't even visible.

**Comment by anatoly-os** [comment]
@mattmcclinch why didn't you add `setCurrentView()` call under `else` section? Isn't it required?

**Comment by anatoly-os** [comment]
Merged to 2.3.1

**Pull request merged**
