### PR TITLE
fix #283152:  measureBase::takeElements update measure flags

### PR DESCRIPTION
**Pull request by lyrra**
The critical fix is in takeElement(), the others are cleanup, code-docs, and proper warnings.

### CODE REVIEW

**Comment by dmitrio95** [comment]
Why only `sectionBreak`? MeasureBase has a lot of other flags, and at least `lineBreak`, `pageBreak` and `noBreak` depend on the presence of some elements. Maybe it would be better to process the taken elements through `MeasureBase::remove` instead?

Also, does this patch fix some reported issue? It so, could you please link it here and add `fix #123456` to your commit's message (replacing numbers with the actual issue number)?

**Comment by mattmcclinch** [comment]
Good job finding the root cause of the problem, but I would be much happier with a one-line fix in the right place, like [this](https://github.com/mattmcclinch/MuseScore/commit/b437fc41235aa1e3b1b8fc511ce4891ed450f830).

**Comment by lyrra** [comment]
Yes that looks more in line with the surrounding code. Please submit your PR.

**Comment by mattmcclinch** [comment]
> Yes that looks more in line with the surrounding code. Please submit your PR.

See #4678.

**Comment by anatoly-os** [comment]
See #4678

**Pull request closed without merging**
