### PR TITLE
[MU4] Disable writing .mxml from the GUI

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
still possible via command line

Fixes an unintended side effect of #13122

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
As far as I can tell mxml writing came in via 025baf6, not sure whether that was intentional though, might well have been a typo (@igorkorsukov?) , corrected later by adding back mxl in bf328ec (@Eism?)

**Comment by Jojo-Schmitz** [comment]
May interfere with 76997dc

**Review by shoogle — CHANGES_REQUESTED** [review]
MuseScore 3 couldn't export `.mxml` via the command line so I'm going to prevent this being merged until we find out why it was added in MuseScore 4. If it was an accident then most of https://github.com/musescore/MuseScore/pull/13122 needs to be reverted.

**Comment by Jojo-Schmitz** [comment]
I believe my 'forensics' above explain when and where this happend. As for the why only @Eism can tell, I guess.

I'd have a PR for reverting this all ready within minutes (have it ready locally, just need to push it)

**Comment by Jojo-Schmitz** [comment]
Actually see #13151

**Comment by Jojo-Schmitz** [comment]
See also #13175

**Comment by shoogle** [comment]
Closing in favour of #13175 and #13151

**Pull request closed without merging**
