### PR TITLE
Ensure workspaces are always compressed after being modified

### PR DESCRIPTION
**Pull request by shoogle**
Should be merged before other workspace PRs such as #4602.

This PR add library of useful CMake functions in build/functions.cmake. These functions are generic and can be used anywhere, hence this file is included in the top-level CMakeLists.txt. I have more functions to put in here at some point, including some that will help keep the headers tidy in `mscore/CMakeLists.txt`.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Looks good to me!
Could we get this extended to also create mscz files out of the mscx templates? Would need to also generate those thumbnails.

**Comment by shoogle** [comment]
This could indeed be used to create MSCZ files but they would not contain thumbnails unless the PNG thumbnails were added to the repository, which is not ideal.

It might be acceptable for the few scores that require custom thumbnails, but not for all of the scores currently in the repository. (And the custom thumbnails could be drawn in the code, and in fact [there is already code to do this](https://github.com/musescore/MuseScore/blob/5e42b27d9fafd109bc0d4a96fa514f29bf4c4bd5/mscore/scoreBrowser.cpp#L134-L137), so it is not really acceptable for any scores.)

A better method would be to call MuseScore (after it is built) to convert the MSCX files to MSCZ, because that way it would create the thumbnails for us. This is actually very easy to do and I have even got it working on my own branch. The only problem is you end up having to choose between:

- __Easy:__ run `mscore file.mscx -o file.mscz` for each template (slow initial build), but it only has to redo templates that change (fast subsequent builds).
- __Medium:__ run `mscore -j jobfile.json` to do all templates at once (fast initial build), but it has to redo them all if any change (slow subsequent builds).
- __Hard:__ write a very complicated CMakeLists.txt that allows you to get the best of both worlds.
  - This would involve a bunch of targets that would construct a `jobfile.json` at build time, with only the required jobs included, and then run it with MuseScore.

However, before we put any effort into this, you may want to consider the fact that the templates can never be translateable while they are separate files, so it would probably be better to generate the templates themselves within the C++ code.

Of course, we could just fix the bugs that cause thumbnail generation to be slow in the first place...

Anyway, I think this PR is ready to merge in its current form. Changes to templates will have to wait for another time.

**Comment by Jojo-Schmitz** [comment]
The json method is already prepared, I've added a json file to the repo for this. Just needs being used during build...

**Comment by shoogle** [comment]
That's helpful, but writing (and even running) the JSON file is not the problem. The issue is making sure it only runs when the templates actually change.

**Comment by Jojo-Schmitz** [comment]
Run it when any of the score or json changed

**Comment by shoogle** [comment]
Yes, but it is making that happen that is the problem. It is not difficult, it just requires reorganising things a bit which takes more time than I have available right now.

If you want to have a go, the code is:

```cmake
add_custom_command(
  OUTPUT ${LIST_OF_GENERATED_MSCZ_FILES}
  DEPENDS ${LIST_OF_INPUT_MSCX_FILES} "${CMAKE_CURRENT_SOURCE_DIR}/convert.json"
  # This relies on a bit of CMake magic to recognise that "mscore" is an
  # executable that we ask it to compile elsewhere with add_executable().
  # CMake will automagically call it with the full path to the executable.
  COMMAND mscore --template-mode -j convert.json
  WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
  VERBATIM
  )
```

The tricky part is making those lists as they need to contain absolute file paths. They are necessary because CMake needs to know every single source file that it needs to watch for changes, and every single file that will be generated by the command.

**Comment by Jojo-Schmitz** [comment]
And to generate the lists from the json, or generate the json from the mscx list, else we're out of sync way too quick

**Comment by shoogle** [comment]
```cmake
file(WRITE convert.json "[")
set(SEPARATOR "")
foreach(TEMPLATE IN LISTS TEMPLATES_LIST)
  file(APPEND convert.json "${SEPARATOR}\n{\"in\": \"${TEMPLATE}.mscx\", \"out\": \"${TEMPLATE}.mscz\"}")
  set(SEPARATOR ",")
endforeach(TEMPLATE)
file(APPEND convert.json "\n]")
```

**Pull request merged**
