### PR TITLE
[MU4] Fix  #58031: Dynamics/hairpin range for voices

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Submitting this PR for discussion, ideas, help, as so far it only has the UI implemented, not the playback

Supposed to resolve https://musescore.org/de/node/58031

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Note to self: needs a rebase.

**Comment by njvdberg** [comment]
I took this change already on board for [#304338](https://musescore.org/en/node/304338). This is on hold because the overhaul of MuseScore 4 which also effects this change. You can rebase it or just wait until the PR regarding the dynamics and hairpins at part extraction.

**Comment by Jojo-Schmitz** [comment]
It needs the real work, for having effect on the playback, before becoming useful anyway

**Comment by Jojo-Schmitz** [comment]
note to self: rebase needed

**Comment by njvdberg** [comment]
Is this still relevant for MU4, looking at all the changes in the UI?

**Comment by Jojo-Schmitz** [comment]
Not sure. That's one reason for it to be in a Draft state.

**Comment by vpereverzev** [comment]
Archived due to inactivity for a long time

**Pull request closed without merging**
