### PR TITLE
[MU3] Added run lupdate on GitHub workflow

### PR DESCRIPTION
**Pull request by igorkorsukov**
Added run lupdate on GitHub workflow

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Don't do that on Ubuntu, use macOS instead. On Ubunti and Windows that `lupdate`takes sevewral hours (!) on Mac just a couple  minutes

**Comment by igorkorsukov** [comment]
> Don't do that on Ubuntu, use macOS instead. On Linux and Windows that `lupdate` takes several hours (!), on Mac just a couple minutes

I tested, takes 20 min - this is a lot 
I will try to use MacOS. Thanks

**Comment by Jojo-Schmitz** [comment]
20 minutes isn't that bad actually. It used to take much much longer

**Comment by igorkorsukov** [comment]
> 20 minutes isn't that bad actually. It used to take much much longer

Hmm, 
on Ubuntu - 19 min
on MacOS - 49 sec!! 

This is very strange :)

**Comment by Jojo-Schmitz** [comment]
Been that way since ages. Don't even think about trying this on Windows ;-)

**Comment by Jojo-Schmitz** [comment]
Are you going to move the tx2s3 job to GitHub actions too? I think that is out last line to Travis

**Comment by igorkorsukov** [comment]
> Are you going to move the tx2s3 job (for the [tx2s3](https://github.com/musescore/tx2s3) to GitHub actions too? I think that is out last like to Travis

Yep

**Comment by Jojo-Schmitz** [comment]
Oh, there's [handbook2PDF](https://github.com/musescore/handbook2PDF) too, once day

**Comment by igorkorsukov** [comment]
> Oh, there's [handbook2PDF](https://github.com/musescore/handbook2PDF) too, once day

Let it work how it works

**Pull request merged**
