### PR TITLE
[MU4] [Tab] Force correct stem direction on non-full tab staves

### PR DESCRIPTION
**Pull request by asattely**
Resolves: https://github.com/musescore/MuseScore/issues/11606

When beams and stems had custom directions and then were switched to tab-common, those stem directions were not being overridden by the staff type. Now they are.

Note: these custom stem directions are still preserved, in case you change back to tab-full or regular notation.

### CODE REVIEW

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

Please, merge to master

**Comment by RomanPudashkin** [comment]
Please add some tests to prevent this fix from regressions

**Comment by asattely** [comment]
> Please add some tests to prevent this fix from regressions

Done, and rebased!

**Review by RomanPudashkin — APPROVED** [review]

**Comment by asattely** [comment]
Rebased again!

**Pull request merged**
