### PR TITLE
Add reorder parts buttons in parts dialog

### PR DESCRIPTION
**Pull request by vgstef**
Add the feature request (https://musescore.org/en/node/38871) to reorder parts in the parts dialog.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
The new buttons should get disabled/enabled as needed/suitable, similar to the album and instruments dialogs.

**Comment by lasconic** [comment]
Please open an issue and a PR.

**Comment by Jojo-Schmitz** [comment]
Filed an issue, see https://musescore.org/en/node/86086

**Comment by Jojo-Schmitz** [comment]
and submitted PR #2277

**Pull request merged**
