### PR TITLE
Add some piobraich-embellishments to bww-Import

### PR DESCRIPTION
**Pull request by michaelsiepmann**
I've inadvertently closed #8520 by deleting my fork. Here is another pull-request,

### CODE REVIEW

**Comment by michaelsiepmann** [comment]
I've also added dare, crunl and crunlb.

**Comment by Jojo-Schmitz** [comment]
None of these merge commits belong into the PR

**Comment by RomanPudashkin** [comment]
@michaelsiepmann Please rebase this PR. There should only be one commit. Thanks!
Screen Shot 2023-05-10 at 15 51 39

**Comment by Jojo-Schmitz** [comment]
`git pull --rebase upstream master; git push -f` should get rid of all the merge commits.

**Comment by RomanPudashkin** [comment]
@Jojo-Schmitz if you want, you can cherry-pick/rebase these commits and open a new PR :)

**Comment by Jojo-Schmitz** [comment]
Will do. only for master I guess?

**Comment by Jojo-Schmitz** [comment]
See #18465

**Pull request closed without merging**
