### PR TITLE
[MU3] Fix #318034: Make Harmonium SND capable.

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Reed Organ is, and is (basically) the same instrument.

Resolves: https://musescore.org/node/318034

See discussion on Telegram too: https://t.me/musescoreeditorchat/104446

Same should go to master too, see #7607

### CODE REVIEW

**Comment by vpereverzev** [comment]
merged in master

**Comment by Jojo-Schmitz** [comment]
Needed on 3.x too though

**Comment by Jojo-Schmitz** [comment]
Is closing this here the penalty for me having done the port to master myself?

**Comment by vpereverzev** [comment]
Of course it's not
I was aimed to merge in 3.x only those changes that we still need to port in master. But actually, there is no harm to "just" merge it in 3.x and then port only "libmscore" changes, so maybe I was in a hurry with this

**Comment by Jojo-Schmitz** [comment]
I thought so, but felt like being punished ;-)

**Comment by vpereverzev** [comment]
> I thought so, but felt like being punished ;-)

Yeah, sorry for that, I'm going to take another look on PRs that have been closed during this day. I guess we can merge them, just in case

**Pull request merged**
