### PR TITLE
[MU4] staccato_loudness

### PR DESCRIPTION
**Pull request by vpereverzev**
Resolves: #12790

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #12790 on Win10, Mac12 - **FIXED**

**Comment by MarcSabatella** [comment]
This is *much* better for sure - Reunion almost sounds like music now! :-) - but regular accent marks still don't play at all that I can tell.  Marcato does.  not sure if that was meant to have been fixed this or not.

**Comment by DmitryArefiev** [comment]
> This is _much_ better for sure - Reunion almost sounds like music now! :-) - but regular accent marks still don't play at all that I can tell. Marcato does. Not sure if that was meant to have been fixed this or not.

@MarcSabatella  Oh I see that now (comparing with MS3). Please log a separate issue when you have time. The current PR fixes loud issues when slurs involved.

Thanks!

**Comment by MarcSabatella** [comment]
There is such an issue already - see https://github.com/musescore/MuseScore/issues/11933

**Pull request merged**
