### PR TITLE
fix #99796 again, unlink the requested element, not another one

### PR DESCRIPTION
**Pull request by lasconic**

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Let me see if I follow:

We use this function both when doing (redoing) an unlink and when undoing a link.  The original problem I had been trying to fix had to do with the undo-link case, where we needed to figure out which element to unlink.  We were clearly getting it wrong sometimes, but while my change made that case right, it broke the redo-unlink case at least sometimes.  I guess we didn't notice because we had other worse issues with unlinking (or not even trying to unlink).  Now that we are actually unlinking things correctly to fix those other bugs, we are seeing the issues in the redo-unlink cases that were there all along (the bug described by cadiz1 in https://musescore.org/en/node/99796#comment-458226 was present in 2.0.2)

Am I close?

If so, then it seems the trick here is to distinguish between the redo-unlink and the undo-link cases, so we can do the right thing for redo-unlink without breaking undo-link (which we are still assuming works, even if it's kind of black magic that it does).  The undo-link cases can be detected because le will normally be set.  In the redo-unlink case le will normally be null, and in these cases we do want to unlink e rather than trying to choose something *other* than e to unlink.  And that is the effect of the change here: to notice at the start of the operation that le is null, and in the end, unlink e rather than some random non-e.

I am not sure what happens if le and e both start out as nullptr (we don't unlink anything, it seems), or if that is even possible.  I am also not totally sure we can count on le == nullptr being a reliable way of telling the difference between redo-unlink and undo-link (what about multiple undo/reo operations) or if that matters.  But it *does* seem this change fixes the problem at hand, and things basically seem to work a whole lot better than 2.0.2.

**Comment by lasconic** [comment]
You are close indeed.
*it broke the redo-unlink case at least sometimes*
Specifically when the number of linked objects is > 2. Since we weren't unlinking the good object.

*it's kind of black magic that it does*
Not really. When we link, e is an existing element, le is a new element. When we undo this, we want to unlink the new element that we just added, so we really want to unlink le which shouldn't be null or already unlinked. The only black magic to me is [why this case happens](https://github.com/musescore/MuseScore/pull/2462/files#diff-d1625459d1ed3699c71c0ca942f53b09R3653).

There is one remaining issue... using le == null is not good because it's still set next time we redo. So unlink (set le), undo (will link, we need le but we don't unset le), redo (le is set, it will unlink le while it should unlink e...)
Taking cadiz example
* 3 linked staff
* remove one (now we are good)
* undo
* redo
* add a half note and undo, it's broken

Maybe it would just be easier to code unlink and link and their undo/redo in different functions...

**Comment by lasconic** [comment]
I think I will just do that and split the implementation. It will not change anything for the link case.

**Comment by lasconic** [comment]
Ok implementation splitted. The code should be  the same for "link", just cleaned up the messages.
Unlink doesn't need to rely on the null le now and can just unlink e unconditionally.
Added tests, I had to move the code I added in the previous PR.
Comments welcome.

**Comment by MarcSabatella** [comment]
Yes, the multiple redo case was concerning me too.  There were separate functions for this once before that then were unified in https://github.com/musescore/musescore/commit/39164ce, and I agree separating them again seems to make sense.  Hopefully it doesn't break https://musescore.org/en/node/49916 (the issue fixed by that commit) again, but I'm guessing it was another aspect of that commit that fixed the issue.

**Comment by lasconic** [comment]
I can't reproduce the crash from  https://musescore.org/en/node/49916
I'm getting confident :) I will push this on master

**Pull request merged**
