### PR TITLE
replace icons with CC-BY 4.0 version

### PR DESCRIPTION
**Pull request by lasconic**

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
Does this change the look of some icons, like the file operations and play and rewind buttons, the same as in master currently? To me the new versions of those don't seem to fit in very well with the other older ones; it makes a few icons very crisp and sharp, while the rest remain thick and soft. I would suggest holding off on that until there are new versions of *all* the icons on the same design principles.

**Comment by Jojo-Schmitz** [comment]
This indeed  is the same set of Icon as in master. There on top we have the 2 addional ... 'skins'?

**Comment by lasconic** [comment]
It will wait for MuseScore 3.

**Comment by Jojo-Schmitz** [comment]
Pity, I liked it

**Comment by IsaacWeiss** [comment]
I liked it too, but it was only some of the icons. Better to have a matching set.

**Pull request closed without merging**
