### PR TITLE
Musicxml fixes

### PR DESCRIPTION
**Pull request by lvinken**
Two updates I'd like to see in 2.0.2:
- support for exporting more color information to MusicXML (requested by Simon Giddings)
- Fix for Sibelius whole measure rest issue (pull parser only)

### CODE REVIEW

**Comment by lasconic** [comment]
I will check the full measure rest issue in particular because I tried to import the samples from the MusicXML website yesterday and some are reported are "corrupted" because of full measure rests.

**Comment by lasconic** [comment]
Don't worry about the failing tests. My mistake...

**Comment by lvinken** [comment]
That is precisely what it aims to fix and why I feel this is must-have for 2.0.2. Most recent issues containing files produced by Sibelius suffer from this. E.g. see #62031 ("The Stolen Child full score.xml"). As always: any feedback is welcome.

**Comment by lvinken** [comment]
@lasconic, my previous comment was based on your first one (but did not refresh the browser, hadn't noticed is has already been merged).

**Pull request merged**
