### PR TITLE
Fix appveyor build

### PR DESCRIPTION
**Pull request by anatoly-os**
switch to x64 config

### CODE REVIEW

**Comment by shoogle** [comment]
The problem is more likely to be in one of the libraries. Things were working only a week ago so I'd try building an older commit and see if that works, then building newer ones until it fails. Unfortunately AppVeyor will automerge builds of pull requests so they will always be against the latest master, so you would need to enable AppVeyor builds on your personal fork, and then add this branch to the list of enabled branches in `.appveyor.yml`.

**Comment by mirabilos** [comment]
portmidi.lib(pmutil.obj) : error LNK2019: unresolved external symbol bzero referenced in function Pm_Dequeue [C:\MuseScore\msvc.build_x64\mscore\mscore.vcxproj]

Did you update portmidi?

`bzero` is a classical BSD function, it does this:

    #include <string.h>

    void
    bzero(void *b, size_t len)
    {
            memset(b, '\0', len);
    }

It’s normally provided by libc.

**Comment by anatoly-os** [comment]
I would bet on the recent Windows images update on appveyor which happened 3 days ago. I wonder why we need to update portmidi if nothing changed in our libs or/and the code.

**Comment by mirabilos** [comment]
anatoly-os dixit:

>I would bet on the recent Windows images update on appveyor which
>happened 3 days ago. I wonder why we need to update portmidi if
>nothing changed in our libs or/and the code.

Hm, this looks as if the Windows system DLLs no longer provide
some core BSD-derived libc functions.

Maybe file a bugreport?

This is bound to not just keep MuseScore from compiling, but
also it (and other software!) from running.

**Comment by dmitrio95** [comment]
@mirabilos Windows builds should not use bzero at all as it should be replaced by memset in this case:
https://github.com/musescore/MuseScore/blob/b594340524f276bf5e4089a1f29b5044481c17af/thirdparty/portmidi/pm_common/pmutil.c#L11-L13


@shoogle similar building problems were reported by other contributors since a long time ago so it is unlikely that any recent commit caused this. It looks like AppVeyor environment got an update recently (as @anatoly-os already mentioned) which caused the build fail here too.

**Comment by anatoly-os** [comment]
See #4676

**Pull request closed without merging**
