### PR TITLE
remove the Unix executable attribute from the new assets

### PR DESCRIPTION
**Pull request by mirabilos**
see PR #4101, need another round after the new assets were merged

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Also changes the content of one file, why?

**Comment by mirabilos** [comment]
I’ve removed that change now and will leave it to PR 3269 to clean up the new assets.

**Comment by mirabilos** [comment]
Please ping me when ready to merge this, I will rebase it on current master then (this PR needs updating every once in a while, especially once the new assets PR will be merged).

**Comment by anatoly-os** [comment]
@mirabilos ping :)

**Comment by mirabilos** [comment]
@anatoly-os rebased

**Pull request merged**
