### PR TITLE
Don't skip gap rests when entering notes (#17931 & #21355) 

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #17931
Resolves: #21355

Also improves input cursor logic when switching voices (first point in [this comment](https://github.com/musescore/MuseScore/pull/23911#issuecomment-2269583163)).

### CODE REVIEW

**Review by cbjeukendrup — APPROVED** [review]

**Comment by oktophonie** [comment]
From this start point:
image
then deleting the rest:
image
then entering note input mode on the 3rd beat:
image

Would it be possible for the cursor to remain in the same place (though changing to green/voice 2) if the 'Voice 2' button is pressed, (or Ctrl+Alt+2 is typed), to allow notes to be entered directly there? Right now it returns the cursor to the start of the bar:
image

At the very least, it would be nice if pressing right would move to the third beat (i.e. the gap rest in voice 2) and allow a note to be added there; unfortunately, right now, it moves to beat 3, but switches back to voice 1 (blue).

However, note that if you select the first voice 2 note and _then_ enter note input mode and press right, the cursor _does_ remain in voice 2:
image

**Review by oktophonie — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
I don't fully understand the second commit. When the "target" voice contains an element at the same segment as the current input state, then the input cursor stays at the segment where it is, and otherwise it jumps back to the beginning of the measure. Have I understood that correctly?
I wonder, why can't it _always_ stay where it is, even when the target voice doesn't contain any element there yet?

**Comment by mathesoncalum** [comment]
@cbjeukendrup Yes that's accurate!

I guess that's more of a UX question - @oktophonie any thoughts on this?

To demonstrate - start with nothing in voice 2:
Screenshot 2024-08-07 at 09 03 22

Then switch voices (we don't jump back to the beginning of the measure):
Screenshot 2024-08-07 at 09 03 29

And enter a note:
Screenshot 2024-08-07 at 09 03 38

Does that look alright to you?

**Comment by oktophonie** [comment]
I love it

**Comment by mathesoncalum** [comment]
Cool, updated now.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/17931 FIXED
https://github.com/musescore/MuseScore/issues/21355 FIXED

**Review by zacjansheski — APPROVED** [review]

**Pull request merged**
