### PR TITLE
Preserve articulations when changing chord duration

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #13429

@Eism I see that you had added this code in 68e609bab08561db95fc5fbf0b439fa1dc01ce07. What was it intended to do?

### CODE REVIEW

**Comment by Tantacrul** [comment]
Just tested it. Seems to work exactly as expected. Hopefully, this is an easy one to merge because it was quite a big usability regression! :D

Thanks @cbjeukendrup!

**Comment by Eism** [comment]
@cbjeukendrup 
It's hard for me to remember exactly what happened(two years have passed), but everything seems to work as expected after your changes.

We had a design document for this feature. We just need to test the user cases from this document.
The problem is that I can't find this document(@Tantacrul)

**Comment by Tantacrul** [comment]
This is the document where I put together the design for the articulations section of the note input bar. You'll need to skip the first few pages.
https://www.dropbox.com/s/ms5554bsej5xnxu/Note_Input_Bar_v03.pdf?dl=0

**Comment by DmitryArefiev** [comment]
@Tantacrul I found some changes in behavior (comparing with MS3) when triggering Input mode after selecting note with articulation:

 

https://user-images.githubusercontent.com/90187801/195113364-f7584deb-263f-4402-95f9-7f9c22f7ab24.mp4

**Comment by Tantacrul** [comment]
@DmitryArefiev - I'm not too worried about that. This difference has existed for months and no one has complained. I'm not even sure it needs to be changed.

My sense is that we **have** to fix the problem logged in my issue - and we can potentially add additional tweaks either in post beta or in 4.x. What do you think?

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev - I'm not too worried about that. This difference has existed for months and no one has complained. I'm not even sure it needs to be changed.
> 
> My sense is that we **have** to fix the problem logged in my issue - and we can potentially add additional tweaks either in post beta or in 4.x. What do you think?

@Tantacrul You are right! I though it was introduced by the current PT but the same result in master build. 

I totally agree to think/discuss that difference in behavior later.

**Comment by DmitryArefiev** [comment]
Tested #13429 on Win10, Mac12, LinuxMint 20.2 - **FIXED**    

@Eism Please review

**Review by Eism — APPROVED** [review]

**Pull request merged**
