### PR TITLE
Updated version to 2.2.1

### PR DESCRIPTION
**Pull request by anatoly-os**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Travis, resp. OPUOSL doesn't seem to like PRs based on 2.2 it seems?

**Comment by anatoly-os** [comment]
It is more for Nicolas to just cherrypick changes and apply to the new 2.2.1 branch.

**Comment by Jojo-Schmitz** [comment]
I wonder whether this is related to 2.2 and so 2.2.1 too still being marked as stable?

**Comment by lasconic** [comment]
merged manually in 2.2.1 branch, and marked unstable. See https://github.com/musescore/MuseScore/commit/6bd9282090f80fdfddc0fd29a6b72ff2e3e750b3

**Pull request closed without merging**
