### PR TITLE
Fix layout of Articulation Inspector

### PR DESCRIPTION
**Pull request by IsaacWeiss**
Remove wasted space along right edge

### CODE REVIEW

**Comment by vpereverzev** [comment]
@IsaacWeiss Can you add your comment from PR to the commit message? Because "Fix layout of Articulation Inspector" just tells nothing :)

**Comment by Jojo-Schmitz** [comment]
Well, it does tell me enough to see it is a good change ;-)  (I looked as it in QtDesigner too).

But please also increase the colspan of the Play button ("Wiedergabe" in German is so much longer ;-)

**Comment by IsaacWeiss** [comment]
Done and done

**Comment by Jojo-Schmitz** [comment]
Thanks, as far as I'm concorned this is ready for getting merged

**Comment by Howard-C** [comment]
Why not also eliminate the "Time stretch" option? (and make the "Ornament style" option explicitly for ornaments?)

**Comment by Jojo-Schmitz** [comment]
That's for another day and PR then :-)

**Comment by Howard-C** [comment]
Probably in a very big PR ;-)

**Pull request merged**
