### PR TITLE
fake the new clef from 19ca0fa for Gonville

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
by falling back to an existing clef with the same meaning

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Remainder of PR #2241. Not sure whether it is really needed, but it needed a rebase due to conflicts with PR #2212

**Comment by lasconic** [comment]
I prefer nothing than this. It's a reminder that we need the clefs in gootville.

**Comment by Jojo-Schmitz** [comment]
It is just one clef, that double G-clef. And keeping this PR open might serve well as a remider ;-)

**Comment by lasconic** [comment]
I'd prefer an issue ;)

**Comment by Jojo-Schmitz** [comment]
Ah, yes, sure, how could I forget that ;-)
Here we go: https://musescore.org/en/node/82741

**Pull request closed without merging**
