### PR TITLE
fix #196771 : Regroup Rhythms deletes various elements

### PR DESCRIPTION
**Pull request by AntonioBL**

### CODE REVIEW

**Comment by AntonioBL** [comment]
I basically cloned the function setNoteRest using chord clone, so that articulations, lyrics, pitch selling etc are preserved.
I have some doubts regarding the handling of slurs.
The effect of this PR on real time entry should be tested.

**Comment by Jojo-Schmitz** [comment]
Travis doesn't like it?

**Comment by AntonioBL** [comment]
From what I see, the tests were wrong: if I insert a tie from scratch, it appends an "endSpanner" tag to the note on which it ends.
I am now looking into each single test to see if the endSpanner is in the right place.
I will try to add further tests for articulations.

**Comment by AntonioBL** [comment]
Now the tests should be ok. I will squash the commit if Travis gives a green light on the tests.

Actually, there are still problems in regrouping inside tuplets (but it was the same also in the previous implementation), and the one about slurs, but it should work in the other cases.

N.B: Because of this bug https://musescore.org/en/node/270433 in some cases regrouping when an articulation is present on the first note will give a crash (related to Chord::removeMarkings not behaving properly at the moment in 3.0-dev).

**Comment by lasconic** [comment]
@shoogle if you are around and have a minute (or an hour...) could you have a look ?

**Comment by shoogle** [comment]
@lasconic, it looks good to me in `master`, but don't merge just yet as I need to test against the `2.2` branch because the code has diverged.

**Comment by shoogle** [comment]
@AntonioBL, nice job! This seems to work fine for me with real-time input.

I submitted a new PR (#3565) which needs to be merged before this one. @AntonioBL, you will need to rebase your PR once mine is merged, but it is quite easy. See my [comment](https://github.com/musescore/MuseScore/pull/3565#issue-176379004) on the other PR.

**Comment by lasconic** [comment]
I merged @shoogle's PR.

**Comment by AntonioBL** [comment]
@shoogle : Thank you for the update.
I see in your comment you suggest replacing the conflicting parts of code with those of this PR: do you think the change in chord.cpp for overlapping voices, i.e. this line
ChordRest* nextCR = nextSeg->nextChordRest(track(), backwards);
is still necessary? From what I see, the problem of overlapping voices should be solved in the updated master with that do-while  loop.

**Comment by AntonioBL** [comment]
Ok. Rebased the PR on the updated master.

**Comment by lasconic** [comment]
Thank you guys !

**Pull request merged**
