### PR TITLE
Fix issues with tempo changes during notes

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #15552
Resolves: #14369

There are several problems:
1. When converting the duration of an element from ticks to microseconds, we do that based on the tempo at the start of the element, which gives a wrong value if there are tempo changes during the element. Instead, we should look at the end and start timestamps, and use their difference as the duration.
2. We convert to microseconds too early. This means that calculations for grace notes and tremolos for example need to be done in microseconds, without any information about the tempo during the element. For example, if there is a ritenuto during a tremolo, the tremolo would need to slow down, but we can't know if we use microseconds. Instead, we should calculate the position of every tremolo note in ticks, and then convert those ticks to microseconds, so that the tremolo will slow down correctly.
3. (Not yet solved) To MuseSampler, we can only communicate the tempo at the beginning of the note; we have no way to tell MuseSampler about tempo changes during the note. This could potentially cause problems with MuseSampler (and maybe even confuse it).

### CODE REVIEW

**Comment by BoBogus** [comment]
In my own submission of this issue (#17863), I realized a potential (if perhaps a bit inelegant) solution that can at least improve the issue with long notes.  If you watch the tempo indicator on the upper left corner, you'll notice it doesn't gradually change, but rather changes in leaps every quarter note. I just realized that I could use that to my advantage by breaking a problematic half note into two tied quarter notes. The interpretation is musically the same, but the software ends up calculating it properly so the note stops in time.

So a potential solution (at least, until something more elegant can be discovered) could be for the software to automatically treat long notes as a chain of tied notes no longer than a quarter, either everywhere or just whenever they occur within a tempo change (unless the necessary calculations are memory inefficient).

**Comment by cbjeukendrup** [comment]
@BoBogus The solution used by this PR is more general and more straight-forward: instead of calculating the length based on the tempo at the start timestamp, we should calculate the end timestamp and use the difference between the start and end timestamp as the length. So, the idea is very simple, but the difficulty is to properly apply it in _all_ places.

**Comment by cbjeukendrup** [comment]
I've now fully implemented this solution in all places. It seems to work well, but I'm afraid that it is prone to rounding errors, since the resolution of "ticks" is only 480 ticks per quarter note. Maybe we should simply change that fact, because it is problematic in more situations: #16253. Ideas are welcome.

**Comment by cbjeukendrup** [comment]
Actually the PR might indeed improve the situation regarding fermatas somewhat, but that's not its main goal; fully solving the "fermata consolidation" problem would be a separate task.

**Comment by DmitryArefiev** [comment]
Tested #14369 on Win10 - **FIXED**

**Pull request merged**
