### PR TITLE
fix #278538: Implement collision avoidance between rests and notes

### PR DESCRIPTION
**Pull request by tobik**
This PR does implement collision avoidance between rests and notes in opposite voices. For measure rests, between all notes in the measure.

Resolves: https://musescore.org/en/node/278538

Rests already get a vertical offset if there are multiple voices. This works in a restricted range of pitches. But if the notes get very low or high, they will collide with rests of other voices. This often happens when transposing SATB scores. 

To avoid this the PR determines, depending of the rests voice, the highest or lowest note in the chords of opposite voices at the same segment (or all segments of the measure in case of measure rests). 

If there is a accident at the note, the offset is incremented because b requires some additional space above and # some more space below.

Stems or articulations are not taken into account, because in multi-voice measures they are at the opposite side.

The highest resp. lowest line is now used to add some extra offset if the rest is nearby, depending on the rest type. 

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
There one vtest difference, and I don't see wh< that'd be needed, before:
line-2-ref
after:
line-2-1
diff:
line-2-diff

**Comment by tobik** [comment]
I did some fine tuning. The tests passed now. Would you apply the PR and look if you like the distances?

**Comment by Jojo-Schmitz** [comment]
Add a `+ collect_artifacts` to the commit message and development builds would be generated

**Comment by tobik** [comment]
Did it work? Where are this development builds?

**Comment by Jojo-Schmitz** [comment]
Yes, it worked, they are at https://github.com/musescore/MuseScore/pull/5897/checks?check_run_id=560674186 (for Linux and Mac) and https://ci.appveyor.com/project/MuseScore/musescore/builds/31953705/artifacts (for Windows)

**Comment by tobik** [comment]
Good to know - thank you

**Comment by anatoly-os** [comment]
I like the changes and would apply them to 3.x. Could you please create a PR based on 3.x, not master?

**Comment by tobik** [comment]
What is the recommended way to do this? 
Rebase my local branch on 3.x and pull force to origin? 
Or rebase local master to 3.x, create a new branch and a PR?

**Comment by Jojo-Schmitz** [comment]
You may get away with doing it on GitHub (I think your PR is old enough for that to still work): click on the Edit button next to the PR title, then under the PR title change from base:master to base:3.x

**Comment by Jojo-Schmitz** [comment]
OTOH that 2 line change is quickly done again from scratch

**Comment by tobik** [comment]
Seems to have worked. Thank you!

**Comment by MarcSabatella** [comment]
Unfortunately these changes cause critical problems on tab staves - see https://musescore.org/en/node/306821.  The results are also off on any staves with other than 5 lines.

The tab problem is easy to fix, we need to use note->string() * 2 instead of note->line() to get the appropriate nline value is it's a tab staff.  The problem with any staves of other than five lines is harder for me to sort out.  It's probably the result of all those "magic numbers" in the switch statement not playing nice with the center diff calculation.  Or, it could be a matter of disabling the center diff calculation if we had set an explicit line value due to the offset.  @tobik if could you look at this?

**Comment by tobik** [comment]
I will look at this

**Comment by tobik** [comment]
@Marc: Does avoiding rests in a TAB staff make sense at all?

**Comment by tobik** [comment]
PR created: #6224

**Pull request merged**
