### PR TITLE
fix #57261: multi-notes tremolo not played back correctly

### PR DESCRIPTION
**Pull request by heuchi**
<s>Added a new member _chordTremolo to NoteEvent, a list, that holds pitches of notes to be played, that don't fit into both chords, because one chord consists of more notes than the other.
Pitches are added via NoteEvent::addTremoloPitch(pitch).
Changed collectNote() and renderChord() in rendermidi.cpp to build and apply this list. Extra notes are added to the chordTremolo list of the first note's NoteEvents of the chord.</s>
Edit: New version.
Create NoteEvents for every note of the first chord, either alternating with a note from the second chord (if 2nd chord has at least as many notes as 1st), or alternating with silence.
If the second chord has more notes than the first one, reuse the first note of the first chord to alternate between silence and the notes of the second chord.

### CODE REVIEW

**Comment by wschweer** [comment]
A NoteEvent is just that, a midi note event. This PR complicates  it a lot which will give problems when implementing the pianoroll editor. Tremolos should add normal NoteEvents to chords.

**Comment by heuchi** [comment]
@wschweer Thank you for your explanation.
I redid it without touching NoteEvent.
(It's indeed a lot simpler now...)

**Comment by lasconic** [comment]
Could you add a test in `mtest/libmscore/midi/`? Then if something changes and it changes the MIDI output for tremolos, the tests should fail.

**Comment by heuchi** [comment]
Added this test file, which makes the test fail for <a href="https://github.com/musescore/MuseScore/commit/6356462dbf686e4743bd46127a47bc97516b1b52">6356462dbf</a>
testmultinotetremolo

**Comment by heuchi** [comment]
Rebased.
@lasconic If there's anything more I need to do to get this merged, please tell me.

**Pull request merged**
