### PR TITLE
Fix GH#15426: Bring back the Save button (4.3.2) 

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
and also add the Save icon to "Save as", "Save a copy" and "Save selection"

See #18883

Just for the artifacts, not for a real merge...

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
> Just for the artifacts, not for a real merge...

You can also do this using just your own fork, but you need a `.github/ci_windows_mu4.yml` file on your default branch (which is 3.x in your fork). The contents must be something like:
```yml
name: CI_Windows MS4

on:
  workflow_dispatch:

jobs:
```

When these prerequisites are met, you can create artifacts at any moment by following these steps:
1. Go to Jojo-Schmitz/MuseScore
2. Click "Actions"
3. Click "CI_Windows MS4" in the sidebar
4. Click "Run workflow"
5. Choose the desired branch, enter desired build mode, and click "Run workflow"

**Comment by Jojo-Schmitz** [comment]
I want all CU jobs running, the Windows one is what I'm least interested uin, I can build that myself. I want them all, for the community, not for myself

**Comment by cbjeukendrup** [comment]
Then you apply the same procedure to those.

**Comment by Jojo-Schmitz** [comment]
That won't notarize the macOS builds

**Comment by cbjeukendrup** [comment]
This neither. Although the action runs in our repo, it runs with "your" access level, so it doesn't have access to the code signing passwords from GitHub Secrets. 

(And artifacts from pull requests are not signed anyway.)

**Comment by Jojo-Schmitz** [comment]
> You can also do this using just your own fork, but you need a `.github/ci_windows_mu4.yml` file on your default branch (which is 3.x in your fork). The contents must be something like:
> 
> ```yaml
> name: CI_Windows MS4
> 
> on:
>   workflow_dispatch:
> 
> jobs:

Error
No jobs defined in `jobs`

**Comment by cbjeukendrup** [comment]
You might need to add some dummy job, like this:
```yml
name: CI_Windows MS4

on: [workflow_dispatch]

jobs:
  dummy:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo
```

**Pull request closed without merging**
