### PR TITLE
Beam custom direction

### PR DESCRIPTION
**Pull request by Nick-Mazuk**
Previously, if a beam group was flipped (i.e., the direction is not the default), the slant for the beam was not calculated correctly. More specifically, beams would often be flat if it were supposed to be slanted, or vice versa. This would occur either when there were multiple voices on a single staff, or if the beam group was flipped manually.

This should now be fixed.

### CODE REVIEW

**Comment by Nick-Mazuk** [comment]
With the exception of this vtest, the vtests are failing as expected. I need to think about this case in the morning.

Screen Shot 2021-12-07 at 10 30 59 PM

**Comment by oktophonie** [comment]
Is this (the flipped B) not just down to the middle-line-contextual-stem-direction-flipping (now undone with #9969 )?

**Comment by Jojo-Schmitz** [comment]
Ah, I'm having the same issue in #10007

**Comment by Jojo-Schmitz** [comment]
And indeed it dues. So just rebase and it'll be fine

**Review by oktophonie — APPROVED** [review]

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
