### PR TITLE
Fix #109066 : Tempo Slider and Volume slider Left Double click wrong default values

### PR DESCRIPTION
**Pull request by nasehim7**

### CODE REVIEW

**Comment by nasehim7** [comment]
I did some blunders on my system so had to close the previous PR. I fixed the issue @ericfont and @lasconic. All for reviews, have tested this on my Linux.

**Comment by Jojo-Schmitz** [comment]
Seems small and harmless enough to make it into 2.1 too

**Comment by Jojo-Schmitz** [comment]
I know I've said this at least once to many ;-), but this does look as if adding it to 2.1 too won't harm?

**Comment by ericfont** [comment]
I agree that this should go into 2.1.

Note: I've just tested this on the latest 3.0 nightly, and it works as originally intended (I doesn't do the extra feature I requested where it would obey the user's saved synth defaults...but that is not a big deal and might have been too much effort anyways.  Double-clicking volume always goes back to the -20dB level, which is a reasonable default even though it doesn't reflect user's saved default and even though the factory reset default is -40dB).

**Comment by lasconic** [comment]
mgainSlider doesn't exist in 2.1

**Comment by Jojo-Schmitz** [comment]
So we'd just need that one line change to awl/volslider.cpp I guess?

**Comment by ericfont** [comment]
I'm the one responsible for removing "mgain" from synthcontrol.ui so that it is only inside playpanel.ui to fix #3086, and I changed the name to "mgainSlider" as well.  So I'll go ahead and make PR containing the fix using this commit plus the necessary variable name change.

**Comment by ericfont** [comment]
I made a 2.1-specific PR with same changes: #3156

I guess this title should really be "Metronome slider and Volume slider" instead of "Tempo Slider and Volume slider" but that isn't a big deal.

**Pull request merged**
