### PR TITLE
Highlight selected notes on the piano

### PR DESCRIPTION
**Pull request by paboldin**
* I want to show all the selected notes as well. Please provide pointers on how to implement that.
* I want to color code notes from different measures. How can I do it?

### CODE REVIEW

**Comment by lasconic** [comment]
Please open a feature request https://musescore.org/en/forum and explain exactly what you are trying to do.

**Comment by paboldin** [comment]
@lasconic the forum appears to be broken. Saving text here:

----------------
Hello,

I'm a beginner and would like to see hints on a keyboard for the notes selected in the score. 

This looks easy to do, should extend Score with a call to _selection->unqiueNotes()) and show it in endCmd of MuseScore.

When multiple notes are selected it would be nice to show them in different colors with matching colors on the piano keyboard.

This looks harder, since piano keyboard don't support different colors for keys, it is unclear for me how to highlight notes using different colors but this is done already for second voice.
```

**Comment by paboldin** [comment]
Here it is:
https://musescore.org/en/comment/809780

**Comment by paboldin** [comment]
Comment is "Access Denied", probably due to the link to this page.

**Comment by Jojo-Schmitz** [comment]
@thomasbonte is looking into this as we speak

**Comment by paboldin** [comment]
@Jojo-Schmitz but I'm banned now, even from musescore.com :-(

Let's continue here though. May you please take a look at the code?

**Comment by Jojo-Schmitz** [comment]
You should be unblocked by now

**Comment by lasconic** [comment]
Superseded by https://github.com/musescore/MuseScore/pull/3488

**Pull request closed without merging**
