### PR TITLE
Fix #293441: [MusicXML export] invalid XML export: direction-type is missing child element

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
TextBase::fragmentList() (last updated by commit 10ebbb9 on Aug 1, 2018) is missing a fix introduced in the similar function TextBase::plainText() (added by commit 3653f4b on Nov 19, 2018). The fix relayouts a clone of the TextBase when it encounters a TextBase with an invalid layout.

Resolves: https://musescore.org/en/node/293441

Closes: #17848

TextBase::fragmentList() (last updated by commit https://github.com/musescore/MuseScore/commit/10ebbb9080d69bb3629ca48dfb76eb2a5aadef9e on Aug 1, 2018) is missing a fix introduced in the similar function TextBase::plainText() (added by commit https://github.com/musescore/MuseScore/commit/3653f4bddb052906d805b2d57565c7d878ab6814 on Nov 19, 2018). The fix relayouts a clone of the TextBase when it encounters a TextBase with an invalid layout.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
This is actually #17848, but rebased and with fixed merge confflicts

**Comment by Jojo-Schmitz** [comment]
Difference between #17848 and this PR here is:

`if (layoutInvalid) {`
to
`if (layoutInvalid()) {`
and
`for (const TextBlock& block : text->_laypout) {`
to
`for (const TextBlock& block : text->m_blocks) {`

**Comment by Jojo-Schmitz** [comment]
@cbjeukendrup here's the rebased version of @lvinken's #17848

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
@oktophonie @asattely Does this need your review?

**Comment by Jojo-Schmitz** [comment]
Can't we get this into 4.1.0?

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/351675

**Comment by Jojo-Schmitz** [comment]
@oktophonie mind to review and approve?

**Comment by Jojo-Schmitz** [comment]
I'd really like this ine merged into master and 4.1.0...

**Review by oktophonie — APPROVED** [review]

**Pull request merged**
