### PR TITLE
Glissando as a multi-segment line.

### PR DESCRIPTION
**Pull request by mgavioli**
- Implemented as a sub-class of `SLine`.
- Anchor type changed from CHORD to NOTE: allows to attach glissando start and end points to individual notes, rather than generically to chords (with note within the chord chosen by the program).
- The Glissando element is now stored in the `Note::_spannerFor` list.
- `Chord::_glissando` has been removed and replaced by a `bool _endsGlissando`, recording whether the chord is at the end of glissando (as gliss.-end chords require more space if mid-measure or system-initial).
- Debugger UI for `Chord` updated accordingly.
- Glissando is now saved into score file as a spanner, within the initial note, and with appropriate `<endSpanner>` tag in the Glissando ending note.
- Existing scores with the old Glissando file format are correctly read back.

Notes:

- This version can read scores from older versions, but older versions **cannot read** scores from this version (they do not expect a `<Glissando>` tag within a Note). This probably requires a new file version number; as the file version number increased fairly recently, it might make sense to piggy-back this change, if merged soon.
- This implementation would rather easily allow to move the start and end anchors around (as for slurs) to override the note/chord chosen by the program when the glissando is initially created; but the UI for this is not implemented yet.

The latest commits should make the PR fully functional.

### CODE REVIEW

**Comment by mgavioli** [comment]
- Fixed cloning of glissando elements into parts and into linked staves (actually of **all** spanners attached to `Note`s)
- Fixed a bug when reading scores with the old format glissando which also contained parts
- Updated MXML I/O according to @lvinken suggestions
- Updated import GTP according to @jpirie suggestions and fixed its tests accordingly.

**Comment by lasconic** [comment]
We merged, we need to bump up the file revision in mscore.h

**Comment by lasconic** [comment]
Can you rebase this PR and maybe bump up the file revision number then?

**Comment by mgavioli** [comment]
@lasconic : rebased, aligned with recent changes and increased file version number; Travis is having its moods again, but sooner or later...

**Comment by mgavioli** [comment]
@lasconic : Travis octroya Sa grace!

**Comment by lasconic** [comment]
Let's merge it. This is hopefully the last big change we merge before MuseScore 2.0 RC.

**Pull request merged**
