### PR TITLE
fix #119376 utility functions for save/restore geometry

### PR DESCRIPTION
**Pull request by jeetee**

### CODE REVIEW

**Comment by jeetee** [comment]
Just another thought; Currently each window/dialog creates its own settingsGroup as was done previously.
I'm considering making the utility functions use a settingsGroup called "Geometries" and use the objectNames as keys in that group. This should allow us to create a "Reset Window Positions" command more easily as it could then clear out this group.

Reason is that I've often seen the "Reset to Factory Settings" been advised/required to recover from offscreen windows, which is a fairly drastic measure to have to take. The new command would leave all other settings intact.

**Comment by lasconic** [comment]
Sure. Good one.

**Comment by jeetee** [comment]
Handles a bunch of the known bugs/requests for window dialog geometries.
Still working on fixing up the MainWindow behavior (including maximized/fullscreen handling)

**Comment by IsaacWeiss** [comment]
@jeetee: Should I log a feature request for "Reset Window Positions"?

**Comment by jeetee** [comment]
@IsaacWeiss good plan, although strictly speaking, we shouldn't have offscreen windows any more with this approach, so the need for such a function is probably much lower now.

**Comment by IsaacWeiss** [comment]
Oh! I didn't realize that. Great. :-)

**Comment by Jojo-Schmitz** [comment]
Can we have this or something to the same effect for 2.0.4 too, please? Comes up increasingly in the Forums as being a problem

**Comment by jeetee** [comment]
@Jojo-Schmitz If 2.0.4 comes into play, it might be easier to update https://musescore.org/en/project/resetdialogpositions to get as close to a reset window position function as possible. This PR influenced the way of storing the information within the configuration file, breaking 2.0.x compatibility.

**Comment by Jojo-Schmitz** [comment]
I don't think the config file (MuseScore*.ini) has to be compatible between versions, Not being compatibel would possibly only affect a downdgrade to 20.x with x < 4, and then a factory reset would fix it. Maybe that factory reset could even be made part of the uninstall

**Comment by lasconic** [comment]
I don't think people with a ton of custom shortcuts/palettes/workspace would agree with that.

**Comment by Jojo-Schmitz** [comment]
Well, as an option this might work. And we do have -R and -F to chose from?

**Comment by Jojo-Schmitz** [comment]
There are loads of topics in the forums where users inistallated and reinstalled in the wrong assumption that this would be at least as good as a factory reset.

**Comment by jeetee** [comment]
For this specific PR the 'breaking' of compatibility is actually quite minor. After the PR window positions are stored differently, so if you'd use an older version, it'll have its own set of positioning info, as it uses different Settings parameters.

As for the latter remark about uninstall-reïnstall, we could perhaps go with "the VLC-way"; having an (un-)installer option to reset to defaults (I believe they call it "remove local settings cache"). But that should be its own feature request...

**Comment by Jojo-Schmitz** [comment]
See (Add "remove settings/preferences" checkbox in uninstall wizard)[https://musescore.org/en/node/88711]

**Pull request merged**
