### PR TITLE
Fix #13761: Implement Lyrics Properties in Inspector

### LINKED ISSUE #13761: [MU4 Task] Implement "Lyrics" panel in Properties with missing MS3.6 functionality and new button icon
**Task description**
This task would resolve #13673. It comprises two elements: 

1. A new "Lyrics" panel would appear in Properties whenever a lyric element is selected:

Properties_Lyrics-new

For now, this setting should function as per MS3.6 (Note also the change in label from "Verse" (3.6) to "Set to verse")

2. A new "Lyrics" button would appear in Properties whenever multiple different elements are selected:

Screenshot 2022-10-14 at 2 21 29 pm

**New button icon**
Please note the new button above uses a new icon: F441 in musescoreicon
Download the new font files here: 
[musescoreicon_14Oct22.zip](https://github.com/musescore/MuseScore/files/9786261/musescoreicon_14Oct22.zip)

@HemantAntony please feel welcome to tackle this one if you like!

Many thanks 🙂

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #13761

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by HemantAntony** [comment]
@Tantacrul This is what happens when you select a lyrics element and a note. Is this desired? Note both the Lyrics Properties and Note Properties side by side while the Text properties are separate
image

**Comment by bkunda** [comment]
> @Tantacrul @bkunda This is what happens when you select a lyrics element and a note. Is this desired? Note both the Lyrics Properties and Note Properties side by side while the Text properties are separate image

Yes this is expected. The lyrics popup will currently contain only one property ("Set verse to..."), whereas the separate text properties panel will do the same thing they do for every other text element, so this is fine. 
Is this ready for checking now?
Thanks!

**Comment by HemantAntony** [comment]
Yeah it is :)

**Review by RomanPudashkin — APPROVED** [review]

**Comment by bkunda** [comment]
🟢 Tested on MacOS and Windows. Looks good! 
Functionality seems to be the same as MS3.6, which for now is good. I've noted some UX quirks with how the "Set to verse" (Formerly "Verse") setting works, which we can address later in a separate issue. 
But for now, this is from a functional POV ready to go! Thanks so much again @HemantAntony 🙏🏻🙂

**Pull request merged**
