### PR TITLE
GUI Icon restyling - revised

### PR DESCRIPTION
**Pull request by SolarGranulation**
Pursuant to concerns and requests raised on PR #5033 I have created a new, yet traditional, set of icons for MuseScore. I've taken care to create consistent icons, without compromising clarity and familiarity. This chiefly concerns document-function icons, but also others.

mscore-icons-documents

_Note: The differences to button icons are my work; the variation in layout is a difference between the development version and that from my distro's repositories._

The Mixer interface elements have also received attention, moving toward a more contemporary 'flat' look, and using familiar visual cues to illustrate button functions. The new slider is designed to expose the underlying interface much as the current pan knob does (and the icon could probably be omitted completely, but that's a code matter.)

mscore-icons-mixer

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
A big improvement over the last iteration. However, I'm not sure this is an improvement over the current set.

On the one hand, I can see you've been very careful in some places to make details consistent—in the cloud icon, I love how you put the angle cut on the arrow to match the note and accidental icons. But in other places, I see the opposite—in a world of balanced geometric shapes, what is going on with the crazy complicated question mark?

Tantacrul suggested two areas of improvement in the toolbar icons, to eliminate "visual awkwardness... when scanning left and right": (1) choosing either outlined or filled, and (2) making everything line up. The toolbar icons you've revised are now all outlined, but many of the rest are filled (including the new ones you've suggested for the Mixer!), so much so that I'd lean rather towards making them all filled than all outline. The alignment among those five at the top left also seems markedly worse now. In addition, while I can see how appealing the idea is in theory, I don't think the particular motif of the whole note works in practice; it creates a new visual incongruity with inconsistent weight of the lines, because the outline of the notehead (naturally) varies in thickness. 

Another possible reason to prefer filled: the flap on the revised envelope icon doesn't show clearly at small sizes—it just looks like a rectangle with an X.

The new mute and solo icons are a big step in the right direction—they clearly show what they're about now. But, well, take the mute icon—when not muted, it looks like its muted. I'd say that should be a regular sound icon when unmuted, and the line across it should appear when clicking to mute. (I can't think what to do with the solo icon to clearly show when it's on and when it's off.)

I am not a fan of the slider handle being transparent, considering that it's supposed to be a metaphor for a real-world control.

By the way, what is `mixer-dial.svg` for? It doesn't seem to be used for the pan control.

**Comment by IsaacWeiss** [comment]
Also, quick tips: the difference in layout you noticed is actually just the Basic vs. the Advanced workspace, which you can switch between at the bottom left; and if you continue working with the same branch, you don't need to close one pull request and open another one (if you do want to close it temporarily, you can reopen the same one).

**Comment by mkruselj** [comment]
Solo and Mute buttons are unfortunately really bad, sorry :( Way too many speaker iconograms in just those two icons, to me it creates too much visual noise.

The volume slider you made doesn't need the polygonal "thumb" part, it can very well just look like a slider in Ableton Live (since the Pan knob has obviously been inspired by Live's pan knob design, too). It would also be consistent - just a straight line and a triangle on the side to show current value (along with the fill).

**Comment by SolarGranulation** [comment]
Well, if nothing else, at least people are discussing what they'd like things to be. 

I have to say that I found "S" and "M" utterly baffling when I first saw them, and a rather unfortunate combination at that (S&M?) But I have no background with mixing equipment. 

I should perhaps, apart from applying outlining more thoroughly, also have mentioned that I thought the buttons should be separated; mute should, I think, be below the volume slider as it commonly is in other computer volume controls. 

I don't think the knob icon is actually used anywhere, but it was in the existing set so I didn't want to overlook it. 

While I've put a great deal of effort into aligning icons' various features -- the heights, angles, widths, ratios and spacing of primary and secondary elements -- the two that I've had most trouble with (cloud save and print) get very much in the way. Really, I challenge anyone to make an attractive printer icon, I've never seen one I didn't hate. 

Dialog icons were deliberately distinct precisely because they're not buttons; they are supposed to grab attention by standing out. In any case, something needs to be done about the existing question dialog icon, which looks like a chat icon!

Thanks for the feedback at technical tips. Ice found the process enjoyable, I only regret that the result is unsatisfactory.

**Comment by mkruselj** [comment]
I think you did pretty great with the toolbar icon set. My only really beef was the volume slider and S/M buttons (yes they're normal in audio-related software, and yes the S&M connotation is unfortunate, but such is life!) :)

**Comment by Obliquely** [comment]
Although the current solo and mute buttons are far from pretty, I'm not keen on the suggested replacements. I think as SIMPLE as possible is best here, perhaps even as minimal as the voice selection buttons in the note entry toolbar, i.e. the letter S or M with a coloured background. The skeuomorphic design in the Mixer seems out of keeping with the rest of MuseScore. If we just styled the QPushButton with the stylesheets it's also easier to manage differences between dark and light theme (which the mixer doesn't do all that well just now).

Just one reference point - the Logic UI has flat buttons for mute and solo. Simple and don't take up much space.
Screenshot 2019-05-21 at 00 24 28

**Comment by mkruselj** [comment]
Flat buttons is all I'm asking for really.

I wouldn't call the current design of S/M buttons skeuo, though. More like 90s website thing. :)

**Comment by L0uisc** [comment]
I would agree with most of what is said here. I really like the new file icons. I just have two suggestions:

1. I think the whole note on the "open" icon looks weird. I think it could be removed without breaking consistency. (The "save" icon could maybe also have a plain dot, as @IsaacWeiss said. Can you maybe post a screenshot of the save icon with a plain circle so we can discuss?)
2. The print icon's paper is much too high. Keep the sides and bottom of the paper as is, but move the top way down: 
printer (mock-up done in MS Paint)

About the Mixer, I agree with the comments here. On physical mixers, Solo and Mute is lamps with text next to it or on it.

**Comment by mkruselj** [comment]
Agreed with both previous points.

**Comment by Obliquely** [comment]
@SolarGranulation On the mixer styling, I'd suggest removing the icon changes you've made from this pull request and keeping the focus on the toolbar icons. (And, if you did, you could always create a separate pull request for mixer icon changes.) The toolbar icon styling and the mixer styling are pretty separate issues I think and are better treated as such. (That said, I definitely think the mixer UI could do with a makeover, but it need more than just icon change - it's just a separate issue)

**Comment by jeetee** [comment]
Specifically on the new/open/save icons.
I like the musical wink in the save icon where the inner floppy disk spinner is. I fail to see the use of it on the folder icon.
Also note that these are currently re-used in the Plugin Creator, where for the new icon, the note itself doesn't make sense. If we do keep that for the main window, then a non-note one should be added for use in the Plugin Creator context.

**Comment by anatoly-os** [comment]
Regarding the Solo, Mute buttons style, check out popular web apps (like soundtrap):
image

Regarding the file icons, I would go with the Google Material Design icons and draw the ones they don't have in accordance with the style.

**Comment by mkruselj** [comment]
This is not a web app. Ew.

**Comment by anatoly-os** [comment]
But the multi-platform user experiences is what we have nowadays. People may use both cloud services and the desktop application, users would expect the same concepts and even visual design (see Figma as an example which has absolutely the same design in web and as a desktop application).

**Comment by mkruselj** [comment]
I'd much rather see solo and mute buttons as they are shown in the great majority of audio programs. There's a reason why it's like that - familiarity.

**Comment by SolarGranulation** [comment]
Just popping in to say a couple of things:

1. I'm unavailable to contribute to the discussion for a few days or so due to personal reasons.
2. When I'm available, would people like me to produce a final revision of main toolbar icons for consideration?

**Comment by mkruselj** [comment]
2. would indeed be very cool!

**Comment by Jojo-Schmitz** [comment]
Rebase needed /meanwhile)

@Tantacrul what's your stand on this?

**Comment by Tantacrul** [comment]
I absolutely agree that they need to be changed. I think the solution for the 'solo' button needs to be quite different though. I'll work on this very soon and provide some more alternatives.

**Pull request closed without merging**
