### PR TITLE
Align text to other text or element

### PR DESCRIPTION
**Pull request by Gai-Luron**
align-text2
align-text3
align-text1

### CODE REVIEW

**Comment by anatoly-os** [comment]
@Gai-Luron @lasconic @Jojo-Schmitz @barafael please see my comment in almost the same PR for elements: https://github.com/musescore/MuseScore/pull/786#issuecomment-389507008.

**Comment by Jojo-Schmitz** [comment]
I (still) like it!

**Comment by anatoly-os** [comment]
@Gai-Luron see my comment in https://github.com/musescore/MuseScore/pull/786#issuecomment-389889553

**Comment by anatoly-os** [comment]
Finale uses such aligners, so it adds a vote to have this in MuseScore :)

**Pull request closed without merging**
