### PR TITLE
Fix 9696: place text and icon properly

### PR DESCRIPTION
**Pull request by duanjr**
Resolves: [#9696](https://github.com/musescore/MuseScore/issues/9696)

Though the detail data may be different, it does look as expected.
Besides, compare to code just several lines above the change I made, it's reasonable to believe that the original code is written by carelessness. (write 'top' as 'left')

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

before change:
D6HDFR38$XA37Q%`RX02T@X
after change:
5B X{QQTU$@27@D9W~2MFKX

### CODE REVIEW

**Comment by jessjwilliamson** [comment]
Hi @duanjr! Thank you so much for looking into this issue! Definitely looks much better than current build does. I think it's almost there, the one thing I have noticed is that the height of the button is supposed to be on 48 pixels on Figma and the build is showing 50 pixels. Are you able to fix the height of the button then it'll be easier to check about the improved placements of the icon and text? :) Thank you!

**Comment by duanjr** [comment]
@jessjwilliamson I was busy yesterday, sorry to respond late. I have made some adjustments, please check it out.

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson I was busy yesterday, sorry to respond late. I have made some adjustments, please check it out.

Thank you! I can see now I can compare with the Figma designs with the correct height of the button! Your icon placement is spot on, I think what needs adjusting now is the text is be moved up 1 pixel then I think that'll be perfect! Here is a screenshot I took of your button then compare to the Figma design on top of it. Hope that makes sense! But thank you so much for doing this :) 
image

**Comment by duanjr** [comment]
The checks failure looks strange to me, they all failed with the same message:
```
./build/ci/tools/setup_ccache.sh: line 41: ccache: command not found
./build/ci/tools/setup_ccache.sh: line 42: ccache: command not found
Error: Process completed with exit code 127.
```
I don't know if it's my problem.
Anyway I think now it meets @jessjwilliamson 's expect

**Comment by Jojo-Schmitz** [comment]
The real problem, and it isn't your's, is some glitch on reaching out to http://azure.archive.ubuntu.com/ubuntu for install ccache.
I guess restarting the build should fix this

**Comment by jessjwilliamson** [comment]
@duanjr That looks fantastic! Well done, thank you so much! @RomanPudashkin can you kindly merge this please? 👍

**Pull request closed without merging**
