### PR TITLE
[engraving] replaced QList to std. Part 1

### PR DESCRIPTION
**Pull request by igorkorsukov**

### CODE REVIEW

**Review by handrok — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Why would this PR change vtests?

**Comment by igorkorsukov** [comment]
> Why would this PR change vtests?

I am investigating this problem, different by 4-16 pixels... (

**Comment by igorkorsukov** [comment]
> Why would this PR change vtests?

there was a different sorting, now the same

**Comment by Jojo-Schmitz** [comment]
Good to have those tests ;-)

**Pull request merged**
