### PR TITLE
Musicxml fixes

### PR DESCRIPTION
**Pull request by lvinken**
Structural fix for #40476: metronomes in formatted texts are also recognized. Both the metronome and the formatted text around it are exported correctly.

### CODE REVIEW

**Comment by lvinken** [comment]
My normal test before making a pull request is running "mtest/musicxml/io/iotest". This is a simple script that runs MuseScore on all MusicXML test files. It runs OK for this pull request ("89 test(s), 0 failure(s)").

For the Travis failure, Travis only tells me: "Test #36: tst_mxml_io ......................***Failed   18.64 sec", which does not help at all.

Furthermore, I cannot reproduce this, as currently (even for a clean build of "master") mtest/musicxml/io/Debug/tst_mxml_io hangs for me (note: OS X) on a busy wait when initializing the MusicXML schema. This looks similar to an issue previously seen and fixed by ABL, but as of now, I have no solution.

**Comment by lasconic** [comment]
OK I will look into it.

**Comment by lasconic** [comment]
Apparently word2 test is failing on Linux with the following...
```
FAIL!  : TestMxmlIO::words2() 'saveCompareMusicXmlScore(score, QString(file) + ".xml", DIR + file + ".xml")' returned FALSE. ()
   Loc: [/home/vagrant/MuseScore/mtest/musicxml/io/tst_mxml_io.cpp(223)]
```

Problem is around line 146, the reference file looks like
capture d ecran 2015-01-01 14 11 02

while the generated file is 
capture d ecran 2015-01-01 14 10 36

**Comment by lvinken** [comment]
Thanks, looks like different end of line handling between Linux and OS X. Could be caused by libmscore/text.cpp line 2740. i'll look into it and see if I can explain and fix it.

**Comment by lvinken** [comment]
Will create a new pull request after merging, if that passes Travis, I'll close this one.

**Comment by lvinken** [comment]
Replaced by PR #1602

**Pull request closed without merging**
