### PR TITLE
Adapt code style for Uncrustify 0.74.0

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Uncrustify 0.74.0 is out, and it has somewhat changed behaviour, so this PR adapts our code to the new behaviour. 

As with 0.73.0, not all changes are desired. For five of the 10 changed files it becomes worse than what it was, for two other files the changes are questionable. Anyway, we have little choice... 

Like with 0.73.0, it will probably take some time before the new version also gets used on GitHub CI. Therefore, I'm just creating this PR now, so that we can merge it right at the moment when it's needed.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I guess #9952 makes this PR here obsolete?

**Comment by RobFog** [comment]
Why? 0.73 is currently used. This pull request is for 0.74.

**Comment by Jojo-Schmitz** [comment]
Because I think this PR is based on the assumption that GitHub CI for macOS may switch to 0.74. We've now avoided getting caught by that by switching to Linx and use out own copy of Uncrustify

**Comment by cbjeukendrup** [comment]
Indeed, this is not necessary anymore now...

**Comment by igorkorsukov** [comment]
I think we will come back to this PR in the future.
At the moment, we decided that it is better to freeze the Uncrustify version, and we will update when we want, we are ready to do it, and not at the most unexpected moment :)

**Comment by Jojo-Schmitz** [comment]
In that canse it might be feasible to keep this PR open (and in a Draft state)?

**Pull request closed without merging**
