### PR TITLE
No parts for invisible instruments

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
see https://musescore.org/en/node/59316

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
2 votes (@MarcSabatella on IRC and Rudi cj7tb in the issue tracker) so far to not include that 2nd commit (that would hide invisible instruments in the "Create Parts" dialog). Add mine and it is 3 votes...

**Comment by lasconic** [comment]
+1

**Comment by lasconic** [comment]
And regaring the first commit, one could argue that it's easier to delete parts once created than create invisible parts manually if they are not needed

**Comment by Jojo-Schmitz** [comment]
This also happens when using the new --export-score-parts

**Comment by lasconic** [comment]
ok. I will go for the first commit.

**Comment by lasconic** [comment]
e072990 has the first commit.

**Pull request closed without merging**
