### PR TITLE
[MU3 Backend] ENG-42 & ENG-14: MusicXML Barlines fixes

### PR DESCRIPTION
**Pull request by iveshenry18**
Resolves: [ENG-42](https://mu--se.atlassian.net/jira/software/projects/ENG/boards/21?selectedIssue=ENG-42): Final barlines must be joined over grand staff, and [ENG-14](https://mu--se.atlassian.net/jira/software/projects/ENG/boards/21?selectedIssue=ENG-14): Double barlines faulty on grand staff

Fixes issues with final barlines and other barlines in grand staves. The former is fixed with a port from 3080d21.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

**Review by vpereverzev — APPROVED** [review]

**Comment by wizofaus** [comment]
Where is testSystemBrackets3_ref.mscx loaded and verified?
I can't find "SystemBrackets3" anywhere in the source code at all.

**Comment by iveshenry18** [comment]
> Where is testSystemBrackets3_ref.mscx loaded and verified?
> I can't find "SystemBrackets3" anywhere in the source code at all.
> 
> UPDATE: it isn't in the master/MU4 branch, only MU3.6

That's correct; these changes are only on this specific branch (3.6.2_backend) for now.

**Comment by wizofaus** [comment]
Is there any reason not to merge everything on 3.6.2_backend to master then? I've updated my PR with some of these changes but not all.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iveshenry18** [comment]
So far this branch does include at least one [commit](https://github.com/musescore/MuseScore/commit/3bb7eb999a2446462e0524a88ffc70814719f35c) containing code exclusive to this task that does not go in master, but other than that, porting all these to master is indeed the eventual plan as far as I know. You are welcome to do that with any commit you see fit, provided you double-check for any regressions.

**Comment by wizofaus** [comment]
Does "Fetch Upstream" not work for branches other than 'master'? I just did it on my fork but my 3.6.2_backend branch didn't get updated, I had to explicitly merge from the original musescore remote to get the latest changes.

**Comment by Jojo-Schmitz** [comment]
`git fetch upstream` (actually `git fetch musescore` as that's the name for my upstream repo) does work for me

**Pull request merged**
