### PR TITLE
fix #301786: Add Barbershop template for women

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
and shortened the men's version (too) by 6 measures for them to fit one page (like the other templates), for their thumbnails to include the final barline

Resolves https://musescore.org/en/node/301786, discussed in https://musescore.org/en/node/301783

Our contribution to Internaltional Women's Day on March 8th ;-)

### CODE REVIEW

**Comment by Howard-C** [comment]
Why not change the men template's title to include "(Men)"?

**Comment by Jojo-Schmitz** [comment]
Because of normal case and exception?
Also Score title or score filename? Or both? If filename, the question is whether an update removes the old templates or leaves them in plance and that way creates duplicates? It that is not the case I'd renamed them in therie initialy part, the numbers, so the 2 Barbershop templates are next to one another.

**Comment by RobFog** [comment]
> Because of normal case and exception?

I've scanned the Wikipedia article on "Barbershop music". It's not clearly a "men's thing":
- "While the modern era of barbershop music is accepted to have begun with a 1940s revival, opinions as to the genre's origins vary with respect to race, gender, region and context." ( https://en.wikipedia.org/wiki/Barbershop_music#Historical_origins )
- "Traditionally, the word "barbershop" has been used to encompass both men's and women's singing in the barbershop style – in quartets and choruses." ( https://en.wikipedia.org/wiki/Barbershop_music#Female_barbershop_music )

At the very least, the situation doesn't seem clear cut enough to warrant making the template for males the rule and the one for females the exception.

**Comment by Jojo-Schmitz** [comment]
Still unsure though how an update handles changed filenames

**Comment by Jojo-Schmitz** [comment]
And hope that having the Barbershop_Quartet_(Men) template before the Barbershop_Quartet_(Women) is gender neutral enough ;-)

**Comment by Jojo-Schmitz** [comment]
Sorry, needs #5790 too

**Pull request merged**
