### PR TITLE
Fix sorting elements for drawing and selecting

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #10917 

- if you select overlapping elements in different voices, the element with the greatest voice will be drawn on top;
- if you click at a place with multiple elements, generally, the same element would be selected that would be drawn on top if you would select all those elements. 

This is slightly different from MU3, but I think it feels more consistent.

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
The vtest differences are not really differences...

**Comment by Jojo-Schmitz** [comment]
Why do the vtests claim to be different? Just curious

**Comment by cbjeukendrup** [comment]
I wouldn't know a logical explanation, but maybe it has to do with antialiasing, that some pixels become by chance a tiny bit lighter?

**Comment by boryskuzmenko** [comment]
https://github.com/musescore/MuseScore/issues/10917 bug is **FIXED**
Tested on macOS, Win11, Linux

Please, merge to Master

**Pull request merged**
