### PR TITLE
Fix #70571 Ottava GPX import crash

### PR DESCRIPTION
**Pull request by eplanet**
This is a PR related to https://musescore.org/en/node/70571.
I'm currently not sure that the fix a perfect, but it definitely avoid the crash that can be easily reproduced with the provided input GPX.
As you can see the ottava would never end in the current import routine, since it is never set to 0 when it states it is closing the ottava.
I added the corresponding unit test with a provided gpx. Hopefully there no metadata from the original author.
Thanks for your help making sure this fix is OK.

### CODE REVIEW

**Comment by lasconic** [comment]
Unfortunately the patch doesn't solve the issue for me. The sample file from https://musescore.org/node/70571#comment-328121 can indeed be opened correctly but there is still a crash with the original file from https://musescore.org/sites/musescore.org/files/issues/Coldplay%20-%20Clocks_0.gpx

**Comment by lasconic** [comment]
Also the test file is not really nice. It contains a single quarter note on the bottom measure.

**Comment by eplanet** [comment]
I'm surprised that it doesn't avoid the crash, it definitely works for me. Anyway my understanding of the gtp import implementation might not be good enough to ensure the fix is consistent, especially in terms of the original programmer design principle in the ottava management routine.

I'll continue to work on it, it will take some time...

**Comment by Jojo-Schmitz** [comment]
all these merges shouldn't have happened, and they apparently cause the Travis CI failures too

**Comment by eplanet** [comment]
Actually I suspect github updated the pull request according to the branch in my MuseScore fork... I wonder why they made updates instantly propagating any change into pull requests. It doesn't make sense to me.

Sorry for the disturbance :-S. I'll fix that ASAP

**Comment by Jojo-Schmitz** [comment]
Just don't `git merge` but `git rebase` instead.

**Comment by eplanet** [comment]
I'll try to get back to it with a fresh start.

**Pull request closed without merging**
