### PR TITLE
fix #89636 fix #94911 fix #70226 fix #91351: unlink the right staves when deleting a part, or deleting a linked staff. Do not store several times the same staves in linkedStaves

### PR DESCRIPTION
**Pull request by lasconic**

### CODE REVIEW

**Comment by MarcSabatella** [comment]
I haven't tried this yet - anything in particular that needs testing about this?  Seems almost anything is better than current behavior, so even if some issues remain, it's probably a win.  But I do wonder, I had at one point identified one of the problems being that the individual elements themselves still contain links to their counterparts on the deleted staves.  See https://musescore.org/en/node/89636#comment-395351.  Does this have the effect of removing those extra links, or make them less harmful, or are there still going to be issues?

**Comment by lasconic** [comment]
For the case of deleting a linked staff in the score with linked staves in the part, I believe we now unlink all elements, chords too.
For the case of deleting an excerpt, I'm afraid we don't... it probably needs another look. Maybe we should actually remove the staves from the excerpt partScore.

**Comment by lasconic** [comment]
We do use the link between elements in several places... for example when adding a clef before a chord and funny things can happen if one deletes a part, add clef, undo, or add another part etc... since the list still contains linked elements in non existing parts...

**Comment by lasconic** [comment]
I pushed some changes. Now I unlink all elements, spanner, annotation and finally the staff when deleting excerpt.

**Comment by lasconic** [comment]
As @MarcSabatella said, it seems to be better in most of the cases... So I will merge this in master for now. Feel free to hammer it and file bugs.

**Comment by lasconic** [comment]
Maybe this bug by marc is a side effect of this change https://musescore.org/en/node/99796

**Pull request merged**
