### PR TITLE
fix #288843

### PR DESCRIPTION
**Pull request by pkjq11**
fix : https://musescore.org/en/node/288843

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
You'd need to sign the [CLA](https://musescore.org/cla)

**Comment by pkjq11** [comment]
> You'd need to sign the [CLA](https://musescore.org/cla)

Yes sir,I just signed the CLA under the name JinQiang.

**Comment by Jojo-Schmitz** [comment]
Thanks and welcome ;-)
BTW: it'd be better (for you) not to use your master branch to submit PRs from

**Comment by pkjq11** [comment]
> Thanks and welcome ;-)
> BTW: it'd be better (for you) not to use your master branch to submit PRs from

Thank you. I'll avoid that later

**Comment by Jojo-Schmitz** [comment]
rebase needed

**Comment by dmitrio95** [comment]
The original issue doesn't happen anymore, see [this comment](https://musescore.org/en/node/288843#comment-984283).

**Pull request closed without merging**
