### PR TITLE
fix #8360: Transpose by Key doesn't transpose by perfect octaves (whe…

### LINKED ISSUE #8360: [MU4 Issue] Metronome not working
**Describe the bug**
Regression: When metronome is turned on no 'click' track can be heard during playback as per MU3.

**To Reproduce**
1. Open/create a score
2. Ensure Metronome is active in the playback toolbar
3. Play
4. No click track can be heard

**Expected behavior**
Click track should play as per MU3

**Screenshots**

**Desktop (please complete the following information):**
Windows 10, built with MSVC 2019

**Additional context**

### PR DESCRIPTION
**Pull request by Fyrult**
…n transposing up or down)

When transposing by key in the same key, going up or down will transpose an octave. Also, transposing by key in the same key and going to the closest shouldn't do anything (optimize).

### CODE REVIEW

**Comment by lasconic** [comment]
@MarcSabatella any opinion on this "feature"?

**Comment by MarcSabatella** [comment]
Not really.  Seems totally unnecessary - if you want to transpose by an octave, just use Ctrl+Up/Down, why bother with a dialog.  on the other hand, also seems totally harmless.

**Comment by lasconic** [comment]
It's harmless indeed and we have a PR and a bug report.. Let's go for it.

**Comment by lasconic** [comment]
Merged, @Fyrult Thank you for the PR and welcome to the MuseScore contributor community!

**Pull request merged**
