### PR TITLE
fix for arm, where char by default is unsigned

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
See https://musescore.org/en/node/73701

### CODE REVIEW

**Comment by lasconic** [comment]
is that tested?

**Comment by Jojo-Schmitz** [comment]
Not on arm, not by me, it is just obviously correct ;-)
I'm quite puzzled that other platforms like Mac or Linux don't complain about this?

**Comment by ericfont** [comment]
I will try to test in the next week or so...will likely be more bugs when try to compile for arch linux arm.  But I do have at least one of each armv5, armv6, armv7 to test on.

**Comment by ericfont** [comment]
My suspicion is the official archlinuxarm build failed 20% the way through, so there will likely be some more compiler errors during the rest.  Probably will be even more of the signed issues.

**Comment by lasconic** [comment]
As far as I know, it runs on debian arm. See at the bottom here https://packages.debian.org/sid/musescore

**Comment by ericfont** [comment]
it is possible that because arch linux always uses the latest stuff version, that the newer compiler complains, while older ones used by debian don't complain.  Or it could be a build script issue.

**Pull request merged**
