### PR TITLE
fix #316645: broken swapping notes/chords with Shift + Left/Right

### PR DESCRIPTION
**Pull request by Howard-C**
Resolves: https://musescore.org/node/316645.

Needs no explanation.

### CODE REVIEW

**Comment by igorkorsukov** [comment]
@Howard-C Could you please port the changes to the master

**Comment by Howard-C** [comment]
Sure

**Comment by Howard-C** [comment]
Wait, I think I already did this... https://github.com/musescore/MuseScore/commit/476c7dd8c51a5052c11743fc251312183c90d20d

**Comment by igorkorsukov** [comment]
ok, thank you :)

**Pull request merged**
