### PR TITLE
Fix #15236: Restored warm pad preset to prior preset to fix incorrect sound

### LINKED ISSUE #15236: [MU4 Issue] MSBasic "Warm Synthesizer" is erroneously mapped to "String" sound
**Describe the bug**

MS4 MS-Basic "Warm Synthesizer" instrument is erroneously mapped to "String" 

**To Reproduce**

Open a new score, select Electronics->Warm Synthesizer and play.

**Platform information**

Win10/64, MuseScore 4.0 (MuseHub not instsalled)

**Additional context**

See (and hear) attached .zip for .mscz and two MP3 audio files for comparing MS3 vs MS4.

[MS4-WarmSynth-MS3vsMs4.zip](https://github.com/musescore/MuseScore/files/10248460/MS4-WarmSynth-MS3vsMs4.zip)

### PR DESCRIPTION
**Pull request by Declan-Griner**
Resolves: #15236 

Restored both Warm pad presets to what they were in MuseScore_General. This included restoring the .ogg samples and adding a "warm pad" instrument to replace the "Strings Layer" instrument in the preset. This should fix the incorrect sound in the warm pad and bring back the sound used in MuseScore 3.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [NA] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [NA] The code compiles and runs on my machine, preferably after each commit individually
- [NA] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by zacjansheski** [comment]
It sounds like the warm synth is still closer in sound to MS4 than to MS3


https://github.com/musescore/MuseScore/assets/69917893/ddbf52e8-0238-40cc-a19e-e7b880cb413d

**Comment by Declan-Griner** [comment]
Hmmm, interesting. I got the soundfotnt I copied everything from  everything from from [the musescore website](https://musescore.org/en/handbook/3/soundfonts-and-sfz-files#soundfonts). I double checked to make sure everything is identical between the two and nothing weird happened between copying. I could grab the sound used by Fluid_R3Mono instead.

**Comment by cbjeukendrup** [comment]
Alternatively, you could install MuseScore 3, and take the SoundFont file from the program files folder (probably C:\Program Files\MuseScore 3\sound\...)

**Comment by Declan-Griner** [comment]
MuseScore_General.sf3 from MuseScore 3.6.2 vs. the altered MS Basic.sf3 vs. Fluid just for comparison. I'm not sure what's causing the discrepancy in sounds between myself and others here.

https://github.com/musescore/MuseScore/assets/143758845/6cc8f29c-0411-43cd-a2ac-77fd435520d1

**Comment by zacjansheski** [comment]
I don't get any sound from your video.

I think there must be something additional under the hood causing the different sound in MS4.

**Comment by Declan-Griner** [comment]
Possible. This example was recorded using 3.6.2 on Linux. I know it was determined to be a soundfont problem in the issue but there could be something else going on here.  Sound should work now in the video

**Comment by Declan-Griner** [comment]
This does appear to also be an issue with musescore's playback as well. Opened issue #19494 regarding it. This should fix the issue with the soundfont itself, though the problem in playback problem with MuseScore 4 means that this won't bring back the MuseScore 3 sound

**Comment by zacjansheski** [comment]
I will be closing this.
You didn't do anything wrong, but as a policy, we don't merge community PRs with binary files.  We might make these updates MS Basic at a later point internally.  However, currently there is no noticeable difference for the end user with regard to https://github.com/musescore/MuseScore/issues/15236

Thank you for looking into this!

**Comment by brobrobrob** [comment]
@zacjansheski 
@cbjeukendrup 
As this is not available as a community project due to requiring changes with binary files, can it be removed from the 'community projects' board?

**Comment by cbjeukendrup** [comment]
What do you mean? https://github.com/musescore/MuseScore/issues/15236 has been removed from the community projects board in April.

**Comment by brobrobrob** [comment]
> What do you mean? #15236 has been removed from the community projects board in April.

[#19494](https://github.com/musescore/MuseScore/issues/19494)

Sorry, think I meant the related #19494

**Comment by cbjeukendrup** [comment]
It looks like the problem there is not the sound font itself, but the "interpreter" (FluidSynth) or how we configure it, so that'd just require a fix in the code.

**Comment by mrbumpy409** [comment]
The problem is that the lowpass filter in MuseScore's FluidSynth build is no longer working, which messes with the intended sound of many of MS_Basic's presets, for example where acoustic instruments are supposed to become more mellow at low velocities. Now, everything that is supposed to use the lowpass filter to sound mellow or dark (such as "Warm Pad"), now always plays the samples at full brightness.

**Pull request closed without merging**
