### PR TITLE
Fix #275259 score v.1.14 with Pedal do not open in 3.0

### PR DESCRIPTION
**Pull request by handrok**
add ability to read pedal from score v.1.14

### CODE REVIEW

**Comment by lasconic** [comment]
It's probably worth to add a test case no ?

**Comment by handrok** [comment]
see https://musescore.org/en/node/275259. Uploaded score (v1.14) do not open in master 3.0. "Bad format" message appear. This message appear not all cases. 3.0 can not read pedal with specific tag <continueText>. Note that volta have implementation to read score old version. So I implemented similar logic for pedal.

**Comment by lasconic** [comment]
I meant a test case in `mtest/libmscore/compat114`

**Comment by RobFog** [comment]
This first commit message should include "Fix #275259" so that the issue gets closed automatically. The second commit message has a typo.

**Comment by RobFog** [comment]
I think the first commit's message still needs a "Fix #275259". ;-)

**Comment by handrok** [comment]
@RobFog thanks

**Comment by handrok** [comment]
folow up https://github.com/musescore/MuseScore/pull/3843 https://github.com/musescore/MuseScore/pull/3863
Add test case for ottava and textline (see link)

**Pull request merged**
