### PR TITLE
Fix #19113  Added "Swap" to "Copy, Cut, Paste" commands

### PR DESCRIPTION
**Pull request by tekCowboy**
Addresses issue 19113-Swap-Notes.  The user can cut (or copy) a range,
(usually a group of measures, say a melody line for one instrument)
then select the starting measure in another instrument, and "swap"
(i.e. melody line for harmony part).  The original line is pasted from
the clipboard, then the clipboard is "Swapped" for the (harmony) parts
that were overwritten.  Return the the original part, and "Paste" the (harmony)

(Request new standard shortcut for "Swap" be CTRL-SHIFT-X)

### CODE REVIEW

**Comment by tekCowboy** [comment]
aka - Jon Enquist

**Comment by ZackTheCardshark** [comment]
Could you rename the commit to include "Fix #19113"? That way, when merged, it will automatically update the feature request in the issue tracker.

**Comment by Jojo-Schmitz** [comment]
changing the PR title is OK, just not sufficient, you need to change the commit message for that automatic issue update to happen. `git commit --amend`, change and save, `git push -f`

**Comment by Jojo-Schmitz** [comment]
Please squash them into just one commit

**Comment by tekCowboy** [comment]
Ok, I'm an absolute newbie to git, but after a couple of mistakes, I think
I've got it.  All my changes are under:
commit 80bb8c0aa0bbb75777b0a662af897504d4096f05
Should I make a new pull request, since the original commit # has changed?
I'm guessing no.

**Comment by Jojo-Schmitz** [comment]
You guessed right, no need for a new PR.

**Comment by tekCowboy** [comment]
As a first time contributor, I am still hoping for some feedback.
I understand that recent changes have been pretty major, so I am looking for more items to work on, but it has been a month :(

**Comment by ZackTheCardshark** [comment]
For what it's worth, I don't know why this hasn't been merged. Probably it just slipped off the devs' radar. Just today somebody requested the same exact thing (without being aware of #19113): https://musescore.org/en/node/111201

**Comment by lasconic** [comment]
@tekCowboy Sorry for the delay. I will review your PR tomorrow.

**Comment by lasconic** [comment]
The icon is not used currently. I think you forgot to add it in musescore.qrc.

**Comment by lasconic** [comment]
Except the remark above, it looks good.

**Comment by ZackTheCardshark** [comment]
@tekCowboy, do you want to make that extra change @lasconic suggested?

**Comment by Jojo-Schmitz** [comment]
@tekCowboy : you need to rebase, I use `git pull --rebase upstream master`for this. Then you need to squash all the commits into one, see http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by lasconic** [comment]
See #2620 for a rebase and clean version.

**Comment by lasconic** [comment]
I did 
```
git checkout -b fix-19113
git cherry-pick 8153185
git cherry-pick f4474a4
# fixed the conflicts
git rebase -i HEAD~2
```
I might have missed on commit. Let's see.

**Pull request closed without merging**
