### PR TITLE
Fix (vertical) positioning of Measure Repeat Signs

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #9877

Schermafbeelding 2021-11-25 om 22 15 25

### CODE REVIEW

**Review by oktophonie — DISMISSED** [review]

**Comment by cbjeukendrup** [comment]
@oktophonie It turns out that this fix works perfectly with Leland, but in other fonts, the repeat sign seems to have a "built-in" offset, which seems to make no sense. Therefore, it now looks misplaced with fonts other than Leland. 

That offset _seems_ to be equal to half of the staff line width specified by the "style defaults" accompanying the font.

Before my fix, the position was adjusted by half of the _current_ staff line width of the score, so therefore, it was theoretically incorrect too when the user had modified the staff line width. 

So what we could do, is check whether the current ScoreFont is Leland, and otherwise query the default staff line width from the score font and adjust the symbol position accordingly. That will feel like a hack, but it'll be okay as long as we support a fixed set of six score fonts, but I wonder what will happen when I make it possible to use custom fonts (because we can't guess whether the offsetting is needed for those fonts). 

Anyway, maybe the biggest benefit of my fix, is that it now takes into account the number of staff lines (and the staff lines distance).

**Comment by oktophonie** [comment]
Good point. Looking at the Bravura symbols they extend vertically from -250 to +265 (not -250 to +250, which would be from the second bottom line to the top bottom line exactly). That would explain the previous slightly-off scaling, etc.

I'm not sure what the reasoning for that is and the SMuFL spec doesn't enlighten me.

Is the simple solution not to vertically centre the bounding box (rather than the y=0) of these symbols on the middle of the staff line you want to position it on? Leland would then look just as it does now, and Bravura would similarly appear vertically centered.

**Comment by cbjeukendrup** [comment]
> Is the simple solution not to vertically centre the bounding box (rather than the y=0) of these symbols on the middle of the staff line you want to position it on? Leland would then look just as it does now, and Bravura would similarly appear vertically centered.

Yes, that worked! Now it should look good with most fonts; only maybe with some asymmetric Jazz fonts it's not entirely how the font designer wants it. But that will be a minority.

I also realised that the positioning for the number above the repeat symbols was not positioned correctly on non-default staves. I fixed that, but this means that the interpretation for the value of the position has changed. So users who have changed that setting manually, will have to adjust it to fit the new behaviour when they open their scores in MuseScore 4. Or we could write compatibility code that does this automatically.

**Comment by Jojo-Schmitz** [comment]
I'd think that these multimeasure repeats are used exceptionally frequently especially on Jazz leadsheets, wouldn't they?

**Comment by RobFog** [comment]
And drum scores… :)

**Comment by Jojo-Schmitz** [comment]
Which always (?) had an odd number of staff lines (1, 3 or 5), so shouldn't be an issue here

**Comment by RobFog** [comment]
I write with five staff lines but I couldn't say if there are exceptions to the rule you mention.

**Comment by cbjeukendrup** [comment]
Maybe in some cases where you have two woodblocks, or two cymbals, you might notate that on two lines. 

Anyway, the number of staff lines was not really an issue anymore; the problem was the centering of the symbol around the desired staff line. But that is solved now.

About Jazz fonts, yes, doubtlessly those bar repeats are not uncommon in Jazz scores, but for MuseJazz and Petaluma is looks very reasonable now, so there will probably be only few fonts with which it does not look good (which can't be used in MuseScore yet anyway).

**Review by oktophonie — APPROVED** [review]

**Comment by chenlung** [comment]
> Which always (?) have an odd number of staff lines (1, 3 or 5), so shouldn't be an issue here?

Also two lines.

**Comment by cbjeukendrup** [comment]
Rebased.

**Review by vpereverzev — APPROVED** [review]

**Pull request merged**
