### PR TITLE
update to SMuFL and Bravura 1.18

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by lasconic** [comment]
Except if I'm wrong, this is only an update to Bravura 1.18 (which as easy as putting the files at the right place...) but not an update to SMuFL 1.18 which is a bit more complicated since some (quite rare) symbols changed names...

**Comment by Jojo-Schmitz** [comment]
True, the SMuFL change is basically only that PDF.
Would those changed and added symbols need to get changed/added elsewhere?
Like in libmscore/sym.{cpp,h}?

**Comment by Jojo-Schmitz** [comment]
True, the SMuFL change is basically only that PDF.
Would those changed and added symbols need to get changed/added elsewhere?
Like in libmscore/sym.{cpp,h}?

**Comment by Jojo-Schmitz** [comment]
3 have changed name (lost a stray space, easy fix), 4 have been removed (should be fairly easy to fix), some have changed their description (do we care? Not difficult to fix, so why not), and quite a few got added. So I guess the question is whether we want to add those.

**Comment by Jojo-Schmitz** [comment]
Added all new symbols now.

**Comment by Jojo-Schmitz** [comment]
Something is severely wrong, MuseScore crashes with "index out of range" when trying to open the Master Palette ?!? And it somewhere in the 1st commit...

**Comment by Jojo-Schmitz** [comment]
found it, a missing and a misplaced comma :-(

**Comment by Jojo-Schmitz** [comment]
somehow I'm still missing the 8 MuseScore local symbols (ornament*), near the end of that enum and those arrays, they don't show in the master palette, but do in 2.0.1. Also missing the following 4 additional symbols (noteLonga*), but these at least are not shown in 2.0.1 either.

**Comment by lasconic** [comment]
Perfect. 
Could you file bugs for the missing glyphs in Emmentaler, missing glyphs in master palette etc...? Thanks!

**Comment by Jojo-Schmitz** [comment]
Done:
* [unicodeNote* glyphs missing in Emmentaler and show as empty rectangles in master symbol palette](https://musescore.org/en/node/62141) 
* [MuseScore local symbols (ornament*) missing in master symbols palette](https://musescore.org/en/node/62146)

And earlier I filed [Gonville shows nothing in the master symbols palette](https://musescore.org/en/node/61931)

**Pull request merged**
