### PR TITLE
fix #38941: multiple texts on mmrests

### PR DESCRIPTION
**Pull request by MarcSabatella**
Reproduces and updates a fix that was applied to 2.1 but never to master - see https://musescore.org/en/node/38941

### CODE REVIEW

**Comment by anatoly-os** [comment]
I can still reproduce the issue described in https://musescore.org/en/node/38941#comment-576541

**Comment by MarcSabatella** [comment]
Even with this fix applied, you mean?  I will take another look.

**Comment by MarcSabatella** [comment]
I don't see the bug with my change here applied.  It's there in 3.0.5 and on master, but for me, this change fixes it.

**Comment by anatoly-os** [comment]
I checked out the PR and built... Ok, I will double check again tomorrow.

**Comment by MarcSabatella** [comment]
@anatoly-os were you perhaps using system text, not staff text?  If so, then maybe you were seeing a separate problem, https://musescore.org/en/node/288013.  Anyhow, since it's going to be the same code involved, I plan to update this PR soon to include a fix for that.

**Comment by MarcSabatella** [comment]
The system text issue turned out to be a duplicate of this one - there was a second system text containing just " " that prevented the other from displaying.

I've updated this PR with no real changes except for formatting, adding comments, and possibly preventing a crash that if would have happened would have happened without the change.  This PR definitely solves the problem described in the issue report.

**Comment by MarcSabatella** [comment]
Another thing maybe that was causing confusion - the issue is about adding multiple text elements *to the same measure*.  It has to be the first measure of the rest, text attached anywhere else does not display, by design (where would we place it?)

**Comment by MarcSabatella** [comment]
@anatoly-os if you still are seeing a problem, could you post the steps, and/or make a video?

**Comment by MarcSabatella** [comment]
As per the discussion https://github.com/musescore/MuseScore/pull/4952, this PR also fixes a crash if you try to add multiple texts directly to an mmrest.

**Pull request merged**
