### PR TITLE
268578 musicxml import export rest colors part2 export

### PR DESCRIPTION
**Pull request by vliegnaarbeer**
This should cover the export side of:
https://musescore.org/en/node/268578 MusicXML Import/Export rest colors

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
This PR actually covevrs both sides, as it has 2 commitzs, one for import and one for export, and as such renders #3415 superfluous?

**Comment by vliegnaarbeer** [comment]
Indeed. This contains both. Sorry about the confusion.

**Comment by lasconic** [comment]
Thank you for looking into this !

It would be good to have an automated test indeed. You can find them in https://github.com/musescore/MuseScore/tree/master/mtest/musicxml/io
The action happens here https://github.com/musescore/MuseScore/blob/master/mtest/musicxml/io/tst_mxml_io.cpp
Most of the tests import and export a MusicXML file and compare the input and the output to make sure they are the same. Could you add your test file to the test suite?

In order to merge your PR, I will need you to sign the MuseScore CLA at https://musescore.org/en/cla or if you already did to give me your MuseScore.org username. Thanks!

**Comment by Jojo-Schmitz** [comment]
And to get past that AppVeyor build fail a rebase seems needed (to get d2f6668)

**Comment by vliegnaarbeer** [comment]
Thanks for your input. My follow up:
- Signed the CLA (user joejoe_).
- Added a test.
- Rebased.

**Comment by lasconic** [comment]
Looks good. @lvinken any remark?

**Comment by lvinken** [comment]
Looks good to me.

**Comment by lasconic** [comment]
Thank you @vliegnaarbeer and welcome in the MuseScore contributors community! 
I see on MuseScore.org that you are a long time user, happy to see you contributing now. Looking forward for your next PR!

**Comment by vliegnaarbeer** [comment]
Thanks Iasconic.

**Pull request merged**
