### PR TITLE
Fix #275479: Master palette doesn't close on ESC

### PR DESCRIPTION
**Pull request by jthistle**
References: https://musescore.org/en/node/275479

### CODE REVIEW

**Comment by lasconic** [comment]
The other dialogs do not implement keyPress so it's probably not necessary to do it here.

**Comment by jthistle** [comment]
Master Palette is not a dialog. It's a widget with the Qt::Dialog flag, which means it's styled like a dialog. It also means it doesn't have the default escape = close keypress event that all dialogs have, since it inherits the keypress events of a QWidget.

**Comment by jthistle** [comment]
From mixer.cpp, in `keyPressEvent`:

    if (ev->key() == Qt::Key_Escape && ev->modifiers() == Qt::NoModifier) 
          close();
          return;
    }
    QWidget::keyPressEvent(ev);

I'll change the keyPressEvent code in masterpalette.cpp to match this for consistency.

**Comment by IsaacWeiss** [comment]
While we're looking at this: I've gotten used to having to press Esc, but I still wish that Ctrl+W would close these widgets when they are open instead of the score beneath.

**Comment by anatoly-os** [comment]
@IsaacWeiss let's discuss your suggestion in the related issue. Do we have one?

**Comment by anatoly-os** [comment]
@jthistle looks like this PR leads to https://musescore.org/en/node/275694. Could you please have a look?

**Comment by jthistle** [comment]
I'd be surprised if it did lead to that issue, but I'll take a look anyway.

**Comment by jthistle** [comment]
I have no idea how changing masterpalette.cpp would break the start center, but I'll see if I can get ESC working. I'd blame @handrok (if anyone, sorry ;)), because their changes were added August 4th, and you were testing with the August 2nd nightly.

**Comment by anatoly-os** [comment]
Maybe :)
I will test thoroughly, could be a coincidence, indeed. Sorry for distruction.

**Comment by jthistle** [comment]
No problem, I'm working on a fix for it :)

**Comment by jthistle** [comment]
Fixed it, made a pr: #3904

**Pull request merged**
