### PR TITLE
fix #195891 reduce save online window height

### PR DESCRIPTION
**Pull request by jeetee**
only verified in the designer view of QtCreator, but should be fine given the minimal change

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
You can test it using the -e option

**Comment by jeetee** [comment]
[WIP] while the initial size of the window is fine, it snaps to a bigger minimal size once you attempt to resize it.

**Comment by lasconic** [comment]
Looking into it, did you find anything else?

**Comment by jeetee** [comment]
Not too much; slightly annoyed and baffled by it.
Most occurrences of that error I can find are mostly related to either not setting the geometry on a window object, but a widget; or setting a geometry that is smaller than the window managers minimal size (for example to ensure visibility of title bar/buttons). Neither should be the case here.

This QTBUG seems slightly related (at least the same error response, but triggered by changing OS scaling of text) from January: https://bugreports.qt.io/browse/QTBUG-58027

And then there is this forumpost from May which seems to be the exact same issue, but has zero responses so far: http://www.qtcentre.org/threads/68266-window-size-out-of-control-error-is-setGeometryDp-Unable-to-set-geometry

**Comment by lasconic** [comment]
Here is my take on it https://github.com/musescore/MuseScore/pull/3260
Trying it on mac

**Pull request closed without merging**
