### PR TITLE
Fix #11334: Added Link to Privacy Policy

### LINKED ISSUE #11334: Create link to Privacy Policy in the 'About' panel
**Task description**
I have updated this on Figma. We just need a link that takes us to our Privacy Policy.

For now, until the PP is ready, I suggest linking to the MuseScore.org homepage.

image

For anyone interested, we're nearly finished the privacy policy text. I'll be publishing a draft for consultation shortly. It's pretty standard stuff but want to make sure the wording is clear.

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #11334 

*(short description of the changes and the motivation to make the changes)*

This PR adds a link to Privacy Policy in the About Panel

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by HemantAntony** [comment]
@Tantacrul This is programmed so it opens the same link as what you get when you click `musescore.org` in the about panel.

On a side note it doesn't work for me: https://musescore.org/en-IN

**Comment by Tantacrul** [comment]
> On a side note it doesn't work for me: https://musescore.org/en-IN

It doesn't. This is possibly something for @shoogle to look at.

**Comment by shoogle** [comment]
> On a side note it doesn't work for me: https://musescore.org/en-IN

The website is translated into many languages but not usually into regional variants of those languages.

For example, we have:
- https://musescore.org/en (English)
- https://musescore.org/fr (French)
- https://musescore.org/de (German)

But we don't have:
- https://musescore.org/en-GB (British English)
- https://musescore.org/en-US (American English)
- etc.

However, the desktop app does have regional variants.

image

### Web links in the desktop app

When linking to the website from within the app, you should **never include a country code**. You might think, *"Aha, here the user has selected en-GB in the app, so I will take them to https://musescore.org/en-GB/handbook on the website"*, but that webpage doesn't actually exist.

Instead, link to https://musescore.org/handbook (no language code) in the app. When the user clicks the link, the website will redirect them to the appropriate language page (in this case https://musescore.org/en/handbook) automatically based on their browser settings.

**Comment by HemantAntony** [comment]
@Tantacrul @shoogle Okay, I also changed where the `musescore.org` link in the About Dialog leads to. Now it leads to https://www.musescore.org/. This now works for me

**Comment by Tantacrul** [comment]
Hey @HemantAntony - that's working. However (and this is my fault), I didn't realise you had not seen this second issue I raised: https://github.com/musescore/MuseScore/issues/11336

This also puts a link to the PP in the 'Update' section in the 'Preferences' popup

Could you possibly add that here too?

Apologies!

**Comment by HemantAntony** [comment]
@Tantacrul that should do it

**Comment by Tantacrul** [comment]
One minor thing - you missed one text change.

image

The update checkbox text should say: **Check to see if a new version of MuseScore is available**

The existing text is just a bit clumsy looking

Apart from that string change, I've tested it and it's good to go.

**Comment by HemantAntony** [comment]
Okay, ready for review/merge

**Comment by Tantacrul** [comment]
100% good to go. Thanks a lot @HemantAntony !

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
