### PR TITLE
[Tab Layout] Allow fingering string text to affect which tablature string is attempted to apply on a linked staff/tab staff

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Port of https://github.com/Jojo-Schmitz/MuseScore/pull/403

Resolves: #22228, the 1st part:

https://github.com/musescore/MuseScore/assets/1786669/526b0e19-285d-4a58-aa63-6e9881e6e3e2

And now 2nd part too.

https://github.com/musescore/MuseScore/assets/1786669/a995e269-0d4c-4d2b-90c0-88d116dc119c

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
The question mark stuff doesn't work though

**Comment by worldwideweary** [comment]
If it's of any value, the "?" in MS3 is got by way of:

```cpp
static const QString unknownFret = QString("?");

QString StaffType::fretString(int fret, int string, bool ghost) const
      {
      if (fret == INVALID_FRET_INDEX)
            return unknownFret;
```

which is invoked during Note::layout() _after_ the handling of String Number texts in my PR for "3.7"... here though in Mu4 the function called is `setFretString()` , but its invocation occurs *beforehand* in relation to this commit. Maybe a relocation of the code beforehand would fix the lack of "questionable results" ... "?" ... ?

**Comment by Jojo-Schmitz** [comment]
Change the order does not help with the ?, but it does together with another change

**Comment by worldwideweary** [comment]
P.S. This stuff is mainly for now as a testing, so it's not necessarily 'worthy' of going into master branch. Like for instance, apparently capo texts "transpose" an instrument, and in that sense this PR wouldn't be too desirable. I was unaware that it functioned as a "movable transposition" in MS3 rather than like a physical capo where it disables frets below the capo. It does things like:"Fret 12 now sounds as if it were Fret 15" or something. 

Scorster provided an mscz. image:

image

The capo 5 and 8 still allow for below capo fret positions. Not sure how to continue with it. For me personally, it would've made sense to disable frets below the capo and then reform the automatic translation from treble to linked tab score if possible, but that's even more work than what has been done so far.... as it would require not just updating any one fret but the entire automatically formed chord shape....

**Comment by Jojo-Schmitz** [comment]
Even if it currently is just for testing and work in progress: testing and comments are welcome

**Pull request closed without merging**
