### PR TITLE
fix #70861: add (sp) and vertical spacers in page layout window

### PR DESCRIPTION
**Pull request by ericfont**
changed "Staff space:" to "Staff space (sp):"
added vertical spacer on bottom of 1st column
added vertical spacer on bottom of 2nd column

### CODE REVIEW

**Comment by ericfont** [comment]
Is Marc there to confirm?  I don't want to comment any more on the [original thread] (https://musescore.org/en/node/70861) (it is too indented so it is hard to tell who is talking to who).  I believe this is what I believe Marc wanted, which when stretched looks like: page-layout-added-vertical-spacer-under-1st-and-2nd-column_stretched

I didn't hear anything about how that 3rd column should appear, but should there be another vertical spacer at the bottom of that?  Also I should I additionally add a vertical spacer at the bottom of "Style"->"General"->"Hairpins..", ->"Pedal, Trill", ->"Figured Bass", ->"Notes", ->"Transpose",  the middle column of "Edit"->"Instruments", the bottom columns of "Preferences" ->"General", ->"Canvas", ->"Note Input" or any other places so the usage of vertical spacer at bottoms of columns is consistent?

**Comment by MarcSabatella** [comment]
Your picture is indeed what I was suggesting.  However, in that thread I
also commented it would be good to develop or adopt a set of GUI guidelines
to follow, and then apply them consistently.

**Comment by ZackTheCardshark** [comment]
This is clearly not in the least an important issue, but I have to say that I dislike the look of that image above (https://github.com/musescore/MuseScore/pull/2141#issuecomment-125405492). Either the dialog's contents should stretch with it, or they should not. Having the right-hand box stretch all the way down, while the two other columns are squished upwards, is not a pleasant solution.

My ideal would be to remove the spacer below the second column (or rather, to <em>not add</em> the spacer below the second column), and only add a spacer in the first column above "First page number." This would mean that when enlarged, in general the contents of the dialog would extend all the way to its bottom, while valuably keeping the "Scaling" box tight and clearly separating "First page number" and "mm/inch" from everything else in the dialog.

**Comment by ZackTheCardshark** [comment]
But, of course, the important thing here is to add the abbreviation "sp" to the dialog.

**Comment by ericfont** [comment]
Regard vertical spacers, sounds like some core dev needs to just write out an official protocol to follow.

**Comment by lasconic** [comment]
For resizable dialog, my impression is that QGroupBox should extends horizontally but not vertically, except if they contains a grid, or a text area. I will merge this and see if we can come with something better for the two orphans, first page number and Unit...

**Pull request merged**
