### PR TITLE
fix #68151: Allowed Edit Style window to remember last user resize

### PR DESCRIPTION
**Pull request by WASamK**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
There are issues with indentation and white space.

**Comment by ericfont** [comment]
fyi, if using qtcreator creator and you put https://musescore.org/sites/musescore.org/files/qt2-musescore.xml in coding styles, then will auto put the correct amount of spaces in when you want to indent...see https://musescore.org/en/developers-handbook/musescore-coding-rules#Coding-Style

**Comment by WASamK** [comment]
I used notepad++ and when I didn't see any indentation problems. But those
indentation errors appear when I committed to github. Check the comparison
at
https://docs.google.com/drawings/d/1SCTJc8cLluWUFD08S0j_4mW113i3yu6DC1bhiFIKzk8/edit
.

This was solved by using qtcreator by using
https://musescore.org/sites/musescore.org/files/qt2-musescore.xml.

**Comment by Jojo-Schmitz** [comment]
You'd need to squash your commints. And still fix the whitespace damage

**Comment by Jojo-Schmitz** [comment]
You'd need to squash your commits. And still fix the whitespace damage, none of the plain whitespace changes are needed.

**Pull request closed without merging**
