### PR TITLE
Fix glissando glitch

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #15316 

The new vtest I've added has nothing to do with the issue solved here, I just noticed we didn't have a vtest for the minTieLength/minGlissandoLength logic, so I put it in.

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

**Comment by RomanPudashkin** [comment]
@Tantacrul 

>  can you let us know if this is safe to merge for 4.0.2

Not really :) This PR introduces 0 new tests, and the fix is located in a very risky and sensitive place for changes

**Comment by Tantacrul** [comment]
OK, @oktophonie @mike-spa - shall we push the underlying issue to 4.1 then?

**Comment by oktophonie** [comment]
A shame (as it's rather gruesome), but so be it!

**Comment by RomanPudashkin** [comment]
@mike-spa please rebase it (I expect to see some red vtests)

**Comment by mike-spa** [comment]
Rebased! About the tests: unfortunately, this is a graphical glitch that exists exclusively as a temporary state during editing (it fixes itself upon save-reload and also upon any re-layout of the interested area of the score). So it basically won't show up in any test that I can create

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
