### PR TITLE
Improve padding and radius of TextInputField and DropDown

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #10046
Resolves: #9900

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Ah, yes, the arrows! I forgot about them. But now I fixed them: 
Schermafbeelding 2021-12-16 om 11 39 39
Also, wouldn't it make sense to give those arrows some hover/hit state? I believe that is not covered yet on Figma, is it?

**Comment by cbjeukendrup** [comment]
I now also added the hover/hit states for the increase/decrease buttons. (Jessica just updated the design for them!)

I also made the behaviour of those buttons a tiny bit smarter. For example, if maxValue = 10, step = 0.5, currentValue = 9.7:
Before: clicking increase button does nothing (because 9.7 + 0.5 > 10)
After: clicking increase button makes it 10 (namely min { 9.7 + 0.5, 10 })

And they are now visually disabled when you can't increase or decrease.

**Comment by jessjwilliamson** [comment]
Fix dark mode please! <3 
image

**Comment by cbjeukendrup** [comment]
Oops, missed one line of code! Fixed.

**Comment by jessjwilliamson** [comment]
Amazing :D Looks great! Happy for this to be merged

**Comment by jessjwilliamson** [comment]
@RomanPudashkin this is great. Can this be merged please?

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
