### PR TITLE
Fix GH#15426: Bring back the Save button (master)

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
and also add the Save icon to "Save as", "Save a copy" and "Save selection"

Resolves: #15426
Resolves: #18896

1. Screenshot 2023-08-02 111420
2. Screenshot 2023-08-02 130118
3. image

See also the (lengthy and heated!) discussion in https://musescore.org/en/node/338612

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Sorry, but I really don't see what's the advantage of having a save button on the Publish tab, since it's also in the menu. If it's on the Publish tab, it takes two clicks to use it (because you need to switch to that tab). If it's in the menu, it also takes two clicks. And opening the menu is far easier and less disruptive than switching to a different tab. So I really don't understand how this is an improvement.

**Comment by Jojo-Schmitz** [comment]
There is no reason at all to __not__ have it there, as long as Print and Export is on that Publish tab too.

But there's no file operations toolbar anymore, this is where it would really belong, along with Open and New, not sure we'd want those 2 though.
Another (additional) option might be to place it next to the undo/redo buttons.

**Comment by Jojo-Schmitz** [comment]
Not sure it'd belong into the Note Input toolbar, but that's be another option

**Comment by Eism** [comment]
Wait... again? 
https://github.com/musescore/MuseScore/issues/15426#issuecomment-1359396603

**Comment by jeetee** [comment]
FWIW; I'm still in the camp, don't place it by default (having Export on the Publish tab suffices imho) but allow the action to be brought back on the toolbar via modification for those that are passionate about it (which a small group of people are).

To me, more time and effort is being wasted in the perception and discussion around this that the effort it would cost us (as a community) to place it into the list of possible toolbar actions a user may customize.

Don't show it on a toolbar by default, but since the action is there and available, allow the toolbar customization for those that love it.

**Comment by MarcSabatella** [comment]
I'm not so sure having it in publish will satisfy the demand that does exist for this - if people have to go hunting for it, they might as well hunt in the menu.

But indeed, if it is to be made available (as an option, certainly not by default) on the Scores tab, the question is, which toolbar?  To me the solution is to actually introduce a file operations toolbar with all the expected icons - open, print, save) that doesn't display by default but can be enabled from the View menu if desired.

Actually, though, another observation: the undo/redo buttons are kind of "orphaned" right now.  They exist but aren't tied to anything in particular.  Maybe *that* should be a toolbar, and *that's* where the file icons could be optionally added.  This would, I suppose, require a settings icon to be added to that toolbar, and it should probably become dockable.

Probably @bkunda would want to weigh in on this.  It's an issue with a history and not a pretty one, I'm afraid.

One other observation: there have been a surprisingly large number of reports along the lines of "I was working on this score all week and never saved it even once, now MuseScore crashed and I just all my work".   Issues with the crash or the autosave functionality aside, it does concern me that some people just don't even realize they need to explicitly save their work, and maybe we need to consider this reality in today's mobile-first world.

**Comment by Jojo-Schmitz** [comment]
Yes, a File Operations toolbar with New, Open, Save, Save to Cloud, Print, Undo and Redo (and a Cog wheel) might be what we need, probably with only the latter 2 (plus the cog wheel) being shown by default. Maybe Save too, for covering your last point.

**Comment by jeetee** [comment]
> Which brings up another question: why is there is Publish toolbar to start with. Everything is in the menu....

Please keep github talk in issues/PRs limited to the subject of them. Go to the discussions or the .org forum for more general and philosophical discussions.

**Comment by stargazer1682** [comment]
Honestly, this might actually work even better than the standard position, because I like to undock the Note Input toolbar and kind of have it floating near the middle of the score. Any other app it's completely the opposite, but I came to find that a preferable workflow with MuseScore; having the save button grouped together with the input buttons, _and_ a customizable position within that space, is _excellent._

**Comment by Jojo-Schmitz** [comment]
See 24833

**Pull request closed without merging**
