### PR TITLE
fix_trill_playback_when_adding_linked_staff_411

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/18715

### CODE REVIEW

**Review by Eism — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/18715 FIXED

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/18715 FIXED

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/18715 FIXED

**Comment by DmitryArefiev** [comment]
Tested #18715 on Win10. Looks fine on my side too

**Pull request merged**
