### PR TITLE
FOSDEM 2020

### PR DESCRIPTION
**Pull request by MarcSabatella**
This isn't a real PR, it just collects the commits for a few other accessibility-related PR's:

#5474 
#5627
#5363
#5655 

The point is to be able to easily create "accessibility" builds for testing.  Ideally, a version of this could be merged into a corresponding accessibility branch on the main MuseScore repository, and "release" builds made available with Qt 5.12.  But any partial steps towards that goal are useful too.

### CODE REVIEW

**Comment by dmitrio95** [comment]
Seems to be not actual anymore.

**Comment by MarcSabatella** [comment]
Correct, although three of the four PR’s are still open and still would be appreciated.

**Comment by dmitrio95** [comment]
#5655 is marked work-in-progress though, is it still so or can it be already merged?

**Comment by MarcSabatella** [comment]
It's mergeable as is.  I mentioned in the comments I marked it that way only because I may be adding yet more strings, but so far this is still the only one I *know* is missing.  I've got an intern (!) doing more testing now, I'll probably end up with a few more changes to submit, and if any are just about names/labels, I might reuse the same branch, but no reason it can't be merged as is.

The palette one from @shoogle is the most important, really.  Although we also still need to have 5.12-or-later builds somehow, even if just as an accessibility special.

**Comment by dmitrio95** [comment]
OK, thanks, I merged the mentioned pull requests.

**Pull request closed without merging**
