### PR TITLE
Replace icons with CC-BY 4.0 version

### PR DESCRIPTION
**Pull request by lasconic**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Plans to add this to the 2.1 branch too? Or would it look too different from 2.0.x?

**Comment by lasconic** [comment]
Any opinion?

**Comment by Jojo-Schmitz** [comment]
Haven't noticed any, but maybe let this sink in a bit longer?

**Comment by lasconic** [comment]
sounds like a plan now.

**Pull request merged**
