### PR TITLE
[MU4 RC] Cherry-picking two trivial string change PRs

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Includes: 
#14750
#14734

### CODE REVIEW

**Comment by shoogle** [comment]
I think it would be better to cherry-pick the actual code commits (as was done in PR #14749 and PR #14747) rather than the merge commits. If you cherry-pick a merge commit then we will probably end up with yet another merge commit.

**Comment by Gootector** [comment]
Let's see - for example: the branch 4.0_alpha is 21 commits ahead and 3660 commits master. So, 21 commits from alpha aren't in the master branch.
I think that MuseScore repo should take example from Audacity repo:
The master is always switched to the next big release. After the release of big release, PRs for patch release are sending into the new branch. With the release of patch release, patch branch is merged into the master. The master contains all commits from the other branches.
I hope I helped.

**Comment by cbjeukendrup** [comment]
@shoogle Done! Indeed a better idea. Also, it seems that cherry-picking a merge commit turns it into a "normal" commit, containing all the changes of the merged commits together.

@Gootector Yes, that's another possible strategy. The big advantage is that the "… commits ahead" message will say something useful: currently, we "cherry-pick" all commits to the RC branch, which means that it becomes technically a different commit, so after cherry-picking one commit, GitHub will say: "1 commit ahead and 1 commit behind". I think that's what happened with the alpha branch: those "ahead" commits are commits that were cherry-picked from the master branch. On the other hand, if we would create the commits on the RC branch, and then merge the RC branch into master, the commits will stay the same, but "glued" to the master branch by a merge commit. That also brings us to the disadvantage: those merge commits create a very non-linear commit history, making it slightly more difficult to track down where a certain bug was introduced. But maybe that's only a small problem.
Anyway, maybe something to try out next time :)

**Comment by shoogle** [comment]
@Gootector
> 21 commits from alpha aren't in the master branch.

When commits are cherry-picked between branches, the SHA changes, so Git and Github no longer identify them as being the same even though the code itself has not changed. In reality, all code on the `4.0alpha` branch also made it to `master`.

Audacity's method is worth investigating, but it has some downsides of its own. Firstly the non-linear history that @cbjeukendrup mentioned, but also...

> With the release of patch release, patch branch is merged into the master.

This means that useful fixes on the patch branch are not available on the master branch until after the patch release has been made.

I'd say the big advantage of Audacity's method is not having to cherry-pick each and every commit individually. However, it puts the burden of rebasing everything all on one person, and rebasing gets harder the longer it is delayed. Eventually some of those SHAs probably wouldn't match even with Audacity's method.

**Comment by cbjeukendrup** [comment]
(Of course, it's also possible to merge the patch branch every few days, or even every few hours. That solves the problems of having to merge everything at once, and of not having important fixes in master for a while.)

**Comment by shoogle** [comment]
True. Regular merges would probably result in fewer changed SHAs as well (once one SHA changes all subsequent SHAs under the same merge commit must change too, but SHAs in future merges can still match). However, the more often you do it the less work you save compared to cherry-picking.

It would also make the history even more non-linear (lots of small merges vs. one big one). I'm not sure whether that would make it easier or harder to follow.

**Comment by MarcSabatella** [comment]
FWIW, I'm in favor of anything that makes it easy for folks like me to be able to submit occasional small PR's and not have to do them each twice.  I still can't tell what if anything I would need to do to make sure https://github.com/musescore/MuseScore/pull/14669 or https://github.com/musescore/MuseScore/pull/14670 make it into the release.  They were both merged into master but perhaps not rc.

**Pull request merged**
