### PR TITLE
fix #68456: fixes pitch bends

### PR DESCRIPTION
**Pull request by MichaelFroelich**
fix #68456: see https://musescore.org/en/node/68456, issue turned out to be an incorrect magic number

### CODE REVIEW

**Comment by anatoly-os** [comment]
Restarted the build to wait for an actual test results. Will merge if everything is ok.

**Comment by anatoly-os** [comment]
Nope, the tests need to be adjusted.

**Comment by MichaelFroelich** [comment]
Tests should be fixed now, sorry for any issues caused.

**Comment by MichaelFroelich** [comment]
a

**Comment by MichaelFroelich** [comment]
Accidentally closed, sorry

**Pull request merged**
