### PR TITLE
Mxl diagram export

### PR DESCRIPTION
**Pull request by kwertyops**
Resolves: https://musescore.org/en/node/303623

Attn: @Jojo-Schmitz , @vpereverzev 

This is a fork of [thibault:mxl_diagram_export](https://github.com/thibault/MuseScore/tree/mxl_diagram_export), and is essentially a reopening of the following pull request:

[https://github.com/musescore/MuseScore/pull/5958](https://github.com/musescore/MuseScore/pull/5958)

In that thread, a rebase onto 3.x was requested to be considered for a merge, but @thibault has not gotten around to it, so I thought I'd try to help it along. I forked that fork, and made the necessary changes for the rebase:

 - [x] Rename testHarmony6.mxl -> testHarmony7.mxl
 - [x] Rename testHarmony6_ref.mscx -> testHarmony7_ref.mscx
 - [x] Rebase onto 3.x
 - [x] Update the reference to the renamed test file in: mtest/musicxml/io/tst_mxml_io.cpp

Also including here the description from the original pull request from @thibault (linked above):

----------------------------------------------------------

There are multiple issues in the MusicXML annotations export that prevents chord diagrams to be exported in most cases:

    chord diagrams are not exported unless there is a sibling harmony element.
    only one chord diagram is exported for a chord.
    chord diagrams that are not linked to a chord are not exported.
    chord diagrams are not always exported to the correct voice.

This PR rewrites the harmony export algorithm to fix those issues.

This is my first contribution to MuseScore and moreover I'm not familiar with c++ at all, so there will probably be some stuff to fix.

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Looks good to me

**Comment by Jojo-Schmitz** [comment]
Did you sign the [CLA](https:://musescore.org/cla), and if so under which name?)

**Comment by kwertyops** [comment]
I've signed it now, under 'kwertyops'.

**Comment by kwertyops** [comment]
> Looks good to me.
> Did you really sign the [CLA](https:://musescore.org/cla), and if so under which name?

Sorry, that was a copy/paste. I've signed it now under 'kwertyops'.

**Comment by kwertyops** [comment]
@Jojo-Schmitz 
> Looks good to me.
> Did you really sign the [CLA](https:://musescore.org/cla), and if so under which name?

Sorry, that was a copy/paste. I've signed it now under 'kwertyops'.

**Comment by thibault** [comment]
Thank you for your work @kwertyops

**Comment by Jojo-Schmitz** [comment]
This PR seems to be needed in master too

**Pull request merged**
