### PR TITLE
Hide SMuFL fonts in Preferences > Appearance > Font

### PR DESCRIPTION
**Pull request by re1san**
Resolves: #20257 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually

### CODE REVIEW

**Review by cbjeukendrup — COMMENTED** [review]
Thanks for your contribution! I had one idea: it would have my slight preference if this new code was moved into `UiConfiguration::possibleFontFamilies()`, so that that method already returns the correct list. Would be great if you could do that!

**Comment by cbjeukendrup** [comment]
@re1san Thanks, this looks good now! Now it would be great if you could rebase the PR and squash your commits into one (this change is simple enough for a single commit).

**Comment by re1san** [comment]
Alright

**Review by cbjeukendrup — APPROVED** [review]
Thanks!

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/20257 FIXED

**Pull request merged**
