### PR TITLE
Fix #209331: Updated Descriptions of Enharmonic shortcuts to reflect current implementation

### PR DESCRIPTION
**Pull request by dinukadesilva**
image

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
1st commit could go to the 2.2 branch too, the 2nd commit should not

**Comment by dinukadesilva** [comment]
@Jojo-Schmitz Do you want me to make a pull request to 2.2 branch

**Comment by Jojo-Schmitz** [comment]
I don't think that is needed, @lasconic could cherry-pick that 1st commit, if he thinks it should go in

**Comment by lasconic** [comment]
1st commit is also in 2.2 now.

**Pull request merged**
