### PR TITLE
Fix #11221: Make playhead cursor thinner

### LINKED ISSUE #11221: New playhead cursor should be thinner
**Describe the bug**
(Edited)

Currently our playhead looks like this. It appears to be centred to the beat, which is fine.
image

I propose we simply make is quite a bit narrower. I think we should try 4px wide (when at 100% zoom) to begin with and then we can quickly test to get a feel for it.
image

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #11221

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Tantacrul** [comment]
You're a legend! Thanks!

OK, so I _think_ the width is good, but because it's now thinner, the transparency is too low, so it's a tiny bit hard to see when zoomed out.

I'm not certain what the transparency is set to but if it is 40%, I'd up it to around 75%.

Once that's done, we may also **ever so slightly** increase the width but I really don't know until the transparency is right.

Do you mind doing that?

Thanks again!
Martin

**Comment by Tantacrul** [comment]
Ooh, this is extremely close!

Sorry @HemantAntony - this is one of those things that you always have to tweak to get perfect. I'm actually not sure if we should tweak any further. However, so I can potentially do some animations myself to figure out the perfect balance between width / opacity, could you tell me the following:

1. What is the hex code for the colour of the playhead? It doesn't look to be our blue accent colour (which is fine).
2. What is the current width in pixels of this latest version?
3. What is the current opacity of this latest version?

Thanks a lot!
Martin

**Comment by shoogle** [comment]
Be aware that this PR has also changed the colour/opacity of the **note input cursor** as well as the playback cursor.

Note input in nightly builds | Note input in this PR
:---:|:---:
image | image

**Comment by Tantacrul** [comment]
Thanks @shoogle. Didn't spot that. Yeah, these two things will need to be separate. @HemantAntony, let me know if that causes any awkwardness.

**Comment by HemantAntony** [comment]
@Tantacrul When you open the new updated PR, go to appearance preferences and you will find that I add temporary settings for playback cursor for you to mess with. Also if you want me to keep those options so users can change it, tell me

image


Enjoy...

**Comment by HemantAntony** [comment]
To answer your questions

1. RGB values: 0, 101, 191
2. I don't know if my number specifies number of pixels. I just entered an arbitrary number - 10. This is why I specified units instead of pixels in the temp settings I created for you
3. 200

**Comment by Tantacrul** [comment]
Legend! OK, trying now.

**Comment by Tantacrul** [comment]
Thanks very much for this! Was a big help

1. the Hex is fine.
2. Opacity: 70% (178)
3. Width: 8 units
4. Make sure the playhead opacity does not affect the opacity of note input! (Not input looks perfect as it is)

Thanks again!

**Comment by HemantAntony** [comment]
@Tantacrul check this PR again. I updated it again

**Comment by Tantacrul** [comment]
Yep. It think this looks much better now! Thanks a lot @HemantAntony!

@RomanPudashkin or @Eism: if you are happy with this, it's ready for merging from an interaction point of view.

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
