### PR TITLE
Backport FinaleMaestro & FinaleBroadway fonts to 3.6.2 

### PR DESCRIPTION
**Pull request by Levitanus**
Since I prefer to stay on the 3.x version due to its ergonomic and stability, I just want to have a backport of Finale fonts from the 4.x version. I feel that this can make sense to other users and want to include the changes to the original repo.

Now I just repeated the actions from this commit: https://github.com/musescore/MuseScore/commit/ceaa8cbe6e0846f65284ef7294790111c8d825c9
If the general idea and realization of PR passes ‒ I'd add all necessary Copyrights etc., including signing CLA. 

- [ ] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
There won't be any further 3.x releases, so we can't merge anything to these branches.

**Comment by Levitanus** [comment]
But many Linux repos have git repos, that are tracking this branch. I still find this useful.

**Comment by cbjeukendrup** [comment]
This branch corresponds with the only official 3.6.2 release; and that release has already happened two years ago or so, so we can't make any amendments to that. There won't be an official 3.6.3 release obviously, since (4.x has already been released and) if we were to do that we'd have to test it properly before we can call it "official", and we can't spend time on that. 

If you want this change to make it into linux repos, then you'll need to commit it to your own unofficial branch and ask those linux maintainers to use your unofficial branch instead, but I don't know if that would make anyone happy.

Anyway, my point is that we don't have time to go through the rituals for making this "official" for an old version that is hardly relevant anymore, and we won't _pretend_ that it's official by just merging it.

**Comment by Jojo-Schmitz** [comment]
In my forks's 3.x branch these fonts (and many more) are available

**Pull request closed without merging**
