### PR TITLE
Add bluegrass, small concert band and small marching band templates; fix #153906: update all templates with instrument definitions for 2.1

### PR DESCRIPTION
**Pull request by IsaacWeiss**
Updated all templates containing piccolo, string bass variants and/or "Percussion" staves

Bluegrass and small concert band templates courtesy of Devyn Horne and Kang Yi, see https://musescore.org/en/node/53891

### CODE REVIEW

**Comment by lasconic** [comment]
That's a lot of templates... Hopefully we can remove some in an upcoming version...

**Comment by lasconic** [comment]
Several templates have already been modified in 2.1 

share/templates/05-Jazz/02-Big_Band.mscz
share/templates/05-Jazz/03-Jazz_Combo.mscz
share/templates/06-Popular/01-Rock_Band.mscz
share/templates/08-Orchestral/01-Classical_Orchestra.mscz

**Comment by lasconic** [comment]
So if we do want all these templates in 2.1, they need to be redone with recent 2.1 nightly build.

**Comment by lasconic** [comment]
I merged the PR in 2.1 too. It would be great if someone could verify that the templates are correct. They do open in 2.1.

**Comment by IsaacWeiss** [comment]
Templates *were* redone with a 2.1 nightly build in January, for the new default instrument definitions. Has anything else changed since then?

As to removing templates, I see them as being very important unless/until MuseScore is able to automatically number instruments, connect barlines, add brackets, and scale staves appropriately when creating a score from scratch—and *especially* important for 3.0 if no easy way to connect barlines through multiple staves is brought back.

**Comment by lasconic** [comment]
and I disagree... We can't measure it but I'm pretty sure that the more we add templates, the less templates are used.

*no easy way to connect barlines through multiple staves is brought back.*
Is there an issue for this one?

**Comment by IsaacWeiss** [comment]
There is https://musescore.org/en/node/153106#comment-629726...

**Pull request merged**
