### PR TITLE
fix #280830 applyPaletteElement to update score

### PR DESCRIPTION
**Pull request by ericfont**

### CODE REVIEW

**Comment by ericfont** [comment]
fixes https://musescore.org/en/node/280830

**Comment by dmitrio95** [comment]
Unfortunately this solution makes time signature changes which are made as described in the issue be not undoable. The issue is probably that `Score::update` is usually called from within `Score::endCmd` and `startCmd`/`endCmd` calls must be done in order for action to be undoable. So a full solution should probably involve something about maintaining proper undo stack state via `startCmd`/`endCmd` calls.

As a side note, I believe it would be good to have eventually some other way to maintain undo stack state, some RAII-based solution, but until that we have to maintain a proper number of `startCmd` and `endCmd` calls manually.

**Comment by ericfont** [comment]
Sorry, I had a feeling it wouldn't be so simple.

**Comment by ericfont** [comment]
I notice if I put a breakpoint in Score::startCmd(), it is never hit when I apply the break.  And I notice that startCmd() and endCmd() would be taken inside Palette::applyPaletteElement() if the following condition is met:

```
      if (viewer->mscoreState() != STATE_EDIT
         && viewer->mscoreState() != STATE_LYRICS_EDIT
         && viewer->mscoreState() != STATE_HARMONY_FIGBASS_EDIT) { // Already in startCmd in this case
            score->startCmd();
            }
```

And viewer->mscoreState() returns STATE_EDIT, which is why it is taken.  I don't know what STATE_EDIT exactly means (enum ScoreState doesn't describe what it is), but maybe the score isn't really in STATE_EDIT...I don't know...

**Comment by ericfont** [comment]
Well I do notice that bottom-right of musescore says "Edit mode" after I double-click some element.

I'm also noticing that while in this so-called "Edit mode" on a note, I can't double click on an accidental from the palette to apply that accidental.  So maybe are we supposed to disable double-clicking from the palette while in this "Edit mode"?  I don't know, cause I don't know what edit mode really means.

**Pull request closed without merging**
