### PR TITLE
[MU3] Added make local build revision

### PR DESCRIPTION
**Pull request by igorkorsukov**
Added make local build revision

### CODE REVIEW

**Comment by worldwideweary** [comment]
Looking forward to the merge :)

**Comment by shoogle** [comment]
How will the `MUSESCORE_REVISION` variable get set for incremental builds (i.e. builds where CMake is not run beforehand)?

**Comment by igorkorsukov** [comment]
> How will the `MUSESCORE_REVISION` variable get set for incremental builds (i.e. builds where CMake is not run beforehand)?

During development, it is not expected to set a revision.
They need to complete the development, make a commit, and only then update the revision and build the application (with the run cmake). If someone needs all this.

**Comment by shoogle** [comment]
Fair enough. I guess the revision is more important for nightlies than for personal builds, especially if it refers to a personal commit that's not in the main repository.

**Pull request merged**
