### PR TITLE
Grammar and typo fixes

### PR DESCRIPTION
**Pull request by Howard-C**
Found during translation

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Shame on me for not having spotted those in my #5832

**Comment by Howard-C** [comment]
It seems only logical that the opposite of "Failed doing" is "Succeeded doing". But if I'm wrong please correct me.

**Comment by Jojo-Schmitz** [comment]
I buy that argument, But still unsure whether the existing term is wrong grammar.

**Comment by Howard-C** [comment]
Actually, the most accurate, I think, is "Loading succeeded" etc.

**Comment by Howard-C** [comment]
> I buy that argument, But still unsure whether the existing term is wrong grammar.

I think it is wrong, "success" is an adjective, which cannot be proceeded by the present participle form of a verb.

**Comment by Jojo-Schmitz** [comment]
I like that better. Same foe the 'failed` strings

**Comment by Jojo-Schmitz** [comment]
There's another one: "Failed clearing directory"

**Comment by Howard-C** [comment]
I think these are best to keep "Failed" for the first word to raise attention.

**Comment by Spire42** [comment]
I would prefer “Successfully prepared [x]” and “Failed to prepare [x]”.

The grammatical structure is first-person narrative with an implied subject (“I”). It's the most commonly used format for status messages in English.

**Comment by Jojo-Schmitz** [comment]
"Success preparing" doesn't have any "[x]" to follow

**Comment by Howard-C** [comment]
@Spire42 Sounds good for me.

**Comment by Spire42** [comment]
> "Success preparing" doesn't have any "[x]" to follow, neither has "Success processing" or "Success loading". Just the failure messages have more text appended, separated by a line break

That's why I put it in brackets; it's optional.

Actually, even the word “successfully” can be omitted. If it isn't a failure, it's a success by definition, and the repeated “successfully” is just noise that the user has to scan past to get to the actual message.

**Comment by Jojo-Schmitz** [comment]
There are several levels or steps to success, Loading, Preparing, Processing, seems important to mention where we're at

**Comment by Howard-C** [comment]
@Jojo-Schmitz He was talking about omitting the word "success" (in various forms), not the other words :-)

**Comment by Jojo-Schmitz** [comment]
I know, thise are still important though.

Loading...
Loading succeeded
Preparing...
Preparing succeeded
Processing...
Processing succeeded

**Pull request merged**
