### PR TITLE
Fix GH#18166: All expression texts not exported to MusicXML

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: #18166

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by oktophonie** [comment]
This addresses standalone Expression items, but expression-type text typed directly either side of a Dynamic mark remains unexported (also a regression since 4.0). Presumbly this is also due to changes in #17001; I will be sure to have @mike-spa publicly whipped.

**Comment by Jojo-Schmitz** [comment]
Someone having a brown paperbag handy? I ran out of supplies...

**Comment by Jojo-Schmitz** [comment]
Could you please open a new issue for that? I don't see a similarly simple fix for that at the moment

**Comment by oktophonie** [comment]
I'll get @mike-spa to clean up his own mess. Meanwhile this can be merged (we'll also need a version for the 4.1.0 branch at some point)

**Comment by Jojo-Schmitz** [comment]
See #18181

**Pull request merged**
