### PR TITLE
Change pitchToString to show flated notes too

### PR DESCRIPTION
**Pull request by mikekirin**
Changed pitchToString, that it shows not only sharp notes, but flat notes as well.

### CODE REVIEW

**Review by alexpavlov96 — APPROVED** [review]

**Review by handrok — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
All nice and good, but so far this isn't called anywhere in a way that would show flats, or am I missing something?

**Comment by mikekirin** [comment]
> All nice and good, but so far this isn't called anywhere in a way that would show flats, or am I missing something?

This is a mu part of fix for xtz.

**Comment by Jojo-Schmitz** [comment]
Ah, OK. So a new mobile app is in the works?

**Comment by Jojo-Schmitz** [comment]
It probably translation-wise benefits from #16172, in that it uses the same strings in the same context.

**Pull request merged**
