### PR TITLE
[MU3] Fix #317438: Wrong order of sagittal accidentals

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: https://musescore.org/en/node/317438

Same fix should be needed in master too, see #7521, merged meanwhile

### CODE REVIEW

**Comment by vpereverzev** [comment]
Closed, since it's already in master

**Comment by Jojo-Schmitz** [comment]
Still needed for 3.x thoug

**Comment by Jojo-Schmitz** [comment]
Is closing this here the penalty for me having done the port to master myself?

**Comment by Jojo-Schmitz** [comment]
Please reopen and merge into 3.x

**Pull request closed without merging**
