### PR TITLE
fix for issue https://musescore.org/en/node/71826

### PR DESCRIPTION
**Pull request by jimka2001**

### CODE REVIEW

**Comment by jimka2001** [comment]
I added a new test case in this PR.  Is there something I need to do to the version number of the .mscx file? mtest/libmscore/midi/testGlissando-71826.mscx

**Comment by lasconic** [comment]
Hi Jim,

It's better if you use "Fix #XXXX : explanation" in your commit message (with XXXX the id of the bug you solved). Even if you squash the commits.. Currently the commit message is "added test case, and fixed problem, was confused about which staff to measure line in" which doesn't make much sense in the whole history.

Regarding MSCX test files, it's better if they are saved by running `mscore -t`. It will strip out variable information such as date, version number, OS information etc...

**Comment by jimka2001** [comment]
sorry, I don't understand what you mean by saying "mscore -t".
I run musescore within Xcode.   and I save the files into the test case
directory explicitly using save-as within musescore.
I don't even know how to run my freshly compiled version of musescore from
the unix command line because Xcode does such an excellent job of hiding
this in the most obscure directory imaginable :-(


Is it possible for me simply to edit the .mscx file by hand and update the
things that need to be changed?


About the commit message, let me see if I understand correctly.
Once I've verified that my commits do indeed solve the problem, you'd like
me to edit the commit message and re-push the commits with "Fix#XXX"
prepended to the commit message.  Is that right?  I cannot prepend that
prefix originally as I do not know until after Travis finishes whether the
issue was indeed fixed.

**Comment by lasconic** [comment]
If you are reading this from you email client. There is a link at the bottom of this mail with a direct link to the conversation on github.com. It's probably easier to read by following this link. The link says "View it on github".


Where is the binary built by XCode?
---

It's in  `build.xcode/mscore/Debug/mscore.app/Contents/MacOS/mscore` when you are in your MuseScore clone directory.

How to run MuseScore with command line argument from XCode
---

In XCode, click here 
capture d ecran 2015-08-03 10 01 31

Type "edit scheme", and select edit scheme menu
capture d ecran 2015-08-03 10 01 31

Choose Run, Arguments, Arguments passed at launch. press the + and add -t. Close and run.

capture d ecran 2015-08-03 10 03 11

capture d ecran 2015-08-03 10 04 38


About fix #xxxxx
---

When you start a branch to fix a bug, you already know the bug id, since your branch here is 71826-glissando. When you commit, just use "Fix #xxx" in the first commit. And if you squash the commits later, make sure you use Fix #XXXXX in the remaining commit message. It's required because it makes the history cleaner and it automagically mark the bug as fixed in the MuseScore bug tracker.

**Comment by jimka2001** [comment]
OK, cool.  so when does the bug get automagically fixed in the tracker?
I.e., I'll commit several times and squash several times before it is
actually fixed.  right?

**Comment by lasconic** [comment]
The bug is marked as fixed only when your PR is merged to the main repository.

**Comment by jimka2001** [comment]
Great.  Makes sense.  And what is the trigger for you to do the merge?  I guess this always involves a conversation between you and the person fixing the issue?

**Comment by lasconic** [comment]
In general, Werner or I merge the PR. 
We need 1/ time, 2/ A good understanding of the problem and the solution (so it helps to have a reference to all the discussions about the problem, comments on the solution), 3/ when applicable, new tests.
So far, it worked like this because we are still a small community of developers and I know all of them by name. If we would grow 3 times bigger, we will need something better, like a code review system with votes, similar to what Qt is doing.

**Comment by jimka2001** [comment]
Hi lasonic, I believe they PR is ready to be merged.

**Comment by lasconic** [comment]
A space is need in "Fix #XXXXX" in order to trigger the auto fixed in the issue tracker :)

**Comment by jimka2001** [comment]
I seem to find every possible wrong way.
OK, i’ve updated two branches  71826-glissando and  71721-baroque-prall

**Pull request merged**
