### PR TITLE
fix #269927: Prevent crash when importing file with fermata on grace note

### PR DESCRIPTION
**Pull request by elias-pap**

### CODE REVIEW

**Comment by elias-pap** [comment]
Sorry for the dummy commit. We could add a section at [https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/git-workflow](url) in paragraph "**Make a pull request to send your changes to MuseScore**" about the usage of Travis and AppVeyor before the pull request part.

**Comment by lasconic** [comment]
What do you miss there exactly ?

**Comment by elias-pap** [comment]
Nothing, it is all well-explained. I've just noticed only later that you have a paragraph for it in section **Advice & tips**, and I wouldn't submit the PR if it didn't compile, that's all.

**Comment by lvinken** [comment]
I highly doubt this fix is correct, as it creates a separate segment for the grace note, while in master grace notes do not get a separate segment, but are children of the following (regular) note. Furthermore, the fermata gets lost.

**Comment by lasconic** [comment]
I agree with @lvinken. Please have another look to this issue in another branch. I close this PR.

**Pull request closed without merging**
