### PR TITLE
Change palette from swapping elements to inserting dropped element.

### PR DESCRIPTION
**Pull request by CammyVee**
Only applies for elements already in the palette. All external elements still append only. 

Feedback would be appreciated.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I believe you'd better sqash them all into just one commit (with keeping the last commit message)

**Comment by CammyVee** [comment]
Thank you @Jojo-Schmitz , they are all quashed now.

**Comment by IsaacWeiss** [comment]
This seems to me like not a bad idea. Any reason it was never merged? I see CammyVee signed the CLA.

**Comment by lasconic** [comment]
It's not yet working correctly. Dragging from the score to the palette doesn't insert but always append.

**Pull request merged**
