### PR TITLE
fix #271299: Errors with multiple clefs

### PR DESCRIPTION
**Pull request by mattmcclinch**
See https://musescore.org/en/node/271299.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I just love these one-letter fixes ;-)

**Comment by mattmcclinch** [comment]
I thought you would like that, Jojo!
Now it is 6 * 1. I thought it best to make the same change to Staff:setClef().

**Comment by anatoly-os** [comment]
I just love the code which has next() and next1() methods. Wtf?) I would even understand nextNew() name, but next1() is something really weird...

**Comment by anatoly-os** [comment]
Created the issue about methods names https://musescore.org/en/node/272985.

**Pull request merged**
