### PR TITLE
fix Linux and MacOS artifacts creation and uploading for PR containin…

### PR DESCRIPTION
**Pull request by AntonioBL**
…g collect_artifacts

At the moment the head_commit.message field for a pull_request event is empty, so a workaround is needed, see also https://github.community/t5/GitHub-Actions/Accessing-commit-message-in-pull-request-event/td-p/40856

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [N/A] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [N/A] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [N/A] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by AntonioBL** [comment]
It was quite difficult, but now it should work, also for PR with multiple commits if the last one contains "collect_artifacts".

**Comment by Jojo-Schmitz** [comment]
does that commits.json belong onto this PR?

**Comment by AntonioBL** [comment]
No. It was a leftover of the test I run locally. Sorry. :sweat_smile:

_Now_ it should be ok.

**Comment by Jojo-Schmitz** [comment]
the Linux artifact build is not happy

**Comment by Jojo-Schmitz** [comment]
and maybe the artifact builds should be allowed failures?

**Comment by AntonioBL** [comment]
That is a legit failure due to a missing semicolon in build/Linux+BSD/mscore.desktop.in introduced in https://github.com/musescore/MuseScore/commit/4419866a31e84d2bc13a7a56dd938f5b9a6b66d6

/MuseScore/build.release/MuseScore-x86_64.AppDir/mscore-portable.desktop: error: value "application/x-musescore;application/x-musescore+xml;application/vnd.recordare.musicxml;application/vnd.recordare.musicxml+xml;audio/midi;application/x-bww;application/x-biab;application/x-capella;audio/x-gtp;application/x-musedata;application/x-overture;audio/x-ptb;application/x-sf2;application/x-sf3" for string list key "MimeType" in group "Desktop Entry" does not have a semicolon (';') as trailing character

**Comment by Jojo-Schmitz** [comment]
> That is a legit failure due to a missing semicolon in build/Linux+BSD/mscore.desktop.in introduced in [4419866](https://github.com/musescore/MuseScore/commit/4419866a31e84d2bc13a7a56dd938f5b9a6b66d6)

So a brown bag for @shoogle :-)

**Comment by AntonioBL** [comment]
Apparently there is no possibility for an "allowed failure" in Github actions. That's also why I tried to restrict artifacts generation only when explicitly asked for.

Apparently, Github actions are less permissive than Travis and as soon as an error is cast by whatever instruction during the build chain, they stop and emit a failure (while Travis sometimes continues to the end of the script).

**Comment by AntonioBL** [comment]
> 
> 
> > That is a legit failure due to a missing semicolon in build/Linux+BSD/mscore.desktop.in introduced in [4419866](https://github.com/musescore/MuseScore/commit/4419866a31e84d2bc13a7a56dd938f5b9a6b66d6)
> 
> So a brown bag for @shoogle :-)

At least this time it is not _my_ brown bag. :rofl:

**Comment by dmitrio95** [comment]
Added a missing semicolon (745038c30d31db55fb0c6c5cbaca69fa6f2dda4a), let's see if build succeeds.

**Comment by shoogle** [comment]
> > That is a legit failure due to a missing semicolon in build/Linux+BSD/mscore.desktop.in introduced in 4419866
>
> So a brown bag for @shoogle :-)

It's a brown bag for somebody, but not me. :wink: 

Quote from the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#value-types) (emphasis is mine):

> Some keys can have multiple values. [...] The multiple values should be separated by a semicolon and the value of the key may be **optionally** terminated by a semicolon.

**Pull request merged**
