### PR TITLE
Fix GH#24553: MusicXML: A title like "Jazz Piece No. 5" get interpreted as a subtitle

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: #24553 

Turned out to be a rather simple off-by-one error, @miiizen ?

Edit: Apparently not, but let's not try it infer anything from a title if it is just one line.

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Note that the exact functionality is still different than before https://github.com/musescore/MuseScore/commit/0ea3638a716ca776db69fe6ce122db555a81b918.

Before:
when one line is encountered that is likely credit/subtitle text, then that line _and all lines below it_ are moved to credit/subtitle text.

After: 
when one line is encountered that is likely credit/subtitle text, _only that line_ is moved.

**Comment by Jojo-Schmitz** [comment]
Question is whether that is better or not, isn't it?

**Comment by cbjeukendrup** [comment]
That's up to @miiizen and @oktophonie.

**Comment by Jojo-Schmitz** [comment]
of course it is ;-)

**Comment by miiizen** [comment]
I can see the problem here, but I don't think this is the way we should fix it.  I'd prefer to prevent this situation either:
- by not inferring subtitles or credits when there is only one line of text
- or, if after inference we end up with an empty title, promote the first line back to title

**Comment by Jojo-Schmitz** [comment]
Isn't my change doing exactly _not inferring subtitles or credits when there is only one line of text_ ? It just skips the loop if there's only one line

**Comment by miiizen** [comment]
We'd still like to check if the first line of a title would be better suited to a subtitle when there is more than one line.

**Comment by Jojo-Schmitz** [comment]
Which again would leave the score without a title

**Comment by miiizen** [comment]
If I set the title to this: 
```xml
<work>
  <work-title>Jazz Piece No. 5
  rest of title</work-title>
</work>
```

I get the following, which is what we'd prefer!
image

**Review by miiizen — APPROVED** [review]
Perfect, thanks!

**Comment by Jojo-Schmitz** [comment]
Rebased to fix merge conflicts.
Please consider a timely merge.

**Pull request merged**
