### PR TITLE
[MU4] fix #301525: Assign 'High Floor Tom' to 1st voice. Update templates.

### PR DESCRIPTION
**Pull request by snieb**
Resolves: https://musescore.org/en/node/301525

The _High Floor Tom_ note is now in the 1st voice, consistent with the other toms & parts of the kit that are hit with a stick.

Besides fixing `drumset.cpp` for freshly generated drumsets, I searched for static occurences of the old configuration in XML (`grep -ir '<Drum pitch="43"'`):
- **Score templates in `share/templates` that include drumset have been updated accordingly.**
  - No change to `drumset_fr.drm`, as French notation apparently puts all toms in the 2nd voice (?).  Not familiar with it, but appears to be consistent.
- **I have NOT looked at the matching files from the test directories**:  *mtest/* (28), *vtest/* (11), *test/* (1).  Just too many to go through manually, and I have not yet come up with a good enough awk script to robustly automate this.  If a few of them are especially important, I can update them manually for now.
- No change to `mscore/importgtp.cpp`.  Externally generated in GP5; toms appear to be at least consistent.
- No change to `share/instruments/instruments.xml`.  Correct in *tom-toms* instrument.  Other match is for triangle & hence not applicable.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Howard-C** [comment]
Please fix the failing mtests. Diffs are shown start from [here](https://travis-ci.org/musescore/MuseScore/jobs/654108612#L4390).

**Comment by snieb** [comment]
JTBC:  The tests use the static `mtest/*.mscx` files as reference?  So I'm supposed to modify those, correct? (Assuming ofc that all diffs are indeed caused by the old drumset.)

Also, how do I run the tests on my machine?  `ctest` (like [mtest/README.md)](https://github.com/musescore/MuseScore/blob/master/mtest/README.md) suggests), or `build/run_tests.sh`?  Before that, do I have to re-run all the `make` commands after any change?

Thanks for pointing me to the diff link @Howard-C ; this is the 1st time I'm interacting with a CI platform (or submitting a PR)... 😅

**Comment by Howard-C** [comment]
> The tests use the static mtest/*.mscx files as reference? So I'm supposed to modify those, correct?

Yes.

> Also, how do I run the tests on my machine?

I don't know, I've never done that.

**Comment by njvdberg** [comment]
> Before that, do I have to re-run all the make commands after any change?

You can go to the directory containing the test you want to <code>make</code>. This will build a <code>tst_xxxx</code> which you can run.

**Comment by Jojo-Schmitz** [comment]
Fixong those mtests is easy enough, just manually edit (like using any plain text editor) those 5 mscx files and change them as per the `diff` output. You could probably even use `patch` on them.

**Comment by anatoly-os** [comment]
@snieb hello sir. Are you around to fix the failed tests?

**Comment by snieb** [comment]
Sorry, I had messed up my repo & could not push, then forgot about it.  Thank you for the reminder, @anatoly-os !
I have used this interactive script that should be fairly easy to adapt to similar find-replace-tasks: https://gist.github.com/snieb/da72125a9a01cde51ffa5e4e6f6ca111

**Comment by snieb** [comment]
@Jojo-Schmitz Yeah, I hadn't realized that only 5 files actually caused problems... And I need to have a closer look at `patch` sometime. ;)

**Comment by snieb** [comment]
I also updated all the other 28 test files containing the old tom setup:
[5725d81](https://github.com/snieb/MuseScore/commit/5953d285e2ad7edf62b864112372007df5c5fcd6)
Should I add this to the PR, or is this more likely to do harm than good?
_vtest_ seems to have [reported failures without them.](https://github.com/musescore/MuseScore/runs/589886951?check_suite_focus=true)
Currently compiling & trying to test on my machine.

**Comment by Jojo-Schmitz** [comment]
I'd leave it at the current status

**Comment by Jojo-Schmitz** [comment]
Rebase needed, maybe on top of 3.x (first)?

**Comment by RomanPudashkin** [comment]
Unfortunately, this PR cannot be merged since it's based on the MS3 code structure. Please reopen if you are ready to make an updated version of this fix

**Comment by Jojo-Schmitz** [comment]
It is part of my 3.x branch/fork since quite long though

**Pull request closed without merging**
