### PR TITLE
[MU4] Fix #313857: Fractional font sizes can't be input using the "Preferences" dialog

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: https://musescore.org/en/node/313857

This is the #7000 version for master, albeit pretty much untested, as the UI for preferences is... rather rough at the edges to put it very mildly

### CODE REVIEW

**Comment by RomanPudashkin** [comment]
I think, better to delay this fix. Recently I have made the fonts theme by the design of the design team
https://github.com/musescore/MuseScore/pull/6984

It will help to fix our "fonts hell" in qml. Also, we want to find the best way to make fonts the same on all platforms. Probably we will switch the fonts theme to using points, but we need some time to find a suitable configuration for this

**Comment by Jojo-Schmitz** [comment]
Yes, I don't think this one is really ready for merge, just wanted to prevent it getting forgotten

**Comment by RobFog** [comment]
Maybe this should be made a draft then?

**Comment by Jojo-Schmitz** [comment]
done

**Comment by Jojo-Schmitz** [comment]
note to self: rebase needed

**Pull request closed without merging**
