### PR TITLE
Fix #52106: fails to compile with -DUSE_SYSTEM_QTSINGLEAPPLICATION=ON

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by BrunoVernay** [comment]
I guess some distro uses:
-  `QtSolutions` and `QtSolutions_SingleApplication-2.6`
- and other `Qt5/QtSolutions` and  `Qt5Solutions_SingleApplication-2.6`

Hopefully not a mix of the 2 :-) that would make quite a combination.    
You would like to make variable like `USE_PATH_WITH_EXPLICIT_QT_VERSION` ?  or `RPM_STYLE_INSTALL` ??

**Comment by Jojo-Schmitz** [comment]
Like this?

**Comment by BrunoVernay** [comment]
That was super reactive! But beware, it may only be the 3rd Qt app I build  and I am **not** an official package maintainer!   
To me anything that work is OK.  If it can be re-used across distro: excellent!   
But I did not put too much though in the `USE_PATH_WITH_EXPLICIT_QT_VERSION` term ...

**Comment by Jojo-Schmitz** [comment]
I don't think CI builds them, surely nor all

**Comment by lasconic** [comment]
Nope, the CI builds a single one, the default one...

**Pull request merged**
