### PR TITLE
Fix rendering of non-square icons on hidpi displays

### PR DESCRIPTION
**Pull request by nezticle**
Due to some questionable logic in Qt regarding the drawing of SVG based
QIcons, we can take advantage of the custom icon engine in MuseScore to
make sure that SVG icons are always rendered to the size requested.

The problem was when we request a non-square icon to be drawn, and the
size needs to be adjusted to maintain aspect ratio, and the screen
displaying the icon has a devicePixelRatio != 1, then the QPixmap
storing the QIcon will have it's devicePixelRatio set to a non-integer
value which is known (and expected) to have rendering artifacts.  By
always returning the requested size of pixmap for an icon, the device
pixel ratio of the pixmap will be the same of the screen the window is
on.

### CODE REVIEW

**Comment by lasconic** [comment]
Thank you for the fix and welcome in the MuseScore contributor community! Looking forward for your next PR! 

For the record, here is before (top) and after (bottom) on Mac book pro retina. The UI will be a lot nicer!

capture d ecran 2016-09-08 11 09 19

**Comment by Jojo-Schmitz** [comment]
Just a hint for your next PR: don't use your master branch, but create a topic branch instead. It can take a while for a PR to get merged, and during that time you can't do much with your master branch.

**Comment by thomasbonte** [comment]
W00t! Thanks @nezticle :)

**Comment by Jojo-Schmitz** [comment]
Shouldn't this make it into the 2.0.4 branch too?

**Comment by lasconic** [comment]
Sure, see https://github.com/musescore/MuseScore/commits/2.0.4

**Comment by Jojo-Schmitz** [comment]
oops, sorry for the noise

**Pull request merged**
