### PR TITLE
fix MSVC/MinGW compiler warnings

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
done

**Comment by Jojo-Schmitz** [comment]
More warnings corpped up and got fixed.
Also trying to fix mtests

**Comment by eplanet** [comment]
Why isn't that PR merged yet?

**Comment by Jojo-Schmitz** [comment]
That in turn is a question for @anatoly-os ;-)

**Pull request merged**
