### PR TITLE
Refactor VTests to build reference and current in parallel

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Oops, I planned to test this on my own fork first...

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Maybe, while at it, also only upload the "compare" part of all the images? That's what the vtests in 3.x do and IMHO is sufficient. Less space needed, less time to download and check. None ideally (if no diffs)

**Comment by igorkorsukov** [comment]
@cbjeukendrup Would you please also rename the artifact, like in executable builds

**Comment by Jojo-Schmitz** [comment]
"Artifact name: , is incorrectly provided" ?

**Comment by cbjeukendrup** [comment]
Still not there yet... 😞

**Comment by cbjeukendrup** [comment]
Finally! 
@igorkorsukov If you confirm that it works as it should when the VTests are failing, I will remove the topmost commit and then this should be ready for merge!

**Comment by igorkorsukov** [comment]
> Finally! @igorkorsukov you can see here how it works if the VTests are failing: https://github.com/musescore/MuseScore/actions/runs/1550456992
> 
> And here how it works if they are succeeding: https://github.com/musescore/MuseScore/actions/runs/1550651602
> 
> I think this is ready for merge now!

Excellent!!

**Comment by cbjeukendrup** [comment]
So now, I'm also a CI Engineer! 🥳

**Pull request merged**
