### PR TITLE
Inspector UI improvments, homogenize, add buddies

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
@Jojo-Schmitz, any opinion on [this](https://github.com/musescore/MuseScore/commit/a29a6f2f662363c0bdc22a55b1b1afdd5799e033#commitcomment-20062302)?

**Comment by Jojo-Schmitz** [comment]
There it was just less of a change to remove the colons. Adding them everywhere would be an option too, of course.

**Comment by IsaacWeiss** [comment]
It seems to be a lot more common with.

**Comment by Jojo-Schmitz** [comment]
In inspector it was less common though. Maybe we keep them without colon in 2.x' inspector and have them with in 3.x?

**Comment by IsaacWeiss** [comment]
I like that idea.

**Comment by Jojo-Schmitz** [comment]
The work is done, for 3.0, along with a few more of fhese for other dialogs. I don't think the commits would apply cleanly to 2.0.4, and to be honest I'm too lazy to make a separate one for 2.0.4 ;-)

**Comment by Jojo-Schmitz** [comment]
rebasesd and additionally fixed an accessibility text for a newly added reset button

**Pull request merged**
