### PR TITLE
FIX 269870

### PR DESCRIPTION
**Pull request by sidewayss**
fix #269870

### CODE REVIEW

**Comment by anatoly-os** [comment]
@sidewayss thank you. Should you have time please add few notes to the commit log to explain the idea of changes. Also, you need to change commit message to "fix #269870" to automatically link this PR and the related issue, so the last could be closed automatically once this PR is merged.

**Comment by sidewayss** [comment]
Details on the changes are catalogued in this comment in the MuseScore issue:
https://musescore.org/en/node/269870#comment-835681

That comment was written when the changes were made and tested, in mid-May of this year.

**Comment by sidewayss** [comment]
As I woefully admitted, posting the link to this PR before the checks were complete would backfire.
I have no idea what failed here.  Last time I created a PR, this check did not exist.
Anatoly?

**Comment by anatoly-os** [comment]
@sidewayss everything is good. Compiling, packaging and distributing are ok. We exceeded the available AppVeyor's storage size (1Tb), so this is the issue, not the code in this PR :)

**Comment by sidewayss** [comment]
OK, I assumed that this failure would prevent the travis process from running, and that the whole thing was stuck.
Yes, I read the failure entry in the log.  >100TB is a lot of space to run out of...

**Comment by anatoly-os** [comment]
@sidewayss the builds are independent. 100Gb, btw.

**Comment by sidewayss** [comment]
I this PR the one that broke that limit, or has that been an ongoing issue recently?

**Comment by anatoly-os** [comment]
Ongoing issue for the last week.

**Comment by sidewayss** [comment]
You should let people know prior to asking them to create a PR.  It took me by surprise, and probably wastes your time when the PR creator wonders what's going on, as I am doing now.  Or are there not many PRs this summer?

**Comment by lasconic** [comment]
Merged manually c859eae4cec549ac03f88e6029ad4d6620fcd603 and fixed the commit message. Thank you !

**Pull request closed without merging**
