### PR TITLE
Notify PR authors when merge conflicts arise

### PR DESCRIPTION
**Pull request by Marr11317**
Edit:
The bot does three things: 
1. When merge conflicts appear, it adds the 'merge conflicts' label if it wasn't there before.
2. The same way, it adds a comment:  'Rebase needed'
3. It checks if PRs with the 'merge conflict' are now mergeable. If so, it removes the label.

Limitations:
- There seems to be no way to subscribe to force-push events, which means that when someone rebases and force pushes, this PR will still have the 'merge conflicts' label until the bot is run. The bot runs whenever: 
    - a PR is opened, re-opened, or new commits are added, 
    - new commits are pushed to the master branch.

Maintainers: when merging this commit to master, the label "Merge conflict" has to be added or the action will fail.

Source: https://github.com/marketplace/actions/auto-label-merge-conflicts

### CODE REVIEW

**Comment by Marr11317** [comment]
I am not sure if we want it though.

**Comment by Jojo-Schmitz** [comment]
Does it send notifications to the subscribers too?

**Comment by Marr11317** [comment]
Apparently, labelling doesn't send notifications. :(
I'll see if it's easy enough to modify it to comment "Rebase needed"

**Comment by Jojo-Schmitz** [comment]
That'd be more useful than a label the user can't remove again after rebasing

**Comment by Marr11317** [comment]
Got a working version.

**Comment by Marr11317** [comment]
Added to the commit description:
The bot does three things: 
1. When merge conflicts appear, it adds the 'merge conflicts' label if it wasn't there before.
2. The same way, it adds a comment:  'Rebase needed'
3. It checks if PRs with the 'merge conflict' are now mergeable. If so, it removes the label.

Limitations:
- There seems to be no way to subscribe to force-push events, which means that when someone rebases and force pushes, this PR will still have the 'merge conflicts' label until the bot is run. The bot runs whenever: 
- a PR is opened, re-opened, or new commits are added, 
- new commits are pushed to the master branch.

**Comment by Marr11317** [comment]
@anatoly-os as many things get merged could you please consider reviewing this one?
Since it looks like PRs are being merged (there was 250 just 3 days ago) it might be the right time to check for "rebase needed" checks.

**Comment by vpereverzev** [comment]
I like the idea, but it should be another implementation (musescore bot api, github extensions, etc.)

I'm pretty sure that we just can't use external repositories for that purpose (I mean Marr11317/ConflictAdviser)

**Comment by Marr11317** [comment]
Yes, Marr11317/ConflictAdviser is one of my repo, but I could transfer the ownership to Musescore if that was needed.

**Comment by Marr11317** [comment]
anyway, with the current development, merges are happening often enough that asking people to rebase is not too much of a problem anyway.

**Comment by vpereverzev** [comment]
yes, we now strive to ensure that the review does not hang for a long time, as was the case before in MuseScore

**Pull request closed without merging**
