### PR TITLE
[MU4] Figured bass navigation

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/9709

### CODE REVIEW

**Review by igorkorsukov — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #9709 on Win10, Mac12, LinuxMint 20.2 - FIXED      

Please merge into master

**Comment by emielbeinema** [comment]
In the latest nightly (`202112220437-master-712908a`) on linux navigation through time (i.e. Ctrl + 1..9) now works as expected, but the use of return to stack digits vertically only works in the edit mode and does not appear to be committed.

So this:
image

Results in:
image

I think this worked in previous nightlies. Might something have changed in the handling of this input?

**Comment by RomanPudashkin** [comment]
@emielbeinema 

See this issue:
https://github.com/musescore/MuseScore/issues/10134

**Comment by emielbeinema** [comment]
Ah, of course. Thanks for the response and thanks a lot for your work!

**Pull request merged**
