### PR TITLE
[MU4] Fixes for tabs

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/8198

### CODE REVIEW

**Comment by RomanPudashkin** [comment]
@cbjeukendrup please check this PR

**Comment by cbjeukendrup** [comment]
It's much better now! 
However, I still found an "edge case" (quite literally 😉): when you drag the current tab at the height where the bottom border would be if it is not the selected tab, then still all dock widgets get undocked. Maybe the mouse area is just one pixel too tall?

https://user-images.githubusercontent.com/48658420/120192434-75ba9600-c21b-11eb-9ae4-d79388299fc1.mov

Also, when you hover a non-selected tab, the borders become lighter. I think they shouldn't. 
Schermafbeelding 2021-05-31 om 14 23 16

**Comment by RomanPudashkin** [comment]
@cbjeukendrup thank you for testing! I have fixed the "edge case" but I'll fix separators later because this PR contains really important fixes and I want to merge it first. We  probably need to create a separate issue for the separators bug

**Comment by cbjeukendrup** [comment]
@RomanPudashkin Thanks, it's fixed now! (I tested on macOS.)
I will create a new issue for the separators color bug.

**Review by Eism — APPROVED** [review]

**Pull request merged**
