### PR TITLE
fix #279389: rename timewise delete/input

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
and fix a typo

### CODE REVIEW

**Comment by anatoly-os** [comment]
It is Deleting, not removing a range, no? Removing is something we do with Del, but deleting is what we do with Cmd+Del.

**Comment by Jojo-Schmitz** [comment]
remove, delete, erase, empty not really sure which is what and when

There's (to) empty or erase (like using an erasor/rubber, leaving the staves, measures, barlines) using Del, which is named after "delete" and then there is remove, cut out like with a scissor, like when using the Ctrl+Del, "Remove selected range" found several fans in the issue

**Comment by shoogle** [comment]
I like "remove" because it is opposite to "add" or "insert". These are powerful actions that will only be used occasionally when it is necessary to alter the length of a measure. "Delete" is a more everyday word, suitable for the everyday action of replacing some notes with rests.

**Comment by IsaacWeiss** [comment]
But it's also for deleting a measure, which is much more common...

**Comment by shoogle** [comment]
Yes, but I think that should be renamed "remove measure" for consistency, as "delete" should be strictly reserved for the simple case of replacing contents with rests.

To put it another way, if a new user searches online for "how do I delete a selection in MuseScore", do you want normal delete or timewise delete to appear first in the list of results? Much safer to call timewise delete "remove" in my opinion.

**Comment by Jojo-Schmitz** [comment]
There is "Remove Empty Trailing Measures" -> perfect match to "Remove Selected Range" in wording and function. There is no "Delete measure" (anymore).

Alsi I'm not sure discussing this here rather than in https://musescore.org/en/node/279389 is really helpful? There the discussion is dragging on since quite a wule and "Remove Selected Range" seems to have been the consensus

**Comment by Jojo-Schmitz** [comment]
There is "Delete Selected Measures", This is really more like "Empty selected measures", isn't it?

**Comment by Jojo-Schmitz** [comment]
Actually "Delete Selected Measures" really is "Empty selected range". It is not just working on measures

**Comment by Jojo-Schmitz** [comment]
Hmm, no, "Delete", the Del key/shortcut, is working on a selection but "Delete Selected Measures" on measures only.

**Comment by Jojo-Schmitz** [comment]
No! "Delete Selected Measures" actually removes them, same as "Timewise delete", just restricted on whole measures. So we better change that5 string too, to "Remove Selected Measures"

**Comment by anatoly-os** [comment]
Let's discuss and maybe revise it at FOSDEM ;)

**Comment by Jojo-Schmitz** [comment]
We als need to take care of https://musescore.org/en/node/283033 and https://musescore.org/en/node/283140, in addition to https://musescore.org/en/node/279389.
Selectins a sinle notw/rest os a range selection and then right clicking in to the staff outside that selection enables that delete selected meaasure menu but really does a timewise delete

**Comment by Jojo-Schmitz** [comment]
I know we discussed this in Saturday even at FOSDEM, but I don't recall the outcome.
Anyone out there to refresh my mind?
We really should have this done for 3.0.3

**Comment by Jojo-Schmitz** [comment]
What about this for 3.1?

**Pull request merged**
