### PR TITLE
Fix initial positioning of element edit popups (harp pedal, capo, ...)

### PR DESCRIPTION
**Pull request by cbjeukendrup**
This issue came up for the first time in https://github.com/musescore/MuseScore/pull/17904#issuecomment-1587930434, and our GSoC contributor discovered it in more extreme forms while working on #18436

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by zacjansheski** [comment]
Might be causing an issue with the harp diagram (unless this is related to some other work going on)

https://github.com/musescore/MuseScore/assets/69917893/4985e2b7-90b8-49dd-ab37-af44d1222934

**Comment by cbjeukendrup** [comment]
Do you mean that in the old version, the initial position of the harp diagram was better than the position after editing something, and that the new version uses the latter instead of the former?
It seems almost a coincidence that the initial position in the old version looked good, because the logic in the code looks a bit weird to me. I'll take a look.

**Comment by zacjansheski** [comment]
The ticked radio buttons don't appear on these checks.  (MacOS)

**Comment by cbjeukendrup** [comment]
Oh wow, I hadn't even noticed that. Fixed now! And fixed/improved the positioning logic too (when opening upward, the popup will now appear either above the element or above the staff, whatever is higher; when opening downward, the popup will now appear either below the element or below the staff, whatever is lower).

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11

Approved

**Pull request merged**
