### PR TITLE
ove files import fixes; initial implementation of mtests for ove files

### PR DESCRIPTION
**Pull request by AntonioBL**

### CODE REVIEW

**Comment by lasconic** [comment]
Awesome! Did you manage to get a copy of overture?

**Comment by AntonioBL** [comment]
I checked against the demo version of Overture software. I will go throguh each file of the old test suite and verify if they correspond to the output of the Overture Demo.
Let's see if this automatic tests work (I had to rebase a few times today and I didn't update the reference files)... Fingers crossed...

**Comment by steveschow** [comment]
Overture5 is coming out any day now....  FYI  Supposedly a major rewrite.  There is probably some file format changes coming...

**Comment by lasconic** [comment]
Cool ! I hope it will get MusicXML export!

**Comment by AntonioBL** [comment]
One of the most recent commits changed the way dotted rests are stored in mscx files (i.e. no more "dot" tag, but a tag with numerator and denominator durations; for dotted notes the behavior is unchanged). That's why the tests were failing.
I also commented out the test for transposing instrument, which was not actually creating a transposing instrument (more investigation needed).

**Comment by AntonioBL** [comment]
To be more precise: the strange dotted rests happen only for ove import. It is probably a side-effect of the commit which fixed the import of full-measure rests [ and a set of working tests would have highlighted this side-effect :-) ].

**Comment by lasconic** [comment]
Exactly :) That's why I call your endeavor awesome!

**Comment by AntonioBL** [comment]
The file is https://github.com/musescore/MuseScore/blob/master/test/testoves/bdat/note-clef.ove
which contains a couple of dotted eighth rests.

**Comment by lasconic** [comment]
Thank you. Fixed in https://github.com/musescore/MuseScore/commit/1cd15c5c7d3ad0f8f1b2fa453684d45c03c85d1a

**Pull request merged**
