### PR TITLE
Check staff move validity when cloning staves

### PR DESCRIPTION
**Pull request by miiizen**
Resolves: #20272 
I could also cause the crash without the slur, just the cross staff note in master but not the latest 4.2 build.

The second commit fixes the below problems:
- The crash detailed below
- Allows chords to have different staffMove values from their linked chords.  Chords cannot be moved from original staves to linked staves and vice versa
- A crash occurring when moving a stave with a chord moved to the the stave above to the top position in a score.
- A bug causing chords to get stuck in their moved position by:
    1. moving a chord to the stave above/below
    2. hiding the stave the chord has been moved to
    3. unhiding the stave
    4. try to move the chord back to its original position

I've also added some tests

### CODE REVIEW

**Comment by oktophonie** [comment]
What is even the expected behaviour with linked staves here?

Creating a linked stave for the treble here:
image

results in
image

i.e. the cross-staved notes return to their origin staves. In the case of the new linked stave all the notes obviously have to be rendered on that stave, but it shouldn't preclude cross-staving above. If I attempt to reshift the last note to the bass stave (with this PR) it crashes again, currently.

In the absence of any sensible use case for this rather niche situation we don't need to overthink the behaviour, but it's safe to say that it shouldn't crash whatever happens :)

**Comment by zacjansheski** [comment]
I think in the example above, the original cross stave note should remain cross stave and the new linked stave should be as it appears in the image.

I hit the crash when taking a piano score, changing instrument to guitar, and making a linked staves for treble and bass clefs.  Not a common thing to do and there is a more proper way to do it of course :)

**Review by oktophonie — APPROVED** [review]

**Review by oktophonie — APPROVED** [review]

**Comment by zacjansheski** [comment]
I still get a crash when I make a linked stave with this score.  Maybe there is an additional (but hopefully similar) issue there?

[Beethoven__Movement III_Piano_Sonata_No._14__Moonlight.mscz.zip](https://github.com/musescore/MuseScore/files/13907303/Beethoven__Movement.III_Piano_Sonata_No._14__Moonlight.mscz.zip)

**Comment by zacjansheski** [comment]
[BeethovenLinkedCrash.zip](https://github.com/musescore/MuseScore/files/13907321/BeethovenLinkedCrash.zip)

**Comment by miiizen** [comment]
@zacjansheski the problem was with cross staff grace notes and ornament cue notes - should be resolved now!

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/20272 FIXED

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
