### PR TITLE
Fix #7864: Renaming Inspector to Properties

### LINKED ISSUE #7864: [MU4 Issue] rename the Inspector to 'Properties'
**Describe the bug**
rename the "Inspector" tab (from the instruments panel) to 'Properties'

2021-04-02 04_13_40-MuseScore 4

### PR DESCRIPTION
**Pull request by apricot2012**
Renamed Inspector Panel to "Properties"

Resolves: *https://github.com/musescore/MuseScore/issues/7864*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by RobFog** [comment]
"naming" should be "renaming"?

**Comment by Howard-C** [comment]
So internally the code still refers to the widget as the "inspector", but the UI text is changed to "properties"?

**Comment by apricot2012** [comment]
> So internally the code still refers to the widget as the "inspector", but the UI text is changed to "properties"?

Hmm... should everything be refactored then? I've noticed there are currently multiple references to inspector in the UI as well.

**Comment by Howard-C** [comment]
> > So internally the code still refers to the widget as the "inspector", but the UI text is changed to "properties"?
> 
> Hmm... should everything be refactored then? I've noticed there are currently multiple references to inspector in the UI as well.

If UI alone has other references to the inspector, then they would definitely need to be changed as well.

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
