### PR TITLE
'Musical Symbols Scale' for markers

### PR DESCRIPTION
**Pull request by XiaoMigros**
Resolves: #21757

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by XiaoMigros** [comment]
I wonder if it's possible to check for `Sid::dummyMusicalSymbolsScale` being used, rather than to use a chain of ORs...

**Review by oktophonie — APPROVED** [review]

**Review by mike-spa — APPROVED** [review]

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
In the VTests, it looks like this has an undesired effect for existing scores (it makes those symbols much larger). Maybe some compat code is necessary to reset things in pre-4.4 scores?

**Comment by XiaoMigros** [comment]
In #20934 there were similar consequences (notably for pedal markings), but last time discussing with @oktophonie the conclusion was made that the symbols should now use their 'true' size, regardless of context.

**Comment by cbjeukendrup** [comment]
I tested it and found that the look of existing scores is indeed affected, but in such way that these scores look the same as when you'd create a new score in this PR's build. So that does make sense to me :)

**Pull request merged**
