### PR TITLE
fix accessibility info for the new 'Z' setting

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I have the feeling that `Z' is not a really good name for this in the UI though, and if. wy may want to prevent it from  getting translated?
'Layer' might be better, but is used elsewhere for something entirely different.
How about 'Stacking order'? Any other clever ideas?

**Comment by Jojo-Schmitz** [comment]
Or "Z-Index"

**Comment by lasconic** [comment]
I like "Stacking order"

**Comment by Jojo-Schmitz** [comment]
OK, here we go

**Comment by Jojo-Schmitz** [comment]
Maybe 'Z-Index' as a tooltip?

**Pull request merged**
