### PR TITLE
msvc_build.bat should allow spaces in the full path

### PR DESCRIPTION
**Pull request by jeetee**
not tested here, as I don't have a dev env set up; but this should do the trick

### CODE REVIEW

**Comment by anatoly-os** [comment]
@jeetee what was the purpose of this PR? Some changes are strange, some enable echo where I wanted to avoid excessive output, some actually allow spaces in the path.

**Comment by jeetee** [comment]
The PR indeed does 2 things.

First it fixes the build and architecture strings to have proper escaping; this was done in hopes that it would also fix string escaping in the VS build for the issues @jthistle was having (but it doesn't fix those).

Secondly it minimizes the output to what should still be enough (there isn't any value in echo'ing the echo command your going to execute only to then see it echo the exact thing already in the command being echo'd itself).

Compare running the "old" batch file on a system without build environment:

> C:\Users\jt\Documents\MuseScore_git>msvc_build-original.bat debug
> 
> C:\Users\jt\Documents\MuseScore_git>echo "Build forlder is: "msvc.build"_"x64""
> 
> "Build forlder is: "msvc.build"_"x64""
> 
> C:\Users\jt\Documents\MuseScore_git>echo "Install forlder is: "msvc.install"_"x6
> 4""
> "Install forlder is: "msvc.install"_"x64""
> 
> C:\Users\jt\Documents\MuseScore_git>echo "Building CMake configuration..."
> "Building CMake configuration..."
> CMake Error: Could not create named generator Visual Studio 15 2017 Win64
> 
> Generators
>   Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
>                                  Optional [arch] can be "Win64" or "ARM".
>   Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
>                                  Optional [arch] can be "Win64" or "ARM".
>   Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
>                                  Optional [arch] can be "Win64" or "ARM".
>   Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
>                                  Optional [arch] can be "Win64" or "IA64".
>   Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
>                                  Optional [arch] can be "Win64" or "IA64".
>   Visual Studio 8 2005 [arch]  = Generates Visual Studio 2005 project files.
>                                  Optional [arch] can be "Win64".
>   Visual Studio 7 .NET 2003    = Generates Visual Studio .NET 2003 project
>                                  files.
>   Visual Studio 7              = Deprecated.  Generates Visual Studio .NET
>                                  2002 project files.
>   Visual Studio 6              = Deprecated.  Generates Visual Studio 6
>                                  project files.
>   Borland Makefiles            = Generates Borland makefiles.
>   NMake Makefiles              = Generates NMake makefiles.
>   NMake Makefiles JOM          = Generates JOM makefiles.
>   Green Hills MULTI            = Generates Green Hills MULTI files
>                                  (experimental, work-in-progress).
>   MSYS Makefiles               = Generates MSYS makefiles.
>   MinGW Makefiles              = Generates a make file for use with
>                                  mingw32-make.
>   Unix Makefiles               = Generates standard UNIX makefiles.
>   Ninja                        = Generates build.ninja files.
>   Watcom WMake                 = Generates Watcom WMake makefiles.
>   CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
>   CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
>   CodeBlocks - Ninja           = Generates CodeBlocks project files.
>   CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
>   CodeLite - MinGW Makefiles   = Generates CodeLite project files.
>   CodeLite - NMake Makefiles   = Generates CodeLite project files.
>   CodeLite - Ninja             = Generates CodeLite project files.
>   CodeLite - Unix Makefiles    = Generates CodeLite project files.
>   Eclipse CDT4 - MinGW Makefiles
>                                = Generates Eclipse CDT 4.0 project files.
>   Eclipse CDT4 - NMake Makefiles
>                                = Generates Eclipse CDT 4.0 project files.
>   Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
>   Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
>   Kate - MinGW Makefiles       = Generates Kate project files.
>   Kate - NMake Makefiles       = Generates Kate project files.
>   Kate - Ninja                 = Generates Kate project files.
>   Kate - Unix Makefiles        = Generates Kate project files.
>   Sublime Text 2 - MinGW Makefiles
>                                = Generates Sublime Text 2 project files.
>   Sublime Text 2 - NMake Makefiles
>                                = Generates Sublime Text 2 project files.
>   Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
>   Sublime Text 2 - Unix Makefiles
>                                = Generates Sublime Text 2 project files.
> 
> 
> C:\Users\jt\Documents\MuseScore_git\msvc.build_x64>echo "Running lrelease..."
> "Running lrelease..."
> Error: could not load cache
> 
> C:\Users\jt\Documents\MuseScore_git\msvc.build_x64>echo "Building MuseScore..."
> 
> "Building MuseScore..."
> The system cannot find the path specified.
> Error: could not load cache
> 
> C:\Users\jt\Documents\MuseScore_git\msvc.build_x64>

Versus the output given by the .bat from this PR:

> C:\Users\jt\Documents\MuseScore_git>msvc_build.bat debug
> Build folder is: msvc.build_x64
> Install folder is: msvc.install_x64
> Building CMake configuration...
> CMake Error: Could not create named generator Visual Studio 15 2017 Win64
> 
> Generators
>   Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
>                                  Optional [arch] can be "Win64" or "ARM".
>   Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
>                                  Optional [arch] can be "Win64" or "ARM".
>   Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
>                                  Optional [arch] can be "Win64" or "ARM".
>   Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
>                                  Optional [arch] can be "Win64" or "IA64".
>   Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
>                                  Optional [arch] can be "Win64" or "IA64".
>   Visual Studio 8 2005 [arch]  = Generates Visual Studio 2005 project files.
>                                  Optional [arch] can be "Win64".
>   Visual Studio 7 .NET 2003    = Generates Visual Studio .NET 2003 project
>                                  files.
>   Visual Studio 7              = Deprecated.  Generates Visual Studio .NET
>                                  2002 project files.
>   Visual Studio 6              = Deprecated.  Generates Visual Studio 6
>                                  project files.
>   Borland Makefiles            = Generates Borland makefiles.
>   NMake Makefiles              = Generates NMake makefiles.
>   NMake Makefiles JOM          = Generates JOM makefiles.
>   Green Hills MULTI            = Generates Green Hills MULTI files
>                                  (experimental, work-in-progress).
>   MSYS Makefiles               = Generates MSYS makefiles.
>   MinGW Makefiles              = Generates a make file for use with
>                                  mingw32-make.
>   Unix Makefiles               = Generates standard UNIX makefiles.
>   Ninja                        = Generates build.ninja files.
>   Watcom WMake                 = Generates Watcom WMake makefiles.
>   CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
>   CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
>   CodeBlocks - Ninja           = Generates CodeBlocks project files.
>   CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
>   CodeLite - MinGW Makefiles   = Generates CodeLite project files.
>   CodeLite - NMake Makefiles   = Generates CodeLite project files.
>   CodeLite - Ninja             = Generates CodeLite project files.
>   CodeLite - Unix Makefiles    = Generates CodeLite project files.
>   Eclipse CDT4 - MinGW Makefiles
>                                = Generates Eclipse CDT 4.0 project files.
>   Eclipse CDT4 - NMake Makefiles
>                                = Generates Eclipse CDT 4.0 project files.
>   Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
>   Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
>   Kate - MinGW Makefiles       = Generates Kate project files.
>   Kate - NMake Makefiles       = Generates Kate project files.
>   Kate - Ninja                 = Generates Kate project files.
>   Kate - Unix Makefiles        = Generates Kate project files.
>   Sublime Text 2 - MinGW Makefiles
>                                = Generates Sublime Text 2 project files.
>   Sublime Text 2 - NMake Makefiles
>                                = Generates Sublime Text 2 project files.
>   Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
>   Sublime Text 2 - Unix Makefiles
>                                = Generates Sublime Text 2 project files.
> 
> Running lrelease...
> Error: could not load cache
> Building MuseScore...
> Error: could not load cache
> 
> C:\Users\jt\Documents\MuseScore_git\msvc.build_x64>


As it doesn't fix the original issue, it's not an urgent PR at all; still it's a small improvement and future proofing of the script.

**Comment by jthistle** [comment]
I don't think it was me having any issues, I build on Linux ;)

**Comment by Jojo-Schmitz** [comment]
It was Michael Froelich, probably @michaelf87

**Comment by L0uisc** [comment]
@jeetee will this PR conflict with mine Jojo linked above?

**Comment by jeetee** [comment]
Quite honestly I'd forgotten all about this PR.
As I'd have to rebase and resolve conflicts anyway, I'm happy with them first merging yours @L0uisc  and only review this one afterwards (if it would still be required).

Also feel free to include the "allow spaces" part into your PR and then we'll just close and remove this one.

**Comment by Jojo-Schmitz** [comment]
this here needs a rebase anyhow

**Comment by L0uisc** [comment]
I added the escaping in my PR (#4983). Review will be appreciated!

**Comment by jeetee** [comment]
superseded by #4983; closing

**Pull request closed without merging**
