### PR TITLE
style_dialog_optimization

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/13193
Resolves: https://github.com/musescore/MuseScore/issues/13104
Resolves: https://github.com/musescore/MuseScore/issues/17060

Caused by https://github.com/musescore/MuseScore/pull/9639/commits/dca87eb256ed5a5af7a3bd2630f85ca5f0aecd32

### CODE REVIEW

**Review by cbjeukendrup — APPROVED** [review]
This solution seems good to me; especially since those QDialog dialogs will be replaced by QML at some point, I think we shouldn't spend too much time on them.

However, I do wonder why it was no problem in MS3. There, nothing was done about disabling accessibility. Do you have any idea about that? 
And might there be a way to apply this fix for other dialogs automatically too, like detecting whether an event comes from a dialog that is not opened yet? (Probably not necessary though, because the style dialog is by far the biggest one, so the problem is probably not significant for other dialogs)

**Comment by RomanPudashkin** [comment]
> However, I do wonder why it was no problem in MS3. There, nothing was done about disabling accessibility. Do you have any idea about that?

This is most likely a consequence of the fact that we are using our custom accessibility root object (see AccessibilityController::init()) and the default is QApplication (which was used in MS3)

> And might there be a way to apply this fix for other dialogs automatically too, like detecting whether an event comes from a dialog that is not opened yet? (Probably not necessary though, because the style dialog is by far the biggest one, so the problem is probably not significant for other dialogs)

I'm leaning toward not applying this fix to other dialogs for now. Implementing automatic detection of whether events need to be ignored would be quite problematic (especially because we have to start ignoring them before calling setupUi)

**Comment by Jojo-Schmitz** [comment]
I can confirm that this PR fixes the issue for me, similar to the earlier change one you asked be to test, but as far as I can tell without the bad side effects on accessibilty

**Comment by MarcSabatella** [comment]
If we were to investigate using this elsewhere, there are three places in particular where people have reported issues with lag and it *might* turn out to be for the same reason:

1. Preferences dialog - see https://github.com/musescore/MuseScore/issues/13193#issuecomment-1442550402
2. Palette search - see https://github.com/musescore/MuseScore/issues/12753.
3. Properties panel - see https://github.com/musescore/MuseScore/issues/14383

I also wonder if explicitly disabling accessibility might be a workaround for now (obviously, not for screen reader users).  But I only know how to do that on Linux, and I don't experience the issue there.

**Pull request merged**
