### PR TITLE
fix #61041: allow staff spacers to decrease distance

### PR DESCRIPTION
**Pull request by MarcSabatella**
This replaces #2147, which I had to close to a messing up a rebase operation.  It's the exact same code, just rebased and squashed, so all comments there still apply.

### CODE REVIEW

**Comment by lasconic** [comment]
See https://musescore.org/en/node/85026

As explained there, spatium are really a measure element. Adding a "negative spatium" goes against this logic and so it's not a good solution for the problem at hand. As @MarcSabatella said in the issue discussion there are probably other way to deal with the problem, a better algorithm to space systems for example.

**Comment by MarcSabatella** [comment]
Hmm, my change does not involve negative spatium at all.  Maybe that wasn't clear.  It simply allows small values to work.  So a spacer with a size of 3sp will actually result in 3sp worth of space.

However, it is true I don't handle spacers up in this way, and maybe I'd need to.  One way or another, though, I think this is a crucial feature, and I don't want to see it abandoned.  There needs to be a way to have two given staves or systems closer together than the nominal value.  And I don't see why spacers cannot be that mechanism, but I'm open to other suggestions.

**Comment by MarcSabatella** [comment]
I'm guessing the failure in the album test is related to the other album changes made recently?

Regarding the overall design/implementation of "absolute" spacers in my PR:

I am using the term "absolute" spacer as opposed to "negative", because there are not actually negative numbers involved.  As mentioned above, it's just that the height of the spacer is honored absolutely - so a 3sp spacer reduces the space to 3sp just as 30sp increase it to 30sp.  However, this does mean that these are not compatible in some sense with current spacers in that with current spacers, you can have several and the largest wins.  With an absolute spacer, the behavior is undefined if you have more than one in the same system.  Currently I think the last wins, or maybe the first - I forget.

What this suggests to me is that we probably should have both the current sapcers and the new absolute spacer on the palette, so you only get the new behavior if you ask for it by using the new absolute spacer.  And I should consider also allowing an absolute spacer up, although the logic that explains why we have spacers up now doesn't really really apply to absolute spacers, so I'm not considering it a must.

Anyhow, I should update the PR to make a new palette icon for the absolute spacer.

**Comment by Jojo-Schmitz** [comment]
rebase needed...

**Comment by Jojo-Schmitz** [comment]
rebase neded

**Comment by rowild** [comment]
+1
Would love to see that feature!

**Comment by Jojo-Schmitz** [comment]
Is this PR still needed, now that we do have fixed spaced since 2b44d04?

**Comment by lasconic** [comment]
Indeed, see https://musescore.org/en/node/137651

**Pull request closed without merging**
