### PR TITLE
Remove the NoteLine element

### PR DESCRIPTION
**Pull request by miiizen**
This may be a little drastic, but as far as I could tell this class has never been used in a release.  The note anchored lines in Add > Lines > Note anchored line have simply been a textbase line with its `anchor` property set to `Spanner::Anchor::Note` (introduced in https://github.com/musescore/MuseScore/commit/0df85cb1d071252ef71f965a7fb54f2f5e3aac23).  
This action briefly created a NoteLine element (https://github.com/musescore/MuseScore/commit/a7904c31f5584955805477ed67da062ad21ea78d) until this was reverted less than a month later (https://github.com/musescore/MuseScore/commit/ee4b4ea5545411817ff9dbaa8844208a903f4126).  This happened June-July 2013, after the release of 1.3 (Feb) and before the release of 2.0 (2015).

If anyone has objections, let me know!

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Just to clarify: this is not about removing the note acnhored line, right?
(Note anchored lines are pretty much the best kept secret in MuseScore, and have been ever since, seems about time to make them known to the workd ;-))

**Comment by Jojo-Schmitz** [comment]
I can't find any ill effect of this removal

**Comment by MarcSabatella** [comment]
Note anchored lines are definitely very under the radar indeed but it seems they are not connected to these NoteLine elements.  I have vague sense they might have been envisioned as a way of implementing guitar slides, but that’s more of a guess than a memory.

Anyhow, no objection from me FWIW.

**Comment by miiizen** [comment]
No, in fact note anchored lines have had their own improvements here: https://github.com/musescore/MuseScore/pull/24992

**Review by mike-spa — APPROVED** [review]
Thanks for the cleanup!

**Pull request merged**
