### PR TITLE
Fix some issues of the fret diagram inspector

### PR DESCRIPTION
**Pull request by Howard-C**
1) Draw the fret diagram on the inspector using `fontPrimaryColor` (from #8498)
2) Make the hover event on the fret diagram work again

### CODE REVIEW

**Comment by Tantacrul** [comment]
Excellent work on the UI.

The second problem is clearly an interaction issue. Observing the changes you make in realtime, help you to recognise how the interaction works, and removes all doubt,

If you do not get an immediate update, the natural assumption is that something isn't working. All Inspector interactions should take effect immediately unless their is an 'apply' button (which there isn't at present)

**Comment by Howard-C** [comment]
I understand, but I'm afraid the issue is not with the inspector, because this part of the code is largely copied from 3.x, where it works fine, and my test does show a change to how scores are _supposed_ to be layout, so I guess it's a problem with how or when the score is refreshed, from other parts of the new 4.0 code. I'll try more later.

**Comment by Eism** [comment]
@Howard-C 
1. To update the data immediately in the notation, you should notify about data changing in the notation(globalContext()->currentNotation()->notationChanged().notify();  in mousePressEvent method)
Also please replace the calling m_diagram->score()->startCmd(); to calling globalContext()->currentNotation()->undoStack()->prepareChanges();
It needs for undo/redo changing

2. To update the color immediately, add an update method to setColor method
The color is set correctly, but QQuickPaintedItem does not know about these changes for repainting

**Comment by Howard-C** [comment]
@Eism Done! Thanks for the pointers.

**Review by Eism — APPROVED** [review]

**Pull request merged**
