### PR TITLE
Fix #12864: fix crashes when there is no staff

### LINKED ISSUE #12864: [MU4 Issue] Crash when deleting staff from single-staff instrument/template
**Describe the bug**
When using Simple template score crashes after deleting its single staff (video 1)
When using any single-staff instrument score crashes after deleting it's single staff and clicking Add Staff button (video 2)

**Expected behavior**
No crash during any action with instruments

**Screenshots**
Video 1

https://user-images.githubusercontent.com/101250347/184632336-678a8799-85c8-4bd8-9546-bff337dcb289.mov

Video 2

https://user-images.githubusercontent.com/101250347/184632356-0abed7e3-ffcd-4eb4-a159-f3aa9bd6d9c9.mov

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

### PR DESCRIPTION
**Pull request by martin-danhier**
Resolves: #12864 

Hello,

There were various places where the code tried to access a staff even if there were none. I added additional checks to prevent this.
Now it works as intended:

https://user-images.githubusercontent.com/36641081/184849252-f43563b0-7f50-48d6-8e82-2e1b2a9dc342.mp4

Have a good day,
Martin

### CODE REVIEW

**Comment by RomanPudashkin** [comment]
@Tantacrul what do you think about disabling the ability to remove ALL staves from a selected instrument (to avoid having instruments without staves)? The user will be able to remove all instruments from the score though. This would greatly reduce the number of such bugs and simplify the implementation of the instrument panel

**Comment by Tantacrul** [comment]
> @Tantacrul what do you think about disabling the ability to remove ALL staves from a selected instrument (to avoid having instruments without staves)? The user will be able to remove all instruments from the score though. This would greatly reduce the number of such bugs and simplify the implementation of the instrument panel

Completely agree. I did not realise users were able to do this actually!

**Comment by martin-danhier** [comment]
Yeah, it would make more sense. I can look into it if you want!

**Comment by martin-danhier** [comment]
@RomanPudashkin @Tantacrul 

I modified the instrument panel to disallow deleting the last staff of an instrument.
I didn't remove the initial fix, because without it there could still be crashes when staves are reordered then deleted.

https://user-images.githubusercontent.com/36641081/184870338-f3bc9fe6-21b3-4f69-92e0-28e191e9b698.mp4

---

However, there still are many problems with scores without any instruments, as mentioned in #11909 #12465 #12466.
Also, when loading an empty score, the score will be completely blank and nothing will work at all (I will report it later if I don't find an existing report for it):

https://user-images.githubusercontent.com/36641081/184871347-1dec4477-82af-4ca7-ab70-088dcd1ca903.mp4

Should I extend the modification and disallow removing the last instrument as well ?

**Comment by RomanPudashkin** [comment]
Thank you for your help! I have prepared a better solution in terms of reliability and ease of maintenance
https://github.com/musescore/MuseScore/pull/12891

**Pull request closed without merging**
