### PR TITLE
[TEMP] Diff 3.5.1 - 3.x

### PR DESCRIPTION
**Pull request by igorkorsukov**
Diff 3.5.1 - 3.x

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
oops, merge conflict, 1st and 4th commit is not good for 3.x

**Comment by Jojo-Schmitz** [comment]
#6637 might be better

**Comment by igorkorsukov** [comment]
> #6637 might be better

Yes! I was going to manually make the same PR.
Thank you for making it!

**Comment by Jojo-Schmitz** [comment]
has be WIP since yesterday ;-)

**Pull request closed without merging**
