### PR TITLE
fix some compiler warnings

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
not dealing with those where the code suggests that there are TODOs and those are too far away to immediatelly spot them

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
After #1000 and #2000 now also #3000 from me ;-)

**Comment by lasconic** [comment]
#4000 is waiting for you

**Comment by Jojo-Schmitz** [comment]
I'll do my best ;-)

**Comment by Jojo-Schmitz** [comment]
And I just did it, #4000 is mine too ;-)

**Pull request merged**
