### PR TITLE
Default shortcuts for next-element and prev-element

### PR DESCRIPTION
**Pull request by divya-urs**
This adds default shortcuts Alt+Right for next-element and Alt+Left for prev-element.

### CODE REVIEW

**Comment by lasconic** [comment]
I believe we didn't use alt+left and alt+right as default shortcuts because they were default system shortcut on some configuration (was it mac or linux?). Anyone remember this? @Jojo-Schmitz @MarcSabatella

**Comment by divya-urs** [comment]
These shortcuts (Alt+left, Alt+right) were suggested by @shoogle.

**Comment by Jojo-Schmitz** [comment]
I don't recall. Might well be Linux.

**Comment by lasconic** [comment]
Ok. Let's try again and see if it causes issues. I can't find a reference on musescore.org so maybe I remember it wrongly.

**Comment by lasconic** [comment]
I just tried it on MacOS and it seems these shortcuts don't work...

**Comment by lasconic** [comment]
So I wonder if it's better to have them working on WIndows (assuming they work, anyone could confirm this?) but not on Mac. Or if it's better to let the user choose.

**Comment by divya-urs** [comment]
These shortcuts work on Linux.

**Comment by Jojo-Schmitz** [comment]
In 2.1 and the nightlies before I have them as Ctrl+Alt+Shift+{left,right}arrow, but those don't seem to be doing anything either (on Windows)

**Comment by thomasbonte** [comment]
Indeed there was a good reason not to use those but I don't recall.

**Comment by Jojo-Schmitz** [comment]
Alt+{left,right}arrow works tough, for me, on Windows

**Comment by Jojo-Schmitz** [comment]
Alt+{left,right}arrow works though, for me, on Windows, in master and 2.1, so this might be a candidate for 2.2 too?

**Pull request merged**
