### PR TITLE
[MU3] Backend log fix

### PR DESCRIPTION
**Pull request by Eism**
Disabled logging for backend

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Wouldn't using a non-Debgg build have disabled that logging automgically?

**Comment by Jojo-Schmitz** [comment]
Also how is disabling some code that is for Windows only going to help on the backend, which is Linux? I'm confused...

**Comment by Eism** [comment]
@Jojo-Schmitz 
> Wouldn't using a non-Debug build have disabled that logging automagically?

qWarning in qt library are printed to stdout. Extra logs interfere with the parsing of command results. We can disable logging only in this way.

> Also how is disabling some code that is for Windows only going to help on the backend, which is Linux? I'm confused...

That is the problem.
Previously, the handler worked only for Windows, for Linux (backend) the logs were printed as they are to the console. Log output is now disabled for all platforms on the backend

**Comment by Jojo-Schmitz** [comment]
I see, thanks for explaining. 
So we might have done this instead:
```
static void mscoreMessageHandler(QtMsgType type, const QMessageLogContext& context, const QString& msg)
{
#if ! defined(QT_DEBUG)
      Q_UNUSED(type);
      Q UNUSED(context);
      Q_UNUSED(msg)
#else
...
#endif
}
```

**Comment by Jojo-Schmitz** [comment]
Of even
```
static void mscoreMessageHandler(QtMsgType type, const QMessageLogContext& context, const QString& msg)
{
      if (debugMode) {
...
      }
}
```
to have them available when using the -d option

**Comment by Jojo-Schmitz** [comment]
BTW: `qWarning()` does not send to `stdout` but to `stderr`, so a ` 2>/dev/null` should get rid of it too

**Pull request merged**
