### PR TITLE
Docker container for AppImage build

### PR DESCRIPTION
**Pull request by shoogle**
I disabled autobuilds on Docker Hub, so the container is not rebuilt on every commit.

Instead, on each commit:
- Travis pulls the docker container and builds MuseScore
- Travis [checks](https://github.com/musescore/MuseScore/compare/master...shoogle:fixed-appimagekit-version#diff-aad98a47365a899c0b7d2387934b15f5R71) if the Dockerfile or Recipe has changed and triggers a rebuild of the container on Dockerhub only if they have changed.

At the moment these build from my Docker because I can't seem to create one for the MuseScore organisation on Docker Hub, but we should do this before merging.

### CODE REVIEW

**Comment by lasconic** [comment]
It looks good. Could you squash?

We will merge first in order to have the Dockerfile on MuseScore github. Then we will change the docker image URL. I believe we should be able to build several images for 64 and 32 bits and with different versions of Qt for different branches.

**Comment by lasconic** [comment]
Actually, there is a new option on github to "squash and merge". I wanted to try it for quite some time. I will try it with this PR :) I hope it will not break anything :)

**Comment by lasconic** [comment]
Ok pretty slick. It works. It squashed the commits into a single one and added it on top of master. Nice!

**Comment by lasconic** [comment]
I create a Musescore repo on hub.docker.com
https://hub.docker.com/r/musescore/musescore

For the moment, it points to the only docker file we have on master. 
I would create 4 builds, two for master, two for the 2.1 branch: x86 and x86_64.
I don't think the build.sh script can cope with that. Looking into it, @shoogle if you are around to check it with me.

**Comment by probonopd** [comment]
Please bundle libcap2 and libdb5.3. On a Pine64 with armbian I had to run:

```
sudo apt install libcap2:armhf libdb5.3:armhf

me@pine64:~$ cat /etc/*release
# PLEASE DO NOT EDIT THIS FILE
BOARD=pine64
BOARD_NAME="Pine64"
VERSION=5.25
LINUXFAMILY=pine64
BRANCH=default
ARCH=arm64
IMAGE_TYPE=stable
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
NAME="Ubuntu"

```

**Comment by shoogle** [comment]
@probonopd thx. This PR was specifically for i386 and x86_64, but perhaps @ericfont can add those to his ARM build?

**Comment by probonopd** [comment]
Oops, sorry. I added this here because GitHub Issues are disabled and I didn't feel like registering a MuseScore account just to report this. Sorry if I added this to the wrong PR.

**Comment by shoogle** [comment]
@probonopd no worries. MuseScore's tracker is likely to move to GitHub later this year (though I think you have a MuseScore account already).

**Comment by ericfont** [comment]
Thanks for the info...in a few days I can add add those and test out on a few different arm boards I have, including the Pine64.  But I have to remember to do this somehow.

**Pull request merged**
