### PR TITLE
Fix #70906 - TAB: slurs between stems not centred

### PR DESCRIPTION
**Pull request by mgavioli**
__References__: issue https://musescore.org/en/node/70906 and _passim_ issue https://musescore.org/en/node/69846

In TABs, when slurs are placed between stems (as opposed to slurs on note head side), they are not perfectly centred.

This may happen for instance in tabs with stems beside staff and more than one voice.

### CODE REVIEW

**Comment by mgavioli** [comment]
@lasconic @MarcSabatella : would you mind to double check if the notes in comments at https://github.com/musescore/MuseScore/pull/2182/files#diff-ff48206423d5b1e9b234471f81b89a53R907 and at https://github.com/musescore/MuseScore/pull/2182/files#diff-ff48206423d5b1e9b234471f81b89a53R970 are correct?

If so, the execution of either section could be spared if either anchor is not NONE

**Comment by MarcSabatella** [comment]
I don't really know this section of code well at all - most of what I did with ties or slurs was elsewhere.  However, I do see that "stemPos" is set in this section of code and then used further down, so it isn't just about xo and yo, which are indeed only used in the NONE case.

**Comment by mgavioli** [comment]
@MarcSabatella : `stemPos` is used only locally for some tests to set `xo` and `yo`; neither `sp` or any of the elements derived from it (`sc`, `ec`, `scr`, `ecr`, `note1`, `note2`) are modified in these parts of the code, except for adding `(xo, yo)` at the end. So, I cannot see any effect of these code parts, if the anchors are not set to `NONE`.

**Comment by lasconic** [comment]
@mgavioli it seems you are right. I guess the code grew organically.

**Pull request merged**
