### PR TITLE
Fix #75316 - Wrong glyphs for note head parentheses

### PR DESCRIPTION
**Pull request by mgavioli**
Fix #75316 - Wrong glyphs for note head parentheses

__References__:
- original issue: https://musescore.org/en/node/75316
- duplicates:
    - https://musescore.org/en/node/85456
    - https://musescore.org/en/node/86451

Note head parentheses glyphs are wrong. This is a side-effect of the change to SMuFL encoding.

Fixed by using the right references; only the font is changed, no code change.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I wonder whether a vtest for these brackets would be due?

**Comment by Jojo-Schmitz** [comment]
I wonder whether a vtest for these brackets would be due?
Maybe in the last 2 measures of the ...-10... files?
See PR #2285

**Comment by mgavioli** [comment]
@Jojo-Schmitz : It seems to me a good place. I have never understood how vtests are made and how they work. If you are familiar with them, please go ahead!

**Comment by Jojo-Schmitz** [comment]
Done deal, see PR #2285, just needs to get updated once your PR got merged. Or 'manually' tweaked to reflect the expected rather than the current behavoir.

**Comment by Jojo-Schmitz** [comment]
OK, I now went the latter way, i.e. took the font from this PR to have the correct expected output in the other one

**Comment by mgavioli** [comment]
@lasconic : Thanks for merging. I would think this PR could be useful in 2.0.3 too, wouldn't it?

**Comment by Jojo-Schmitz** [comment]
Not sure 2.0.3 is affected by the bug this PR fixes but my vtest PR would show ;-)

**Comment by Jojo-Schmitz** [comment]
As far as I can see PR #2120 never got merged into 2.0.3 I think, so it should not be affected by the bug this PR fixes but my vtest PR would show ;-)

**Comment by lasconic** [comment]
2.0.3 still use the same font than 2.0.2, so indeed this PR is not necessary there.

**Pull request merged**
