### PR TITLE
Don't rewrite measures, if deleted time sig has same length as previous one

### PR DESCRIPTION
**Pull request by sammik**
Resolves one case of #20812 

quote from issue:
For duplicate signatures there should be NO CHANGE. Don't reprocess, even to the default "correct" order; preserve the rest structure exactly as it is. This is existing data; the default is not correct, the user is correct.
(🙏 and maybe don't delete other time-dependent data the user does not associate with a particular instance of a time signature, like Layout breaks. 🙏 )

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
What about 4/4 vs. 2/2 or cut time or common time? Or 3/4 vs. 6/8?

**Comment by Jojo-Schmitz** [comment]
What about possibly different beaming settings?

**Comment by sammik** [comment]
> What about 4/4 vs. 2/2 or cut time or common time? Or 3/4 vs. 6/8? Seems covered by the title of this PR, but not by the code, as far as I can tell? What about possibly different beaming settings?

It seemed to work in my test. May be measure.timesig returns recude value of time fraction. But yes, to be sure, better to include directly into the code. Thanks.

Also, I think behaviour should be same for insert time sig. So all situations (remove, add, change) should give same results.

Ill work on it may be tonight.

**Comment by sammik** [comment]
@Jojo-Schmitz `(3/4 == 6/8) = true` is already covered by `==` operator, see:
https://github.com/musescore/MuseScore/blob/89e36981841bac0ce0d3d659d7b2badf0d8780b4/src/engraving/types/fraction.h#L143-L146

**Comment by Jojo-Schmitz** [comment]
OK, I didn't know, but then again this may not be wanted here, 3/4 and 6/8 do have different beaming rules (by default), so removing a 6/8 and falling back to 3/4 would need to reset beams too, wouldn't it?

**Comment by sammik** [comment]
> 3/4 and 6/8 do have different beaming rules (by default), so removing a 6/8 and falling back to 3/4 would need to reset beams too, wouldn't it?

Refreshing layout fixes beams. 
I thik `triggerLayoutAll()` would fix it. @mike-spa will love us. 
May be he would have some smarter solution.

By the way, same issue (not refreshed beams) happens also after undoing some timesig (3/4 - 6/8) changes.

**Comment by sammik** [comment]
Hm, I tried `setLayoutAll();` but it has no effect in refreshing beams.
Only adding and removing line break before affected measure fixes it.

**Comment by sammik** [comment]
@Jojo-Schmitz it should be done now

**Comment by RobFog** [comment]
@sammik A rebase is necessary, it seems.

**Comment by sammik** [comment]
rebased

**Comment by sammik** [comment]
> Replacement to come?

Not now (not from my side).

**Pull request closed without merging**
