### PR TITLE
fix #311036 Mtest fix

### PR DESCRIPTION
**Pull request by Eism**
Resolves: https://musescore.org/en/node/311036

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Sorry, no cigar. While this fix certainly is good and needed, it does not fix the mtests, they still fail the very same way.

**Comment by mattmcclinch** [comment]
The problem can be solved by moving [this line](https://github.com/musescore/MuseScore/blob/master/mu4/plugins/api/qmlplugin.cpp#L28) inside the body of the `if (!MuseScoreCore::mscoreCore) { ... }` block. The stub `MuseScoreCore` object should only be constructed if `MuseScoreCore::mscoreCore` is null, because the `MuseScoreCore` constructor overwrites the value of `MuseScoreCore::mscoreCore` no matter what. This means that a subsequent call to `MuseScoreCore::mscoreCore->currentScore()` will now return `nullptr`, which is why the test (and plugins in general) are failing.

**Comment by Eism** [comment]
@mattmcclinch Great job. That's right!

**Comment by Jojo-Schmitz** [comment]
That seems to be it, please merge ASAP!

**Pull request merged**
