### PR TITLE
[MU4] Migration dialog. Stabilization

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: 
https://github.com/musescore/MuseScore/issues/10120#issuecomment-1017846773

### CODE REVIEW

**Comment by oktophonie** [comment]
Can confirm this now shows the correct dialog according to the version of the file being opened!

The 'Automatic spacing' checkbox option seems to have no effect, which is a regression from 3.6. (The 'Leland' option seems to work fine; the 'Edwin' option works selectively, but that is the same as in 3.6 and should be handled as an entirely separate issue.)

**Comment by RobFog** [comment]
Is #9070 related?

**Comment by oktophonie** [comment]
Certainly not impossible; it looks like the right 'basic' style sheet isn't always being used for the version of the file, which could cause unpredictable things to happen when subsequent changes are applied.

**Review by vpereverzev — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxMint 20.2 - PASS

**Pull request merged**
