### PR TITLE
fix #111856: Add Unicode accidentals to "Common Symbols" section of Special Characters

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by lasconic** [comment]
I would add them at the start. It would be very cool if the Common Symbols was rearranged according to the actual text element. (Tempo, the note first, etc...) I guess it would be even better if it was in docked widget or in the inspector. What do you think? Worth expanding in the forum?

**Comment by Jojo-Schmitz** [comment]
Well, I've just added them in ascending order, like all the rest was sorted.
We could swap the commonTextSymbols[] and commonScoreSymbols[]? Or do you just want to reorder inside commonScoreSymbols[]?
Those entries in commonTextSymbols[] could use some more comments.

**Comment by Jojo-Schmitz** [comment]
Oh, I see, they are not strictly in ascending order

**Comment by Jojo-Schmitz** [comment]
Moved sharp, natuaral and flat to the top of commonTextSymbols[] (after &copy;), added a few more and commented, using  (something similar to) HTML entities, to descibe what these characters look like.

**Pull request merged**
