### PR TITLE
remove pre-2.0 compatibility stuff

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
there's probably quite a bit more, but these are the obvious places

### CODE REVIEW

**Comment by lasconic** [comment]
Ideally, it would be great to regroup all this stuff in a single file instead of delete it. In a short discussion with Werner, he suggested to create a completely separated file to load press 2.0 files, something similar to the importxml files.

**Comment by Jojo-Schmitz** [comment]
OK, so I've for now just removed `114 > mscVersion() < 206`, i.e. alt the post-1.3 and pre-2.0.0 stuff.

**Comment by Jojo-Schmitz** [comment]
oops, looks like a lot of the mtest files are pre-2.0.0, `mscVersion() < 206`

**Comment by Jojo-Schmitz** [comment]
I can go ahead and fix them, if this PR in General is going into the right direction, otherwise I'd rather not invest the time. Just let me know.

**Comment by lasconic** [comment]
I believe it does. Only little problem is that we will need to update the test over and over again if we increment the format numbers like we did between 1.3 and 2.0.

**Comment by Jojo-Schmitz** [comment]
Well, we'd need to doi it again for MuseScore 4.0 ;-)
We may need to do some mtests files again due to other test failures caused by format changes, but that was the case during 2.o development too.

**Comment by Jojo-Schmitz** [comment]
Question is which version to use to rewrite them now, latest master or plain 2.0.0, or something in between?

**Comment by Jojo-Schmitz** [comment]
sorry, somehow I managed to fat-finger this PR. New on at #2581

**Pull request closed without merging**
