### PR TITLE
Translatable plugins descriptions

### PR DESCRIPTION
**Pull request by Gootector**
Translatable plugins descriptions

Greetings,
Gootector

Resolves: #NNNNN 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Unfortunately, this has no result at the moment because plugins are not yet scanned for translatable strings. But in the future, that will be fixed, so let's leave this PR open until then. Thanks!

**Comment by Gootector** [comment]
OK.

**Comment by igorkorsukov** [comment]
This approach allows to translate only built-in plugins (if we add a folder with plugins for scanning). But it does not allow to translate external plugins. I believe that there should be a unified localization system for built-in and external plugins. We will do it later.

**Comment by Gootector** [comment]
Please merge my PR into the master.

**Comment by cbjeukendrup** [comment]
I think this PR unfortunately won't work anymore, because of the new limited way of parsing plugins in 4.4. @igorkorsukov Is that right?

**Comment by igorkorsukov** [comment]
yes, that's right, but as far as I understand, it wouldn't have worked before, because we don't collect strings from plugins and don't send them to transifex

**Pull request closed without merging**
