### PR TITLE
Switch Windows build to Qt-5.5.1

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
as a follow up to fc8fad97.

Unfortunatly PCH still fails miserably, even with the (minor) compiler update that comes with Qt-5.5

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Very strange, I'm 100% sure to have it compiled and running, opened a score, verified in "About Qt" that is really got built against Qt-5.5, but now it just crashes on startup with `During startup program exited with code 0xc0000139`, no idea why?

**Comment by Gootector** [comment]
New Qt = a new problems with displaying, etc. (fonts) :P

**Comment by Jojo-Schmitz** [comment]
Nope, my Gonville-vtest PR was done with Qt-5.4.2

**Comment by lasconic** [comment]
Qt is not used to layout or draw musical glyphs anymore...

**Comment by Jojo-Schmitz** [comment]
Which may explain the differences seen in that Gonville-vtest PR, the previous version had been done prior to the switch to freefont

**Comment by Jojo-Schmitz** [comment]
I just tried again, but it still crashes on startup with `During startup program exited with code 0xc0000139`, no idea why? Various hints point at incompatible compiler versions and/or Qt DLLs, but I don't see how this applies here?

**Comment by ericfont** [comment]
I got a similar startup message when I was first trying to build mscore in windows.  Turns out that I didn't have all of the library directores in my %PATH%.  I don't know if this helps you.

**Comment by Jojo-Schmitz** [comment]
Hmm, I'm using similar setting to the 5.4 version, but of course adjusted to 5.5
`set QTDIR=C:\Qt\5.5\mingw492_32
set PATH=%QTDIR%\bin
set PATH=%PATH%;C:\Program Files (x86)\CMake\bin
set PATH=%PATH%;C:\Qt\Tools\mingw492_32\bin;C:\Qt\Tools\mingw492_32\lib
set PATH=%PATH%;C:\Qt\Tools\QtCreator\bin
set PATH=%PATH%;%SystemRoot%\System32`

**Comment by ericfont** [comment]
where is GnuWin32\bin?  Where is is \Jack\lib?

**Comment by Jojo-Schmitz** [comment]
Not in PATH, and why should it? It isn't needed for Qt-5.4, resp. autodetected by the builds (cmake?), for freetype and jack

**Comment by ericfont** [comment]
build doesn't need them.   But execution does, I believe.

**Comment by Jojo-Schmitz** [comment]
Certainly not when building for/with 5.4

**Comment by ericfont** [comment]
maybe disregard what I'm saying...i might be off track.

**Comment by ericfont** [comment]
Jojo, if you are using QT 5.5 on windows, I would appreciate if you respond to  https://musescore.org/en/node/71731 to let me know if you are able to use any [Shift]+key commands (e.g. Shift+comma for crescendo).  I want to determine if this is a QT 5.5 specific issue, or if it is some funny thing with my linux setup.  No one responded to my post so I have no idea why I was running into that issue, and I don't want to try to setup QT 5.5 on windows now.  I apologise if this is comment is not the appropriate place to alert your attention.

**Comment by Jojo-Schmitz** [comment]
Eric, I can't get it to run at all, so can't really check, sorry

**Comment by briff** [comment]
I managed to start 3 times, last time it did not crash. Problem was that it found qt creator dlls on path, so dll references got mixed up.

**Comment by Jojo-Schmitz** [comment]
Just upgraded to Qt-5.5.1, rebase the PR and adjust slighlyx /QtPositioning.dll is available again, seems it was missing in 5.5. Seems to work fine

**Comment by lasconic** [comment]
See #2476

**Pull request closed without merging**
