### PR TITLE
add MuseJazz font

### PR DESCRIPTION
**Pull request by lasconic**

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
I can't find anything about "Skatcat" on the internet. However, this looks just like [LilyJazz](http://www.musictypefoundry.com/product/lilyjazz/), and the license file credits Torsten Hämmerle and Abraham Lee with a link to http://www.musictypefoundry.com. Why this name? Why not "MuseJazz"?

I love it either way. 😀

**Comment by lasconic** [comment]
Let's say it's a working name that Abraham chose for now. Glad you like it !

**Comment by MarcSabatella** [comment]
Very cool!  Even though I've grown comfortable with using standards fonts for notation, I may start giving this a shot, and I know others will appreciate it for sure!

**Comment by lasconic** [comment]
Abraham sent me another update. The font is not called MuseJazz, the former MuseJazz font is now MuseJazzText and so we follow the same scheme than for the other fonts.
That might cause some compatibility headaches... I tried to mitigate the problems I could think about. Tests are welcome.

**Comment by Jojo-Schmitz** [comment]
The vtest scores name it Emmentaler rather than MuseJazz

**Comment by lasconic** [comment]
Yes, well it's more letters to test :)

**Comment by Jojo-Schmitz** [comment]
Just had a very brief look, still away from my computer for a couple more days.

**Pull request merged**
