### PR TITLE
Update generateTs.py to use Python 3 syntax

### PR DESCRIPTION
**Pull request by shoogle**
Preserves compatibility with Python 2 (for now).

- Replaces Python 2 `print` statement with Python 3's `print()` function.
- Removes UTF-8 encoding statements as everything is UTF-8 by default in Python 3.
- Adds compatibility code to make sure the above changes work in Python 2.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Mind to have a look at and convert the python script for tours too, https://github.com/musescore/MuseScore/blob/master/share/tours/generateTs.py ?
And while at it also this: https://github.com/musescore/tx2s3/blob/master/tx2s3.py ?

**Comment by shoogle** [comment]
@Jojo-Schmitz I've done the other generateTs.py. I will have a look at tx2s3.py, but it is not in this repository so it shouldn't hold up this PR.

**Comment by shoogle** [comment]
I used `find . -iname "*.py"` to check for other Python files in this repository, and looked at each one manually to try to see which Python version it is using, and whether I could upgrade it.

file | Python version
---|---
./build/add-mc-keys.py | 2 only
./build/appveyor/irccat.py | 3 only
./build/appveyor/updateHTML.py | 2 only
./build/travis/job_macos/updateHTML.py | 2 only

(There are a few more in `thirdparty/freetype/src/tools` but presumably they don't belong to us.)

The ones that still use Python 2 interact with servers and encryption keys, so I cannot upgrade them to Python 3 myself (well I can but I can't test it to see if it still works). However, I have added a Unix-shebang to each one to indicate the Python version.

- `#! /usr/bin/env python` for Python 2 scripts
- `#! /usr/bin/env python3` for Python 3 scripts

Scripts that are compatible with both versions use `#!/usr/bin/env python`, followed by:

```python
from __future___ import ...
```

That has to be the first non-empty, non-comment line of the file for it to work.

**Comment by shoogle** [comment]
If somebody with server access wants to update the remaing Python 2 scripts then it shouldn't be too difficult. In most cases it is as simple as replacing the `print` statement with a `print()` function:

- `print "string"` becomes `print("string")`
- `print "string1", "string2"` becomes `print("string1", "string2")`
- etc.

Occasionally there will be a division `/` that needs to be replaced with `//`:

- `x = 2/3` becomes `x = 2//3`

The only other issue I am aware of is with text encoding, which was ASCII by default in Python 2 but UTF-8 in Python 3. We were using UTF-8 strings in most places anyway, so the correction is simply:

- find `.encode('utf8')` and replace with `` (i.e. the empty string)

That will get the script working in Python 3 but break it in Python 2. If you want to preserve compatibility with Python 2 then insert the [compatibily code](https://github.com/musescore/MuseScore/pull/5142/files#diff-ca2c14b05e1be398ee7b30786d24800dR3) I added at the top of `generateTs.py`.

It is possible that you may run into compatibility problems with the modules you are using to interact with the server, hence I cannot update those files myself. However, any problems that do arise should be correctable by small changes in syntax like those above.

**Comment by shoogle** [comment]
__TLDR:__ This is ready to merge.

**Comment by Jojo-Schmitz** [comment]
Rebase needed.
I wonder whether we could do away with instrumentsxml.h and toursxml.h alltogether and have them being automatically generated by the lupdate step, or maybe even only in the Mac_OS_lupdate Travis job?

**Comment by shoogle** [comment]
Rebase done. This PR does everything it set out to do. I will leave the `lupdate` job to somebody who can test the upload.

**Comment by Jojo-Schmitz** [comment]
the `lupdate` part most probably needs to be done by someone on a Mac I guess, only there  a `make lupdate` really works (without taking several hours to finish, like on Windows/MinGW, or not doing anything at all, like on Windows/MSVC, not sure about Linux)

**Comment by shoogle** [comment]
I made a small change to ensure that the output is identical on Windows and macOS. The string list is populated by listing all translation files in the relevant directory, but I noticed that the directory listing is returned in a slightly different order on each platform, leading to a false diff. I get around this by [sorting the list alphabetically](https://github.com/musescore/MuseScore/pull/5142/files#diff-ca2c14b05e1be398ee7b30786d24800dR31) before using it. The output is now identical on all platforms and Python versions.

**Comment by anatoly-os** [comment]
There is no need to keep compatibility with Python 2, so I'll apply the changes related to Python 3 syntax manually and test.

**Comment by anatoly-os** [comment]
Applied proposed changes in a3dd079093079890c5eee23f68a8296822a6b3b2, 8087b11c772a67aca99961edecd11aca6b67de2e and https://github.com/musescore/tx2s3/commit/dc2862085199d169ddafdcf48eb1b32b8f02f13b.

**Pull request closed without merging**
