### PR TITLE
make args to msvc_build.bat being case insensitive

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by anatoly-os** [comment]
Why?)

**Comment by Jojo-Schmitz** [comment]
in MSVC it is called RelWithDebInfo, CamelCase, ussing that as an arg to the bat fails with an error message

**Comment by Jojo-Schmitz** [comment]
in MSVC it is called RelWithDebInfo, CamelCase, ussing that as an arg to the bat fails with an error message

Having said that: yes, I've just been biten by that ;-)

**Comment by anatoly-os** [comment]
So you made it **not** case sensitive?

**Comment by Jojo-Schmitz** [comment]
not case sensitive == case insensitive ;-)

**Pull request merged**
