### PR TITLE
Fix cross-system beaming

### PR DESCRIPTION
**Pull request by pgkos**
This should fix the issues with beams spanning two (or more) systems:

Before:
crosssystem_beaming_old

After:
crosssystem_beaming_new

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Interesting solution!  Having looked at this and given up on trying anything for 2.0, I understand why you are using a signal here - the beam layout is otherwise performed too early.  This solution not very consistent with how we do anything else, but it's perhaps simpler and less invasive than actually changing the implementation of a beam to be based on a spanner.  And it makes me wonder if similar solutions might help solve other problems.  But I also wonder if there are good reasons why we don't use this approach elsewhere.

**Comment by pgkos** [comment]
Yes, I have noticed that signals and slots rarely appear in the source code, nevertheless I decided to use them as in my opinion they are very flexible and easy to implement. Other approaches would probably require more changes to the code.

I like using signals and slots as they are similar to events, and they allow easy communication between any two distinct components (classes) of an application.

**Comment by pgkos** [comment]
I have improved (amended) the commit. Now the grips (rectangles) are always drawn at the correct positions when editing a beam spanning multiple systems.

**Comment by pgkos** [comment]
I have added preliminary support for beams which begin on one page and end on a second page. This is a really hacky solution, but it should work.

**Comment by lasconic** [comment]
A quick discussion with Werner about this PR.

Long time ago, MuseScore elements were not QObject. We made them QObject for the plugin framework but we carefully avoided to use signal/slot with the plan the make the QObject dependency optional if plugin framework was not needed. The QObject machinery is quite heavy and could hurt memory usage and runtime performance. 
Also, Werner thinks that signal/slots makes the code hard to read. The MuseScore object knows each others in general so a direct call could be possible.

**Comment by pgkos** [comment]
In my opinion signals and slots do not make the code harder to read, but I understand that you want to keep the dependencies on QObject minimal. Therefore, I have changed it to a direct call.

**Comment by Jojo-Schmitz** [comment]
rebase needed...

**Comment by pgkos** [comment]
Squashed and rebased.

**Comment by rowild** [comment]
Thank you, but after testing, the cross-system beaming still does not work, neither in the nightly 2.0.3 nor in the 2.1 (for Mac; MuseScoreNightly-2016-03-21-0756-master-1fd67d0.dmg, 
MuseScoreNightly-2016-03-21-0716-2.0.3-8814553.dmg)...

**Comment by lasconic** [comment]
This pull request is not merged into master or 2.0.3 so it's perfectly logical.

**Comment by RobFog** [comment]
What does the "procrastinated" label mean? It seems this is the only pull request with this label.

The creator of this pull request has rebased the changes as requested so they are certainly not procrastinating. ;-)

**Comment by lasconic** [comment]
It means the solution implemented is not good enough but that we don't have a better one yet. So we are procrastinating... cc @wschweer

**Comment by Jojo-Schmitz** [comment]
And it seems to no longer be needed, as far as I can see in current master we don't have the issue anymore

**Comment by MarcSabatella** [comment]
As far as I can tell,cross staff beaming across system breaks doens't work *at all* in current master?

**Comment by FryderykChopin** [comment]
I added the patch to mscore-2.0.1-6.fc23.x86_64.rpm, as you can read [here](http://forum.fedoraonline.it/viewtopic.php?pid=237421#p237421).
This patch works fine, except for a group of eights with only one note at the second line, because in this case the end of the beam ends just over the note stem, rather than on the steam, as you can see in the following image (see the red line): there is a way to correct this?
Note that this problem was already in MuseScore without this patch, although it was not noticeable because of the incorrect positioning of the beam.
schermata da 2016-04-23 17-56-47

**Comment by FryderykChopin** [comment]
I fixed the last problem (a group of eights with only one note at the second line), and I expanded a bit the prolongation, as you can see [here](https://github.com/pgkos/MuseScore/compare/cross-system-beaming-fix...FryderykChopin:patch-1).
I think the result is ok, now. 
schermata da 2016-04-25 18-54-43

**Comment by Jojo-Schmitz** [comment]
Rebase needed and see also https://musescore.org/en/node/16278, the issue for this.

**Comment by lasconic** [comment]
The PR is not mergeable. @wschweer we will have to come up with another solution with the new smart layout algorithm.

**Pull request closed without merging**
