### PR TITLE
Add feature #28376 - Drop the keysignature you want

### PR DESCRIPTION
**Pull request by vgstef**
This commit adds the feature Issues #28376 - Request method to specify that key signature being added is already transposed (https://musescore.org/fr/node/28376)

This way, when not in Concert Pitch mode, the Key signature taken in the palette will be the one put on the staff where it is dropped. All other staves will adjust accordingly, unless Control key is hold. In that case, only the selected staff will be changed.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
I don't see where you do anything to let the user know which is the "active" staff.  To me, that;s the Achilles Heel of this whole idea.  The vast majority of the time users don't drag key signatures to specific staves - they frag to a measure as a whole, and it's the measure as a whole that highlights.  If we are going to start making the behavior of drag and drap depend on the whims of the verttical position of where you happen to release the mouse, it is going to vitally important to make sure the user gets feedback before dropping which staff he is dropping on.

I'm still not a fan of this change, as it makes drag & drop behavior seem quite random for the vast majorty of use cases.  The only case that is helped is the very rare case of a user creating a score for a single transposiung instrument - that's really the only case that I recall seeing proposed where the current behavior is not very clearly superior.  And even in this rare case, it's still going to seem inconsistent, since the Create New Score wizard will surely still deal in concert pitch when adding key signatures.

**Comment by vgstef** [comment]
Presently, I consider it worst, because there is no visual indication of why staff will be taken into accounts. And depending where we drop the new keysignature, a different keysignature will appear coming from nowhere. So often I've seen people going back to the palette think they chose the wrong key, try again and not understanding why the key dropped doesn't show up.

So it's much more user friendly to have the right key appear where we drop it. People don't just drop a key signature randomly anywhere on the score. They already have to choose in which measure they want to drop it. And the brownish colour indicates which staves will be influenced.

Why being so attached to a wrong behaviour. If you always work in concert pitch, why opposing an improvement in the non concert pitch? Over here, we work a lot in non concert pitch, with different transposing instruments. So there a tons of use cases. I know that this commit corrects a behaviour that bring interrogations and headache.

In this screenshot, what key will appears where with drop the new key signature? 
screenshot-keysig

With my commit, I know exactly what it's going to be (ie. the one I drop). Otherwise, no one knows.

**Comment by MarcSabatella** [comment]
I don't consider the behavior wrong at all.  It is completely natural to me, as a compser of many scores for transposing instruments.  If I write a score in the key of "F" for an orchestra, and I want to drag the key of "F" to the score, I don't want to suddenly have to start being careful of the vertical position where I drop that "F".  Just like I don't have to be careful where I drop a time signature.  In both cases, I know it will apply to *all* staves, so I don't pay attention to which staff my mouse curosor happens to be closest to.  I do get that some people who primarly are putting together individsual parts rather than than writing complete scores might not be thinking about the concert key at all, but this, again, is very much the exception.  Normally whenone writes for a transposing instrument, it is just one instrument among manyin a score, and in such case, when one changes key, one expects to change it for the entire score at once, and one thinks in terms of concert pitch when doing so.  Which again is why I think your change is a step backwards for most cases even though I can see why it help[s in certain rare special cases.

Anyhow, looking at your screen shot, there is no visual indication whatsoever as to which staff is going to be used to calculate the transoposition. Sure, since your mosue cursor just happened to be directly on top of a staff, you might guess if you were expecitng this behavior - which I think the vast majority of people won't be, because they had no intention of dropping onto a particular staff but instead were thinking of the score as a whole.  But even for the subset of people who do wish to drop onto a specific staff, what if your mouse cursor is half-way betwen two staves?  Again, it is vitally important they be given feedback as to which staff they are dropping onto.

**Comment by vgstef** [comment]
Sorry, but I totally disagree. I'd really like a survey on this issue, because it seems like you talk only from your utilisation of MuseScore. 

The actual behavior only works for you because you think in term of concert pitch. But that's a minority. You do the transposition in your head. So you have to guess (or calculate) the right keysignature before picking it from the palette.

My commit offers the user to do the transposition automatically. The user simply pick the key signature they want for the instrument whatever the instrument key. With many different transposing instrument, my commit is very important. And not just for me or for rare use case. Other people a issuing MuseScore bugs because the current behaviour isn't obvious and requires musical knowledge. I want MuseScore accessible even for people that don't have all that musical background. 

Actual behaviour is only valid if we drop the key signature on an instrument in the key of C.

**Comment by vgstef** [comment]
Btw, this commit also accounts for a key signature dropped directly on a key signature on a staff. That's an other example where people expect to replace that key with the one dropped on it.

**Comment by MarcSabatella** [comment]
I don't do the transposition in my head - I too want MuseScore do do it for me.  I know that, for example, Ravel's Bolero changes key from C to E toward the end.  I don't want to calculate anything - I want that portion of the score to be in E major, so I simply drag E major from the palette to the score.  I want MuseScore to autoamtically turn that into F# for the clarinets, B for the horns, etc.  And I don't want to worry about whether I accidentally release the mouse too close to to a clarinet staff and thus end up with E major only for the clarinets with is actually *D* major.  I want to drag the actual key of the piece, not whatever it happens to work out to be once transposed.

Again, I can certainly understandc how in certain unusual special cases - lke if I am transcxribing individual parts rather than composiung, arranging, or transcribing full scores - I might *not* be thinking in terms of the actual key of the piece.  And in those unusual special situations, I might indeed want to add the transposed key rather than the actual key.  And I can see how if some people happen to do a lot of that unusual special thing, it might seem common, but I think for most usersit is not.

Any in case, even if we decide we do want to cater to the people who mostly work in that particular way I think is the unusual special case, it is absolutely essential we providee feedback as to which staff you are dropping onto.  Surely you can agree to that?  Otherwise, the results of dropping will depend on something you are not given any visual feedback whatsoever about.  If your mouse happens to be half way between a clarinet and flute staff when you prepare to release the button to drop, you *must* get feedback from MuseScore as to which staff is going to be used for the transposition.  Otherwise the result will seem random - move the mouse by a millimeter up or down and you get different results with no warning at all.  We highlight the specific measure because that is vital information you - depending on which measure you drop onto, you get different results, obviously.  So we start behaving differently depending on which staff you are dropping onto, we must provide that same visual feedback for the same reason.

**Comment by vgstef** [comment]
Ok, I added hightlighting the staff where the key is about to be dropped. See image.

screenshot-keysig

**Comment by ZackTheCardshark** [comment]
I can see value in both perspectives. Would it be reasonable to make this only a Preferences option (maybe a checkbox in the "Note Input" tab, but maintain the current behavior as the default?

**Comment by MarcSabatella** [comment]
The highlighting definitely helps, thanks.

As for an option, you've probably heard developers say they aren't fans of options.  I have nothing against them personally, but I'm not not sure it would really help here.  The issue in't one of how easy it is to do something - it's equally easy either way.  It's simply one of expectations and surprise, and even if an option is provided, some percentage of users will be surprised and won't understand the behavior.  They will simply think there is a bug and report it as such; they won't know there is an option to change the behavior.  And once you understand the behavior, the need for the option goes away, as it is trivially easy to adapt to either behavior *once you understand what to expect*.

Realistically, if this PR is merged, then you could get the current behavior by switching to concert pitch mode temporarily (or not so temporarily).  So in that sense, it is almost like providing an option.  I still prefer the current behavior, but it might be interesting to try merging this and see what people think.

**Comment by Jojo-Schmitz** [comment]
I like that measure highlight. And the default behavior might be decided on by the number of staves? Or even better by looking whether there are instruments of different transpositioning in the score?

**Comment by lasconic** [comment]
* I'm mostly the one "not liking options", so to make it clear, I'm not against options but it's just that  8à to 95% of users don't change settings at all (https://www.uie.com/brainsparks/2011/09/14/do-users-change-their-settings/), so adding an option is often not a good solution. Default needs to work for these 95%.

* About this particular issue, I guess the line of separation is between transcribers (who just blindly copy a printed score and so think in what is printed) and composers (who know that they want to modulate to a certain key for the whole orchestra, and so think in term of "tonality" change). I don't know what the distribution of MuseScore users is, but I understand the tension.

* I would like to see a better survey of what other software packages are doing and not be dismissive, since they do have an history and years of user feedback...

**Comment by MarcSabatella** [comment]
I agree, seeing how others handle this makes sense.

FWIW, though, it's not just transcribers versus composers.  Even when transcribing, when one changes the key signature, one might be thinking about the overall key or about any one particular staff, and that's hard to predict.  User expectations could depend on whether is one is transcribing just one part or an entire score, also could depend on whether one is transcribing staff by staff or measure by measure, whether one uses drag and drop or double click to add the key signatures, etc.

**Comment by vgstef** [comment]
Good points Lasconic.

From my understanding, composer usually use Concert pitch, so this PR  won't change anything about that.

Second, if composers don't work in concert pitch, with this PR, they simply have to drop the key signature on the staves for instruments in concert tonality (ie piano, guitar, flute...).

One example of use case : we have a partition for a marching band. We'd like to clarinets to play in D, and adjust other instruments accordingly. What would be the process in the actual behavior? 
With this PR, we need is drop the D key signature on the clarinet staff, and that's it.

**Comment by vgstef** [comment]
Here's a short video comparing both ways : https://youtu.be/vvpaUz1Sc_w

The behavior in Concert pitch isn't affected.

**Comment by ZackTheCardshark** [comment]
But what are the odds of somebody wanting the clarinets to play in D? Whether transcribing or composing, it seems every circumstance would incline the user more towards wanting the trombones to play in C, and the specific desire to have the clarinets to play in D wouldn't enter into it.

**Comment by vgstef** [comment]
Zack, I was just giving an example with the clarinet. The key didn't matter. It could by a saxophone or a trumpet. It's the process of finding the key that I wanted to emphasize. Why do you bring trombone in? Why would trombone need to play in C ? 

I see a lot of clarinet partitions in D (with 2 sharps in their key signature). What's wrong with that?  Clarinets are chromatic instruments, they can play in any key.

**Comment by ZackTheCardshark** [comment]
My point is that trombones are a concert pitch instrument, and clarinets playing in D = trombones playing in C.

**Comment by MarcSabatella** [comment]
Correct me if I'm wrtong, but I think this particular use case goes something like this:

Pretend you have a stack of faded copies of parts for a concert band arrangement, and you are trying to recreate the score and parts so you can print better parts.  The first thing you do is set up your score, then you start entering the music into the score from those old faded copies of the parts.  The first part you enter happens to be a clarinet part, and it happens to be in D, so without giving thought to what the overall key of the piece actually is, you simply enter D as the key signature since that is what you see on the individual part you are copying.

This is the sort of use case for which I can imagine the propsoed change making perfect sense.  There may be others too, some of which might seem equally obscure to many of us, but I guess this sort of thing comes up pretty often in certain circles.

**Comment by vgstef** [comment]
You're right Marc. Here's other actual use cases :
- Sometimes we get different versions of the same tune, but in different keys. We just want to take the saxophone parts from that version. So we transcribed that one, then simply drop the new key on that staff to fit the rest of the tune.
- We have a new tune in an unusual key with complex fingering for our beginner clarinettist. We'll just want to set a key for that staff that is easy for him to play, and the other musicians with adapt.
- Or we have a score and we simply want to see in what key the others would play if the trumpet plays in F. 

Since I made this change on my local MuseScore, I very much enjoy seeing instantly in what keys the others in my band play (I play alto saxophone in Eb). It's a great learning tool to understand transpositing instruments. Especially for beginners who don't know that concept.

**Comment by ZackTheCardshark** [comment]
Well, considering that the double highlighting of the measure and staff is an effective warning that the result will be very different depending on where you drop it—and considering that usually the first staff in a score is in concert pitch, anyway—I could probably adapt pretty quickly, myself. I still feel some kind of vague worry about "dumbing down" MuseScore with this change—it's not unreasonable to assume some prior knowledge of music theory, and an explanation like https://musescore.org/en/node/75466#comment-346086 can bridge that gap if needed—but then again, as you say, this would be just as likely to be a learning tool.

Question: With this branch, what happens if you make a vertical range selection that includes one measure on two staves, of a Bb instrument and an Eb instrument, and then double-click a key signature in the palette?

**Comment by vgstef** [comment]
With range selection, the first staff selected (upper most in the range) gets the key signature, the following ones adapt to that key accordingly.

**Comment by ZackTheCardshark** [comment]
Good. I was hoping it wouldn't cause the same key to be added to both staves. ;-)

**Comment by shoogle** [comment]
What if the Ctrl shortcut did both things:

1. Apply the key signature to the current staff only.
2. Not correct for the staff transposition (i.e. the keysig that appears looks like the one added).

Users would always press Ctrl when adding a keysig to a single instrument score where the instrument is a transposing instrument.

**Comment by dmitrio95** [comment]
Archiving this pull request, please open a new pull request for this feature.

**Comment by MarcSabatella** [comment]
I still like @shoogle 's suggestion of having the behavior tied to Ctrl, even though this makes it hard to discover and thus we'll still have some amount of surprise.  Would be useful to get input from Martin on this, maybe something could be part of one of his design proposals.

**Comment by TheRealSamChaney** [comment]
Ah bummed this never got merged. I agree with @vgstef that it would be intuitive to have a toggle between concert pitch and relative pitch for key signatures. If you're just making a little score for sax for something like transcribing a solo, it's counter-intuitive to drag 1 sharp thinking you're going to put the sax in its key of G, then see 3 sharps appear. Ah well, I appreciate your efforts vgstef!

**Comment by xpEMS** [comment]
Thanks @TheRealSamChaney Yeah, I've been quite disappointed to work on this issue and people not understanding that it's very important for some people (for example those that aren't professional composers). My improvement was working very well and it was a joy to test different key for different instruments. But with the new version of Musescore, I'd have to rework it, but I lost interest in contributing.

**Comment by vgstef** [comment]
Thanks @TheRealSamChaney. I’ve been quite disappointed working on this issue, since many don’t realize it’s very important for some users (for example, those who aren’t professional composers). My improvement was working well and it was a joy to test different keys for different instruments. Unfortunately, with the new version of MuseScore I’d have to rework it, and I’ve lost interest in contributing.

**Comment by MarcSabatella** [comment]
I don't see what being a professional has to do with anything.  The basic problem here is that different instruments have different transpositions, and this is true whether you are a professional or an amateur.  So one way or another one has to learn how this works and to deal with this.  Which isn't to say that a new feasture to allow alternate ways of dealing with this couldn't be nice, but it's not going to suddenly mean people don't need to understand transposition in order to work with transposing instruments.

**Pull request closed without merging**
