### PR TITLE
Change Hide/delete to Hide/Delete.

### PR DESCRIPTION
**Pull request by Rishav1707**
Resolves: #15672  

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually

### CODE REVIEW

**Comment by PetJer** [comment]
Capture+_2023-01-02-16-47-59(1)

Seems that you mistakingly changed other "deletes" to start with a capital letter (as shown above). Only "Hide/delete" should be changed to "Hide/Delete"

**Comment by Harmoniker1** [comment]
Also must all the instances in the `.ts` files be updated? I thought they were something that were generated automatically

**Comment by Rishav1707** [comment]
> Capture+_2023-01-02-16-47-59(1)
> 
> Seems that you mistakingly changed other "deletes" to start with a capital letter (as shown above). Only "Hide/delete" should be changed to "Hide/Delete"

Done @PetJer

**Comment by cbjeukendrup** [comment]
The `.ts` files should also stay unchanged indeed; those are re-generated automatically at the moments that we need them.

**Comment by Rishav1707** [comment]
> The `.ts` files should also stay unchanged indeed; those are re-generated automatically at the moments that we need them.

What does it mean? I am not able to understand and what I have to do now?

**Comment by cbjeukendrup** [comment]
You should undo the changes to the files with the `.ts` extension. There should be only one change, namely the one in `src/palette/qml/MuseScore/Palette/internal/TreePaletteHeader.qml`. The other changes should be removed from this PR.

**Comment by Rishav1707** [comment]
> You should undo the changes to the files with the `.ts` extension. There should be only one change, namely the one in `src/palette/qml/MuseScore/Palette/internal/TreePaletteHeader.qml`. The other changes should be removed from this PR.

Ok I'll undo these changes

**Comment by Rishav1707** [comment]
> Almost there! The changes in `share/locale/musescore_af.ts` need to be undone too...
> 
> Once that is done, it would be great if you could squash the commits, so that you have 1 commit containing 1 changed file. The easiest way is using [GitHub Desktop](https://desktop.github.com), which I do recommend.

Done @cbjeukendrup

**Review by igorkorsukov — APPROVED** [review]

**Pull request merged**
