### PR TITLE
MinGW5.3 ld.exe .rsrc merge failure: duplicate leaf

### PR DESCRIPTION
**Pull request by jeetee**
resfile.o is already included via object1.rsp, there should be no need to explicitly link it again

See discovery thread https://musescore.org/en/node/181796

### CODE REVIEW

**Comment by lasconic** [comment]
Brilliant !

**Comment by Jojo-Schmitz** [comment]
I wonder whether this would be beneficial to the 2.2 branch too

**Comment by Jojo-Schmitz** [comment]
I checked and 2.2 does build with this commit being cherry-picked (there's a conflict due to some formatting/indenting changes though, but that should be easy to resolve)

**Comment by Jojo-Schmitz** [comment]
I wondered whether this would be beneficial to the 2.2 branch too, so I checked and 2.2 does build with this commit being cherry-picked (there's a conflict due to some formatting/indenting changes though, but that is easy to resolve)
But see yourself in #3437

**Pull request merged**
