### PR TITLE
vst_audio_glitch_fix_442

### PR DESCRIPTION
**Pull request by RomanPudashkin**

### CODE REVIEW

**Review by mathesoncalum — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac13.6. The new regression (from 4.4.1) is **FIXED**

**Comment by Ysabelle12** [comment]
this audio glitch also happens in just normal playback from time to time where first note would not play

**Comment by cbjeukendrup** [comment]
@Ysabelle12 I assume you mean in 4.4.1, right? Or also in the 4.4.2 nightly builds after the fix?

**Comment by Ysabelle12** [comment]
> @Ysabelle12 I assume you mean in 4.4.1, right? Or also in the 4.4.2 nightly builds after the fix?

4.4.1 !

**Comment by RomanPudashkin** [comment]
> this audio glitch also happens in just normal playback from time to time where first note would not play


@Ysabelle12 this is something else, please open an issue. Or describe the steps to reproduce it here and we'll open it ourselves

**Pull request merged**
