### PR TITLE
smooth over icons, redesign mixer icons

### PR DESCRIPTION
**Pull request by cainy-a**
Resolves: *(direct link to the issue)* No issue; standalone pull request

*(short description of the changes and the motivation to make the changes)*
- smoothed over weird bumps, jagged edges and general errors in the icons.
- redesigned the mixer icons to look nicer (less realistic to fit in with the rest of the program)

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Under which name (on musescore.org) did you sign the CLA?
Can you provide these images as images, before and after?

**Comment by cainy-a** [comment]
> Under which name (on musescore.org) did you sign the CLA?
> Can you provide these images as images, before and after?

Signed as: cainatkinson9
Before: image

After: 
image

**Comment by Jojo-Schmitz** [comment]
That's not what I mean with before/after ;-), I meant the icons and images you changed in this PR,
so we can compare without having to build it ourself first

**Comment by cainy-a** [comment]
Mixer Buttons Before -> After
image
Icon Error Fix Before -> After
image
Above, but zoomed out
image
Mixer Fader Before -> After
image

**Comment by Jojo-Schmitz** [comment]
OK, that is 3 out of the 35 you changed.
I certainly buy that middle one, as small as the improvement is, not so sure about re Solo button though. and do like the old Mixer fader better.

**Comment by Marr11317** [comment]
@Jojo-Schmitz no need for him to copy every version.

image

**Comment by Marr11317** [comment]
Hmm, I can't find the difference for most files, so I guess you will have to actually post them.
For the mixer buttons and mixer fade, I am strongly against those changes. It makes the difference between on and off less visible.

**Comment by Jojo-Schmitz** [comment]
Oh, now I see too how to look ar the graphial difference

**Comment by Howard-C** [comment]
The mixer buttons originally seem so nice. Simplifying it seems so boring ;-)

**Pull request closed without merging**
