### PR TITLE
Fix: 303027 - Add System lines

### PR DESCRIPTION
**Pull request by njvdberg**
Resolves: https://musescore.org/en/node/303027

This PR add System Text Lines. System Text Lines are like Text Lines but are attached to a system instead of staff. System Text Lines are implemented as a new type <code>SystemTextLine</code>. This is just a copy of the existing type <code>TextLine</code>.

This could also be implemented by a new <code>system</code> property on the existing <code>TextLine</code> but by implementing <code>SystemTextLine</code> as new type this new type has a dedicated style which is more in line with the 3.0 text style implementation.

By creating a <code>SystemTextLine</code> class it would logical to rename the existing <code>TextLine</code> to <code>StaffTextLine</code>, consistent with <code>SystemText</code> and <code>StaffText</code>. However by doing this a compatibility issue will be created because the class name appears as a tag name in the XML file. This can be corrected but this gives a messy code in the <code>XmlReader</code> and <code>XmlWriter</code> classes.

During MusicXML export, the new <code>SystemTextLine</code> is written as a normal <code>TextLine</code>. This is consistent with how <code>SystemText</code> is handled.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
How is such a new system text line read by MuseScore (3.x) version prior to this? Just ignored?
Wouldn't it, if implemented as a Text Line with a system property, get better read in downrev versions, which then would just ignore that new property rather then the entire line?

**Comment by MarcSabatella** [comment]
Maybe there is some reason this wouldn't work, but I'd be inclined to try having it both ways: going ahead and making it a new class with new next text style etc. but actually writing the tags in such a way that older versions will see it as a normal textline.  I suspect if you literally *only* wrote it as textline with a system tag, the current read code would struggle with readahead a bit just as it does sometimes telling the difference between staff and system text part when importing 2.x scores.  That's because by the time we see the system flag, it's too late.  But here we could use an attribute on the textline tag itself so we create the correct line type right from the beginning.

**Comment by njvdberg** [comment]
> How is such a new system text line read by MuseScore (3.x) version prior to this? 

Older versions silently skip the new SystemTextLines.

> implemented as a Text Line with a system property

For the implementation I looked at <code>StaffText</code>/<code>SystemText</code> and I don't see any <code>system</code> property. As a matter of fact, but I can be wrong, I don't see it anywhere (but I'll never claim I know all ins and outs of MuseScore :-)). 
The current implementation should for users now more consistent.

I thought about downward compatibility (which is the main reason I decided **not** rename <code>TextLine</code> to <code>StaffTextLine</code>, which would be more consistent) but since this is a new type it is fair to say it will be ignored when a file is loaded into an older version of MuseScore.
Mapping onto another type can be dangerous because the score can change without any warning, so users will not be aware. When score is saved using an older version of and again loaded into a version which does support <code>SystemTextLine</code>, the original <code>SystemTextLine</code> is suddenly changed into a <code>TextLine</code> but a a first glace, nobody can tell it item has been change. So nobody will check and after a while, if somebody is looking at the parts, people might find out the original <code>SystemTextLine</code> is actually a <code>TextLine</code>. This might be after a, very, long time.

All in all I think the chosen solution is the best but I realise others might have another opinion. But before we decide for Marc's proposal, which is fine for me too, I will do some tests to see it is feasible. Watch this space :-)

**Comment by MarcSabatella** [comment]
To me it is absolutely worth the extra effort to make sure the line isn't ignored in older versions.

System text is currently implemented as a separate class, but it *used to be* (in 2.0 and before) just staff text with a "system" tag.  Because we completely broke compatibility from 2.0 to 3.0, there was no question of older versions reading newer files - this simply isn't possible at all.  But there will doubtless be people using 3.4 even after 3.5 comes out, and it's important the compatibility works as well as possible.  So I do recommend pursing the approach I mentioned.  Or, perhaps, an alternate approach - writing both sets of tags (systemTextLine, also textLine with system attribute).

The point is, 3.0 - 3.4 and older should be able to see the line and display it on the score.  If the worst that happens is, it isn't copied to parts, I can live with that.

**Comment by njvdberg** [comment]
Writing <code>SystemTextLine</code> to the XML file as <code>TextLine</code> is not straight forward because there is 1-to-1 relation between tag and element name, both in reading and writing the XML file. And to complicate things, text lines are, like other spanners, surrounded by a <code>\<Spanner\></code> / <code>\</Spanner\></code> pair and the <code>Spanner</code> tag also uses the element name as a <code>type</code>. It will require a lot of hacking to get this work. 
And then we have the Copy/Paste, which also uses XML. I guess a lot of change make to read/write the XML file are to implemented here too. All together looks this approach tricky.

Another approach could be extending the existing <code>TextLine</code> with a system flag (as @Jojo-Schmitz already suggested) but with a double set of styles, depending the element has a staff or system scope. Next, in the GUI, there will be still two different types, <code>TextLine</code> and <code>SystemTextLine</code>. So, for the user, text lines will have the same look and feel as text's. But since they are internally mapped onto the same <code>TextLine</code> class both types appear in the XML file as a <code>TextFile</code>, with  a flag specifying the scope, staff/system. When reading such a score into an older version, the flag will be ignored and both <code>TextLine</code> and <code>SystemTextLine</code> will appear as a <code>TextLine</code>.

**Comment by njvdberg** [comment]
Changing to the new approach is more work as expected and really deviating from what this PR tries to do. Therefor I'll close this PR and create a new one for the new approach. Still a few wars to fight with inspectors and so on but I'm getting there :-)

**Pull request closed without merging**
