### PR TITLE
[MU4] Fix GH#14787: Finale Maestro / Broadway: repeat dots appear too low

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: #14787

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Might be easier and shorter to check for Emmentaler, Gonville and MuseJazz?
Or, as these are 'our' fonts', to fix those?

**Comment by Jojo-Schmitz** [comment]
That alternative fix would turn the issue into (a workaround for) "Emmentaler, Gonville, MuseJazz: repeat dots appear too high"

**Comment by cbjeukendrup** [comment]
> Or, as these are 'our' fonts', to fix those?

@oktophonie What do you think about this? Can we reasonably easily fix those fonts themselves?

**Comment by cbjeukendrup** [comment]
I like the latter!

**Comment by Tantacrul** [comment]
I can fix Emmentaler, Gonville and MuseJazz. I may not be able to do it for a few days so perhaps we may need this hack instead.

**Comment by Jojo-Schmitz** [comment]
That hack is in already, I just corrected it to also work for Finale Maestro and Finale Broadway, by simply inverting it.

**Comment by cbjeukendrup** [comment]
@Tantacrul @oktophonie What do you think about merging this for now, and then fixing "our" three fonts later when we have more time, so that we can remove the workaround by that time?

**Comment by Jojo-Schmitz** [comment]
That's indeed the whole and only purpose of this PR ;-)

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/343759
Can we have this for 4.0.2 too, please?

**Comment by cbjeukendrup** [comment]
I've nominated the linked issue for 4.0.2.

**Comment by Jojo-Schmitz** [comment]
Ah, the issue, nit the PR, I see now, thanks and sorry for the noise

**Comment by Jojo-Schmitz** [comment]
Any update on fixing the `repeatDot` position in Emmentaler, Gonville, MuseJazz, so we can get rid of the hacky workaround from this PR here?
See also #27960...

**Pull request merged**
