### PR TITLE
[MU3] Update Bravura to 1.39

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
As taken fresh from https://github.com/steinbergmedia/bravura
Follow up to #4879, which updated it to 1.32

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Most of the vtest differences are very minor and to be expected. But the one for arpeggions is not:
Before:
bravura-8-ref
after:
bravura-8-1
Note the wiggly down arroe arpeggio

**Comment by Jojo-Schmitz** [comment]
that fixed it to this:
bravura-8-1

**Comment by Jojo-Schmitz** [comment]
that fixed it to this:
bravura-8-1

**Comment by Spire42** [comment]
It looks like the vtest is still failing because in the current output of the PR, the wiggles on the downward-pointing arpeggiatos are now left-to-right mirror images of the way they used to look.

If this new output is correct (and according to Gould's *Behind Bars*, it is — I just checked), then you need to update the vtest.

**Comment by Jojo-Schmitz** [comment]
The vtests are showing differences indeed, but they are pretty minor as far as I can tell and there's no need to update the vtests, not for this PR though.
A general overhaul of them all though would be worth a separate PR, one day, maybe after 3.5 release. Many of the score used still stem from MuseScore 2.x... a direct comparison of the ref files with the current ones would show huge differences, this CI_test just compares between 2 subsequent commits, not against those ref files

**Comment by anatoly-os** [comment]
I don't think the issues with the symbols are worth updating the font version. At least, not before fixing those issues.

**Comment by Jojo-Schmitz** [comment]
Fixing what issue?

**Comment by Jojo-Schmitz** [comment]
oops, update to 1.37 needed meanwhile

**Comment by Jojo-Schmitz** [comment]
Hmm, for some strange reason Travis CI doesn't want to run on that 2nd commit

**Comment by Jojo-Schmitz** [comment]
And now updated to 1.39

**Review by vpereverzev — APPROVED** [review]

**Pull request merged**
