### PR TITLE
add violins, violas, violoncellos and contrabasses

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
actually replace "String Section" with "Violins" (and add the other 3).
See https://musescore.org/en/node/56376 (amongst others).
Adjusting Classical Orchestra template and midi import test too.

Also change the abbreviated names of Euphonium to "Euph.", "Tu." to
"Tba." and add "Db.", see https://musescore.org/en/node/56616

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
mtest fails in tst_importmidi, no idea why.

**Comment by lasconic** [comment]
Actually with the test failing, I realize that we do have String section, so I changed my mind and we probably don't need the violins etc... But the euphonium is needed.

**Comment by Jojo-Schmitz** [comment]
Hmm, that "String Section" only covers Violins, as far as the range is concerned, not Violas, Violoncellos or Contrabasses. Could get fixed by extending the range down to the Contrabass', still would be the wrong clefs then on those others, so most certainly this is not the right way.
Or just drop that "Strings Section" and replace with "Violins", then add the other 3?

**Comment by Jojo-Schmitz** [comment]
Hmm, that "String Section" only covers Violins, as far as range and clef are concerned, not Violas, Violoncellos or Contrabasses. Could get fixed by extending the range down to the Contrabass', still would be the wrong clefs then on those others, so most certainly this is not the right way.
So I'd favor dropping that "Strings Section" and replace with "Violins", then add the other 3.

Whoever wants to call them (esp. "Violins")  differently, can do so any time. Likely needed anyway to something like "Violins 1" and "Violins 2".

Opinions?

**Comment by lasconic** [comment]
OK. Let's do this

**Comment by Jojo-Schmitz** [comment]
OK, let's see whether mtest likes it...

**Comment by Jojo-Schmitz** [comment]
Hmm, mtest doesn't like it, but once again Travis isn't generous enough to tell what exactly it doesn't like...

**Comment by Jojo-Schmitz** [comment]
Hmm, mtest doesn't like it, but once again Travis isn't generous enough to tell what exactly it doesn't like...
Seems it still wants the duplication of the channel infos?

**Comment by Jojo-Schmitz** [comment]
Hmm, mtest didn't like it, but once again Travis wasn't generous enough to tell what exactly it didn't like... OK, in the 2nd attempt it did tell.
Seems it still wants the duplication of the channel infos?
Anyway, mtest (and Travis) is happy now. Not sure whether there is more magic needed for the new strings to show up on Transifex.

**Comment by Jojo-Schmitz** [comment]
Ah, I see, it seems the `<init>` causes that duplication

**Pull request merged**
