### PR TITLE
Score tags

### PR DESCRIPTION
**Pull request by Marr11317**
This branch is the rebased version of [this](https://github.com/musescore/MuseScore/pull/3696) pull request.
To resume what was modified:
   - Adds in the meta edit dialog:
       - Translatability fixups
       - Add and remove tags now possible (it was possible to add some,  but not to remove them).
   - A few comments corrections to prevent misunderstandings.
   - Remove a few unwanted tags, like the platform: Linux, in My_First_Score.mscx.
   - as of [shoogle's comment]((https://github.com/musescore/MuseScore/pull/3696#issuecomment-397915254), replace the .mscz with .mscx.
   - In newwizard:
       - Add a more option to be able to edit more tags when creating a new score
       - Save basic settings like composer lyricist, default number of measures, etc. in QSettings.
   - As the end of this work on tags, add an option to automatically track the work number:
       - Every time a new score is created, the work number is incremented;
       - the option contains a suffix and a prefix, and both can be activated or not.
       - The work number can be modified anytime in the prefsdialog.

### CODE REVIEW

**Comment by Marr11317** [comment]
would a screen shot be useful?

**Comment by RobFog** [comment]
For people following MuseScore's development screenshots would be neat. ;-)

**Comment by anatoly-os** [comment]
You don't need to merge changes. You can just rebase your changes on top of the current master:
`git fetch upstream`
`git checkout master`
`git merge upstream/master`
`git checkout yourBranch`
`git rebase master`

**Comment by lasconic** [comment]
I didn't try the PR yet but from the description I'm a bit concerned about two things. Looking forward to a clean PR to try it more in details.

* *Save basic settings like composer lyricist, default number of measures, etc. in QSettings.*
This is good for composers, a lot less for transcribers etc... I'm not sure the majority of users will like to have to delete composer and lyricist for each new score.

* *add an option to automatically track the work number: the option contains a suffix and a prefix, and both can be activated or not.*
One more option, with suffix and prefix. I don't believe we make MuseScore more user friendly by adding more options, especially in the UI. On the contrary, one option at the time, we would make it bloated. And again, this option could be cool for composers, not even sure, but it's not necessary for transcribers, arrangers etc...

**Comment by Marr11317** [comment]
@lasconic 
 _I don't believe we make MuseScore more user friendly by adding more options, especially in the UI_:
_You mean no new options should be added? Or that they should be only accessible via the advanced worskspace (actually, there's that new tab for advanced settings, should I put it there or completely remove it?)?
_This is good for composers, a lot less for transcribers etc... I'm not sure the majority of users will like to have to delete composer and lyricist for each new score._ : Do you think the composers would like to retype their name every time? But you know better than me: I have no idea if MuseScore is used more by composers or transcribers. (once again, I could add this option in advanced preferences)

@anatoly-os Thanks for the advice.

@Jojo-Schmitz I just closed the other pull request

**Comment by Marr11317** [comment]
@lasconic Talking of overwhelming things, to simplify the preferences, would a tree view of the advanced preferences be good? Since the preferences are actually named kind of path-like, wouldn't this would seem logical?

**Comment by Marr11317** [comment]
image
image

**Comment by Marr11317** [comment]
since there was that rebasing problem, move [here] (https://github.com/musescore/MuseScore/pull/3809)

**Pull request closed without merging**
