### PR TITLE
Cleanup leading and trailing whitespace in some strings, getting rid of html in some others

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Also update copyright, change Soundfonts to SoundFonts and midi to MIDI

This is for 2.2, for master see #3453

### CODE REVIEW

**Comment by lasconic** [comment]
Travis error: https://travis-ci.org/musescore/MuseScore/jobs/338891673#L2535

```
/home/travis/build/musescore/MuseScore/mscore/pluginCreator.cpp: In member function ‘void Ms::PluginCreator::runClicked()’:
/home/travis/build/musescore/MuseScore/mscore/pluginCreator.cpp:318:21: error: invalid operands of types ‘const char [3]’ and ‘const char [12]’ to binary ‘operator+’
       msg(tr("  " + "  Version: ") + " " + item->version() + "\n");
                     ^
/home/travis/build/musescore/MuseScore/mscore/pluginCreator.cpp:319:21: error: invalid operands of types ‘const char [3]’ and ‘const char [16]’ to binary ‘operator+’
       msg(tr("  " + "  Description: ") + " " + item->description() + "\n");
```

**Comment by lasconic** [comment]
It would be great if you could make PR on master instead of 2.2. A single direction makes my workflow more predictable :)

**Comment by Jojo-Schmitz** [comment]
Noticed and fix the error. Added another one, copryright year...

**Comment by Jojo-Schmitz** [comment]
Created one for master too, #3453

**Pull request merged**
