### PR TITLE
fix #115191: wrong translation on English (AU)

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
map it to English (GB)

### CODE REVIEW

**Comment by lasconic** [comment]
The correct issue number is #115191
I wonder if en_AU is ok for all the terms that are different between en_US and en_GB, thus my question in the issue tracker.

**Comment by Jojo-Schmitz** [comment]
Well, the user pretty clearly stated that en_GB is desired.

**Comment by Jojo-Schmitz** [comment]
Commit message fixed, the Travis failure got to be unrelated, as it passed before and I didn't change anything but the commit message. I guess 216fa4a i s the culprit

**Comment by lasconic** [comment]
A quick double check with australians and indeed it seems ok.

**Pull request merged**
