### PR TITLE
Implemented new UI sizing for toolbars and home menu

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #9525

### CODE REVIEW

**Comment by Eism** [comment]
@cbjeukendrup is #9525 the actual version UI spec? Do we need to reopen this issue?

**Comment by cbjeukendrup** [comment]
I had contact about this with @jessjwilliamson. The information in that issue is not actual anymore; additional changes have been made on Figma, which is followed in this PR. So I don't think we need to reopen the issue, but I still linked it because it is related.

**Comment by Eism** [comment]
Can you send me a link to the changes? I can't find

**Comment by cbjeukendrup** [comment]
It is on the "--- DRAFT --- TOP BAR AND SIZING UI FIX" page on Figma.

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
