### PR TITLE
Fix #9650 beam stem direction modification

### LINKED ISSUE #9650: [Inspector] Unable to change stem direction in a note group when selecting other than the first note in group
https://user-images.githubusercontent.com/90187801/140068738-26b97894-54e8-491c-9eab-501bf3315dd7.mp4

**To Reproduce**
1. In a group of four eight notes, select 2nd or 3rd or 4th note 
2. Try to change stem direction in Properties - it doesn't work

**Expected behavior**
It should be able to change note goup stem direction  when selecting any note in group

**Additional context**
The same behavior in MU3

### PR DESCRIPTION
**Pull request by LovCAPONE**
Update all notes' stem direction in a beam whenever the user applies
modification to any of them.

When setting a beam's stem direction, the direction is based solely
on the stem direction of the first note of the group. So, if the user
modifies the stem direction of another note in the group, in the
beam's layout process the new value of the direction will be ignored
and the value of the first note in the group will be used.

Fix #9650

Resolves: *https://github.com/musescore/MuseScore/issues/9650*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by LovCAPONE** [comment]
This PR is ready for review.

**Comment by DmitryArefiev** [comment]
Tested #9650 on Win10, Mac12, LinuxMint 20.2 - PASS

@LovCAPONE  Thanks for fixing!

**Comment by DmitryArefiev** [comment]
@RomanPudashkin  Please merge into master

**Review by RomanPudashkin — APPROVED** [review]

**Comment by LovCAPONE** [comment]
@DmitryArefiev You're welcome! If nobody is assigned to issue #9779 then I'll fix it and make a PR.

**Pull request merged**
