### PR TITLE
fix #59306: crash when printing to PDF printer

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Or is it possible that the Qt documentation and header files are just wrong and it really does return a qreal?

**Comment by Jojo-Schmitz** [comment]
PR updated, uses an int again, but makes sure to set it to 1 in case devicePixelRatio() returns a 0.

**Comment by lasconic** [comment]
Same fix applied here https://github.com/musescore/MuseScore/commit/7fbf11fd4ebb5168002f7d4f2f7388f050fc12c6

Thank you for the investigation!

**Comment by Jojo-Schmitz** [comment]
Seems with 89d455f and/or 3e383af and/or 7fbf11f this isn't needed anymore

**Comment by Jojo-Schmitz** [comment]
oops, posts crossed

**Pull request closed without merging**
