### PR TITLE
fix #70861: added vertical spacer below 1st column of page layout & sp

### PR DESCRIPTION
**Pull request by ericfont**
added vertical spacer to clarify that "Staff spacing" is a parameter of "Scaling".
changed "Staff spacing:" to "Staff spacing (sp):" to clarify that is defining the "sp" entity.

### CODE REVIEW

**Comment by lasconic** [comment]
Hi Eric,

We are receiving an email every time your code is built on your travis account. https://travis-ci.org/ericfont/MuseScore Could you change the notifications in .travis.yml ?

**Comment by ericfont** [comment]
I'm sorry, I signed up for travis but never changed the settings.  I've just removed the musescore email and notification from my travis yml and reuploaded to my github.  If you do not get any notification now, that means I've fixed it propertly.

**Comment by lasconic** [comment]
thank you! Fixed. 
There must be a better way to fix this notification settings but I couldn't find it so far.

**Comment by ericfont** [comment]
Maybe have travis.yml query travis api to ask for the user's email address, and use that email address for notification settings?

**Pull request closed without merging**
