### PR TITLE
add instruments to orchestra group

### PR DESCRIPTION
**Pull request by Laurelin**
Added Bass Oboe to instrument list

Removed Contrabass clarinet from Orchestra genre
Added Horns and Trumpets of many keys, Bass Oboe, Oboe d'amore, C Clarinet, Bb cornet, Tenor Trombone, Cimbasso, Ophiceleide(sic) and a few common percussion instruments to orchestra group.

Second try at a pull. Probably better without working off of a two year old master.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Looks much better indeed. I just wonder whether Bariton Obeo shouldn't also be in the Orchestra genre?

**Comment by Jojo-Schmitz** [comment]
Did you already sign the [CLA](https://musescore.org/cla) and if is so under what name?

**Comment by Laurelin** [comment]
I've never seen Baritone Oboe listed on an orchestra score, and I've looked at a *lot* of them. It's always Bass Oboe - Holst calls for it in the Planets, Delius asks for it a few times, but it's always 'Oboe basso', not Baritone. I'm not actually sure who does call it a baritone - England, maybe?

I signed it, Laurelin. That hurt a little - too well trained to not tell people my address on the internet, even if I know it's fairly easy to figure out who I am.

**Comment by Laurelin** [comment]
I'm a little worried that someone who doesn't know that Baritone and Bass oboe are the same instrument will compose for them thinking they're two different, as Baritone and Bass are two different voices. They'd be right on any other instrument, too.

**Comment by Jojo-Schmitz** [comment]
Your address is not exposed to anyone publicly.
I'm not sure about Bariton Oboe, I just go by Wikipedia: https://de.wikipedia.org/wiki/Baritonoboe, which links to https://en.wikipedia.org/wiki/Bass_oboe, https://es.wikipedia.org/wiki/Oboe_bajo and https://fr.wikipedia.org/wiki/Hautbois_baryton
So in German and French it seems to be Bariton, in English and Spanish Bass

**Comment by Laurelin** [comment]
Welches Instrument? They are the same I thought. What other instrument would the English be writing for? English Horn? Now I'm confused, lol.

**Comment by Laurelin** [comment]
Ah, I read it. It wasn't clear whether English composers were writing for Hecklephone or bass oboe. The way it's written sort of implies baritone oboe is the same as hecklephone? There was also a German instrument maker who invented 'die neue Bassoboe' so that probably didn't help with naming confusion.

And you know what, we could solve it via translation. Bass oboe translates to Bass oboe in English, Baritonoboe in German, Oboe basso in Italian, Hautbois baryton in French, etc. If the naming is separated by languages, why not disambiguate via translation ? And then neither German nor English speakers would be confused about an extra of the same oboe.

**Comment by Jojo-Schmitz** [comment]
OK, seems like it, So let's do away with Bariton Oboe. Once it shows on Transifex we can add a comment as to what the translation on those 4 languages shoud be and that way give a hint to translators of other languages

**Comment by Laurelin** [comment]
Do I need to wait for this to be merged, or should I just fix the baritone/bass and submit again? It's been a little while.

**Comment by Jojo-Schmitz** [comment]
Just make the change now.

**Comment by Jojo-Schmitz** [comment]
Continued in #4474

**Pull request closed without merging**
