### PR TITLE
add the 3.1 release to AppData

### PR DESCRIPTION
**Pull request by mirabilos**
it was apparently missed

### CODE REVIEW

**Comment by dmitrio95** [comment]
The previous 3.0.X releases have a lot shorter descriptions in this file, including the 3.0 version itself. Do releases really need to have such a detailed description in AppData?

**Comment by mirabilos** [comment]
Dmitri Ovodok dixit:

>The previous 3.0.X releases have a lot shorter descriptions in this
>file, including the 3.0 version itself.

That’s because they were previously missing and @jurf only added the
quick summary for these when I pointed it out.

>Do releases really need to have such a detailed description in AppData?

I don’t know… I just copied from the release notes.

**Comment by jurf** [comment]
I used to include the whole changelog, but that created tonnes of warnings with `appstream-util validate`. Turns out the release info should be ideally [a few sentences](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases), not the whole changelog so I started just using the intro from the [release page](https://musescore.org/en/3.1), something like this would be fine (slightly modified version):

> MuseScore 3.1, in addition to hundreds of bug fixes, introduces some new features (including single-note dynamics) and significant improvements related to playback, automatic placement and layout, fretboard diagrams, and performance.

**Comment by mirabilos** [comment]
@dmitrio95  Updated with the text from @jurf and rebased.

**Comment by dmitrio95** [comment]
@mirabilos, @jurf, thanks!

**Comment by ovari** [comment]
Should this show at https://flathub.org/apps/details/org.musescore.MuseScore? Thank you

**Comment by mirabilos** [comment]
ovari dixit:

>Should this show at https://flathub.org/apps/details/org.musescore.MuseScore? Thank you

After being merged then occurring in a release, yes.

(Also, don’t forget to add the 3.2 release with the exact date ☻)

**Comment by jurf** [comment]
@ovari I’ll add it tomorrow. :slightly_smiling_face:

**Pull request merged**
