### PR TITLE
Fix #16396: Tie invisibility crossing system breaks

### LINKED ISSUE #16396: Issues with tie invisibility when crossing system break
**Describe the bug**
First issue with tie invisibility: If you tie a note, make the tie invisible, then make the invisible tie go over a system break, the portion of the tie after the system break is visible and the keyboard shortcut 'v' doesn't do anything either. You either have to press v twice on the part of the tie before the system break, or you can also press the 'visible' checkbox in the Properties panel twice.
Second issue: If you copy and paste anything with invisible ties, the ties are visible after the paste and the only way to make them invisible is with the checkbox in Properties.
Additionally, the checkbox in the Properties tab will report the incorrect state for the tie, believing that it is invisible when it is not.

**To Reproduce**

https://user-images.githubusercontent.com/21023353/219411803-7b063ee2-9780-4537-9fa2-afa16de51e0b.mp4

**Expected behavior**
The ties should be invisible when I tell them to be

**Platform information**
 - OS: Reported on Windows

**Additional context**
This was an issue in MS3 too, not just MS4

### PR DESCRIPTION
**Pull request by XiaoMigros**
Resolves: #16396

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
I found that there are some similar problems:
- For ties, the same applies to the "color" property too
- For slurs, it also applies to the "color" property, but seemingly not to the "visible" property
- For glissandos, it applies to the "visible" property but seemingly not to the "color" property

There may be even more cases. And perhaps there are even more properties to which this applies, for example the "auto-place" property. 
So we should either fix all cases separately, or look if a more general solution can be found.

**Comment by Jojo-Schmitz** [comment]
tie color and glissando visibility seem easy to fix (1-liner each), slur color not so much (haven't found a way yet)

**Comment by Jojo-Schmitz** [comment]
Actually that's a 1-liner too...

**Comment by Jojo-Schmitz** [comment]
But @cbjeukendrup is right: AutoPlace is affected too

**Comment by Jojo-Schmitz** [comment]
albeit different: it disconects regardless whether set before apply a system braek or after, so seems a different issue altogether

**Comment by XiaoMigros** [comment]
Thanks @Jojo-Schmitz for finding the places for slurs and glissandos! I agree that autoplace is a different issue, since this PR currently only changes the visual rendering of the elements and not any actual properties themselves.

**Comment by Jojo-Schmitz** [comment]
Same issue and fix applies to GuitarBend, as far as I can tell
Might apply to Beam too

**Comment by XiaoMigros** [comment]
Guitar bends seem fine in master (both visibility and color)

**Review by mike-spa — COMMENTED** [review]
There should be a more elegant solution IMO. We have a method called `propertyDelegate` which is used by SpannerSegments to "delegate" a given property to their Spanner. If you look at `SpannerSegment::propertyDelegate` you'll see that `visible` and `color` are already delegated. Problem is that calling the `visible()` method returns the internal value directly and bypasses the property routing. I think this may be solved by just calling `item->getProperty(Pid::VISIBLE)` rather then `item->visible()`.

**Comment by Jojo-Schmitz** [comment]
I guess it'd need to be `item->getProperty(Pid::VISIBLE).toBool()`

**Comment by XiaoMigros** [comment]
My understanding would be `PropertyValue::fromValue(item->getProperty(Pid::COLOR))`

**Comment by mike-spa** [comment]
> My understanding would be `PropertyValue::fromValue(item->getProperty(Pid::COLOR))`

Yep!

**Comment by cbjeukendrup** [comment]
`PropertyValue::fromValue(item->getProperty(Pid::COLOR))` doesn't make a lot of sense, because `getProperty` already returns a PropertyValue, so that expression would be equivalent to (but less performant than) just `item->getProperty(Pid::COLOR)`.
If you want to retrieve the property value as a `Color` type, then `item->getProperty(Pid::COLOR).value<Color>()` is probably what you want.

**Review by oktophonie — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
As far as I can tell this here is just waiting to get merged?

**Pull request merged**
