### PR TITLE
Turn upper case first letters of Sid's to lower case

### PR DESCRIPTION
**Pull request by Howard-C**
For consistency

### CODE REVIEW

**Comment by riaanvn** [comment]
Does this PR contain strings? If so, @anatoly-os pls label it.

**Comment by Howard-C** [comment]
> Does this PR contain strings? If so, @anatoly-os pls label it.

No, only `Sid` enum ids.

**Comment by Jojo-Schmitz** [comment]
Well, it containst strings, even translatables ones, but doesn't change any of them, which is what the "Strings" tag is about

**Comment by Howard-C** [comment]
> Well, it contains strings, even translatables ones

What exactly? I don't see one.

**Comment by Jojo-Schmitz** [comment]
Opps, sorry, now I don't see any myself ;-)

**Comment by Jojo-Schmitz** [comment]
rebase needed

**Comment by Howard-C** [comment]
Is this PR really valid? If the `Sid`s are used in plugins, this can probably make some plugins unusable. Do we want to risk this?

**Comment by vpereverzev** [comment]
Looks like PR is hanging
We can't rename any **Sid**s because of existing plugins

**Pull request closed without merging**
