### PR TITLE
Inspector: fix applying offsets to style

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Splitting properties over multiple PropertyItems turns out to cause problems.

Resolves: #13077

### CODE REVIEW

**Comment by RomanPudashkin** [comment]
> @RomanPudashkin I see that in commit [cdd36db](https://github.com/musescore/MuseScore/commit/cdd36db14e3faddfd3c5c321b130d3d3f9998c50) you removed the ability so set the horizontal offset because that was "undesired". What's undesired about it?

This question should be addressed to @Tantacrul or @bkunda

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Tantacrul** [comment]
@cbjeukendrup - I don't quite recall making any decision about horizontal offset one way or another. Could you possibly describe the problem from the user's POV? What objects are we talking about?

It may be the case that we hid horizontal offset for certain items because (in specific cases), it was a useless option.

**Comment by cbjeukendrup** [comment]
It concerns almost all elements from the Lines palette; specifically it affects what you see in the "Text" tab in Properties.
Scherm­afbeelding 2022-09-29 om 11 32 06
With this PR, you will see a full offset control, before, it was only a vertical offset field. 

It might be that horizontal offset is not applicable in all cases, but in some cases it is absolutely useful. So I propose to expose the setting anyway for now, and later we can build complicated logic to hide it in certain cases where it is less useful.

**Comment by Tantacrul** [comment]
> It might be that horizontal offset is not applicable in all cases, but in some cases it is absolutely useful. So I propose to expose the setting anyway for now, and later we can build complicated logic to hide it in certain cases where it is less useful.

What are the cases where it is useful?

I would be more inclined to not show it unless there is a really strong case.

**Comment by MarcSabatella** [comment]
In MU3, changing the horizontal offset for text on lines was, as far as I can tell, the same functionally as adjusting the left endpoint.  So it was in that sense useless, and I might guess that is why it was removed.

But, in my opinion it *should* have done something better all along - it should have moved the text relative to the line.  So you can have text closer or further from the actual start of the line than the default.  That would be useful for any number of custom line types, including things like using an arrow or some other Unicode character as the text.

**Comment by DmitryArefiev** [comment]
Tested #13077 on Win10, Mac12, LinuxMint 20.2 - **FIXED**

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Should I check other things except described in #13077 ?

**Comment by cbjeukendrup** [comment]
@DmitryArefiev Except for the offset control in Appearance > Offset, the other offset controls are also fixed now:
- Notehead offset in Notehead > Show more
- Stem offset and Flag offset in Stem > Show more
- For text offset, the horizontal offset setting is back, because that setting is necessary to create certain kinds of custom text lines. In the future we might want to tweak the behaviour of this setting, or we might want to hide it under certain circumstances (although I don't see any advantage in that). But for now it is just visible and working as in MU3.

**Comment by Tantacrul** [comment]
I've tested all of these and they seems good to go.

I am a little unhappy with adding back in the horizontal offset option (because it is broadly valueless) but as @MarcSabatella says, we can always make it do something valuable in future.

Let's leave for now and keep on truckin' through the rest of the issues!

**Pull request merged**
