### PR TITLE
100501 expose key sig key

### PR DESCRIPTION
**Pull request by jeetee**
Depends upon https://github.com/musescore/MuseScore/pull/2408.

### CODE REVIEW

**Comment by jeetee** [comment]
If someone could figure out why that macro isn't working in this case, but does in https://github.com/musescore/MuseScore/pull/2408 I'd be very interested, as this PR should be about simply using the macro.

On that note, if anyone knows how to get the preprocessor output (working with Qt Creator on Windows7 here) that would be good enough as well, allowing me to compare the actual expansion with my expectation

**Comment by lasconic** [comment]
Try to add -E in the CXX flags?
Le 5 mars 2016 5:44 PM, "Johan Temmerman" <notifications@github.com> a
écrit :

**Comment by jeetee** [comment]
Slightly stumped again: Travis is failing on the step that this last comment-commit fixes for me locally (Win7/QtCreator)

**Comment by lasconic** [comment]
Travis is running Qt 5.4.2.
If you are using something else, moc can behave differently.

**Comment by jeetee** [comment]
As stated on IRC as well. I'm also on 5.4.2.
Some more investigation in how moc works / can be fooled will be required.

**Comment by jeetee** [comment]
@heuchi Any chance you can spare some of your time to help look into this? I still seem unable to build locally without the comment...

**Comment by heuchi** [comment]
I can build locally redefining the macro just before it's used in key.h
(See <a href="https://github.com/heuchi/MuseScore/compare/285ceebd56ad029e3132507d108eff02ed5a1609...heuchi:tmp-testQMLEnums">my local test branch</a>)
So maybe using the macro with moc only works if the term Q_GADGET appears somewhere in the same file. It might be not sufficient to only include the file.

**Comment by heuchi** [comment]
I just found this in <i>man cmake-qt</i>
<pre>If a Q_OBJECT or Q_GADGET macro is found in a header file, moc will be run on the file.</pre>
This seems to support my theory.
So to me it looks like we have to options:
<ol><li>Somehow add G_GADGET (or Q_OBJECT) to key.h</li><li>Move the definition of enum Key to mscore.h or some other header file that contains Q_GADGET or Q_OBJECT</li></ol>

**Comment by heuchi** [comment]
A summary of what I found:
I think the problem is caused by how <a href="https://cmake.org/cmake/help/v3.2/prop_tgt/AUTOMOC.html">cmake's AUTOMOC decides on what files to run Qt's moc</a>:

Since there is no include statement for a .moc file and no occurrence of Q_OBJECT or Q_GADGET in <i>key.h</i>, moc is not run on it. 

Fooling cmake to run moc on <i>key.h</i> anyway is a little more difficult than I would have hoped. The easiest way I found is adding this:
<pre><code>/* make AUTOMOC run moc on this file
      Q_GADGET
   for MS_QML_ENUM macro to work */
</code></pre>
Things I tried that do not work include
<pre><code>#define AUTOMOC_HELPER Q_GADGET
// Q_GADGET
/* G_GADGET */
</code></pre>
Setting CMAKE_AUTOMOC_RELAXED_MODE to TRUE didn't help, either.

**Comment by jeetee** [comment]
Wow! I was out this weekend, but didn't expect this much detail so soon. Awesome!
I've bookmarked that cmake manual link, as the Windows-me doesn't have _man_

@lasconic: want me to clean up the comment with @heuchi 's findings? Or do you (and/or werner) prefer a different approach to forcing moc?

**Comment by jeetee** [comment]
Writing up the test revealed that fixing up the enum for setKey is not enough.

issue 1: negative numbers in the enumeration whilest key() returns the wrapped positive value for it (previous enums where positive numbers only, so I missed that)

issue 2: setKey doesn't affect undostack as expected:
upon assigning a new key, the score is not modified and the key signature 'disappears'.

- scenario 2a.
Run plugin.
Switching viewmode (page/continous) shows/restores the old key signature again.

- scenario 2b.
Run plugin.
Run it again: log seems to indicate the key signature did change!
Click where it should be; inspector indicates 'invisible' key signature to be selected and visible.
Toggle the visibility (either by inspector or 'V') --> old key signature shown as invisible signature
Undo (CTRL-Z) --> new key signature shows up, but score is marked as not modified..

**Comment by anatoly-os** [comment]
Since this functionality is pending so long and there are no more reuests for this feature, let's close this PR until more use cases appear.

**Comment by jeetee** [comment]
Fair enough, it required some backend fixes I apparently didn't consider a high enough priority up until now. It'll be far easier to redo the limited work I did against master should the need arise once more.

**Pull request closed without merging**
