### PR TITLE
Rename upNote to highestNote and downNote to lowestNote for clarity

### PR DESCRIPTION
**Pull request by Marr11317**
Sometimes when searching in the codebase, it is simpler to search for common terms and hope the element/function/etc. has been named that way.

### CODE REVIEW

**Comment by Howard-C** [comment]
I'd vote against this change. The original way is short and not hard to understand, and experienced developers are already accustomed to `upNote` and `downNote`. There should be some discussion before doing such changes.

**Comment by njvdberg** [comment]
I agree with @Howard-C and vote against this PR. Besides the mentioned reasons, such changes might cause merge issues.

**Comment by Marr11317** [comment]
Two things, I think such changes are necessary to progressively clean up the code base, and do agree that it might cause merge conflicts. However, in the long term, as the code base gets bigger and bigger, such changes will be needed.
Another thing: as you say, it will probably cause merge conflicts. That also means that this PR will have to be rebased often. As there is clearly more important matters, I won't want to rebase it too often, or it will simply be lost time.
If you believe the function itself should not get it's name modified, one option would be to only keep the comments: https://github.com/musescore/MuseScore/pull/5746/files#diff-428e0bb12d899d2d494b3cc99e75e22fR67.
This would avoid any merge conflict, would allow someone doing a global codebase search of `topNote`, `highestNote`, `bottomNote`, and `lowestNote` to find what he is looking for.

> Such changes might cause merge issues.
I think cleaning the codebase should prevail over merge conflicts

> The original way is short
When mentionning that in Telegram, I was answered with `autocomplete`

> The original way is not hard to understand
It's not about understanding. It's about newcomers that want things to be how they are really called

> experienced developers are already accustomed to upNote and downNote
Shouldn't be hard to get used to highestNote and lowestNote either. And way easier for newcomers.

> There should be some discussion before doing such changes.
There has been such a discussion in telegram

**Comment by njvdberg** [comment]
> one option would be to only keep the comments
I agree with you here. As a matter of fact, some more comments on what a method is supposed to do could be very helpful (a good lesson for myself :-))

**Comment by Marr11317** [comment]
rebase needed.
I won't rebase it knowing it will never get merged. Given that apparently a consensus will never get reached, I close the PR for now.

**Pull request closed without merging**
