### PR TITLE
fix #100396: change "note heads" to "noteheads"

### PR DESCRIPTION
**Pull request by ZackTheCardshark**

### CODE REVIEW

**Comment by MarcSabatella** [comment]
This does not really make it consistent.  We still use the term "head" by itself in a few places - "Head group", "Head type", and "Mirror head" in the Inspector, for example.  I personally think we should leave it alone and intead fix the documentation, but if we do decided "notewhead" needs to be a single word, we should use it what way consistently and note allow uses of "head" by itself.

**Comment by ZackTheCardshark** [comment]
I think "head" by itself is not inconsistent. After all, a windowsill is also a sill, a basketball is also a ball, and a rattlesnake is also a snake—even though we do not respectively call them window sills, basket balls, and rattle snakes.

**Comment by ZackTheCardshark** [comment]
As to basketball, see also the words football, baseball, softball, and snowball. ;-)

**Comment by MarcSabatella** [comment]
OK, point taken, although I'm still unconvinced of the need for the change.

**Comment by ZackTheCardshark** [comment]
Anybody else have any thoughts on this? I don't think it's correct to leave it at "note head", any more than it's correct to refer to a back bone or a counter top.

**Comment by MarcSabatella** [comment]
What is your source for that claim?

**Comment by ZackTheCardshark** [comment]
My own sense of what I've usually seen. And, as stated, it's what Sibelius and Finale both use.

Which does Elaine Gould use? I'm prepared to immediately back down if she uses "note head."

**Comment by MarcSabatella** [comment]
She uses "notehead", but that still doesn't make "note head" wrong.  FWIW, the New Harvard Dictionary of Music uses "note head".  And a simple Google search for the phrase turns up tons of hits, leading off with the Wikipedia article of that name, followed by the LilyPond documentation for that feature, also documentation for the Sonata font - the original music notation font - and other quite authoritative sources.  It seems absolutely without question to me that this is a completely valid term in very common use.  The same is true for "notehead", no doubt.

Again, I'm not *opposed* to the change, I just don't understand the rationale - it seems like gratuitous extra work for translators with no advantage to anyone.

**Comment by ZackTheCardshark** [comment]
Do the translators have to do anything? I would think they would be using the most correct term in their respective languages already.

**Comment by ZackTheCardshark** [comment]
By the way, as to work, changing the documentation to reflect the software looks like it would be more complicated—dozens of "noteheads" in the Handbook, versus three "note heads" in MuseScore 2.0.2.

**Comment by lasconic** [comment]
About translations, the english sentences work as a key. If the key changes, translators need to translate again.

**Comment by ZackTheCardshark** [comment]
Well, now is the time when the translators will be active: https://musescore.org/en/node/102146

But I'd like to remind you that this is far from unprecedented: https://github.com/musescore/MuseScore/pull/2216/files https://musescore.org/en/node/77186

**Comment by RobFog** [comment]
Good idea!

**Comment by MarcSabatella** [comment]
Yes, but that was a change that fixed inconsistency within the UI, changing on the bare minimum of instances to be consistent with how it was wored in the majority of places.  So, it was broken before (inconsistent), the change fixed it (made it consistent), and it fixed it with the least amont of changes and thus the least amount of retranslation required.  None of these statements apply to the PR at hand.

**Comment by ZackTheCardshark** [comment]
I'm counting "the majority of places" as including the website, so I see the "bare minimum" of instances as being these three. We're asking the translators to verify this one word that occurs *three times* in the entire software—that's about as insignificant as you can get. I'm having a really hard time understanding why this should be controversial.

BTW, thanks, Rob!

**Comment by MarcSabatella** [comment]
Again, I'm not *opposed* t the change.  I just don't see understand the problem the change is intended to solve, so I don't see the *need* for the change.  From where I sit, It appears to be a gratuitous change from one correct and universally recognized wording to another equally correct and universally recognized wording.  What is the benefit?

**Comment by ZackTheCardshark** [comment]
That it <i>is</i> inconsistent between dozens of places in the documentation and three places in the software.

**Comment by MarcSabatella** [comment]
Fair enough.

**Comment by MarcSabatella** [comment]
But FWIW, it's more than just those strings.  I also see "note head" in element.cpp, note.ui, editstyle.ui, and masterpalette.ui.

**Comment by ZackTheCardshark** [comment]
I can't remember what type of search I did that convinced me it was only used in those three places, but whatever it was did. Now I'm embarrassed.

However, I still feel that "notehead" wins the tug-of-war, and "note head" should be the one to give. Gould used the former for a reason, and a couple of StackExchange experts [found good references for it](http://music.stackexchange.com/questions/42722/notehead-or-note-head) (it turns out reputable dictionaries define "notehead" and don't define "note head"). But I do accept that rightly or wrongly, "note head" is also common. Given the further four places "note head" is used in the software, I guess the work is six of one and a dozen of the other whichever way we change.

**Pull request closed without merging**
