### PR TITLE
tempo_slider

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/15385

### CODE REVIEW

**Comment by DmitryArefiev** [comment]
Tested #15385 on Win10, Mac12, LinuxMint 22.04 - **FIXED**

**Comment by daddadpfc** [comment]
Thank you for all the work on this. Is there a way I could test the result or will I have to wait for 4.0.2?

**Comment by DmitryArefiev** [comment]
> Thank you for all the work on this. Is there a way I could test the result or will I have to wait for 4.0.2?

@daddadpfc Sure! Can you try this build please?  https://github.com/musescore/MuseScore/actions/runs/3996457128

**Comment by GeertWil** [comment]
Hi. I downloaded the build mentioned above. It seems to contain only a Mac version, so I am not able to give it a try. I also downloaded the latest nightly build. That version doesn't allow any playback at all. After pressing the play button, the play head moves to the start of the score, moves 1 mm and nothing else happens. No playback at all.
If your changes are not yet merged into the nightly build, then both problems are not related of course.

**Comment by DmitryArefiev** [comment]
> Hi. I downloaded the build mentioned above. It seems to contain only a Mac version, so I am not able to give it a try. I also downloaded the latest nightly build. That version doesn't allow any playback at all. After pressing the play button, the play head moves to the start of the score, moves 1 mm and nothing else happens. No playback at all. If your changes are not yet merged into the nightly build, then both problems are not related of course.

@GeertWil Correct. I've added a link to Mac build for testing because @daddadpfc mentioned MacOS in his environment 

Here are for Windows and Linux:
https://github.com/musescore/MuseScore/actions/runs/3996457129
https://github.com/musescore/MuseScore/actions/runs/3996457132

Please try them

**Comment by GeertWil** [comment]
Hi Dmitry. This version works like a charm. Wonderful, thank you very much. I can start practising at reduced speeds again.
(The playback in the regular version started working again after a system restart)

**Comment by DmitryArefiev** [comment]
Cool. Thanks for testing!

**Comment by daddadpfc** [comment]
Hi Dimitry

unfortunately this build was not accepted on my system. I placed it in the
App folder. Any suggestions?

[image: Screenshot 2023-01-27 at 06.34.57.png]

**Comment by cbjeukendrup** [comment]
@daddadpfc Maybe these instructions help: https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#macos

**Comment by daddadpfc** [comment]
many thanks

**Comment by daddadpfc** [comment]
Fantastic. it works it works. Thank you thank you. Everybody take the rest of the week off

**Review by vpereverzev — APPROVED** [review]

**Pull request merged**
