### PR TITLE
Build AppImage with Qt 5.12.4 in Ubuntu 18.04 environment

### PR DESCRIPTION
**Pull request by dmitrio95**
The upgrade should also fix [284164](https://musescore.org/en/node/284164) and, possibly, [288662](https://musescore.org/en/node/288662).

### CODE REVIEW

**Comment by shoogle** [comment]
For maximum portability, AppImages should always be built against the *oldest* distribution that you want to support. Building against Ubuntu 18.04 means that AppImages will not work on any distribution released prior to 18.04. This is one of the reasons why Travis CI and others always avoid upgrading their default build environment until the last possible minute.

Ubuntu 14.04 was still supported by Canonical until April, so it is probably no coincidence that those bugs have just started to show up now. Ubuntu 16.04 is still supported for another couple of years, so it should be safe to use it until then.

I will test on 16.04 and check that those issues have disappeared and then submit a PR to "downgrade" if that's the case. I was going to create a PR to upgrade to 16.04 anyway before this one was merged, so it doesn't mean any extra work.

By the way, the rule about "always use the oldest version" doesn't apply to things like Qt that get bundled inside the AppImage. If we bundle something then we know that it will be present on the user's computer, so we may as well give them the newest version. On the other hand, if we don't bundle something (such as the C++ standard library) then there is no guarantee that it will be present on the user's machine, so we have to use the oldest version to maximise the chance that it will be present.

**Comment by dmitrio95** [comment]
Packaging with Ubuntu 16.04 required adding some `libmirclient` libraries into AppImage (it just doesn't work otherwise, didn't test it with the added libraries though), that is why I proposed building it with 18.04 instead. But if using 18.04 version causes some compatibility issues then getting it to work with Ubuntu 16.04 may indeed be a better choice. 

> those bugs have just started to show up now

The OpenSSL version bug was present since a long time ago, it happens due to a [Qt bug](https://bugreports.qt.io/browse/QTBUG-68156) that was reported first in May 2018. So at least this issue is not related to the Ubuntu version being used.

**Comment by dmitrio95** [comment]
@shoogle if we need something older but mostly compatible with other distributions, can perhaps Debian Oldstable (Debian 9 currently) be used? Ubuntu 16.04 doesn't look like a good candidate because of a large number of Mir-related dependencies which will certainly be not present anywhere except Ubuntu and thus need to be packaged inside AppImage.

**Comment by shoogle** [comment]
@dmitrio95, Debian Oldstable would be idea for compatibility, but you might end up having to compile some of the dependencies yourself since everybody else builds on a more recent distro. Mind you, I've heard that Qt's official binaries are build on an ancient version of CentOS, so it should certainly be possible.

However, I've got it working very well on Ubuntu in #5200, so do check that out. Library bundling there is now a fully automated process, so it should be fairly straightforward to switch to a different distribution if required.

**Pull request merged**
