### PR TITLE
fix #107936 - [MusicXML] crash when divisions is defined in second me…

### PR DESCRIPTION
**Pull request by lvinken**
…asure but used in first measure

### CODE REVIEW

**Comment by lasconic** [comment]
Why 1/4 if I may ask?

**Comment by lvinken** [comment]
In this case, we have an incorrectly encoded MusicXML file starting with a full measure rest of unknown size. Either the measure must stay empty (which leads to issues later, thus to more complex code), or a default value must be provided. There is no particular reason why one value would be better than another, 1/4 is a more or less random choice.

Note that for this particular issue, the intended meaning of the encoded music is easily guessed (a 3/4 full measure rest), but to detect this would require a third pass on import, which IMHO takes too much effort to implement and would probably cost too much run time to consider.

**Comment by lasconic** [comment]
If 1/4 is a random choice, and so we can pick anything else and it would work, it's probably better to take 4/4, I think we do assume this to be the default in other part of the code.

**Comment by lvinken** [comment]
Fine with me, will change accordingly and push again.

**Comment by lasconic** [comment]
Thanks !

**Comment by lvinken** [comment]
Done !

**Comment by lasconic** [comment]
Thanks!

**Comment by lasconic** [comment]
I should have told you before but could you squash the two commits? http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by lasconic** [comment]
That's fine. Let's live with the two commits.

**Pull request merged**
