### PR TITLE
Move Diagnostics menu and re-arrange Help menu

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: https://github.com/musescore/MuseScore/issues/25015

Dev mode disabled: 
Scherm­afbeelding 2024-10-04 om 22 14 40

Dev mode enabled:

https://github.com/user-attachments/assets/99691d56-8c4a-4fc0-9471-8d70552140be

(Sorry, it's Dutch, but you get the idea)

### CODE REVIEW

**Comment by RomanPudashkin** [comment]
It looks so weird, imo. Diagnostics should either always be inside the Help menu or always outside of it (regardless of whether dev mode is enabled or disabled). The new behaviour is going to be very confusing

**Comment by cbjeukendrup** [comment]
It was @DmitryArefiev's request to have it quickly available in dev mode, because he needs it often. At the same time, we were quite convinced that the Diagnostic menu should not be unnecessarily exposed in release builds because it's useless 99.9% of the time.

**Comment by avvvvve** [comment]
+1 to @cbjeukendrup's comment

I don't know if there's a way to test the release version, but it looks good based on your screenshot!

One thing with dev mode: I know "Help" typically comes last in the list of menu options, but I think we should keep "Diagnostics" last in the menu list (after "Help") for dev mode as it was before. That way "Help" is always visually in the same spot in both dev and release modes.

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
> ..but I think we should keep "Diagnostics" last in the menu list (after "Help") for dev mode as it was before

@cbjeukendrup Yes, I vote for this too. 

Also, I have a **crash** when clicking any item in Help menu (Win10)

**Comment by cbjeukendrup** [comment]
> I think we should keep "Diagnostics" last in the menu list (after "Help") for dev mode as it was before.

This is implemented now.

I can't reproduce the crash on macOS, and don't have access to Windows today. Is it really certain that it is caused by this PR?

**Comment by DmitryArefiev** [comment]
In the latest build (where Diagnostics goes after Help), the **crash doesn't occur** on Windows

Tested on Win10, Mac13.6, LinuxUbuntu22.04.1 LTS - **PASS**

**Review by avvvvve — APPROVED** [review]

**Pull request merged**
