### PR TITLE
fix #24056 - crash on append vbox

### LINKED ISSUE #24056: Crash when appending a vertical frame
### Issue type

Crash or freeze

### Description with steps to reproduce

Select last bar
Go to "Add"
Select "vertical frame"

### Supporting files, videos and screenshots

[Diagnostic.zip](https://github.com/user-attachments/files/16627870/Diagnostic.zip)

https://github.com/user-attachments/assets/feeee853-701f-4481-ba19-8ab637528af4

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242261344, revision: github-musescore-musescore-f46cdec

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

_No response_

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by sammik**
Resolves: #24056 

forgotten nullcheck added

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
@sammik Could you please also create a version for the 4.4.0 branch? Thanks in advance!

**Comment by Jojo-Schmitz** [comment]
Done...

**Comment by sammik** [comment]
> @sammik Could you please also create a version for the 4.4.0 branch? Thanks in advance!

I've got people.

Thank You @Jojo-Schmitz !

**Comment by Jojo-Schmitz** [comment]
It is just a few mouse clicks with GitHub Desktop ;-)

**Pull request merged**
