### PR TITLE
Add support for triple sharp and triple flat

### PR DESCRIPTION
**Pull request by mattmcclinch**
SMuFL provides glyphs for triple sharp and triple flat, so they might as well be available to use in MuseScore. This involves adding 14 new TPCs and expanding the range of the AccidentalVal enum class.

This was requested on the forum topic [Triple sharps and triple flats](https://musescore.org/en/node/304503).

See https://seanyeh.com/pages/alkans_triple_sharp/ for an example of a triple sharp being used in a piece of music from the Romantic period.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I was looking into this too today and my changes look surprisingly similar to your's, only that mine doesn't yet fully work  ;-)
Seems you got those places to work where my code wasn't working.

**Comment by Jojo-Schmitz** [comment]
Missing is the translatability of the qlyph names

    $ git diff libmscore/sym.cpp
    diff --git a/libmscore/sym.cpp b/libmscore/sym.cpp
    index d8e18e9be..054b0e21b 100644
    --- a/libmscore/sym.cpp
    +++ b/libmscore/sym.cpp
    @@ -3143,8 +3143,8 @@ const std::array<const char*, int(SymId::lastSym)+1> Sym::symUserNames = { {
           "Three quarter tones sharp (Bussotti)",
           QT_TRANSLATE_NOOP("symUserNames", "One and a half sharps (three-quarter-tones sharp) (Stein)"),
           "Three-quarter-tones sharp (Stockhausen)",
    -      "Triple flat",
    -      "Triple sharp",
    +      QT_TRANSLATE_NOOP("symUserNames","Triple flat"),
    +      QT_TRANSLATE_NOOP("symUserNames","Triple sharp"),
           "Two-third-tones flat (Ferneyhough)",
           "Two-third-tones sharp (Ferneyhough)",
           "Wilson minus (5 comma down)",

**Comment by Jojo-Schmitz** [comment]
On top of the needed rebase, please also see #6263 and add the MusicXML im-/export for these accidentals here too

**Comment by Jojo-Schmitz** [comment]
Seems `inspector_ambitus.ui` would probably need to get adjusted too to allow for all these triple sharp/flat notes.
Once added there, it could/should get added to `notenames.qml` too.

**Comment by Jojo-Schmitz** [comment]
still needs a rebase

**Comment by Jojo-Schmitz** [comment]
Still needs a rebase
Would be nice to have for 3.6 (3.x) and 4 (master)

**Comment by mattmcclinch** [comment]
Given that this was not a very popular idea on the original thread, I guess I have been waiting to hear more people speak up in favor of this before spending any time rebasing.

**Comment by Jojo-Schmitz** [comment]
I'd think it be a pity to not have this in 3.x (and later master too)

**Comment by Jojo-Schmitz** [comment]
Also that discussion pretty much digressed into politics. And also talked about triple sharp/flat in key signatures, which isn't the scope of this PR anyway (and there are no double flat/sharp key in signatures either)

**Comment by mattmcclinch** [comment]
Replaced by #6762 (thanks @Jojo-Schmitz!).

**Pull request closed without merging**
