### PR TITLE
Fix MSVC compiler warnings

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
* reg.: unreferenced formal parameter (C4100)
* reg.: conversion from 'size_t' to 'int', possible loss of data (C4267)

there's one warning left:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4702	unreachable code	braille	...\src\braille\internal\braillecode.cpp	1030	
```
which I don't understand, code in question:
https://github.com/musescore/MuseScore/blob/1df93bbf23ad3bc66fe492a12331d1b6a11578ab/src/braille/internal/braillecode.cpp#L1025-L1044
Possible fix:
* reg.: unreachable code (C4702)
* reg.: declaration hides function parameter (C4457)
* Some 1000 warnings C4996, all in internal VS code,  'xutility', lines 1141, 1255 and 1256 and '__msvc_iter_core.hpp', lines 488-492, nothing we can fix, so disabled it.

And now also a compiler error:
* reg.: undeclared identifier (C2065)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
See #20031 for the unit test failure

**Comment by cbjeukendrup** [comment]
About that other warning: it's indeed a bit cryptical, but might relate to the fact that there's a `return` statement at the end of the body of the for loop, causing it to be executed at most once and thus making the loop unnecessary. It's indeed a slightly suspicious situation. @shoogle Could you please double-check that piece of code?

**Comment by Jojo-Schmitz** [comment]
I see! And guess what it really is ment to be, @shoogle, please check

**Comment by shoogle** [comment]
@Jojo-Schmitz, the braille code was written by @TuanLa1972. The `findBrailleCode()` function doesn't appear to be used anywhere, but my guess is `return br;` was correct (i.e. your change is wrong) and the two `return nullptr;` lines above were supposed to be `continue;` instead.

**Comment by Jojo-Schmitz** [comment]
Ah, I see, my guess wasn't just wrong, it was downright bad, thanks!
Amended to follow your sugggestion.
@TuanLa1972 please review.
If it is unused code though, we might as well just remove it?

**Comment by TuanLa1972** [comment]
Sorry to say that I don't remember what idea was behind
findBrailleCode()function.
Please remove it.
Also, some other findXXX functions in braille.h aren't used anywher and
they can be removed too.
I guess we've changed the algo and they are not necessary anymore.

Vào CN, 19 thg 11, 2023 vào lúc 06:53 Peter Jonas <
***@***.***> đã viết:

**Comment by Jojo-Schmitz** [comment]
OK, removed

**Review by shoogle — APPROVED** [review]
I'm happy with the Braille `find...` functions being removed. They are not used anywhere.

The other changes seem reasonable as well.

**Comment by Jojo-Schmitz** [comment]
Now I also got and fixed a compuler error

**Pull request merged**
