### PR TITLE
fix #279914: Remove unnecessary timer

### PR DESCRIPTION
**Pull request by blackears**

### CODE REVIEW

**Comment by anatoly-os** [comment]
Really? @dmitrio95 made the timer work. Why don't we need it?

**Comment by blackears** [comment]
The timer doesn't do anything.  You're just delaying the update for no reason.  I presume it's in there because the older version wasn't updating correctly, but that shouldn't be a factor with the new code.  This is a regular GUI component that should be updating in response to events.  Using a timer seems like a hacky way to skip over a bug.

**Comment by blackears** [comment]
Also, if you look a the old code, the timer didn't call anything.  It just started a timer which ran and did nothing else.

https://github.com/musescore/MuseScore/pull/4375

**Comment by anatoly-os** [comment]
If the timer reduces number of update calls up to three times, let's keep it.

**Pull request closed without merging**
