### PR TITLE
[MU4] Score add elements error messages

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #9668

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by bkunda** [comment]
Tested on Windows and Mac.
All functionality works fine on MacOS. 
Just one problem with Windows – no dialog appears when adding items from the `Add` menu (as opposed to the `+` menu):

https://user-images.githubusercontent.com/86290556/149142098-386f59b9-eda3-43d9-9f51-65ef7720ca7e.mp4

**Comment by Eism** [comment]
> Tested on Windows and Mac. All functionality works fine on MacOS. Just one problem with Windows – no dialog appears when adding items from the `Add` menu (as opposed to the `+` menu):
> 
>  Recording.1-12-22.at.11.31.37.PM.mp4

Thanks, this bug will be fixed in #10235

**Comment by Eism** [comment]
> Tested on Windows and Mac. All functionality works fine on MacOS. Just one problem with Windows – no dialog appears when adding items from the `Add` menu (as opposed to the `+` menu):
> 
>  Recording.1-12-22.at.11.31.37.PM.mp4

@bkunda 
can you please recheck this PR?

**Comment by bkunda** [comment]
> > Tested on Windows and Mac. All functionality works fine on MacOS. Just one problem with Windows – no dialog appears when adding items from the `Add` menu (as opposed to the `+` menu):
> > Recording.1-12-22.at.11.31.37.PM.mp4
> 
> @bkunda can you please recheck this PR?

Sorry @Eism, the issue persists for me (same as before - the dialog appears when the item is added from the `+` menu, but not from the `Add` menu.

**Comment by bkunda** [comment]
> @bkunda I can't reproduce it. Maybe there are some additional steps?

Hi @Eism, 

This video shows the exact steps I go through. Maybe I've done something wrong somewhere? 
Anyway, I hope this helps! 

https://user-images.githubusercontent.com/86290556/150735211-ab408357-cc2a-4694-a6c7-686951beb039.mp4

**Comment by Eism** [comment]
@bkunda
I hope this will be the last time I ask you to test :)
Please recheck

**Comment by bkunda** [comment]
> @bkunda I hope this will be the last time I ask you to test :) Please recheck

Yes it can be the last time, this now works 🥳

FIXED!

Many thanks @Eism,
Bradley.

**Pull request merged**
