### PR TITLE
fix #290060: improving dark theme

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
This PR improves the dark theme. The main modifications made were:
* backgrounds are substantially darker, in line with how dark themes work in other software (GIMP, Darktable, etc.)
* blue highlight colour has been darkened a bit as it did not work well with the white text of the dark theme
* tooltip text has been changed from black to white as to match the rest of the theme

For the initial report, see: https://musescore.org/en/node/290060

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
You'd need to sign the [CLA](https://musescore.org/cla)

**Comment by gilbertohasnofb** [comment]
@Jojo-Schmitz Done. My username in the forum is gsagostinho.

**Comment by gilbertohasnofb** [comment]
Btw, here are screenshots of the change. Here is the default look:

image

And here is the look with the modifications from this PR:

image

**Comment by gilbertohasnofb** [comment]
I am really sorry, I messed up this PR, I thought I was working on a separate branch and not on the `master` branch. I am starting a clean fork and I will resubmit this PR shortly. Apologies once again.

**Pull request closed without merging**
