### PR TITLE
[MU4] Fix-Woverloaded-virtual warnings and linux specific -Wclass-memaccess warning

### PR DESCRIPTION
**Pull request by minerscale**
Note: I made sure no data in _alsaData was left undefined before removing the memset.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Review by minerscale — COMMENTED** [review]
```if (NOT MSVC AND NOT MINGW AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 9.0)```

Do you know if we can get rid of `AND NOT MINGW` now that I've added a check for the compiler version? MINGW uses GCC, no? So if the GCC version is > 9, we suppress the warning.

Nevermind, it doesn't seem to even work >:(

**Comment by minerscale** [comment]
Oops, I was in python mode and forgot the endif :facepalm:

**Comment by minerscale** [comment]
Okay can I stop messing up already? :P

**Comment by igorkorsukov** [comment]
> Okay can I stop messing up already? :P

Glory СI !! ;)

**Pull request merged**
