### PR TITLE
fix #271717: Match default tempo in New Score Wizard

### PR DESCRIPTION
**Pull request by JGreenlee**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Just a hint: better create a branch rather than using master, so not to block your master branch until the PR got merged
Also I think you'd need to sign the [CLA](https://musescore.org/cla)

**Comment by Jojo-Schmitz** [comment]
Why?

**Comment by JGreenlee** [comment]
@Jojo-Schmitz Because I forgot to make a separate branch, like you said.

I think I did it right this time. https://github.com/musescore/MuseScore/pull/3648

And I signed the CLA. Thanks for letting me know about that; I didn't see anything about it in the developer handbook.

**Comment by Jojo-Schmitz** [comment]
Ah, I see, thanks

**Comment by Jojo-Schmitz** [comment]
What is your name/nick on musescore?

**Comment by Jojo-Schmitz** [comment]
The CLA requirement is listed on the very first section of the very first page of the developers' handbook, https://musescore.org/en/development

**Comment by JGreenlee** [comment]
@Jojo-Schmitz Yeah I don't know how I missed it, but thanks for your help.

My Musescore is [tealFedora](https://musescore.com/user/1839556?q=user/1839556).

**Pull request closed without merging**
