### PR TITLE
Treat NumPad Enter the same as Return

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: https://musescore.org/en/node/365089

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Any special reason why shortcuts_AZERTY.xml is missing an entry for `<key>add-lyric-verse</key>`? Should I add it?

**Comment by Jojo-Schmitz** [comment]
Would someone mind to review this?

**Comment by zacjansheski** [comment]
Is this confirmed to work? 

I don't get any change using NumPad Enter (Neither Num Lock on or off)

Windows 11 QWERTY

(num pad enter works as expected when writing text)

**Comment by Jojo-Schmitz** [comment]
That's not usent the shortcut ;-)

One way to test: select a measure or barline, press Return. Then try the same with Enter
With the fix both should add a system break, without on the Return
Ctrl+Return and Ctrl+Enter should add pages breaks
On lyrics both Retrurn and Enter should add another verse.

**Comment by zacjansheski** [comment]
I did a factory reset and now the numpad enter works and regular enter does not 

https://drive.google.com/file/d/107IPhRuh9hFVIT_RcBdFBTs1N-RHrpB-/view?usp=sharing

**Comment by Jojo-Schmitz** [comment]
Looking into that...
What does the shortcuts dialog show when serching for Return and/or Enter?
Should lokk like this:
image

**Comment by Jojo-Schmitz** [comment]
Asking because it does work for me, even after a factory reset

**Comment by Jojo-Schmitz** [comment]
While at it, I rebased it

**Comment by zacjansheski** [comment]
This is what I have after factory reset

Notice:
Add/remove page break = Ctrl+Return
Add/remove system break = Enter

Screenshot 2024-07-02 114856

**Comment by Jojo-Schmitz** [comment]
Not for me. Windows 11, German QWERTZ keyboard

**Comment by zacjansheski** [comment]
Well, I'm not sure what was going on there but after another restart and reset everything seems in order on my Windows device, my apologies

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved

**Pull request merged**
