### PR TITLE
remove superfluous/duplicate channels

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Might better get integrated in #4625. It surely conflicts with that sooner or later

**Comment by lasconic** [comment]
Note that instrumentsxml.h should be created by running `generateTs.py` in the same directory.

**Comment by Jojo-Schmitz** [comment]
done ;-)

**Comment by Jojo-Schmitz** [comment]
@lasconic I never managed to run that Python script locally, so I (try to) keep instrumentsxml.h in sync with instruments.xml manually. Occasionally this fails (read: I fail on it)

**Comment by Jojo-Schmitz** [comment]
Might be better to somehow autogerenate instrumentsxml.h always

**Comment by RobFog** [comment]
Typo: "superfluos" should read "superfluous".

**Comment by Jojo-Schmitz** [comment]
Will look into fixing that and the Travis fail tomorrow

**Comment by Jojo-Schmitz** [comment]
Or

**Pull request merged**
