### PR TITLE
fix #281652: cloneMeasure breaks tuplets

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Definitly needs a review, as I have no idea what I'm doing here, I just took the issues's author's word for it and turned it into a PR

see https://musescore.org/en/node/281652

### CODE REVIEW

**Comment by mattmcclinch** [comment]
It is clear to me that this is the correct thing to do. If we are going to fix this now, we should probably add this line in the same block of code:
```
nt->setTick(m->tick() + ot->rtick());
```
But since this code is never executed currently, there is no way to observe the problem or to verify that this fixes it.

**Comment by Jojo-Schmitz** [comment]
Thanks, added

**Comment by anatoly-os** [comment]
@velochy this PR is based on your suggestion in the related issue. Could you take a look please?

**Comment by velochy** [comment]
@anatoly-os @Jojo-Schmitz  looks good.
The feature I was working on was what later became https://github.com/musescore/MuseScore/pull/4644
Unfortunately, I do not remember which file caused a problem exactly so I can not test, but I remember patching in similar lines and having it work after that so I think it is ok.

**Comment by Jojo-Schmitz** [comment]
there is no work in progress ;-)

**Pull request merged**
