### PR TITLE
implement import of simple tuplets (n equal notes) from Capella files

### PR DESCRIPTION
**Pull request by AntonioBL**

### CODE REVIEW

**Comment by lasconic** [comment]
There is an infrastructure for tests and capella in mtest/capella/io
Would you mind adding one for tuplet then?

**Comment by lasconic** [comment]
Actually there is already a commented tuplet test for capx import. Not sure what it does but if I uncomment it, it passes without your changes.

**Comment by AntonioBL** [comment]
The test already present does include only triplets, which were implemented as default import kind for tuplets; that's why it was already working. This change implements tuplets of n notes, with n a possible integer number between 2 and 15 (for example, quintuplet, duplet, et cetera).
I do not have the possibility to create a sample Capella file (I do not have Capella software; I tested the change by looking at the specs for Capella files and some files from the set freely given by Capella site). A test file should include tuplets of 3, 5, 6, 7 (et cetera) notes and also tuplets in compound time (e.g. a duplet in 6/8). Do you have access to Capella?

**Comment by lasconic** [comment]
I have it on a old computer. I'll add a test later. Let's see if it passes our current test suite.

**Comment by lasconic** [comment]
@AntonioBL Here are some test files https://dl.dropboxusercontent.com/u/497455/musescore/tuplet.zip
Let me know if you need anything else.

**Comment by AntonioBL** [comment]
Thank you Nicolas, I tried to add them as tests.
You changed one of the measure from those shown in the png file, but I could double-check with Capella Reader to verify that the import is correct :-)
There are differences in beaming of the notes inside the tuplets between the imported scores and the original ones, but that is a (minor) different bug.
Hopefully Travis will not complain :-)

**Pull request merged**
