### PR TITLE
fix #266407: Barlines reduced to a point on one-line staff

### PR DESCRIPTION
**Pull request by lyrischesich**
removed minus sign

### CODE REVIEW

**Comment by lasconic** [comment]
Thanks! 
For your commit message, it's better to use the issue title instead of a comment describing your changes in the code. You can add comments about your changes in the pull request description if needed.

**Comment by Jojo-Schmitz** [comment]
Commit message != PR title ;-)

**Comment by lasconic** [comment]
thanks !

**Comment by Jojo-Schmitz** [comment]
Ooops, too early, it hadn't been merged yet!

**Comment by lyrischesich** [comment]
Sorry! So much trouble with such a small change ...

**Comment by lasconic** [comment]
Sorry for that. I try to test each PR and it takes time.

**Pull request merged**
