### PR TITLE
[MU4] partially fix #290533: issues with articulations and the MusicXML exporter

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
This PR addresses the following:

* the MusicXML exporter now exports the position of the articulations using the `placement` argument
* previously, the marcato-tenuto articulations was completely ignored. It is now exported as a tenuto

What is not fixed from the [original report](https://musescore.org/en/node/290533):
* marcato-staccato and marcato-tenuto export only a single staccato and a single tenuto instead of two articulations. This is because MuseScore considers the formers as single graphic object, while they would have to be exported as two separate articulations in the MusicXML. If anyone can guide me on how to tackle this, I will be happy to update this PR.

Note that the problem 1) reported in the [original report](https://musescore.org/en/node/290533) is actually not caused by the MusicXML exported and has since been reported as a [separate issue](https://musescore.org/en/node/290567).

### CODE REVIEW

**Comment by dmitrio95** [comment]
@gilbertohasnofb could you please check out the failing tests and correct them if needed?

**Comment by gilbertohasnofb** [comment]
@dmitrio95 I think the tests are failing because this PR has been standing for almost a year. Do you think it might be easier for me to delete this branch, pull the current master and add my modifications to it once again?

**Comment by Jojo-Schmitz** [comment]
No, those tests failed back on June 10th already.
They may now pass or fail athe thame or ad fifferent places though, so rebasing first and getting them to run again seems in order

**Comment by gilbertohasnofb** [comment]
@Jojo-Schmitz Oh, my bad Jojo, I did not notice those tests failing back then. I will investigate this. Many thanks!

**Comment by Jojo-Schmitz** [comment]
Now with those failing mtests out of the way (why did the vtest job fail? @AntonioBL?) it'd be good if @lvinken could review this?

**Comment by gilbertohasnofb** [comment]
Also, if anyone could guide me on how to approach the issue with double articulations (such as accent-staccato, marcato-staccato, marcato-tenuto, tenuto-staccato, etc.) I could try to solve the whole original issue. The main problem is that the function symIdToArtic takes a single SymID and outputs a single string, but double articulations would need to output multiple MusicXML tags

**Comment by AntonioBL** [comment]
@Jojo-Schmitz : I think I found the problem in the vtest check, see second comit in PR https://github.com/musescore/MuseScore/pull/5806
I don't know why this problem is happening now for this specific PR but not before. However, that commit should solve it.

**Comment by RobFog** [comment]
There's a typo in this PR's title: "articualtions".

**Comment by lvinken** [comment]
Hi Gilberto, with respect to the double articulations, you will indeed have to output multiple tags. This is mentioned e.g. in https://forums.makemusic.com/viewtopic.php?f=12&t=1243&p=2053&hilit=accent+staccato&sid=ae3e4cb7a4f36cdc69c9cff19d6335c2#p2053 and https://forums.makemusic.com/viewtopic.php?f=12&t=1216&p=1967&hilit=accent+staccato&sid=ae3e4cb7a4f36cdc69c9cff19d6335c2#p1967. The export code may not yet support that and require some rework. Also: please make sure the MusicXML produced is valid / conforms to the schema.
As soon as I find the time, I will review your changes.

**Comment by lvinken** [comment]
Had a quick look at the code, which seems to work as advertised. I would suggest updating the testfiles to cover all accent types with both placement above and below and also with no placement. Currently I am not convinced import works correctly (which would be pre-existing bug).

**Comment by lvinken** [comment]
Final remark, please rebase your branch to the current master. That simplifies any checks I do.

**Comment by hhpmusic** [comment]
To Gilberto:
  Yes, the composite articulations should be exported separately in Musicxml, as if they were entered as separated ones (e.g., marcato-tenuto = marcato + tenuto = in Musicxml strong-accent + tenuto). This is the only way.

**Comment by gilbertohasnofb** [comment]
@lvinken I will work on the tests and then rebase after all work is done. 

> The export code may not yet support that and require some rework. 

Yes, I think the function `symIdToArtic` would need to be extended quite a lot in order to do that, since as of now it outputs a single string which is interpreted as a MusicXML tag. But I am afraid this is beyond my programming skills.

> Currently I am not convinced import works correctly (which would be pre-existing bug).

I am not sure I understand what you mean by that.

@hhpmusic thanks for the info as well.

**Comment by hhpmusic** [comment]
> Currently I am not convinced import works correctly (which would be pre-existing bug).

So first to do the export side if possible, since this can ensure correct xml output and corresponding braille transcription.

**Comment by gilbertohasnofb** [comment]
@lvinken I had a look at the tests but I am not sure I understand how they work. For instance, the file `test/musicxml/testNoteAttributes1.xml` is being tested against what exactly? Other tests have two files, a regular one and a `_ref` one, but again I am not sure how this works (i.e. what score is being used to create the first xml file which is then compared against the reference xml file).

**Comment by vpereverzev** [comment]
Archived for in-activity

**Pull request closed without merging**
