### PR TITLE
Rename human performance column in the MIDI import panel

### PR DESCRIPTION
**Pull request by trig-ger**
This change was suggested by chen lung.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Hmm, I wonder about this.  I agree the existing wording is a bit akward.  But the the new wording is quite misleading, I think.  Someone might think it means can *apply* some sort of "human performance" emulation to the track - eg, our version of Finale's "Human Playback".  Maybe an easier way to avoid the confusion would be to reverse the sense of the flag (at least for the GUI; internal representation could be the same) and label it something like "Computer generated"?

**Comment by trig-ger** [comment]
@MarcSabatella What is better:
"Computer generated" or "Computer generated file" ?

Also, maybe you have other renaming suggestions for the MIDI import panel, for another options?

**Comment by MarcSabatella** [comment]
I don't really have strong opinions on any of this, as I seldom use MIDI.  Probably makes more sense to ask soemone who uses it more.

**Comment by Jojo-Schmitz** [comment]
Could reverse the text too "Not a computer\ngenerated file"

**Comment by Jojo-Schmitz** [comment]
Could reverse the text too "Not a computer\ngenerated file"
On the other hand every MIDI file is computer generated?

**Comment by trig-ger** [comment]
Maybe call it "Human-performed" then?

**Comment by Jojo-Schmitz** [comment]
"non-quantized"? That's what this is about, isn't it?

**Comment by MarcSabatella** [comment]
I agree in some sense every MIDI file is computer generated, but was hoping people would get the idea.  I don't like a "negative" checboxes - needing to check somethng to say it *isn't* computer-generated or whatever - although I recognize we do use a few of these.  A checkbox to say soemthing "Quantized" is not bad, I thought of that, but in addition to being pretty technical, I wonder if it's quite accurate.

**Comment by Jojo-Schmitz** [comment]
What does that checkbox after all? It does take care of quantizing, tight?
So a simple "Quantize" should get the meaning across? This is technical, true, but this task is a technical one too. Maybe accompany it with a toolTip "Like typically needed for a human performance"?

**Pull request closed without merging**
