### PR TITLE
Complete reordering of the layout sequence

### PR DESCRIPTION
**Pull request by pthvogt**
In this PR we try to resolve some of the flaws in automatic layout by reordering the layout sequence. The new layout sequence is:

* ...
* Tuplet
* Slur
* Dynamic
* Spanner w/o slur, ottava, pedal, volta
* Fermata, Tremolobar
* Ottava
* Pedal
* Lyric
* Harmony **if no Fret Diagram in system** 
* StaffText, InstrumentChange
* Jump, Marker
* TempoText
* Volta
* Fret Diagram
* Harmony **if Fret Diagram in system**
* RehearsalMark

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Testing the various combinations using the AppVeyor build, I like it very much.  Works as expected, and I think the order is exactly right.

**Comment by MarcSabatella** [comment]
@pthvogt Don't know if you have a test file you've been using, but here's my own before/after

Before:

layout-order-before

After:

layout-order-after

**Comment by anatoly-os** [comment]
It is worth adding a couple of visual tests + updating existing ones. @pthvogt you can make a new PR with the new vtests. I'll update the existing once tomorrow.

**Comment by pthvogt** [comment]
This commit is unfortunately buggy :-( The git rebase doubled the layout of the Volta part in layoutlinear.cpp. I think this does nothing bad, only waste some time. 

What is the correct way to fix this? New PR?

**Comment by anatoly-os** [comment]
New PR and the related issue describing the bug.

**Comment by chenlung** [comment]
Hi guys,

[This](https://musescore.org/en/node/276248) may interest you, @pthvogt :)

I sent you something on Skype that could be useful for this, @MarcSabatella :)

**Pull request merged**
