### PR TITLE
Reword "margin" to "padding" in frames

### PR DESCRIPTION
**Pull request by pratyaksh1610**
Resolves: #16625 

Reword margin to padding in frames.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
This fixes only one case though. See also `VerticalMarginsSection.qml` and `TextSettings.qml`, which should receive the same treatment.

**Comment by RomanPudashkin** [comment]
Closing due to a long period of inactivity

**Comment by Jojo-Schmitz** [comment]
> This fixes only one case though. See also `VerticalMarginsSection.qml` and `TextSettings.qml`, which should receive the same treatment.

There's nothing (anymore?) in TextSettting.qml, as far as I can tell?

> Closing due to a long period of inactivity

Well, considering how long if often takes before a PR gets reviewd and merged a little more patience might be doue on your side too ;-)
Anyway, I'll pick this up and create a new and full PR, see #17582

**Comment by cbjeukendrup** [comment]
> There's nothing (anymore?) in TextSettting.qml, as far as I can tell?

Looks like it got moved to `FrameSettings.qml` recently.

**Comment by Jojo-Schmitz** [comment]
I've searched the entire project and didn't find any other place

**Pull request closed without merging**
