### PR TITLE
Replace Cyrillic character in autobotscripts

### PR DESCRIPTION
**Pull request by bakajikara**
Replaced Cyrillic `с` in `сhooseInstrument` with alphabetic `c`.
(This is my first time making a pull request, so please let me know if I am doing something wrong!)

- [ ] I signed [CLA](https://musescore.org/en/cla)
- [ ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Oh boy, how could that happen? I wonder whether there's more of those, os is only lowercase "c" and uppercase "C" (fixed in another PR, IIRC) prone to this confusion?

**Comment by cbjeukendrup** [comment]
I found a few more:
- datetime_tests.cpp, `// to Local short (С locale)` a few times
- xmldom.cpp:156, `// XmlDomDoсument` 
- NewScore.js and other files: `сhooseFluteAndPiano`

For the rest, gpbeat.h and rtf2html.cpp contain whole comments in Russian, but that's no problem to me. It's just that those single characters can be quite confusing because you can't distinguish them. I haven't found any other hidden Cyrillic characters, only `С`.

@igorkorsukov Is this a joke of yours? Or a joke of your keyboard? 😉

**Comment by Jojo-Schmitz** [comment]
Although I'd rather have the Russian comments translated into English...

**Comment by HemantAntony** [comment]
@cbjeukendrup Apparently it can be translated to English using Google Translate. So maybe it was a note for himself?

**Comment by cbjeukendrup** [comment]
@HemantAntony I meant to refer to the "hidden" Cyrillic characters, not necessarily to those Russian texts (those are not created by Igor anyway).

**Comment by cbjeukendrup** [comment]
@bakajikara It is preferred to have no merge commits in PRs. Please use `git pull --rebase upstream master` instead, and then force-push to your PR branch.

**Comment by igorkorsukov** [comment]
> @igorkorsukov Is this a joke of yours? Or a joke of your keyboard? wink   

Oh, this happens due to 2 reasons:    
* Cyrillic `C` and Latin `C` in the same place on my keyboard 
* Ubuntu has a bug, when switching keyboard layouts, sometimes the first character entered from the previous layout. And when it's the `C` symbol, it's not noticeable that an error has occurred (

**Review by igorkorsukov — APPROVED** [review]

**Pull request merged**
