### PR TITLE
Fix #85856: MIDI import - better handling of Yamaha SG SysEx block

### PR DESCRIPTION
**Pull request by shoogle**

### CODE REVIEW

**Comment by lasconic** [comment]
Great! thank you for looking into this. Could you add a test case with a SG file?
Import midi tests are here https://github.com/musescore/MuseScore/tree/master/mtest/importmidi
the main test file https://github.com/musescore/MuseScore/blob/master/mtest/importmidi/tst_importmidi.cpp

**Comment by shoogle** [comment]
Sorry, what's an SG file? Do you mean a SMF with some Yamaha SysEx inside?
Do I create the reference MSCX file manually, or do I run the test once to generate one?

**Comment by lasconic** [comment]
Yes a MIDI file with Yamaha XG sysex, possibly https://musescore.org/sites/musescore.org/files/UserSong5.MID if it's not copyrighted.
And you can generate the mscx with the test. Open it in MuseScore and/or a text editor to check that it looks ok.

**Comment by lasconic** [comment]
Just pinging @trig-ger so he knows the import midi code is changed and I will merge this (even without the test) since it seems to fix the issue at hand.

**Comment by shoogle** [comment]
Sorry I didn't get around to doing the test in time. I haven't done one before and I'd need a bit more time to look at it properly. By definition SysEx is non-standard so we're unlikely to see many cases of this anyway.

**Pull request merged**
