### PR TITLE
[MU4] Fix #329060, fix #48251: [MusicXML export] decimals in metronome markings get separated

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: https://musescore.org/en/node/329060

Same issue exists with 3.x and with a similar fix.

### CODE REVIEW

**Review by rettinghaus — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
@lvinken: mind to cast an eye on this?

**Comment by lvinken** [comment]
Implementation looks OK to me. Understanding the regular expression took some time :-). Did not have master handy, but copied the regex into 3.6.2, that works OK, I see no reason why it wouldn't be OK in master.

A regression test file would have been nice, attached a suggestion to the original issue.

**Comment by Jojo-Schmitz** [comment]
Thanks, I'll add it

**Comment by Jojo-Schmitz** [comment]
rebased and sorted merge conflicts

**Comment by Jojo-Schmitz** [comment]
and fixed the unit test, adjusting it to #10761

**Comment by Jojo-Schmitz** [comment]
As far as I can tell this is now (again) ready for merging

**Comment by Jojo-Schmitz** [comment]
@vpereverzev, esp. see the fixed MusicXML tests

**Comment by Jojo-Schmitz** [comment]
Any reason not to merge this?

**Comment by Jojo-Schmitz** [comment]
Could this eventually get reviewed and merged?

**Review by cbjeukendrup — APPROVED** [review]

**Pull request merged**
