### PR TITLE
Fix #19230: Re-enabled vertical offset for text in lines

### LINKED ISSUE #19230: Vertical offset for text in lines is disabled
### Your idea

The title is all that's it. I just reckon that vertical offset for the text on pedals shouldn't be greyed out.

MuseScore 4.0 | MuseScore 4.1
:---:|:---:
image | image

### Problem to be solved

Here's an example of a use case for vertical offset
image
Sometimes the pedal can be pushed down a bunch along with the Rosette, which may make it a tiny bit troublesome for some performers to make out exactly when they should stop pedaling. But by adding vertical offsets to pedals texts, and by extension, rosettes, you'd be able to communicate to the performer by like 5-10 milliseconds faster or something.
image

### Prior art

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #19230

### CODE REVIEW

**Review by Eism — APPROVED** [review]

**Comment by zacjansheski** [comment]
> Interesting, can you confirm what I'm seeing @zacjansheski which is that this is only the case for Pedals? Offsets for staff/system text seem to save just fine for me.

Yes, that is correct.

**Comment by mathesoncalum** [comment]
Thanks @zacjansheski

I think we might have stumbled across a separate issue - it looks like horizontal pedal offsets are getting nuked too?

You can also try this:
- Create a vertical pedal offset in MS3, save it.
- Open it in MS4, save it.
- Reopen, vertical offset is gone.

**Comment by zacjansheski** [comment]
I opened a separate ticket. https://github.com/musescore/MuseScore/issues/19460

This PR was tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
Approved

**Comment by cbjeukendrup** [comment]
This fix seems to be only for "beginning text" offset, but what about "continue text" offset and "end text" offset?

**Comment by mathesoncalum** [comment]
Thanks @cbjeukendrup - I've enabled these offsets too. I will point out that #19460 is even more apparent now though, I've posted a [comment](https://github.com/musescore/MuseScore/issues/19460#issuecomment-1727153701) on that issue.

**Comment by mathesoncalum** [comment]
After some discussion, the latest push changes the default value for the enabling of vertical offsets throughout the app.

@zacjansheski with a note selected, this change also affects:
- Properties->Note->Head->Notehead offset
- Properties->Note->Stem->Stem offset
- Properties->Note->Stem->Flag offset

This led to the discovery of another potential engraving bug (see video).

https://github.com/musescore/MuseScore/assets/47119327/bf5d837e-9f16-404b-a60e-2c7198a71023

**Comment by zacjansheski** [comment]
@mathesoncalum same behavior in 4.0-4.0.2

**Comment by zacjansheski** [comment]
Other than the issues mentioned, this seems fine to me.
Are we in agreeance that this should be merged despite the two issues above? (saving issue and notehead offset bug). I can log the notehead offset bug once this is merged.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
@zacjansheski That seems good to me!

**Pull request merged**
