### PR TITLE
Fixed wrong bitwise operator: & instead of |

### PR DESCRIPTION
**Pull request by L0uisc**
Resolves: *(direct link to the issue)*

In `globals.h`, the following enum is declared:

```cpp

enum TelemetryDataCollectionType : unsigned char {
      COLLECT_NO_DATA = 0,
      COLLECT_CRASH_FREE_DATA = 1,
      COLLECT_INSPECTOR_DATA = 1 << 1,
      COLLECT_SHORTCUT_AND_MENU_DATA = 1 << 2,
      COLLECT_ALL_DATA = COLLECT_CRASH_FREE_DATA & COLLECT_INSPECTOR_DATA & COLLECT_SHORTCUT_AND_MENU_DATA
};
```
The fifth member (`COLLECT_ALL_DATA`) will evaluate to 0, duplicating the first member (`COLLECT_NO_DATA`). This is most probably not what was intended. This fix changes the bitwise operator to `|` in order to make the last member a bit field with all bits on.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [ ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by L0uisc** [comment]
Coding rules link gives me 404 not found and I don't know what kind of tests I could create for this.

**Comment by Jojo-Schmitz** [comment]
Reg. the 404 error see #7588

**Review by Jojo-Schmitz — APPROVED** [review]

**Comment by Marr11317** [comment]
If I remember well, Telemetry has been completely disabled not so long ago, because there was enough reports already. I haven't check, but this might actually what they used to disable it? Maybe @igorkorsukov would know?

**Comment by Jojo-Schmitz** [comment]
Since 18576da0 only `COLLECT_CRASH_FREE_DATA` gets collected

**Comment by Jojo-Schmitz** [comment]
I wonder whether this would need to get ported to master

**Pull request merged**
