### PR TITLE
Cloud. Execute request not in main thread

### PR DESCRIPTION
**Pull request by Eism**

### CODE REVIEW

**Review by igorkorsukov — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
Sorry to be pedantic, but isn't this thread-unsafe? When th_downloadAccountInfo takes long because of bad network, wouldn't it cause a conflicting memory writes/reads with other methods that do run on the main thread?
Maybe need to add mutex to protect some member fields.

**Comment by zacjansheski** [comment]
What is the status of this?  I'm not really sure what to look for here.  Thanks in advance!
@Eism  @cbjeukendrup   @igorkorsukov

**Comment by cbjeukendrup** [comment]
I believe the status is that this change needs some more thought/refinement.

**Comment by Eism** [comment]
Yes, this problem needs to be solved differently - https://github.com/musescore/MuseScore/issues/24141
 Gonna close this PR

**Pull request closed without merging**
