### PR TITLE
Fix #184246: Add same string option in select notes

### PR DESCRIPTION
**Pull request by techiespace**
Select -> More: ability to distinguish same pitch on a specific string in Tabs

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
as mentioned on IRC: revision.h shoulnd not be there, check build/git/hooks/post-checkout and the README next to it on how to prevent this.

**Comment by techiespace** [comment]
Did you mean squash? If yes, should I do it or it will be done by maintainers while merging the PR?

**Comment by Jojo-Schmitz** [comment]
Yes I meant squash and no this needs to be done by you prior have the PR merged

**Comment by techiespace** [comment]
Sorry this is my first PR. I'm having some problems with git. To clarify I have to -
1) Squash changes locally
2) Push it to origin
3) GitHub will automatically update the PR upstream.

**Comment by Jojo-Schmitz** [comment]
Yes. You can also to a `git reset HEAD^2` (or whatever it takes to go be to the state before your fìrst commit), than a `git commit -m "Fix #184246:..."` then a `git push -f`

**Comment by Jojo-Schmitz** [comment]
Looks good now and should also go into 2.2 IMHO

**Comment by lasconic** [comment]
Looks good. Will merge. I might add a check to see if there is some stringdata associated with the instrument, if not this option doesn't really make sense.

**Pull request merged**
