### PR TITLE
Fix #278493: Reorganize workspace

### PR DESCRIPTION
**Pull request by JoshuaBonn1**
Change archived workspaces into raw xml.

The issue mentioned multiple different requests. I focused on just what is mentioned above. Not refactoring menus.cpp nor creating a beginners mode

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
rebase needed

**Comment by JoshuaBonn1** [comment]
Before merging, let me update the actual workspace xml

**Comment by JoshuaBonn1** [comment]
Updated to xml that was in master at this moment.

**Comment by anatoly-os** [comment]
See #4579.

**Pull request closed without merging**
