### PR TITLE
Braille Panel to be included in View Menu & Associated Shortcut #19556 (Part 1)

### PR DESCRIPTION
**Pull request by daijingz**
Resolves: #19556 
As you can see, this is my original code on Jan 16.

The problem is that I did not submit it before because I have not found a successful implementation on hotkeys. I almost spend two months on this. (I need help) @cbjeukendrup 

This PR addresses:
- [x] A new view menu button is inserted inside
- [x] The marker is inserted as well
- [x] It has a consistent effect on the navigator: Initially, both of them are open.

Not sure whether all of its tests will pass, but it works well in my machine.

(There are many options I have not double-checked below)
- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [ ] Each commit's message describes its purpose and effects and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ ] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by daijingz** [comment]
@cbjeukendrup mentor you can see that there are a few failings in this PR, but by manual testing, you can see all functions work well. I do not know where the problem exists, but there may exist some redundant programs.

**Comment by Jojo-Schmitz** [comment]
Isn't there a B missing in the PR title?

**Comment by daijingz** [comment]
> Isn't there a B missing in the PR title?

Corrected.

**Comment by Jojo-Schmitz** [comment]
The MusicXML unit test failure would be fixed by a rebase, but please use pill rather than merge: 
`git pill --rebase upstream master; git push -f

**Comment by daijingz** [comment]
> The MusicXML unit test failure would be fixed by a rebase, but please use pill rather than merge:
> `git pill --rebase upstream master; git push -f`
> That'd also get rid of all these unwanted merge commits

Have some difficulties while rebasing, let me do some researches

**Comment by daijingz** [comment]
@Jojo-Schmitz Mentor, there is a problem: my local terminal does not accept `git pill`, which only accepts `git rebase`, which is quite strange. Can we use the rebase technique inside the GitHub desktop?
FZB SIO(JJ 04 {`8NVF897

**Comment by Jojo-Schmitz** [comment]
Or because I screwed up the syntax, `pill` rather than `pull` 🫣

**Comment by Jojo-Schmitz** [comment]
Or because I screwed up the syntax, `pill` rather than `pull` 🫣

**Comment by daijingz** [comment]
> Because I screwed up the syntax, `pill` rather than `pull` 🫣 Sorry about that

Now I built a new branch, and use both commands, not sure all tests will succeed or not

**Comment by cbjeukendrup** [comment]
@daijingz As Jojo said, the failing test is not related to your code, so you can ignore it. (We're still investigating what causes the failure.)

However, please close either this PR or #21938, because one PR is enough. And you should either fix the title of #21938, or get rid of the merge commits in this PR. 

By the way, no need to call us "mentor", this is not school :) This is just that you are voluntarily contributing to our project, for fun (and if it's not fun, then there's no obligation to do it!)

**Comment by daijingz** [comment]
> @daijingz As Jojo said, the failing test is not related to your code, so you can ignore it. (We're still investigating what causes the failure.)
> 
> However, please close either this PR or #21938, because one PR is enough. And you should either fix the title of #21938, or get rid of the merge commits in this PR.
> 
> By the way, no need to call us "mentor", this is not school :) This is just that you are voluntarily contributing to our project, for fun (and if it's not fun, then there's no obligation to do it!)

@cbjeukendrup I am going to close the PR #21938

**Comment by daijingz** [comment]
@cbjeukendrup @Jojo-Schmitz shortcut key `Alt+F11` added

**Comment by cbjeukendrup** [comment]
@daijingz Could you please get rid of the merge commits?
```sh
git pull --rebase upstream master
git push -f
```
(It's easier to run these commands simply on the command line, instead of trying to figure out how to do it using some GUI app)

**Comment by daijingz** [comment]
> @daijingz Could you please get rid of the merge commits?
> 
> ```shell
> git pull --rebase upstream master
> git push -f
> ```
> 
> (It's easier to run these commands simply on the command line, instead of trying to figure out how to do it using some GUI app)

I did not use these commands in this master PR, instead, I only use them in my new-created branch: #21938. I do not think there are some additional effects here. Do not worry.

**Comment by Jojo-Schmitz** [comment]
But that's closed, so better do it here too

**Comment by cbjeukendrup** [comment]
You should regularly update your master branch anyway, for which you'd also use these commands. 

(The only thing is that if you never commit directly to your master branch, you wouldn't need the -f flag. But now you do need it.)

**Comment by daijingz** [comment]
@Jojo-Schmitz @cbjeukendrup Confused now, should I use these two commands or not?
(I have used both commands in my `master` branch now)

**Comment by cbjeukendrup** [comment]
It looks like you forgot to add `--rebase` to the pull command. Because now you created another merge commit instead.

**Comment by daijingz** [comment]
@Jojo-Schmitz @cbjeukendrup Updated
O~)W1B $IFT}A{@N{_PF$_Y

**Comment by shoogle** [comment]
@daijingz, the terminal output shows problems with your `git` setup. Running `git rebase --abort` might help, but I'm not sure.

Anyway, I've tidied things up for your in PR #21938, so let's continue there for now.

I recommend you read these [Git Workflow instructions](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/git-workflow#Create_a_topical_development_branch), and use this method from now on.

**Comment by daijingz** [comment]
@shoogle no problem, I read this guidance before, seems like here is the place to use it.

**Pull request closed without merging**
