### PR TITLE
[MU4] Change workspace fix

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #11353
Resolves: #11987
and other bugs on workspaces

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Tantacrul** [comment]
Just some minor UI points. The two dialogs in this flow need headers.

image

I've put both of these in our **Non-modal dialogs** section in the Master file in Figma, if you want it.

**Comment by Eism** [comment]
@Tantacrul fixed

**Comment by Tantacrul** [comment]
Thanks! This is all looking good to me now. I can confirm it fixes https://github.com/musescore/MuseScore/issues/11353.

@HemantAntony - can you confirm it fixes https://github.com/musescore/MuseScore/issues/11987?

**Comment by HemantAntony** [comment]
This fixes #11987 :)

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #11353 #11987 on Win10, Mac12, LinuxMint 20.2 - **FIXED**

**Pull request merged**
