### PR TITLE
fix #290060: improving dark theme

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
This PR improves the dark theme. The main modifications made were:
* backgrounds are substantially darker, in line with how dark themes work in other software (GIMP, Darktable, etc.)
* invert icons for window close, window close hover, and window float, since they were still dark on the dark theme and thus virtually invisible
* blue highlight colour has been darkened a bit as it did not work well with the white text of the dark theme
* tooltip text has been changed from black to white as to match the rest of the theme

For the initial report, see: https://musescore.org/en/node/290060

image

### CODE REVIEW

**Comment by anatoly-os** [comment]
@gilbertohasnofb hi! I like the changes and I want to merge the changes to the icons from 35623c37038a03778100d00948f69d330a5c1099. Btw, I need you to sign CLA to merge the changes to the MuseScore codebase. Would you mind signing it (https://musescore.org/en/cla)?

Please let me know once it is signed and under which name

**Comment by anatoly-os** [comment]
Is it you https://musescore.org/en/user/116431? :)

**Comment by gilbertohasnofb** [comment]
@anatoly-os Yes, that's me and I had already signed the CLA. It's just that my username is different in the forum.

**Comment by anatoly-os** [comment]
manually merged the mentioned commit in 21cac7bf23d75999dc19b1f5f1488f28bc827288. Thank you @gilbertohasnofb

**Comment by gilbertohasnofb** [comment]
@anatoly-os Thanks for reviewing this and merging that commit. But may I ask you why you did not merge https://github.com/musescore/MuseScore/commit/84f0d5101d7b9550f4fc416d1a061e79e2b17a09 ? I personally find the darker UI far better than what we currently have now

**Comment by anatoly-os** [comment]
@gilbertohasnofb checkout the master branch. I applied the darker theme by myself few commits ago. I borrowed the colors from the Figma dark theme and adjusted different button colors as well.

**Comment by gilbertohasnofb** [comment]
@anatoly-os I see, that's great, I hadn't noticed that commit. I am away from my computer and I can't compile MuseScore right now to check how it looks, but the values you chose seem really good. The only comment I would make is that you don't seem to set the `"Highlight"` value nor the `"ToolTipBase"` and `"ToolTipText"`. The default highlight value was not looking good at all with the white text of the dark theme because the blue colour is too bright and there is not enough contrast for reading. I had set it to `#6994BF` which is the same hue and saturation as the default but a bit darker. The tooltips looked better with dark background and bright text in my opinion. Perhaps it might be worth it to check these out.

Thank you so much once again both for reviewing my work as well as for working on the dark theme too, I think this is such a nice feature which many users really enjoy (I myself use nothing but dark themes whenever possible).

**Pull request closed without merging**
