### PR TITLE
Add line to align some element relative to other

### PR DESCRIPTION
**Pull request by Gai-Luron**
align
stem

### CODE REVIEW

**Comment by anatoly-os** [comment]
@lasconic @Jojo-Schmitz @Gai-Luron I like it but there is more work to be done to make this feature great again :) These lines give approximate aligning which is not good since it can be done with less accuracy manually. Really cool solution is snap points based on anchor points of elements. This is indeed cool, but I'm not sure it is really useful for musicians. Is it widespread practice to align elements this way?
Also, new layouting in 3.0 assumes using auto-placement as much as possible.
So, the question is do we really need this PR, will someone continue work here?

**Comment by lasconic** [comment]
There has been a discussion recently about aligning elements on the forum. I still think we should favor auto-placement and giving more tools to align will just give users more insentive to tweak the placement and so destroy these tweaks when using a different layout (like continuous view or a floating layout like in the mobile apps)

If we are not worried about this, I do prefer this PR approach instead of a grid or ruler on left and right. Also, if we go this way, it would be helpful to have "align to left", "align to right", "align center" for multiple selection.

**Comment by Jojo-Schmitz** [comment]
I (still) like it!

**Comment by lasconic** [comment]
*maybe something that would be available in the context menu when a list selection is present.*
In the inspector ?

**Comment by anatoly-os** [comment]
Finale uses such aligners, so it adds a vote to have this in MuseScore :)

**Comment by jthistle** [comment]
> Finale uses such aligners, so it adds a vote to have this in MuseScore :)

I think we may have to close this however, unless you want to fix all the merge conflicts ;)

**Comment by jthistle** [comment]
> Finale uses such aligners, so it adds a vote to have this in MuseScore :)

I think we may have to close this however, unless you want to fix all the merge conflicts ;)

**Comment by Jojo-Schmitz** [comment]
resolving the conflicts looks like a lot of work :-(

**Pull request closed without merging**
