### PR TITLE
fix #10728:Add ability to rename part title

### PR DESCRIPTION
**Pull request by salilkhandelwal**
The part title is no longer grayed out and we are able to rename it .

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
As I wrote in the issue tracker:
Looks like a very easy one-line fix. Except that it doesn't work:

* the name in the part's tab doesn't change
*  the filename when exporting the part doesn't change
* the partname text in upper left Corner of the title frame of the part doesn't change
* the meta- tag partName doesn't change

Only thing that does change is what is shown on the excepts dialog. And even that doesn't survive a save/close/reopen!

**Comment by salilkhandelwal** [comment]
Yes , I will work on it , did not notice so many loop holes

**Comment by Rockettwo** [comment]
Hey,
are you still working on this or would it be okay, if I'll stick to this? Or do you need some help?

**Comment by lasconic** [comment]
I close this PR. It needs a lot more work.

**Pull request closed without merging**
