### PR TITLE
Fix some compiler warnings and perform some tiny cleanups

### PR DESCRIPTION
**Pull request by cbjeukendrup**

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
@vpereverzev I added a fix for some typos I had seen in the MuseSampler lib handler. Could you please check if this is correct? Or are the typos part of the library and did you thus make them on purpose in the MuseScore code?

**Review by igorkorsukov — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
See also #12708

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz Is it okay it I merge this PR first, and #12708 after that (after a rebase)?

**Comment by Jojo-Schmitz** [comment]
Sure

**Comment by Jojo-Schmitz** [comment]
done

**Pull request merged**
