### PR TITLE
fix #270496: Add missing elements to incomplete tuplets when reading …

### PR DESCRIPTION
**Pull request by mattmcclinch**
…from a file

See [issue 270496](https://musescore.org/en/node/270496).

### CODE REVIEW

**Comment by lasconic** [comment]
Pretty cool. Could you add test and test files in tst_tuplet ?

**Comment by mattmcclinch** [comment]
I will see about adding test cases and test files in tst_tuplet like you asked. And yes, this can happen for 3.0 files as well as imported 1.x and 2.x files.

**Comment by anatoly-os** [comment]
I like the PR, it is really good job! @mattmcclinch how about tests?

**Comment by RobFog** [comment]
This is "work in progress" and should be marked as such, right?

**Pull request merged**
