### PR TITLE
[MU4] Rename note Hooks to Flags, to match SMuFL terms and some more text fixes

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
and to differentiate from line hooks. Also the new Inspector uses "Flag offset" already.

Change some more strings too. Including some that came up as an issue on Transifex.

Counterpart to #6292, but for master

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Counterpart to #6292, but for master

**Comment by Jojo-Schmitz** [comment]
note to self: rebase needed

**Comment by Jojo-Schmitz** [comment]
The mtests failures are known and unrelated to this PR

**Review by vpereverzev — APPROVED** [review]

**Comment by Howard-C** [comment]
Not changing any instances in code variables?

**Comment by Jojo-Schmitz** [comment]
Why?

**Comment by Jojo-Schmitz** [comment]
Would have made up for a much fatter change, much more likely to cause merge conflicts

**Pull request merged**
