### PR TITLE
Fix build when not using QtWebKit

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
like needed e.g. when building a 2.x branch with Qt version > 5.4

### CODE REVIEW

**Comment by anatoly-os** [comment]
Any description?

**Comment by Jojo-Schmitz** [comment]
I don't get wuy it doesn't buildfor Linux on Travis, nor Wondoes on AppVeyour (both with WbebKit on), but does build locally for Windows (with WebKit off) and does for Mac (with WebKit on and off, as per @nasehim7)

**Comment by anatoly-os** [comment]
2.3.1 has been released.

**Comment by Jojo-Schmitz** [comment]
True. It might still be needed/used for #3782 though

**Pull request closed without merging**
