### PR TITLE
fix #299393: [Musicxml Export] - Shortcut hairpin dynamic not exported

### PR DESCRIPTION
**Pull request by lvinken**
https://musescore.org/en/node/299393

MusicXML export of dynamics embedded in spanner begin and end text.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by lvinken** [comment]
If I understand the Travis output correctly, there is a build error:

mtest/mscore/palette/tst_palette.cpp:27:21: error: ‘vector’ was not declared in this scope

which is in a file I did not touch ...

**Comment by Jojo-Schmitz** [comment]
Known issue, pending #6023

**Comment by lvinken** [comment]
Thanks

**Comment by Jojo-Schmitz** [comment]
This one is needed for 3.x too

**Comment by Jojo-Schmitz** [comment]
Except for one failing mtest, https://travis-ci.org/github/musescore/MuseScore/jobs/689215102#L4360-L4373, this should merge cleanly onto 3.x too?

**Comment by RobFog** [comment]
@lvinken, could you fix the mtest?

**Comment by Jojo-Schmitz** [comment]
See #6102

**Comment by lvinken** [comment]
Jojo, thanks for fixing the test issue. Leon.

**Comment by Jojo-Schmitz** [comment]
I hope my correction was correct ;-)

**Pull request merged**
