### PR TITLE
fix #184156 Score::makeGap tie new notes

### PR DESCRIPTION
**Pull request by ericfont**
This is my first attempt...I haven't actually finished the test case, but I'll do that later today...just putting up for comments.

I need to add test to verify that previous ties in original notes will remain.

### CODE REVIEW

**Comment by ericfont** [comment]
@lasconic (or anyone else): I am wanting to keep pre-existing ties to the next note after the note that is being broken.  However, the original note was removed in https://github.com/musescore/MuseScore/pull/3117/commits/c9be2fd38390c27472758cb3cd8b105e6a9d6c4e#diff-44ed85c6927e1199227c7488016b668fR752 and so I loose the tie information (which I try to use later when I use the variable "originalTie".  So I'm thinking about copying the state of the ties at that line (maybe in a boolean array), to use later.  Unless let me know if you have a preffered way to do that.

**Comment by ericfont** [comment]
(note this test will fail, cause I haven't figured out best way to keep ties to subsequent notes)

**Comment by anatoly-os** [comment]
@ericfont is this PR still viable?

**Comment by anatoly-os** [comment]
This PR is too far from actual master, so let's reapply this idea in new PR.

**Pull request closed without merging**
