### PR TITLE
Fix orphan popup windows when clicking a harp pedal diagram multiple times (and other elements with popups)

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #22604

### CODE REVIEW

**Review by Eism — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested on Win10. 

@cbjeukendrup There is still a regression comparing with 4.2.1.

1. Click on harp diagram
2. Click again and drag harp diagram
3. Drag score


https://github.com/musescore/MuseScore/assets/90187801/3b89f61e-d7d9-4acb-b713-3a974609cc83

**Comment by cbjeukendrup** [comment]
@DmitryArefiev That should be fixed too now!

**Comment by Eism** [comment]
@cbjeukendrup 
I suggest closing the popup in `AbstractNotationPaintView` at the start of the drag, as we do for zoom, moveCanvas...

**Comment by cbjeukendrup** [comment]
That's perhaps a better idea. Pushed that now!

**Review by Eism — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #22604 on Win10, Mac13.6, LinuxUbuntu22.04 - **FIXED**

**Pull request merged**
