### PR TITLE
Fix #109716, also add/remove new wallpapers

### PR DESCRIPTION
**Pull request by ZackTheCardshark**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Maybe at that occasion add the wallpapers that recently have been published in the forum?
See https://musescore.org/en/node/108386, but also older posts like https://musescore.org/en/node/24966, https://musescore.org/en/node/13790, https://musescore.org/en/node/13970

**Comment by ZackTheCardshark** [comment]
I was thinking of separate and subsequent PR for that (only that most recent one really catches my eye), but I guess it's simpler to make the changes at the same time.

**Comment by Jojo-Schmitz** [comment]
I'd make it a separate commit.

**Comment by ZackTheCardshark** [comment]
Well, it will be. ;-) But I won't squash.

**Comment by Jojo-Schmitz** [comment]
If you'd squash it'd not be separate commits ;-)

**Comment by ZackTheCardshark** [comment]
Exactly my point.

Is it all right as a JPEG, or is it better as PNG? The file grows from 196 KB to 283 KB in that conversion, apparently.

**Comment by Jojo-Schmitz** [comment]
I'd prefer png

**Comment by ZackTheCardshark** [comment]
New mystery! Apparently paper4 and paper5 are, and perhaps always have been, byte-for-byte identical. What gives?

**Comment by Jojo-Schmitz** [comment]
Delete one?

**Comment by Jojo-Schmitz** [comment]
What about shoichi's and schepers' from https://musescore.org/en/node/24966?

**Comment by ZackTheCardshark** [comment]
Well, since I've confirmed in the history that there never was a time when those two were different, I guess I'll delete one.

As to those others, as I understand it the idea would be to provide a visual grid of 1sp boxes to align elements. But it doesn't work, because when zoom changes the paper background stays scaled the same.

**Comment by Jojo-Schmitz** [comment]
Ah, I guess I should have had a closer look

**Comment by shoogle** [comment]
Rather than converting from JPEG (a lossy format) to PNG (a lossless format) you ideally want the author to export the original image as a PNG using whatever image software they used to create it. Converting from JPEG to PNG is a bit like converting from MIDI to PDF when you could have exported the original MSCZ as PDF directly. It's probably not all that important in this case, but it's worth knowing for the future.

**Comment by ZackTheCardshark** [comment]
Added some further suggestions by Philip Bergwerf, and I think we're done.

**Comment by lasconic** [comment]
Why are the paper so large now? 400px vs 96px ?
What are Philip Bergwerf suggestions?

**Comment by ZackTheCardshark** [comment]
The new ones are from https://musescore.org/en/node/108386#comment-497001 and https://musescore.org/en/node/14154 (linked to), and I had no control over the size—paper4 looks like it became larger, but actually that's because paper4 was a duplicate of paper5, and to keep the same number for paper5 in the Preferences I put in Philip's as paper4.

**Comment by ZackTheCardshark** [comment]
What about 2.0.4?

**Comment by lasconic** [comment]
If the user already use paper from the resource file system, it will be messy...

**Comment by ZackTheCardshark** [comment]
You could be right.

**Pull request merged**
