### PR TITLE
Change "Measure Width" to "Layout stretch"

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
as per https://musescore.org/en/node/269655

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
Changes to measureproperties.ui still needed to stay in sync.

**Comment by Jojo-Schmitz** [comment]
in measurepropeties.ui the string is `Layout stretch:`, hasn't been changed since 2014, ande seems OK to me?

**Comment by lasconic** [comment]
Are we all happy with this ? @IsaacWeiss @MarcSabatella @Jojo-Schmitz

**Comment by Jojo-Schmitz** [comment]
I'm considering adding a change for "Reset Shape and Position" to "Reset Shapes and Positions"

**Comment by lasconic** [comment]
I prefer the singular. In any case, it has nothing to do in this PR.

**Comment by Jojo-Schmitz** [comment]
Directly next to "Reset Beams" and near "Add/Remove System Breaks"?

**Comment by MarcSabatella** [comment]
I'm fine if it's the consensus.  So the menu itself says "layout stretch", but the full name will add "factor"?

**Comment by Jojo-Schmitz** [comment]
"factor" is shown in the tooltip (at least for measeureproperties.uinot really sure where/when for those shortcuts).

**Pull request merged**
