### PR TITLE
Adjust spacing of items in Playback Toolbar

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: https://github.com/musescore/MuseScore/issues/14448

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by bkunda** [comment]
I have one request for @cbjeukendrup before this gets merged, which is to adjust the positioning of the time/measure/beat counter by 2px down and 2px to the right. This should ensure that the text baseline is correctly aligned with the tempo counter, and is vertically centered with the icons. It also slightly improves the amount of empty space between the right side of the time/measure/beat counter and the tempo counter:

Contents in the red box should be moved 2px down and 2px to the right:
Screenshot 2022-11-25 at 5 09 57 pm

**Comment by cbjeukendrup** [comment]
@Tantacrul This is now ready for testing (when the builds are ready). 
Scherm­afbeelding 2022-12-02 om 11 22 30
We need to check that it looks acceptable for 1, 2, and 3 digits for the measure counter, also for "wide" digits (i.e. "8" opposed to "1"), on Windows too (with the different font there).

**Comment by Tantacrul** [comment]
> @Tantacrul This is now ready for testing (when the builds are ready). Scherm­afbeelding 2022-12-02 om 11 22 30 We need to check that it looks acceptable for 1, 2, and 3 digits for the measure counter, also for "wide" digits (i.e. "8" opposed to "1"), on Windows too (with the different font there).

Still waiting for Mac builds. It's taking forever!

**Comment by cbjeukendrup** [comment]
Yeah, it got stuck for some reason, so Roman restarted it. Hopefully better now :)

**Comment by Tantacrul** [comment]
One comment: I feel there is a tiny too much extra padding on either side (in green):
image

You can literally halve that space on either side and it'll look perfect:
image

**Comment by cbjeukendrup** [comment]
Hopefully this is the final iteration :)
Scherm­afbeelding 2022-12-02 om 15 52 00

**Comment by Tantacrul** [comment]
> Hopefully this is the final iteration :) Scherm­afbeelding 2022-12-02 om 15 52 00

That looks right to me

**Pull request merged**
