### PR TITLE
fix #276840: Soundfont selector: button to move soundfont to top

### PR DESCRIPTION
**Pull request by barafael**
This branch adds a button to the soundfont selector (View -> Synthesizer -> Fluid tab). The button moves the currently selected item to the top, changing the playback soundfont.

Previously, one had to repeatedly click the "Move soundfont up" button.

Note: This is affected by issue #276456, which I created. I verified that the issue persists without my changes.

### CODE REVIEW

**Comment by anatoly-os** [comment]
Thank you for your contribution. We thought about "Apply" button which should apply all changes made after using arrows to change the place of the soundfonts. Your solution is good as well.
Could you please sign cla so we could merge your changes to the product? (https://musescore.org/en/user/1743378/cla)

**Comment by anatoly-os** [comment]
@barafael could you please create the issue in the tracker which describes the main reason of these changes. It is useful to track related changes in the future.
Could you also please squash all commits at one and add "fix #XXXXXX" at the beginning of the title and the commit message (XXXXXX is a number of the created issue mentioned in the first paragraph), so the issue could be automatically closed?

**Comment by barafael** [comment]
Travis fails, it looks like due a package management issue. I squashed my commits but did not change the code. If there is something I need to do (like cherry pick from master) let me know.
Issue: https://musescore.org/en/node/276840

**Comment by anatoly-os** [comment]
Some internal error, I've restarted the build.

**Comment by barafael** [comment]
IMHO one possible implementation of this feature would be to have a drop-down list of soundfonts. I am willing to try to implement this, are you open for this change?

**Comment by anatoly-os** [comment]
@barafael what are advantages of the proposed approach? I think having "move to top" already does its job. Btw, you also need to add this widget and related logic to Zerberus synth.

**Comment by barafael** [comment]
@anatoly-os right now the purpose of the up/down buttons is unclear, that is why I thought to experiment a bit.
A dropdown requires 2 clicks, just like selecting a list entry and moving it to top. Actually, dropdown is not better here.
I applied the changes to zerberus gui as well.
I still need to change the move-to-top button to gray out when list is empty (like the up/down buttons).

**Comment by barafael** [comment]
The buttons in fluid and zerberus are now grayed out when the list is empty or the first/last element is selected. I changed the code in the zerberus updateButtons function as it didn't correctly en/disable the buttons correctly. I hope it has no other side effects.

The weird bug where the soundfont list is growing with every reload does NOT affect the zerberus list, by the way.

**Comment by anatoly-os** [comment]
@barafael please add "fix #276840:" at the beginning of the commit message so the related issue could be closed automatically.

**Comment by barafael** [comment]
I used username "rafaelement": https://musescore.org/en/user/31589 which is my old forum name.

**Comment by barafael** [comment]
Please let me know if there is anything else I need to do or if there is something wrong with the CLA.

**Comment by barafael** [comment]
If there is nothing more to do here, I will delete the branch and close the PR. Please let me know :)

**Comment by anatoly-os** [comment]
Let me look at this PR again tomorrow. I'll leave the comment once I refresh my memory.

**Comment by anatoly-os** [comment]
@barafael could you please rebase the changes on top of the master branch? The changes look good and should have been merged earlier...

**Comment by barafael** [comment]
I think this is beyond my merge-fu. I'd rather open a new pull request with the same changes.

**Comment by Jojo-Schmitz** [comment]
@barafael are you still planning to open a new pull request on this?

**Comment by barafael** [comment]
No, I don't think I will.

**Comment by Jojo-Schmitz** [comment]
OK, I'm on it now

**Pull request closed without merging**
