### PR TITLE
fix #141426 restored the 2.0.3 New Score Wizard default size

### PR DESCRIPTION
**Pull request by jeetee**
Showing 5 scores next to each other again by default.

For master and 2.1

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Does this really work across all systems, though?  840 pixels is a vastly different size on a 72 DPI display than a 100 DPI display or a 300 DPI display.  If the score thumbnails themselves are calculated in absolute pixel dimensions, then I guess having the window itself use absolute pixel dimensions will indeed result in the same number of thumbnails across all systems, but still, that's five tiny thumbnails in a tiny window for a 300 DPI window, five enormous thumbnails in an enormous window on a 72 DPI system (which for all I know is already the case in 2.0.3?)

In general, we should be using the various physical / logical DPI values for the screen when calculating sizes for objects.  Trick is knowing which to use when.  I *think* this is a case where multiplying your absolute values by "guiScaling" is the appropriate thing to do, but you'd want to test to be sure, across a variety of screen resolutions.

**Comment by IsaacWeiss** [comment]
FWIW, I only observed https://musescore.org/en/node/141426 in 3.0-dev; 2.1 does not appear to be any different form 2.0.3.

**Comment by jeetee** [comment]
@MarcSabatella Sounds sensible, I'll attempt to account and verify (dual monitor setup at work) as best as I can.

@IsaacWeiss could be because you've not used 2.1 after https://github.com/musescore/MuseScore/pull/2929 was merged? (6 days ago) Or perhaps this is a difference between how 5.4 and 5.6 handle auto-sizing of a QWizard (just mindguessing this, haven't checked)

@jeetee: note to self: MainWindow uses this default sizing instruction with non-scaled pixels as well, so if it works here, apply DPI-scaling to MainWindow as well

**Comment by IsaacWeiss** [comment]
@jeetee Following a revert to factory settings, I see that this is needed for 2.1 too. Sorry for the noise.

**Pull request merged**
