### PR TITLE
fix #190991 update scoreList order when tabMoved

### PR DESCRIPTION
**Pull request by ericfont**

### CODE REVIEW

**Comment by ericfont** [comment]
I forgot to test if there is a viewSplitter and if there is any particular thing I need to handle in case of split view.  I'm away from my machine now to test this...  Is it fine if each score tab has its own separate order of scoreList?

**Comment by lasconic** [comment]
There is one ScoreTab for each part of the viewSplitter, and it's a pointer on the same list of scores in MuseScore.. If the two score tabs are not in sync bad thing will happen since several methods rely on the index of the score in the scoretab and/or the one in MuseScore::scorelist.

**Comment by lasconic** [comment]
For example, with this PR, changing the order in one tab doesn't change the order in the other tab and so I can reproduce the bug, but in the other tab...

**Comment by ericfont** [comment]
Ok, sorry it had only occurred to me to consider that question until after I had made this PR, but I'm glad I asked and I appreciate you clarifying that.  I'll update this tomorrow when I have a fresh mind...it seems this is a bit complicated.

It seems that when the tabMoved() slot is called, I will also have to call moveTab for the other ScoreTab if it exists (but then make sure I don't get into infinite loop of each ScoreTab calling each other endlessly).  Now how to do this, I'm not sure the best way...  It might involve calling the top MuseScore object to handle the updating...or there might be a simpler way.

**Comment by ericfont** [comment]
@lasconic I believe I have fixed with this updated PR.  I had to resort to using a boolean global to scoretab.cpp, which was the simplest way I could think of to communicate whether or not that ScoreList has been updated already, so that calling moveTab() for the other tab won't undesirably update ScoreList a second time.  Anyway, I am unable to produce any crashes or undesirable behavior now.

**Comment by ericfont** [comment]
I changed bool scoreListChanged from global scope into a static variable just of scope of  ScoreTab::tabMoved().  Same behavior, but I suppose this is slightly better than using a global variable.  Everything is still working...the score tab order is kept in sync.

**Pull request merged**
