### PR TITLE
fix #270765:Update Layout for Plugin-Manager

### PR DESCRIPTION
**Pull request by AnandHemachandran**
Issue: https://musescore.org/en/node/270765

Made some changes in the layout in order to fix the wrong sizePolicy of the QPushButton which didn't show the text properly when loaded for the first time.

Before:

wrong-button-size-config

After: 

correct-button-size-config

### CODE REVIEW

**Comment by AnandHemachandran** [comment]
Is the build fail caused due to wrong indentation.

**Comment by anatoly-os** [comment]
We exceeded the allowed packages size on AppVeyor again.

**Comment by AnandHemachandran** [comment]
How am I supposed to fix this?

**Comment by RobFog** [comment]
> How am I supposed to fix this?

You're not. It was just in response to your question about the build failure. :-)

**Pull request merged**
