### PR TITLE
use same logic as in top-level CMakeLists to include freetype headers

### PR DESCRIPTION
**Pull request by mirabilos**

### CODE REVIEW

**Comment by mirabilos** [comment]
Rebased on git master as of today (3.0.1 release equivalent), please apply now.

**Comment by mirabilos** [comment]
@anatoly-os ping?

**Comment by mirabilos** [comment]
@anatoly-os ping?

**Comment by dmitrio95** [comment]
@mirabilos is this PR still actual, I believe?

**Comment by mirabilos** [comment]
Hi Dmitri,

>@mirabilos is this PR still actual, I believe?

yes, we’re shipping it in Debian, have been since a while.

**Comment by dmitrio95** [comment]
OK, thanks, I'll merge it then.

**Pull request merged**
