### PR TITLE
Fix Mac deployment for all libraries

### PR DESCRIPTION
**Pull request by AntonioBL**

### CODE REVIEW

**Comment by AntonioBL** [comment]
I could test a Nightly build and there was a leftover /usr/local/Cellar address inside one of the dependency (libvorbisenc.2.dylib) of the dependency libsndfile.1.dylib of mscore.
This should hopefully solve it (as before, I could not test this change in a local compilation).

**Comment by Jojo-Schmitz** [comment]
If you rebase to merge in @wschweer's last fix, c1a143f , this one should build

**Comment by AntonioBL** [comment]
I finally manged to recreate a build environment under Mac and it seems this PR is not solving the issue.
I will try to update it.

**Comment by AntonioBL** [comment]
Ok. Now it works (and I locally tested it), there was just a silly typo in the previous version of this PR.
I also rebased onto the latest master.

**Pull request merged**
