### PR TITLE
fix #18620: [MusicXML] Small notes not exported

### LINKED ISSUE #18620: custom time sig numbers not transferring to parts
### Issue type

Engraving bug

### Bug description

when the display numbers of a time signature is altered in a score, the parts still have the default signature numbers on that measure instead of the custom numbers.

### Steps to reproduce

1. make a custom time sig with altered numbers on a score
2. export to parts
3. see the parts have the default numbers instead

### Screenshots/Screen recordings

image

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

windows

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
See also http://musescore.org/en/node/50931

### CODE REVIEW

**Comment by lasconic** [comment]
That will at least need:
1/ tests
2/ import code

**Comment by Jojo-Schmitz** [comment]
Well, the issue is about export, not import. And there doesn't seem to be any infrastructure to just to export tests?

**Comment by lasconic** [comment]
That's why import is needed ;)

**Comment by Jojo-Schmitz** [comment]
OK, so here's import. However, first export, then import back may not in all cases result in the same score, is that acceptable? In MuseScore we can have small notes and small chords and even combine that. On export my PR makes them cue notes in either case, on import it make the chord small if one (the last, probably top topmost usually?) note of a chord is small.

**Comment by Jojo-Schmitz** [comment]
Updated to export only small chords and import as small chord if any of it's notes is small. Still not mtest for it though.

**Comment by lvinken** [comment]
A few remarks.

The exporter exports small notes as regular (non-cue) notes with cue note size (which is perfectly legal MusicXML, assuming this is the meaning we want to convey).

The importer does the exact reverse, but the code suggests we import cue notes ("bool cue"). I would suggest renaming "cue" to something like "noteSize". Real cue notes have a "cue" element instead of an attribute "size" equal to "cue".

Note that I am not familiar with the way MuseScore handles small notes, so I cannot comment on that part.

Finally, as importxml.cpp is about to be retired, the fix should go into the new pull parser instead, assuming this does not make it into 2.0.

**Comment by lasconic** [comment]
This doesn't make it in 2.0. Packages for mac and windows are ready, the code is tagged on github and Linux packagers are already packaging.

**Comment by Jojo-Schmitz** [comment]
We could export small notes and non-cue note with cue note size and small chords as cue notes
And import similar, if a note as a cue note size, make it small, it a note has a cue element (how does that look in XML?), make the chord small, but with the new pull parser, I'd rather leave that part to you anyway, if that's OK with you?

**Comment by lvinken** [comment]
On export: for non-cue small notes, add an attribute size="cue" to the notes type element. For a cue cote, add an empty cue element. See the Recordare samples, any contain small or cue notes.

On import: it is probably easiest if I handle that, as soon as the pull parser is merged in. It would help if you could provide a test file.

**Comment by Jojo-Schmitz** [comment]
Modified (and rebased) PR to handle cue chords and small notes, on export and import. A test file is attached to http://musescore.org/en/node/18620

**Comment by Jojo-Schmitz** [comment]
Rebased and integrated with the new pull parser

**Comment by Jojo-Schmitz** [comment]
@lvinken: please have a look...

**Comment by lvinken** [comment]
Looks mostly (but not completely) OK to me. Built MuseScore with these changes and loaded the Recordare samples containing cue notes. Visual inspection shows correct behavior.

The node 18620 test file does not export correctly though, size="cue" is missing from the rest. Furthermore, I'd like to have the test file reworked and included in the mtest/musicxml/io directory, to guard against accidental regressions.

**Comment by Jojo-Schmitz** [comment]
Hmm, well... yes, I missed the rest, but it does export OK:

      <note>
        <rest/>
        <duration>1</duration>
        <voice>5</voice>
        <type size="cue">quarter</type>
        <staff>2</staff>
        </note>

only the import fails.

**Comment by Jojo-Schmitz** [comment]
Fixed the rest issue and added test file, hopefully correct?

**Comment by Jojo-Schmitz** [comment]
Hmm, well... yes, I missed the rest, but it does export OK:

    <note>
      <rest/>
      <duration>1</duration>
      <voice>5</voice>
      <type size="cue">quarter</type>
      <staff>2</staff>
      </note>

only the import fails. Thanks for checking!
Fixed the rest issue and added test file, hopefully correct?

**Comment by Jojo-Schmitz** [comment]
Hmm, apparently it fails in tst_mxml_io now, but I have no idea why nor how to fix?

**Comment by Jojo-Schmitz** [comment]
Would you be OK with me commenting that test out and letting you deal with it, once it is merged?

**Comment by lvinken** [comment]
You should be able to run the test from the command line, this shows you the diffs.

In the encoding, software should be "MuseScore 0.7.0", encoding date "2007-09-10". You get these values when running mscore -d. This makes the auto tester independent from MuseScore version and current date.

Furthermore, the auto tester does not expect formatting, thus in line 57 the default-x should be removed.

If you cannot easily fix it, I will do so after the merge.

**Comment by Jojo-Schmitz** [comment]
-d, not -t? Anyway, I can't seem to get it fixed, no matter what I try, the files differ in seemingly irrelevant places.
So I'll submit with that test disable for now.

**Comment by Jojo-Schmitz** [comment]
rebased and resolved conflicts.

**Comment by Jojo-Schmitz** [comment]
split into 3 commits now, for easier cherry picking into 2.0.1, export plus DOM import, pull parser import and mtest

**Comment by Jojo-Schmitz** [comment]
Stil can't get that mtest to work.

**Comment by lasconic** [comment]
Here is the single failing test log https://gist.github.com/lasconic/02b5ba136c0ea27c664b
As far as I understand it's not related to your code?

**Comment by Jojo-Schmitz** [comment]
Thanks, not related to my changes at all, but I guess I can fix it, let's see....

**Comment by Jojo-Schmitz** [comment]
Hah! Finally the test succeeded!

**Pull request merged**
