### PR TITLE
c-splashscreen of 3.6

### PR DESCRIPTION
**Pull request by Marr11317**
shows only on december 24th

2020-12-03 15_21_17-Window

### CODE REVIEW

**Comment by shoogle** [comment]
I'd show this on at least the 25th too, maybe also for a few days before and after.

**Comment by Marr11317** [comment]
Maybe after, but not before, since it should be a surprise, and surprises traditionnaly come the 24th.

It is now from the 24th to the 27th (inclusive)

**Comment by njvdberg** [comment]
How about showing during the 12 days of Christmas? So, until January 5th?

**Comment by Jojo-Schmitz** [comment]
"The 12 days of Christmas"

**Comment by Howard-C** [comment]
Although we Chinese people don't celebrate Christmas, it's still nice to see some festive hint. Please merge this :)

**Comment by Marr11317** [comment]
> How about showing during the 12 days of Christmas? So, until January 5th?

I think twelve days might be too much. I'm open to it though if someone agrees with you.

**Comment by Jojo-Schmitz** [comment]
That is the official Christmas period IIRC

**Comment by vpereverzev** [comment]
OK, I promise to merge it if every single issue on this board will be resolved - https://trello.com/b/Ymc5O1KG/temp-36-bug-board
:)

**Comment by vpereverzev** [comment]
> 
> 
> OK, I promise to merge it if every single issue on this board will be resolved - https://trello.com/b/Ymc5O1KG/temp-36-bug-board
> :)

Otherwise, I'm going to be this guy
изображение

**Comment by njvdberg** [comment]
Hm,  I like that guy maybe better. So don't solve too many issues then  😁

**Comment by Marr11317** [comment]
> That is the official Christmas period IIRC

For some people, Christmas isn't even a period. I wouldn't want to annoy them too much with that.

**Comment by Howard-C** [comment]
> OK, I promise to merge it if every single issue on this board will be resolved - https://trello.com/b/Ymc5O1KG/temp-36-bug-board
> :)

Why does this conflict other issues :)

**Comment by Jojo-Schmitz** [comment]
It doesn't. Plain extortion ;-)

**Comment by Jojo-Schmitz** [comment]
Not keeping the promise?

**Comment by Jojo-Schmitz** [comment]
Or will there be another release before Christmas?

**Comment by Marr11317** [comment]
It was nice seeing it this year btw;)

**Pull request merged**
