### PR TITLE
fix #278053 - Failed assert on MusicXML import

### PR DESCRIPTION
**Pull request by lvinken**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Travis CI's mtests are not happy with this, see https://travis-ci.org/musescore/MuseScore/jobs/453642107#L5574-L5616, I don't see though how the changes in this PR relates to octave changes in XML import/export?

**Comment by lvinken** [comment]
Unfortunately, this issue is not yet present in commit 6035ece8 (the last one before 1edd676 where Werner fixed the staff properties issue). Will investigate, but that won't be done today.

**Comment by lvinken** [comment]
Status update: mtest fails because the third part in testVirtualInstruments.xml now gets a staff type percussion, which was pitched before. Note that it is kind of a corner case, as this happens only when a virtual instrument is used and no midi information is present. Still investigating.

**Comment by lvinken** [comment]
Fix pushed, waiting for Travis.

**Pull request merged**
