### PR TITLE
Fix #9779 beam stem direction flip

### LINKED ISSUE #9779: [Inspector] Unable to change stem direction in Properties after applying flip direction with X from keyboard to the group of notes
Unable to change stem direction in Properties after applying flip direction command with X from keyboard

https://user-images.githubusercontent.com/90187801/142410623-cb10c5eb-3e5b-4505-8629-d52da1935d46.mp4

**Desktop:**
Win10/Mac12/LinuxMint20

**Additional context**
Occurs in **MU3** as well

### PR DESCRIPTION
**Pull request by LovCAPONE**
Resolves: *https://github.com/musescore/MuseScore/issues/9779*

Update chord's set stem direction method to set the beam's direction
to Direction::AUTO if applicable.

Update the beam's set direction method to update its notes' stem
direction.

When a beam's direction is set with the "x" keyboard key, the
"_direction" member of the beam class is no longer equal to
"Direction::AUTO". So, in the beam's layout code the final beam
direction is not taken from the first note in the note group
(of the beam) but from the "_direction" member.

The problem is that if the user tries to set the beam's direction
with a note stem direction (in the property panel), it will be
ignored in the beam's layout code.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by LovCAPONE** [comment]
This PR is ready for review.

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
For some strange reason my backport of this to 3.x just crashes. Sure it doesn't in master too?
And is why not there but in 3.x?

**Comment by DmitryArefiev** [comment]
Tested #9779 on latest master build on Win10, Mac12, LinuxMint 20 - FIXED

Thanks!

**Comment by LovCAPONE** [comment]
@Jojo-Schmitz Did you find the issue with the crash in the 3.x branch? If not I can investiage.

**Comment by Jojo-Schmitz** [comment]
No, I didn't. I'd appreciate if you'd investigate ;-) It is this part that's causing the crash:
```
        if (beamDir == Direction::AUTO) {
            beam()->setBeamDirection(beamDir);
        }
```

**Comment by LovCAPONE** [comment]
@Jojo-Schmitz Ok I'm on it. When I find the fix how do I proceed then? PR? Patch? Because I think this bug only affects the 3.x branch.

**Comment by Jojo-Schmitz** [comment]
I don't mind either way, wether you just tell me what to change to make it work or PR against my branch.

**Comment by LovCAPONE** [comment]
@Jojo-Schmitz Ok I'll just make a PR against the 3.x branch.

**Comment by Jojo-Schmitz** [comment]
Or indeed against the 3.x branch

**Pull request merged**
