### PR TITLE
Fix color of shadow note

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #8769 

And simplified the list of colors in EngravingConfiguration and transferred the colors from MScore to EngravingConfiguration. 

---

@bkunda Now the shadow note color equals the voice selection color, but with 0.5 opacity. The result slightly disappoints me; a problem is that the shadow note exists of multiple components which are drawn separately, which becomes obvious with a non-1.0 opacity. It seems not trivial to change the way the note is drawn. 
I also doubt whether the shadow note is visible well enough, especially when you hover a black note that is already in the score. 

You can download the build here from GitHub to try it out.

Maybe it's better to just take the MU3 approach? 

Schermafbeelding 2021-08-07 om 17 21 13

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by bkunda** [comment]
I have to say I quite like this solution @cbjeukendrup, but I think @jessjwilliamson and @Tantacrul should check it out as well because it is an especially noticeable and integral part of how the UI works. 
I'm glad all the colours are working well now, though (gone be the ultra highlight green!).

**Comment by Tantacrul** [comment]
I think you should increase the opacity to 80% so it can pass the minimum contrast ratio.

Currently this is how it performs:
image


You can use this site to test:
https://webaim.org/resources/contrastchecker/

**Comment by Tantacrul** [comment]
Hmmm. I almost wonder if we should remove the opacity entirely?

**Comment by jessjwilliamson** [comment]
Hey just catching up on this thread..

I don't remember having an opacity on note input?.. just a slightly lighter version colour of selected voice 1 colour? I'm not a huge fan of the opacity idea, to be honest. 

"I also doubt whether the shadow note is visible well enough, especially when you hover a black note that is already in the score." I absolutely agree.

**Comment by Tantacrul** [comment]
@jessjwilliamson - if we want to colour to be lighter, then we should create specific colours - along with their 'light' equivalents. Can you do this?

I don't recall if we made any changes to the V1, V2, V3 & V4 colours. They're a little ghastly in MS3 and could do with a tiny bit of refinement.

**Comment by cbjeukendrup** [comment]
I'm not sure if creating another set of lighter colours is a good idea. The voices colors can be customised, so therefore I would prefer if the lighter color is calculated based on the normal voice colours. 

In the end I think the MU3 behaviour was totally fine. The reason for the opacity experiment was that the colors were broken recently, caused by the switch from the `QColor` representation (from Qt) to our own `Color`, and our own colours work a bit differently, so they don't have the `lighter` and `darker` functions that we used from `QColor`. But that can be easily solved by just converting back and forth to `QColor`.

**Comment by cbjeukendrup** [comment]
I returned the MU3 behaviour in #8820.
If we still want to adjust the default selection colours, please let me know, so I can add the change to that PR. The lighter colors for the shadow note and drop target elements will be calculated based on those (35% lighter; the 35% can of course be adjusted too).

**Comment by Tantacrul** [comment]
@cbjeukendrup - sure: some way to apply general ‘lightness’ would fine, although I’d opt for not going too light (again, for contrast reasons). Agree the MuseScore 3 way wasn’t bad.

@jessjwilliamson: in that case, let’s define slightly refined new colours for each voice.

**Pull request merged**
