### PR TITLE
Fix crash when opening score with instruments without instrumentId and without InstrChannels

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #16248
Resolves: #16235

Maybe a candidate for the patch release? Two reports already.

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Now that I think a bit more about it, I'm wondering how it is possible that these instruments without an ID got written to a 4.0.0 file. You'd say that the ID should be determined when opening the score in 4.0.0+, and then it should be written to the file.
Anyway, I still think this fix would make sense...

**Comment by MarcSabatella** [comment]
Perhaps the ID was lost as a result of trying to replace the instrument from 4.0, then backing out of the dialog?  See https://github.com/musescore/MuseScore/issues/14303 for a report of this losing the mixer channel immediately, and a reference to another report in the forum of this then leading to a crash on save/reload.

**Comment by cbjeukendrup** [comment]
Thanks, that sounds very likely. I'll take a look at that issue too.

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Tantacrul** [comment]
@RomanPudashkin - if you're happy, I'm happy to include in the patch release.

**Comment by DmitryArefiev** [comment]
Tested #16248 #16235 on Win10, Mac12, LinuxUbuntu 22.04 - **FIXED**

**Pull request merged**
