### PR TITLE
fix: locale data zh_CN

### PR DESCRIPTION
**Pull request by cw1997**
- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Translations are purly done on Transifex, so make those changes at https://app.transifex.com/musescore/musescore/translate/#zh_CN/$

**Comment by Jojo-Schmitz** [comment]
Actually some of those proposde changes are already in (e.g. "Enable high-contrast",  some "...(experimental)"), so first of all update your translations

**Comment by cbjeukendrup** [comment]
As Jojo says, editing translations is done on Transifex (https://app.transifex.com/musescore/musescore/dashboard/). Editing these files manually is useless, since these changes will be overridden the next time we pull strings from Transifex. 
(And when creating a release build, these files are not used anyway, because then the strings are directly taken from Transifex.)

I also second Jojo's remark about the IO device string.

**Comment by cw1997** [comment]
> Translations are purly done on Transifex, so make those changes at [app.transifex.com/musescore/musescore/translate/#zh_CN/$](https://app.transifex.com/musescore/musescore/translate/#zh_CN/$)
> 
> Actually some of those proposed changes are already in (e.g. "Enable high-contrast", some "...(experimental)"), so first of all update your translations. As far as I can tell from Google Translate, those about "I/O device not opened for reading/writing" are correctly translated already and your translation is wrong, changes the meaning to "I/O device for reading/writing not opened", a different thing.
> 
> So as far as I'm concerned, this PR should get closed, not merged.

Sorry, I open the link https://app.transifex.com/musescore/musescore/translate/#zh_CN/$ but it reports 404 not found.
image

**Comment by cw1997** [comment]
> Perhaps you need to log in or create an account first, via [app.transifex.com](https://app.transifex.com).

Sure! As u can see, I have already signed in Transifex, but it still shows 404 not found.
image

**Comment by cbjeukendrup** [comment]
That's strange... Also I wonder a bit about the text on your profile page: "Your trial has ended and your account has been locked. Please subscribe to a plan to continue using Transifex." Perhaps that's what causing problems. I'm not sure how to solve that though; I've never seen anything about a "trial" or a "plan" on my Transifex... perhaps they make a distinction between open-source accounts (which you can use for MuseScore) and commercial (?) accounts.

Another thing to try: what if you go to https://explore.transifex.com/musescore/musescore/ ? That should bring you to a page with a "join project" button. 
If that doesn't work, try logging out, then going to that link, clicking "join project" and logging in, or creating a new account.

**Pull request closed without merging**
