### PR TITLE
fix #281112: enable time stretch customization for articulations [WIP]

### PR DESCRIPTION
**Pull request by Howard-C**
Resolves: https://musescore.org/node/281112.

A new in-class valuable `_gateTime` to store the customized value.

The tricky part is the addition of `_gateTimeInitialized`. `propertyDefault()` needs a value based on the instrument in instruments.xml, so `this->part()` should be called. This is done in `defaultGateTime()`, but the first call of `propertyDefault()` is before `part()` exists, which means `defaultGateTime()` cannot be called. So a temporary value 1.0 is assigned, but it's subsequently overwritten by `InspectorArticulation::setElement()`, which assigns the correct default value if `_gateTimeInitialized` is `false`, meanwhile setting it to `true`.

### CODE REVIEW

**Comment by Howard-C** [comment]
There will be a weird tag written upon the second load and save. It may be related to the flawed `_gateTimeInitialized` workflow,

**Comment by MarcSabatella** [comment]
Thanks for tackling this!  The plugin is nice and all, but it does feel like there should be native controls.

The Travis failures is a bunch of gateTime tags that shouldn't need to be there since the value is the default of 1.0.  So something about the way you are dealing with the property flags or the default value isn't working as it should.  I think maybe it shouldn't be set to STYLED, as you didn't also add a style settings for this?

**Comment by Howard-C** [comment]
Maybe. But besides that, the `_gateTimeInitialized` workflow still is flawed. Copy and paste loses the custom value, reload loses the custom value too. Even if I can somehow fix this, it can become broken any time, since this isn't a standard workflow and is hard to maintain. So I really need to find another way to bypass the "`part()` doesn't exist" thing...

**Comment by Jojo-Schmitz** [comment]
TravisCI is not happy, seems several mtests fails and either need to get adjusted or the code needs to get changed to avoid those mtests to fail, like never write `<gateTime>1</gateTime>` onto the score, being the default anyhow?

**Comment by Howard-C** [comment]
What really bother me are https://github.com/musescore/MuseScore/pull/5598#issuecomment-573278406 and the midi test failures, which suggest even start-tick differences.

**Comment by Howard-C** [comment]
Closing for now.

**Pull request closed without merging**
