### PR TITLE
[4.4.3] Another attempt at fixing the OpenGL issue with the AppImage

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: https://github.com/musescore/MuseScore/issues/24228

Ports: https://github.com/musescore/MuseScore/pull/24696

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Let's see how this goes on ARM... https://github.com/cbjeukendrup/MuseScore/actions/runs/10865732002

**Comment by cbjeukendrup** [comment]
Another attempt: https://github.com/cbjeukendrup/MuseScore/actions/runs/10872223342/job/30166979810

**Comment by cbjeukendrup** [comment]
https://github.com/cbjeukendrup/MuseScore/actions/runs/10876035218/job/30175371186

**Comment by cbjeukendrup** [comment]
Success, finally: https://github.com/cbjeukendrup/MuseScore/actions/runs/10876561482

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
