### PR TITLE
fix #277055: Add StaffText to a Segment instead of Measure when reading Guitar Pro files

### PR DESCRIPTION
**Pull request by dmitrio95**
The proposed changes intend to partially fix [the issue](https://musescore.org/en/node/269924) on crashes when reading Guitar Pro files. The issue includes several smaller problems, and this pull request intends to fix a problem on attaching the read StaffText to a wrong parent (`Measure` instead of `Segment`).

Should the described issue be split perhaps into some smaller issues?

### CODE REVIEW

**Comment by lasconic** [comment]
You could create a specific issue for the problem and use it in the commit message. Also, is it useful to have a test case for this bug  and add it to mtests ?

**Comment by anatoly-os** [comment]
The explanation of why you decided to change the call from `Measure::Add` to `Segment:Add` is also interesting.

**Comment by dmitrio95** [comment]
@anatoly-os The explanation is rather simple:
1) `StaffText` is added to a `Segment` every time it is created in other parts of code (including reading MSCX format: [1](https://github.com/musescore/MuseScore/blob/c354eb24c3a8e4844ee60cbf74ef88018b832010/libmscore/measure.cpp#L2196), [2](https://github.com/musescore/MuseScore/blob/c354eb24c3a8e4844ee60cbf74ef88018b832010/libmscore/measure.cpp#L2167)).
2) Calling `Element::add` implies setting the corresponding parent for the added element while it is assumed (at least via a [call to `autoplaceSegmentElement`](https://github.com/musescore/MuseScore/blob/c354eb24c3a8e4844ee60cbf74ef88018b832010/libmscore/stafftext.cpp#L51) on layout) that the parent should be a `Segment` rather than any other type of element.

That suggests that the code adding `StaffText`s to `Measure` in `importgtp` files is probably obsolete and should be changed to adding `StaffText`s to a `Segment`.

@lasconic A test case should indeed be useful. Still it seems it is better to create a sample Guitar Pro files from scratch rather than using the files from the bug report?

**Comment by lasconic** [comment]
Yes, always better to have a simple file.

**Comment by dmitrio95** [comment]
Added some tests on reading those "capo fret" marks which were mostly involved in the discussed crash.

**Comment by anatoly-os** [comment]
@dmitrio95 could you please add "fix #XXXXXX" at the beginning of the PR title and the commit message? Squashing commits is also good thing to do.

**Pull request merged**
