### PR TITLE
Fix #271103: Add 7-string Guitar and Cavaquinho (4-string Guitar)

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
also tablature for both, the former needs a 7-string tablature type.
Sorting that tablature type array by # of lines.

See also https://musescore.org/en/node/271096

Not sure we really need 3 different types of tablature for 7-string, or whether we'd also want 8-, 10-, 11-, 13-string tablatures (and guitars) too.

The changes to stafftype.cpp won't cherry-pick cleanly to 2.3, let me know whether an extra PR is needed

### CODE REVIEW

**Comment by lasconic** [comment]
Where is 271103 ? not the right id maybe?

**Comment by Jojo-Schmitz** [comment]
It should be the right ID, but seems to have been unpublished, probably by an over-zealous spam filter. I've asked for it several times on IRC...

**Comment by lasconic** [comment]
OK @thomasbonte will look into it

**Comment by Jojo-Schmitz** [comment]
Seems the idea to sort tablature types by number of lines breaks mtests.

**Comment by mgavioli** [comment]
Well, I don't know about modern practice, but historically no tablature has ever been used with more than 6 lines, no matter of the number of strings of the instrument; the _n_-string (archi)lute / theorbo as well as the 7-string viola da gamba all used the 6-line tablature, with some typographical device to notate the additionally strings.

This leads me to believing that a tablature with more than 6 (exceptionally maybe 7) lines would be practically unreadable and of very little usefulness. Unless there is a strong demand for it with very solid use cases, I would not take this slippery path.

**Comment by Jojo-Schmitz** [comment]
OK, so no 8-, 10-, 11-, 13-string tablatures needed.

**Comment by Jojo-Schmitz** [comment]
Fixed GuitarPro mtest failures. Revealed that also the 5-string tablatures were missing from the `StaffTypes` enum, added those along with a comment hinting that this and the _presets initialization needs to be kept in sync

**Comment by lasconic** [comment]
What's the rationale for changing the order of the presets? I kind of like the way it was, somehow listed by rareness. Do we really need the 3 variants for 7 strings? FWIW, Guitar Pro goes up to 8 strings.

image

**Comment by Jojo-Schmitz** [comment]
Sorting by rareness should be OK too, and just one variant for 7-string (and another for 8-string) should indeed be enough

**Comment by Jojo-Schmitz** [comment]
Which of the three 7-string tablatures to keep (and use for 7-string Guitar)?
Same question for 8-string.

**Comment by lasconic** [comment]
@mgavioli 7 and 8 are supported for modern instruments in GuitarPro but that's the end of the slippery path.
@Jojo-Schmitz  I would just put the common preset though.

**Comment by anatoly-os** [comment]
@Jojo-Schmitz could you please rebase to 2.3 and squash commits?

**Comment by Jojo-Schmitz** [comment]
Squashed, not sure why cherry-pick won't work to pull it into 2.3?

**Pull request merged**
