### PR TITLE
{MU4] Fix finding libsndfile for MSVC

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
As discussed in https://github.com/musescore/MuseScore/pull/11143#issuecomment-1111934130 ff.

### CODE REVIEW

**Review by igorkorsukov — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Mind to update dependencies.z7 with the latest libsndfile stuff now?
So we're really all benefitting from this, and not just those who build locally and know how to get that stuff done?

**Comment by cbjeukendrup** [comment]
Personally, I'm not against. I've been using libsndfile 1.1.0 (the latest version) for a while now on macOS, without any problems. So it might work on Windows too.

**Comment by Jojo-Schmitz** [comment]
It does, as far as I can tell, using libsndfile 1.0.31, (which I believe was the latest mid-March?)
Updating to 1.1.0 as we speak ;-)

**Comment by igorkorsukov** [comment]
I would prefer to just get rid of libsndfile :), for this we need to rewrite the soundfont loader for fluidsynth 
In order not to use different libraries for the same thing in different places of the project, and to reduce dependencies

**Pull request merged**
