### PR TITLE
Fix #100636 : [Piano Roll] The score view doesn't paint correctly when selection in the piano roll changes.

### PR DESCRIPTION
**Pull request by luyikei**
https://musescore.org/en/node/100636

### CODE REVIEW

**Comment by lasconic** [comment]
Can you squash the two commits?  http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by luyikei** [comment]
Is this fine?

**Comment by lasconic** [comment]
Yes, looks good. You need to sign the Musescore Contributor License Agreement at https://musescore.org/en/cla so I can merge this PR.

**Comment by luyikei** [comment]
I signed it.

**Comment by lasconic** [comment]
Thank you and welcome in the MuseScore contributor community!

**Pull request merged**
