### PR TITLE
modified PR #2288 scrolling with stricter rules and simpler code

### PR DESCRIPTION
**Pull request by ericfont**
Folks, I spent a few hours looking into AntonioBL's scrolling code which I modified to obey stricter rules:

1. When moving right, ensure the left edge of system won't be right of frame's left edge margin.
2. Never move left if entire system already fits entirely within the frame.
3. When moving left, ensure the right edge of system won't be left of frame's right edge margin.

### CODE REVIEW

**Comment by ericfont** [comment]
Here is an image showing the furthest that each score is able to be scrolled rightward:

screenshot 133

Here is an image showing the furthest that each score is able to be scrolled leftward:

screenshot 132

Note that I'm leaving a little boundary.  But there is no way for the scrolling to exceed my stricter rules.

**Comment by ericfont** [comment]
not quite done...I need to make sure works with window resizing.

**Comment by ericfont** [comment]
Note, the reason for rule 2 is so that system always remains left-justified inside the Frame.  That ensures that scrolling doesn't get messed up when the Widget's right edge position is adjusted.

**Comment by ericfont** [comment]
I just noticed that start with a large time sig (like 40/4) with each score moved all the way leftward, then if switch to smaller time sig (like 4/4), then it will get lost cause is way to far left.  So I need to reset the scrolling when time sig is changed.

**Comment by ericfont** [comment]
Ok, I fixed that issue I just described by adding a resetMatrix() function which gets called when the numerator or denominator changes, to reset scrolling so that can always see the new time signature's systems starting at the left of the frame.  So this PR I think is ready for review.

**Comment by lasconic** [comment]
looks good.

**Comment by ericfont** [comment]
There is one super minor glitch I didn't account for: If have tons of 32nds, and have them moved all the way left, then if increase right hand side of window a little (not more than enough to hold all the 32nds), then if select and drag mouse left a bit, then view will immediately place the right end of system just within the right edge of the frame...  I should say this this is not really undesirable behavior, and honestly I'm don't think is even worth fixing cause would have to add extra code to adjust the scrolling when the window is dragged.  I'm just making a note of this for reference.

**Pull request merged**
