### PR TITLE
fix #5163 Add PortAudio Midi Output

### PR DESCRIPTION
**Pull request by lasconic**
For 2.2 branch

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
How about giving it a try, so it can get tested in the 2.2 nighlies?

**Comment by ypresto** [comment]
On macOS, building MuseScore requires building Qt from source or downloading 3.5GB binary.
I wanna try nightly build!

**Comment by Jojo-Schmitz** [comment]
Nightly builds for macOS are available on https://ftp.osuosl.org/pub/musescore-nightlies/macosx/, this particular fix though is not in any 2.2 nightly yet though, only in those from master

**Comment by lasconic** [comment]
You can find nightlies here for MacOS http://prereleases.musescore.org/macosx/nightly/
If you need a small download (it will not contain everything Qt but only what you need, you can get it here http://utils.musescore.org.s3.amazonaws.com/qt-opensource-mac-x64-clang-5.4.2.dmg

**Comment by ypresto** [comment]
> I wanna try nightly build!

Oops, I meant I wanna try *this PR* as nightly build too :bow:
Anyway thanks for instruction about nightly builds and Qt binary. I'll try it later!

**Comment by lasconic** [comment]
Since we do have some people willing to test this in 2.2, let's merge it and see how it works out. We can always revert if something goes wrong.

**Comment by jurf** [comment]
@lasconic, hey, this is failing to build on Flathub, see https://github.com/musescore/MuseScore/pull/3170#issuecomment-377807290.

**Pull request merged**
