### PR TITLE
Fix several issues with repeat and volta. Counterpart of PR #3371

### PR DESCRIPTION
**Pull request by lasconic**
Some test files are missing. They need to be recreated in MuseScore 2.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
That "add property 'play repeats' to jump elements" commit would fix issues #56451 and #44666 . Not sure the commit message can get tweaked to mention that, if it is a cherry pick?

**Comment by lasconic** [comment]
Sure it can. I'll do that.

**Comment by lasconic** [comment]
Commit message updated. Added the tests from PR #3371 redone in 2.2.

**Comment by lasconic** [comment]
Here we go. Happy testing everyone!

**Comment by lasconic** [comment]
And thank you to everyone involved ! @jeetee @Jojo-Schmitz @wschweer @MarcSabatella

**Comment by MarcSabatella** [comment]
Can't say I actually did anything here, but I'm certainly thankful for those who did!  I assume this will mean some documentation changes for 2.2, but it also seems they will be welcome changes as the story should be simpler now.

**Comment by Jojo-Schmitz** [comment]
Well, actually 2.2 should no behave as per the documentation in the handbook.

**Comment by MarcSabatella** [comment]
OK, so this only about setting of volta properties, none of the other changes I saw about voltas appearing in places other than at the end of a repeated section or allowing repeats on DS etc are included?

**Comment by Jojo-Schmitz** [comment]
Ah, yes. But that is more about additional feature, not about having to change existing documentation, just add to is?

**Comment by MarcSabatella** [comment]
Gotcha.  Didn't realize the Handbook was actually wrong.  How about tutorials, how-tos, etc?  Still, seems it would be useful to have a clear summary of what is actually changing so we can make all necessary corrections or additions wherever they may needed.

**Comment by lasconic** [comment]
First it adds the "Play repeat" checkbox on jump to choose if one wants to play the repeats after a jump (DC, DS etc...) or not (it's off by default, like in 2.1)

Then as said by @jeete in PR #3371 
"*Where 2.x currently requires the repeatlist of a volta to be set to the n-th time that measure/volta is encountered, this PR requires the repeatlist to reflect the human-readable logic of being the x-th repeat in total.*"
In practice, it means that now the third coda should work out of the box. And we have the ability to define 4., 5. etc... easily. We can also have complex voltas (1.3. and 2.4 for example) and playback works!

On top of that, the algorithm is now smarter and will stop a open volta when a new volta is found and doesn't require the open volta to span until the next repeat barline.

**Pull request merged**
