### PR TITLE
'Play' property for the Bend class + tests

### PR DESCRIPTION
**Pull request by Igevorse**
As were requested in a comment to PR https://github.com/musescore/MuseScore/pull/2040:
1. Implemented 'Play' property for bends: it's possible to mute them now.
2. Tests for exporting bends to a MIDI file.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
wouldn't his requite to bump up the file format version number?

**Comment by Jojo-Schmitz** [comment]
Wouldn't his require to bump up the file format version number?
What happens if an older version of MuseScore opens an mscz/mscx file that does use this property, if it just ignores it, fine, although I guess then that property gets lost on write. But I think instead MuseScore would complain about a bad format, wouldn't it?

**Comment by Igevorse** [comment]
@Jojo-Schmitz I opened the test file with an older version of MuseScore. I had several error messages ("xml read error at line 231 col 24: playBend"), but score opened well.
XmlReader::unknown() works well for unknown tags.

**Comment by Jojo-Schmitz** [comment]
OK, then we're just losing information when saving with that older version. Not my call to decide whether this is acceptable or whether having a file version bump make the user aware of that.

**Pull request merged**
