### PR TITLE
MusicXML: Add export for smufl noteheads

### PR DESCRIPTION
**Pull request by rettinghaus**
Addresses notehead issue from #17553

### CODE REVIEW

**Comment by rettinghaus** [comment]
@cbjeukendrup could you have a look here, please?

**Comment by cbjeukendrup** [comment]
Here too it would be nice to have a test file where we see this new code in action. But the code itself looks good to me!

**Comment by Jojo-Schmitz** [comment]
that new unit test crashes

**Comment by rettinghaus** [comment]
@cbjeukendrup test added

**Review by cbjeukendrup — APPROVED** [review]

**Pull request merged**
