### PR TITLE
Fix - Make text labels on radio buttons clickable

### PR DESCRIPTION
**Pull request by shubham-shinde-442**
Resolves: #25576 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Can't we use the `StyledTextLabel` that's inside RoundedRadioButton, by setting its `text` property? That way we wouldn't need to create separate StyledTextLabels.

**Comment by shubham-shinde-442** [comment]
@cbjeukendrup I tried using the `text` property initially, but probably due to alignment issues, the labels were not visible. So I went with the initial setup and implemented the solution using `StyledTextLabel`.

**Comment by cbjeukendrup** [comment]
I see. The problem seems to be inside RoundedRadioButton: the `implicitWidth` and `implicitHeight` values are not really good. I think we should make those much simpler, like this:
```c++
implicitWidth: leftPadding + implicitIndicatorWidth + spacing + implicitContentWidth + rightPadding
implicitHeight: topPadding + Math.max(implicitIndicatorHeight, implicitContentHeight) + bottomPadding
```
This means that the width will need to be overridden in some places where RoundedRadioButton is used. That may take a while, but I think it's worth it; it makes the behaviour of RoundedRadioButton more predictable and makes it more generally applicable.

**Comment by shubham-shinde-442** [comment]
@cbjeukendrup  Apologies for the delay. 

This is not working in `RoundedRadioButton`.
> ```c++
> implicitWidth: leftPadding + implicitIndicatorWidth + spacing + implicitContentWidth + rightPadding
> implicitHeight: topPadding + Math.max(implicitIndicatorHeight, implicitContentHeight) + bottomPadding
> ``` 
It seems the issue lies with the width of the `RoundedRadioButton` only. The implicitWidth works well when there is a [ListView](https://github.com/musescore/MuseScore/blob/c88f6e64840878f34d281d96a14b529e722a64ae/src/framework/uicomponents/qml/Muse/UiComponents/RoundedRadioButton.qml#L38), but setting it to [20](https://github.com/musescore/MuseScore/blob/c88f6e64840878f34d281d96a14b529e722a64ae/src/framework/uicomponents/qml/Muse/UiComponents/RoundedRadioButton.qml#L42) doesn't seem effective in this case. Perhaps adjusting the Implicit width to around 50 and setting the [text label](https://github.com/musescore/MuseScore/blob/c88f6e64840878f34d281d96a14b529e722a64ae/src/framework/uicomponents/qml/Muse/UiComponents/RoundedRadioButton.qml#L87) width property to approximately around 15 might resolve the issue. What are your thoughts? (feel free to correct me)

**Comment by cbjeukendrup** [comment]
@shubham-shinde-442 After some investigation, I found that some more changes were needed; I made those in https://github.com/musescore/MuseScore/pull/25778/commits/c1d7bb36451e200f15401dae3c5e9920542acb6d. I'll close this PR, but thanks anyway for your contribution!

**Pull request closed without merging**
