### PR TITLE
Fix panning score during playback and note input and when selecting elements

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #9775

By fixing NotationPaintView::canvasPos, which fixes in turn NotationPaintView::adjustCanvasPosition.

Also replaced some QPointF to PointF.

### CODE REVIEW

**Comment by DmitryArefiev** [comment]
Tested (#9775, #9912, #9812, #9615) on Win10, Mac12, LinuxMint 20.2 - FIXED      

Please merge into master

Thanks!

**Comment by bkunda** [comment]
This is great! Thanks so much @cbjeukendrup ☺️

My only request for this, to bring it more in-line with MS3.6 behaviour, is that panning during note entry mode should position the system higher than it currently does in this build. It mainly affects higher zoom levels when working on upper staves in a system. At the moment, the upper staff appears at the bottom of the score window, whereas in MS3.6 the entire system always seems to be visible (I dare not say "vertically centred", because it seems to sit slightly lower than the vertical centre point. But systems are certainly higher up than where this build repositions them while panning).

Just to give you a side-by-side of Ms3.6 v. this build's behaviour (both 4-staff systems at 252% zoom, entering notes on uppermost staff):

MS3.6
MS3 6-pan-252-highest-staff

This build
MS4-pan-252-highest-staff

Let me know if this needs to be raised as a new issue, or if it can be incorporated into this PR before merging. Thanks!

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Hello @bkunda, we decided to merge it because a lot of issues were fixed with this PR!
Can you log the issue above separately please (about matching with MU3.6 regarding note input) ? 

Thank you! :)

**Comment by cbjeukendrup** [comment]
@DmitryArefiev I think that's a good idea! I'll try to tackle the discrepancies between mu3 and mu4 as soon as I can.

**Comment by bkunda** [comment]
No problem @DmitryArefiev, and will do! Thank you :-)

**Pull request merged**
