### PR TITLE
fix travis ci readme badge

### PR DESCRIPTION
**Pull request by ivebencrazy**
This was just bugging me.
I guess at some point Travis started requiring a branch name 🤷‍♂️

### CODE REVIEW

**Comment by jthistle** [comment]
Does the badge need fixing? It displays fine for me, saying that there was an error in building...

**Comment by ivebencrazy** [comment]
Oh maybe, I was just assuming that this badge was supposed to point at master branch, like the appveyor one.

Not sure what it's pointing at right now, exactly, but it shows up as [error] on master branch for me; if it's supposed to show any error on any branch, then that one will never show pass haha.

**Comment by jthistle** [comment]
Ah, I see. I just assumed the last master build errored :)
In that, case, it seems like a good enough change. And congrats on your first MuseScore PR! I don't know if a change this small requires signing [the CLA](https://musescore.org/cla), but there's no harm in doing so.

**Comment by ivebencrazy** [comment]
Thanks! 🎉  I've been using MuseScore for years, but had never taken a look at the repo before. Would be cool to start making contributions here and there. Re CLA, 🤷‍♂️ I just signed it right now. I was intending on looking at more... uhhh... real fixes anyways, so may as well.

**Comment by anatoly-os** [comment]
Let's see whether the builds are ok.

**Pull request merged**
