### PR TITLE
fix #248891: chord symbols don't transpose in mixed company

### PR DESCRIPTION
**Pull request by MarcSabatella**
I had written this some time ago but got distracted by the fact that chord symbols seemed totally broken on master, so I never submitted a PR.  I'm not sure of the status for master, but this branch should work for 2.2 (additional testing welcome).

Note this does not address the key signature problem I noted in the original issue -
 reported separately as https://musescore.org/en/node/70201.  There is a separate PR for that, but I cannot vouch for it.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
This also doesn't address transposition when the parts are generated.  So if a score is in concert pitch at the moment you generate parts, the parts are incorrect.  I'll look at adding a commit for that.

**Comment by MarcSabatella** [comment]
Depending on what Travis says, this should be good for 2.2.  Looking into doing same for master.

**Comment by MarcSabatella** [comment]
FWIW, I'd like to see this in 2.2 if possible. master still seems pretty broken with respect to chord symbols so I'm not sure what to do there, but this current PR is good for 2.2

**Comment by Jojo-Schmitz** [comment]
Too late for 2.2 unfortunatly, but maybe rebase to the new 2.3 branch

**Comment by MarcSabatella** [comment]
Despite the tag, this work isn't "in progress", it's been done for a while, with respect to 2.x.  Chord symbols remain completely broken with respect to parts on master, so no way to test this there.

**Comment by RobFog** [comment]
The "work in progress" label can go?

**Comment by MarcSabatella** [comment]
This was closed, but wasn't merged that I know of?  It's not something that comes up often, so if we don't want to merge it last minute for 2.3.2 that's OK.  But you never know if a 2.3.3 will come up, I see no harm in keeping it open?

**Comment by anatoly-os** [comment]
See https://github.com/musescore/MuseScore/pull/4298 for master.

**Pull request closed without merging**
