### PR TITLE
Fix #18352: Fix minimum values in fretboard diagrams

### LINKED ISSUE #18352: Regression - Musescore 4 Fretboard Has Minimum of 4 Strings. Version 3 allowed
### Issue type

Other type of issue

### Bug description

Unable to work on dulcimer music with chord charts in Musescore 4 as the new Fretboard editor has a minimum of 4 strings. Mountain dulcimers (and plenty of other instruments as well) typically feature 3 courses. Please eliminate the minimum. 

### Steps to reproduce

View the "Fretboard diagram" settings panel and attempt to reduce the number of strings below 4. The UI won't allow fewer than 4 strings. 
There is no such limit in Musescore 3.

### Screenshots/Screen recordings

image

### MuseScore Version

4

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iwoithe**
Resolves: #18352

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Please fix the visible frets minimum too

**Review by oktophonie — APPROVED** [review]

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Do we want this for 4.1.0 too?

**Comment by bkunda** [comment]
We're only pushing fixes to 4.1 that are regressions on the current stable release, or which fix critical app stability problems, or which are problems with a new feature going in. 
Unless we can be absolutely certain a fix isn't going to adversely affect anything else in the app, I'd rather put it to the next release (I rely on @RomanPudashkin to advise on the risk here).

**Comment by Jojo-Schmitz** [comment]
This in is a Mu3 regression, and as hamless as it can be in terms of stability. Not a new feature at all

**Pull request merged**
