### PR TITLE
Add an 80 pixels icon-round in the assets folder.

### PR DESCRIPTION
**Pull request by Marr11317**
Needed by some APIs such as the Microsoft office addin API.

### CODE REVIEW

**Comment by dmitrio95** [comment]
Could you please provide a link to the documentation of that API which requires this 80-pixel icon?

**Comment by Marr11317** [comment]
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-addin-commands#step-6-add-extensionpoint-elements

If you scroll down just a little bit, to **ICON**, you can read this description:

>Required. Specifies the group's icon to be used on small form factor devices, or when too many buttons are displayed. The resid attribute must be set to the value of the id attribute of an Image element. The Image element is a child element of the Images element, which is a child element of the Resources element. The size attribute gives the size, in pixels, of the image. **Three image sizes are required: 16, 32, and 80.** Five optional sizes are also supported: 20, 24, 40, 48, and 64.

**Comment by dmitrio95** [comment]
OK, thanks for the reference. Then I guess it should be installed somewhere along with MuseScore to have an effect? Or how is this icon supposed to be used?

**Comment by Marr11317** [comment]
This icon won't show in the MuseScore app, it is only for developpers looking for MuseScore icons for a project outside this repo.

**Comment by dmitrio95** [comment]
But developers can just generate if from `.svg` in this repo, can't they? There are many different icon sizes which are needed in different situations but are not present in MuseScore repo (like 20, 30, 40, 72, 192, even some sizes with odd dimensions like 29px), should we really add them all to the repository?

**Comment by Marr11317** [comment]
Maybe not. But I didn't know that these were common formats.
You are right. It is kinda useless. Close it if you think it is not worth it.

**Pull request closed without merging**
