### PR TITLE
Updating backend build env to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
as 18.04 is deprecated and will get discontinued shortly, _fully unsupported by 2023/04/01_

See https://github.com/musescore/MuseScore/actions/runs/4433107633

### CODE REVIEW

**Comment by Eism** [comment]
Thank you for reminding.
The backend is not ready to migrate to ubuntu 20.
But yes, we need to solve this problem as soon as possible.

**Comment by Jojo-Schmitz** [comment]
Before the end of this month actually ;-)

**Comment by Jojo-Schmitz** [comment]
BTW: why would we want to build the backend once a week?

**Comment by igorkorsukov** [comment]
> BTW: why would we want to build the backend once a week?

Because when it's really needed, it often turns out that the build is broken. We would like to detect a breakdown in advance.

**Comment by Jojo-Schmitz** [comment]
I see, sort of a securite measure

**Comment by Eism** [comment]
@Jojo-Schmitz 
Please cherry-pick these two commits https://github.com/musescore/MuseScore/commit/710a998222486906279786bd0ea6a164f1bed841 and https://github.com/musescore/MuseScore/commit/9c553d8c541c04afddbfa102cbe8a199aa024367

**Comment by Jojo-Schmitz** [comment]
I guess
```
$ git cherry-pick 710a998
fatal: bad revision '710a998'
```

**Comment by Jojo-Schmitz** [comment]
Got it, manually cherry-picked them

**Comment by Jojo-Schmitz** [comment]
See https://github.com/musescore/MuseScore/actions/runs/4624991158 CI_backend got stuck 8 hours ago...

**Review by Eism — APPROVED** [review]

**Pull request merged**
