### PR TITLE
Fix #108161: barline inspector

### PR DESCRIPTION
**Pull request by akhilabrahamt**

### CODE REVIEW

**Comment by jthistle** [comment]
Good so far. A couple of things: to make things clearer, all the commits should be squashed.

You can do this with an interactive rebase: `git rebase HEAD~3 -i`. Squash the commits that aren't the 'fix #...' and 'pick' the 'fix' commit. Then force push your branch: `git push origin issue-bug -f`.

**Comment by MarcSabatella** [comment]
Also, revision.h shouldn't be part of your commit.  Re-read the compilation and git workflow instructions and be sure to follow them precisely.  Maybe someone else can tell you what specifically you did wrong, I know I've seen this before but forget what causes it.

I want to commend you on getting to this point so quickly!  However, I have to wonder if the change here really works.  Looks to me like it will prevent *any* barline from showing anything in the Inspector.  The goal is to make the *initial* barline (the one at the beginning of each system) not shwo in the Inspector, but other barlines still need to.

However, I also wonder if perhaps things have changed now to the point where it's OK for initial barliens to be accessed in the Inspector?  I just tried changing type, and while there were glitches, it did actually work to some extent.

**Comment by Jojo-Schmitz** [comment]
Very strange that GitHub claims these commits having been ondone on June 9th?

**Comment by akhilabrahamt** [comment]
@jthistle will do that next time!
@MarcSabatella still haven't figured out why revision.h was included. 
@Jojo-Schmitz yes, I have signed the CLA. It's akhilabrahamt.

**Comment by anatoly-os** [comment]
Unfortunately, the reviews were not addressed for a long time.

**Pull request closed without merging**
