### PR TITLE
Fix #275694: start center doesn't close on esc

### PR DESCRIPTION
**Pull request by jthistle**
See, https://musescore.org/en/node/275694, and #3885

### CODE REVIEW

**Comment by jthistle** [comment]
Right, this code isn't exactly what I wanted to push @anatoly-os , because GitHub is experiencing some problems at the moment, so it hasn't updated it with my latest local push yet. Once they fix the problems it should be correct though: https://status.github.com/messages

**Comment by anatoly-os** [comment]
I wonder why are these changes needed now, why and how did it work before?

**Comment by jthistle** [comment]
I have no idea, I'll have a look through the git blame.

**Comment by jthistle** [comment]
@anatoly-os just a guess, but maybe @handrok 's addition of the WebView made it focus on that instead of on the actual dialog. You'll notice that it doesn't work until you click on the start center, then the keyboard shortcuts work fine. My code just automatically focuses on the dialog.

**Comment by anatoly-os** [comment]
Ah, I see. Lol, your changes to the masterpalette are just coincidence :) sorry again. I will talk to @handrok tomorrow.

**Comment by Jojo-Schmitz** [comment]
Wrong issue number in commit- and PR title, should be #275694

**Comment by jthistle** [comment]
All fixed :) @Jojo-Schmitz @anatoly-os

**Comment by anatoly-os** [comment]
@jthistle great! Thank you for being around.

**Comment by shoogle** [comment]
See #4540

**Comment by jthistle** [comment]
@shoogle I didn't break something, did I?

**Comment by shoogle** [comment]
@jthistle, no it was already broken. I was just point that there was a better fix available that handling the Esc key. I meant to comment on #3885 but it landed here instead (too many tabs open! :wink:).

**Pull request merged**
