### PR TITLE
fix #116771 fix #119101: NoteDot visibility

### PR DESCRIPTION
**Pull request by Fyrult**
…ility with note and dot selected

When toggling the note's visibility, check to see if the note's dot is also selected.

### CODE REVIEW

**Comment by lasconic** [comment]
I don't really think it's a good idea to mess with the selection in setProperty. Could we solve it earlier in scoreview.cpp?

**Comment by Fyrult** [comment]
I initially considered fixing it in scoreview.cpp, but I thought that the actual problem was that the note changes the dot's visibility when it really wasn't supposed to. If a solution is preferred in scoreview.cpp, that's a possibility too.

**Comment by Fyrult** [comment]
For #119101, moved the part related to changing notedot's visibility to scoreview.cpp
I think the only main consequence this has is that, from the inspector, changing visibility of the notehead won't change the visibility of the dot (this may be an improvement, since then there is a way for users to change only the notehead. This also shows that the inspector is low-level.).

For #116771, same as before, don't toggle dot again.

**Comment by IsaacWeiss** [comment]
This now has merge conflicts.

**Comment by Jojo-Schmitz** [comment]
Issue came up again, thie PR still needs a rebase.

**Comment by Jojo-Schmitz** [comment]
See #4954, which seems to replace thise PR here

**Comment by Jojo-Schmitz** [comment]
Can we close this now, as #4954 has just been merged?

**Comment by Jojo-Schmitz** [comment]
Or now, with #4980?

**Comment by anatoly-os** [comment]
@Jojo-Schmitz yep. Thank you!

**Pull request closed without merging**
