### PR TITLE
more navigation fixes

### PR DESCRIPTION
**Pull request by MarcSabatella**
Still finding a few glitches in navigation for voice > 1 in note input mode:

- cursor right into an empty measure is possible (good) unless there is a subsequent measure with notes in that voice (bad)

- same for cursor left, but here there is also a glitch where if there is no previous measure with notes in that voice, the first cursor left action would appear to not work

I tested this as well as I could think to.  I'm attaching the file I did most of my testing with to the issue report https://musescore.org/en/node/69866.  Try clicking a note in voice 2 then cursoring right to end of score, left to beginning, and back to starting place, to cover all the cases I am trying to be sure to handle.  They all work.  it is of course possible I am still missing something, but this much at least works smoothly.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
@mgavioli : see my changes in scoreview.cpp to fix https://musescore.org/en/node/73876#comment-338041 and let me know what you think.  The idea is, a grace note might already be selected when we call ScoreView::moveCursor, and I don't want this to reset the selection to a note in the parent chord.  Otherwise, there is no way to navigate through grace notes.

**Comment by mgavioli** [comment]
@MarcSabatella : simply by looking at the code (which, I agree, might be not enough), it is not clear to me which is the purpose of the change to `scoreview.cpp`. The purpose of that part of the code is to _vertically_ move the input cursor (the transparent rectangle) to a specific note, if there is a 'blue-selected' note in the current 'input-cursored' chord. If the 'blue-selected' note is another chord, it should not trigger (the input cursor should not move _horizontally_), even if that other chord happens to be in the same segment (being a grace chord of the segment/track main chord).

Two more general notes:

1) It seems to me that `InputState` is lacking a member variable. Currently, it assumes that segment/track are enough to identify a chord(/rest); but this is no longer true, since graces are in the same segment/track of their main chord. It is possible that to solve cursor movements into/from grace chords, an additional `ChordRest*` member variable is needed to keep track of the current chord?

2) Should not cursor movements into/from graces also take into account that there are before-chord and after-chord graces?

**Comment by MarcSabatella** [comment]
Although the *purpose* of that part of the code might have to do with vertical cursor motions, the problem is the code is also hit during *horizontal* motions.  So on every horizontal motion, we were looking for a note on the current string and selecting it if found.  That's fine in general, but it puts a dead stop to cursor navigation if grace notes are present.  See the issue report https://musescore.org/en/node/73876.

For standard staves, cursor navigation works nicely in the presence of grace notes.  If the current note has grace notes and you hit "left" the rectangular input cursor remains fixed on the main note while the selection moves through the grace notes, and when the grace notes are done being traversed the rectangular input cursor (as well as the selection) moves to the previous "real" note.  Grace notes after are handled similarly.

But while this works well for standard standard staves, it fails for tab staves because this bit of code is forcing the selection to remain on the main note.  At the point where ScoreView::moveCursor() is called, Score::move() has correctly selected a grace note if appropriate, but.that selection is being clobbered here.

So my change simply makes it so that if the current selection is a grace note, the code here will not overrule this and select a note in the main chord, making it possible to navigate the selection to grace notes as it is for standard staves.  And with a note of grace note chord selected, hitting up or down will select other notes of that grace note chord just as it does for regular chords.

**Comment by MarcSabatella** [comment]
As for additional members for InputState, I'm not oppsoed, but it isn't needed here.  The InputState only records the rectangular input cursor, and that never is on a grace note.  Only the *selection* reaches grace notes.

**Pull request merged**
