### PR TITLE
fix #100406

### PR DESCRIPTION
**Pull request by abhinavaggarwal**
https://musescore.org/en/node/100406

### CODE REVIEW

**Comment by lasconic** [comment]
See https://musescore.org/fr/node/100406#comment-451326

**Comment by abhinavaggarwal** [comment]
Updated the filterShortcut to behave similar to Instument dialog.

**Comment by lasconic** [comment]
It's better to add some text in your commit message. Something like 
```
fix #XXXXX: Title of the issue.
```

This way it's easier to see what the commit is about without the visiting the issue tracker.

**Comment by lasconic** [comment]
Thank you! and welcome in the contributor community !

**Comment by abhinavaggarwal** [comment]
Sure, will take care next time .
Pleasure to be a MuseScore Contributor :)

**Pull request merged**
