### PR TITLE
[MU4] Fixed closing unfocused popups and when the user clicks on the title bar for Windows and macOS

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #11619
and https://github.com/musescore/MuseScore/issues/11548#issuecomment-1125189603

### CODE REVIEW

**Comment by DmitryArefiev** [comment]
Tested #11619 on Win10, Mac12, LinuxMint 20.2 - **FIXED**

**Comment by DmitryArefiev** [comment]
@jessjwilliamson Can you check please https://github.com/musescore/MuseScore/issues/11548#issuecomment-1125189603 on your 4K monitor please? :)

**Comment by jessjwilliamson** [comment]
> #11548 (comment)

I'm away from my 4k monitor right now so I will have to check back on Friday! :)

**Comment by DmitryArefiev** [comment]
> > #11548 (comment)
> 
> I'm away from my 4k monitor right now so I will have to check back on Friday! :)

Cool! The fix will be in the master then. Thanks! :)

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
