### PR TITLE
Remove music xml dom parser

### PR DESCRIPTION
**Pull request by lvinken**

### CODE REVIEW

**Comment by lvinken** [comment]
I feel the MusicXML pull parser has had sufficient test coverage to safely remove the DOM parser.

This PR removes the code that was used only by the DOM parser, but still leaves some code used by the pull parser in files formerly used by the DOM parser (to be moved to different files, that will be done later).

**Comment by lasconic** [comment]
Sorry for the delay. Could you squash the 3 commits together and comment when it's done? http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
Thank you !

**Comment by lvinken** [comment]
Will do, but probably no sooner than sometime next week.

**Comment by lvinken** [comment]
Done (squashed and pushed -f). Hope it is OK.

**Pull request merged**
