### PR TITLE
Fix #300124: Add default shortcut for synthesizer as Shift+F12

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
resolves https://musescore.org/en/node/300124

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
F7 surely is free on Windows, not sure about Mac though?

**Comment by Spire42** [comment]
I like the idea of adding a default keyboard shortcut for the Synthesizer dialog, but function keys are such a scarce resource that I can't help but wonder if this dialog would be the best use for <kbd>F7</kbd>.

Perhaps it would be better to use <kbd>F7</kbd> for, say, the Navigator? The Navigator seems like a good candidate because unlike the Synthesizer dialog, it's a panel just like all of the other items that currently have function keys assigned to them.

Another possible candidate is the Score Comparison Tool, although I suspect that it's not used nearly as often as the Navigator.

Yet another possible candidate is the Piano Keyboard. Although it already has <kbd>P</kbd> assigned to it, it's the only panel that's assigned a non-function key, so it sticks out like a sore thumb.

It would be instructive to look at the telemetry data to see which of the items on the *View* menu that don't yet have a keyboard shortcut is the most frequently used.

**Comment by MarcSabatella** [comment]
Navigator is, to me, all but obsolete, and I don't see the need to reserve a shortcut for it.  I suppose the small percentage of people who use it, probably use it a lot, but they can define their own shortcut.

Note though that we will probably be needing to shuffle the shortcuts some because F6 is really supposed to be reserved for accessibility (see #5920, which for now is moving Selection Filter to F7).

Anyhow, I do agree Synthesizer should get a default shortcut if possible, and I would be OK with seeing Timeline lose its shortcut in the process.  So, F6 for accessibility, F7 for selection filter, F12 for synth is one possibility.  I like keeping the playback-related shortcuts together, mixer/play panel/synth as F10/F11/F12.

**Comment by Jojo-Schmitz** [comment]
Ok, let's go for F12 then

**Comment by Marr11317** [comment]
> Navigator is, to me, all but obsolete

@MarcSabatella Why do you think that the navigator is now obsolete? I recently haven't used it often, but I haven't been working on any large score either. Is there a better approach to navigate through the score? And why wasn't it obsolete at one point?

**Comment by MarcSabatella** [comment]
The usual way to navigate through scores is the scroll wheel, no additional aids are normally needed at all.  And ever since the Timeline was added, it has mostly replaced whatever use cases formerly might have led one to use the Navigator, which is why it took over the F12 shortcut that was once used for the Navigator.

**Comment by Marr11317** [comment]
The timeline may be attractive to experienced users, but is way less user-friendly and self-explanatory. 
I would definitely not get rid of the navigator in for the timeline. The I actually find the timeline too cluttered too be of any use in complex/large scores. And that is exactly when navigation becomes important.
However, I must admit that I did not use the timeline enough to get familiar with it.

**Comment by Jojo-Schmitz** [comment]
I'm still using the navigator too.

**Comment by Jojo-Schmitz** [comment]
> Note though that we will probably be needing to shuffle the function key shortcuts some because F6 is really supposed to be reserved for accessibility (see #5920, which for now is moving Selection Filter to F7).
> 
> Anyhow, I do agree Synthesizer should get a default shortcut if possible, and I would be OK with seeing Timeline lose its shortcut in the process. So, F6 for accessibility, F7 for selection filter, F12 for synth is one possibility. I like keeping the playback-related shortcuts together, mixer/play panel/synth as F10/F11/F12.

F12 seemed a good idea, but is "Toggle Timeline" already, so not an option, not without loosing the current setting

**Comment by MarcSabatella** [comment]
No one is suggesting getting rid of the timeline  just not wasting a default shortcut on it.  As I said, for the vast majority of scores, you don't need *anything* on screen to navigate your scores - scroll wheel works perfectly already.  So for most users most of the time, no shortcut is needed at all, which is why I'd prefer to see F12 made available for something more valuable if there is another window that needs a shortcut, and synthesizer does seem the most natural choice.

As for the timeline, I agree it can look overwhelming at first, but I think if you do give it a shot, you'll find it much more valuable than the navigator.  Again, in the vast majority of cases you don't need either - scroll wheel is great, plus shortcuts like PgUp/Down, Ctrl+Home/End, Ctrl+F, etc.

But in those few cases where a core is sufficiently long and complex where you might need more, the timeline provides a ton of really useful functionality to help you find your way around according to rehearsal marks, tempo change, key changes, instrument entrance etc.  I definitely recommend spending some time with it to get more comfortable with it.  But then, probably keeping it closed most of the time because it normally isn't needed.

**Comment by Jojo-Schmitz** [comment]
Nobody suggested to get rid of timeline.
OK, so 'steel' F12 from timeline and use for synthesizer?

**Comment by MarcSabatella** [comment]
FWIW, I was responding to the statement "I would definitely not get rid of the navigator in for the timeline" and simply pointing out that indeed no one has suggested this.

So yes, to the extent we want a shortcut for synthesizer, stealing from timeline seems good to me.  I guess Shift+F10 or the like would have been a possibility too.  But I know function keys are problematic on some systems 0 might be non-existed, might be reserved by the system, etc. - and combinations with modifiers possibly even more so.

**Comment by anatoly-os** [comment]
Won't be really user-friendly for the ones who get used to showing/hiding Timeline using F12. Why not something like Ctrl+F10 since Synth is almost like Mixer :)

FYI, F11 doesn't work on maOS at all. This is a system shortcut that hides all opened windows...

**Comment by Jojo-Schmitz** [comment]
OK, done

**Comment by MarcSabatella** [comment]
I don't have good insight into which key combinations are available on which systems.  I've used plenty that have no function keys at all, or stop at F10, and I know some Linux installations reserve some things too.

But, regarding the fact that taking the F12 shortcut from timeline might surprise users - sure, but it's a small number of users who rely on this, and they can easily customize if they like.  Compared to other changes we've made lately and are proposing - the "new" palettes, the change to accidental input, etc - it's nowhere near as big a deal.  I doubt we'll get 1/100th as many complaints.

**Comment by Spire42** [comment]
On the subject of accessibility, one thing that no one has mentioned yet is that both <kbd>F10</kbd> and <kbd>Shift</kbd>+<kbd>F10</kbd> are reserved system shortcuts under Windows: the former activates the application menu and the latter opens the context menu for the item with the input focus. (And MuseScore currently hijacks <kbd>F10</kbd>.)

If we're ruling out system-reserved shortcuts, in addition the above we've got <kbd>F11</kbd> and <kbd>F12</kbd> on the Mac (as @anatoly-os has mentioned).

I strongly suggest that we take this opportunity to rethink *all* of the default function-key shortcuts rather than just commit to a single new one here. I think a forum thread would be a good open place to do so.

**Comment by anatoly-os** [comment]
Ok, I agree with @Spire42 and suggest revising the shortcuts later.

**Pull request closed without merging**
