### PR TITLE
Fix the width of the columns on the Choose Instruments Page (NSW) + other issues

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #8497 
Schermafbeelding 2021-09-17 om 00 48 38

Resolves: #9139 
Schermafbeelding 2021-09-17 om 00 43 38

And introduces some code quality improvements.

**To do:** 
- The icons to select the note head type are somewhat small (@Tantacrul?);
- Selecting the pitches for the ambits is very buggy.

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Tantacrul** [comment]
About those noteheads: I agree they're a hair small looking (both here and elsewhere). I'm not 100% sure how they are drawn. Could we bump them all up by around 20%? May take a little trial and error, since some are way bigger than others. To really get it right, we'd need to specify slightly different sizes for different noteheads.
image


Also, I notice that you never see scrollbars in those notehead options, so you can't tell that there are more noteheads out of view! That's another important one.

**Comment by jessjwilliamson** [comment]
> About those noteheads: I agree they're a hair small looking (both here and elsewhere). I'm not 100% sure how they are drawn. Could we bump them all up by around 20%? May take a little trial and error, since some are way bigger than others. To really get it right, we'd need to specify slightly different sizes for different noteheads.
> image
> 
> Also, I notice that you never see scrollbars in those notehead options, so you can't tell that there are more noteheads out of view! That's another important one.

I'm seeing these icons look quite blurry.. are they imported SVGs or from font? Would like to investigate to make them look sharper :)

**Comment by jessjwilliamson** [comment]
> Regarding the scrollbars: I just added them in this PR :)
> However, like all scrollbars in the app, they only become visible when the user already scrolls, or hovers the area where the scrollbar would be.
> 
> Regarding the notepad groups icons: they are indeed SVGs. For some reason, QML won't render them beautifully. We could try to use them directly from the music font (Leland).
> And I think the size of the note head _group_ icons is okay, but the note head _type_ icons are too small. Those are from the MusescoreIcon font.
> Schermafbeelding 2021-09-17 om 13 08 18

I think they were not blurry in the past.. this issue is also on Beam types. Do you think because they're SVGs the render is causing this way?

**Comment by Tantacrul** [comment]
Ah. Regarding the notehead types, they should be set to 24pt (assuming they're 16pt now?)

**Comment by Tantacrul** [comment]
And, yes, we should replace the SVG noteheads. I'll have to port them from Leland. It'll take a bit of time. Perhaps a job for @jessjwilliamson :)

**Comment by jessjwilliamson** [comment]
> And, yes, we should replace the SVG noteheads. I'll have to port them from Leland. It'll take a bit of time. Perhaps a job for @jessjwilliamson :)

Sure thing!

**Comment by vshalkevich** [comment]
This PR works fine for me

**Pull request merged**
