### PR TITLE
Correct accidentals for cross-staff notes

### PR DESCRIPTION
**Pull request by XiaoMigros**
Resolves: #21061

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Not sure that vtest diff is intended?
cross-8-1 diff
Whereas this probably is
narrow-spacing-2-1 diff

**Comment by XiaoMigros** [comment]
What makes you think it's not intended?

**Comment by Jojo-Schmitz** [comment]
Hard to tell what note the # applies to and what the natural?
Easy fix for the vtest: change the pitch so both are the same?
Doesn't fix my concern though?

**Comment by XiaoMigros** [comment]
But it's equally as hard to tell when the notes are in the same staff. It's the same behavior here as there

**Comment by Jojo-Schmitz** [comment]
OK, I rest my case then ;-)

**Review by oktophonie — APPROVED** [review]

**Review by mike-spa — APPROVED** [review]

**Review by cbjeukendrup — APPROVED** [review]

**Pull request merged**
