### PR TITLE
Fix #13411. Changed "Capo line" to "Barre line"

### LINKED ISSUE #13411: [MU4 Issue] "Capo line" should be "Barre line" (Guitar palette)
**Describe the issue**

In the "Guitar" palette, the "Capo line" symbol needs to be renamed to "Barre line".

### PR DESCRIPTION
**Pull request by mooredylan**
Resolves: [*(direct link to the issue)*](https://github.com/musescore/MuseScore/issues/13411)

Updated the name of "Capo line" to "Barre line" in response to issue #13411. This is my very first contribution to an open source project, and I have used Musescore much in the past. I found this to be a good starting point, even if this change is not approved :)

- [X ] I signed [CLA](https://musescore.org/en/cla)
- [X ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [X ] I made sure the code compiles on my machine
- [X ] I made sure there are no unnecessary changes in the code
- [X ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ X] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ X] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [X ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Hello! Thanks for this fix!
As discussed [here](https://github.com/musescore/MuseScore/issues/13411#issuecomment-1259144585), it should be `barré`, with accent, instead of `barre` (sorry, our fault). Could you please amend the pull request? (please let us know if you need help with that 🙂)

**Comment by cbjeukendrup** [comment]
Hi @mooredylan! Are you still around to amend this pull request as suggested above? Otherwise, I will close it so that another contributor can work on it.

**Comment by Jojo-Schmitz** [comment]
This can now get closed I guess

**Comment by cbjeukendrup** [comment]
@mooredylan Another contributor took this on, so I will close this PR. Thanks for your contribution anyway, and you're welcome to contribute again in the future!

**Pull request closed without merging**
