### PR TITLE
Assigning MIDI port/channel to instruments [ready to merge]

### PR DESCRIPTION
**Pull request by Igevorse**
Here's a feature that allows to assign any MIDI port/channel to an instrument in Mixer.
It was proposed many times starting from [2011](https://musescore.org/en/node/10601) or even earlier.
This is a part of my work in Google Summer of Code 2015.
#### New opportunities unlocked:
* Assign each instrument to a different MIDI port and connect MuseScore to external synthesizers, effects processor and VST instruments via JACK with minimum additional software (JACK + MuseScore + QJackCtl/any patchbay).
Example of assigning different MIDI ports to instruments
* Export MIDI mapping to MusicXML and MIDI files to make futher editing/processing simpler.
* Better control of MuseScore output for research/related projects (MuseScoreSSMN, etc).
* *Your use case here*

#### Changes in file format:
Tags **midiPort** and **midiChannel** are written if necessary.
#### Changes in UI:
* MIDI port and channel spin boxes in Mixer 
* "Show Midi controls in Mixer" checkbox in Preferences->Score

#### Backward compatibility:
Yes
#### Import MIDI mapping:
MusicXML, Guitar Pro files
#### Export MIDI mapping:
MusicXML, MIDI files

Animation of MIDI port/channel synchronization

Welcome for testing!

### CODE REVIEW

**Comment by ycollet** [comment]
I vote for this one. I already use this kind of thing with tuxguitar to simulate a multitrack recording.

**Comment by mgavioli** [comment]
I run a first, rather simple, test and, as far as I can tell, it works correctly for my (simple!) purposes, mainly for driving GrandOrgue.

Then, so far so good! Thank you!

(Do I remember correctly that once upon a time there was the project to enable staff text to send arbitrary MIDI events? Is this still in agenda? Thanks)

**Comment by Igevorse** [comment]
@mgavioli Thanks for the testing!
I will start to work on ["MIDI Actions"](http://igevorse.lited.net/p22.html) in a few days.

**Comment by mgavioli** [comment]
@Igevorse : Great news! Thanks.

**Comment by daeavelwyn** [comment]
I woks perfectly on my kxstudio 14.04. Really, really thanks igevorse !

**Comment by daeavelwyn** [comment]
Hi guys, i'm working with this branch for about 3 months and I have notice no issue so I just wonder when it could be merge to the master branch ?

**Comment by Igevorse** [comment]
@lasconic @daeavelwyn has been using this branch for 3 months and it works well.
I haven't added more commits, bugfixes or improvements since they were not needed. 
Thus, I think now this branch is ready for the merge.

**Comment by daeavelwyn** [comment]
@Igevorse glad to read this :)

**Comment by ao2** [comment]
Hi, I see this pull request as "merged" but I don't see the port and channel boxes in the mixer in MuseScoreNightly.

**Comment by ao2** [comment]
OK, sorry for the noise, I had to enable them in the preferences.

**Comment by laconbass** [comment]
I'm trying to enable this option, I've searched for it Preferences -> Score as suggested by @ao2 . What version should I have to be able to use it? I have 2.0.3 (3c7a69d) currently installed, may I need a higher rev? Thanks in advance!

**Comment by daeavelwyn** [comment]
@laconbass it seems to me this option is available from version 2.1 and higher. You can actually use it in the nightly builds (but those builds are really unstable) as shown in the screenshot below.

Tips: to see midi options, you have to click on the "+" button near the M button

musescore-3 0-unstable-nightly

**Comment by laconbass** [comment]
Ok, I will build from source and check it. Thanks!

**Comment by Linwood-F** [comment]
Did this get pulled from 2.1?   I just built 2.1 from source today, and it doesn't show up there.  The mixer is there, but no midi stuff (and no "+" to check).  I looked in the 3.0 nightly and do see it there, but not 2.1.

Does that mean in 2.1 there is no way to select midi channel for output?

**Comment by lasconic** [comment]
I believe it's too big of a change to be in 2.1. It would make file incompatible with 2.0.X

**Comment by daeavelwyn** [comment]
If you really need this functionality, you can try to use the developpment
version (it will be musescore 3). Not fully stable but really usable.
Nightly build are there : https://musescore.org/en/node/2653

**Comment by lasconic** [comment]
Using nightly builds based on master, there is no chance that the mscz files you are created will open in MuseScore 3. Do keep that in mind.

**Comment by Linwood-F** [comment]
Thanks @lasconic , the comments above indicated it was there, so was confused, probably was merged them pulled.  @daeavelwyn I've run 3.0 a bit, and it is just not that usable yet.  Since I wrote the midi player I am using, I will just adjust it to hard code some changes based on tracks.  The problem is that the vocal line on a 3 staff piano piece is coming out as channel 1, with the grand staff 2, and the Pianodisc player I am sending to has only channel 1 so only the vocal line plays.  But I can fix outside.

**Comment by ao2** [comment]
Hi, maybe people here can also comment about this related feature request:
https://musescore.org/en/node/138681

**Comment by anatoly-os** [comment]
Hi @virtualdxs, did you try the latest nightly? It is definitely more usable than year ago :)

**Comment by virtualdxs** [comment]
I have not. My main worry is about the file format - I want to guarantee that my music is usable by mscore 3. Has the format been finalized? If not, can I force it to save in mscore 2 format as well as the format it uses (as two different operations)?

**Comment by anatoly-os** [comment]
Im afraid the answer is No to both your questions. File format is not finalized due to upcoming project of GSoC student. 3.0 cannot save file in 2.x format.

**Comment by MarcSabatella** [comment]
I would like to point out there are two different sense of the word
"usable" here.  It might be "usable" in the sense that you can actually try
it out and produce scores with it and not have it crash every two minutes.
But it's not "usable" in the sense of actually being supported for
real-world production usage.

**Pull request merged**
