### PR TITLE
[MU3] Fix #309192: Add advanced preference to remove letters from piano keyboard

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
plus a minor cleanup.

Resolves https://musescore.org/en/node/309192

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I'm pretty sure the mtest failure is not my (PR's) fault, got to be the one just before mine (from PR #6776), @vpereverzev ?

**Review by vpereverzev — APPROVED** [review]

**Comment by vpereverzev** [comment]
looking for rebase

**Comment by Jojo-Schmitz** [comment]
Oh, darn, again...

**Comment by Jojo-Schmitz** [comment]
Ported to master in #6890

**Pull request merged**
