### PR TITLE
update translations for 2.3 Release Candidate

### PR DESCRIPTION
**Pull request by anatoly-os**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Way too early, give the translators a chance to translate the ~58 new strings

**Comment by anatoly-os** [comment]
I think incomplete translations are not critical for Release Candidate, I will update strings again once we are ready with MuseScore 2.2.9 packages.

**Comment by Jojo-Schmitz** [comment]
In this case this entire PR is not critical, and IMHO not needed at all, for an RC the existing translations should be sufficient, and can get updated via the resource manager

**Comment by anatoly-os** [comment]
Let 2.3 RC users have all the translations from 2.2 and completed German translations for 2.3 ;)

**Comment by Jojo-Schmitz** [comment]
Not with this PR, when you pulled them the German translation was not complete ;-)

**Comment by Jojo-Schmitz** [comment]
Guess this one is not needed any longer?

**Comment by anatoly-os** [comment]
Truth.

**Pull request closed without merging**
