### PR TITLE
add Jazzy and JazzyText fonts

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
on behalf of @Gootector, see
http://musescore.org/en/node/25027#comment-213346 and
https://musescore.org/en/node/89521

### CODE REVIEW

**Comment by lasconic** [comment]
I would not merge this now... Let's wait for 2.1

**Comment by Jojo-Schmitz** [comment]
OK by me.
Why are those mtest failures?
Guess we'd need more vtests for that font too.

**Comment by Gootector** [comment]
Yeah. Let's wait for 2.1. Font is still in development. It's too late for a new font at this moment :p :D.

**Comment by Jojo-Schmitz** [comment]
rebased, updated, added vtests

**Comment by Jojo-Schmitz** [comment]
Still don't understand why those mtests fail

**Comment by Jojo-Schmitz** [comment]
rebased once again, still awaiting the updated font(s) though

**Comment by Jojo-Schmitz** [comment]
Maybe a JazzyText won't be needed, as we have MuseJazz?

**Comment by Gootector** [comment]
As I write on the Technical Preview forum: Jazzy musical symbols + MuzeJazz text symbols.

**Comment by Jojo-Schmitz** [comment]
PR rebased and updated with @Gootector's lastest version from https://onedrive.live.com/?authkey=%21AOGp13CPKiC408k&id=2CA050E53852F58F%213417&cid=2CA050E53852F58F

**Comment by Jojo-Schmitz** [comment]
PR rebates, updated with @Gootector's latest fonts and added vtests for JazzyText

**Comment by Gootector** [comment]
Take it easy. I try to find the time in April to finish my project in 100%. Greetings!

**Comment by Jojo-Schmitz** [comment]
@Gootector: there's no need nore use anymore for classes.json, glypnames.jason and ranges.json, only metadata.json is needed, the rest is taken straight from SMuFL

**Comment by Jojo-Schmitz** [comment]
Will most probably conflict with #2853, but shouldn't be too difficult to resolve.

**Comment by Jojo-Schmitz** [comment]
Is this PR still needed or wanted, now that we have a fully fledged MuseJazz since #2853 got merged?

**Comment by lasconic** [comment]
Not sure what Gootector plan is with that. But it seems MuseJazz has some support and people like it. See https://musescore.org/en/node/137146 Let's see if we get any update.

**Pull request closed without merging**
