### PR TITLE
Mxml refactoring

### PR DESCRIPTION
**Pull request by lvinken**
Major refactoring and cleanup of MusicXML import/export. Was long overdue, many functions were way to big. Still more work to do, but that won't happen on short notice.

No functional changes at all, but should be a significant improvement wrt maintainability.

Would be nice to have this in 2.2 too, but I don't know how difficult the merge will be.

### CODE REVIEW

**Comment by lasconic** [comment]
I guess the commit history is not really useful right ? Could you squash the commits http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html and write a single meaningful commit message. I could do it, but not sure I can come up with a meaningful message :)

Regarding 2.2, I quickly tried... and it's a mess to merge...

**Comment by lvinken** [comment]
Will squash. Commit message will probably be a simple summary of the original commit messages. May put this in a new PR (to keep the old one for reference).

Wrt 2.2, I'm not surprised it is a mess to merge. It is probably easier for me to simply make the equivalent changes in 2.2. This would simplify porting changes from 3.0 to 2.x. Would you like me to do this and submit one or more PRs against 2.2 ?

**Comment by lasconic** [comment]
Sure. It would make it easier to merge new feature or bug fixes in the future. Thanks!

**Comment by lvinken** [comment]
Squashed and rebased (in a separate branch), am building and testing now. Will push as soon as tested OK, expect without half an hour.

**Comment by lvinken** [comment]
Done, see PR #3465. Will close this one.

Note that manually creating the 2.2 equivalent takes "some" :-) time, don't know how long this will take.

**Pull request closed without merging**
