### PR TITLE
Changes to MSCX fileformat for better comparability (squashed)

### PR DESCRIPTION
**Pull request by dmitrio95**
This pull request is a version of #3760 with reduced number of commits and rebased to current master. The original pull request is left in its original state for GSoC evaluatuon.

This pull request contains also two minor edits compared to #3760:
- Remove `Element::ftick`. It was merged with `Element::afrac` already but one occurrence of this function was accidentally left in the code.
- Drop [this commit](https://github.com/musescore/MuseScore/pull/3760/commits/c3ab89e0316f61977b5a958fb8e9830fade2018a) as it doesn't make sense for this pull request.

I have squashed most of commits in the history and now it seems to include as separate commits only actual changes in the format, some auxiliary changes (mostly grouped together) and a little number of optional changes that could not be included to the first two groups. Still there are about 20 commits left, and if you consider this commit history necessary to be reduced further feel free to ask me to do so.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
one seemingly legit mtest failure, https://travis-ci.org/musescore/MuseScore/jobs/416662658#L5485

**Comment by shoogle** [comment]
Looks ready to merge.

**Comment by anatoly-os** [comment]
Ok, here we go!

**Comment by anatoly-os** [comment]
@dmitrio95 congratulations! Your valuable input is in MuseScore codebase now :) Could you please create new PR which removes read300 logic according to @wschweer's suggestion.

**Comment by dmitrio95** [comment]
@anatoly-os Thank you! I'll prepare a new PR removing `read300` functionality soon.

**Comment by anatoly-os** [comment]
@dmitrio95 some news on preparing new PR?

**Comment by dmitrio95** [comment]
@anatoly-os I am working on it. Some of `read300` functions are still needed for reading 1.x and 2.x scores, and I am trying to figure out which should be left (and moved to `read114.cpp` and `read206.cpp`) and which should be removed. This work is still in progress.

**Pull request merged**
