### PR TITLE
Catch exceptions by const-ref rather than by value

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
Not having to copy objects when throwing exceptions, possibly leading to memory leaks in some cases where it is mishandled (not implying it is the case here, just a general rule). It's also warned on with GCC's `-Wcatch-value`.

**Comment by Jojo-Schmitz** [comment]
May need to get reverted, if the [CLA](https://musescore.com/cla)doesn't get signed...

**Comment by janisozaur** [comment]
When I navigate to the linked page, I get "Page not found" error.

**Comment by Jojo-Schmitz** [comment]
try again now (typo: .org vs. .com)

**Comment by anatoly-os** [comment]
@janisozaur did you sign the cla?

**Comment by anatoly-os** [comment]
@janisozaur ?

**Comment by anatoly-os** [comment]
Reverted changes due to not signed CLA

**Comment by anatoly-os** [comment]
It is not possible to close merged PRs.

**Pull request merged**
