### PR TITLE
fix #111431 and fix #111311: some additions/corrections to instruments.xml

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
* Add single-staff marimba and contrabass marimba to instruments.xml
* Fix come incorrect pitched percussion instruments' default ranges in instruments.xml
* Fix Traverso short name (ommision from 10bca19f)
* Add channels to Harp for staccato and flageoletti, see #18779 and https://musescore.org/de/node/110481#comment-499521 ff.
* Fix apparent typos for octave-mandolin and contrabasses

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@duck57: sorry for the collision, I took your remark in the issue tracker to mean I should have a go at this. As you may see, I took the opportunity to make some more changes I had piled up on my PC.

**Comment by lasconic** [comment]
as we change some ids, it will not go into 2.0.4

**Comment by Jojo-Schmitz** [comment]
Want one with unchanged IDs?

**Comment by Jojo-Schmitz** [comment]
Want one with unchanged IDs? It is just 2 of the them, octave-mandolin vs. OctaveMandolin and contrabasses vs. contrabasss

**Comment by Jojo-Schmitz** [comment]
See #2616

**Pull request merged**
