### PR TITLE
#16011 Step 1 Submission

### PR DESCRIPTION
**Pull request by daijingz**
#16011 Two sections' cursor shapes have been updated. (PanelTab and TitleBar)
The toolbar is not working, and I aborted this program's changes before.
Now you can see my change.
The toolbar cursor shape is working! Thanks for everyone's help!

### CODE REVIEW

**Review by cbjeukendrup — APPROVED** [review]
Thanks!

**Comment by cbjeukendrup** [comment]
Note: CLA still needs to be signed (@daijingz Please comment when ready)

**Comment by daijingz** [comment]
Already signed, you can find my account david11470629... at the end of the name list

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved

**Pull request merged**
