### PR TITLE
Fix #19470: remove “show navigator” option from general preferences

### LINKED ISSUE #19470: Remove 'Show navigator' in Preferences
### Issue type

Other type of issue

### Bug description

Remove 'Show Navigator' check box in General > Programme Start > Preferences.
This option has proven to be pointless and would be easily produced by using the View option to create the same action.

### Steps to reproduce

1. Preferences
2. General
3. Programme Start
4. See checkbox

### Screenshots/Screen recordings

Screenshot 2023-09-21 at 11 26 41

### MuseScore Version

Latest master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mmeyn**
Some code that looks like it becomes unused now is removed too.

Resolves: #19470

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ ] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

Concerning unnecessary changes: Is removing unused code necessary?

### CODE REVIEW

**Comment by mmeyn** [comment]
I just realised there might be some more unused code (f. e. the PanelList type and other things called …Panel…).

**Comment by cbjeukendrup** [comment]
@mmeyn Yes, it would be great if you could remove those few types from `generalpreferencesmodel.h`!

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/19470 FIXED

**Comment by jessjwilliamson** [comment]
Thank you @mmeyn! Perfect :)

**Comment by shoogle** [comment]
@mmeyn, this commit for this PR hasn't been linked to your GitHub account. If you would like it to be linked, please go to your [GitHub Settings > Emails](https://github.com/settings/emails) and add your `m***@m*******n.de` email address there. Doing this will make GitHub will recongnise you as the author of this commit. It will also enable me to credit you properly in the release notes for the next release.

**Comment by shoogle** [comment]
@mmeyn, the commits for your [PRs](https://github.com/MuseScore/MuseScore/pulls?q=author%253Ammeyn) aren't linked to your GitHub account. If they were linked, we would see the commits listed at https://github.com/musescore/MuseScore/commits/master/?author=mmeyn like mine are [here](https://github.com/musescore/MuseScore/commits/master/?author=shoogle).

This likely happened because you're using a different email address for `git config user.email` to the one you use for GitHub.

If you would like to link the commits to your account, all you need to do is:

1. Go to your  [__GitHub Settings > Emails__](https://github.com/settings/emails).
2. Locate the **Add another email** box.
3. Add the `m***@m*******n.de` email address you used to create these commits.

Doing this will enable us to credit you properly in the release notes for the next release. Thanks!

**Comment by mmeyn** [comment]
Thank you for the hint. I had the “wrong” mail address in my .gitconfig for a while. I now added it as a secondary mail address to my github account.

**Pull request merged**
