### PR TITLE
Fix #11527: Tweaks to palette layout properties

### LINKED ISSUE #11527: [MU4 Task] Further minor tweaks to palette layout properties
**Task description**
This describes a few minor tweaks to the following palettes: 

### Beam properties
Default palette properties should be: 
Width = 35
Height = 33
Element offset = 0sp
Scale = 1.4
Show grid = ON

Screenshot 2022-05-05 at 3 23 56 pm

### Key signatures
Make default height = 47

### Clefs
Make default height = 55 

### Bagpipe embellishments
Set show grid = ON

### Time signatures
Set show grid = ON 

@HemantAntony another minor one if you're interested 😀

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #11527 

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by bkunda** [comment]
@HemantAntony Almost everything looks right, though I'm not sure why the beam properties is still showing an incorrect scaling: 

Screenshot 2022-05-06 at 5 34 03 pm

This was after I had reset the palette itself, reset preferences, and deleted the workspace file.

**Comment by HemantAntony** [comment]
@bkunda, I changed it to look like the expected behaviour photograph in the issue. I can change it to 1.4 if you want me to

**Comment by HemantAntony** [comment]
@bkunda I have updated the PR once more

**Comment by bkunda** [comment]
This is now correct. Thanks so much @HemantAntony!
@vpereverzev ready for your team's review

**Pull request merged**
