### PR TITLE
more pre-translation text fixes

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Work In Progress, let me check and probably add more

**Comment by anatoly-os** [comment]
@Jojo-Schmitz could you please rebase the PR?

**Comment by Jojo-Schmitz** [comment]
Will do, after #4167 is in (as that will create more conflicts)

**Comment by Jojo-Schmitz** [comment]
rebased, and added some more. Still not all strings revivewd, but the majority is, so ready for merge any time, even if more texts may follow, which will happen anyhow

**Pull request merged**
