### PR TITLE
fix withoutqt-test

### PR DESCRIPTION
**Pull request by lyrra**
- [x] I signed the [CLA](https://musescore.org/en/cla)

- musescore ci was running ubuntu 20.04
- github ubuntu-latest points to ubuntu version 22.04
- around august github will push ubuntu-latest to 24.04

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
See also my fix in https://github.com/musescore/MuseScore/pull/22701/commits/6909b31c7d40618750ecd870c5f074a7fb167848

**Comment by lyrra** [comment]
> See also my fix in [6909b31](https://github.com/musescore/MuseScore/commit/6909b31c7d40618750ecd870c5f074a7fb167848)

Yeah but you're downgrading gcc

**Comment by lyrra** [comment]
> > See also my fix in [6909b31](https://github.com/musescore/MuseScore/commit/6909b31c7d40618750ecd870c5f074a7fb167848)
> 
> Yeah but you're downgrading gcc

(if you just change to ubuntu-latest, you can keep gcc at version 11)

**Comment by Jojo-Schmitz** [comment]
yes, to the same version the real build uses

**Comment by Jojo-Schmitz** [comment]
And without further CI failurs ;-)

**Comment by Eism** [comment]
> yes, to the same version the real build uses
@Jojo-Schmitz Good point. 
Could you please create the PR?

**Comment by Jojo-Schmitz** [comment]
It is in #22701

**Comment by Jojo-Schmitz** [comment]
I'm not a big fan of `-latest`, as it tends to change under your feet when you least expect it.

**Comment by lyrra** [comment]
> I'm not a big fan of `-latest`, as it tends to change under your feet when you expect it least.

That's kind of the point, you get a early headsup when a breaking change has occured.

**Comment by lyrra** [comment]
> It is important that we compile on the very oldest version of Ubuntu that we can get, because if we compile on a new Ubuntu, MuseScore won't run on any older Ubuntu or other older Linux OSs.

I see, the app-image needs maximum portability. I'll close this PR.

**Pull request closed without merging**
