### PR TITLE
Add Flatpak manifest

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
This adds a manifest for creating a cross-distro Flatpak package (http://flatpak.org).

You can test this by installing flatpak and flatpak-builder and then running

flatpak remote-add kde-repo --from https://distribute.kde.org/kderuntime.flatpakrepo
flatpak install kde-repo org.kde.Platform
flatpak install kde-repo org.kde.Sdk
flatpak-builder --repo=musescore-repo musescore-build org.musescore.musescore.json
flatpak remote-add --no-gpg-verify musescore-repo
flatpak install test org.musescore.musescore
flatpak run org.musescore.musescore

With the following command you can create a .flatpak bundle (size: 24.8 MB):

flatpak build-bundle musescore-repo musescore.flatpak org.musescore.musescore

The .flatpak file (I uploaded one here: https://drive.google.com/open?id=0B1SoIjRsaQikYkotQnAzM24xeHc) can be installed by running

flatpak install --bundle musescore.flatpak

The AppData file is neccessary in order to showcase MuseScore in GNOME Software and KDE Discover. The mscore.AppData.xml.in file needs to be licensed under CC0 so distros can easily use it for creating repository indices.

### CODE REVIEW

**Comment by lasconic** [comment]
I have no idea how flatpack work but since you list the dependencies, what about 
* Qt? (provided by the kde repo?) Plugins are working?
* libsndfile, libogg, libvorbis

**Comment by Alexander-Wilms** [comment]
Here's an explanation how it works: http://docs.flatpak.org/en/latest/introduction.html#how-it-works

* Qt is provided by the KDE runtime (org.kde.Platform)
* Some Plugins do work, but not all of them yet
* I'll have to add libsndfile, libogg and libvorbis to the manifest

**Comment by Alexander-Wilms** [comment]
I added the libraries

I tested the plugins:
* ABC tunes: I was able to import

"X:20
T:Swallowtail Jig
C:Traditional
R:Jig
M:6/8
L:1/8
K:Amix
F|:"Em"GEE BEE|GEE BAG|"D"FDD ADD|dcd AGF|
"Em"GEE BEE|GEE B2c|"D"dcd AGF|1"Em"GEE E2F:|2GEE E3||
|:"Em"Bcd e2f|e2f edB|Bcd e2f|edB"D"d3|
"Em"Bcd e2f|e2f edc|"D"dcd AGF|"Em"GEE E3:|" , no errors reported in the terminal
* helloQML: window with text is displayed, but there are errors reported in the terminal: "qml: Hallo Welt                                                                                 
qml: Ms::MasterScore(0x54cbdf0)                                                                 
qml: undefined                                                                                  
file:///app/share/mscore-3.0/plugins/helloqml/helloqml.qml:22: Error: Unknown method return type: Ms::Measure*"
* random: nothing happens, the following error output appears: "file:///app/share/mscore-3.0/plugins/random.qml:31: TypeError: Cannot call method 'addText' of null"
* random2: nothing happens, no terminal output
* scorelist: a window with a grey background appears, the terminal shows the following errors: "qml: hello scorelist
file:///app/share/mscore-3.0/plugins/scorelist.qml:14: ReferenceError: scores is not defined
qml: hello scorelist
file:///app/share/mscore-3.0/plugins/scorelist.qml:14: ReferenceError: scores is not defined"
* panel: works
* createscore: nothing happens, output: "qml: hello createscore
file:///app/share/mscore-3.0/plugins/createscore.qml:16: TypeError: Cannot call method 'addText' of null"
* Walk: the following output is printed in the terminal: https://pastebin.com/Xp4ggH2x
* Color Notes: Nothing happens, output: "qml: hello colornotes
QMetaProperty::read: Unable to handle unregistered datatype 'Ms::Segment*' for property 'Ms::MasterScore::lastSegment'
file:///app/share/mscore-3.0/plugins/colornotes.qml:53: TypeError: Cannot read property 'tick' of undefined"
* Note Names: Nothing happens, the following output is printed: "QMetaProperty::read: Unable to handle unregistered datatype 'Ms::Segment*' for property 'Ms::MasterScore::lastSegment'
file:///app/share/mscore-3.0/plugins/notenames.qml:139: TypeError: Cannot read property 'tick' of undefined"

**Comment by Jojo-Schmitz** [comment]
Plugins don't really work in master, AKA 3.0. Try 2.0.3 or 2.1

**Comment by Alexander-Wilms** [comment]
The issue with the 2.0.3 and 2.1 branches is that tey use the deprecated QWebView from QtWebKit. Since the Sdk and runtime use Qt 5.7.1, I can't compile MuseScore.

**Comment by Jojo-Schmitz** [comment]
3.0 is pretty far from getting released (and uses Qt 5.8). And or 2.x you need Qt 5.4

**Comment by Alexander-Wilms** [comment]
Since Flatpak itself is still pretty new and the KDE Sdk and runtime are still experimental (https://community.kde.org/Guidelines_and_HOWTOs/Flatpak), there are no older runtimes.

**Comment by Jojo-Schmitz** [comment]
But surly you can install other Qt version addition? And add these to the dependencies?

**Comment by Alexander-Wilms** [comment]
That might be possible, one would need to copy all the Qt modules from https://cgit.kde.org/flatpak-kde-runtime.git/tree/org.kde.Sdk.json into the MuseScore manifest and change the Branch to 5.4. But I'm not sure if the build options need to be modified and how long it will take to compile.

**Comment by Jojo-Schmitz** [comment]
As mentioned earlier, plugins are severely broken in master. And meanwhile we do have a 2.x flatpack at https://flathub.org/repo/appstream/org.musescore.MuseScore.flatpakref

**Comment by Alexander-Wilms** [comment]
Maybe some of the dependencies have to be added to that package, but this pull request is no longer necessary.

**Pull request closed without merging**
