### PR TITLE
fix #286001: Change dynamicStyleFont to Italic

### PR DESCRIPTION
**Pull request by quarriedstone**

### CODE REVIEW

**Comment by quarriedstone** [comment]
Hello Mr. Schmitz,

Yes, i've done it after recieving your message.

Best regards,
Herman Tarasau

пн, 1 апр. 2019 г. в 22:35, Joachim Schmitz <notifications@github.com>:

**Comment by Jojo-Schmitz** [comment]
some mtests are failing on Travis CI, looks like those test scores need to get ammended

**Comment by quarriedstone** [comment]
There were excessive tags in reference files, so I deleted them maually. I believe the reason was that reference files were created with older versions of MuseScore.

**Comment by Jojo-Schmitz** [comment]
Yep. Now you just need to squash your 3 commits into just one (provided the tests pass now)

**Comment by Jojo-Schmitz** [comment]
nitpick: it is "italic", just one "l"

**Comment by anatoly-os** [comment]
Something is wrong with the authorship of the commit itself. @quarriedstone do you use the correct gitHub credentials in Git?

**Comment by quarriedstone** [comment]
Yeah, the name of commiter and my gitHub profile name are different, if I understood you right. If it makes triuble i can rebase commit and make ther author name as in my profile in git.

**Pull request merged**
