### PR TITLE
fix related to #93376: Added smooth scrolling controls and preferences for continuous view

### PR DESCRIPTION
**Pull request by SKefalidis**
Resolves: https://musescore.org/en/node/93376

Added the ability to smoothly pan in continuous view, during playback (gif with terrible framerate below, in reality, it's smooth :^). For that to happen, a second 'control-cursor' is used. The view follows this cursor. The speed of the control-cursor is influenced by the distance between it and the playback-cursor and by the time elapsed between each update (tied to the heartbeat, every 20ms as of right now). 

The variables used in the calculations have been added to the preferences. Some of them are hidden (and commented out, that way they can be easily enabled in the future), the rest is available in the advanced tab. If the users request more control over the behavior I have prepared a separate tab used to control all the variables (as shown in the images), but that has been removed from this PR.

ezgif com-crop

Alternative preferences, if that's required:
image
image

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Build errors

**Comment by SKefalidis** [comment]
> Build errors
Should be ok now, uploaded the wrong thing.

**Comment by Jojo-Schmitz** [comment]
rebase needed

**Comment by SKefalidis** [comment]
Rebase completed.

**Comment by SKefalidis** [comment]
Fixed formatting and replaced QTimer with QElapsedTimer.

**Comment by Ryzza5** [comment]
The continuous scrolling feature is very welcome and well implemented.  I think the following two points are missing, either as default behaviour or advanced settings:

1) Keep scrolling at the end of the song.  On a fast 130 BPM song, when the scrolling suddenly stops near the end of the song, it's surprisingly jarring, like jumping off a spinning ride and feeling a little dizzy.  I would prefer to see the entire staves keep scrolling off the screen.

2) Bar counter on the left - I would find this to be more useful it it showed the bar number where the floating cursor is, to reflect where I am, not where I was 2-3 bars ago.  To a lesser extent the same could be said about the key & time signature, but since these don't change as often it's less of a concern for me.

I hope the feedback is valuable.
Thanks :)

**Comment by SKefalidis** [comment]
@Ryzza5 I will look into all of the issues/suggestions. The feedback is very valuable :^)

side note: I believe that this should have been posted at https://musescore.org/en/project/issues/musescore

**Comment by ronaldocpontes** [comment]
That's a great feature and I've seen it has been merged.

However, I can't find a way to use Continous Playback. I have version 3.2.54... on Mac but I can't find a way to enable the feature nor I see the settings on the preferences screen. How can I enable Continous Playback?

image
image

**Comment by MarcSabatella** [comment]
See the Advanced tab of the preferenecs dialog.

For further questions on how to use MsueScore, please see the Support forum on musescore.org.

**Comment by ronaldocpontes** [comment]
Found it. Thanks @MarcSabatella 

image

**Pull request merged**
