### PR TITLE
Improve scroll gradient visibility in Add-ons -> Languages

### PR DESCRIPTION
**Pull request by PratikSonal**
Resolves: https://github.com/musescore/MuseScore/issues/7929

The scroll gradient in Add-ons, Languages page isn't obvious enough. While the issue required the gradient at the bottom to be prominent, the following modifications also improve gradient visibility at the top of the list.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by RobFog** [comment]
The merge commits shouldn't be there. I think @Jojo-Schmitz knows how to sort that out.

**Comment by Jojo-Schmitz** [comment]
`git pull --rebase musescore master` (if musescore is the name of your upstream repository, else adjust accordingly), then `git push -f`

**Comment by Jojo-Schmitz** [comment]
There's still 3 merge commits...

**Comment by Jojo-Schmitz** [comment]
Why closing it?

**Comment by PratikSonal** [comment]
@Jojo-Schmitz apologies, I made a mistake with my commit and messed up my repository. This is all still new to me. I ended up resetting my fork, and that in turn closed the request automatically. I'm assuming it's not possible to reopen it now (as the pull request no longer exist on my repository), so would it be okay if I made another pull request?

**Comment by Jojo-Schmitz** [comment]
sure

**Pull request closed without merging**
