### PR TITLE
fix a compiler warning

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
about control reaching end of non-void function

### CODE REVIEW

**Comment by Howard-C** [comment]
Oops...
But isn't making "T" the "default" case a better idea? That will save some time if the extension is written in "B".

**Comment by Jojo-Schmitz** [comment]
IMHO Bytes is a good default

**Comment by Jojo-Schmitz** [comment]
Actually this is used for Extensions only, Translations use KB, hard coded, but, in contrast to Extensions, this string is translatable. So there's another bug...

**Comment by Howard-C** [comment]
Do you think these should be translatable or not?

**Comment by Jojo-Schmitz** [comment]
I believe they should.

**Pull request merged**
