### PR TITLE
fix #103401: Allow editing identical ontime/len of multiple notes in piano roll view

### PR DESCRIPTION
**Pull request by LuiCat**
In piano roll view, when multiple notes with the same value of a property is selected, the value will be shown in the spinbox (except velocity) and can be edited (currently only ontime & len).

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
all These meare commits shouldn't be there. You'd need to rebase rather than merge, check https://musescore.org/en/developers-handbook/git-workflow

**Comment by Jojo-Schmitz** [comment]
all these meare commits shouldn't be there. You'd need to rebase rather than merge, check https://musescore.org/en/developers-handbook/git-workflow.
Neither should there be duplicate commits, guess you'd have to squash them.

Seems your change to mscore/CMakeLists.txt  breakes the build on Travis, I don't think it is needed at all, same for your changes to build/mingw32.mingw.cmake and build/mingw32.cmake

**Comment by Jojo-Schmitz** [comment]
Also it seems you'd need to sign the CLA, http://musescore.org/cla

**Comment by LuiCat** [comment]
my fault. commits updated & CLA signed.

**Comment by Jojo-Schmitz** [comment]
Ah, looks much better. Not sure whether the "Powers To Be* prefer a single commit though

**Comment by lasconic** [comment]
Please squash them all. http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by lasconic** [comment]
It would be good if you could explain in an issue on the issue tracker which problems you are solving in this PR. I have no idea what I need to test. https://musescore.org/en/project/issues/musescore

**Comment by LuiCat** [comment]
commits squashed
issue created: https://musescore.org/en/node/103401

**Comment by Jojo-Schmitz** [comment]
And if you now `git commit --amend` the commit message to mention `fix #103401: ...`, it'd get automagically closed once this PR gets merged

**Comment by LuiCat** [comment]
done. thanks for all your patience.

**Comment by dmitrio95** [comment]
Needs actualization for current master

**Pull request closed without merging**
