### PR TITLE
fix #201146 allow BUILD_LAME=FALSE

### PR DESCRIPTION
**Pull request by ericfont**
Build would fail if BUILD_LAME=FALSE, because MuseScore::canSaveMp3() and MuseScore::saveMp3() were defined in a file that is excluded from build when BUILD_LAME=FALSE, but since those functions are declared in musescore.h and are used by file uploader, they need to be defined.  I've moved those functions to musescore.cpp since they are part of the class MuseScore, and have made them return false when BUILD_LAME=FALSE.

### CODE REVIEW

**Comment by Qantas94Heavy** [comment]
Would there need to be further handling within `Ms::LoginManager::onGetMediaUrlRequestReady` of this case?

**Comment by ericfont** [comment]
I don't think so, because:

 if (mscore->saveMp3(score, path))

will not execute because will return false.

**Comment by Qantas94Heavy** [comment]
Ah, I've taken a further look and it won't even be run in the first place if MP3 export is not supported. Yeah, this looks fine to me.

**Comment by ericfont** [comment]
yeah, all I've done other than moving those functions to a different file is to make them return false if USE_LAME is not defined.  I suppose it would be the responsibility of whatever calls these functions to correctly handle if return false, and I believe I checked all callers are doing that properly.

**Comment by ngg** [comment]
Hi! I'm trying to build without lame as well, and the master branch still doesn't compile for me. In `musescore.cpp` the function `MuseScore::canSaveMp3()` tries to create an `MP3Exporter` which is in `exportmp3.h` but that's not included unless BUILD_LAME is set.

**Comment by ericfont** [comment]
@ngg, I'm just reading your message now.  Sorry I haven't looked into what you said.  Is this still a problem for you?

**Pull request merged**
