### PR TITLE
fix #100596

### PR DESCRIPTION
**Pull request by abhinavaggarwal**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Seems you're mixing several fixes into several PRs?

**Comment by Jojo-Schmitz** [comment]
Seems you're mixing several fixes into several PRs?
The 1st and 2nd commit are in #2419 already, the 1st is also in #2416

**Comment by abhinavaggarwal** [comment]
Yes, it sort of occured accidentally. Will take care in future PRs.

**Comment by Jojo-Schmitz** [comment]
You'd need to make sure to create a new branch off of master.
And I guess you'd have to redo this PR and #2419, to fix this issue and squash commits in #2416.

**Pull request closed without merging**
