### PR TITLE
Realize the basic functions of Jianpu

### PR DESCRIPTION
**Pull request by Auase**
Resolves: #NNNNN 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Auase** [comment]
jianpu
The characters added to Leland were copied from Edwin-Bold. I tried adding independent font files, but the amount of code that needed to be changed was too much, so I gave up the plan of adding font files.
f
e

**Comment by oktophonie** [comment]
This is amazing!

I don't think extending Leland is a great idea, though. However, if you don't want to create a separate font file, and only text characters are being used, is it not possible to use the text font directly? (Which may be Edwin by default, but could be configurable so users could choose whatever font they like)

**Comment by Auase** [comment]
@oktophonie 
I understand, I have tried, but I cannot solve the problem of program lag. Of course, this is just my personal technical issue, and if you can implement it, it would be the best.

**Comment by oktophonie** [comment]
Unfortunately we can't make changes to Leland in this PR; that would have to be done in the Leland repo separately, and I don't want to do that anyway since it ties Leland and Edwin together. So, as it is, we cannot merge this PR until it uses a text font directly, or possibly even a custom font especially for Jianpu.

**Comment by Auase** [comment]
This only provides a display method and does not involve audio (as Jianpu does not require audio and specific instruments). Elements that do not need to be written to the music file have been excluded as much as possible, so it will not affect the normal opening of music in other versions.

**Comment by Auase** [comment]
@oktophonie 
I am unable to implement it because I don't know how to make Jianpu change the default to use a different font file. Can you help me?

**Comment by Jojo-Schmitz** [comment]
why closing it?

**Comment by Auase** [comment]
@Jojo-Schmitz 
我修改后重新打开了一个请求：https://github.com/musescore/MuseScore/pull/19421

**Comment by Jojo-Schmitz** [comment]
Ah, I see

**Pull request closed without merging**
