### PR TITLE
[MU4] Separated iex ove module

### PR DESCRIPTION
**Pull request by igorkorsukov**
Separated iex ove module

### CODE REVIEW

**Comment by Howard-C** [comment]
`ove.cpp` and `ove.h` still have a lot of code style violations, such as member variable names (`variable_` instead of `m_variable` or `_variable`), a lot of unnecessary long `//////` comments, and no indentation for commented-out code. Do you have automatic tools to fix them?

**Comment by igorkorsukov** [comment]
> `ove.cpp`, `ove.h` and `importove.cpp` still have a lot of code style violations, such as member variable names (`variable_` instead of `m_variable` or `_variable`), a lot of unnecessary long `//////` comments, and no indentation for commented-out code. Do you have automatic tools to fix them?

unfortunately, not.
Perhaps you could fix this?

**Comment by Howard-C** [comment]
> > `ove.cpp`, `ove.h` and `importove.cpp` still have a lot of code style violations, such as member variable names (`variable_` instead of `m_variable` or `_variable`), a lot of unnecessary long `//////` comments, and no indentation for commented-out code. Do you have automatic tools to fix them?
> 
> unfortunately, not.
> Perhaps you could fix this?

I tried it once in #5680, I couldn't have been more bored :( The only reason I closed it was because I somehow messed with its functionality, and I couldn't for the life of me figure out where I did wrong (the changes are so many!!)

The long comments and indentation can be fixed without much thought, but I literally can't stand flipping the variable names all over again :)

**Comment by Howard-C** [comment]
But maybe I can write a C++ program to flip the names in C++ files :) And even commit it here to share it.

**Comment by Howard-C** [comment]
https://github.com/Howard-C/Variable-Name-Inverter/blob/main/main.cpp

**Pull request merged**
