### PR TITLE
fix #15526: [MU4 Issue] Part group barlines not respected in MusicXML…

### LINKED ISSUE #15526: [MU4 Issue] Part group barlines not respected in MusicXML import
**Describe the bug**
Barlines connecting part-groups are not respected in MusicXML import except for the first two parts, and even there they are not respected in the final barline.

**To Reproduce**
1. Create a default score containing three or more groups from the same instrument family (here I chose Fl. Ob. Cl. and Bassoon).
2. Notice that they are all part of the same part-group with barlines going across all parts (screenshot 1)
3. Export as MusicXML (here I've done uncompressed for ease of looking at the score).
4. Open the MusicXML file in MuseScore 4.0.0
5. See that the barlines only go through the first two parts, and that the final barlines are not connected in those two parts (screenshot 2).  The grouping brace, however, is imported properly.

**Expected behavior**
The barlines should look the same upon import as they were on export.

**Screenshots**
MCSZ file in MuseScore:
Screen Shot 2022-12-22 at 14 52 55

After export and reimport as MusicXML:
Screen Shot 2022-12-22 at 14 53 06

**Platform information**
 - OS: macOS 12.6
 - MuseScore 4.0.0 w/o MuseHub

**Additional context**
This problem first arose somewhere around MuseScore 3 -- sorry I'm only now getting around to posting it.

The `<part-list>` and `<part-group>` information in the musicxml produced by MuseScore 4 appears to be correct, and I can get the same results from musicxml produced by music21 and Finale.

The mcsz (4.0.0) and musicxml files from the screenshot are attached in the zip-file below.

(And thanks for supporting MusicXML v4.0 validation -- as the incoming Editor of the MusicXML spec, I appreciate this a lot!)

[empty_quartet.zip](https://github.com/musescore/MuseScore/files/10291268/empty_quartet.zip)

### PR DESCRIPTION
**Pull request by lvinken**
… import

Correctly set barline span for parts in a MusicXML part-group as requested by [Michael Cuthbert](https://github.com/mscuthbert)

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Doesn't this apply to Mu3 too?

**Comment by Jojo-Schmitz** [comment]
Seems to apply to Mu3 too, doesn't it? My attempts at a backport though fail a cople MusicXML mtests, @lvinken: mind to cast an eye?

**Comment by mscuthbert** [comment]
Thanks for the amazing work.  I really appreciate it!

**Comment by lvinken** [comment]
The failing test is Engraving_PartsTests.createPartSymbol. I could not find any relation between this test and MusicXML import.

**Comment by lvinken** [comment]
> Seems to apply to Mu3 too, doesn't it? My attempts at a backport though fail a cople MusicXML mtests, @lvinken: mind to cast an eye?

Hi Jojo, will have a look, may take a few days due to other obligations. Don't know if barline span handling is identical in MuseScore 3 and 4, I did not investigate MuseScore 3.

**Comment by Jojo-Schmitz** [comment]
> > Seems to apply to Mu3 too, doesn't it? My attempts at a backport though fail a cople MusicXML mtests, @lvinken: mind to cast an eye?
> 
> Hi Jojo, will have a look, may take a few days due to other obligations. Don't know if barline span handling is identical in MuseScore 3 and 4, I did not investigate MuseScore 3.

All the tests that fail in my port seem to not exist in Mu4, so maybe all that's needed it to adjust those tests?

**Comment by lvinken** [comment]
[@Jojo-Schmitz](https://github.com/Jojo-Schmitz) checked your back port: it is OK, you just have to regenerate the mscx reference files.

**Comment by Jojo-Schmitz** [comment]
Thanks! Do I need that `for` loop I mentioned above or not? Same tests fail in the same way with and without, apparently

**Comment by lvinken** [comment]
Hi Jojo, yes, the loop is required, it came from [PR8175](https://github.com/musescore/MuseScore/pull/8175/files). Without it, only the barline in the first staff of a multi-staff part is set correctly. Also, apparently something when wrong in the back port. In your branch, the loop is incorrect. This causes testBarlinesGrandStaff.xml to fail. See [proposed fix](https://github.com/lvinken/MuseScore/commit/997b88eb6ec5f4afe0e5220fa8d460fab72102c6). Will also check MuseScore 4.

**Comment by Jojo-Schmitz** [comment]
Thanks! Yes, I suspected that I scrwed up that loop. Please recheck my port now.

**Comment by lvinken** [comment]
[@Jojo-Schmitz](https://github.com/Jojo-Schmitz) rechecked your port: it is now OK

**Comment by Jojo-Schmitz** [comment]
Thanks!

**Comment by Jojo-Schmitz** [comment]
@lvinken any changes I'd need to be aware or, or a pure rebase?

**Comment by lvinken** [comment]
Just a rebase (to pass the unit tests)

**Comment by lvinken** [comment]
Is there any specific reason why this PR does not get merged ?

**Review by RomanPudashkin — APPROVED** [review]

**Comment by RomanPudashkin** [comment]
@lvinken Sorry for ignoring this PR. Please rebase it again. Thanks!

**Comment by lvinken** [comment]
Will rebase, may take a few days.

**Comment by lvinken** [comment]
Rebased

**Review by oktophonie — APPROVED** [review]

**Pull request merged**
