### PR TITLE
TAB - More French styles for frets and duration symbols

### PR DESCRIPTION
**Pull request by mgavioli**
__Reference__: discussion, screen-shots and background on style selection in the forum thread https://musescore.org/en/node/76561

__Data-wise__ changes:

Adds __4 new styles of fret marks__ for French tablatures:
- "Phalèse" from mid-XVI c. Phalèse prints (replaces the "Late Renaissance" style which was unsuccessful)
- "Bonneuil-de Visée" from 1686 print by Bonneuil of de Visée "Livre de pièces pour la guittarre"
- "Bonneuil-Gaultier" from late XVII prints by bonneuil of Gaultier works
- "Lute Didactic", exampled on Yisrael's well-known methods for lute, an 'abstract' style familiar to lutenists

Adds __two new styles of duration symbols__ of French origin:
- "French Baroque" which goes well with the "Bonneuil-de Visée" fret mark style;
- "French Baroque (headless)" which goes well with the "Bonneuil-Gaultier" style.

__Code-wise__ changes:

Converts legacy names into newer ones.

### CODE REVIEW

**Comment by lasconic** [comment]
What will happen in MuseScore 2.0.2 if a user open a score with an unknown fret or duration style?

**Comment by mgavioli** [comment]
@lasconic : Ether style falls back to the first style available (I did the test).

**Comment by lasconic** [comment]
Ok. So we could merge this in a 2.0.3 version if any right?

**Comment by mgavioli** [comment]
@lasconic : yes, I assume it can be merged into 2.0.3. However, I expect there will be adjustments in the font glyphs ('power TAB users' are scrutinizing this addition with the microscope!); then, there might be more steps in the (near?) future.

**Comment by lasconic** [comment]
OK. I'm not in hurry. It can wait 2.1. I'm still unsure we go for 2.0.3 or not.

**Pull request merged**
