### PR TITLE
Tag editing

### PR DESCRIPTION
**Pull request by Marr11317**
This branch is the rebased version of [this ](https://github.com/musescore/MuseScore/pull/3803/)pull request.
To resume what was modified:
 - Adds in the meta edit dialog:
   - Translatability fixups
   - Add and remove tags now possible (it was possible to add some, but not to remove them).
 - A few comments corrections to prevent misunderstandings.
 - Remove a few unwanted tags, like the platform: Linux, in My_First_Score.mscx. as of [shoogle's comment]((#3696 (comment)), replace the .mscz with .mscx.
 - In newwizard:
   - Add a more option to be able to edit more tags when creating a new score
   - Save basic settings like composer lyricist, default number of measures, etc. in QSettings.
 - Add an option to automatically track the work number:
   - Every time a new score is created, the work number is incremented;
   - the option contains a suffix and a prefix, and both can be activated or not.
   - The work number can be modified anytime in the prefsdialog, advanced tab.

### CODE REVIEW

**Comment by Marr11317** [comment]
image
image

**Comment by Jojo-Schmitz** [comment]
rebase needed

**Comment by Marr11317** [comment]
rebased and added completers as discussed [here](https://musescore.org/en/node/274345)

**Comment by Jojo-Schmitz** [comment]
Build failed on AppVeyor (MSVC), with a compile error, see https://ci.appveyor.com/project/MuseScore/musescore/build/1.0.2333#L4870

**Comment by Marr11317** [comment]
@Jojo-Schmitz Corrected. SubstyleId has been replaced by Tid a few weeks ago.

**Comment by Jojo-Schmitz** [comment]
Better commit message needed, like:

"Translatability to the tags , add ability to remove tags and edit them

and a few translations. A few corrections of comments to prevent misunderstandings. remove the Linux tag from My_First_Score.mscz."

**Comment by Marr11317** [comment]
@Jojo-Schmitz Is the new commit message good?

**Comment by Jojo-Schmitz** [comment]
fine by me. There is no issue to go along with it?

**Comment by Marr11317** [comment]
this one: https://musescore.org/en/node/274345, Do I close it with the link of the pull request?

**Comment by Jojo-Schmitz** [comment]
No, it is just a forum topic, not an issue, so nothing to close. But that's OK

**Comment by Jojo-Schmitz** [comment]
Travis CI is not happy, all mtests fail, looks like MuseScore crashes on all of them

**Comment by Marr11317** [comment]
Ok, anything else needed?

**Comment by Jojo-Schmitz** [comment]
Well, Travis CI and AppVeyor both failed

**Comment by Marr11317** [comment]
I can one test failed (`tst_compat114`), But why does it say 4 did at the very bottom of the raw log?
`  processed 34  -- failed 4`
What are the other tests that failed?

**Comment by Jojo-Schmitz** [comment]
I see "98% tests passed, 1 tests failed out of 56"

**Comment by Marr11317** [comment]
Reworked pull request coming. Closing now.

**Pull request closed without merging**
