### PR TITLE
Pocket Sax improvements

### PR DESCRIPTION
**Pull request by riaanvn**
Resolves: [Pocket Sax spelling and abbreviations improvements](http://musescore.org/en/node/299881) 

(forum discussion, no issue)

These are the commands I used to edit and the two edited files
I also swapped around  Pocket Sax/Xaphoon to Xaphoonin/Pocket Sax in the description field to prevent ambiguous expansion of the "/" to Pocket Sax / Pocket Xaphoon 

perl -p -i -e 's:Pocket-Sax/Xaphoon:Xaphoon/Pocket Sax:' share/instruments/instruments{.xml,xml.h} 

perl -p -i -e 's/pocket-sax/Pocket Sax in/i' share/instruments/instruments{.xml,xml.h} 

perl -p -i -e  's/P.-Sx. /Pkt. Sax /' share/instruments/instruments{.xml,xml.h} 

egrep -i 'P.-Sx.|Pocket-Sax|Pkt. Sax|Pocket Sax' share/instruments/instruments{.xml,xml.h} 

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [n/a] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Why 2 commits, and with the same title?

**Comment by riaanvn** [comment]
Thanks, not sure how that happened. I updated a branch in the past without having to squash. Should be fixed now. I assume this will only be merged post-3.4?

**Comment by riaanvn** [comment]
@Jojo-Schmitz are you happy with the changes (since the original/previous Pocket Sax was your PR) and ready to be merged?

**Comment by Jojo-Schmitz** [comment]
Fine by me, except maybe the "squashed" in the commit title

**Comment by riaanvn** [comment]
Agreed, " squashed" squashed. Ready for merge.

**Comment by Jojo-Schmitz** [comment]
?? It's still in the commit title, forgot to `git push --force`?

**Comment by riaanvn** [comment]
Jup that was it. What would I do without you?
@anatoly-os : ready to merge.

**Comment by Jojo-Schmitz** [comment]
Once we're in 3.5 mode...

**Comment by riaanvn** [comment]
I was thinking the exact thing paraphrased; "once the 3.4.x dust settles"

**Pull request merged**
