### PR TITLE
MeterSlider::paintEvent code cleanup

### PR DESCRIPTION
**Pull request by ericfont**
Use maxValue() instead of hardcoded -20.0f.
Also adjust code whitespace according to musescore style.

### CODE REVIEW

**Comment by ericfont** [comment]
There are many more whitespace formatting errors in this code.  If you want, I could fix all of them in this PR.

**Comment by Jojo-Schmitz** [comment]
Doesn't this collide with #3080?

**Comment by ericfont** [comment]
@Jojo-Schmitz yes it does.  What I think I'll do is wait for #3080 to be merged, and then I'll go fix *all* the whitespace errors in that file for this PR...

**Comment by lasconic** [comment]
I guess this can be coped in #3080. If yes, then please close this issue.

**Comment by ericfont** [comment]
Yes, this could be copied in #3080, so I'll close this.  But that issue discussion is a bit long already, so I don't necessarily want to confuse it anymore.  Regardless I'll open up new PR if needed after the dust settles.

**Pull request closed without merging**
