### PR TITLE
Fix #13487: Retain MU3 behavior by hiding dots when notehead (or rest) is hidden

### LINKED ISSUE #13487: [MU4 Issue] Making dotted note, or rest invisible doesnt make dot invisible - regression
**Describe the bug**
When user makes dotted note, or rest invisible, dot reamins vible.

**To Reproduce**
1. Select doted note (or rest)
2. Press "v", or untick "Visible"
3. Dot remains visible.

**Expected behavior**
Dot is marked invisible,or visible together with note (or rest)

**Screenshots**

https://user-images.githubusercontent.com/1646034/192146645-cc06869b-acdd-4e7a-9d12-8acc9ecaf222.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
May be (or may be not) related to #13114

### PR DESCRIPTION
**Pull request by asattely**
Resolves: https://github.com/musescore/MuseScore/issues/13487

### CODE REVIEW

**Comment by asattely** [comment]
This PR deals with visibility when the user selects a part of the note and presses the `v` shortcut. However, due to https://github.com/musescore/MuseScore/issues/11740 (I believe), the properties panel currently does not work when you attempt to hide only the dot--instead, it hides or shows the entire chord when any part of that chord is selected. I am now looking into that issue and may (but not necessarily will) fold that fix into this PR if it's simple. If it's not simple then I'll submit a PR for that first and we can merge this afterwards.

**Comment by asattely** [comment]
After a buncha back-and-forth with @oktophonie and @Tantacrul, this PR has been amended with the ability for note dots (as a whole, though if we want it to work on an individual basis that's an easy fix) to be affected by the properties panel independently from the rest of the chord. If people want individual dots hidden, they can still use the `v` shortcut.

**Comment by Tantacrul** [comment]
OK, this is working fine for me. Thanks very much!

**Comment by Tantacrul** [comment]
Actually. Hold on... I just got a crash when pressing V on a note within a chord. Very easy to reproduce.

https://user-images.githubusercontent.com/21022311/204672954-b5e1dac1-62a6-4f12-b033-21ecbaa4fb87.mov

**Comment by oktophonie** [comment]
I can replicate this crash but only very unpredictably - i.e. if I make a few chords, and toggle the invisibility on and off over and over again (perhaps mixing in toggling the visibility of a whole bar) it will crash __eventually__, but it takes some time!

**Comment by Tantacrul** [comment]
When I test in Windows it is a little harder but I've now done it about a dozen times, so there's definitely a problem. Mac may be easier to test on

**Comment by Tantacrul** [comment]
Tested again on Windows. Unfortunately can still get a crash (after a few attempts) where I make a note (that sits within a chord) invisible and then undo it.

I think we're going to have to bump this to 4.x since the instability issue makes it dangerous to merge now.

**Comment by asattely** [comment]
I'm unable to reproduce any crash on windows, using the Debug or RelWithDebInfo builds, or even with the build artifact from this PR. @Tantacrul if you are still able to reproduce this on windows, could you take a video of it so I know the exact steps that are happening?

**Comment by Tantacrul** [comment]
@oktophonie @asattely @RomanPudashkin 

I think we need to park this for a moment. @oktophonie, @bkunda and I have just agreed on a proper design improvement, which seeks to address this problem in a more robust way. In the process I've learned a lot about how this whole system works. Once we've agreed on the design I'll share it and we can then plan the best way forward.

One current confusion is that @RomanPudashkin and @asattely have similar PRs which do slightly different things.

**Pull request closed without merging**
