### PR TITLE
[Mu3] fix #327681 illegal repeatsegment crash

### PR DESCRIPTION
**Pull request by jeetee**
illegal repeatsegment inserted due to a certain open volta, jump and end repeat combination

Resolves: https://musescore.org/en/node/327681

Fixes interpretation order so the end repeat is covered by the open volta if a jump also exists in the same measure.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows the *3.x* coding rules
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by jeetee** [comment]
I realize you don't really want Mu3 PR's anymore, but this one is the only build system I have currently set up; and for the benefit of PR#9000

**Comment by jeetee** [comment]
See #10159 for the Mu4 fix

**Comment by Jojo-Schmitz** [comment]
Deleted a tad early, too early for a `git cherry-pick`. Oh well, I will pick that cherry manually then...

**Comment by jeetee** [comment]
> Deleted a tad early, too early for a `git cherry-pick`. Oh well, I will pick that cherry manually then...

Closed, purposefully *not* deleted the branch yet ;-)

**Comment by Jojo-Schmitz** [comment]
Well, it doesn't show in the list of PRs in GitHub desktop anymore. Anyway, my manual cherry pick works.

**Comment by Jojo-Schmitz** [comment]
It doesn't crash with that sample score anymore, but playback stoppes at the Fine, the 1st round already, never plays the part after it.
Well, my hacky fix did that too... but I'd rather be sure that this is your intention here?

**Comment by jeetee** [comment]
[Yes](https://musescore.org/en/node/327681#comment-1109054), both volta's are skipped and the open volta should cover the end repeat, thus skipping it as well.

**Pull request closed without merging**
