### PR TITLE
Add files to create a snap package for version 2.2

### PR DESCRIPTION
**Pull request by pachulo**
Created another PR instead of this one https://github.com/musescore/MuseScore/pull/3204, as I messed up with the other branch.

This was tested by myself and the snap seems to be quite functional. But:

* Some interfaces need to be pluged manually: https://forum.snapcraft.io/t/snaping-musescore/704

This is based off: https://github.com/pachulo/musescore-snap

This version could go to the beta channel of the store:
* https://snapcraft.io/docs/core/store

And this service could be used to create the snaps for the different archs and upload them to the store:
* https://build.snapcraft.io/

### CODE REVIEW

**Comment by pachulo** [comment]
@lasconic No, I don't have enough access to put build.snapcraft.io in place, it needs to be somebody who can grant read access to MuseScore main repo to their App.

**Comment by lasconic** [comment]
OK, I will have a look. I guess I need to create another application, like musescore-dev or something like that?

**Comment by pachulo** [comment]
I'm not really sure about you needing to create another application...that wouldn't make a lot of sense.
I just though that you could have different ways of putting releases for the same application...

**Comment by lasconic** [comment]
Ok. I see, tracks and channels here https://snapcraft.io/docs/reference/channels
Where is 2.1 published right now?

**Comment by pachulo** [comment]
2.1 is in the beta channel, because the snapcraft.yaml that was used to create the snap comes with grade devel: https://github.com/pachulo/musescore-snap/blob/master/snap/snapcraft.yaml#L16
Once you feel confident about the snap it can be promoted to stable and then use the 2.2 buid.snapcraft.io snaps for the beta channel, or something like this...

**Comment by lasconic** [comment]
Ok the beta channel of the latest track, since we have a single track right now. I would put 2.2 on the edge track then, not the beta, not sure how to do that thought. I will merge this PR and we will see.

**Comment by pachulo** [comment]
OK, I've been told in the snappy IRC channel that "build.snapcraft.io will release to edge, and then you can release those same revisions to other channels OR upload manually other revisions and release them to channels you choose" So it fits your use case perfectly!

**Comment by lasconic** [comment]
Mm.. that will not work with build.snapcraft.io, it seems they only poll the master branch...
I added a comment here https://github.com/canonical-websites/build.snapcraft.io/issues/440 
At least the file is in the repo, if they manage to make it happen, we can test.

**Pull request merged**
