### PR TITLE
fix #275230 Change loader_path for non Qt lib

### PR DESCRIPTION
**Pull request by handrok**
Change_loader_path to executable_path for non Qt dylib

### CODE REVIEW

**Comment by shoogle** [comment]
Just so you know, it's possible to create "nightly builds" on your own fork so that you can test features on all platforms before they are merged into the main repository. See these items in the [Git Workflow](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/git-workflow):

- [Run tests on personal Travis](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/git-workflow#Run_tests_on_personal_Travis)
- [Upload AppImages to personal Bintray](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/git-workflow#Upload_AppImages_to_personal_Bintray)

You can also do this for Windows builds on AppVeyor. In fact, AppVeyor creates builds for all pull request, which can be downloaded from the [build details page](https://ci.appveyor.com/project/MuseScore/musescore/build/1.0.2313) under the [artefacts tab](https://ci.appveyor.com/project/MuseScore/musescore/build/1.0.2313/artifacts) (or could be if AppVeyor wasn't currently disabled).

**Comment by anatoly-os** [comment]
Also, the most important artifact here is Mac package which could be theoretically built, but not easily uploaded. It could be done by setting up users own storage, but it is not trivial.

**Comment by shoogle** [comment]
[These instructions](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/git-workflow#Upload_AppImages_to_personal_Bintray), with only a little bit of modification, work equally well on Mac. I think MuseScore was asked to close its official repo on Bintray for using too much bandwidth, but this doesn't apply to unofficial repos belonging to a single contributor. I have one [here](https://bintray.com/shoogle/test), for example.

**Comment by handrok** [comment]
follow up https://github.com/musescore/MuseScore/commit/9fb8c7d6d62a4d7cc200c38179ca7fe4d8602385

**Pull request merged**
