### PR TITLE
some capitalization fixes

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by MarcSabatella** [comment]
On the assumption that Travis might fail as usual and we'll need to trigger another build anyhow :-), you could add  Show courtesy clefs and Hide courtesy clefs in context menus, which I guess should be capitalized in title case like everything else.

**Comment by MarcSabatella** [comment]
Oh well, maybe next time :-)

**Comment by Jojo-Schmitz** [comment]
Will do anyway.

**Comment by Jojo-Schmitz** [comment]
Done.
Would these Status bar info need to be in Title Case or is Sentence case OK?

**Comment by MarcSabatella** [comment]
I have no real preference on that.

**Pull request merged**
