### PR TITLE
fix #81121: hairpin overlaps dynamic

### PR DESCRIPTION
**Pull request by MarcSabatella**
Improved layout of hairpins, to avoid dynamics in same segment / track, as shown in the accompanying vtest.

This represents an incompatible change from earlier versions and should not be merged into 2.0.3, but I have added compatiblity code so 2.0.X and old scores (mscVersion <= 206) will still render correctly.  Note this compatibility code will not currently work as expected since 2.0.X scores will currently still show as mscVersion == 206 even after loading, until two minutes pass and the score is auto-saved, at which point the version number bumps up to 207 automatically.  I think we need to update the code at the end of doLayout() to set mscVersion to MSCVERSION unconditionally rather than only doing it if it is currently 114 or less.  But that change is a bit more global in implication, so I am leaving it out of this PR.

### CODE REVIEW

**Comment by ZackTheCardshark** [comment]
@lasconic, could you look at this one again? It seems like a perfect extension of Smart Layout.

A rebase is needed, though, @MarcSabatella.

**Comment by MarcSabatella** [comment]
OK, thanks for the heads up.

But now that we have the new layout merged, I'm not so sure the approach I took here still makes sense.  Maybe it does, but do we (or should we) have an overall strategy for how to handle collisions?  Seems like maybe now we should be using the new shape system for things ike this, and have one central place - or perhaps a single virtual function that is overloaded - to check for collisions.  Rather than having individual functions for different element types each handling some part of the job differently.  I wouldn't mind seeing the existing articulation and fingering layout code brought in line with this.

**Comment by lasconic** [comment]
I would love @wschweer's input on this.

**Comment by IsaacWeiss** [comment]
Same request again at https://musescore.org/en/comment/reply/116236.

**Comment by anatoly-os** [comment]
Current state of master is much better than in 2016. The related issue is closed.

**Comment by IsaacWeiss** [comment]
Actually, hairpins and dynamics are still extremely poorly handled... collisions not being detected, and false positives causing offsets where they shouldn't be.

**Pull request closed without merging**
