### PR TITLE
Fix #135791: Make dynamics text style italic for 2.1

### PR DESCRIPTION
**Pull request by IsaacWeiss**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
one mtest failed, tst_text

**Comment by IsaacWeiss** [comment]
Oddly, I can't seem to find the specific problem in the log at https://travis-ci.org/musescore/MuseScore/jobs/209590844. I'm used to seeing a diff in a test file that needs to be updated; is this something different?

**Comment by lasconic** [comment]
Yes, the tst_text doesn't use diff files, instead it constructs tests programatically.
The error is later in the log and it says:

```
FAIL!  : TestText::testTextProperties() Compared values are not the same
   Actual   (text->xmlText())                               : "I<b>Love</b>MuseScore"
   Expected (QString("I<b>Lo<i>ve</i></b><i>Muse</i>Score")): "I<b>Lo<i>ve</i></b><i>Muse</i>Score"
   Loc: [/home/travis/build/musescore/MuseScore/mtest/libmscore/text/tst_text.cpp(338)]
```

**Comment by IsaacWeiss** [comment]
Thanks. Hopefully this should do it.

**Comment by IsaacWeiss** [comment]
Success!

**Comment by lasconic** [comment]
I changed the test a bit and merge it 5b43154dded5b693188e9cd458c61cfad1510785

**Pull request closed without merging**
