### PR TITLE
[MU4] Adding articulations

### PR DESCRIPTION
**Pull request by Eism**
Peek 2020-12-01 19-52

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Wow, cool that the articulations are also visible on the shadow note!
One thing, regarding the GIF you posted: I see that if you add a note to a chord that already _has_ the selected articulation, that articulation is removed from the chord. Isn't that a bit unintuitive?

(By the way, how do you create such long and high-res GIFs? 😉)

**Comment by Marr11317** [comment]
> One thing, regarding the GIF you posted: I see that if you add a note to a chord that already _has_ the selected articulation, that articulation is removed from the chord. Isn't that a bit unintuitive?

yes, it looks like it's acting like a toggle.

@cbjeukendrup liceCAP is nice for gifs

**Comment by cbjeukendrup** [comment]
@Marr11317 Thanks, I'll have a look! 😀

**Comment by Eism** [comment]
@cbjeukendrup, thanks! I find it difficult to answer, I am going to submit the solution for testing.

(I use [peek](https://github.com/phw/peek) )

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
