### PR TITLE
Fix GH#23241: Header/footer special symbols tooltip closes too quickly

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: #23241

### CODE REVIEW

**Comment by Eism** [comment]
see https://github.com/musescore/MuseScore/issues/23241#issuecomment-2172461004

**Comment by Jojo-Schmitz** [comment]
See https://github.com/musescore/MuseScore/issues/23241#issuecomment-2172560190

**Comment by cbjeukendrup** [comment]
See https://github.com/musescore/MuseScore/issues/23241#issuecomment-2173153835 :)

**Comment by Jojo-Schmitz** [comment]
I'll be AFK for the next 2 weeks and a bit...
So if someone else would like to take over: be my guest ;-)

**Comment by Jojo-Schmitz** [comment]
Wouldn't this be a good enough quick and dirty fix for 4.4?

**Comment by Jojo-Schmitz** [comment]
Closing this in favor of https://github.com/cbjeukendrup/MuseScore/commit/c62c81d8257d3aa985bcee9a9073df88fccd18b2

**Pull request closed without merging**
