### PR TITLE
Fix #21456: Set mag rate for the grace note palette

### LINKED ISSUE #21456: Grace note icons in palette are too small
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

_No response_

### Steps to reproduce

1. open grace notes platte

### Screenshots/Screen recordings

grace-palette

### MuseScore Version

master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

Setting scale to 1.4 corrects icons size.

### PR DESCRIPTION
**Pull request by bakajikara**
Resolves: #21456

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by bkunda — COMMENTED** [review]
It's good, but 1.45 strikes me as being a tad on the bulky side. 
Could we go with 1.35 instead? 
Then it'd be perfect :-) 

1.45
Screenshot 2024-08-22 at 11 02 59 AM

1.35
Screenshot 2024-08-22 at 11 03 31 AM

**Review by bkunda — APPROVED** [review]
Looks great! Tested on macOS and Win. 

Just a point on macOS: I had to manually reset the palette to see changes. I did not have to do this on Win. 

@cbjeukendrup not sure if this is a problem to be dealt with here?

**Comment by MarcSabatella** [comment]
I suspect the different there isn't macOS vs Windows, but rather, a matter of whether or not you had previously customized that palette or the workspace in general.  I'm guessing you had on the macOS system but not on the Windows system.

**Comment by cbjeukendrup** [comment]
I think it's exactly what Marc says. For now, it is kind of expected that new changes to palettes are not applied automatically if the user had modified their palettes. This could be refined in the future, but doesn't seem something for this particular PR.

**Pull request merged**
