### PR TITLE
fix #281867 : Crash when closing MuseScore on Mac with a MIDI device

### PR DESCRIPTION
**Pull request by AntonioBL**

### CODE REVIEW

**Comment by AntonioBL** [comment]
I managed to reproduce the bug by creating a virtual MIDI setup ( https://help.ableton.com/hc/en-us/articles/209071169-Sending-and-receiving-MIDI-messages-using-a-virtual-MIDI-network ).
Apparently the mididriver was accessed by portaudio from a different thread with respect to the one in which it had been deleted. By deleting the mididriver only after stopping and terminating portaudio I could not reproduce the bug, so I think this change should solve it.

**Comment by AntonioBL** [comment]
@blackears : I hope this change does not interfere with your PR which introduced these lines (commit https://github.com/musescore/MuseScore/commit/32a6b128ebac6fb6ff11596385c5088825c65a5d ). From what I understand, their goal is only to prevent a memory leak and shifting them after portaudio termination should still prevent the memory leak.

**Comment by blackears** [comment]
I think that will work.  The midi driver is still being deleted.

**Comment by SinanKarasu** [comment]
Still crashes on exit on Ver. 3.0.5.21343. I deleted the App, got rid of all MuseScore files/folders on ~/Library, /Library, /System. Fresh installed and it crashed on exit with SIGSEGV. Mojave 10.14.4
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_pthread.dylib       	0x00007fff6aff1137 pthread_mutex_lock + 0
1   com.apple.CoreFoundation      	0x00007fff3e90de5d CFRunLoopStop + 45
2   org.musescore.MuseScore       	0x000000010a35e46c Pt_Stop + 28

**Pull request merged**
