### PR TITLE
fix #255791 - [MusicXML import] use lyric number as relative instead …

### PR DESCRIPTION
**Pull request by lvinken**
…of as absolute line number

### CODE REVIEW

**Comment by lasconic** [comment]
I had forgotten about this PR. Sorry for that.
I'm not sure it's the good thing to do. The `testExtendedLyrics.xml` doesn't work anymore. Somehow lyrics with the same "number" should be on the same line, but it's not the case in this test.

**Comment by lvinken** [comment]
No problem, thanks for being critical and quality conscious. Apparently I missed some details, will have a look (again).

**Comment by Jojo-Schmitz** [comment]
Also it meanwhile needs a rebase

**Comment by lasconic** [comment]
No need to rebase. As highlighted above, the implementation is not ok. I will close the PR. @lvinken feel free to do another PR when you look into it again.

**Comment by lvinken** [comment]
As this is on the hit list for 2.2, I will have another look at it.

**Pull request closed without merging**
