### PR TITLE
Add retry on saving file if temp file cannot be opened for writing. …

### PR DESCRIPTION
**Pull request by manish-makwana**
…Saving will be retried up to 3 times, with a 10ms wait between each attempt. This may help with saving from cloud synced folders (dropbox etc).

Resolves: https://musescore.org/en/comment/1093332

Changes:
- Retry opening the temp file up to 3 times.
- 10 millisecond wait between each attempt.

Reason:
- Workaround for race conditions if other programs (such as dropbox) lock the temp file for access at the same time.

Potential issues:
- Wait might not be long enough to avoid conflicts with other programs.
- Unsure if this is thread safe. (Does MuseScore use multithreading?)
- Other issues (such as filename format) might be causing the original error, not race conditions.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
The 3.6.2 branch is a dead end road. better use 3.x (but even that may turn out as a dead end), best use master.

**Comment by manish-makwana** [comment]
@Jojo-Schmitz Ohh I didn't realise 3.x was a separate branch and more up to date haha.

I'm confused by the code structure in master. E.g. I can't find the function that saves files - seems to have been renamed. Are there any docs about the code reorganisation in v4?

**Comment by Jojo-Schmitz** [comment]
For master scorefile.cpp is now in src/engraving/libmscore
But that temp file stuff seems gone, so I guess you're PR is not relevant for master anymore

**Comment by wizofaus** [comment]
Try NotationProject::doSave

**Comment by manish-makwana** [comment]
Ok thanks, seems like the best thing will be to wait for v4 to be released then :)

**Pull request closed without merging**
