### PR TITLE
Removing outdated MusicXML files from LilyPond

### PR DESCRIPTION
**Pull request by rettinghaus**
I was wondering what should happen with the `lilyXml` in directory in `test`? It seems rather outdated and unused. I ran the script with LilyPond 2.24.3 and MuseScore 4.2.1 updating all the PNGs.

I'm in favor of just removing it completely, but if it must stay, it should at least be updated to the more recent files from <https://github.com/cuthbertLab/musicxmlTestSuite>.

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
I believe this folder is currently completely unused, so we can just as well remove it. 
We could in theory add these files to the VTests, but that would be questionable for two reasons:
- that would be testing two things at the same time, namely xml import _and_ layout
- it's unclear how much added value it would have, on top of the existing musicXML "unit tests"

What do you think about this? 
And what do @oktophonie and @miiizen think about utilising this musicXML test dataset?

**Comment by rettinghaus** [comment]
I think the tests we have for MusicXML support are tailored to specific functions of import or export, whereas the LilyPond test suite addresses more general functions of MusicXML itself. I don't see any added value in them.

**Comment by cbjeukendrup** [comment]
In that case I'm also in favour of removing the thing. Less unused old files = less opportunities for confusion :)

**Comment by rettinghaus** [comment]
@cbjeukendrup The whole directory has been removed now.

**Comment by miiizen** [comment]
Yes, I agree! I don't see the need for any more XML tests.

**Review by miiizen — APPROVED** [review]

**Pull request merged**
