### PR TITLE
Switch to Qt 6.2.9

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: https://github.com/musescore/MuseScore/issues/23505
Resolves: https://github.com/musescore/MuseScore/issues/23970
Resolves: https://github.com/musescore/MuseScore/issues/24232
Resolves: https://github.com/musescore/MuseScore/issues/24579
Resolves: https://github.com/musescore/MuseScore/issues/24667

Resolves: https://musescore.org/en/node/356338
Resolves: https://musescore.org/en/node/346998#comment-1218129
Resolves: https://musescore.org/en/node/366417
(and a big number of 'popups on wrong screen' reports from .org)

### CODE REVIEW

**Comment by desertwind77** [comment]
I cannot find the macos image so I cannot test this on my system. Could you give me the URL to the .dmg file for this pull request build?

**Comment by cbjeukendrup** [comment]
This page: https://github.com/musescore/MuseScore/actions/runs/10459146162 (found via Checks > "Build: macOS") contains the download link (I can't give a direct link because GitHub has some kind of system with auto-expiring-redirect-whatever).

(You're right by the way that the docs need updating, since the name was changed from "CI_macOS MU4" to "Build: macOS". Thanks!)

**Comment by desertwind77** [comment]
I tested the latest image. I think the issue is gone.

**Comment by cbjeukendrup** [comment]
Right now, the easiest way is to use a 4.4.3 nightly build. See https://musescore.org/en/nightly-builds, which also includes instructions.

**Comment by cbjeukendrup** [comment]
Closing as superseded by #25016 for 4.5; for 4.4.3, this change has been applied on Windows only, in #24969.

**Comment by Jojo-Schmitz** [comment]
Isn't this needed for master too, now that we won't move to Qt 6.8?

**Pull request closed without merging**
