### PR TITLE
"Double Coda" to "Doppia Coda"

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
(and "Doppio Segno")
Separated out from #19155, pending a reply from @mike-spa

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@mike-spa mind to review?

**Comment by Jojo-Schmitz** [comment]
ALternative might be "Doppio Coda", maybe?

**Comment by mike-spa** [comment]
> ALternative might be "Doppio Coda", maybe?

That would be "DoppiA coda". The thing is: I don't know the context of this, how are these strings going to be used? I'm also not familiar with the term itself: I know what a Coda is, but for me Codetta just means a "small coda", and "Double code" means nothing to me, so I can't give any specific advice besides ensuring the correct italian words

**Comment by Jojo-Schmitz** [comment]
It is just 2 codas.

**Comment by Jojo-Schmitz** [comment]
I'd just like the confusing mix of Italian and English sorted, my initial idea was "Doppia Coda", untill I remembered MuseScore 1 and its "Codetta"

**Comment by Jojo-Schmitz** [comment]
And yes, you've been asked because of your language skills ;-)

**Comment by Jojo-Schmitz** [comment]
Note though that the palettes don't contain a double coda at all, just the jumps to them

**Comment by Jojo-Schmitz** [comment]
So maybe we'd rather remove them entirely?
@oktophonie ?

**Comment by Jojo-Schmitz** [comment]
Some context: I believe these came in via GuitarPro import (so we'd rather keep them), see
https://github.com/musescore/MuseScore/blob/186dbacf08be423508df226a51e23f9b0d0f6f05/src/importexport/guitarpro/internal/gtp/gpconverter.cpp#L64-L79

**Pull request merged**
