### PR TITLE
Fix keyboard navigation for DockTitleBar

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves the easier part of #16066

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
@DmitryArefiev One note for testing: it is known that this fixes only a part of the issue; see https://github.com/musescore/MuseScore/issues/16066#issuecomment-1404345758. When you launch MuseScore with the Mixer already opened, it should work fine now, but after opening, closing, undocking and re-docking it might stop working. That will probably require a separate fix.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Tested on Win10. 

> When you launch MuseScore with the Mixer already opened, it should work fine now

in this case in PR's build it **skips mixer channel section** (master build then PR's build):

https://user-images.githubusercontent.com/90187801/215774229-6d89325e-0d35-4fea-b748-48ae799b27ca.mp4

**Comment by Eism** [comment]
@cbjeukendrup 
Look at this commit https://github.com/eism/MuseScore/commit/fec479d70a4a455e56f7d2259054c0860a082223

**Comment by cbjeukendrup** [comment]
@Eism Thanks! I cherry-picked that commit. Now it works well for me, as long as the panels are docked in their default location.

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxUbuntu 22.04 - **now Mixer menu accessible**

**Comment by bkunda** [comment]
🟢 Re-tested: Windows 11 Pro, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d. Remains FIXED.

**Pull request merged**
