### PR TITLE
fix #278382: add Soprano, Mezzo-soprano, Alto, Tenor and Baritone with C Clef, for Early Music

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by mirabilos** [comment]
Is this really worth the added visual clutter in the instruments dialogue?

I’d rather people just select the “instruments” and then drag the appropriate clefs from F9.

**Comment by Jojo-Schmitz** [comment]
It is only visible if you select all instruments (or just early music),  not I'm the default of common.
IMHO it is worth it as it otherwise is impossible for users to create templates using those clefs.

**Comment by mirabilos** [comment]
Saving as teplate removes the clef? Or template instantiation?

Is that deliberate, or shouldn’t perhaps that be the place to apply the wrench to?

**Comment by MarcSabatella** [comment]
Clefs added to a score used as a template are treated no differently from notes or other elements added - they are not used when instantiating the template.  That again is the issue here.  Yes, in theory, it is possible to special-case an initial clef, so the template instantiation would look just enough at the content of a score to see if those exist.  So far we haven't done that sort of thing.  I'm not opposed to it, personally, but it is a more significant change.

**Comment by mirabilos** [comment]
Marc Sabatella dixit:

>Clefs added to a score used as a template are treated no differently
>from notes or other elements added - they are not used when
>instantiating the template. That again is the issue here. Yes, in

OK, thanks for the explanation.

**Pull request merged**
