### PR TITLE
fix #282730: "Untitled"/"My First Score" does not respect locale page size

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by shoogle** [comment]
Couldn't this be MSCX? I don't think we show the thumbnail anywhere.

**Comment by Jojo-Schmitz** [comment]
Good idea, done

**Comment by Jojo-Schmitz** [comment]
Not sure though whetter we'd need to convert preferences for older vesions to adjust to that change, nor how to do that

**Comment by shoogle** [comment]
Ah, good point. That would involve finding the place where preferences are read during startup (I think in `mscore/musescore.cpp`), and then immediately afterwards saying:

```c++
if (preferences.startupFile == "My_First_Score.mscz")
      preferences.startupFile = "My_First_Score.mscx"
```

I believe that would be enough to ensure the new preference is written when MuseScore is closed too.

**Comment by Jojo-Schmitz** [comment]
I guess this should work

**Pull request merged**
