### PR TITLE
Save locale-dependent preferences on first start

### PR DESCRIPTION
**Pull request by Soerboe**
https://github.com/musescore/MuseScore/pull/3934 for v3.0

and some renames

### CODE REVIEW

**Comment by anatoly-os** [comment]
Thanks!

**Comment by anatoly-os** [comment]
@Soerboe @mirabilos afaiu this PR, if I start MuseScore first time, it will apply system locale, e.g. Russian one and creates folders in `MuseScore3Development/` with Russian names. Then, if I switch MuseScore language to English, folders will be kept in Russian. Is it correct?

**Comment by Soerboe** [comment]
@anatoly-os You just pointed me at a bug. If you choose something else then system locale in first-start-dialog two sets of folders are actually created. Not good. Will look into it. It has to do with when updateExternalValuesFromPreferences() are called.

But what you explained was the intention behind #3934, afaiu

**Comment by mirabilos** [comment]
anatoly-os dixit:

>@Soerboe @mirabilos afaiu this PR, if I start MuseScore first time, it
>@will apply system locale, e.g. Russian one and creates folders in

Directories. (But yes.) Folders are IMAP folders, things like this
https://www.eoffice24.com/images/thumbnail/produkte/large/920207AA.jpg
and the name of the GUI representation of a directory in MS Windows.

>@`MuseScore3Development/` with Russian names. Then, if I switch

Yes.

>@MuseScore language to English, folders will be kept in Russian. Is it
>@correct?

Either MuseScore or system language.

The idea is that the directories, once initially created, keep
their names, unless the user EXPLICITLY changes them in the
Preferences dialogue.

bye,
//mirabilos
-- 
15:39⎜«mika:#grml» mira|AO: "mit XFree86® wär’ das nicht passiert" - muhaha
15:48⎜<thkoehler:#grml> also warum machen die xorg Jungs eigentlich alles
kaputt? :)    15:49⎜<novoid:#grml> thkoehler: weil sie als Kinder nie den
gebauten Turm selber umschmeissen durften?	-- ~/.Xmodmap wonders…

**Comment by will** [comment]
why does your email program add @ symbols when you reply

**Comment by mirabilos** [comment]
Will Leinweber dixit:

>why does your email program add @ symbols when you reply

When I reply, I wrap overlong lines; it seems to take
the leading >@ as line præfix for all lines.

**Comment by Soerboe** [comment]
@anatoly-os Last commit should fix the bug mentioned above.

**Pull request merged**
