### PR TITLE
[MU3] Paren time sig

### PR DESCRIPTION
**Pull request by Marr11317**
Resolves: https://musescore.org/en/node/313219#comment-1042033

NOTE: This PR needs elerouxx's PR to be merged first (#6550 )

MuseJazz includes parentheses by default in its time signatures. With elerouxx's PR #6550 it is now possible to append them manually. As such, new scores created with 3.6 will not have this trailing parenthesis by default. 

The change to MuseJazz hasn't been done yet, but because I have no development machine right now, I am testing with the build here and the artifacts generated while I remove the MuseJazz Parentheses.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/WorkflowAndGuidelines/CodeGuidelines.md)
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Marr11317** [comment]
@elerouxx do you have any clue why [these changes](https://github.com/musescore/MuseScore/pull/6917/commits/ac39238619f1f55d6f48ffe27a63e586170854cc#diff-99314dfd537ef914e998d85f1ad9531863797db00952c3c70aceedfc672ecd97R261) do not set the parser string?

**Comment by elerouxx** [comment]
> @elerouxx do you have any clue why [these changes](https://github.com/musescore/MuseScore/pull/6917/commits/ac39238619f1f55d6f48ffe27a63e586170854cc#diff-99314dfd537ef914e998d85f1ad9531863797db00952c3c70aceedfc672ecd97R261) do not set the parser string?

You mean timeSig.cpp @ 261? I don't think the (old) variable is getting set true for these types. This variable seems to be for a very old time signature implementation that had a sequence of nominators. (additive?).

**Comment by Marr11317** [comment]
okay, this is now ready. As soon as elerouxx's PR is merged this one can be too. (or both can be merged at the same time with this PR)

So here's how it works: When older scores are loaded, if these scores are using MuseJazz, then the symbols are corrected.

**Comment by Jojo-Schmitz** [comment]
The vtest fails are actually fixes, before:
musejazz-4-ref
emmentaler-4-ref
after:
emmentaler-4-1
musejazz-4-1

**Comment by vpereverzev** [comment]
3.x merges are closed

**Pull request closed without merging**
