### PR TITLE
Fix #286600: Use same dependencies for MinGW as are used for MSVC

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
works for compile, i.e. the header files are found and also for `make install`, i.e. the dlls are found and copied/renamed onto the instal folder (win32install or win64install), but not yet at link time, i.e. the libs are not found at that step, help needed there...

Edit: I think I got it now (basically thanks to the hint that MinGW doesn't need the static libs)

### CODE REVIEW

**Comment by anatoly-os** [comment]
Mingw doesn't need static libs. It somehow generates it by itself. Btw, FYI, I'm implementing WinSparkle which won't work with mingw from the box. It means autoupdating won't be supported from the box.

**Comment by Jojo-Schmitz** [comment]
Well, for self-built version WinSparkle won't be needed anyhow ;-)

**Comment by Jojo-Schmitz** [comment]
I think I got it now (basically thanks to the hint that MinGW doesn't need the static libs)

**Comment by Jojo-Schmitz** [comment]
_Mingw doesn't need static libs. It somehow generates it by itself._ Maybe that is why the linking takes so long?

**Comment by Jojo-Schmitz** [comment]
Esp. helpful when switching between Qt versions (like from 5.9.x to 5.12.2, which does again provide a 32bit MinGW), as all dependencies are in one place rather than scattered about in Qt directories and need to get copied across to a different Qt/Tools directory time and time again.
And there are still some 'die-hards' preferiing QtCreator/MinGW over MSVS/VC...
Doesn't affect anybody else as far as I can see.

**Comment by Jojo-Schmitz** [comment]
I don't get why the ApVeyor build fails now. It didn't before the rebase and there havn't been conflicts.

**Comment by Jojo-Schmitz** [comment]
Hmm, seems to work now, so possibly a temp. glitch

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/286600

**Comment by dmitrio95** [comment]
Looking through the changes, it seems they indeed should not change anything that worked previously for all compilers except MinGW. Still I didn't pay much attention to MinGW changes, but if they work correctly I see no reasons not to merge them (especially given that MinGW seems to be considered unsupported officially).

Also after these changes the MinGW compile instructions in Handbook will need an update. @Jojo-Schmitz, will you do such an update?

**Comment by Jojo-Schmitz** [comment]
Yes, I'll update those instructions

**Comment by dmitrio95** [comment]
OK, then let's merge it, I hope it helps MinGW users.

**Comment by Jojo-Schmitz** [comment]
https://musescore.org/en/handbook/developers-handbook/compilation/compile-instructions-windows-mingw-git updated

**Pull request merged**
