### PR TITLE
Fix #275218: fix MSVC warnings

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Fixes:

* Warnings C4304, C4804 and C4838.
* Warnings C4065 and most C4702 (all but two, see below).
* Warnings C4701.
* Issue with lrelease failing when path to repo is longer apparently resulting in a command line to long for MSVC to handle.
* Warnings C4244.
* Speed up MSVC builds by using all CPUs. Saves some 4 minutes out of some 18 on AppVeyor, so should help getting 4 builds done per hour rather than 3. Helps even more with local builds, for me a 50% boost.
* Warnings C4457.
* Warnings C4459.
* Some warnings C4456, due to nested `foreach` loops.

Leaves us with: 

* Those two C4702 warnings (unreachable code), in `mscore/importgtp-gp4.cpp` (lines [1023](https://github.com/musescore/MuseScore/blob/0e7cd231f360aac342514b1563a978dfd3d16e05/mscore/importgtp-gp4.cpp#L1023) and [1082](https://github.com/musescore/MuseScore/blob/0e7cd231f360aac342514b1563a978dfd3d16e05/mscore/importgtp-gp4.cpp#L1082)(both understood now, but no idea how to fix)). Those do not show on the AppVeyor builds, might be due to me using a slightly different MSVC?
* A whole bunch (406!) of C4456 and C4458 warnings (variables shadowing others, either local or class members).
* Two Linker warnings LNK4221, due to empty objects for libscore/keyfinder.obj (where all code is commented out in the corresponding cpp file with `#if 0 ... #endif`) and bww/writer.obj (where the corresponding cpp file doesn't contain any code at all)
* One Linker warning LNK4098, LIBCMTD conflicting with other libs

See also https://musescore.org/en/node/275218

### CODE REVIEW

**Comment by 19joho66** [comment]
Concerning :
"Those four C4702 warnings (unreachable code), two each in libmscore/instrtemplate.cpp (lines 341 and 350)"

This warning is issued because you jump out of the for loop before the increment operator of the for loop can be executed. (You jump out right after the if() condition due to the break command which I guess  isn't intendet anyway)

**Comment by Jojo-Schmitz** [comment]
Ahh, indeed, if I break up those to two loops into multiple lines the C4702 shows at the `i++`!
Same code in 2.3.2, and probably longer, so may be a long standing bug.

**Comment by Jojo-Schmitz** [comment]
Quite a few C4456 are due to nested `foreach( , )` loops, could get fixed by using `for( : )` for the inner loop, but I wonder whether to just change them all? Or only those in the affected files? Or only those in direct vicinity?

**Comment by 19joho66** [comment]
Concerning the nested foreach() loops:

Have a look at the following link:
https://stackoverflow.com/questions/30705166/qt-wshadow-warning-on-nested-foreach

I think this explains the problem

**Comment by 19joho66** [comment]
concerning:  mscore/importgtp-gp4.cpp (lines 1023 and 1082)

If I counted the braced correctly I think the for loop is left prematurely due to the break direktly after the If clause

**Comment by Jojo-Schmitz** [comment]
When re-indenting the code it becomes clearer and does not look like what you think, I believe?

**Comment by 19joho66** [comment]
I've copied the snipped and formated it with another bracing convention. There you can see that there is a break after the if clause, which is basically the same problem as the two previous ones. 

```
for (auto n : cr->notes()) 
{
	if (n->string() == last->string()) 
	{
		Glissando* s = new Glissando(score);
		s->setAnchor(Spanner::Anchor::NOTE);
		s->setStartElement(n);
		s->setTick(seg->tick());
		s->setTrack(chord->track());
		s->setParent(n);
		s->setGlissandoType(GlissandoType::STRAIGHT);
		s->setEndElement(last);
		s->setTick2(chord->segment()->tick());
		s->setTrack2(chord->track());
		score->addElement(s);
		if (slide == 2 || effect == SLIDE_OUT_UP) 
		{
			if (!lastSlurAdd) 
			{
				createSlur(true, chord->staffIdx(), cr);
				createSlur(false, chord->staffIdx(), chord);
			}
		}
	}
	br = true;
	break;
}
```

**Comment by anatoly-os** [comment]
@Jojo-Schmitz could you please squash commits related to warnings and keep one separate commit related to (/MP + lrelease step)?

**Comment by Jojo-Schmitz** [comment]
rebased and squashed

**Comment by mattmcclinch** [comment]
Judging by the indentation alone, it looks like there should be a `{` at the end of line 1022, and a `}`  between lines 1051 and 1052. And I suspect that lines 1043 and 1044 should move up 1 level so that they are at the end of the `if` clause that begins on line 1024.

**Comment by Jojo-Schmitz** [comment]
Adding those braces don't fix the warnings.

**Comment by Jojo-Schmitz** [comment]
Adding those braces don't fix the warnings.
Moving those 2 lines up though does fix that ine warning.

**Comment by mattmcclinch** [comment]
It is a little difficult to tell without an actual gp4 file to use for testing, but it looks like lines 1097-1111 should be moved up to line 1094.

**Comment by Jojo-Schmitz** [comment]
There should be gp4 files in mtest

**Comment by Jojo-Schmitz** [comment]
Maybe better comment in the new and open PR #3869

**Pull request merged**
