### PR TITLE
fix #62276: Viola da gamba in 2.0 missing channels

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by lasconic** [comment]
@mgavioli What about Violone and friends? worth adding pizz and tremolo too?

**Comment by Jojo-Schmitz** [comment]
@mgavioli  Also what about the request to have a 7-string Viola da gamba?

**Comment by Jojo-Schmitz** [comment]
I've added pizzicato and tremolo to the other early musing strings now too

**Comment by Jojo-Schmitz** [comment]
@lasconic while at it: shouldn't those channel names also get translated? Maybe not needed so much for "pizzicato", "tremolo", "arco" (won't harm though), but for "mute" and the ones for Synthesizers? See https://musescore.org/en/node/57461

**Comment by lasconic** [comment]
As far as they don't end up translated in MSCZ files, feel free to make another pull request.

**Comment by Jojo-Schmitz** [comment]
I guess this is something needed in generateTs.py, but I don't speak Python...

**Comment by lasconic** [comment]
That's the easy part. I can extract the channel name with python. The other part is too make sure we translate them only for the UI. So assume they are extracted, it adds something like the following in `instrumentsxml.h`. Can you pinpoint where we should use translate() in the code?
```
QT_TRANSLATE_NOOP("InstrumentsXML", "pizzicato"),
QT_TRANSLATE_NOOP("InstrumentsXML", "tremolo"),
```

**Comment by Jojo-Schmitz** [comment]
OK, see PR #2021 ...

**Comment by mgavioli** [comment]
Hmmm... my personal opinion is that those addition would be harmless, but of little relevance: tremolo is unheard of for VdG and pizzicato, while occasionally used by some players in some passages for "fun", is never asked for in the literature.

So, if it is handy for symmetry with other instruments, ok, but I doubt anybody would miss them with the current setup.

**Comment by mgavioli** [comment]
I forgot:

@lasconic : same as above for violone "and friends".

@Jojo-Schmitz : as far as I remember, the currently implemented (bass) VdG is the 7-string version. During development, I originally made the distinction in `instruments.xml` but, after some comments, I realized it was an excess of detail from my part: the two versions are operatively exactly the same, except for the extra string: anything which can be done on the 6-string, can be done in exactly the same way on the 7-string.

**Comment by Jojo-Schmitz** [comment]
@mgavioli: mind to add that to the issues https://musescore.org/en/node/62276 and https://musescore.org/en/node/62321 ?

**Pull request merged**
