### PR TITLE
[MU4] Fixed tx2s3 workflow

### PR DESCRIPTION
**Pull request by igorkorsukov**
Fixed tx2s3 workflow

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Strange that fixing something on master will work for updating translations for 3.x... but parently it does!

**Comment by Jojo-Schmitz** [comment]
Hmm, no, it apparently does not, it does not grab recently updated translations from Tnasifex and does not makes them available to the tranmslations updater in MuseScore

**Comment by igorkorsukov** [comment]
> Strange that fixing something on master will work for updating translations for 3.x... but apparently it does!

scheduled workflows run only in the master, 
so tx2s3 workflow runs in the master, checkout on 3.x branch and run scripts from the 3.x branch. 
(same work nightly builds for 3.x)

**Comment by igorkorsukov** [comment]
> Hmm, no, it apparently does not, it does not grab recently updated translations from Tansifex and/or does not make them available to the translations updater in MuseScore, not for 3.5.2, 3.6.0 Beta nor the laetest self built

Now tx2s3 uploading to 3.6 version, but URL for 3.5 version in the source code. Vasiliy fixed it. But I don't know what url for you. 
Anyway, we'll figure it out tomorrow

**Comment by Jojo-Schmitz** [comment]
Ah, I see, resourcemanager.h still uses 3.5: `static inline QString baseAddr() { return "http://extensions.musescore.org/3.6/"; }`

**Comment by Jojo-Schmitz** [comment]
But not even when fixing that it finds updated translations...

**Pull request merged**
