### PR TITLE
Add button to move soundfont to top

### PR DESCRIPTION
**Pull request by barafael**
This branch adds a button to the soundfont selector (View -> Synthesizer -> Fluid tab). The button moves the currently selected item to the top, changing the playback soundfont.

Previously, one had to repeatedly click the "Move soundfont up" button.

Note: This is affected by issue #276456, which I created. I verified that the issue persists without my changes.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
* That merge commit shouldn't be there
* Please include "Fix #276456: " in the commit title (and also in the PR title), so that issue automagically closed when this PR gets merged. Hmm, hold onl that one got fixed last December already?!
* Did you sign the [CLA](https://musescore.org/cla) or are you [rafaelement](https://musescore.org/en/user/31589) there?

**Comment by anatoly-os** [comment]
@Jojo-Schmitz regarding CLA, see https://github.com/musescore/MuseScore/pull/3983

@barafael you need to `git rebase master` instead of merging with the `master` branch. Could you please delete the merge commit and rebase the changes on top of the master branch? Or create new PR with your changes only?

**Comment by Howard-C** [comment]
Haven't heard from the author of this PR for over a month? In this case according to the PR merge process shouldn't this be closed? (but this is still a very useful suggestion)

**Comment by Jojo-Schmitz** [comment]
It'd indeed be a pity to loose this, it could still get cherry-picked

**Comment by anatoly-os** [comment]
See https://github.com/musescore/MuseScore/pull/5429

**Pull request closed without merging**
