### PR TITLE
fix GH#8937 and #8938: inspector setting for tremolo doesn't appear

### LINKED ISSUE #8937: [Inspector] tremolo marks are being given the name 'tremolo bar' in the inspector
Reproduce:

1. Place a note on the score
2. Put a tremolo mark on it (see image) 
image
3. Select the tremolo mark and observe the name 'Tremolo bar' in the inspector. It should just be called 'Tremolo'

### LINKED ISSUE #8938: [Inspector] Between-note tremolo options not yet implemented
**Describe the bug**
Options do not appear for between note tremolo in MS4 (as they do in MS3)

See video: https://www.dropbox.com/s/f4733beiew5wjhp/01_Between_Note_Tremolo.mov?dl=0

### PR DESCRIPTION
**Pull request by Howard-C**
Fixes #8937 and fixes #8938.

The second commit is for a different issue (that has been kind of brought up in the linked issues as well). Not sure whether this kind of hack can be allowed or I can do it better in another way.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Resolves #8937 and #8938

**Comment by Howard-C** [comment]
The second commit is for a different issue (that has been kind of brought up in the linked issues as well). Not sure whether this kind of hack can be allowed or I can do it better in another way.

**Comment by RomanPudashkin** [comment]
Thanks for your fix! I like the first fix, but I am afraid that the second one isn't solid enough. I've cherry-picked your first commit and I have plans to merge it to the master branch:
https://github.com/musescore/MuseScore/pull/9064

I'll investigate the second issue later, maybe I can find some alternative solution

**Comment by Howard-C** [comment]
@RomanPudashkin I see, let me now when you've found a more elegant solution!

**Comment by Howard-C** [comment]
Since this one already has conflicts, I'll close it for now.

**Pull request closed without merging**
