### PR TITLE
fix #275313: rework mixer ui 2

### PR DESCRIPTION
**Pull request by blackears**
This is a replacement for https://github.com/musescore/MuseScore/pull/3898 after my local repo got toasted after trying to revert a few things.

### CODE REVIEW

**Comment by blackears** [comment]
I've changed volume and pan back to being chars.  Too hard to integrate the change into Travis.

Continuing on from the last thread:

4. What is being displayed is part name, not the instrument name.   If the user should change the part name it will be displayed there.   The instrument name shows up in the tooltip.  Should I show the instrument name instead?

8. I might need to redesign for this.  The problem here is what exactly a 'track' is.  The Channels co-respond most naturally to tracks.  At the moment, parts are also being displayed as tracks even though they're not really tracks.  They're just a convenient way to group a bunch of Channels together.  A master track would be a new sort of track.

We could turn Parts into true tracks by adding volume and pan settings to them. Then the Channels could be mixed by multiplying their volume by the Part's volume.  If you want to make this system work like tracks in a DAW, each track needs to have its own output which is then mixed into the master.  The current mixer isn't really a mixer because it does not separate audio like this.  It's more a way of adjusting MIDI parameters for channels with a mixer look-and-feel.

**Comment by anatoly-os** [comment]
@blackears I've merged the piano roll PR. We need the same dark/light theme approach to be implemented for Mixer UI

**Comment by anatoly-os** [comment]
@blackears I reviewed the code and played with mixer a bit. First of all, big thank you for code refactoring and doing incredible amount of work! Your code is easy to read which is good.
There are few notes of what I see can be improved:

1. Default value for Pan is 1.4 which is weird, I would expect 0.0.
2. Default value for Volume is 78.7. Again, it looks very strange. I would use db values or even percentage. Default value should be somehow marked on the slider or have clear value like 100%.
3. Master gain doesn't have its own details, it means it is not possible to specify default volume with a number. Again, additional "sticky" mark on the slider would be very useful.
4. MuseScore crashes if I check "Drumkit" checkbox on Grand Piano. The crash happens at mixerdetails.cpp:442. I would disable the checkbox for the instruments which cannot be used as drum set.
5. Reverb/Chorus controls are broken. It is not possible to change the value neither with mouse nor with numbers. Looks like each mouseMove sets default 50.4 value. Again, why 50.4, but not 50?

These are major issues should be addressed. After that, we can merge it to master.

**Comment by blackears** [comment]
Some of those strange numbers are a result of converting between an integer based range and a decimal based one.  Mapping a 0 - 127 int range onto a -180 to 180 double one is going to have alignment issues, especially given that pan's 'zero' is actually 64.  I tried to fix this earlier by switching to double based values for these internally, but I eventually had to rollback those changes because of the file format freeze.

At the moment, I cannot run MuseScore due to https://musescore.org/en/node/277686.  I won't be able to address the above until I can get it running again.

Regarding #4, do we really need the drumkit checkbox at all?  It might be easier to just remove it, or maybe just have a label that is read only.

**Comment by Jojo-Schmitz** [comment]
@blackears: I can't reproduce the issue you describe in  https://musescore.org/en/node/277686. But then again maybe it is time for you to switch to MSVC?

**Comment by anatoly-os** [comment]
@blackears last thing is master gain number which looks really strange. Minus looks like underline or numbers are too small there. Once you fix it, I'll tend to merge the PR.

screenshot 2018-11-13 at 16 37 05

**Comment by Jojo-Schmitz** [comment]
This PR introduced a couple new compiler warnings with MSVC and MinGW. Dealt with in PR #4136

**Pull request merged**
