### PR TITLE
GSoC 2018: Score comparison tool

### PR DESCRIPTION
**Pull request by dmitrio95**
This pull request includes the second part of my GSoC work and contains an implementation of a score comparison engine and a score comparison tool itself. The branch proposed in this pull request is based on the branch represented in [this pull request](https://github.com/musescore/MuseScore/pull/3760) so it doesn't seem to make sense to merge it before that one. Still this pull request may be useful for reviewing the second part of my work. After merging the first pull request this one can be rebased to master.

A brief description of the score comparison tool is available [here](https://musescore.org/en/node/274180#comment-848252). Apart from that, this pull request adds also command-line options to MuseScore for obtaining raw or processed ("intelligent") diff for the given scores.

The score comparison engine code is currently located at `libmscore/scorediff.cpp` and needs a textual diff library for it to work. Currently `diff_match_patch` library found in MuseScore's `thirdparty` section of source code is used. That is, a dependency on the textual diff library have been added for `libmscore`. If this is undesirable feel free to ask me to remove the engine's code from `libmscore`.

### CODE REVIEW

**Comment by anatoly-os** [comment]
I tested it a bit and already found 4 crashes and 8 suggestion for an improvement. I will share the list with you tomorrow. Btw, could you please rebase the PR?

**Comment by anatoly-os** [comment]
Remaining issues overview.

1. When comparing with last saved version, but there are no last saved versions (just opened file):
screencast 2018-10-22 16-43-44
2. Comparing happens open fly with "last saved version", but UI shows comparing similar files with "Schubert" title:

3. Closing all scores and pressing "Compare" leads to crash

**Comment by dmitrio95** [comment]
There is also the related licensing issue with `diff_match_patch` (see [this letter](https://sourceforge.net/p/mscore/mailman/message/36428618/)).

Concerning the mentioned issues:
1) This is really a bug, I'll fix it.
2) This behavior is probably not the best one but still it is not clear which is the best option here. The intention was that user should be able to select scores to compare both via dropdown lists in the tool itself and via switching currently viewed score. Scores that are actually compared are listed just above the comparison itself. Though the behavior can be really somewhat misleading. Will it be better to lock dropdown lists until the comparison is cancelled? Or are there some other options here?
3) I cannot currently reproduce it, and I thought I fixed this issue on Saturday. Are you using the latest version of my `scorecmp_tool` branch?

**Comment by dmitrio95** [comment]
Fixed some issues, rebased to the current master.

**Pull request merged**
