### PR TITLE
Fix asking before closing First launch setup dialog

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #10835

### CODE REVIEW

**Comment by Eism** [comment]
@cbjeukendrup you broke the navigation on app menu. Linux/Windows
1. go by keyboard navigation to File->Open recent(Alt+F, down arrow)
2. press right arrow(or space)
3. press left arrow(or Esc)

After closing the submenu (Open recent), the menu should not be closed (File menu)

Before

https://user-images.githubusercontent.com/10116828/159238038-1fb0c5ef-8f78-43e5-be97-2820fef8307a.mp4

After

https://user-images.githubusercontent.com/10116828/159238072-bc1e53fe-e2da-4baf-ae9d-2bd32ea58963.mp4

**Comment by cbjeukendrup** [comment]
@Eism I tried to reproduce on Windows 11 ARM (Parallels, M1 Mac), but couldn't; it seems to work fine. Unfortunately, I cannot check on Linux nor on other versions of Windows. Not sure what I can do...

**Comment by Eism** [comment]
@cbjeukendrup 
Ok, I did some tests.
Indeed, the problem is that we are manually handling the close event. (Because of this, aboutToClose processing comes after close of dialog)
To solve the problem with the Getting started dialog, we just need to remove the handling of the close event. Tested cases that were the reason for adding handling the close evenе. Everything seems to be working as expected.
But it will need to be tested more thoroughly.

**Comment by cbjeukendrup** [comment]
@Eism Thanks for trying! I tested this on macOS and Windows, and on both systems it seems to work well. So, let's go for it :)

I also moved the other changes to a new PR (#10898), so that we can take time to test this thoroughly without holding up the other fixes.

**Review by Eism — APPROVED** [review]

**Comment by Eism** [comment]
@cbjeukendrup 
please make some changes and push them to activate build
some problems with GitHub Actions

**Comment by cbjeukendrup** [comment]
Done!

**Comment by DmitryArefiev** [comment]
Tested #10835 on Win10, LinuxMint 20.2 - **FIXED** 

@boryskuzmenko Please check on Mac. Thanks!

**Comment by boryskuzmenko** [comment]
https://github.com/musescore/MuseScore/issues/10835 bugfix verified
OS: macOS 12.0.1
**FIXED**

**Pull request merged**
