### PR TITLE
Add Finale Maestro and Finale Broadway fonts

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #12001

At a first glance, I see no problems with these fonts.

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Tantacrul** [comment]
@oktophonie - we have a little task for you! :)

**Comment by Tantacrul** [comment]
I've noticed that the ottava marks are fine for Broadway but not for Maestro (at least, I doubt Maestro is meant to look like this...)

 **Broadway** 
image

**Maestro**
image

**Comment by cbjeukendrup** [comment]
That '8' seems to be a Maestro Text problem. I believe we are using the "Text" variant of the font in that place, but Maestro Text does not contain the ottava symbols, also not that '8' which should be at U+E510. However, at U+E888 I seem to recognize that small 8 that I see in your example. And I suspect that the '15' is from either Leland or Bravura (whichever is used as a fallback).

**Comment by Tantacrul** [comment]
Thought so. Perhaps I can modify Maestro text for now (until they fix it themselves)?

**Comment by cbjeukendrup** [comment]
> 2\. I don't think we use the text fonts for 8ve markings - mainly because I never added them to LelandText.

We really are. That would mean that ottava markings fall back to Bravura, and that seems to be the case...

**Comment by Tantacrul** [comment]
Got it. Thanks!

**Pull request merged**
