### PR TITLE
fix #210116: Delete all and Undo duplicates the clef

### PR DESCRIPTION
**Pull request by mattmcclinch**
See [210116: Delete all and Undo duplicates the clef](https://musescore.org/en/node/210116).

### CODE REVIEW

**Comment by anatoly-os** [comment]
@wschweer could you please review?

**Comment by mattmcclinch** [comment]
I replaced more occurrences of Measure::add() and Segment::add() with Score::undoAddElement(). I could produce the same error after trying to delete a courtesy key signature, and I got warnings after trying to delete bar lines.

**Comment by wschweer** [comment]
It should not be possible to delete a generated element. For the system header the clef segment should not be deleted if empty but set  disabled. It will be reenabled later by layout when generating a new clef. So no undo/redo record is necessary for the clef segment. This also avoids confusion on undo. 
I have another patch which tries to address this and at least fixes the clef problem.

**Comment by Jojo-Schmitz** [comment]
So this pr could be closed, right?

**Comment by mattmcclinch** [comment]
@wschweer, thank you for your comments. I have tested your solution, and I would like to make the following notes.

1. Since it is possible for an element to lose its “generated” status, it is still possible to delete an element that was originally generated automatically, by first making it invisible (for example). Perhaps it would be helpful to add a “modified” flag, and keep generated elements “generated”. That way, it would be impossible to delete a required element, even if it was modified after being generated.

2. In `Score::undoRemoveElement()` in libmscore/edit.cpp, when deciding whether the segment should be disabled or removed, perhaps a better test would be
```if (s->header() || s->trailer())```
instead of
```if (s->isHeaderClefType())```.
I can still cause a crash related to this issue, but this change seems to fix it.

**Comment by wschweer** [comment]
I changed undoRemoveElement() as you suggested.

**Pull request closed without merging**
