### PR TITLE
fix #313420 [MusicXML] Instrument brackets are all imported at column 0

### PR DESCRIPTION
**Pull request by AntonioBL**
Resolves: https://musescore.org/en/node/313420

System bracket implementation was changed between MuseScore 2.x and 3.x, but it was never updated in the MusicXML import.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by AntonioBL** [comment]
There was a problem with Create_New_Score.mscz during rebase.
I will try to amend it.

**Comment by AntonioBL** [comment]
Now the rebase conflict is solved.
That mscz file messed a little with the git history of my branch.

**Comment by Jojo-Schmitz** [comment]
Blame it on @njvdberg ;-)

**Comment by njvdberg** [comment]
> Blame it on @njvdberg ;-)

I just opened a new packet with brown bags, shall I one or two for myself? :wink:

**Pull request merged**
