### PR TITLE
Trivial musicxml fixes master

### PR DESCRIPTION
**Pull request by lvinken**
Resolves:
https://musescore.org/en/node/305313
https://musescore.org/en/node/306725

Low risk small fixes improving MusicXML import/export

This is the equivalent of [#6256](https://github.com/musescore/MuseScore/pull/6256) which was recently merged. I am assuming there will be no automatic sync (which would probably fail anyway due to the reformatting applied to master).

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/WorkflowAndGuidelines/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by anatoly-os** [comment]
@lvinken ping :)

**Comment by lvinken** [comment]
Had lost sight of this one. Rebased.

**Comment by lvinken** [comment]
Codestyle fails on mscore/scoreview.cpp, which I did not touch ...

**Comment by Jojo-Schmitz** [comment]
Code style fixed by #6438

**Pull request merged**
