### PR TITLE
fix #286679:  Piano keyboard display does not update when adding accidental using toolbar or palette

### PR DESCRIPTION
**Pull request by Gac70**

### CODE REVIEW

**Comment by jthistle** [comment]
Hi! Congrats on your first MuseScore pull request. A couple of things:

Have you signed [the CLA](https://musescore.org/cla)? Under what name?

Also, can you please change your commit's title to the name of the issue, or something related to it? That would be more useful than how you solved it :)

e. g. fix #286679: Piano keybaord display does not update when adding accidental using toolbar or palette

Other than that, if this changes works, the code looks good to me.

**Comment by Gac70** [comment]
Hi,I have signed the CLA under the name vagelisbilios1.

**Comment by jthistle** [comment]
Great. Can you change the actual commit message instead of the PR title, please? If you're not sure how to do that, please say.

**Comment by Gac70** [comment]
I have already changed the actual commit message. This is how the git log looks like :)

commit c03c5d6f20ed8710c84837babb24ad095dd4ef48 (HEAD -> 286679-pkeyboardnotdisplayaccidendals)
Author: Gax70 <vagelisbilios@gmail.com>
Date:   Tue Apr 2 22:14:23 2019 +0300

    fix #286679: Piano keyboard display does not update when adding accidental using toolbar or palette

**Comment by Jojo-Schmitz** [comment]
Well, the commit message is: "fix #286679: setSelectionChanged seems to solve the problem" but the PR title seems more suitable to also serve as the commit title: "fix #286679: Piano keyboard display does not update when adding accidental using toolbar or palette"

**Comment by Jojo-Schmitz** [comment]
I guess the commit SHA here, c00ecf0 and on your machine, c03c5d6 don't really match, guess you'd need a `git push -f`

**Comment by Gac70** [comment]
Thank you for the remark.I did what you mention.Let me know if the problem has been fixed know.

**Comment by Jojo-Schmitz** [comment]
Hmm, now you have a foreign commit in the PR

**Comment by Gac70** [comment]
I tried once again.Hopefully it works know.

**Comment by Gac70** [comment]
I tried once again.Hopefully it works now.

**Comment by Jojo-Schmitz** [comment]
Seems so

**Pull request merged**
