### PR TITLE
46861 melisma

### PR DESCRIPTION
**Pull request by lvinken**
On popular request: add support for melisma (lyric extend) in MusicXML import (export already done).

### CODE REVIEW

**Comment by lvinken** [comment]
As happened many times before, Travis runs for a long time and then fails with an apparently unrelated error ("./gen: 97: ./gen: rekonq: not found") ...
:-(

**Comment by lasconic** [comment]
Ok I will remove this line because apparently it's confusing.
`./gen: rekonq: not found` is not an error, it's just a warning that the rekonq browser is not available while the vtest script is trying to open the resulting HTML file in it...

The actual failure is in tst_xml_io here 
https://travis-ci.org/musescore/MuseScore/builds/77119474#L4336

**Comment by lvinken** [comment]
Could you send me the diff output ? Currently I only know the diff fails, which it doesn't when I run the test.

**Comment by lasconic** [comment]
There is no diff. The diff is comparing with _ref.xml file and this file is missing. You probably forgot to push it to git.

**Comment by lvinken** [comment]
Oops, my mistake, sorry about that. Pushed again with file added.

**Comment by lasconic** [comment]
No pb. if the tests pass, can you squash the 4 commits into a single one with commit message 
"Fix #46861: [MusicXML] Add support for melisma in import and export" ? thanks
Instructions to squash http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by lvinken** [comment]
Do you mean "squash and push again" ? Or make a new pull request (possibly from a fresh branch) ?

**Comment by lvinken** [comment]
Made a new pull request (46861-melisma-2), closing this one.

**Pull request closed without merging**
