### PR TITLE
cloud_scores_offline_mode

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/22081

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
I found a regression. Steps to reproduce:
1. Connect to the internet
2. Open Home > My online scores and let the list load
3. Disconnect your internet
4. Click one of the cloud scores; especially one that has never been opened yet on your computer so hasn't been downloaded locally

Result in 4.2.1:
Scherm­afbeelding 2024-04-18 om 13 00 09

Result in this PR:
Scherm­afbeelding 2024-04-18 om 13 17 55

Also, in this PR, if you disconnect from the internet and open a cloud score that _has_ been download to the computer earlier, then the filename is missing:
Scherm­afbeelding 2024-04-18 om 13 22 34

**Comment by cbjeukendrup** [comment]
Also, there is still one situation where the user may lose data:
1. On computer A, upload a cloud score.
2. Disconnect computer A from the internet.
3. On computer B, open the same cloud score and make changes to it and re-upload it. It gets a new revision ID on MuseScore.com. 
4. On Computer A, also make changes to this score (i.e. starting from the original version, not yet modified by computer B), but these can only be saved locally, because there is no internet connection. Do that and close the score.
5. Reconnect computer A to the internet.
6. Reopen the score on computer A. Now, the revision ID is different from .com (because on .com it was modified by computer B), so on computer A MuseScore downloads the latest version from .com. This means that the local changes made on computer A are lost. 

We don't have the technology yet to merge the changes made on computer A with those made on computer B, but we should warn the user in this case, and give them the choice whether they want to open the version with the local changes from computer A or the version from .com.

How can we detect this case? @shoogle had some ideas about that. The idea is that a score should not only store its revision ID, but also a `hasLocalChanges` field. This lets us handle all cases correctly:
- Local revision ID matches online revision ID $\to$ just open the local version
- revision IDs mismatch and `hasLocalChanges` is `false` $\to$ just open the online version
- revision IDs mismatch and `hasLocalChanges` is `true` $\to$ there's a conflict. 
   - For now: ask the user which version they want to be opened. 
   - In the future: give the user the option to see both versions and compare them manually. 
   - In the further future: merge the changes automatically where possible, and create a way for the user to manually merge the changes where that can't be done automatically.

Whenever the upload succeeds, we set `hasLocalChanges` to `false`, and whenever a score is saved without successfully uploading, we set it to `true`.

**Comment by cbjeukendrup** [comment]
Oh, sorry, I wish I had seen that earlier

**Comment by RomanPudashkin** [comment]
>I found a regression
>the filename is missing

Thanks, these both should be fixed now (1st commit)

**Review by cbjeukendrup — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #22081 on Win10, Mac13.6, LinuxUbuntu22.04 - **FIXED**

**Pull request merged**
