### PR TITLE
Dropped in QT 5.9 file for gd locale

### PR DESCRIPTION
**Pull request by gunchleoc**
In the gd locale, the translations for the "Pervious", "Next" buttons etc are not being fetched from QT, so I hope adding this file will fix it. I don't know if we're still on QT 5.4 for the nightly builds - the gd locale is only available for QT starting from QT 5.6, because 5.4 translations were already End of Life when we first added the locale to MuseScore.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
The master branch is on Qt 5.9 (or later), 2.x branches are on 5.4, and at least for Windows need to stay there. Whether or not that locale file works in 2.2 (i.e. with Qt 5.4) needs to be determined.

**Comment by Jojo-Schmitz** [comment]
For master make sure to get your file added to the next versions of Qt, like 5.9.5, 5.10.x and 5.11, you'd need to get in touch with Qt development for that. For master we rely on whatever Qt provides, if they provide. Until that happens we can take this file you provided, I guess.

But there's a mismatch between the filename (ending in `_gd`) and the content (claiming locale to be `gd_GB`, shouldn't that get fixed`?

**Comment by Jojo-Schmitz** [comment]
The master branch is on Qt 5.9 (or later) and there the Qt translations are fetched automagicalle, 2.x branches are on 5.4, and at least for Windows need to stay there. Whether or not that locale file works in 2.2 (i.e. with Qt 5.4) needs to be determined.

For master make sure to get your file added to the next versions of Qt, like 5.9.5, 5.10.x and 5.11, you'd need to get in touch with Qt development for that. For master we rely on whatever Qt provides, if they provide. Until that happens we can take this file you provided, I guess.

But there's a mismatch between the filename (ending in `_gd`) and the content (claiming locale to be `gd_GB`, shouldn't that get fixed`?

**Comment by Jojo-Schmitz** [comment]
And a very minor issue: it is Qt, not QT, the latter stands for Quick Time...

**Comment by gunchleoc** [comment]
I am already contributing everything to QT, that's where I got the file from.

We usually use gd as a locale, but some programs use gd_GB instead for some reason. So, maybe that needs fixing.

Alternatively, I could create a translation of legacy QT for the branches, if you could point me at an English source file.

Which branch are the nightlies built off if? Because the QT translation is missing in the current nightly.

**Comment by Jojo-Schmitz** [comment]
There are currently development builds for 2.2 and master

**Comment by gunchleoc** [comment]
I downloaded MuseScoreNightly-2018-03-13-0959-master-c08fe0d, so that's from Master. I have been translating qt_base since QT version 5.6, so it's strange that the translation isn't fetched. Maybe it's throwing a fit at the gd/gd_GB thing? Just guessing here.

**Comment by Jojo-Schmitz** [comment]
What do you mean by _the translation isn't fetched_, it is not fetched by the resource manager when updating translations? Of course not, the qt_gd files are not added yet, but when you manually copy then next to the mscore and instruments translations files, on next start of MuseScore should see them taking effect

**Comment by gunchleoc** [comment]
I mean if I download a nightly build (either 2.2 or master) and run the *nightly.exe* files, some buttons are in English. So, this is what the user will get on release, which is not good - see screenshot of the "New Score" dialog below. Button translations should be provided by QT, but they aren't.

If you check the official QT localizations, *qt_base* (where those button texts are translated as far as I know) has had those buttons translated since version 5.6. So, I am assuming that

* **2.x branches:** QT 5.4 doesn't have any official translations yet, so I'll need to provide those somehow - I don't know where to get an English master file though

* **Master branch:** QT provides official translations, but they're not there anyway. I am not familiar with the MuseScore codebase, so I have no idea why. So, I hoped that adding the file manually might fix it.

qt_buttons

**Comment by Jojo-Schmitz** [comment]
Your file is not part of MuseScore 2.2 yet, so they are not in 2.2 builds (the 2.x branches don't check for what Qt provides, a corresponding change had been reverted). It is not part of Qt 5.9.4, and not part of MuseScore master, so that's why you don't see the translations there either. If it once was part of Qt 5.6, they must have been removed by the Qt folks somewhen before Qt 5.9. I have not checked whether it is part of Qt 5.10.1 or 5.11beta.
Ti test your file, yu'd need to drop the qt_dg_qm file, generated form your qt_gd_ts file usong the lrelease tool from Qt and dropt to where the musescore installation stores its *.qm files, and restart MuseScore

**Comment by Jojo-Schmitz** [comment]
Alternatively date the qm file from the artifacts the AppVeyor build generates

**Comment by Jojo-Schmitz** [comment]
I'd vote for merging this PR, but please fix that `gd_GB`  to just `gd` first, even if only for consistency

**Comment by gunchleoc** [comment]
OK. I have also filed a bug with QT - let's wee what they say https://bugreports.qt.io/browse/QTBUG-67060

I'm currently waiting for a reinstall of QT so I can create a qm file - just to make sure it's working.

**Comment by Jojo-Schmitz** [comment]
Ah! `qtbase_gd` indeed is in 5.6 (irrelevand for MuseScore) and 5.9, but no plain `qt_gd`, as for all other languages, for most that is just sort of a wrapper referencing various other `qt*_* files`. So wither renamed qtbase_dg ro just qt, of provide such a wrapper file.

**Comment by Jojo-Schmitz** [comment]
For the master branch that wrapper file should be enough already, to pick up the translation from Qt.

But there sees to be a bug with that currently, I suspect since the removal of mingw32.mingw.cmake, @lasconic? ...share/locale/CMakeLists.txt should copy from CROSSQT/translations, bit that variable is not set anywhere anymore?

**Comment by gunchleoc** [comment]
Alternatively, we could shift the Transifex translation project from gd to gd_GB?

Anyway, I have tested the .qm off the AppVeyor now and it woks with either name. So, I have renamed it as requested. I'll be happy to have this pull request sitting here until we decide what to do.

I take it that we still need a QT version 5.4 translation for the current release branch (2.2)? I could try dropping my 5.6 translation there, all I really care about are the buttons. Users don't really care about regex parsing error messages that much...

**Comment by Jojo-Schmitz** [comment]
No, please leave the filename as gd and change the content to be consistent

**Comment by gunchleoc** [comment]
> No, please leave the filename as gd

Will do

> and change the content to be consistent

I don't understand what you mean

**Comment by Jojo-Schmitz** [comment]
Try that file with a 2.2 build and see whether it works there

**Comment by Jojo-Schmitz** [comment]
Change the content of the ts file from `gd_GB` to just `gd`

**Comment by Jojo-Schmitz** [comment]
Actually, as mentioned, we most probably want that file only for 2.2, and that wrapper file for master, but let me try to fix the apparently broken mechanism in master first

**Comment by Jojo-Schmitz** [comment]
Well, that is just a rename without any change

**Comment by gunchleoc** [comment]
I have fixed the file just in case - it will give me a baseline for the 2.2 version in any case. I have run out of time for now, I'll try to create a new PR by 2.2 tomorrow.

**Comment by gunchleoc** [comment]
Sorry, forgot to stage.

**Comment by Jojo-Schmitz** [comment]
OK, I've just verified now, that my PR #3540 plus that wrapper file mentioned above does fix the translations issue for gd (and lv). So for master nothing more is needed, so your qt_gd.ts file from this PR here is only needed for the 2.2 branch, this PR here is not needed at all anymore.
Please verify using the AppVeyor aritfact from my PR

**Comment by Jojo-Schmitz** [comment]
For testing you could use the build at https://ci.appveyor.com/project/MuseScore/musescore/build/1.0.712/artifacts

**Comment by lasconic** [comment]
Should be fixed in 2.2 now too.

**Pull request closed without merging**
