### PR TITLE
Update Guitar and Trombone Orders

### PR DESCRIPTION
**Pull request by zacjansheski**
Possibly fixes
https://github.com/musescore/MuseScore/issues/21742 https://github.com/musescore/MuseScore/issues/21670

Change order in spreadsheet and run python script

### CODE REVIEW

**Comment by shoogle** [comment]
The order of instruments in the spreadsheet is determined automatically based on formulas. Instruments shouldn't be reordered manually, but we can change the data that is used to determine the automatic order.

One factor considered by the formula is the instrument's minimum professional pitch. Higher pitched instruments go above lower pitched instruments, which is how you would expect to find them in the score.

Here's the current pitch data for the instruments concerned:

Instrument | Minimum professional pitch in MuseScore
:---|:---
Cavaquinho |  D4 (MIDI 62)
Acoustic Guitar | D2 (MIDI 40)
Contrabass Trombone | E1 (MIDI 28)
Bass Trombone | D♯1 (MIDI 27)

According to this data, the instruments were ordered correctly before. However, I'm suspicious of the trombone data.

These links put the minimum pitches at [Bb0](https://www.vsl.info/en/academy/brass/bass-trombone#range) or [A0](https://en.wikipedia.org/wiki/Bass_trombone#Range) for the Bass Trombone, and [Ab0](https://www.vsl.info/en/academy/brass/contrabass-trombone) for the Contrabass Trombone, which would make the Contrabass lower, so it would appear below the Bass. I've edit the spreadsheet to use these values for now. (@oktophonie, what do you think of them?)

Assuming the data for the guitars is correct, the Cavaquinho is indeed higher pitched than the acoustic guitar, so I've moved it back to where it was before. Unfortunately, this means we'll need to find an alternative solution for the MusicXML problem.

**Comment by Jojo-Schmitz** [comment]
As mentioned in https://github.com/musescore/MuseScore/issues/21742#issuecomment-1970832924, the order (alone) didn't matter in Mu3.

**Comment by shoogle** [comment]
> Why then are Bouzoukis after Guitars?

Answered in https://github.com/musescore/MuseScore/issues/21742#issuecomment-1978875807

@zacjansheski, please rerun the Python script and update the PR to get the new trombone data. You can ignore the MusicXML issue with guitars since that needs to be fixed in the code rather than the instrument data.

**Comment by Jojo-Schmitz** [comment]
And the amateur picthes of trombones remain unchanged?

**Comment by shoogle** [comment]
@oktophonie, what do you think of these pitch ranges from the [instruments spreadsheet](https://docs.google.com/spreadsheets/d/1SwqZb8lq5rfv5regPSA10drWjUAoi65EuMoYtG-4k5s/edit#gid=516529997)?

image

The minimum professional pitch (**minP**) was taken from:

- **Bass trombone:** [This page](https://www.vsl.info/en/academy/brass/bass-trombone#range) suggests Bb0, but [Wikipedia says](https://en.wikipedia.org/wiki/Bass_trombone#Range) that A0 is possible if both slides are extended.

- **Contrabass trombone:** [This page](https://www.vsl.info/en/academy/brass/contrabass-trombone) suggests Ab0 (i.e. G#0).

We haven't changed the maximum (**maxP**) or the amateur ranges, but let us know if you have a recommendation for those.

**Comment by Jojo-Schmitz** [comment]
"The bass trombone's fingering is particularly challenging, because the fundamental pitch can be lowered from Bb1 to F1 by means of a fourth-valve and, depending on the instrument, to Eb1 or D1.", so I'd say the former is amateur, the later professional?
And highest is F5 for either? (and Ab0 to C3 for contrabass trombone, both ranges)?

**Comment by shoogle** [comment]
Let's wait for Simon to respond. He may know or have a text book with the answer. The rest of us would just be guessing.

**Review by oktophonie — APPROVED** [review]

**Comment by shoogle** [comment]
Lowering the bass & contrabass trombone pitches put them both below the Cimbasso, which has a similar standard range to the contrabass trombone but doesn't have access to the lowest pedal notes available on either of the trombones.

After a discussion with @oktophonie, I've moved the Cimbasso into a new `cimbassos` family, so it's no longer part of the `trombones` family. It appears below the trombones and will be bracketed separately with a thin bracket. It's still part of the `brass` group so will be within the same thick bracket.

I've also updated the pitch ranges of all three instruments. It turns out the ranges are pretty fluid, so it's kind of arbitrary where we draw the boundaries.

image

I've set the professional range to what is technically possible, though even many professionals would struggle to get that far. Hopefully users will realise that it's not a good idea to stray too far outside the amateur range when writing. In future, we might want to add a more fine-grained system for determining the ranges.

@zacjansheski, could you run the script one more time, rebase & squash your commits?

**Review by shoogle — APPROVED** [review]

**Pull request merged**
