### PR TITLE
fix #61041: allow staff spacers to decrease distance

### PR DESCRIPTION
**Pull request by MarcSabatella**
This implements a "negative staff spacer".  In this implementation, a single staff spacer down can either increase or decrease distance to the next staff/system - the size of the spacer controls the distance directly, rather than simply setting a minimum.  The old behavior is available via an Inspector option, currently labelled "Shrink distance" (and I'm definitely open to suggestions here).

Currently, we read/write spacers in two - well, three - different ways.  Spacer::read() and Spacer::write() are involved, apparently, when cloning the spacer from the palette; these use "Spacer" tags.  But normal score read/write doesn't use those methods, instead reading/writing "vspacerUp" and "vspacerDown" tags directly within Measure::read() and Measure::write().  "vspacer" tag is also supported on read, I guess for 1.3 scores?  My implementation keeps all that for compatibility but uses Spacer::read() and Spacer::write() normally, so that I can support a new "shrink" tag.

Using a spacer to set the distance between staves within a system, btw, is more likely to be problem-free than using one for setting distance between systems.  I've tested enough know the basic cases work, but it wouldn't surprise me to find cases where it doesn't.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
I should also reference the forum discussion where I proposed this solution:

https://musescore.org/en/node/71761

**Comment by Jojo-Schmitz** [comment]
How about naming the option 'Minimum distance' and revert the logic checked vs. unchecked?

**Comment by MarcSabatella** [comment]
Yes, I did originally play with wordings that way.  I kind of thought it would be harder to find a succinct way of describing the current behavior, which is really quite complex to describe fully, than to find a succinct way of describing the new behavior, which is quite simple to describe.  I'm not opposed to it, still would like to hear other suggestions.

BTW, I am working on a bug involving use of hide empty staves in conjunction with the new spacer behavior.  Hope to have a fix later today.

**Comment by MarcSabatella** [comment]
Fixed the issue I found with hide empty staves, which it turns out also affects regular spacers in 2.0 as well (spacer adds too much space in certain cases with hide empty staves).

Also changed the option name to "Absolute" for now.

**Comment by MarcSabatella** [comment]
Bad rebase, I guess.  I'll open a new PR.

**Pull request closed without merging**
