### PR TITLE
fixed #12589 and #11656: Don't drag objects with middle button

### LINKED ISSUE #12589: [MU4 Issue] Middle Click + Drag moves note even if mouse isn't over
**Describe the bug**
When a note is selected and middle click is dragged, even if the mouse isn't over the note/rest, it will drag it.

**To Reproduce**
1. Create a new score
2. Insert a new note
3. Select the note
4. Middle click and drag
5. See error

**Expected behavior**
The page moves

**Platform information**
 - OS: Windows 11

**Additional context**
Once, when middle clicking and dragging with a note selected, MuseScore crashed.

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #12589
Resolves: #11656

Was broken in #10147

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #12589 #11656 on Win10, Mac12, LinuxMint 22.04 - **FIXED**

**Comment by MarcSabatella** [comment]
Am I understanding this fix is not yet merged into any release branch?  It has come up as an accessibility issue on the forum.  Could it be considered for 4.0.2?

**Comment by DmitryArefiev** [comment]
@MarcSabatella How it's critical issue for accessibility? As I know the same happens in MS3

**Comment by MarcSabatella** [comment]
I didn't say it was "critical", but it was discussed on the forum by a user with limited mobility who needs to be able to perform actions with a single hand where possible.  The scroll wheel - his particular scroll wheel anyhow - requires two hands to move horizontally (one for the wheel, one to press Shift).  I did tell him about the scroll bars, but he is accustomed to middle button panning from other apps and would like to see it here.  For people with mobility issues, dragging may well be an easier / more reliable way.

**Pull request merged**
