### PR TITLE
[MU3] option for disabling zita reverb

### PR DESCRIPTION
**Pull request by RomanPudashkin**
- added an option for disabling zita reverb

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I guess this one is needed for 3.x (and master) too?

**Comment by RomanPudashkin** [comment]
>I guess this one is needed for 3.x (and master) too?

Probably it is needed for 3.x but not for master. There are several important fixes in 3.5.2_backend which are missed in 3.x and master

**Comment by Jojo-Schmitz** [comment]
> There are several important fixes in 3.5.2_backend which are missed in 3.x and master
None that I'd be aware of?

**Comment by Jojo-Schmitz** [comment]
Oh, I see, 3ae1d4125, 9c2a429b, 701bacaa36, faa5f997

**Comment by RomanPudashkin** [comment]
https://github.com/musescore/MuseScore/commit/9c2a429be4bc486ba5db4b5cdd4e3dcbcfdb6ce8
https://github.com/musescore/MuseScore/commit/3ae1d412513330b28cd591d6bd5096940ed8bcca

**Comment by Jojo-Schmitz** [comment]
See #6817

**Pull request merged**
