### PR TITLE
Pianoroll3 link error - do not merge!

### PR DESCRIPTION
**Pull request by blackears**
Do not merge this branch.  I'm pushing this branch so that Casper Jeukendrup can take a look at it and figure out why it is not linking correctly.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
If you want to prevent merging, change to draft

**Comment by cbjeukendrup** [comment]
@blackears For me, your branch seems to build fine. Maybe you just need to do a clean build? Quite a number of things has changed in the CMake files recently.

**Comment by blackears** [comment]
It builds for me too.  The problem is when you run it.  I'm getting an error thrown by the QML system that boils down to it not being able to create an instance of my components.  And when I step through it with the debugger, it seems to be completely ignoring the methods I've overwritten in the PianorollModule.

**Comment by cbjeukendrup** [comment]
And are you sure that `MUE_BUILD_PIANOROLL_MODULE` is indeed enabled? Maybe there is somehow a problem with that?

**Comment by cbjeukendrup** [comment]
Ah, maybe I found it. 
- a `def_opt(MUE_BUILD_PIANOROLL_MODULE ${MUE_BUILD_PIANOROLL_MODULE})` is missing in `SetupConfigure.cmake`
- there's a typo in `src/stubs/CMakeLists.txt`, namely 
```
if (NOT MUE_BUILD_PIANOROLL_MODULE)
    add_subdirectory(palette)
endif()
```
(palette instead of pianoroll)

**Comment by blackears** [comment]
Okay, it's working now.  Thanks.

Is there any chance this module could be reviewed and applied now that work on MS 4.1 has started?

**Comment by blackears** [comment]
This is the main PR for this module: https://github.com/musescore/MuseScore/pull/9109

**Comment by RomanPudashkin** [comment]
Closing because there is the main PR. Please reopen if you still need it, thanks!

**Pull request closed without merging**
