### PR TITLE
Fix: typos in editstyle.ui

### PR DESCRIPTION
**Pull request by Gootector**
Fix: typos in editstyle.ui

Greetings,
Gootector

Resolves: #NNNNN 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by cbjeukendrup — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
This causes 5 compiler warnings: Warning	C4125	decimal digit terminates octal escape sequence

**Comment by Jojo-Schmitz** [comment]
So I'm affraid we'd have to revert this

**Comment by Jojo-Schmitz** [comment]
or use ', just like in multiple other places, like "Reset 'Vertical position of number' value"

**Comment by Gootector** [comment]
There are two solutions:
'1' or ‘\1’

**Comment by Gootector** [comment]
Fix #25516, the first solution.

**Comment by Jojo-Schmitz** [comment]
Tha t's also in #25515

**Comment by Gootector** [comment]
Closed #25516.

**Comment by Jojo-Schmitz** [comment]
And the other solution desn't work:
image

**Pull request merged**
