### PR TITLE
[MU4] Added engraving module

### PR DESCRIPTION
**Pull request by igorkorsukov**
And moved `libmscore` to `engraving/libmscore` 
I think in the future it will be renamed to something like an `engine`, or a `model` ... or will separate into parts, but all this will be later.

### CODE REVIEW

**Review by vpereverzev — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
This move also needs adjustments to tools/fonttools/smufl2sym*

**Comment by igorkorsukov** [comment]
> This move also needs adjustments to tools/fonttools/smufl2sym*

Thanks, I will do it

**Comment by igorkorsukov** [comment]
> This move also needs adjustments to tools/fonttools/smufl2sym*

I looked, there is no dependency on libmscore path (it generate new output files, not changing current)
But I figure out other bug, and fixed it :)
https://github.com/musescore/MuseScore/pull/8245

**Comment by Jojo-Schmitz** [comment]
Oops...

**Pull request merged**
