### PR TITLE
Fix: incorrect apostrophe

### PR DESCRIPTION
**Pull request by Gootector**
Fix: incorrect apostrophe

Greetings,
Gootector

Resolves: #NNNNN 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Gootector** [comment]
@cbjeukendrup I found one string to fix.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
There's a bunch more: all the "Reset 'xxx' value" ones

**Comment by Jojo-Schmitz** [comment]
And "Show '1' on 1-measure repeats"

**Comment by Jojo-Schmitz** [comment]
and "expected token type and name 'EndElement %1', actual '%2 %3'"

**Comment by Gootector** [comment]
@Jojo-Schmitz https://github.com/musescore/MuseScore/pull/19868

**Pull request merged**
