### PR TITLE
Transposition fix

### LINKED ISSUE #17530: Wrong notes rendered after the tab transposition (Cant Help Falling In Love - Elvis)
### Issue type

Other type of issue

### Bug description

[Elvis Presley - Cant Help Falling In Love (ver 16 by savchenkoroman94).gpx.zip](https://github.com/musescore/MuseScore/files/11452521/Elvis.Presley.-.Cant.Help.Falling.In.Love.ver.16.by.savchenkoroman94.gpx.zip)

### Steps to reproduce

1. Open the tab
2. Apply transposition to the score on major third or to E major key (which is the same)
3. Pay attention to notes changes (e.g. measure 5 in ac guitar. Same notes are rendered)

At the same time there's no an issue if you transpose to 1 semitone

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/101250347/decadaa9-21c0-4f59-8ad1-bbd0ff1c8120

### MuseScore Version

MuseScore 4.0.2 

### Regression

No.

### Operating system

macOS 13

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mikekirin**
fixes #17530

### CODE REVIEW

**Comment by abariska** [comment]
@mikekirin 
1. Chords are not changed when transposition applied
2. Crash when applying transposition for selected chord symbol


https://github.com/musescore/MuseScore/assets/101250347/1799628e-9c97-4b09-9e94-f5b92e673d62

Test tab (but could be used any) 
[Layers, chords and meta.gp.zip](https://github.com/musescore/MuseScore/files/11453886/Layers.chords.and.meta.gp.zip)

**Comment by Jojo-Schmitz** [comment]
The crash on transposing (real!) chord symbols still happens, and apparently got intriduced with this PR!

**Comment by mikekirin** [comment]
@Jojo-Schmitz chord symbols works as they were working before this PR. This happens only for gp imports.

**Comment by Jojo-Schmitz** [comment]
Yes, except for the crash on attempting to transpose them

**Comment by Jojo-Schmitz** [comment]
Please check my #17588

**Comment by Jojo-Schmitz** [comment]
Darn, that sample file from @abariska still crashes, now directly on load

**Comment by Jojo-Schmitz** [comment]
from the logs:
```
2023-05-16T17:46:43.139 | ERROR | main_thread | engraving  | LayoutContext&>: "ASSERT FAILED!": found, file: C:\Users\Jojo\Documents\GitHub\MuseScore\src\engraving\layout\../infrastructure/rtti.h, line: 97
```

**Comment by mikekirin** [comment]
Looks like latest layout changes might be the reason

**Comment by Jojo-Schmitz** [comment]
Yes, as that wasn't the case before

**Pull request merged**
