### PR TITLE
Update_Timeline_Tempo

### PR DESCRIPTION
**Pull request by AnandHemachandran**
Changed the height of the cell in order to prevent the crossing over of the grid lines on the Tempo Segment.
Before:
timeline
 After:
timeline2

### CODE REVIEW

**Comment by anatoly-os** [comment]
Better solution is to fit text into the existing height. Is it possible to implement?

**Comment by AnandHemachandran** [comment]
Thanks for the reply, I will try my best to do that.

-- 
Regards,
Anand.H
Github <https://github.com/AnandHemachandran> || Blog
<https://anandinblog.wordpress.com/>

**Comment by AnandHemachandran** [comment]
Created if condition to check the row number and changed the Y position of the addMetaValue

**Comment by anatoly-os** [comment]
@AnandHemachandran could you please update the "After" image in the title message?

Current result is better, but still needs an improvement to make text vertically centered:
timeline 2019-02-21 11-39-49

**Comment by AnandHemachandran** [comment]
I got it different:
timeline 3

**Pull request merged**
