### PR TITLE
Sound flags popup glitch fix

### PR DESCRIPTION
**Pull request by Eism**
also 
Resolves: #21804
Resolves: #21693

### CODE REVIEW

**Comment by avvvvve** [comment]
@Eism I should've anticipated this but the popup appears too far away from the SF button now (24px). Please make the space between them 12px instead, which will match the harp pedal diagram popup spacing. Thanks!

**Comment by avvvvve** [comment]
Should've also mentioned it's so nice to not see that stutter glitch when opening the popup. Great job!

**Comment by Eism** [comment]
> @Eism I should've anticipated this but the popup appears too far away from the SF button now (24px). Please make the space between them 12px instead, which will match the harp pedal diagram popup spacing. Thanks!

@avvvvve fixed

**Comment by avvvvve** [comment]
@Eism Awesome, looks good to me!

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
