### PR TITLE
fix #289374: tuplet numbers: 'follow staff size' not working

### PR DESCRIPTION
**Pull request by jthistle**
Resolve: https://musescore.org/en/node/289374

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Cool, thanks for getting on this!  I'm surprised there needed to be so much change, though, as it works already for non-2.x scores.  But, I guess it works more by accident than by explicitly handling Pid::SIZE_SPATIUM_DEPENDENT?

BTW, your inspector changes show what appear to be mismatches between "Fixed" vs "Expanding" for some of the controls, and other changes that might not have been intended.  Or it could be the diff is not comparing apples to apples.  But do be careful when messing with the Inspector not to make things not able to compact horizontally the way they should.

**Comment by jthistle** [comment]
Oops, thanks for picking up the inspector, that is a mistake. I'll fix it.

**Comment by jthistle** [comment]
Fixed now, I think.

**Comment by anatoly-os** [comment]
The changes here are not a regression comparing to what we have in 3.0.5, they are not trivial, so let's postpone it to 3.1.1.

**Comment by jthistle** [comment]
Fine with me :)

**Comment by Jojo-Schmitz** [comment]
Rebase needed

**Comment by anatoly-os** [comment]
@jthistle could you rebase the PR please?

**Comment by jthistle** [comment]
I'm not around today, but when I can, sure :)

**Comment by anatoly-os** [comment]
@jthistle ? :)

**Comment by jthistle** [comment]
Aha, sorry. Will do now.

**Comment by jthistle** [comment]
Rebased @anatoly-os

**Pull request merged**
