### PR TITLE
Add sticking feature

### PR DESCRIPTION
**Pull request by dmitrio95**
Implements a sticking feature for drumline scores. As per @danieljray's advice (see also #5038), for a number of reasons it is implemented separately from Fingering, and although the current implementation is a simple `TextBase` subclassing, it can be expanded in future. The tradeoff though is a fully missing backward compatibility so the newly added sticking won't appear in the version 3.1 and below.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
FWIW, I'm not fully convinced there is any real benefit in making this a full separate element type rather than just a new text style type within the Fingering element.  But I guess that would have its own compatibility issues as well, so there is no real downside either.  My PR #5038 was based on the idea of supporting the requirements of sticking without requiring new element types or styles, but even so, it still would have been the case that stickings added "my" way would not layout as expected in earlier versions.

Assuming we do go forward with this for 3.2 or whatever, I also want to add a similar new element type for Roman numeral analysis that would just be a subclass of Harmony that skipped any attempt to parse, render specially, or transpose the text.

**Comment by danieljray** [comment]
The only thing that sticking and fingering have in common is that they are text instructions for the performer.

Placement of sticking is strict and fixed, always in same place at bottom of staff.

Unlike fingering, sticking is not only indicated for playability but also reasons of timbre - left hand and right hand hits actually sound different.

So, sticking should ultimately have playback implications. A sticking indicated as "l" on an unarticulated hit should pull a sample from roundrobin pool for unarticulated left hand hit.

Case of sticking should also be inherited by articulations. For example, an unarticulated hit on the right hand is indicated by a lowercase "r". If accented or otherwise articulated, it is transformed to an upppercase "R".

Once again, while they may share similar characteristics, they are not close to the same and should not be combined.

**Comment by MarcSabatella** [comment]
It's not at all true that the only thing they have in common is that they are both text instructions - there is far more to it than that that is relevant to implementation.  In particular, the fact that both are inherently attached to *notes* as opposed to chords, chordrests, or segments is significant.  The PR here makes them segment annotations, meaning it will be impossible to have different sticking for different notes in a chord, for instance.  That seems like it would limit things.

It's not impossible to implement any of the things you say for fingering, and indeed, it's actually quite relevant there.  Most wind instruments, for example, can produce different sounds for the same note with different fingerings, and the same round-robin technique would potentially apply there.  And since string numbers are also implemented as fingering indications, the same is true there as well.

So, I'm not opposed to introducing a new type, but I think you are greatly overstating the differences here - missing the ways in which the things you mention can apply to fingering as well.  I think you may also be underestimating the issues that would result from the proposed implementation.

I think it probably makes more sense to have a new base type that both fingering and sticking inherit from, so the common elements (of which there are many) can be shared, and only those very few things that need to be different be.

**Comment by danieljray** [comment]
We need to move beyond generalized solutions that half solve something for multiple segments into solutions that more more fully-meet the needs of individual segments.

This means that some may have deeper solutions than others at some points in time.

If you are writing for percussion on a high level, you have very specific expectations and requirements. Half solving this is as effective as not solving this at all.

Mixing sticking with fingering is no better for this segment than mixing sticking with lyrics. It is still a half solution.

We also need to start thinking beyond paper and consider how these information layers can be expressed in more meaningful ways. 

For example, fingering on piano, on string instruments, and wind instruments (even woodwind vs. brass) share little beyond the name. There are purposes beyond playability, such as intonation and tone and it is not really effective or practical to display on paper in a score - yet this information is valuable to the performer.

This information should be attached to the score, to a very specific point, but have ability to selectively display under various scenarios. Again, this is a very different implementation than the need of constant display for sticking.

To put this a different way, fingering on piano is a guide meant to assist the performer with playability. Though suggested by the performer, adherence is delegated to the performer.

Many assume incorrectly that sticking is similar to bowing annotations made by a concertmaster to ensure both the visual timing and timbre of a section. With percussion, it is much deeper than this.

Any sticking other than the indicated sticking indicated by the composer is considered incorrect, and is not a choice delegated to the performer. There are very distinct differences in timbre and it is not an optional element of a percussion score.

**Comment by MarcSabatella** [comment]
I'm not suggesting half-solving anything.  I'm suggesting solving it fully, but doing so in a way that allows the portions of the solution that are relevant to fingerings to eventually apply to them.  Better to set up the architecture now than have to refactor things later.  And again, many of the things that you are assuming to be relevant only to sticking are actually quite relevant to fingering as well, liek the possibility of a connection to sound (not so much on piano, but definitely for wind and stringed instruments.

And again, I do think you will discover that attaching sticking to segments (the MuseScore data structure of that nam, not the marketing jargon) ends up making this a half-solution, because you will lack the ability to have different sticking for different notes in the same "chord" (two notes in same voice at same time).  Attaching stickings to note rather than segments seems to me to be essential to have the full solution of which you speak.

**Comment by dmitrio95** [comment]
>  because you will lack the ability to have different sticking for different notes in the same "chord"

I discussed this question specifically with @danieljray before creating this PR, and it looks like there are never more than one sticking marking per chord in percussion scores, even if there are more than one note there. That is why attaching them to segment was preferred. Still if there are examples of the opposite then this implementation should probably be changed indeed.

**Comment by MarcSabatella** [comment]
OK.  I do share the goal of not doing some a half-solution, hence my concern here, but if we're sure we don't need that, then indeed attaching to segment simplifies much.  Ideally, there would still be a way to structure at least *some* of the eventual playback code to make it possible to tie into fingering for wind and strings, but it's not like this is a commonly-requested feature in that world.

Slur playback, on the other hand, is maybe more analogous in terms of user expectation and what might need to happen in order to implement it.  And of course, we already have articulations that affect playback.  So now I'm wondering if there is some way to share some of this sort of playback code between all of these elements - text for both sticking and fingerings, lines for slurs, and articulations - so that any of them can potentially do things like swap out samples etc.  But that probably has little bearing on how the fingering class itself fits into the text hierarchy.

**Pull request merged**
