### PR TITLE
Add brass band template

### PR DESCRIPTION
**Pull request by IsaacWeiss**
Courtesy of Henk De Groot

### CODE REVIEW

**Comment by lasconic** [comment]
What's the difference with https://github.com/musescore/MuseScore/pull/2625/files
Is there an issue somewhere? 5 is a good number per category. if we use 6, it adds one row.

**Comment by lasconic** [comment]
Ok I see, you renamed them.

**Comment by IsaacWeiss** [comment]
Shame on me for forgetting CMakeLists.txt.

The other thing changed here is the number of measures in a couple of the new marching templates. I doubt it makes any difference, but the rest of them seem to be 32 measures, so now these are the same as well.

**Comment by IsaacWeiss** [comment]
I don't think having six in a category is a problem—there are six chamber groups already.

**Pull request merged**
