### PR TITLE
Fix #17700: Update mixer view ticks correctly across app instances

### LINKED ISSUE #17700: Mixer View Ticks are not updated correctly across insistences of the app
### Issue type

UI bug

### Bug description

The "ticks" or "check marks" next to channels in the view options for the mixer are inconsistent when working with multiple instances of MuseScore.

### Steps to reproduce

1. Open two instances of MuseScore
2. Go to the mixer menu ...
3. Select view and tick or untick a channel.
4. The other instance of MuseScore will update
5. Check the mixer menu ... in the second window
6. Look at the check marks under view and they will be inconsistent

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/c5391c29-df72-425e-959a-ac7765f12a79

### MuseScore Version

MuseScore version (64-bit): 4.1.0-231420826, revision: github-musescore-musescore-230479a

### Regression

No.

### Operating system

OS: macOS 11.6, Arch.: x86_64, 

### Additional context

This is pertaining to the release of the mixer with added reverb controls.

https://github.com/musescore/MuseScore/pull/17570

### PR DESCRIPTION
**Pull request by nasehim7**
Resolves: #17700 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
This PR looks really good, but it would only affect aux channels and aux sends, and not other items in the view menu. Shouldn't those get the same treatment?

**Comment by nasehim7** [comment]
If we think about it, yes for the consistency it makes more sense to have other items also should behave the same across all instances of the application. Considering the issue that was raised, I thought the expectation is only to have these 2 items shared across instances. I just had a more closer look on the other menu items and can see they are being set as a shared variable across instances here: https://github.com/musescore/MuseScore/blob/b1a4459a40f297bc0e9997ea467c08813ba82d30/src/playback/internal/playbackconfiguration.cpp#L163
So it makes more sense to also have these other items checked status as well be tracked across instances

**Comment by nasehim7** [comment]
@cbjeukendrup I have updated the code to incorporate `isMixerSectionVisibleChanged()` notification which can be monitored similarly to update the menu checked status across instances. I have slightly refactored the code to have a method called as `emitMixerSectionVisibilityChanged()` which based on the sectionType, emits the respective notification, which was originally been done in the `toggleMixerSection()` method. This was needed to be decoupled from the toggle method so that this can be directly invoked whenever `isMixerSectionVisibleChanged()` happens. Hope this aligns well now. Let me know your take on this :D

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/17700 FIXED

**Comment by nasehim7** [comment]
Thanks @cbjeukendrup @zacjansheski for the review. I can see the "vtests/build_reference" failed. When I go and check to see what exactly is the issue, it says logs have been removed due to the pipeline retention policy. Can you suggest how can I check the issue here? I am aware of unit tests but not vtests

**Comment by cbjeukendrup** [comment]
@nasehim7 Don't worry about it, that's currently broken. Or actually it just got fixed on master, so if you rebase it gets fixed here too, but you don't need to make that effort since it's clear enough that your PR can't cause VTest issues.

**Pull request merged**
