### PR TITLE
fix AppImage build for armhf

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
which seems to be lacking Qt-5.4 and with that `QVector::removeOne()`

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Just testing one option...

**Comment by lasconic** [comment]
If it go through, let's use QList in 2.x on all platforms.

**Comment by Jojo-Schmitz** [comment]
Apparently there are more issues due to a too old Qt version, so this seems the wro f way of trying to fix it

**Comment by Jojo-Schmitz** [comment]
As per @mirabilos QStorageInfo(), QSysInfo::prettyProductName(), QSysInfo::currentCpuArchitecture() are the only other issues, but while it'd be relatively easy to work around QSysInfo::prettyProductName(), QSysInfo::currentCpuArchitecture(), QStorageInfo() is really needed for being able to install/update extensions. So we really need a newer Qt here, and most provably only get that by updating the docker image to some newer Debian (?) distribution

**Pull request closed without merging**
