### PR TITLE
fix #202271: Copy-paste sextuplets/octuplets and their removal leads …

### PR DESCRIPTION
**Pull request by lasconic**
…to corruption

### CODE REVIEW

**Comment by MarcSabatella** [comment]
This is basically the fix I tried and it seemed to work.  I'd still want to look more at @AntonioBL fix that is already merged for master, which seems more involved.

**Comment by lasconic** [comment]
Did you have a chance to look at this fix? A link?

**Comment by MarcSabatella** [comment]
I have not had a chance to look at this, still on my todo list.  The fix I meant is #2881, which I gather was based on #2880 although it's still confusing to me.  But see comment in https://musescore.org/en/node/202271#comment-719966

**Comment by lasconic** [comment]
I added a check similar to the one of #2880. 
However we still have the problem here 
https://github.com/musescore/MuseScore/pull/2881#discussion_r86953943

**Comment by AntonioBL** [comment]
I think that the problem comes from the fact that the tuplet duration is not stored in the file, but it is derived with tuplet.ratio and tuplet.baseLen. Therefore, if these two do not "agree" (i.e. one of them is "wrong") the computed duration is wrong.
In principle, the ratio should not be reduced and the baseLen should be computed when creating the tuplet as Dur/Den where Dur is the tuplet duration and Den is the ratio denominator (since there are Num notes in the duration usually occupied by Den notes, with Num the numerator of the ratio).
However, in the code there was (there is) a problem of fraction reduction when creating the tuplet via tupletdialog and therefore some of the existing files have a wrong couple baselen-ratio (in particular the baseLen is wrong). It is difficult to deal with this, since in some point of the code (for example during copy-paste) the duration is computed by using Den times the baseLen.

Maybe we could always reduce the ratio whenever tuplets are involved (and compute the baselen accordingly), but this **would not be "sematically" correct**, i.e. **a 6/8 tuplet would always become a 2/3 tuplet** (I don't know if this would heavily influence the "show ratio" option, since after saving every memory of the tuplet being a 6/8 instead of a 2/3 would be lost).

Since the duration is not saved in the file, retrieving the correct baselen for a tuplet loaded from a file with a wrong baseLen and a correct ratio is quite involved (this is what I tried with the "tupletCheck" function, but this is not always correct - for example if some notes/rests are missing in tuplets of voice>0).

**Comment by MarcSabatella** [comment]
My impression is that indeed we cannot easily fix scores that were already saved with incorrect information. 
 There is no obvious / foolproof way to calculate it correctly even if we didn't have to resort to hacks to differentiate "bad" from "good" versions, and then there is the hackiness of both the version check and the heuristics we could use to try to get the right answer "sometimes".

I'm still having trouble wrapping my brain around the full ramifications of all this, though.  I will play with it some today and/or over the weekend so I can give better feedback.

**Comment by MarcSabatella** [comment]
The case described in https://github.com/musescore/MuseScore/pull/2881#discussion_r86953943 still produces corruption.  That is, 4/4 time create the 8/6 tuplet with dotted quarter duration, try to copy and paste - it fails, even copying to another 4/4 bar.  And if you save/reload, then try to delete the tuplet, you get corruption.  I'm still working on understanding all the different variables involved here; I'm not sure why this case fails with this fix but the other cases work.

**Comment by AntonioBL** [comment]
That's because the ratio is reduced, therefore the globalduration of the tuplet is wrong, too.
https://github.com/musescore/MuseScore/blob/master/libmscore/duration.cpp#L70

**Comment by AntonioBL** [comment]
Actually the situation is a real nightmare.
There can be around files with correct tuplet ratio (given by actualNotes and normalNotes) and correct baseLen and also files with correct tuplet ratio (given by actualNotes and normalNotes) and wrong baseLen, but there is no possibility a priori to tell apart one from the other, since the duration is computed during import of the tuplet (line 691 of tuplet.cpp).
Example:
-  correct tuplet ratio (given by actualNotes and normalNotes) and wrong baseLen: in MS 2.1 create a 6:4 tuplet on a 1/2 rest with the tuplet dialog, fill it with 6 eight notes and save as mscz or mscx file
- correct tuplet ratio (given by actualNotes and normalNotes) and correct baseLen:  in MS 2.1 create a 6:4 tuplet on a 1/2 rest with the tuplet dialog, fill it with 6 eight notes and export as xml file. Import this xml file and save as mscz or mscx.

One way or the other, the line computing the duration during import will give a wrong value or the baseLen will be set wrongly.



Side note: if in the previous example the tuplet is filled with 3 quarter notes, during xml import the baseLen is set to a null value, determining a series of problem. Also in master: the problem is here https://github.com/musescore/MuseScore/blob/97b5aec8d5bfcb492485e74d8c846e43e6387785/mscore/importmxmlpass2.cpp#L996 since tupletCount is 3 and t->ratio().numerator() is 6 in this case.
But this is an additional bug.

**Comment by lasconic** [comment]
I'm afraid that to stop the nightmare we will have to take some strong decision... 
So I would propose we fix the problem properly in 2.2 (and master) and make sure that "simple" tuplets from MSCZ files are handle correctly. Then, we make sure that more complex tuplets from previous versions are handle correctly. And if MusicXML cannot be made OK, then we just state in our release note that we have a known incompatibility... We cannot make all the cases OK, so let's try to make most cases OK and document the ones we cannot solve.

@AntonioBL  you know the problem very well, do you want to give it a try?

**Comment by AntonioBL** [comment]
I think that this change:
https://github.com/musescore/MuseScore/pull/2880/files#diff-c9b79bb5698a9f30aece92a077d7e3c3R106
should prevent the problem to occur **for files created from scratch** if the import of the tuplet https://github.com/musescore/MuseScore/blob/2.2/libmscore/tuplet.cpp#L691-L692 is modified to use the non-reduced ratio.

The problem is the compatibility with existing "corrupted" files. As the code is at the moment, it should import:
- a correct duration but a wrong baseLen for tuplets created with correct ratio and wrong baseLen,
- a wrong duration but a correct baseLen  for tuplets created with correct ratio and correct baseLen (e.g. the xml-exported-imported-saved case of above).
See:
https://github.com/musescore/MuseScore/blob/2.2/libmscore/tuplet.cpp#L691-L692
(note that these considerations hold only for tuplets with a non-reduced ratio, no problem for "normal" tuplets)

Since the duration is computed a priori by mean of the baseLen and the ratio, it is not possible to correct a priori the values of the tuplet without knowing the notes and rests belonging to the tuplet and adding their duration to determine the actual tuplet duration.
That's why in master I introduced the "sanitize" step:
https://github.com/musescore/MuseScore/pull/2920/files#diff-a6897f4738755a08439b6c0c404757e4R1080
which is a "brute-force" approach to the problem: for problematic tuplets it adds up the durations of the elements of the tuplets and from this duration and the (non-reduced) ratio it determines duration and baseLen. However, I think it will fail if some elements of the tuplet are missing, for example for a corner case voice-2 tuplet?

**Comment by lasconic** [comment]
See PR #3503. I followed ABL advices. Not sure if we need the sanitize function. Can someone provide a failing file created with 2.1 or 1.3 ?

**Pull request closed without merging**
