### PR TITLE
Fixes: Measure Repeats -> Measure repeats and more

### PR DESCRIPTION
**Pull request by Gootector**
Fixes:
Measure Repeats -> Measure repeats
Articulations, Ornaments -> Articulations, ornaments
Automatic Capitalization -> Automatic capitalization
like https://github.com/musescore/MuseScore/pull/19155.

Greetings,
Gootector

Resolves: #NNNNN 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Umph, why did I miss those?

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
By the way, for information, we are planning to upload all new strings and your fixes to Transifex at the end of this month. Currently, Transifex is still bound to 4.1.x, so that new translations will go to 4.1.x's "Check for language updates" button. By the end of this month, we'll switch it over to 4.2, so that we can push the new changes.

**Comment by Jojo-Schmitz** [comment]
If you'd drop the `-no-obsolete`, the updated strings and their translations would work even for 4.1, the old strings would stay untouched untouched and the new would be available to 4.2 only

**Comment by Jojo-Schmitz** [comment]
IMHO the use of `-no-obsolete` should be the exception rather than the rule, only on major version changes. It was handled that way in the past (Mu1,2,3)

**Comment by Gootector** [comment]
@cbjeukendrup Thanks for info and merge.
@Jojo-Schmitz Don't worry - you're only human. There is always something missing, if you make changes manually.

**Pull request merged**
