### PR TITLE
[MU4] gradual_tempo_changes_step_1

### PR DESCRIPTION
**Pull request by vpereverzev**
Introduced basic elements for gradual tempo changes - Accelerando, Allargando, Calando, etc.
The processing of these elements in "tempo-map" calculations will be coming soon

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Is this the fix for https://musescore.org/en/node/9383 ?

**Comment by jthistle** [comment]
Hi Vasily, just to let you know, `ChangeMap` exists in libmscore. This class may be of some help - it's currently used for dynamics (hairpins etc.) but may be of some use in this case.

**Comment by vpereverzev** [comment]
> Hi Vasily, just to let you know, `ChangeMap` exists in libmscore. This class may be of some help - it's currently used for dynamics (hairpins etc.) but may be of some use in this case.

yep, I'm playing around this class already :)

**Comment by vpereverzev** [comment]
> Is this the fix for https://musescore.org/en/node/9383 ? Seems at least a 1st step towards it, right?

yep

**Pull request merged**
