### PR TITLE
Updating of instrument name in linked parts

### PR DESCRIPTION
**Pull request by BartlomiejLewandowski**
Not sure if this is the correct way to do this, but this solution works. There might be a better way to get the linked parts for a score part though.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
seems to need a rebase

**Comment by anatoly-os** [comment]
Linked parts are implemented and work in 2.2.1 and master.

**Comment by lasconic** [comment]
A reference to a bug report is missing for pull request but the bug is still present, at least 
In 2.2.1
* create a score with two instruments
* create a part with the two instruments
* right click on a staff in the score, change the instrument name and OK
* go to the part and see that the instrument name didn't change

**Comment by anatoly-os** [comment]
Well, tab with part name is also not updated and parts list keeps the previous name. So, it needs complex solution. We can mention this PR in the bug to keep reference, but I don't think this PR can be resurrected :)

**Comment by anatoly-os** [comment]
@lasconic you also didn't mention the link to the bug report :) I cannot find one, but found another interesting one https://musescore.org/en/node/10728

**Comment by Jojo-Schmitz** [comment]
So reopen it?

**Comment by lasconic** [comment]
@anatoly-os for your interest, this report is very different. Part name is entirely different from instrument name . They are not related except when the part is created with "New All"

**Comment by dmitrio95** [comment]
Closing this pull request, if there is an update on implementing this feature please open a new pull request.

**Pull request closed without merging**
