### PR TITLE
Improve pattern detection in beamed notes (zero slope)

### PR DESCRIPTION
**Pull request by pgkos**
This improves the behavior of the Beam::slopeZero method.

If there is a repeated pattern of pitches in the beamed notes, the beam will have zero slope (ref. Behind Bars, pg. 22):

Before:
beamslope1
After:
beamslope2

The slope will also be zero if the pattern of pitches is "truncated", e.g.: a b c d a b c

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Very cool!  The test failure, btw, looks at first glance likely to be "expected".

**Comment by pgkos** [comment]
Yes, the pitches in the test are: 76 77 74 76 77 - so this is a truncated repeating pattern, which should have zero-sloped beam. I will try to update the test.

**Comment by lasconic** [comment]
It's pretty cool. However on my computer it makes the layout algorithm 5% slower on our benchmark score. I wonder if the cost is worth the feature. Any opinion?

**Comment by MarcSabatella** [comment]
I was never able to get benchmark results repeatable enough to detect a 5% difference, so I don't know how significant that really is.  Clearly, we can't afford a *lot* of changes that have this sort of effect, unless we get a matching or larger gain elsehwere.  I wonder how efficient the "newlayout" system is compared to the current (I haven't yet had time to teast it out)?

**Comment by lasconic** [comment]
From what I heard from @wschweer, the layouting in the newlayout branch is currently faster, but also a lot of codes has been commented out or removed... So I don't have definitive answer.

For my test, I ran tst_benchmark 5 times with current master and 5 times with this PR merged.

**Comment by pgkos** [comment]
I can think of another solution (but only approximate). On the other hand, it would be very fast (as fast as it was without this PR, or even faster).

The beam would have zero slope if one of these two conditions holds:
- the beam is concave (one of the inner notes of the beam are closer to the beam than both of the "border" notes)
- the **second half of the beam** contains a note of identical pitch to the first note of the whole beam (which I think is a good approximation to the "repeating pattern")

**Comment by MarcSabatella** [comment]
That would result in flat beams in situations where it shouldn't be, though, right?  I don't think that's advisable.  The current situation is preferable to me.  But maybe there are other solutions.  I was wondering about buiding a hash value, for example - line1 + line2 * 100 + line3 * 10000 etc, 

We could also consider a "Flat" checkbox in Inspector to make it easier to flatten beams individually.

**Comment by lasconic** [comment]
a "Flat" checkbox ?
How would that be different from the "Horizontal" checkbox we already have :) ?

**Comment by MarcSabatella** [comment]
It wouldn't be greyed out in the example I tried, causing me to not notice it? :-)  I guess that's our indication that the value comes from the style setting.  Still wish there was a better way to indicate that.

**Comment by lasconic** [comment]
The was the easiest way but if you have a better one, I can take a look how to implement it !

**Comment by MarcSabatella** [comment]
We should probabky be using italics to indicate a "mixed" selection (that is, selection where the values aren't all the same), but maybe underline or color to indicate the settings that come from style (ooh, and make that a hyperlink to bring up the corresponding style dialog).  Something like that, maybe I'll bring it up on forum.

**Comment by pgkos** [comment]
I have tried hashing, but it also comes with performance penalty.

Therefore, performance-wise, for now, the best option would be to use the approximation algorithm.

I have updated my idea for this algorithm, I think now it will almost never true when the beam should be sloped:

1. Check for concavity, if a beam is concave, return true.
2. Check for a note in the second part of the beam which is identical to the first note of the whole beam. If it exists, and there also is a note **in the first part of the beam identical to the last note of the whole beam**, return true.
3. Else return false.

If the rule 2 is true, but the beam does not in fact contain a repeating pattern, it can be regarded as "almost concave", and have zero slope.

**Comment by dmitrio95** [comment]
Needs actualization and reopening for current master

**Comment by MarcSabatella** [comment]
FWIW, there is a lot of room for improvement in the beam algorithms.  Although to be fair, it's something that all programs struggle with, even LilyPond.  Anyhow, I'd love to see someone take on a project of rewriting the whole thing.  Little tweaks like the one here are potentially nice but since it will change layout of existing scores and thus in a sense break compatibility, I do think it better to wait until we have something really worth breaking compatibility over.

**Pull request closed without merging**
