### PR TITLE
fix #270910: raise minimum GCC version to 4.8

### PR DESCRIPTION
**Pull request by mirabilos**
https://musescore.org/en/node/270910

### CODE REVIEW

**Comment by anatoly-os** [comment]
@mirabilos could you please create the PR for 2.3 branch? 2.2.1 is used for only critical changes.

**Comment by Jojo-Schmitz** [comment]
Or even for master?

**Comment by mirabilos** [comment]
That GCC version is needed for even **2.1** to build cleanly, but okay.

Switched to 2.3 for now, because I don’t know if master doesn’t have an even higher requirement.

**Comment by Jojo-Schmitz** [comment]
Same fix __is__ needed for master

**Comment by mirabilos** [comment]
Joachim Schmitz dixit:

>Same fix __is__ needed for master

What I meant is: I don’t know if master might not need an even *newer*
GCC version, I was just trying to build 2.1 on *buntu 12.04…

**Pull request merged**
