### PR TITLE
[MU4] Update Bravura to 1.39

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
As taken fresh from https://github.com/steinbergmedia/bravura
Follow up to #4879, which updated it to 1.32

Counterpart to #5934 (which is in 3,x meanwhile)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
failing vtests expected

**Comment by vpereverzev** [comment]
@Jojo-Schmitz I'm not against of this particular update, but we probably need to update the vtests ref-images in this PR?

**Review by vpereverzev — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Maybe. But there's a lot of those that need updating and not just for Bravura as far as I can tell? And many/most of the scores used for that are still from 2.x

**Comment by Jojo-Schmitz** [comment]
IMHO updated vtests is a whole project of its own

**Comment by Jojo-Schmitz** [comment]
I've tried, but can't get MuseScore 4 to run in converter mode (on Windows) :-(

**Comment by vpereverzev** [comment]
@Jojo-Schmitz Oh, I think it's much easier. In CI_vtests job details you can find an artifact "compare" - https://github.com/musescore/MuseScore/suites/1367961822/artifacts/22385020. It contains the "new" images and the existing "refs".

**Comment by Jojo-Schmitz** [comment]
So just grabbing them from there might be the solution?

**Comment by vpereverzev** [comment]
Yep, just grab them and upload the new ones here

**Comment by Jojo-Schmitz** [comment]
That would cover only those this PR changes, but not the ones changed by other already merges ones, like from #6705.
Unless I'll collect those artifacts too (which in this case II could, but might miss others), should I?

**Comment by vpereverzev** [comment]
No, I think all you need here is to rebase your branch on the latest master (if you didn't it before). And result should cover all the difference considering the previous PRs.

**Comment by Jojo-Schmitz** [comment]
Ah! Of course...

**Comment by Jojo-Schmitz** [comment]
Well, no, it does not. So I'll add the ledgerlines ones too.

**Pull request merged**
