### PR TITLE
renaming of *Info* under File menu

### PR DESCRIPTION
**Pull request by salilkhandelwal**
The pull request is with respect to  https://musescore.org/en/node/92166 . The "info" under File menu has been changed to "Score Properties ".

### CODE REVIEW

**Comment by lasconic** [comment]
Please also change the description accordingly.

**Comment by salilkhandelwal** [comment]
By changing the description you mean changing 1) QT_TRANSLATE_NOOP("action","Edit Score info") to  QT_TRANSLATE_NOOP("action","Edit Score Properties")

**Comment by lasconic** [comment]
Yes, but use the same case, sentence case!

**Comment by ZackTheCardshark** [comment]
Also, don't forget the ellipsis (...).

**Pull request closed without merging**
