### PR TITLE
[MU3] Prepare for updated libsndfile

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
This enables us to update libsndfile from the currently used 1.0.25 to 1.0.29 or later (1.0.30 is available meanwhile too, see https://github.com/erikd/libsndfile), which apparently changed the name of the lib from `libsndfile-1`to just `sndfile`.
In a separate step the dependencies file for Windows may get updated. If the newer one is found on build, that is taken, else the older one.
This in turn might enable us to add opus support, see https://musescore.org/en/node/288994

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Attached the updated dependencies.zip (renamed to dependencies.7z.zip as GitHub doesn't allow .7x).
It has sdnfile.dll and sndfile.lib added for 32-bit and 64-bit, the sndfile.h updated and sndfile.hh added.
[dependencies.7z.zip](https://github.com/musescore/MuseScore/files/5122387/dependencies.7z.zip)

**Comment by anatoly-os** [comment]
Do we really want it in 3.5.1, or even 3.6? I would merge this to master (MU 4).

**Comment by Jojo-Schmitz** [comment]
Fine by me, but as long as dependencies.7z doesn't get updated this PR doesn't make any difference

**Comment by Jojo-Schmitz** [comment]
And here the
[dependencies.7z](https://github.com/musescore/MuseScore/files/5298199/dependencies.7z.zip) for libsndfile 1.0.30

**Comment by Jojo-Schmitz** [comment]
It is in master now, waiting for it to get merged into 3.x for 3.6

**Comment by vpereverzev** [comment]
@Jojo-Schmitz I'm not sure what this might affect for 3.x users, but one thing I know for sure, support for Opus should be in master, because it does not look like something trivial.

So since this is already merged in master, I'd close this PR for 3.x

**Comment by Jojo-Schmitz** [comment]
Without the updated dependencies this PR does nothing, but allow for an updated libsndfile 
and opus support needs more than that

**Pull request closed without merging**
