### PR TITLE
notes_sound_indefinitely

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/18889
Resolves: https://github.com/musescore/MuseScore/issues/16389
Resolves: https://github.com/musescore/MuseScore/issues/15243
Resolves: https://github.com/musescore/MuseScore/issues/14447
Resolves: https://github.com/musescore/MuseScore/issues/15608
Resolves: https://github.com/musescore/MuseScore/issues/16890
Resolves: https://github.com/musescore/MuseScore/issues/18452

### CODE REVIEW

**Comment by MarcSabatella** [comment]
I don't suppose the "fallback" approach also solves https://github.com/musescore/MuseScore/issues/16389?  Or could be easily extended to?  Unfortunately I can't test these builds on Linux currently (need newer GLIBCXX).

**Comment by RomanPudashkin** [comment]
> I don't suppose the "fallback" approach also solves #16389? Or could be easily extended to? Unfortunately I can't test these builds on Linux currently (need newer GLIBCXX).

@MarcSabatella  I've changed my implementation. Now this PR should solve all those issues when notes get stuck/played with the wrong velocity. It turned out, that we have a lot of such reports... If you remember any of them, please list them here, so we can test them

**Comment by MarcSabatella** [comment]
Wow, crazy, I hadn't remembered some of those, but yeah, some variation of this does come up often.  I did a quick search and the only thing I saw that looked maybe also related (but maybe not) is https://github.com/musescore/MuseScore/issues/16854

**Comment by zacjansheski** [comment]
Almost everything is fixed!

In reference to https://github.com/musescore/MuseScore/issues/15524
Short mordents on non-string instruments in MS Basic still sound infinitely

https://github.com/musescore/MuseScore/assets/69917893/c4dad6b5-c13e-490c-af3d-622158a26e52

**Pull request merged**
