### PR TITLE
Fix key sig bug

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #15314

### CODE REVIEW

**Comment by sammik** [comment]
@mike-spa I dont know, why it was imortant, not to create C (empty) key signature, but I guess, there was some reason.
Are we sure, it is not relevant enymore?
If so, I saw many places in code, where similar code ("not create emptykey sig") is present. Isnt is related with this PR?

https://github.com/musescore/MuseScore/blob/3f9b94d3e54c554b9e046cfb1249fdc0601c2711/src/engraving/libmscore/measure.cpp#L3868-L3873

https://github.com/musescore/MuseScore/blob/3f9b94d3e54c554b9e046cfb1249fdc0601c2711/src/engraving/libmscore/edit.cpp#L4652-L4653

https://github.com/musescore/MuseScore/blob/3f9b94d3e54c554b9e046cfb1249fdc0601c2711/src/engraving/rw/measurerw.cpp#L408-L413

And possibly many others.

**Comment by MarcSabatella** [comment]
I can provide a little historical background that might be relevant.  There was a conscious design decision many years ago to represent C major by the absence of a key signature based on a general feeling that it was bad to have elements in the score that showed no visible trace of their existence.  I personally never shared that feeling, but did what I could to make things work despite any number of complications that design caused.  So some of those comments are likely mine, as is some of the code, but I'd be very happy to see it simplified.

There is nothing wrong in my book with C major being represented by an explicit element.  I don't even think the code actively *requires* C major to be handle with no key signature, as there are still ways you can end up with a C major key signatures element in the score.  But they do tend to get cleaned up on save/reload, so you'd want to make sure that isn't still happening.

**Comment by sammik** [comment]
Same fix is part of PR #12560 which fixes issue #12506

**Comment by mike-spa** [comment]
Thanks both for providing context! To me, eliminating the keySig event from a staff just because it isn't graphically shown is a profound mistake. The fact that the key isn't shown is purely incidental, and managing the showing/not showing just requires some very simple logic. Eliminating it altogether, on the contrary, effectively deletes a fundamental piece of information from our score representation that can't be reconstructed, and it keeps causing bugs and problems everywhere. 
The clearest example is the problems I fixed in #14849. There is a fundamental difference between global key signatures (i.e. the ones that apply to all staves) and local key signatures (i.e. the ones that apply only to individual staves). The first need to be repeated in all extracted parts, regardless of transposition, the latter doesn't. Problem is: if your score has instruments with different transposition and some of them happen to be in C,

**Review by oktophonie — APPROVED** [review]

**Pull request merged**
