### PR TITLE
Fix #10908: Added cross-staff beaming button

### LINKED ISSUE #10908: [MU4 Task] Implement cross-staff beaming button in note input toolbar
**Task description**
This is a task to add a button for cross-staff beaming into the note input toolbar. 

The button will trigger a context menu – much the same as the current behaviour for the tuplet button. 

The actions will be identical to the current keyboard shortcut commands "move chord/rest to staff above" and "move chord/rest to staff below". We are not adding any new functionality to this feature at this stage.

Screenshot 2022-03-25 at 11 53 41 pm

Please see this Figma file for the full design spec: https://www.figma.com/file/l0TQUrNFZmEfrZnfHhFDfb/Musescore-Notation-App-MASTER?node-id=23179%3A569821

The relevant icon has been added to `musescoreicon` in position U+F43D

Let me know if you have any questions,
Thanks!

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #10908

*(short description of the changes and the motivation to make the changes)*

This Pull Request adds cross-staff beaming button in note input toolbar

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by bkunda** [comment]
@HemantAntony @RomanPudashkin I cannot see where this has been implemented. This icon appears in neither the Mac nor Windows builds (in neither the note input toolbar nor the toolbar settings popup):

no-cross-staff-beam

**Comment by HemantAntony** [comment]
@bkunda, I can see the button in my build:
image
I don't know why its not there in your build

**Comment by cbjeukendrup** [comment]
You might need to delete your workspace file. It seems like the list of toolbar items is stored in the workspace, and when a new item is added, that is not added to the workspace (not even invisible), so you can't make it visible using the toolbar settings popup.

**Comment by bkunda** [comment]
Tested on both Win and Mac. WORKS.
Happy with this from a design-implementation POV. Many thanks @HemantAntony!

**Comment by HemantAntony** [comment]
> Tested on both Win and Mac. WORKS. Happy with this from a design-implementation POV. Many thanks @HemantAntony!

Happy to help 😁!

**Pull request merged**
