### PR TITLE
fix #276689: Add a timewise note input mode to MuseScore UI

### PR DESCRIPTION
**Pull request by dmitrio95**
This pull request contains a work towards a completion of [the task](https://musescore.org/en/node/276689) on addition of a user interface for Timewise note input mode. Currently this mode is added but there are few points to be reconsidered in the nearest future:
1. We need to pick or create a proper icon for the item for this mode;
2. We need to resolve issues related to note input modes in tabulatures and drumset staves (see [this issue](https://musescore.org/en/node/276671)).

### CODE REVIEW

**Comment by anatoly-os** [comment]
@dmitrio95 could you please add "fix #276689" at the beginning of the PR's title and commit message and use always use it to automatically close related issues.

**Comment by dmitrio95** [comment]
@anatoly-os I changed the title.

**Comment by MarcSabatella** [comment]
I like the concept, can someone explain how it actually works?  I see I can insert notes.  Can I delete them or change their duration?  Those would seem necessary to make this mode truly useful for the things I imagine people wanting to use it for.  Seems making delete work would be very straightforward, duration change might be slightly more involved...

**Comment by dmitrio95** [comment]
@MarcSabatella this mode does the same that you could previously achieve in MuseScore 3 by entering notes with Ctrl+click, that is, it allows inserting notes to a measure increasing measure's duration. The corresponding deleting operations is currently available on pressing `Ctrl+Del`. Perhaps it would be good to make usual delete behave like `Ctrl+Del` in this timewise input mode but it was decided not to put it to this mode yet. Still this mode is definitely highly experimental and can be adjusted in any way so it would be great to hear any suggestions and opinions on that.

The case of duration changes was not considered as far as I remember. But this can certainly be implemented. Do you believe this option will be useful for working in this mode? And in which cases this can be useful?

**Comment by MarcSabatella** [comment]
Ctrl+del isn't working for me in this mode. Works fine on normal mode, but nothing happens if I press it in this new mode.  Are you seeing otherwise?

**Comment by dmitrio95** [comment]
Indeed, Ctrl+Del seems not to work while being in any note input mode. Well, then we need to change it a bit to make it work in note input mode.

**Pull request merged**
