### PR TITLE
Changed all copyright dates to 2002-2016, since it's 2016.

### PR DESCRIPTION
**Pull request by awelch83**
Hopefully this one isn't ignored too.. I've been trying to find a way to contribute here. I have to start with trivial things such as this, until I become more familiar with the code.

### CODE REVIEW

**Comment by RobFog** [comment]
I don't think your other pull request has been ignored. To me as someone following the project it rather seems there is a large  backlog of pull requests pending review because of a lack of time.

**Comment by awelch83** [comment]
I question that. There was a series of merges recently. My pull request,
#2325 I think, had already been submitted at that time and had passed its
checks. It still sits there unmerged. There was also #2321 that was
submitted and passed checks. Nobody did anything with that either. It seems
like PR's are only wanted from a select few people. I could be wrong though

On Wed, Jan 6, 2016 at 2:41 PM, Robbie <notifications@github.com> wrote:

> I don't think your other pull request has been ignored. To me as someone
> following the project it rather seems there is a large backlog of pull
> requests pending review because of a lack of time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/musescore/MuseScore/pull/2337#issuecomment-169455167>.
>



-- 
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFWEqXIBEADAZ6IYll3rfCXefv7x8zl3E8eN94ILjuIK4gxv0SLw109ntyVM
RIhBAObrPzgVit6k+IT+BrJd5op23MmaDoaN6c7nIRqtSwMdEosNJY5RLD7V1/mv
+nsBkBnA3J8sDPAa/1Smfma/8bqvDOaK/lYTyDDUyJbEyCWmt/PeSyEJrKrg5Ihu
wfc20OFRaeskTBLPxFDtmOWOSTMta/s7XCmZuL7SCEtzEMxDHX8twAHIwHqI/jor
zl5C2kMb8DT5dUY2Z1AGhe0kRsQfHCuLLDw62yD+Jwclm73ZGKG6eF0Xhna5cwln
+uH0mlMqn+0PLl+Fih6gaUMUah1qb2N2yYil0p39F8sK5PHnMUf86wV/GE0auG0j
FkyWL6b0/L2DzPFQUxafIajn5OW6ULPLlhpqk0irwz+jZnTwJibWZqrIR8hehEhZ
GQhPBAD+xvlyCMCYRraj2NgvCMizMY50p/CqKI+IOBTamN965sSOfQlFWscjZZdR
3qaFFoeeuoUyWF6SjpRXrxcdOpNrro9Ghx1m816ibi7RhMZz7lmPO1kbQS4RliMu
VTYMXJ9rlzmFQ/a+1qERcs2zSgOxKYvvJIXBB2QRJUyohivcJu5/OHrQvjMQkHcl
sJxFJevPVO9ePUtz3OZfu0prODTPl4dqQs692q1pzRi1WRIInMZEd5zTUwARAQAB
tCZBYXJvbiBDLiBXZWxjaCA8c2VuZHMyYWFyb25AZ21haWwuY29tPokCPQQTAQoA
JwUCVYSpcgIbAwUJB4YfgAULCQgHAwUVCgkICwUWAgMBAAIeAQIXgAAKCRCfZkwd
I4s54ge8EACP96E72flh6ehpzaWxvVlN69EbLf9ZjDoIQz82yxmS397tg7ZZfzan
+W2X0w9YBSS7DOaznF4uqQKmchwBdrCes4ukGh9WA04OnppibHi7RBUEhYgk46Zq
zwhThOCk1Fr/83KZa/n5iYMpRtSqyDYYjBnL6NqoZkaaXtaTG8UnY1SehC0DtDlU
4AhmKqAWt5iUXG6V9ZPvJu7Iw9iZApanELtcqOAHnBY6MCJgyLcdVyNWCe5LF6t8
qbAeVdoJVfJcCOhMJrkr1rOLFzfNJfIpGS8Pyj6/FwiAPRJvlffnCrWm54h8kx1j
Y/w6tHnQrKDZ19Eo/ZPuhL21r0uJXcczT9wU70DMS/ji52UxhxFkP8hEJdIXsSeo
Azfs0UOfziu7+swvuGl5oGyxeb2556xl++2MuBTAuPhFi34CJ4d1j9TsgIENFLxb
LMy2a3iIRZcCXzCLd6cJUtgUajxYEfe2fxDwgRkmUmcKj5ePs04yNAIaB6aBc9CP
8SxXKHixEFpLVCzrGk+AhxetrGN1Vm+KVak2HVvpB1jXxOBIpMCKGRmcujFkVgQV
IKwmsrJA1Xg0ynUKmX2ZomftWv/h+Q3IOdyvigXfwffFJbj5A/hUj615H53Lp4u3
jbaM8iGPZeT1BJM78a+yVLOOM9ZsEU5blZa4s2YSTRXSgzVVKgsYJrkCDQRVhKly
ARAA4lEjCFqEKP1xpR5Ij2+Ho1Z/IktTgHSff26IBAsSDmHcpGVHyFnADl3imAzL
KrmWaI3eNCB5QQrif4+yyT4OAUxOYMberCAP4YA16Idy0vuhx1sVeDBHXNcdslCm
Isjehvf8j8WqxFMJ+2oLQ5Bpy8g3d8p3qkKZFNkeG4eqWiI5XfZKTApdun1sfbcp
qCu7J44mMVV5erKXm/0HGLJWbbhKoKjJ5wwZJPXXj19QescbDUluDad1hYvHhK5+
AY2FnN9nwbnxmNh/ptgS9JkyZjZgRuvCDin6RPAIMI3zAfJ/8MZdrzgssqek8gXm
jO3g6tyhH1CM2OsXCXu5+Lbddw8E92zCuMTOn0fSJT9Xp0FlCtqznrZXFrXMTDU6
23MwzCVae+hUqmtYRxZLiBUcdRwpEgk7X7X6OZJcV5b1FIeUxC0cb+H3sfqIqZL/
35mjCEm/9R/MplL92nIoycHZnwPPdq9HA095ryS98HmB3z4vLw4zgcylAbp4rgFk
OkYGvhmk3x7+xkPSH803DfxCufSo+z57vIMqHDP5WgUYW55lkDkijFx6AxQjbGxn
ZyC9O3caBSgTsjWlKA3hRyyVnPhiftEvlMAtPEQ3CbAttCasjcGHB4327n6GF4g2
FgHnxogN5bN8Czh9wRCEgKVkqOwjq++gFsIfnJekUZhGjMUAEQEAAYkCJQQYAQoA
DwUCVYSpcgIbDAUJB4YfgAAKCRCfZkwdI4s54vdZD/0RdZZMVv10BBXMzReb3/rO
xXumG7uFXBIARKuUKj4pG/GpWhbfj5UTvAiB22RGvuAIwuPwjDsnnIBJom/WWc8B
nKNOpPWkif92kSXtjDyXeGNznkSV72xVzkAM6n3DRssGLyyLcLH8YxdF+w3f65Dg
74WSakuNIsbV5HLRgiO0YzU0hFxWmraQjqFNgo26fUsax2XtJCe7vAORjPuPdJ3E
dH3y7dYYKqxTBGLtXqDS+lFFETuS26te06XJJJ7yuLjH0yJbocc+R+Zvy77a1dgU
cwHvXa/Kd7KrD97umhc9ByFxGuY3xpy4dCD7c+GmQz9IvFPgqG9DlxII5jX7OOkv
365mNm3gLw8o5OjFkd+PhJLMaQsP3lczkxywWciT6oTRHGWvy/j5m6d1ZFfnnR25
qn//hxk+NAS9lsY2ORZWBXHiGx1tlTJit3466aqIGS0S4O2LS5Ot2YcZYe/HZnOP
ovbYWI8M+o0SiUPaj5g3iCoupXALTwvrA2QBvnmAascq38P6WEiYH3naLgV7ZNXB
BudO+AC2fnJntXkPnblShQC6OXGoQxD+Jx+IPJMkfD/5GphYq2BgtSCV8RgbEhji
hiR2bvECoAEZ2qPAbSdD7Oupgw0AWsqN3lHrbU1HCUY++JQomZzfYMdl+qdZgVna
sR+RsK43UVuEVsaIWvIHgw==
=YvCU

-----END PGP PUBLIC KEY BLOCK-----

**Comment by MarcSabatella** [comment]
If you check the commit log, you will see that virtually no PR's at all
were merged for the entire months of November & December.  That includes 20
PR's of mine that were pending.  It seems quite clear you are not being
singled out; the holidays and whatever else may have been going on those
months just made them a bad time to focus on merging PR's.  No need to take
personal offense.

**Comment by shoogle** [comment]
Hi there @awelch83!

It's always good to have someone new who on board! I'm pretty new myself, and I started out by looking at the packaging for Linux thinking that would be easier than getting stuck in to the main C++ code. I [couldn't have been more wrong ;)](https://www.debian.org/doc/manuals/maint-guide/), but I got there in the end!

Now I'm trying to get to grips with the main code by implementing a [Lyrics Editor](https://github.com/musescore/MuseScore/pull/2326). It doesn't do much at the moment, but that means the code is nice and simple. If you [have a look](https://github.com/musescore/MuseScore/pull/2326/files) you'll see how various things are done in MuseScore, both at the level of the GUI (basically everything in the "mscore" directory) and the backend (everything in "libmscore"). It demonstrates various things, like setting a keyboard shortcut, creating a text widget, detecting changes in the score, extracting lyrics, etc.

If you want to try running the code, and if you followed the [git workflow instructions](https://musescore.org/nl/developers-handbook/git-workflow), then you can fetch my code like this:

<pre>
# Warning: these commands will delete unsaved changes so commit your changes first!
git remote add shoogle-repo git://github.com/shoogle/MuseScore.git
git fetch shoogle-repo
git checkout shoogle-repo/lyrics-editor
git reset --hard shoogle-repo/lyrics-editor
git clean -xfd

# Have a look at my code and try running it if you like (at your own risk, obviously)

# When you're done, if you want to get the upstream code back:
git fetch upstream
git checkout upstream/master
git reset --hard upstream/master
</pre>

You can use that method to keep swapping back-and-forth between my code and the upstream code, but remember to commit any changes before you switch (you'll need to create your own local branch to commit to). You're welcome to give me a hand if you want, and feel free to ask questions. (I can't promise I'll know the answer though since I'm just getting into it myself!)

**Comment by IsaacWeiss** [comment]
@lasconic @awelch83 I was just reminded of this by https://github.com/musescore/MuseScore/pull/2661. Why wasn't this merged? Especially given the contributor's concern about it (hopefully ameliorated by https://github.com/musescore/MuseScore/pull/2325).

The problem is, during the time when this slipped off the radar, all the big 3.0 development started, and this now has conflicting files. @lasconic, could you verify that this is something you'd appreciate? Then, @awelch83, you can resolve the conflicts as described at https://musescore.org/en/developers-handbook/git-workflow#Rebase-your-branch-on-the-latest-upstream.

**Comment by Jojo-Schmitz** [comment]
it needs a rebase

**Comment by shoogle** [comment]
FWIW the older the copyright date the better (as long as it's accurate) because in copyright and patent disputes the question is always "who came up with it first?". In the US and EU copyright expires 70 years after the death of the last surviving copyright holder and is not affected by the date of publication. You certainly don't lose your copyright by forgetting to update the date. Updating the copyright date is more of an honesty thing than a legal requirement, and as Jojo indicated in #2661, it should only be done on files that have actually been changed.

**Comment by shoogle** [comment]
@awelch83 if you are still interested in contributing then have a look at the [issue tracker](https://musescore.org/en/project/issues/musescore) and find something manageable that interests you. If you want an easy route into the code the here's a [PR for a lyrics editor](https://github.com/musescore/MuseScore/pull/2326) that I've been working on for a while. The code is not very long, but it demonstrates how to add a new panel to the GUI, get information from a score, and handling keyboard shortcuts. Feel free to work on it yourself if you like. Head over to the [#musescore IRC channel](http://irc.lc/freenode/musescore) if you need help getting started.

**Pull request closed without merging**
