### PR TITLE
[MU4] Fix (MSCV) compiler warnings related to UNITY build

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
There's 1 more (being reported twice) reg. unreachable code at https://github.com/musescore/MuseScore/blob/bfd75feec3e4da1b8c01cc0fd0aa81350ed42710/src/plugins/api/scoreelement.h#L154
Not sure whether it is related to UNITY build, nor how to fix it

### CODE REVIEW

**Review by igorkorsukov — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
There's 1 more (being reported twice) reg. unreachable code at https://github.com/musescore/MuseScore/blob/bfd75feec3e4da1b8c01cc0fd0aa81350ed42710/src/plugins/api/scoreelement.h#L154

**Comment by igorkorsukov** [comment]
> Not sure whether it is related to UNITY build, nor how to fix it

You can globality turn off UNITY BUILD - set option BUILD_UNITY to OFF

Or you can disable UNITY BUILD for module - add `set(MODULE_USE_UNITY_NONE ON)` before include `module.cmake` in a corresponding CMakeLists.txt
 
```
set(MODULE_USE_UNITY_NONE ON)
include(${PROJECT_SOURCE_DIR}/build/module.cmake)
```

**Comment by Jojo-Schmitz** [comment]
Well, I rather meant how to fix that warning ;-)

**Comment by igorkorsukov** [comment]
> Well, I rather meant how to fix that warning ;-)

I'll take a look later, but for now, I will merge this PR

**Pull request merged**
