### PR TITLE
GUI icon restyling

### PR DESCRIPTION
**Pull request by SolarGranulation**
GUI icons for document functions, dialog boxes, mixer interface and miscellaneous others.

Colours and motifs have been unified, many icons being completely redesigned while others were merely modified. The goal is to create a sense of visual cohesion and user comfort and confidence.

This addresses points raised by musician and YouTuber Tantacrul in video https://youtu.be/4hZxo96x48A?t=1149

### CODE REVIEW

**Comment by jthistle** [comment]
Welcome! Congratulations on your first MuseScore PR. This looks like an impressive amount of work, do you have any screenshots you can provide to show differences between old and new symbols?

**Comment by jthistle** [comment]
And also, you need to [sign the CLA](https://musescore.org/cla), or, if you have already, just say what name you've signed it under.

**Comment by SolarGranulation** [comment]
Thank you for the warm welcome! I have now signed the CLA, my username on the MuseScore website is SolarGranulation, same as here. 

I probably won't be able to provide screenshots until the day after tomorrow at this point. I'll keep it in mind in future.

**Comment by L0uisc** [comment]
First off, thank you very much for this! I looked at your new icons, and I can see that you put a lot of thought into making them unique and fitting for MuseScore and to make them stylistically consistent. I love your use of whole notes for the dots of the exclamation mark, i and question mark icons. Nice touch!

I do have a suggestion, though. I find your open, save and print icons difficult to decipher. Can you maybe rather use the traditional stiffie for save, printer for print and folder for open? I put this out there, so other people can chime in. If most disagree with me, it's ok as well.

**Comment by mattmcclinch** [comment]
I have to say that I agree with @L0uisc about the document-function icons. I do not believe that they achieve your stated goal of "user comfort and confidence".

**Comment by SolarGranulation** [comment]
Thank you both, I wondered if I'd gone to far with those. I shall re-edit and go for something more familiar for users, while continuing to address the original concerns.

**Pull request closed without merging**
