### PR TITLE
(3.x) fix 280260: added an option to set the default font for all text types

### PR DESCRIPTION
**Pull request by SKefalidis**
Resolves: 3.x version of #5816 

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [n\a] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by SKefalidis** [comment]
Added button:
image

**Comment by Tantacrul** [comment]
I think it's cool we've addressed this problem. I do think we need a slightly more blunt and discoverable option. I also dislike putting this here. I have a few suggestions for an alteration or two.

**Comment by shoogle** [comment]
@Tantacrul, how does the above compare to my suggestion [here](https://github.com/musescore/MuseScore/pull/5816#issuecomment-748664844)?

**Comment by vpereverzev** [comment]
It's a feature-freeze stage for 3.6 now, so I'll close this PR, because it's a kind of feature that should be implemented carefully.
I suggest to focus on a version for master and consider @Tantacrul UX suggestions.

**Comment by Jojo-Schmitz** [comment]
I'll try merge it into #9000

**Pull request closed without merging**
