### PR TITLE
fix a text

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
to use the same string as the new corresponding inspector_bend.ui

### CODE REVIEW

**Comment by Howard-C** [comment]
Well, tremolo bar properties will be moved eventually...

**Comment by Jojo-Schmitz** [comment]
Moved? Not removed?

**Comment by Howard-C** [comment]
Moved to inspector.

**Comment by Howard-C** [comment]
Yeah, they have the same type of canvases, but they should be different, but right now tremolo bar canvas is completely messed up...

**Comment by Jojo-Schmitz** [comment]
Ok, that text still should get unified

**Comment by Howard-C** [comment]
I'm trying to say I will get it done soon. Probably this weekend :-))) So if this PR isn't merged for a week then it will most probably be unneeded.

**Comment by Jojo-Schmitz** [comment]
See #5585

**Pull request closed without merging**
