### PR TITLE
Fix #110386: Corrected typo for beam32 and added beam64.

### PR DESCRIPTION
**Pull request by njvdberg**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
While at it, why not also add
    getAction("beam64")->setChecked(is.beamMode()     == Beam::Mode::BEGIN64);
in mscore/keyb.cpp, line 151?

**Comment by Jojo-Schmitz** [comment]
and maybe

     { "beam-auto",                    [this]{ cmdSetBeamMode(Beam::Mode::AUTO);

in libmscore/cmd.cpp line 3712?

**Comment by njvdberg** [comment]
For the simple reason I'm very new here and still learning my way around :-(. But thank for the hints, I'll go after it and update the PR a.s.a.p.

**Comment by Jojo-Schmitz** [comment]
You're doing good, no worries ;-) I just searched for other occurences of beam32 and found that, then the beam-auto.

**Comment by njvdberg** [comment]
By the way, I'm looking for more lines I might forgot. Do I need to create a new pull request for these lines or can I "add" them to this pull request?

**Comment by Jojo-Schmitz** [comment]
I'd add to this, and squash, so that there is only one commit.

**Comment by anatoly-os** [comment]
@njvdberg Hi! Did you sign the [CLA](https://musescore.org/en/cla)?

**Comment by Jojo-Schmitz** [comment]
Yes, he did, under the same name even

**Comment by njvdberg** [comment]
On Tuesday, 1 October 2019 16:59:58 CEST anatoly-os wrote:
> @njvdberg Hi! Did you sign the [CLA](https://musescore.org/en/cla)?

Yes, somewhere in May I think.

**Comment by Jojo-Schmitz** [comment]
Seems we missed the chance for the additions I suggested above.
Guess that's for another day and PR then.

**Comment by Jojo-Schmitz** [comment]
Seems we missed the chance for the additions I suggested above.
Guess that's for another day and PR then. 

@njvdberg are you going to look into that?

**Comment by njvdberg** [comment]
> @njvdberg are you going to look into that?

Yes! Sorry, it was unclear for me who was doing what. But I will pick it up.

**Pull request merged**
