### PR TITLE
Fix #269952: allow new templates to be shown in new score wizard w/o restart

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
2.3 counterpart for #3522, shamelessly stealing @finleylau 's code and adjusting it for 2.3 (and recycling an old branch of mine).
Travis failure due to being in Release mode now...

It works fine, I see no reason not to merge #3522 into master.
Merging this here into 2.3 might still be an option, although I understand that such a last minute change is frowned upon.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
FWIW, things have already changed in this respect for 2.3 as a result of the "extension" changes.  It is not the case that things are updated every time you visit Edit / Preferences.  This happens because preferencesChanged() calls updateNewWizard().  If this work for preferences, seems we could take advantage of this and do the same thing here to make this a one-line change?

**Comment by Jojo-Schmitz** [comment]
Feel free to propose this ;-)

**Comment by Jojo-Schmitz** [comment]
Oh, you mean removing all(most) the stuff from this PR and use `updateNewWizard()` instead of `newWizard->updateTemplate();`?

**Comment by Jojo-Schmitz** [comment]
See #3771

**Pull request closed without merging**
