### PR TITLE
fix #46941: corruption on "change voice" command

### PR DESCRIPTION
**Pull request by MarcSabatella**
I fixed the corruption and also completed the implementation of the command.  It actually manages to do something reasonable almost no matter what you have selected, what voice you are moving to, what's in that voice already etc.  It's pretty cool, except I wonder if I went too far.  It might take a little getting used to the fact that pressing a voice button outside of note input mode now will very likely modify your score if you have any notes selected.  I don't know, people do seem to want the feature, but I wonder if it should be a little harder to invoke.

Anyhow, the code works.  If we don't like it, we could always disable it, limit it, require an extra key modifier (eg, hold "Ctrl" while pressing toolbar button), etc.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Here are the different cases handled by this implementation:

1) if the destination voice contains a chord, the source note is moved to that chord (thus inheriting the length of the destination, if they are different)

2) if the destination voice contains a rest, a new chord of the same duration as the destination rest is created to replace the rest, and the source note is moved to that

3) if the destination contains nothing, I create a chord of the same duration as the source chord, call makeGapVoice() to create room for it (eg, shortening preceding chordrests, deleting/shortening subsequent chordrests), insert it, and add the source note to that

4) the source note is removed from the source chord if it contains >1 note; the chord itself is removed if the source chord contains only that note

5) if the source chord is removed and was in voice 1, it is replaced with a rest of the same duration

About the only cases where nothing happens is if the destination contains nothing and the source chord was part of a tuplet.

**Comment by lasconic** [comment]
I believe it would be very useful to have tests for this feature.


1/ Definitely powerful, but not "reversible". A more conservative approach would be to move only if the destination chord has the same length?
2/ idem. A more conservative approach could be to move the note only if the rest is longer, and keep the note duration?
3/ Here too. Maybe move only if there is enough room? and not changing other chordrests? What happens currently if the destination is a tuplet?

5/ if in voice > 1, we are then creating holes?

What happens with tied notes?


I agree that it would probably better to make the feature a bit more hard to use... or we might end up with a lot of scores with 4 voices in no time. It's also easy to "destroy" a score...

**Comment by MarcSabatella** [comment]
These are good suggestions.  For 1) - the cases where the destination voice has a chord in the segment already - changing to only move the note if the durations match makes sense and is of course very easy.  For 2) - the case where there is a rest already - changing to only move the note if the rest is longer - and then probably add a new shorter rest to fill the gap, at least in voice 1, is certainly possible too.

It's 3) that concerns me most.  This is the case that currently could have caused corruption.  It was easy to fix it by calling makeGapVoice(), which automatically fixes things up pretty up.  That's actually easier than *detecting* if there is room, but it should be possible to that as well, and it does seem safer.  I like the idea of thinking in terms of the move being "reversible".

For 5), yes, my code keeps the current behavior of creating holes.  It is of coruse very easy to not do that, and I'd be happy to make that change.  I don't like holes and would be just as happy if we didn't support them, but I know others don't mind them.

I will look into what happens with ties.  My inclination is to skip tied notes for simplicity unless they just magically work.

**Comment by MarcSabatella** [comment]
I like this version much better than my previous one.  It is fully reversible now.  Moving a note never changes its duration.  If there is a chord already in the destination, we move the note only if the durations match.  If there is a rest or nothing in the destination voice, notes are only moved if there is room to create a new chord of the original duration without disturbing the surrounding notes.  Surrounding rests are rewritten as necessary by makeGapVoice(), which also fill any existing gaps.

Tuplets are handled if the source and destination have elements of the same duration (eg, are both already parts of similar tuplets), otherwise they are skipped.

Tied notes are skipped.  It would presumably be *possible* to move tied notes and fix them up afterwards; that's just a whole separate problem I didn't want to deal with.

Rests are now left behind when moving the last note of a chord regardless of voice, to avoid creating holes.  I dislike holes.  User can delete the rests if they feel otherwise.

In testing, I discovered the original implementation also created corruption is when moving a note from a chord that was part of a tuplet, or if parts were present.  Both of these problems are fixed.

The test I added covers all the basic cases in the code, as described above.

It should be pretty foolproof, although I guess I wouldn't be surprised if a sufficiently determined fool were able to find a way to break it :-)

Final note - I also found and fixed what I take to be a bug in expandVoice() - if the element *before* the gap you are expanding was a chord rather than a rest, it was being deleted (replaced by a rest).  I guess we probably don't otherwise ever call expandVoice on a gap like this - those gaps are normally difficult to fill.  I hope I am not misunderstanding the purpose of that function.  If so, we could revert that part of my change, but the result would be that moving a note into a gap using changeVoice() would delete the chord preceding the gap.

**Pull request merged**
