### PR TITLE
Allow for the pasting of lyrics

### PR DESCRIPTION
**Pull request by mattmcclinch**
This pull request allows the user to paste lyrics as in MuseScore 2.x.

### CODE REVIEW

**Comment by mattmcclinch** [comment]
After some testing, it seems the hyphens are not placed correctly. So this is not ready to merge after all.

**Comment by Jojo-Schmitz** [comment]
The hyphen problem is another issue, see https://musescore.org/en/node/21310 and https://musescore.org/en/node/262405

**Comment by mattmcclinch** [comment]
That's true. The same issue occurs when typing in hyphens rather than pasting them.

**Comment by Jojo-Schmitz** [comment]
I believe this one is no longer needed, as we now allow non-breaking spaces, see #3426

**Comment by lasconic** [comment]
You are too fast. The other one is for 2.2 and not merged in master yet.

**Comment by mattmcclinch** [comment]
I can update this PR to include that changes that were merged into 2.2.

**Comment by lasconic** [comment]
it's ok. I will merge this one and cherry pick the other one.

**Comment by lasconic** [comment]
Done. More tests welcome !

**Comment by mattmcclinch** [comment]
It worked on my branch, but doesn't seem to work after being merged into master. [This pull request](https://github.com/musescore/MuseScore/pull/3432) gets it working again, and makes it undoable.

**Pull request merged**
