### PR TITLE
Add an option to show measure number intervals at mmrests

### PR DESCRIPTION
**Pull request by Marr11317**
the MMRestRange is a new class derived from MeasureNumber.
The logic is handled by layoutMeasureNumber, as if it was an usual measurenumber.

MMRestRange may not be styled like MeasureNumber, so a new set of textstyles were added.
There is 3 possible bracketing around the ranges: parentheses, brackets, or none (the default).

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made. though not many. I will probably add some more, even if it needs to be done in another PR

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
rebase needed. Also one mtest failed, see https://travis-ci.org/github/musescore/MuseScore/jobs/680872818#L4294

**Comment by Jojo-Schmitz** [comment]
ping...

**Comment by Marr11317** [comment]
oh yes, thank you. I'll have a look at that today.

**Comment by Marr11317** [comment]
The implementation was functional, but not safe enough. I'll rewrite that in a safer manner.

**Comment by Marr11317** [comment]
There's a problem with CI: it shows an appveyor build. (?)

**Pull request closed without merging**
