### PR TITLE
fix #267549: metronome mark for swing contains several metronome-note and crash

### PR DESCRIPTION
**Pull request by lasconic**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Wrong issue in commit message? Shouldn't that rather be #267549?

**Comment by Jojo-Schmitz** [comment]
Maybe I shouldn't try to understand this in the middle of Rheintal night,  but how is this different from #3350?

**Comment by lvinken** [comment]
Tested and verified OK. Created a test file for this issues, available in my 267549-add-testfile branch on Github. Could you add that ?

**Comment by Jojo-Schmitz** [comment]
I take you mean https://github.com/lvinken/MuseScore/commit/a085fb36634fda4a5e16a3c02420c2847eee1644

**Comment by lasconic** [comment]
Added the test case

**Pull request merged**
