### PR TITLE
Musicxml fixes

### PR DESCRIPTION
**Pull request by lvinken**
Resolves:
https://musescore.org/en/node/299761
https://musescore.org/en/node/305169
https://musescore.org/en/node/305407

Assorted MusicXML export fixes, to improve support for Braille conversion. Would be nice if this made it into 3.5.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
You may want/need to rebase this on top of the 3.x branch (can be done directly on GitHub)

**Comment by lvinken** [comment]
If this PR gets accepted for 3.5, i'll be happy to do whatever is required.

So far I have been unable to find any documentation on the required way of working, given the current state of 3.5.

**Comment by Jojo-Schmitz** [comment]
It is an easy thing to do on Github, under the Edit button (which would also allow to edit the PR title. 
Currently 3.x is the brach to use, unless you explicitly want it in master only.

**Comment by lvinken** [comment]
It seems that did not work well, I think I'd better create a new pull request from branch based on 3.x.

**Comment by Jojo-Schmitz** [comment]
Did you do it on Github, via that Edit dialog?

**Comment by Jojo-Schmitz** [comment]
Maybe that only a works with PRs created before that split

**Comment by lvinken** [comment]
Yes, I did it using Github's edit button, with unexpected result. It offered conflict resolution in Github, which I did not dare try :-). Created a branch off 3.x and cherry-picked the relevant commits. That went down without a hitch. Doing QA now.

**Comment by Jojo-Schmitz** [comment]
Then sorry for the miileading advice

**Comment by lvinken** [comment]
No problem, little time lost. Created https://github.com/musescore/MuseScore/pull/6088, will close this one.

**Pull request closed without merging**
