### PR TITLE
[MU4] Add single stroke caesura

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
it got added with SMuFL 1.4

Resolves: *https://musescore.org/en/node/334302*

Adds a single string to the translations

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Just came up again in https://musescore.org/en/comment/1169310

**Comment by Jojo-Schmitz** [comment]
This one is awaiting review since quite long too

**Review by cbjeukendrup — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Can we get this merged, please

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/348837

**Comment by cbjeukendrup** [comment]
I was wondering one thing, shouldn't we handle it in `ExportBrailleImpl::brailleBreath` too? Or maybe even use `isCaesura` there?

**Comment by Jojo-Schmitz** [comment]
Using `isCasura` is even better

**Review by cbjeukendrup — APPROVED** [review]

**Pull request merged**
