### PR TITLE
[MU4] Code-style fix

### PR DESCRIPTION
**Pull request by Eism**
Updated formatting for lambda(available from Uncrustify 0.68)
image

Force set number of spaces before a trailing or embedded comment
image

Force set one space around assignment operator '=', '+=', etc
image

Force remove space between '>' and '>' in '>>'
image

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I can easily bu1 1. and 4, but 2. and 3. are taking away readability by using spaces to align things

**Comment by Eism** [comment]
@Jojo-Schmitz my opinion on this.
An example of why it is so bad to do it:
one developer added variables
```
int a     = 1;
int abc   = 2;
```

The second developer decided to add abcdef and needs to align the entire column for readability. 
```
int a     _= 1;
int abc   _= 2;
int abcdef = 3;
```
As a result, he touched changes that he did not need, but he is now responsible for them because according to git blame these are his changes.
This is a simplified example, but real :)

**Comment by Jojo-Schmitz** [comment]
It still adds redability to the code, and I'm not at all in favor of changing code style as often as other change their underwear

**Comment by Eism** [comment]
I agree, so I marked it as WIP + DRAFT :)
Just created a place for discussion and find out the opinions of other developers

**Comment by Jojo-Schmitz** [comment]
OK, so you just got my opinion ;-)

**Comment by Eism** [comment]
reverted 
Force set number of spaces before a trailing or embedded comment
Force set one space around assignment operator '=', '+=', etc

**Comment by Jojo-Schmitz** [comment]
3 files under mtest needs to get adjusted.
At least, as I really doubt the code style checker has been adjusted to the recent code moves, so I don't think it really chacks all source files it should be checking

**Comment by Eism** [comment]
reverted
Force remove space between '>' and '>' in '>>'

For now
Do not remove space between '>' and '>' in '>>', just ignore this rule

**Review by igorkorsukov — APPROVED** [review]

**Review by vpereverzev — APPROVED** [review]

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Merged regardless of failing code style tests????

**Comment by igorkorsukov** [comment]
> Merged regardless of failing code style tests????

my mistake...
I thought so, and now I understand that it was a mistake.
I'll fix it.

**Pull request merged**
