### PR TITLE
Fix reading back note-anchored cross-staff spanners from a lower to a higher staff

### PR DESCRIPTION
**Pull request by mgavioli**
If a cross-staff spanner goes from a lower to a higher staff, the start point is saved **after** the end point.

When reading it back, the end point is ignored because a matching start point has not been met yet.

This applies for instance to glissandi from the bass to the treble staff of a grand staff.

Fixed by adding to the XML reader spanner map a temporary place-holder spanner with the end point data, to be looked for when meeting the start point.

This fix only deals with note-anchored spanners.

### CODE REVIEW

**Comment by lasconic** [comment]
Would be great to have tests for this. Maybe with glissando and slurs.

**Comment by mgavioli** [comment]
Added a test for glissando. Slurs are different, as they are chord-anchored, rather than note-anchored; so, this PR does not cover them (and in fact a slur in the same conditions is not read back correctly!)

I have created a new `mtest` dir for "spanners", though, where to add future tests: spanners are of so many element types but of relatively less general kinds (in most case, the anchor type makes the biggest difference), that I thought better to have a single `mtest` dir for all of them, rather than 8 or 9 different directories.

**Comment by lasconic** [comment]
@wschweer can you take a look please?

**Comment by lasconic** [comment]
@wschweer  will be working on a solution for slurs.

**Pull request merged**
