### PR TITLE
Add start hook options in the Properties panel

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #14209

Continuing the work of @Gravifer, who could not finish his PR #15885 due to technical problems.
Scherm­afbeelding 2023-03-07 om 12 53 19

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
@bkunda Could you please check if this does what it should do?

**Review by oktophonie — APPROVED** [review]

**Review by RomanPudashkin — APPROVED** [review]

**Comment by bkunda** [comment]
> @bkunda Could you please check if this does what it should do?

@cbjeukendrup just tested on macOS and I cannot see any "start hook" options (although I can see the settings for "start hook height", but they are, of course, disabled given the absence of the start hook options themselves).

Screenshot 2023-03-14 at 11 02 39 pm

Tested in: OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-230672054, revision: github-musescore-musescore-049474e

**Comment by cbjeukendrup** [comment]
@bkunda Thanks for testing, it should be better now!

**Comment by bkunda** [comment]
> @bkunda Thanks for testing, it should be better now!

thanks, I'll have a look now

**Comment by bkunda** [comment]
🟢 Tested on macOS. FIXED.

One observation: the perpendicular start/end hook lines don't seem to conform to style adjustments (unlike the other hook variants). I gather this is quite a separate issue though: 

Screenshot 2023-03-17 at 11 02 55 am

**Comment by Gravifer** [comment]
So glad this was accomplished:D I have a lot to learn from this

**Pull request merged**
