### PR TITLE
Add basic Guitar Pro 7 support

### PR DESCRIPTION
**Pull request by mvolganli**
I added code to the Guitar Pro 6 (.gpx) importer so that it will also handle Guitar Pro 7 (.gp) files.
I also made some minor modifications which impact the Guitar Pro 6 import (part names and transposition).
I only tested it from command line.

### CODE REVIEW

**Comment by mattmcclinch** [comment]
Thank you for your pull request! Have you signed the [CLA](https://musescore.org/cla)? Under what name?

**Comment by mvolganli** [comment]
I signed it just now, under the name Volganli.

**Comment by mattmcclinch** [comment]
The Travis CI build failed with this message:
```
/home/travis/build/musescore/MuseScore/mscore/importgtp-gp6.cpp:64:31: fatal error: qzip/qzipreader_p.h: No such file or directory
 #include "qzip/qzipreader_p.h"
                               ^
```

**Comment by anatoly-os** [comment]
Congratulations with the first PR to MuseScore project!

Ideally, we would be happy to see unit tests which specify and check new capabilities. See existing ones in mtest/guitarpro for the reference.

Don't hesitate to ask for help in https://t.me/musescoreeditorchat.

**Comment by lasconic** [comment]
There are some test files and a full discussion here : https://musescore.org/en/node/247546#comment-773861

**Comment by Jojo-Schmitz** [comment]
see also #3324

**Comment by mvolganli** [comment]
I removed calls to `part.setPlainLongName()` and `part.setPlainShortName()` from the importer because these were not used, as later in the parsing process `part.setInstrument()` is called, which sets an instrument with default values for `longName` and `shortName`.

I think I will refactor the code to make a GuitarPro7 class as @lasconic did (I missed this PR), and I will see about adding those test files for guitar pro 7.

**Comment by mvolganli** [comment]
I added the test files mentioned by @lasconic. A small number of tests didn't pass at all so I commented them out in `mtest/guitarpro/tst_guitarpro.cpp`. I created reference files for the others after checking that the resulting MSCX could be opened in MuseScore. For most of the GP7 tests the rendered score was similar to what was rendered with the equivalent GP6 tests.

I don't know if this is sufficient for you to take my changes ?

**Comment by Jojo-Schmitz** [comment]
rebase needed

**Comment by Jojo-Schmitz** [comment]
That merge went horrible wrong

**Comment by mvolganli** [comment]
I will close this and make another pull request then.

**Comment by Jojo-Schmitz** [comment]
Not needed, this Pr is not yet beyond repair

**Comment by Jojo-Schmitz** [comment]
Better reopen and fix

**Comment by Jojo-Schmitz** [comment]
Like `git reset --hard 
966162e ; git pull --rebase musesacore master`

**Comment by mvolganli** [comment]
Sorry, I couldn't reopen because I had already deleted my branch. The new PR is here: https://github.com/musescore/MuseScore/pull/5299

**Comment by RJVB** [comment]
> Sorry, I couldn't reopen because I had already deleted my branch. The new PR is here: #5299

Just FYI: I often do that; delete my local branch, then recreate it off the current source branch with my rebased/refactored changes applied, and then force-push it to the remote. Git doesn't care that the branch has been recreated, it only looks at the name and commit hashes. Doing things this way prevents the need for having to squash merge-commits later on.

**Pull request closed without merging**
