### PR TITLE
fix #290445: replace "???" with "…" in palettes

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
more

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
No text needed, there's a toolTip for that and there wasn't a text before either, and sonce some 6 years...
I don't see how color would help here, and I don't have a suitable icon at hand.

**Comment by anatoly-os** [comment]
Looks not good with Dark Theme on Retina display:
image

**Comment by Jojo-Schmitz** [comment]
Too small?

**Comment by anatoly-os** [comment]
I didn't say "bad" :) I find them inconsistent and not properly scaled (which is definitely not our fault). I wouldn't take a decision in a hurry and consult with UI experts who might want to help us or take a look at a dozen of different apps which have the same panel semantic and "More" button.

**Comment by Jojo-Schmitz** [comment]
"not good" is the opposite of "good", so "bad" ;-)

**Comment by anatoly-os** [comment]
Palettes are under reconstruction and refinement right now. Let's see what we can achieve with Tantacrul's help ;)

**Comment by RobFog** [comment]
Um, do you mean the GSoC project or something else? The merging of GSoC won't happen at least until the GSoC over. Why not fix this glaring UI issue now?

**Comment by anatoly-os** [comment]
I mean both the GSoC project and the redesign we started in collaboration with Tantacrul. The official news will be published altogether with the 3.3 Beta release.

**Comment by RobFog** [comment]
Okay, thanks. Fingers crossed this issue gets fixed for the next release. :-)

**Pull request closed without merging**
