### PR TITLE
Import hidden instruments as hidden staves

### PR DESCRIPTION
**Pull request by MarcSabatella**
Resolves: https://github.com/musescore/MuseScore/issues/10951 (partially)

MU4 treats hidden instruments as muted with no possibility of unmuting, which breaks older (3.x and earlier) scores that use invisible playback staves.  The change in this PR acts on import, setting the instrument itself to show but marking the staves of the instrument as invisible.  This allows existing scores to both look and sound as before.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

I did not create a test for this as I am not sure how this should be done.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
rebase needed ;-)

**Comment by MarcSabatella** [comment]
Indeed.  Although I think now that I realize it also applies to MusicXML, it makes more sense to look at how to do this further upstream so the code doesn't need to be duplicated everywhere.  Unfortunately, I don't have any good insight into where that might best be done.

**Comment by Jojo-Schmitz** [comment]
Rebases cleanly without any merge conficts
I believe the MusicXML import issue needs to be dealt with elsewhere and is independant of this

**Comment by MarcSabatella** [comment]
OK, I'll rebase later today when I'm at my other system.  I think this wasn't really considered for mergng because there was a plan to somehow revamp the whole visibility / muting system.  But I have no idea if that's ever going to happen, and meanwhile, it's a shame that scores are getting imported incorrectly.  This is a quick and painless fix.

**Comment by Jojo-Schmitz** [comment]
I had created a new branch off of latest master and cherry picked your commits

**Comment by Jojo-Schmitz** [comment]
See #18229

**Comment by MarcSabatella** [comment]
Thanks!  I'm sure I could have eventually figured out how to do that, but my git skills are still pretty minimal.

**Comment by Jojo-Schmitz** [comment]
Mine ain't much better...

**Comment by Jojo-Schmitz** [comment]
Are you trying it again, or should we leave it at my attempt? Mine fauls some unit tests, need to investogate

**Comment by Jojo-Schmitz** [comment]
@MarcSabatella please double check my unit test fix

**Comment by MarcSabatella** [comment]
I was happy to see your PR and didn't pursue it further :-).  The test fix seems logical to me; the isStaffVisible tag is new for this feature so I can only guess from the fact the test passes that it's being used correctly.  Thanks!

I guess the 206 tests weren't being run when I originally created my PR and that's why it wasn't caught then.

**Comment by Jojo-Schmitz** [comment]
Then I guess you may close this one?

**Pull request closed without merging**
