### PR TITLE
[4.2.1] Minimum drag distance: use physical instead of logical

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: https://github.com/musescore/MuseScore/issues/20743
Ports: #20781

Feel free to close if we really don't want this to be ported

### CODE REVIEW

**Comment by fernandomartin777** [comment]
I don't understand. After it was tested and working why was it not included in MU4.2.1?

**Comment by oktophonie** [comment]
4.2.1 was a patch release intended to fix regressions introduced in 4.2.0 itself. Fixes for older issues, or new features, need to wait until the next point release, i.e. 4.3.

**Comment by fernandomartin777** [comment]
Oh no! +/- six months waiting for a new pointed release. Ok.

**Comment by MarcSabatella** [comment]
Could this be added to 4.3 before it's too late?  We get more and more reports of this on the forums / social media etc.  If it's found via wider testing to cause problems it could of course always be reverted.

**Comment by Jojo-Schmitz** [comment]
#20781 got merged long ago, as far as I can tell before 4.3.0 got forked off

**Comment by RomanPudashkin** [comment]
> Could this be added to 4.3

done

**Comment by cbjeukendrup** [comment]
> #20781 got merged into master long ago (11 Jan), so before 4.3.0 got branched off, 28 days ago.

Except that 4.3 was branched out of 4.2.1 instead of master.

**Comment by Jojo-Schmitz** [comment]
Oops, but as per @RomanPudashkin it is done anyway

**Pull request closed without merging**
