### PR TITLE
Fix #107081

### PR DESCRIPTION
**Pull request by sidewayss**
Scaling is now handled properly in the SVG transform="matrix()"
atribute.

### CODE REVIEW

**Comment by sidewayss** [comment]
Why did this fail?  The code compiles on my machine and runs fine.  It is rebased properly, AFAIK.  Everything looks fine.  What is the problem?  This is my second attempt at a PR from this branch.

**Comment by Jojo-Schmitz** [comment]
The travis fail is not your fault, it fails since d42f0e1

**Comment by Jojo-Schmitz** [comment]
The travis fail is not your fault, it fails since d42f0e1. Should be fixed in 4ae2df6, so should pass after you rebased the PR

**Comment by lasconic** [comment]
I would use isRotating and isScaling, looks less error prone
http://doc.qt.io/qt-5/qtransform.html#isRotating
http://doc.qt.io/qt-5/qtransform.html#isScaling

**Comment by sidewayss** [comment]
Thanks for the info on isRotating and isScaling, but after reading the docs I think I'll stick with the way I have it, which <i>should</i> be the same.  What concerns me in the docs is:
"Note: A rotation transformation of 180 degrees and/or 360 degrees is treated as a scaling transformation."
What makes you think that these functions are more reliable than my checks?  If you read about the way the transforms work, my logic is good.  I just sync'd my latest rebase and it's building again.  If you really want me to switch to IsRotating and inScaling, I will do that.  Let me know.

**Comment by lasconic** [comment]
I'm fine. I thought it would be a more readable way, but indeed the meaning is a bit different.

**Comment by sidewayss** [comment]
It really shouldn't matter if isRotating thinks it's scaling, since all I do is check for rotation or scaling then copy the whole matrix.  But the way the code is now lines up the QTransform with the SVG transform in a more direct way, in terms of aligning the elements and what they mean.

**Comment by sidewayss** [comment]
Why after rebasing did MuseScore commits show up in my branch?  This happened once before, then after another rebase they all went away.  Does this affect the PR in any negative way?

**Comment by lasconic** [comment]
You probably rebased in the wrong way. It looks like you rebased the commits of master on top of your branch instead of your commit on top of master... Yes, it does impact this PR. It can't be merged as it... What I would do... You need to remove the three commits and rebase your commit on top of master.

Or I can copy your changes and commit it directly.

**Comment by Jojo-Schmitz** [comment]
Looks like you did something wrong with the rebase. Try `git pull --rebase musescore master`

**Comment by sidewayss** [comment]
I did everything prior according to the Git Workflow...
I tried git pull --rebase musescore master, and it did not solve the problem.
I tried the interactive amend, but these commits are after my commit, so that doesn't work.
I don't understand "rebase your commit on top of master".  I thought that is what I had done.
I think maybe I need to sync my master with the origin prior to rebasing my branch?  Anyway, I just made a new branch and a new PR here:
https://github.com/musescore/MuseScore/pull/2564
It took a while because I compiled and ran it just to make sure.  I'll close this one later today

**Comment by Jojo-Schmitz** [comment]
Guess this one can get closed now, as #2564 got merged

**Pull request closed without merging**
