### PR TITLE
Fix #112361: Add 4-handed piano part

### PR DESCRIPTION
**Pull request by duck57**
Using the instruments.xml option
so that we don't use the last slot in the solo templates row
and so that other scores can use a 4-hands piano part.

If you have ideas on how to improve the piano defined in instruments.xml, please let me know.
Mainly, is there some way to make one instrument display two instrument names in the score?

### CODE REVIEW

**Comment by lasconic** [comment]
Check the "aeolus-organ" in instruments.xml for how to display multiple instrument names. But be aware that if you define the 4 hand piano as a single instrument then, you can't 1/ extract each piano player to a linked part, 2/ Mix the two piano player independently in the mixer. I guess both are desirable for training purpose, each player with his own piano.

**Comment by duck57** [comment]
1. Are positions beyond `5` defined for a specific position?  I can only seem to get "Primo" to line up properly, but "Secundo" either aligns with the top staff of its part (position 5) or the center of all 4 staves  (seemingly every other numbers I try).
2. Would a template file with two renamed regular piano parts work well enough (for separability), or do you also want separate additional entries in instruments.xml for each player?

**Comment by lasconic** [comment]
As I said earlier I'm not a pianist or a piano teacher, I guess that if you want 4 hand to be easy to make you are one, so you know better how you would use the possibilities. I just want to lay out the pros and cons from a user point of view
A template:
Cons
* take one slot in the solo section
* not sure a 4 hand piano is frequent enough
* AFAIK sib and fin don't have a template
Pros
* you can make parts easily
* you can mute one of the 2 instruments
An instrument
Cons
* No easy parts
* No mixing
Pros
* Do not take a slot in the template grid

**Comment by lasconic** [comment]
Do we have some support from a pianist for this? I hate to add stuff in MuseScore that nobody will use.

**Comment by ajyoon** [comment]
This would be confusing for me, especially considering that piano four hands works usually come with extracted part books so intuitive part extraction is important. It seems simpler to think one player = one staff (or in this case grand staff), as is typical in percussion scores as well.

**Comment by lasconic** [comment]
@ajyoon so you would favor the template.

**Comment by ajyoon** [comment]
yes, or nothing at all

**Comment by MarcSabatella** [comment]
I've seen 4-hand piano music published several different ways:

- as independent parts (which we'd do as a score for two piano with parts , I guess)

- as a full score with full size staves

- as a full score but with with one part (eg, the "teacher" part) in small staves

- a unqiue layout in which the parts are printed on facing pages, so both performers can read from same score with same page turns but each player looking at his own part only

**Comment by lasconic** [comment]
So I would at least remove the instrument and I'm really not sure if we should include a template... I know it seems to make no harm but the more we add templates, the more we will get requests to add templates and in no time, we will have a kazoo quartet template... (no disrespect to kazoo players... but I hope you see my point...)

**Comment by duck57** [comment]
I'll update my commit by removing the instrumens.xml solution and leave just the template file.  Does the template (and template folder selection) otherwise look fine?

**Comment by anatoly-os** [comment]
No more requests for this instrument template. Let's reopen once more requests are obtained.

**Pull request closed without merging**
