### PR TITLE
fixing #21649 MusicXML import & export of any-sized RepeatMeasures

### PR DESCRIPTION
**Pull request by ericfont**
this is a work in progress, still need to test more.  Briefly, the main changes are:
- added a _repeatMeasureSize to RepeatMeasure allowing it to represent a single-measure or any multi-measure repeat.  Subsequent measures covered by a multi-measure repeat will have no chordrest elements in that staff.
- when importing from MusicXML, when find a "measure-repeat" "start" in the xml, will create a new RepeatMeasure of that duration, and then after duration number of measures, will create another RepeatMeasure, until reaching the "stop" tag in the xml.
- when exporting to MusicXML, since the specs require the notes from the original source measure of a measure repeat to be written to that repeat measure, I had to split off the code for exporting measures into a seperate function ExportMusicXml::writeMeasureContents() which could be called either to export notes only or everything but notes (basically).

### CODE REVIEW

**Comment by ericfont** [comment]
have MusicXML i/o tests working for 3 basic cases of single-staff score with measure repeat, still need to do multi-staff export, and I need to get multi-meas repeats working in regular libmscore.

I want to acknowledge that I'm currently producing superfluous backup & forward tags:
```
      <backup>
        <duration>4</duration>
        </backup>
      <forward>
        <duration>4</duration>
        </forward>
```
during measures of repeat.  These occur because have to MusicXML specs require writing original music to the repeat measures.  So I'm first doing a pass through the source measure & writting all notes, and then doing another pass through the repeat measure to write all non-note elements.  Long story short, I would have to rewrite a lot of the code inorder to get rid of those superflous forward & backward tags.  I'm afraid I might introduce an error if I try to mess too much with @lvinken 's original code.  But since these extra tags don't result in an incorrectly-saved MusicXML score, I'd rather not spend a bunch of time trying to avoid them.  I did try a few approaches to avoid unnecessary moveToTick() operations, but halted that effort when things started becoming complicated.

@lvinken , there are a few large blocks of #ifdef 0 in exportxml.cpp, I'm guessing to comment out unused code.  Can I remove them, or is there any reason to keep them around.

**Comment by ericfont** [comment]
yay, those three trival test cases passed on travis:

* testMeasureRepeat_m1_r1.xml   // one single-measure repeat in m2 gets "start" tag, no need for "stop" tag
* testMeasureRepeat_m1_r1_m3.xml  // "stop" tag in m3 because stopped having measure repeats
* testMeasureRepeat_m1_r1_r1_r1.xml // series of single-measure repeats

**Comment by lvinken** [comment]
Hi Eric,

the #ifdef's should stay in. Wrt the "#if 0"'s, none of those was put in by me, so I am not the right person to ask ("git blame" is your friend).

Would like to review your code before it gets merged in, but I am a bit time-limited this week.

**Comment by ericfont** [comment]
I will ping you when this PR is finalized.  I'm going to start working on the multi-measure repeat code inside of musescore...exportxml.cpp might change just a bit more.

sorry for not checking the git blame on the #if 0's, which turn out to be werner's commit https://github.com/musescore/MuseScore/commit/9f933d8503b3060e4f9a3880805ed18fc3fac642

**Comment by ericfont** [comment]
OK, I have MusicXML import & export code working and have tests passing for single-meas & double-meas repeats on multi-part scores with multi-staves.  I think that the exportxml.cpp and importmxmlpass2.cpp are done, so I think ready for @lvinken to take a look at those two files when free.  Let me know if I should change variable names or if something isn't clear, and I can clean up.

I will start working on getting the layout happening and get musescore GUI to add/remove these multi-meas repeats so the main issue 10220 is complete... Would @lasconic want a separate PR for that or combine with this?

FYI, these multi-meas repeat .xml test files do open inside of musescore gui even though I haven't started on layout...If you see a measure of % followed by an empty measure, then that means it is actually a two-meas repeat internally.

**Comment by lasconic** [comment]
I'm fine with a single PR. If it's not too mingled, with two commits? One for MuseScore implementation, one for MusicXML Import/Export?

**Comment by ericfont** [comment]
Ok, well then I guess I'll squash what I have so far and name it "fix #21649 ..." and then when the rest of the GUI/layout is done I will squash those commits as "fix #10220 ..."

**Comment by lvinken** [comment]
Hi Eric,

will have a look at your MusicXML changes, but unfortunately not on short
notice. Probably sometime next week.

Regards, Leon.

**Comment by ericfont** [comment]
no worries.  I'll probably be done with the gui & layout by then.  In the meantime, just ignore any pushes I do to this PR, and I'll ping you when finalized.

**Comment by ericfont** [comment]
FYI, just added repeatmeasure.ui to the debugger which allows you to inspect each RepeatMeasure's internal value of size and slashes.

**Comment by ericfont** [comment]
I've got 2-meas and 4-meas repeats in the palette using the symbols.  I implemented dropping on score.  Will remove all chord rests from the measures that the mutli-measure repeat covers, and will have the multi-measure chordrest on first measure only.  

@lasconic, May I move RepeatMeaure up one level in the hierarchy to be a direct descendant of ChordRest instead of Rest, which it currently is...logically it is not a Rest.

**Comment by lasconic** [comment]
Sure, if it doesn't need anything from Rest, go ahead.

**Comment by ericfont** [comment]
ok thanks...I might do that.

Looks like I broke the .mcsx output for single-measure repeat with my last push.  Anyway I should ask if you have any preferred way to save the multi-measure repeats in the mscx?  The first measure of each multi-measure rest (in my current internal representation) contains the multi-measure repeat element, and subsequent measures that are covered by the multi-measure repeat don't have any chordrests.  Should I just write out .mscx in that same way it is internally represented?

**Comment by lasconic** [comment]
@wschweer any input on that?

**Comment by lvinken** [comment]
Hi Eric,

Had a look at the current state (b74c6d4). You obviously put in a lot of effort, thanks for that. 

Unfortunately, it does not yet work completely. I get segfaults on import for three testfiles, two other testfiles do not compare correctly after export.

Furthermore, the musicxml autotester should verify that all features supported are imported correctly and then also exported without changes. Most (all ?) of your tests simply import a file created by a different application and verify the resulting MuseScore output is still the same, without actually verifying correctness. I would expect all testfiles to be produced by MuseScore, have a pdf file that illustrates what it should look like after import and export unchanged.

Finally, I still have to review the actual code changes (had a quick look, part of it is OK, part of it still to check). Quite a lot of MusicXML import/export code was moved or refactored, making review somewhat difficult.

Regards, Leon.

**Comment by ericfont** [comment]
Sorry I had left this in a failing state.  There are some segfaults I need to fix that result from measures not contacting any segments other than barline.  I also need to implement the .mscx storage format for these multi-measure repeats.

I didn't know exactly how tests should be for this, but thanks for telling me...I will generate tests from inside musescore for every behavior.  I had started with those xmls generated from finale and sibelious because I didn't want to "bootstrap" without some known correct XML files to start with.

**Comment by dmitrio95** [comment]
Needs actualization for current master

**Pull request closed without merging**
