### PR TITLE
Add missing glyphs in Gootville

### PR DESCRIPTION
**Pull request by rettinghaus**
Resolves: 
https://musescore.org/en/node/125251
https://musescore.org/en/node/125191
https://musescore.org/en/node/310421
https://musescore.org/en/node/312877

added glyphs:
- 4stringTabClef
- fermataLongHenzeAbove
- fermataLongHenzeBelow
- fermataShortHenzeAbove
- fermataShortHenzeBelow
- breathMarkTick
- breathMarkUpbow 
- caesuraThick
- caesuraShort
- breathMarkSalzedo

fixed glyphs:
- fixed scaling in timeSigParensLeft
- fixed scaling in timeSigParensRight
- fixed position of octaveParensLeft
- fixed position of octaveParensRight

Also this updates the metadata file, which before was just a copy of the metadata file coming from Bravura. Now it contains the correct bounding box informations.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [ ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Why is the change to fonts/gootville/metadata.json  so huge?

**Comment by rettinghaus** [comment]
Basically yes. It now only reflects the glyphs actually contained in the font.

**Comment by Jojo-Schmitz** [comment]
I guess the vtest differeneces are to be expected?
Almost all look pretty small and harmless except maybe the one for ornamets?

**Comment by Jojo-Schmitz** [comment]
@rettinghaus maybe you'd like to check https://musescore.org/en/node/319778, esp. the part of the issue with the gap, apparently cause by your changed to the engraving defaults, esp. those for `stemThickness` (0.12 to 0.076) and `staffLineThickness` (0.13 to 0.08)

**Comment by Jojo-Schmitz** [comment]
Yes, it does...

**Pull request merged**
