### PR TITLE
fix #282234: last bar of volta breaks mmrest

### PR DESCRIPTION
**Pull request by MarcSabatella**
Looks like we're breaking for the end of the volta twice - the first time correctly, the second time incorrectly.  I removed the second check and added a comment to the first.

### CODE REVIEW

**Comment by anatoly-os** [comment]
Script test and/or mtest should cover the issue, shouldn't they?

**Comment by MarcSabatella** [comment]
Sure.  I haven't created a script test before, sounds "fun"...

**Comment by anatoly-os** [comment]
Looks like the code you removed fixed the https://musescore.org/en/node/44466. See Werner's https://github.com/musescore/MuseScore/commit/16764d461490cdcfc122b14ce9403b6634f968f4.

**Comment by MarcSabatella** [comment]
True, but I don't believe those lines actually were the ones responsible for the fix - it was a big commit.  Anyhow, thanks for the thorough review!  I have now verified that none of the problems described in that issue exist with my fix, and thinking through the code further, I am confident that code was not needed given the similar but better code a few lines above (where I added the comment).

**Comment by MarcSabatella** [comment]
FWIW, looks like this was never included in 3.0.x

**Pull request merged**
