### PR TITLE
Add keyboard shortcuts for up bow and down bow symbols

### PR DESCRIPTION
**Pull request by divya-urs**
Fix #152766

### CODE REVIEW

**Comment by lasconic** [comment]
Hi, thank you for your PR.
You need to squash all commits together, see http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
The resulting commit should have a message "fix #152766: Add keyboard shortcuts for up bow and down bow symbols".
And I need you to sign the MuseScore contributor license agreement at https://musescore.org/en/cla so I can merge your work.

**Comment by divya-urs** [comment]
Okay, I will do that.

**Comment by lasconic** [comment]
Try to keep the discussion public.
The changes don't need to be on your master branch. In fact they shouldn't. Just follow the instructions from [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html). So go to your branch `git checkout add_keyboard_shortcut` and run `git rebase -i HEAD~9`. Squall all commits but one and change the commit message. Then, check the history with `git status` and force push your changes. 
If you need a crash course on git, check https://musescore.org/en/developers-handbook/git-workflow 
If needed, you can find me on IRC https://kiwiirc.com/client/irc.freenode.net/?nick=musescore|?#divya

**Comment by lasconic** [comment]
Nope, that's not good. As you can see, the history is a mess :)

**Comment by divya-urs** [comment]
I'm very sorry. I'll try to fix this. It may take some time though.

**Comment by divya-urs** [comment]
I've made another branch with the necessary modifications. There's only one commit in that branch. Can I close this pull request and create another pull request from that branch?

**Comment by lasconic** [comment]
Sure. I close it for you.

**Pull request closed without merging**
