### PR TITLE
Update marching percussion instruments and shortcuts

### PR DESCRIPTION
**Pull request by zacjansheski**
Update marching percussion instruments and shortcuts in spreadsheet. Run python script and update instruments.xml

Resolves: #NNNNN 

- [ ] I signed the [CLA](https://musescore.org/en/cla)
- [ ] The title of the PR describes the problem it addresses
- [ ] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [ ] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ ] There are no unnecessary changes
- [ ] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by zacjansheski** [comment]
@shoogle and @oktophonie 

The idea here is to make our marching music look more like this https://www.youtube.com/watch?v=0ctEyZ3gekQ&t=3s

Let me know if you have any questions.  I will need some assistance updating the templates (changing 5-line staves to single line staves)

**Review by shoogle — APPROVED** [review]
@zacjansheski, I know very little about percussion. If you're happy with these changes then I'm happy!

On thing I'll say in case there are any more big changes coming: we've planned for a while to remove instrument definitions from the templates, so the templates would just contain a list of instrument IDs and then MuseScore would fill in the rest of the instrument details (staff, clef, etc.) automatically based on what's in instruments.xml.

We've also planned to split instrument definitions from notation definitions, so the instrument ID `marching-snare` would just represent the physical instrument, and then you could choose between different ways of notating it (e.g. `perc1line`, `perc5line`) as a separate option in the New Score dialog.

We've actually never got round to doing these things, but if we did it would make changes like this a lot easier.

**Comment by MarcSabatella** [comment]
> we've planned for a while to remove instrument definitions from the templates, so the templates would just contain a list of instrument IDs and then MuseScore would fill in the rest of the instrument details (staff, clef, etc.) automatically based on what's in instruments.xml.

Hmm, hopefully that would be only for settings that haven't changed from the default?  One of the things people use templates for is to create scores with instrument customizations already filled in - custom staff names, custom guitar tunings, custom transposition or playable range settings, etc.  Of course, in MU3 they also would use custom instruments.xml files and add the instruments in a score created "from scratch", but this capability is gone for now at least.  If it were to come back, then it would make sense for templates to refer to those custom instruments.xml definitions, and that would potentially be even better than templates.

**Comment by shoogle** [comment]
We can certainly keep adjustments from defaults in the templates.

**Comment by zacjansheski** [comment]
@oktophonie I don't think these are quite there yet, but definitely an improvement.  Are you ok with a merging?

**Review by oktophonie — APPROVED** [review]

**Pull request merged**
