### PR TITLE
make extension file size suffixes translatable

### PR DESCRIPTION
**Pull request by Howard-C**
Kind of a follow-up for #5405, but not really, it's a bug existing before. First brought up in #5513.

### CODE REVIEW

**Comment by dmitrio95** [comment]
As far as I understand, this will likely break `operator<()` for `ExtensionFileSize` which relies on a proper Latin character being in a text of this item on a certain position. It also looks like `operator<()` for `LanguageFileSize` also has the same kind of issue. I believe this is what @Jojo-Schmitz mentioned in #5513.

**Comment by Howard-C** [comment]
Are you suggesting that if the strings are translated, the character won't be recognized?

**Comment by Howard-C** [comment]
`LanguageFileSize` doesn't have this problem, the `<` operator for it doesn't deal with non-numeric strings.

**Comment by dmitrio95** [comment]
Yes, that character may happen to be absent in a translation or be at another position. `LanguageFileSize` should also be affected because of this line:
https://github.com/musescore/MuseScore/blob/b083d12865e13fa78c607027fe6ef62fe1ecdfdd/mscore/resourceManager.cpp#L102
so it also relies on the assumption that text consist of a number, a space and `K` and `B` characters.

**Comment by Howard-C** [comment]
What if we make both cases untranslatable? I don't actually see why these suffixes should be translated anyway...

**Comment by dmitrio95** [comment]
Like I have already mentioned in https://github.com/musescore/MuseScore/pull/5441#discussion_r342505466 and https://github.com/musescore/MuseScore/pull/4672#issuecomment-486867135, international measurement units are spelled differently in different languages and it would be better for localization to be able to adapt to this. As for `operator<` implementation, maybe we could pass a custom [type](https://doc.qt.io/qt-5/qtablewidgetitem.html#QTableWidgetItem-1) to a constructor of `QTableWidgetItem` and implement `operator<` by casting its argument to the same type:
```
bool LanguageFileSize::operator<(const QTableWidgetItem& nextItem) const
      {
      if (nextItem.type() != type())
            return false;
      return getSize() < static_cast<const LanguageFileSize&>(nextItem).nextSize();
      }
```

**Comment by Howard-C** [comment]
This is in fact a very very good idea. I'll try this in the next few hours.

**Pull request merged**
