### PR TITLE
Revert a change to google analytics that causes issues on Mac

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
to fix an error I introduced in #6588. See also https://musescore.org/en/node/311571

Also give credit where credit is due (including a rename of the directory).
Disable deprecation warnings for Apple too.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Mac build fails, but for an entirely different reason, not related to this PR as far as I can tell

**Comment by mattmcclinch** [comment]
We probably want this function to return the same values as it did before, since it is used to format the HTTP header for sending Google Analytics results. The changes to the macOS side accomplish this; the changes to the Windows side do not.

**Comment by Jojo-Schmitz** [comment]
I'll have another look tomorrow evening or Sunday. Unless are getting ahead, which I wouldn't mind

**Comment by Jojo-Schmitz** [comment]
I've removed the changes for Windows

**Comment by Jojo-Schmitz** [comment]
Alternative approach would be to revert that part of #6588, as this is third party code we probably should not be modifying (without an urgent need) anyway

**Comment by Jojo-Schmitz** [comment]
Guess I'd better squash them. Unless we want those changes from the 1st commit, in which case I'd need to amend the 2nd. Just let me know

**Comment by mattmcclinch** [comment]
The only reason to modify this third party code would be to get rid of the deprecation warnings, and if we wanted to do that properly, it would probably involve changes to more than just this macOS-specific code. And if we were thinking about sending changes upstream, we would need to make sure only to use QOperatingSystemVersion `#if (QT_VERSION >= QT_VERSION_CHECK(5, 9, 0))`.

**Comment by Jojo-Schmitz** [comment]
The deprecation warnings had been taken case of long ago, by disabling them in CMakeLists.txt

**Comment by mattmcclinch** [comment]
I don't know which version of Xcode you use on your Mac, but I get 33 deprecation warnings for google_analytics.

**Comment by Jojo-Schmitz** [comment]
I don't use Xcode at all (als this problem hadn't happened). And indeed the warnings are disabled only for MSVC and MinGW (in thirdparty/google_analytics/CmakeLists.txt). Feel free to (tell me how to) add ignoring those for Xcode too.

**Comment by mattmcclinch** [comment]
Where it says
```
    if (MINGW)
        set_target_properties( google_analytics PROPERTIES
          COMPILE_FLAGS "-Wno-deprecated-declarations"
        )
    endif (MINGW)
```
changing `if (MINGW)` to `if (MINGW OR APPLE)` seems to do the trick.

**Comment by Jojo-Schmitz** [comment]
Easy enough :-), I'll add it.

**Comment by mattmcclinch** [comment]
Great! But don't you want to squash the 2 commits?

**Comment by Jojo-Schmitz** [comment]
Patience ;-)

**Review by igorkorsukov — APPROVED** [review]

**Pull request merged**
