### PR TITLE
Prevent adding two staff type changes to the same measure (fix #301848)

### PR DESCRIPTION
**Pull request by Howard-C**
This automatically fixes issues (discovered and potential) like https://musescore.org/node/301848.

### CODE REVIEW

**Comment by Marr11317** [comment]
Shouldn't the PR's title be "Prevent ... to the same **element**"?

**Comment by Howard-C** [comment]
> Shouldn't the PR's title be "Prevent ... to the same **element**"?

No, staff type change can only apply to a measure.

**Comment by Howard-C** [comment]
> it might be easier just to search for the existing staff type change directly in staff (which has a list of staff type changes)

As for this, is it deliberate that you cannot access `_staffTypeList` outside `Staff` class? There isn't a public port for that.

Also, is there any good way to search for a staff type change element without searching through the list of staff types?

**Comment by dmitrio95** [comment]
> As for this, is it deliberate that you cannot access `_staffTypeList` outside `Staff` class? There isn't a public port for that.

It could make sense to give an access to StaffTypeList by a const reference, but better not direct editing access to StaffTypeList from outside of Staff.

> Also, is there any good way to search for a staff type change element without searching through the list of staff types?

StaffTypeList is a map internally so lookup in it doesn't require iterating over all elements. For the purpose of this pull request maybe something like [this](https://github.com/musescore/MuseScore/pull/5745/files#diff-a44fcad707a9c5c4401aa0b391f9f879R106-R116) would make sense, so you  could check if there is a staff type change at the given tick.

**Comment by Howard-C** [comment]
> For the purpose of this pull request maybe something like [this](https://github.com/musescore/MuseScore/pull/5745/files#diff-a44fcad707a9c5c4401aa0b391f9f879R106-R116) would make sense, so you could check if there is a staff type change at the given tick.

But this will require your PR to be merged first, right?

**Comment by Howard-C** [comment]
Yeah I'll just close this before I find any good solution...

**Pull request closed without merging**
