### PR TITLE
Respect plugins' `requiresScore: false`

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #13162

### CODE REVIEW

**Review by Jojo-Schmitz — APPROVED** [review]
Resolves the issue

**Comment by RomanPudashkin** [comment]
As far as I can tell, none of our standard plugins use this API. So why do we need to fix it?

>To Reproduce
Load and and activate the batch-convert plugin.

This plugin won't work in 4.0 anyway

**Comment by Jojo-Schmitz** [comment]
Why won't it work?

**Comment by Jojo-Schmitz** [comment]
Hmm, well, it in does, reports "ERROR on reading [file]"

**Comment by Jojo-Schmitz** [comment]
Which means that `readScore(fileFullPath, true)` fails, for siome reason. So it seems there's another bug in the Plugin framework

**Comment by cbjeukendrup** [comment]
That method is indeed not implemented at the moment.

**Comment by Jojo-Schmitz** [comment]
Reported in #13593

**Comment by jeetee** [comment]
> none of our standard plugins use this API. So why do we need to fix it?

Because of existing MS3 plugins using it?

**Comment by cbjeukendrup** [comment]
> So why do we need to fix it?

Also, why would we _not_ fix it? It might make some people a bit happier, with minimal effort 🙂

**Comment by Jojo-Schmitz** [comment]
What's holding this PR from getting merged?

**Comment by Jojo-Schmitz** [comment]
It is not just Batch Convert that would benefit from this, but also ABC Import. The workaround of having to open another unrelated score is just nasty and annoying

**Comment by cbjeukendrup** [comment]
Rebased. @RomanPudashkin Could you please review and merge this? I don't really see any disadvantages, and it would make some people a tiny bit happier, so why not :)

**Comment by Jojo-Schmitz** [comment]
It is the lesser of the 2 issues the ABC plugin has (the other being the missing file I/O API). Still worth having it fixed though

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
