### PR TITLE
[MU3] Fix #314899: Identical expression

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: https://musescore.org/en/node/314899

Same fix needed in master, see #7180, or #7627, both closed by now.
And see #8762, which brought this up again.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
The mtest fail (https://github.com/musescore/MuseScore/pull/7179/checks?check_run_id=1622482883#step:5:762) seems to be the result of this PR's change, and reveal a real bug for a change.

**Comment by AntonioBL** [comment]
The crash is caused by an assert at line 104 of importexport/midiimport/importmidi_simplify.cpp
` QFATAL : TestImportMidi::voiceSeparationTuplet() unknown: ASSERT failure in Simplify::lengthenNote: "Too short note durations remaining", file /media/antonio/Mint0/MuseScore/importexport/midiimport/importmidi_simplify.cpp, line 104`

**Comment by AntonioBL** [comment]
And I think that in master importmidi mtests are not being tested at the moment.

**Comment by Jojo-Schmitz** [comment]
It had to be one of those 4 Q_ASSERT_X, but why?

**Comment by AntonioBL** [comment]
By using a break at that X_ASSERT (line 104 in 3.x and line 102 in master), the noteDurations list is:
first    second
2/2     1/16 dots 0
2/2     1/128 dots 0
2/2     1/512 dots 0
which gives sum = 37/512, while the desiredLen (offset - DurationStart) is 7/96.

**Comment by Jojo-Schmitz** [comment]
Close but not the same

**Comment by Jojo-Schmitz** [comment]
Guess a case of "never check for error conditions you can't handle"

**Comment by Jojo-Schmitz** [comment]
Need to introduce an epsilon for this apparent floating point comparison?

**Comment by Jojo-Schmitz** [comment]
The tuplet_3_5_7_tuplets test produces a corrupt MuseScore file (in 3.5.2)

**Comment by AntonioBL** [comment]
tuplet_3_5_7_tuplets.mid is imported exactly as the reference if "Split staff" is unchecked. And indeed in the mtest there is `data.trackOpers.doStaffSplit.setDefaultValue(false, false);`

**Comment by Jojo-Schmitz** [comment]
For me that .mid file crashes with an assertion failure on load (in a debug build). Only when importing in a non-debug build I couls save it as mscz (but without using any of those options) and got that corrupt score.
Anyway; I think this crash might be a red herring, as it crashes in an entirely different place, one that my change can't possibly have caused.

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Want me to port it over to master?

**Comment by Jojo-Schmitz** [comment]
That "Thumbs up" doesn't notify...
Anyway, see #8849

**Pull request merged**
