### PR TITLE
Removed an accidental ledge from stem

### PR DESCRIPTION
**Pull request by vpereverzev**
Inspired by the request from @Tantacrul and @oktophonie

Before:

Снимок экрана от 2020-10-23 17-06-14

After:

Снимок экрана от 2020-10-23 17-04-11

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
> Wouldn't then the Flag need that extra round cap?

Good question; I would be interested to see how it looks if the top of the flag does not coincide with a staff line, so, if the note is one line higher.

**Comment by Jojo-Schmitz** [comment]
Just flat.

**Comment by Jojo-Schmitz** [comment]
Funny, regardless the vtests label the vtests get reported as failing?

**Comment by Jojo-Schmitz** [comment]
I'm pretty sure the mtest failure is not this PR's fault, got to be the one just before mine (from PR #6776), @vpereverzev ?

**Pull request merged**
