### PR TITLE
fix #239181: make fret diagrams accessible for screenreaders

### PR DESCRIPTION
**Pull request by jthistle**
Resolves: https://musescore.org/en/node/239181

Sample output for fret diagram below:

'Fretboard diagram with chord symbol C minor, 6 strings, string 1 cross marker, string 3 dot on fret 5, string 4 2 dots on frets 5 and 6, string 5 dot on fret 4, partial barré fret 3 starting string 2'

image

### CODE REVIEW

**Comment by RobFog** [comment]
Perhaps add "+ collect_artifacts" to the commit message so that testers (@MarcSabatella and blind people) can try a build?

**Comment by igorkorsukov** [comment]
rebase needed

**Comment by anatoly-os** [comment]
@jthistle rebase is needed

**Comment by jthistle** [comment]
@anatoly-os rebased

**Pull request merged**
