### PR TITLE
change "Lyrics Line Segment" to "Melisma Line Segment"

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
to match "Melisma Line"

### CODE REVIEW

**Comment by mgavioli** [comment]
I appreciate the consistency but, as it is also used for dashes and not only for melismas, perhaps it would have been better to uniform both to "Lyrics Line" (unless in English "melisma" covers both usages).

**Comment by MarcSabatella** [comment]
It doesn't.  *Some* hyphens represent melismas, but only if there two or more in a row, so a single syllable extends over multiple notes.

**Comment by lasconic** [comment]
Let's revert it then.

**Comment by Jojo-Schmitz** [comment]
If so, both need to get changed, "Melisma Line" and "Melisma Line Segment", right? Or does one have a different meaning than the other?

**Pull request merged**
