### PR TITLE
Fix #20962: Keep selection when deleting, changing note/rest lengths

### LINKED ISSUE #13469: [MU4 Issue] When deleting a chord, the resulting rest is deselected; when dotting a chord, the chord is deselected
**Describe the bug**
An inconsistency and minor annoyance more than a 'bug'.

When deleting a note, the rest that replaces it remains selected. When deleting a _chord_, the rest is not selected, and therefore must be manually selected in order to perform any further operations. (This is a regression from 3.6.)

https://user-images.githubusercontent.com/20604032/192023927-facd5d00-c92c-491c-990f-7ad0a204c1e5.mp4

Presumably somewhat related: when adding an augmentation dot to a note, the note remains selected. When adding a dot to a _chord_, the chord is deselected:

https://user-images.githubusercontent.com/20604032/192026248-c7271944-e5a0-4603-91ab-138929dbcf13.mp4

This is actually not a regression from 3.6, but it is an inconsistency.

---
Note: regarding this latter case, a chord can be selected in two ways. Either by Ctrl+clicking each of its notes:
image
or by clicking the first note then Shift+clicking another, whereupon it becomes a 'range' of one chord:
image
In the former case, it seems unarguable (famous words) that the resulting rest should remain selected. In the latter case, it appears logical for nothing to remain selected - a range could span any number of chords. However, is there a case to be made for an exception where the range spans only one duration, so that the rest remains selected?

The reason I mention this relates specifically to bar rests. It is much easier (and feels natural) to select the bar by clicking somewhere on it - rather than precisely on the bar rest symbol itself, which is a much smaller target. That selects the whole bar as a range:
image
At this point one can enter notes immediately by typing letter names. The first note created will be selected. If, instead, you choose a _duration_, then the bar rest splits to begin with a rest of that duration; that first rest, however is _not_ selected. If you then proceed to type letter names to input notes, they will actually be input wherever was _previously_ selected in the score (which could be anywhere), rather than where the new rest was just created:

https://user-images.githubusercontent.com/20604032/192092205-468de997-298d-44f9-be71-219e651f1e8b.mp4

### LINKED ISSUE #20962: Changing duration of multiple notes should leave all selected
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When selecting multiple notes (list selection):
image
Changing their duration (selecting a note duration, or adding dot(s)), either via the toolbar or the relevant keyboard shortcuts, then leaves nothing selected:
image
When it would be far more useful if the originally selected notes remained selected:
image
(which does happen when adding articulations from the toolbar, for example)

Curious exception: selecting multiple _rests_ and adding a dot to them will leave the first rest selected.

I'm not entirely sure what should happen in the case of a range selection.

Not unrelated: https://github.com/musescore/MuseScore/issues/20720 (and indeed https://github.com/musescore/MuseScore/issues/13469)

### MuseScore Version

4.2

### Regression

No

### PR DESCRIPTION
**Pull request by XiaoMigros**
Resolves: #20962
Resolves #13469

When changing the duration of several selected notes or rests at once, those notes or rests remain selected.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by XiaoMigros** [comment]
Haven't quite gotten range selections working when the chordrests get longer yet- it selects up until the end of the score instead. interestingly it works fine after ctrl z+y

**Review by oktophonie — APPROVED** [review]

**Comment by oktophonie** [comment]
Behaviour not perfect in a case where multiple notes or rests are converted to tuplets, but this is a wider problem with tuplet generation which should be solved separately and generally. In other cases it works as expected (when multiple notes are changed, they are list-selected).

**Review by bkunda — APPROVED** [review]

**Comment by bkunda** [comment]
@XiaoMigros the macos build failed on this one. Could you please retry?

**Comment by cbjeukendrup** [comment]
I've restarted it

**Comment by bkunda** [comment]
🟢 Re-tested on macOS. Approved.

**Review by cbjeukendrup — APPROVED** [review]

**Pull request merged**
