### PR TITLE
Remove mingw32.mingw.cmake

### PR DESCRIPTION
**Pull request by lasconic**
I tried compile MuseScore with Qt Creator in Windows 10 for the first time since Qt creator 4. INstructions are https://musescore.org/en/node/116991 are very helpful but I was not very confortable editing the kit and appending reference to MuseScore there. Also, we have a pull request for Qt 5.9.0 on Windows https://github.com/musescore/MuseScore/pull/3191 but Qt 5.9.1 is coming etc... On windows, we need to change mingw32.mingw.cmake every time we want to use a new version of Qt. 
This PR aligns the behavior of the windows build with the other platforms and so pick Qt and the toolchain (gcc etc...) from the PATH. Tests very welcome. You will need to compile from scratch.

```
git checkout -b lasconic-win_build_no_qt 2.2
git pull https://github.com/lasconic/MuseScore.git win_build_no_qt
```

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Should we need to do anything else in terms of updating QtCreator kit or project settings?  This is for 2.2?

**Comment by lasconic** [comment]
I'll work on the same one for master. We should be able to let the QtCreator kit alone, or just delete the CMAKE_CXX_COMPILER in the default kit cmake configuration since it messed up with the project configuration in Qt Creator 4.2.2.
Again the two big wins are:
1. No need to update the code to change Qt version (if there is nothing else changing of course). It also means we can build with several Qt version without changing the code.
2. No need to change the cmake configuration in the Qt Kit (and so the ability to reuse the kit in other project...)

**Comment by AntonioBL** [comment]
I think one of the biggest change in this case is that for a debug build the link with this PR happens against Qt debug libraries instead of usual runtime libraries (e.g. Qt5Cored.dll instead of Qt5Core.dll). Therefore the execution is (much) slower and the "*d.dll" libraries are needed in the bin directory to run MuseScore.
This was not happening before because the link was made against QT_mingw_LIBRARIES which hardcoded the name of the non-debug dlls, while for the QT_LIBRARIES case the non-debug and the debug dlls are chosen accordingly to the CMAKE_BUILD_TYPE variable.

**Comment by Jojo-Schmitz** [comment]
With Qt-5.9 we also need to get rid of a dll, Qt5CLucene.dll, but need it in older versions. Similar things happened with earlier version changes

**Comment by lasconic** [comment]
@AntonioBL  that's inconvenient indeed... Why is it so slow though?

**Comment by Jojo-Schmitz** [comment]
Still in the pipeline? Works quite nicely in master, but 2.x is tied to Qt 5.4 anyway, so there's only limited usefulness here, isn't it?

**Comment by lasconic** [comment]
Exactly my thinking. It's not really needed in 2.2 and I wanted to see how well it works in master. I keep it open a bit more just in case.

**Comment by lasconic** [comment]
Let's stay like this for 2.2.

**Pull request closed without merging**
