### PR TITLE
[MU4] Minor tweaks to Parts dialog

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/11420
Resolves: https://github.com/musescore/MuseScore/issues/11349
Resolves: https://github.com/musescore/MuseScore/issues/11154
Resolves: https://github.com/musescore/MuseScore/issues/11356
Resolves: https://github.com/musescore/MuseScore/issues/11359

### CODE REVIEW

**Comment by RomanPudashkin** [comment]
@mccoydtromb 

> Is this a good place to add the keyboard functionality in the same PR?

What kind of functionality do you mean? :)

**Comment by mccoydtromb** [comment]
> @mccoydtromb
> 
> > Is this a good place to add the keyboard functionality in the same PR?
> 
> What kind of functionality do you mean? :)

Sorry, should have been more specific. It's from this Issue: #11848, requesting to use keyboard to select combinations of parts to open.

**Comment by RomanPudashkin** [comment]
> > @mccoydtromb
> > > Is this a good place to add the keyboard functionality in the same PR?
> > 
> > 
> > What kind of functionality do you mean? :)
> 
> Sorry, should have been more specific. It's from this Issue: #11848, requesting to use keyboard to select combinations of parts to open.

I see. This functionality is definitely very important. But this is a global problem, not just in this dialog. In other parts of the app, we can't use these keyboard shortcuts to select anything either. So this task should be treated separately from this PR. But it looks like the solution to this problem will be quite straightforward because we just need to improve the basic components that are used in this dialog and throughout the app

**Comment by DmitryArefiev** [comment]
Tested #11420 #11349 #11154 #11356 #11359 on Win10, Mac12, LinuxMint 20.2 - **FIXED**

**Pull request merged**
