### PR TITLE
fix #139641: Do Shape note misaligned with stem (Emmentaler)

### PR DESCRIPTION
**Pull request by vinayakvivek**

### CODE REVIEW

**Comment by lasconic** [comment]
Thank you! I need you to sign the MuseScore CLA https://musescore.org/en/cla in order to be able to merge your PR.

**Comment by vinayakvivek** [comment]
@lasconic signed it. :)

**Comment by lasconic** [comment]
What about half notes ;) ?

**Comment by lasconic** [comment]
Could you fix the half note too? And then squash the two commits together. See http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by vinayakvivek** [comment]
@lasconic  Done :)

**Comment by lasconic** [comment]
Thank you and welcome in the MuseScore contributor community ! You are the 90th person who contributed some code to MuseScore. Congrats!

You can find more easy (and with a bit more code) issues here https://musescore.org/en/project/issues/search/musescore?tags=easy
Feel free to pass by IRC to celebrate and find another issue to work on!

**Pull request merged**
