### PR TITLE
Adding Spanish Bandurria and Spanish Laud popular instruments

### PR DESCRIPTION
**Pull request by manolo**
References:
Spanish Bandurria: https://en.wikipedia.org/wiki/Bandurria
Spanish Laud:  https://en.wikipedia.org/wiki/La%C3%BAd

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
instrumentsxml.h needs have these added too, either manually or by running generateTS.py

**Comment by manolo** [comment]
Run the python script and updated the `.h` file. Thanks

**Comment by Jojo-Schmitz** [comment]
If for Laud the long and short name is identical, why a dot after the short?

**Comment by manolo** [comment]
You are right, removed the dot.
Also changed the cleft for Laud, that should match classic guitar.

**Comment by Jojo-Schmitz** [comment]
Did you sign the [CLA](https://musescore.org/cla) meanwhile?

**Comment by manolo** [comment]
Signed

**Comment by Jojo-Schmitz** [comment]
rebase needed

**Comment by anatoly-os** [comment]
@manolo thank you very much for your first contribution to MuseScore! I created the rebased version of this PR: #5912. The changes you've made will be in public release, soon. Cheers!

**Comment by Jojo-Schmitz** [comment]
As per https://en.wikipedia.org/wiki/La%C3%BAd it is "Laúd", not "Laud" even in English?

**Pull request closed without merging**
