### PR TITLE
Fix metronome bug #87266

### PR DESCRIPTION
**Pull request by tobiatesan**
This is my attempt to fix the issue in #87266.

It seems to work fine with the example provided, with regular measures and with loops started at 
arbitrary points.

Odd time signatures and count-ins seem to work similarly well.

However, I don't completely understand what the original author was trying to do by adding clicks to an incomplete measure, so perhaps it would be best if somebody familiar would review it.

4e2eadf7 is about using a "Tock" only on the first beat, so that an incomplete measure does not start with a "clack" - i.e. in "Happy Birthday To You", as notated here (https://upload.wikimedia.org/score/d/x/dxdw8ddy3oga5r3rj0yo587ct6cxceq/dxdw8ddy.png), the metronome goes "click CLACK click click CLACK click click" instead of "CLACK CLACK click click CLACK click click".

I think the original behaviour ("CLACK CLACK click click") was a bug, but feel free to disregard the extra commit if it was intended behaviour.

### CODE REVIEW

**Comment by tobiatesan** [comment]
Whoops. I didn't notice I had broken some tests, though. Let me see why.

**Comment by mgavioli** [comment]
Not sure to understand your comment about incomplete measures: a link to specific code lines would be helpful.

Are you sure you do not refer to the clicks of the count-in feature, rather than of the 'regular' metronome during the piece? the count-in should always at least fill any partial measure before the beginning of the play, whether this happens because of an anacrusis at the very beginning of the piece or because play is started mid-measure.

**Comment by tobiatesan** [comment]
@mgavioli I'm referring to line 1553, and specifically:

int addClick = (delta + clickTicks - 1) / clickTicks;
numOfClicks += addClick;

numClicks is already initialized to the time signature's numerator, I don't understand how _adding_ to it is beneficial.
I suppose for an incomplete measure you would _subtract_ from it?

**Comment by mgavioli** [comment]
For the count-in, the number of clicks for the missing part is needed **in addition** to a measure of clicks.

**Comment by mgavioli** [comment]
The last modification I can find of this part of the code seems to be [this commit](https://github.com/tobiatesan/MuseScore/commit/3f7589dbc7087318610659ddca58115d04beb003) by @lasconic merging the algorithm for metronome and for count-in. I assume he may have more details on this.

**Comment by lasconic** [comment]
I implemented this differently, and it passes the tests. https://github.com/musescore/MuseScore/pull/2689

**Pull request closed without merging**
