### PR TITLE
Final font

### PR DESCRIPTION
**Pull request by FRL200**
Resolves: *https://github.com/musescore/MuseScore/issues/10258*

*Issue was regarding the thickness and hook having increments of 0.5 and not of 0.1, changes were made to the increments, the minimum , maximum value and the decimal*

- [x ] I signed [CLA](https://musescore.org/en/cla)
- [x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Somthing went very wrong with this PR, only the last file resp. the fierst commit should be part of it as far as I can tell?

**Comment by FRL200** [comment]
Hello,
Thank you so much for reaching out, I’ll have to double check as the changes I made were very basic, but I feel like other files were changed in the process somehow. I am still learning how to do the whole commit, push and do the pull request correctly with GitHub, I will reach out if it does not seem to work.

Thank you,
Fernando Rauseo

On Jan 31, 2022, at 2:32 AM, Joachim Schmitz ***@***.******@***.***>> wrote:

[External Email]


Somthing went very wrong with this PR, only the last file resp. the fierst commit should be part of it as far as I can tell?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_musescore_MuseScore_pull_10413-23issuecomment-2D1025453406&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=w70Hz4Km4lEBwbBRIPHyZPLrOONFCX2mS3j1aBRKN5g&m=RM1dU2gZwTka3dy3Gpio8nw_ludNklXPojhr2IZow1GeAI7LtWkrrVx_im4B3PEB&s=tyTJEaMkbPJ51J_XpcMMKc7KnTCWkE8V1h6v8sm4hko&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ARREP4TMEYTRQJSVMIGDGJDUYY3I3ANCNFSM5NFF4K6A&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=w70Hz4Km4lEBwbBRIPHyZPLrOONFCX2mS3j1aBRKN5g&m=RM1dU2gZwTka3dy3Gpio8nw_ludNklXPojhr2IZow1GeAI7LtWkrrVx_im4B3PEB&s=156Ebrfkf_OaEqt98AF1r7Rxf20eLYS2R4F-R-Vk_Qo&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=w70Hz4Km4lEBwbBRIPHyZPLrOONFCX2mS3j1aBRKN5g&m=RM1dU2gZwTka3dy3Gpio8nw_ludNklXPojhr2IZow1GeAI7LtWkrrVx_im4B3PEB&s=aUgZZpOJl2Yz7SIO_NwXwlFXuG71bDAIMXvQGlNfB_Q&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=w70Hz4Km4lEBwbBRIPHyZPLrOONFCX2mS3j1aBRKN5g&m=RM1dU2gZwTka3dy3Gpio8nw_ludNklXPojhr2IZow1GeAI7LtWkrrVx_im4B3PEB&s=79gXNZIZyEFR0WRwg9K7QdWxWpyCTncZxquIqW_6XD4&e=>.

**Comment by Jojo-Schmitz** [comment]
As per https://github.com/musescore/MuseScore/pull/10425#issuecomment-1029897044 this should probably get closed

**Comment by Jojo-Schmitz** [comment]
(oops, wrong)

**Comment by Jojo-Schmitz** [comment]
Yes, so this here can get closed

**Pull request closed without merging**
