### PR TITLE
Automatic charset detection for MIDI import (updated 2)

### PR DESCRIPTION
**Pull request by trig-ger**
This is a functionality for the initial guess of what is the encoding of a MIDI file.
It is also a fix for #3370 "Import or detect encoding of text from MIDI": http://musescore.org/en/node/3370
The results of automatic detection (without manual work) are 100% positive for 4 test MIDI files. 
Longer the text (lyrics, staff names) - more accurate is the charset detection.

Japanese lyrics (100% match):
https://docs.google.com/file/d/0B5alKuFoSol2ZTB5MnhFUXp6ZVE/edit?usp=sharing

The result on Windows is the same:
https://docs.google.com/file/d/0B5alKuFoSol2RklyUnBTNmdDXzQ/edit?usp=sharing

UPDATE:
Russian staff name and lyrics - 100% match:
https://docs.google.com/file/d/0B5alKuFoSol2Y2VLSDljWHFaUFU/edit?usp=sharing

Korean lyrics - 100% correct:
https://docs.google.com/file/d/0B5alKuFoSol2ZjBBTFJ6MkZtVGc/edit?usp=sharing

Korean MIDI file: 
https://docs.google.com/file/d/0B5alKuFoSol2aldEUko0VzNoTjA/edit?usp=sharing

One more example - windows-1252:
https://docs.google.com/file/d/0B5alKuFoSol2OXQ3NF9UeUNLYkU/edit?usp=sharing

***
The code of the detector was downloaded from here:
https://code.google.com/p/uchardet/

and here:
https://github.com/batterseapower/libcharsetdetect

It is based on the 'universalchardet', the encoding detector library of Mozilla.

The original Mozilla core code is located here:
http://mxr.mozilla.org/seamonkey/source/extensions/universalchardet/

The licence is Mozilla Public License 1.1.
The code was put into the thirdparty/universalchardet dir.

### CODE REVIEW

**Comment by lasconic** [comment]
We got 0 feature requests about this. Not worth the additional dependency.

**Comment by IsaacWeiss** [comment]
0 feature requests? What about https://musescore.org/en/node/3370 ?

**Comment by Jojo-Schmitz** [comment]
And what about https://musescore.org/en/node/252671?

**Comment by trig-ger** [comment]
When there will be such built-in function in Qt library...

**Pull request closed without merging**
