### PR TITLE
fix #147196: Minimum width of Inspector has increased significantly

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
esp. note and ambitus inspector, due to these long names for note head groups

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
"Slashed bottom left to top right" -> "Slashed (Forward)" or "Shlashed 1" or maybe "Slashed"?
"Slashed top left to bottom right" -> "Slashed (Backwards)" or "Slashed 2" or "Backslashed"?

**Comment by IsaacWeiss** [comment]
"Forward slash" and "back slash" are commonly used for the keyboard characters / and \.

**Comment by Jojo-Schmitz** [comment]
These note heads are not plain slashes though, but a normal notehead with a slash (or backslash) through it, hence the 'ed" ending

**Comment by IsaacWeiss** [comment]
Ah, I see. I like "slashed (forwards)" and "slashed (backwards)," then.

**Pull request merged**
