### PR TITLE
Add support for soundfonts as symbolic links

### PR DESCRIPTION
**Pull request by flxkrmr**
Resolves: #17103

Should fix the issue, but I could only test it on Windows. Any input is welcome :) 

I did not yet write a unit test for this, as I think it would not be much use in this code, but I can try to write one if you want to.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Exactly my point in the issue. As said there in MU3 the only place where symlinks were not permitted was for extension (MDL and the HQ soundfont, but not soundfonts in general)

**Comment by shoogle** [comment]
@cbjeukendrup, yes, I don't think we need to worry about that situation. Like you said, it's no different to renaming the original file.

I think the issues specific to symlinks are:

1. **Unresolvable link:** Target file does not exist, or we lack permissions for it.
2. **Infinite loop:** Target file is another symlink pointing (possible via more symlinks) back to the original symlink.
3. **Infinite search:** A subfolder of the target directory is a link (possible via more symlinks) back to a parent directory of the original symlink.

But I don't think it's our job to worry about these cases. If the user has created a symlink then we should assume they know what they are doing.

**Comment by cbjeukendrup** [comment]
... plus that I think that Qt's scan functions have some protection against these problems. 

So indeed, I think it's safe to allow symlinks everywhere in principle, and only disable it in specific places if it ever turns out to cause problems.

**Comment by flxkrmr** [comment]
Thanks for the input :) I changed it to work globally with symbolic links and tested it with Soundfonts, Templates and Scores so far, which seem to work fine.

**Review by igorkorsukov — APPROVED** [review]

**Pull request merged**
