### PR TITLE
fix #331007: [MusicXML import] support tie element

### PR DESCRIPTION
**Pull request by lvinken**
Resolves: https://musescore.org/en/node/331007

Create a tie on MusicXML import when either a tie or a tied element is present.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@lvinken:  My backport to 3.x fails an mtest, "testUnterminatedTies" (see [here](https://github.com/musescore/MuseScore/runs/6245663871?check_suite_focus=true#step:5:808)), seems related to this change. any idea whow to deal with it?

**Comment by Jojo-Schmitz** [comment]
That test doesn't seem to exist in master (see https://github.com/musescore/MuseScore/blob/a623af3beb5264655ab572a8ad9a812150dd5e38/src/importexport/musicxml/tests/tst_mxml_io.cpp#L255-L256)

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
I see, that test isn't in 3.x either, but had been last added with #8556 into the 3.6.2_backend_musicxml branch

**Comment by lvinken** [comment]
It is quite unfortunate that MusicXML import in the backend and the application itself are not in sync ...

**Comment by Jojo-Schmitz** [comment]
Yes, it is. And unfortunate that the author of those is no longer around.

**Pull request merged**
