### PR TITLE
Ensure the user is logged in before trying to open cloud score

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #18090

### CODE REVIEW

**Comment by jessjwilliamson** [comment]
Perfect! Much better - Thank you!!

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested on Win10, LinuxUbuntu 22.04 - **FIXED**

**Comment by Jojo-Schmitz** [comment]
Shouldn't that make it into 4.1 too?
If so better sooner than later, as it contains a new string to translate

**Comment by bkunda** [comment]
> Shouldn't that make it into 4.1 too? If so better sooner than later, as it contains a new string to translate

It will.

**Comment by Jojo-Schmitz** [comment]
yeah, my legendary patience, you know...

**Pull request merged**
