### PR TITLE
continuous panel fix and cosmetic changes

### PR DESCRIPTION
**Pull request by Gai-Luron**
- Name are now horizontal
- Name are now scaled regarding scaling value
- Measure Number is scaled too
- Control panel enlarge when shortname is "long"
- Less Opacity of control panel

### CODE REVIEW

**Comment by Gai-Luron** [comment]
Travis issue.

**Comment by lasconic** [comment]
Not really, it's a compilation error 
https://travis-ci.org/musescore/MuseScore/builds/55146595#L2301

```
/home/travis/build/musescore/MuseScore/mscore/continuouspanel.cpp: In constructor ‘Ms::ContinuousPanel::ContinuousPanel(Ms::ScoreView*)’:
/home/travis/build/musescore/MuseScore/mscore/continuouspanel.cpp:48:7: error: ‘_lineWidthName’ was not declared in this scope
       _lineWidthName         = 0.0;
       ^
/home/travis/build/musescore/MuseScore/mscore/continuouspanel.cpp: In member function ‘void Ms::ContinuousPanel::findElementWidths(const QList<Ms::Element*>&)’:
/home/travis/build/musescore/MuseScore/mscore/continuouspanel.cpp:178:7: error: ‘_lineWidthName’ was not declared in this scope
       _lineWidthName = 0;
       ^
```

**Comment by Gai-Luron** [comment]
Yes you are right for this one. The first exit at 78% with internal error.
I do the modification and resend PR.

Merci

**Comment by lasconic** [comment]
Thanks for the fix. Unfortunately the PR will have to wait next version. There is already an ongoing effort to document, make videos, make screenshots for MuseScore 2.0 and it's hard to change the interface, even if it's for the better. Let's release 2.0 and I will come back to this PR ASAP.

**Comment by Gai-Luron** [comment]
No problem i understand. Interface it's not the priority for now.

**Comment by ZackTheCardshark** [comment]
I'm wondering—lasconic said "Unfortunately the PR will have to wait next version. There is already an ongoing effort to document, make videos, make screenshots for MuseScore 2.0 and it's hard to change the interface, even if it's for the better. Let's release 2.0 and I will come back to this PR ASAP." But there are no plans to remake the videos and screenshots for 2.0.1 or 2.1, are there? So timing doesn't really matter to that aspect of it.

**Comment by Jojo-Schmitz** [comment]
There are no plans to remake the videos and screenshots for 2.0.1, but 2.1 is an entirely different story.

**Comment by lasconic** [comment]
I merged this PR a bit differently in 27b0a39

**Pull request closed without merging**
