### PR TITLE
fix #116906: support for control structure

### PR DESCRIPTION
**Pull request by hpfmn**
this is starting support for the sfz control structure. set_cc is not really implement yet. Have to find out what would be the best way?

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
seems a rebase is needed?

**Comment by hpfmn** [comment]
yep - would have been clever to have these changes on top of the recent parsing changes...

**Comment by lasconic** [comment]
This is not wip anymore right?

**Comment by hpfmn** [comment]
It is not that good tested (still has to be done) and I thought I could implement set_cc (for this I need to do more investigation) - but I can also add set_cc in a later PR

**Comment by hpfmn** [comment]
For me everything should be good to go now!

**Pull request merged**
