### PR TITLE
[MU4] Ported #6425: migrate invisible staff lines and line color to staffType

### PR DESCRIPTION
**Pull request by igorkorsukov**
Ported #6425: migrate invisible staff lines and line color to staffType

### CODE REVIEW

**Comment by Howard-C** [comment]
No changes to the inspector?

**Comment by igorkorsukov** [comment]
> No changes to the inspector?

We'll do it as it is for now, and later we'll make edits for the inspector. Or you can do it :)

**Comment by Howard-C** [comment]
> > No changes to the inspector?
> 
> We'll do it as it is for now, and later we'll make edits for the inspector. Or you can do it :)

Thanks! I can do it.

**Comment by Howard-C** [comment]
#7397 ;-)

**Pull request merged**
