### PR TITLE
Fix #100181 cursor addNote segment reference

### PR DESCRIPTION
**Pull request by jeetee**

### CODE REVIEW

**Comment by lasconic** [comment]
As discussed on IRC, some tests would be nice
Not really needed for 2.0.3 but could be nice to have if time permits.

**Comment by jeetee** [comment]
Added my first attempt at a test case, had to rebase/merge for CMakeLists to include it. Here's to hoping I didn't screw up :)

**Comment by jeetee** [comment]
Went through all available plugins. There is one unfinished one that is affected by this change. It uses code from the random.qml plugin. Given that I've included an update for random.qml in this PR, getting the author to patch up his/her plugin should be fairly easy.

[MuseScore plugin overview - Sheet1.pdf](https://github.com/musescore/MuseScore/files/193257/MuseScore.plugin.overview.-.Sheet1.pdf)

**Comment by lasconic** [comment]
Great work !

**Comment by lasconic** [comment]
Could you squash the commits? http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by jeetee** [comment]
Notified DonH of the one plugin with links to the issue and new random.qml sources as examples.

**Pull request merged**
