### PR TITLE
Fix #283063: "MuseScore File" string (under File -> Save As...) does not indicate which version you are about to save as

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by riaanvn** [comment]
Thank you Jojo 🙏

**Comment by riaanvn** [comment]
Discussed at length at original issue. 
https://musescore.org/en/node/283063
and Jojo sees my point. If I can convince Jojo, hopefully that is good enough for you.

**Comment by Jojo-Schmitz** [comment]
For the record: You haven't really convinced me... I still doubt the usefulness of this change

**Comment by riaanvn** [comment]
Ok, I hear you Jojo.

What do we lose by making the Save As dialog text/version more transparent. Is Save As without a version number in the string objectively worse or better? Without the version in the string, users can get burned by the assumption that this file is version agnostic and transparent (e.g. like saving to PDF, Midi, or MusicXML, which are standardised), which is made worse by the file extension also not making a distinction. I consider this a consolation prize for the extension not being able to change to reflect the V2 vs V3 differences.

**Comment by Jojo-Schmitz** [comment]
We'd lose a couple translations, for 3.0.5 at least. We don't win enough to make it worthwile IMHO. users most like won't noticed that subtle change anyhow, but still compiain that they've overwritten their 2.x files. They do complain already, after having overridden a bug fat explicit warning!

**Pull request merged**
