### PR TITLE
update vtests for gonville

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by Gootector** [comment]
@Jojo-Schmitz: It's ok.
@ZackTheCardshark: Nothing is shifted. 4 i 5 are unchanged.

**Comment by Jojo-Schmitz** [comment]
I've noticed that too, look at test 3 and use swipe or onion skin  view

**Comment by Gootector** [comment]
Yeah... And articulations, and noteheads, and most of the glyphs are dancing... :dancers: :D :D :D

**Comment by Jojo-Schmitz** [comment]
The recent switch from letting Qt render to using freefont instead may explain differences seen here, I'm pretty sure the previous versions of these had been done prior to that switch

**Comment by Gootector** [comment]
In my opinion in the current version of MuseScore the displaying of fonts is better than previous. The best I've seen in all versions of MuseScore.

**Comment by Jojo-Schmitz** [comment]
this and the better cross-platform consistency was the reason for the switch

**Comment by Gootector** [comment]
Will this commit be merged to repo?

**Comment by Jojo-Schmitz** [comment]
would PR #2212 potentially cause some visible changes?

**Comment by Gootector** [comment]
No, any visible changes of vtests. It's a code optimization only.

**Comment by lasconic** [comment]
done.

**Pull request closed without merging**
