### PR TITLE
Fix: unnecessary colon

### PR DESCRIPTION
**Pull request by Gootector**
Fix: unnecessary colon
https://github.com/musescore/MuseScore/pull/20259

Greetings,
Gootector

Resolves: #NNNNN 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Gootector** [comment]
@cbjeukendrup PR for 4.2.0.

**Review by cbjeukendrup — APPROVED** [review]
Thanks :)

**Comment by cbjeukendrup** [comment]
I've also pushed it to Transifex but it seems it got auto-translated by the Translation Memory.

**Comment by Gootector** [comment]
Yes, it is auto-translated by the TM. I just reviewed it.

**Pull request merged**
