### PR TITLE
[4.4.0] Fix Wayland popup positioning

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: https://github.com/musescore/MuseScore/issues/15285

See #24121

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
@kbloom @MarcSabatella This PR should have it all: should start correctly on Wayland, but default to xcb, and contains the positioning fix. Would be great if you could give it a test!

**Comment by kbloom** [comment]
Good:

* When I don't specify an environment variable, Musescore runs in X11.
* When running in X11, menus and tooltips work normally (as intended)
* When I specify `QT_QPA_PLATFORM=wayland`, Musescore runs in wayland
* When running in Wayland, menus, context menus, and tooltips are positioned near the cursor.
* When running in Wayland, if one menu is open, moving to the next menu heading does not crash the program.

Bad:

* When running in Wayland, moving the mouse from one menu heading to the next changes the content of the menu, but does not change its position.
* When a tooltip is open, hovering over something else (another item in the palate) updates the content of the tooltip, but does not change its position.

[Kai Uwe Broulik's blog](https://blog.broulik.de/2024/08/a-fresh-perspective-on-things/) suggested that both of these problems may need to wait until Qt 6.8, which isn't due for release until the end of September. Alternatively, destroying and recreating the popup menu may help with this.

**Comment by MarcSabatella** [comment]
Looks good from my perspective, thanks all for the work on this!  I can the positioning glitche that @kbloom mentions (or popup content but not positioning updating when hovering over items in quick succession), and if there is a simple fix for that, I'd take it.  But it's already better for me than xcb - scaling works really well.  Except, disappointingly, the braille panel, which remains tiny. 

FWIW, the sound flag icon does seem correctly drawn now, which was the one thing that was most "off" in 4.3.2 using my workarounds for 4.3.2.

I do get a warning to console each time a popup displays:

> ignoring unexpected wl_surface.enter received for output with id: 7 screen name: "Screen5" screen model: "unknown" This is most likely a bug in the compositor.

In addition, for sound flags specifically (also harp diagrams), I get:

> Wayland does not support QWindow::requestActivate()

**Comment by cbjeukendrup** [comment]
Given these observations and [Dmitry's test results](https://github.com/musescore/MuseScore/pull/24121#issuecomment-2302384681), I think this is ready to be merged. Thanks to everyone involved!

**Pull request merged**
