### PR TITLE
Fix #12811: Unable to change Volta text font in Edit Style

### LINKED ISSUE #12811: Unable to change volta text font in Style editor
**Describe the bug**
Not able to change font for voltas. In the Style editor, it lets me change it, but reverts back to Edwin when closing, regardless of clicking "Ok" or "Cancel". Also won't show font selection in the left-hand object editor when selecting the volta, only the text field which you can edit, but no font selector like in MuseScore 3.

**To Reproduce**

1. Create a volta
2. Go to 'Style editor'
3. Click on 'Text styles'
4. Scroll down to 'Volta'
5. Change font
6. Click "Ok"
7. Notice the font hasn't changed
8. Go back to the style editor, and see it has reverted back to Edwin (default)
9. Click on volta
10. In the left-hand object editor click "Text"
11. Notice you can change the text, but not the font (like you could earlier)

**Expected behavior**
When performing the steps above, I would expect that the font for the voltas actually changed to the one I selected, and not revert back to default without changing anything. Also I would expect there to be a menu to change the font individually independent from the style editor, like there was in previous version.

**Screenshots**
Skjermbilde 2022-08-12 kl  01 26 30
Bilde_2022-08-12_012722294

**Platform information**
 - macOS 12.1 on MB Pro 14" M1 Pro

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #12811

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Oh... This is a duplicate of https://github.com/musescore/MuseScore/pull/13292...

That shows how dangerous duplicate issues are: they can cause duplicate PRs!

**Comment by cbjeukendrup** [comment]
@RomanPudashkin I'll leave it up to you to choose between this PR and my https://github.com/musescore/MuseScore/pull/13292. This PR's solution involves less changed files; my solution is a bit more in line with my personal vision for text styles (but that's just my vision).

**Comment by HemantAntony** [comment]
Aw that sucks. I did spend a couple hours on this PR 😁. Anyway, please feel free to close this PR if the other one is better 🙂 (@RomanPudashkin)

**Comment by RomanPudashkin** [comment]
@HemantAntony thanks for your help! We will use this solution  https://github.com/musescore/MuseScore/pull/13292 because it's more flexible

**Pull request closed without merging**
