### PR TITLE
get rid of doxygen

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
also check for WebEngine and WebEngineWidgets only if not MINGW

### CODE REVIEW

**Comment by lasconic** [comment]
Could you amend your message to point to https://musescore.org/en/node/106291 Thanks

**Comment by Jojo-Schmitz** [comment]
I just did, even before reading your request ;-)

**Comment by Jojo-Schmitz** [comment]
want it as 2 commits, so one can cherry picked for 2.0.4?

**Comment by lasconic** [comment]
it's fine, I'm ok to have some doxygen code in 2.0.4 so I will not cherry pick this one. Thanks.

**Pull request merged**
