### PR TITLE
fix #87871: Add Serbian Cyrillic (sr_RS) language

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Note that I've changed the existing language "Српски" to "Srpski", to reflect that is is the Latin version, and added the new language as "Српски" to reflect that it is the cyrillic version.

Remaining task:
On the update translation server
* Modify languages.json
* rm share/locale/details.json

### CODE REVIEW

**Comment by lasconic** [comment]
Update translation server done.

**Comment by Jojo-Schmitz** [comment]
Hmm, in MuseScore 2.0.2 the resource Manager Dialog is totally empty now?!

**Comment by Jojo-Schmitz** [comment]
Ah, now everything is in place. Not for the master branch though.

**Comment by lasconic** [comment]
We only update the 2.0.3 branch indeed.

**Comment by Jojo-Schmitz** [comment]
Understood, however, the corresponding changes are currently in master only, not in the 2.0.3 branch? Or is that something for later, shortly before relase?

**Comment by lasconic** [comment]
Now they are. I forgot to push my local branch

**Comment by Jojo-Schmitz** [comment]
Ah, I see, thanks

**Pull request merged**
