### PR TITLE
vst_crashes

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/13867
Resolves: https://github.com/musescore/MuseScore/issues/14205

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
@Tantacrul @vpereverzev I think it would be nice to nominate these fixes too for 4.0.1

**Comment by Tantacrul** [comment]
I second that. I'm adding now. If anyone has a big objection, let me know. Thanks @cbjeukendrup !

**Review by vpereverzev — APPROVED** [review]

**Comment by vpereverzev** [comment]
@DmitryArefiev check this one please

**Comment by DmitryArefiev** [comment]
Tested #14205 #13867 on Win10, Mac12 - **FIXED**

**Pull request merged**
