### PR TITLE
Implement scale editor based on discussion from https://musescore.org/en/node/99841

### PR DESCRIPTION
**Pull request by sraduvictor**
The diff is not finished yet, but I'm making a pull request to get early comments.

### CODE REVIEW

**Comment by mgavioli** [comment]
Thanks for this whole lot of work: need sometime to study it! (time which I probably will not have at least for the two coming days).

The first-sight comment is that the `ui_*.h` files should not be there at all: they are generated by the Qt tools and should be in the build directory not in the sources.

**Comment by sraduvictor** [comment]
I looked at the files in the mscore project and saw all the ui_*.h files, but now I see they are not in mscore folder.

**Comment by sraduvictor** [comment]
removed ui_*.h files

**Comment by sraduvictor** [comment]
I finished the implementation and tested changing the number of notes per scale in both dialogs. I still need to test changing storage mode and reference.

**Comment by sraduvictor** [comment]
1) So no matter what options we choose in the combo boxes, we should store the notes as absolute cents for notes?

2) I'll change the name to aTuning. Then should aTuning in the scalesDialog match the delta from the A absolute cents value to the A standard cents value?

3/4) originalNotes stores the actual strings from either the scalaFile or the editor (so for absolute cents it can be a number or a ratio). computedTunings stores the delta between the note for that temperament and the standard temperament. 
  If I want to have only one vector I'd have to stop storing ratio, and store the actual pitch of the note for that temperament instead of the delta. Should I do this?

**Comment by sraduvictor** [comment]
Another question : If I were to store only absolute cents, I still need functions to regenerate the tuning from the storingMode I showed to the absolute cents storing mode, which are going to be very similar to the one generating storing mode for absolute cents.
So should I have a separate class ScaleUtils or ScaleEditorUtils that copies this function of generating the notes from one storing mode to another? And should I also use this function when reading Scala files, or should I have another function like this in the Scale class?

**Comment by sraduvictor** [comment]
What I thought after reading your description in https://musescore.org/en/node/99841 was that changing the options in the editor will not actually change the pitches, it will just show the values under a different requirement, and that A tuning will be changed to make this happen.
Also I was thinking of keeping the ratios, so I thought I should store the strings that the user wrote in the editor.
Please comment if this is not the way you envisioned it.

**Comment by sraduvictor** [comment]
I'm testing the editors and I see that when I change from absolute cents to absolute frequency and back for notes, we sometimes loose 1 cent for some notes. But for the fifths editor because the values get added to obtain the notes this loss is added and it gets to a 14 cent difference for a full 35 scale. This might be aggravated because we round the cents value to the nearest int. Should we switch to using double instead?

**Comment by mgavioli** [comment]
**Referring to yesterday numbered points** (I cannot check this more than once a day and not even every day, so I have to cumulate comments!):

**3/4)**: What we ultimately need are the delta cent from eq.temp., because these are the values actually needed when the data is used (i.e. when applying a tuning to a score). These are the data needed as fast as possible, possibly always readily available in `computedNotes[]`.

Ratios as decimal numbers, absolute cents or any other numeric format are easily computed from delta cent if and when needed for displaying (when a few milliseconds more or less do not matter so much). So, I see little need to store those formats, and set a machinery up to remember which format is currently used and to update when needed.

Does this make sense to you?

Additionally, storing numerical values as strings and converting them back and forth to numbers looks a little 'Byzantine' to me (pun not intended (or perhaps yes, maybe &lt;g&gt;!) ). Different _could_ be the case for ratios, originally expressed as ratios in the Scala file -- like "5/4" --; this can only expressed as a string and is usually slightly more informative than a number and might be worth storing. However, it should be removed once the value changes, as the original ratio is no longer valid.

So, you might evaluate if it is worth the trouble to set the array up, discriminate among the values in input and manage the updates in order to store this additional info, as long as it remains valid ad removing it when obsolete.

Does this too make sense to you?

**1/2):** The actual A pitch (440Hz, 415Hz, or whatever) is irrelevant: should it change, all actual frequencies will shift up/down with it (but the synth is taking care of this), but ratios / relations between notes would not change.

What is relevant is the delta cent for A. When the scale is displayed with A as reference, the delta cent for A should always by 0 (and consequently the absolute cent always `Scale::STANDARD_NOTES[TPC_A]`), with all other values shifted up/down correspondingly: this is what using A as reference means, isn't it? And, correspondingly, when C is the reference, the delta cent for C should always be 0 (again with all the other values shifted up/down correspondingly).

The synth ultimately needs deltas in A reference. If -- as the current code does -- we set for storing `computedNotes[]` as A-ref. delta cent, the only case we need to take care of is the C-ref display (and only for display in the editor): the conversion to the current reference is rather trivial:
`    <delta in current ref.> = scale.computedNotes[noteTpc] - deltaRef;`
where `deltaRef` is:
`    deltaRef = (ref == Scale::C_REFERENCE ? scale.computedNotes[TPC_C] : 0);`
and needs to be computed only when the user changes the reference in the editor.

Does this look correct to you?

Other comments:

**Functions to convert between formats**: conversion between format is really needed only in the editor, only for filling/reading edit box values and from/to the format used for actual storing (according to the above comments, let's assume this is going to be delta cent in A-ref.). In most cases, it is very simple, for instance, converting from delta cent to absolute cent in note display is just:
`  absCent = scale.computedNotes[noteTpc] + Scale::STANDARD_NOTES[noteTpc] - deltaRef;`
and vice versa, from absolute cent to delta cent:
`  scale.computedNotes[noteTpc] = absCent - Scale::STANDARD_NOTES[noteTpc] + deltaRef;`
where `deltaRef` is the same as above and needs only to be computed when the user changes the reference, not for each note; either hardly worth a function.

If you think it cleaner and clearer, you might well create functions for each combination, but I am not sure it is really worth the effort. What do you think?

"_the previous diff was changing the tuning so that A was the standard pitch. Should I change the original notes to reflect this change?_": why? If they are _original_, they should not be modified, should they? Still, I am not entirely sure we really need original notes at all.

"_should I show the original notes in the editor, but have A tuning show by how much it shifted the pitch_:" I'm afraid that either I do not understand your point or you are making things much more complex than necessary; the editor has a number of display formats reputed useful (I proposed a few, but they can be discussed and increased/reduced/changed, also according to what actual practice might show): once the user selects a certain display format, the editor shows that format, that's all!

**int vs decimal cent**: rounding errors were to be expected, it was simplistic of me to forget that, once the editor is brought into the picture and back-and-forth calculations happen, there will be rounding errors. I checked and `NPlayEvent::_tuning` is a `float`, so it is wiser to store `computedNotes[]` as `float` rather than `int`; this should give more than enough precision, as everything below the half of a cent is purely illusory. It might make sense to evaluate how many decimal positions to show in the editor, to strike a balance between number readability and rounding errors. What about having 3 decimal positions (as in 1.123)? Perhaps 4 (1.1234)?

**Comment by mgavioli** [comment]
More comments once running the actual PR (I finally had time to do it!).

**1/2) A pitch**: seeing the screen, memory flashed back to me! You are replicating the plug-in editor; there the actual value of the pitch of A was needed from some reason I no longer remember (perhaps, MuseScore 1.x could not apply pitch shift yet). Now that any pitch shift is managed directly by MuseScore, we do not need it any more.

**5) Fifths**: what I had in mind was different, I apologize if the description in the forum post was not clear. The idea is to have the notes in TPC order, from Fbb, Cbb, Gbb, ... up to A##, E##, B## and to display _between_ them the size of the _fifth_ in between. So, for equal temperament, all fifths should show 0 (as delta cent) or 700 (absolute cent) or 1.5 (frequency ratio).

The calculation is again rather trivial; the fifth between the _n_-th and the _n+1_-th TPC note is:

    deltaCents = scale.computedNotes[n+1] - scale.computedNotes[n];

and accordingly for the other display formats (this layout is independent from any A- or C-reference).

**6): TPC range shown**: you are replicating the plug-in editor also in this. Since them, I realized that there is a possibly much more efficient way. The editor dialogue box only needs to show edit boxes for the range `Scale::minTpc - Scale::maxTpc`; data for items below or above that range is duplicated and redundant. This makes the selector [7 notes , 12 notes, 17 notes, 21 notes, 35 notes] obsolete. This applies to both the Fifth-order and the Note-order layouts.

Possibly an easy way is to add all the 35 boxes in the dialogue box designer and simply hide the unneeded one when the dialogue box is displayed.

**7) Dialogue box work-flow**: I expect the work-flow of dialogue boxes might change with more tests. Perhaps, not now: let the existing code to settle, as there is already a good deal to test and tune. But sooner or later, particularly if and when a scale manager will be implemented, selecting a (loaded) scale, loading a(nother) scale and editing a scale might become separate operations, interesting different kinds of users.

**Comment by sraduvictor** [comment]
All the dialogs I made, were from getting your Scales plugin for 1.3 and changing them for now only for editing the current scale.
1/2) So are you suggesting that all scales will have the A pitch identical to the A note? Is there no scale, where this is not the case?
3/4) I still want to store the ratios which represent absolute values, so I'm thinking of storing absolute cents and ratios in the string. I agree that if we decide to not store ratios, going with delta cents would be the easiest way.
Another difference between originalNotes and computedTunings is that originalNotes could be only 7-12 values, while computedTunings is always 35. An interesting thing with the combobox showing the number of notes you want to use is that you can use a scale with 7 notes, select 35 from the combobox and see what values did we actually choose for you for all 35 notes, and if you are not ok with it you can edit them, or you can come back to 7 if they look good.
5) Somehow I'm not getting emails from the forum, so I missed your comment there that I should use this order, I'll make the change and update the code.
6) So if I import a 7 notes scale, should it be impossible for me to switch to 35 notes to edit the notes if somehow our logic does not generate the expected output?
7) Should the scale manager be in a separate dialog, or the same one as this?

**Comment by sraduvictor** [comment]
For the fifths editor, if I want to store ratios, then I can't convert the values back into absolute cents of the note, and I need to store them as absolute cents of the difference between notes on the same temperament (Fbb -> Cbb). So should I keep storeFifths as a parameter in Scale?

**Comment by sraduvictor** [comment]
I changed the notes to use float instead of int.
I changed the order of the notes shown in the editor for fifths to show the correct order
I moved storingMode out of Scale and now scales should be stored only using absolute cents so they can support ratios.
I did not move storeFifths yet, as that would mean not supporting ratios for the fifths editor.
I did not delete aTuning yet, as that would mean all scales have a standard A note.
I added some tests in tst_scale.

**Comment by mgavioli** [comment]
First, a general remark. I would be more confident in making suggestion if I am sure that you do not make changes to the code just because I tell, but because my arguments sound convincing, you agree with them and I didn't overlook some point.

**1/2)** Scales in themselves do not have any pitch: they can be applied to whatever pitch the performer chooses to use (deriving all other notes supported by that scale from some given reference, according to the ratios defined by the scale).

As it is common practice to tune on a given A, it seems to me simpler and, above all, quicker when speed matters (i.e. when creating play note events), to store the scale data as deltas so that the delta for A be 0 (and all other deltas shifted correspondingly). In that way the A will always be 'in tune' and all other notes tuned according to the relationships defined by the scale.

Whatever scale I apply, regardless I set the MuseScore player for A at 440Hz or at 415Hz or at 392Hz, I'll have A in tune and the other notes according to what that scale requires. There is no need for the scale to be tied to a specific A pitch or even for it to know which A pitch is in effect.

Do you agree? Am I missing something?

**3/4)** To avoid ambiguity, can we agree to call expressions like "5/4" _fractions_ rather than generically _ratios_, to distinguish them from single numbers like `1.25` which also are ratios (and call only the latter _ratios_)?

I agree that fractions are informative and it would be nice to keep them. However, in this case, `originalNotes[]` should not store other things than fractions, or we would loose track of what is what. In addition, if a ratio originally expressed as a fraction is modified, the fraction should be deleted, as it no longer represents the new value (unless you find a way to re-create a new fraction out of the new value). So, I wonder it is really worth the trouble. But, if you want to support this kind of fraction management, I would not stop you, for sure!

"_... that you can use a scale with 7 notes, select 35 from the combobox ..._": hmmm, this seems to me both a logic inconsistency and a misuse of the available data (one I myself fell into at the time of the plug-in):
- if the user chooses a scale with 7 notes, he has 7 notes, period. The fact the **internally** we supply a whole set of 35 notes for the sake of the playback system should not concern him. If he applies this 7-note scale to a Bruckner's symphony, he should expect things to go awry; rather he should probably choose a 12-note scale. If you do not need G# to be different from Ab, you may go for a 12-note scale, but if you need (or would like to experiment with) them being (potentially) different, you need a more articulated scale. Data not present in the scale, from the user perspective, should not exist (in fact, they 'really' do not exist as independent data: they are the duplicate of other data for the sake of the playback system).
- we did not "_actually chose for you_" anything! We did not chose the fact that G# is an enharmony of F# as well as E##; this is implied by the 'circle' of fifths.

**6)**: as far as I see it, yes, it should not be possible to 'see' more notes than there are in the scale. Later on, it might be possible (or even desirable) to add to the editor a function to change the scale 'TPC span' (conveniently worded in order to make it comprehensible to the laymen), but making it clear that this creates a new scale, rather than 'unblocking' some 'hidden feature' of the existing scale.

Or maybe a better way to implement such a function could be a "Create new scale" function (which sooner or later we would need anyway) with selectable range, optionally initialized from some existing scale. Usually, however, scales are self-consistent systems and adding arbitrary new notes often makes little sense and requires adjusting (most) existing notes, for sure this happens in many temperaments.

**7) Scale manager**: No clear idea yet. Really, it seems to me wiser to wait until the current features (on which a scale manager would rely anyway) are settled, debugged and tested, before implementing anything of it.

**8) fifths vs. ratios**: "_For the fifths editor, if I want to store ratios, then I can't convert the values back into absolute cents of the note_": why can't you? what forbid it? can you elaborate where the problem is?

**Comment by sraduvictor** [comment]
I guess I'm just trying to get to a resolution quicker and considering I don't have strong opinion on how this should look like (just that it supports my use case), I'm agreeing with any other options that are suggested.
Having said that my use case is to have a scale that has C as the tuned note and is not tuned on A, that stores only 7 notes, but if those 7 notes don't generate the correct 35 I expect then I'll use 35 to correct it. As I don't think I want to respect the circle of fifths I will want to import the scala file for a byzantine scale that has only 7 notes then use the combo to expand to 35 and edit those notes until I get to a satisfying conclusion.

For storing fractions I don't have a strong opinion

**Comment by sraduvictor** [comment]
For point 6) If you change to see 35 from 7, edit the scale and save it like that the new scale will be the 35 one. But if you use the notes editor your first 7 notes will be the original ones (not true for the fifths editor)

**Comment by mgavioli** [comment]
**About pitch**, are you aware than MuseScore has a supported way of setting the global score pitch through the Synthesizer panel?

Among the ways you list for quicker communication, I thing **Skype** or a **Goggle+ hangout** to be the more direct; as neither of us is a native English speaker, I hope we can understand each other pronunciation; in the worst case, we can fall back to our common heritage and talk in Latin! :)

Assuming you are in Romania, 1 hour ahead of me (Italy): today, I will not be free before late in the night, say 23 or 24 your time. Otherwise, tomorrow in the morning, after 11 your time or Saturday almost all day after 11 your time (I am not sure 30 minutes will be enough, but we'll do what we can...)

**Comment by sraduvictor** [comment]
Hi @mgavioli , my skype contact is sraduvictor. I just added a user mgavioli to skype and am waiting for his approval.
I'm actually in California so the time difference between us is 9 hours. So 24 in Italy would be 15:00 for me.

For pitch. MuseScore has a way of setting global score pitch, but this is a global setting so it does not change from score to score. I would have to remember the A pitch for every single score I load and update it.
And after talking with @lasconic I understand that this master tuning is applied on top of the note tuning without changing the base pitch sound, so it could end up being tuned too much (more than 200) and end up sounding off. I tried looking at the code, but could not understand it to figure out how a fix for this issue would be made.

**Comment by sraduvictor** [comment]
Added tests for conversions to all modes.

**Comment by mgavioli** [comment]
My skype ID is different; but it is irrelevant: Skype seems not working at all on my machine (never managed to have Skype reliably working under Linux). Later in the evening I will try G+ hangout.

**Comment by sraduvictor** [comment]
My google account is sraduvictor@gmail.com

**Comment by sraduvictor** [comment]
Fixed a bug in the display of fifths editor.

**Comment by sraduvictor** [comment]
Ideas from discussion with @mgavioli :
  - add an option to not change pitch of the note if tuning is more than 200, default off
  - remove A tuning options
  - don't save the scale unless the user edited a note.
  - support fractions for absolute fractions, not just absolute cents but only for notes editor.
  - remove the combo that changes the number of notes to a checkbox that will show all 35 notes or only the ones from the scale.

**Comment by sraduvictor** [comment]
@mgavioli, I updated the PR with the ideas we discussed about. Please let me know if I should change anything else.

**Comment by sraduvictor** [comment]
I made another PR for saving the scale : https://github.com/musescore/MuseScore/pull/2428

**Comment by dmitrio95** [comment]
Archiving this pull request, please reopen if there is an interest in it.

**Pull request closed without merging**
