### PR TITLE
[WIP] Winportabletest + collect_artifacts

### PR DESCRIPTION
**Pull request by AntonioBL**
**Do not merge this**
This is just a WIP commit to obtain a portable executable (with hopefully telemetry enabled) for testing purposes.

If everything is ok, I will update the original implementation, ( https://github.com/musescore/MuseScore/pull/5508 )

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
The Linux builds fail at some Ubuntu stuff, but why? This PR doesn't change anything related to that as far as I can tell?

    + add-apt-repository -y ppa:ubuntu-toolchain-r/test
    Cannot add PPA: 'ppa:~ubuntu-toolchain-r/ubuntu/test'.
    ERROR: '~ubuntu-toolchain-r' user or team does not exist.


    $ sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    Cannot add PPA: 'ppa:ubuntu-toolchain-r/test'.
    Please check that the PPA name or format is correct.
    The command "sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"" failed and exited with 1 during .

**Comment by Jojo-Schmitz** [comment]
AppVeyor did build a PortabApp artifact though!

**Comment by AntonioBL** [comment]
Appveyor worked, but the artifact is not a 100% portable executable.
It leaves behind a couple of folders/files:
AppData\Local\MuseScore\MuseScore3\QtWebEngine\Default\File System
AppData\Local\MuseScore\MuseScore3\QtWebEngine\Default\Local Storage
The version I am building locally, on the other hand, works properly (i.e. it respects the setPersistentStoragePath I set); the main difference is that I am using Qt 5.12.8 32bit locally.
Today I will try a local build with Qt 5.9 32bit.

**Comment by Jojo-Schmitz** [comment]
Maybe building it without WebEngine?

**Comment by AntonioBL** [comment]
I found it is a problem of Qt 5.9.x (if possible, I wanted to avoid to completely disable the webengine). It uses the correct folder if I set the folder for the defaultProfile (note that in Qt 5.12.x this additional step is not necessary).
I verified with the artifact from this PR and updated the original PR.

I am closing this one.

**Pull request closed without merging**
