### PR TITLE
fix #285591: accidentals should tuck under notes

### PR DESCRIPTION
**Pull request by MarcSabatella**
The intent of this is to fix https://musescore.org/en/node/285591, and I'm coming close but running into issues.  So I'm submitting this PR as a work in progress, hoping maybe someone else can see a way out.

The good news is that my initial analysis was correct, simply leaving accidentals and other elements out of _spaceLw and _spaceRw *does* solve the problem.  It turns out we can't just remove the code calculating those variables because this is also the code used to *position* the symbols attached to chords.  But I was able to separate out the positioning from the allocation of space easily enough.  There is a slight complication with grace notes (which use the same code recursively), but nothing we shouldn't be able to solve.  I was able to get the following with little effort:

image

This is much better than 3.0.4 (which is similar to both 2.3.2 and current master):

image

Unfortunately, there is a problem with certain beamed note groups where the final stem direction and length is not known until long after segment spacing has been finalized.  In these cases, it is quite possible that at the point we are calculating the minimum distance between segment shapes, we might decide it is safe to tuck an accidental above a note, but it turns out to create overlap with the previous stem once its final direction and length are determined.  Thus we get the following:

image

This was the case in earlier 3.0 builds as well, we just didn't notice it (or maybe someone did, but it never got addressed).

The only solution I see is to figure out the beaming earlier in the layout process, but then there are also reasons why it needs to be as late as it does, so I don't see a way out.

Maybe someone else wants to take it from here?

### CODE REVIEW

**Comment by MarcSabatella** [comment]
One way to salvage something of this could be to make this a manual decision.  Like, if we kept the current behavior for safety, but made it so disabling autoplace on an accidental allowed it to tuck under.  Seems that actually accomplishes nothing now - it doesn't remove the accidental from any other collisions detection.  We could also consider extending the "local relayout" property to control this, or just add a new property.

**Comment by MarcSabatella** [comment]
Pushed a change to do exactly that.  Not nearly as nice as having this automatic, but better than nothing.

**Comment by MarcSabatella** [comment]
More thoughts on the beam issue:

I guess the reason we don't deal with beaming until later in layout is that the possibility of beaming across the barline means we don't know the full set of notes and hence cannot compute direction or stem lengths until all measures are accounted for.  Fair enough.  But, how about a pre-calculation for beams that are *not* cross barline?  Then the vast majority of beams would work with this.  We could also do something like temporarily assign a super-tall (in both directions) bbox to stems that *are* part of cross-measure beams, so we could avoid trying to tuck for those, and even then keep the idea of allowing disabling autoplace to circumvent that. (in this case, maybe it makes more sense to disable it for the beam).

Maybe this refactoring would also somehow help us with cross-*staff* beaming.

**Comment by MarcSabatella** [comment]
There has been some renewed attention on this via a few forum & Facebook posts, etc.  Actually, the biggest benefit potentially is really more of a side effect.  Right now accidentals etc always add a little extra space even when not necessary, due to the way the layout works (calculating min width then stretching).  The result is that even with four very widely spaced quarter notes, adding an accidental to one of them increases the spacing somewhat when it doesn't have to.  A few people have mentioned this as a significant issue for getting "professional" results.

In theory, my changes here could help (at least in the cases where the accidentals would tuck), and could possibly be adapted to help even more if I also provided a way to exclude accidentals from the note shape entirely.  Would have to be manual or there would be collisions galore, but a checbox beats needing to adjust leading space.  So sometime after things settled down post-3.3, I hope to revisit this.

To me, this is perhaps the biggest remaining opportunity for improvement I see in the default layout.

**Comment by MarcSabatella** [comment]
See for example https://www.facebook.com/groups/musescore/permalink/3663074770385481/?comment_id=3667702803256011 (I think that link works, "award-winning" comment from Barnie Snyman :-)

**Comment by Jojo-Schmitz** [comment]
rebase needed :-)

**Comment by dmitrio95** [comment]
@MarcSabatella do you plan to finalize this PR in the nearest future?

**Comment by MarcSabatella** [comment]
Realistically, I don't see a good automatic solution to the basic issue here, given the problem I mentioned regarding stem direction not being finalized until too late.  There may be some way around this, but given also the discussion in https://musescore.org/en/node/299741, I think probably this should all be looked at together.

However, I do think there is something salvageable here: the idea that disabling autoplace for an accidental should remove it from the shape for the note (same for dots and similar markings).  This would allow one to achieve the "tucking" behavior reliably with a single click (as opposed to trying to eyeball it with leading spacing adjustments).  And it *also* allows you to correct spacing for a measure as per the issue linked above.  It seems to come at no real cost, so I do think I would like to update this.  I will try to get it to it in the next day or two.

**Comment by MarcSabatella** [comment]
See https://github.com/musescore/MuseScore/pull/5840 for another, somewhat simpler, approach.  Here the only real change is in Chord::shape(), I simply don't bother including anything but the notes and stems if autoplace is disabled.  Going forward I'd be more likely to favor that approach most likely, but still, more work is needed.  So I don't think either of these will be usable as is yet,  This one can be closed (so I'm doing that), the other is worth keeping open though I think.

**Pull request closed without merging**
