### PR TITLE
Treat svgz file as a vector image

### PR DESCRIPTION
**Pull request by mercuree**
Musescore suddenly supports compressed svg  files (with `.svgz` extension) if you add them via drag&drop.
This PR fixes a situation where compressed svgs are incorrectly treated as raster images, which causes incorrect "pixelated" rendering and makes musescore slow.
Before:
before
After:
after

Explanations:
A compressed svg file is a regular gzipped svg.
Musescore accepts and renders svg files in these formats:
* plain svg with `.svg` extension (correct rendering)
* compressed svg with `.svg` extension (correct rendering)
* compressed svg with `.svgz` extension (incorrect raster rendering, fixed by this PR)
* compressed svg with `.svg.gz` extension (incorrect raster rendering, not covered by this PR)

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
why not adding ".svf.gz" too?

**Comment by cbjeukendrup** [comment]
Probably because the suffix will then be considered to be `gz` so `withSuffix("svg.gz")` doesn't work

**Comment by Jojo-Schmitz** [comment]
Some code (from Mu3):
```cpp
void MIconEngine::addFile(const QString &fileName, const QSize &, QIcon::Mode mode, QIcon::State state)
      {
      if (!fileName.isEmpty()) {
            QString abs = fileName;
            if (fileName.at(0) != QLatin1Char(':'))
                  abs = QFileInfo(fileName).absoluteFilePath();
            if (abs.endsWith(QLatin1String(".svg"), Qt::CaseInsensitive)
                || abs.endsWith(QLatin1String(".svgz"), Qt::CaseInsensitive)
                || abs.endsWith(QLatin1String(".svg.gz"), Qt::CaseInsensitive))
                  {
                  QSvgRenderer renderer(abs);
                  if (renderer.isValid()) {
                        d->stepSerialNum();
                        d->svgFiles.insert(d->hashKey(mode, state), abs);
                        }
                  }
```

**Comment by mercuree** [comment]
> why not adding ".svf.gz" too?

Initially I added support for .svg.gz, but it turned out that the file was still saved as .gz inside mscz. When you open the project, it will again be treated as a raster image. Additional changes need to be made, which is inconsistent with my almost zero  C++ knowledge😁
Feel free to create more proper and complete PR and I will close mine

**Comment by Jojo-Schmitz** [comment]
Yes, I'm currently backporting this to Mu3. And found a few other places where we cpuölc/shpuld support `*.svgz`, in file.cpp and in palette.cpp

**Comment by Jojo-Schmitz** [comment]
in Mu4 it is in
https://github.com/musescore/MuseScore/blob/b38394fb5cf4bfdcbbf7b32248783889ffc5db85/src/notation/internal/notationactioncontroller.cpp#L1244-L1245
, 
https://github.com/musescore/MuseScore/blob/b38394fb5cf4bfdcbbf7b32248783889ffc5db85/src/notation/internal/notationinteraction.cpp#L4291
and https://github.com/musescore/MuseScore/blob/b38394fb5cf4bfdcbbf7b32248783889ffc5db85/src/palette/view/widgets/palettewidget.cpp#L820

**Comment by mercuree** [comment]
Thank you, @Jojo-Schmitz! Added your changes. Everything seems to be working

**Review by Eism — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved

**Pull request merged**
