### PR TITLE
[MU4] Quality of Life Improvement: Double Click to enter Note Input Mode

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/10642
Closes: https://github.com/musescore/MuseScore/pull/10691

### CODE REVIEW

**Comment by Tantacrul** [comment]
> What's wrong with #10691?

Lines of code were just deleted that were important. It was mentioned in that PR.

**Comment by RobFog** [comment]
> > What's wrong with #10691?
> 
> Lines of code were just deleted that were important. It was mentioned in that PR.

Do you mean [this comment](https://github.com/musescore/MuseScore/pull/10691#discussion_r853208743) from 24 days ago?

I'm just confused because the last comment from four days ago is "Just tested it. Looking good!" and there's no other recent comment stating that the pull request is lacking something.

**Comment by Tantacrul** [comment]
> > > What's wrong with #10691?
> > 
> > 
> > Lines of code were just deleted that were important. It was mentioned in that PR.
> 
> Do you mean [this comment](https://github.com/musescore/MuseScore/pull/10691#discussion_r853208743) from 24 days ago?
> 
> I'm just confused because the last comment from four days ago is "Just tested it. Looking good!" and there's no other recent comment stating that the pull request is lacking something.

Me being happy from an experience POV does not mean the devs are happy and the fact that the request was made 24 days ago should really be all you need to know to learn why Roman decided to just do it himself.

**Comment by RobFog** [comment]
Mr Pudashkin asked for an explanation, the contributor gave one and never heard back again. And now, three weeks later, a new PR appears that invalidates theirs. I think I'd be miffed if I were them.

**Comment by Tantacrul** [comment]
> Mr Pudashkin asked for an explanation, the contributor gave one and never heard back again. And now, three weeks later, a new PR appears that invalidates theirs. I think I'd be miffed if I were them.

Incorrect. The contributor didn't understand why the question had been asked and @RomanPudashkin was faced with the need to get the thing finished.

Please don't fight others battles and stir up pointless arguments. We don't do what we do for no reason.

**Comment by RomanPudashkin** [comment]
@RobFog 

This PR is mainly a proof of my assumption (that we can achieve the same result without removing some logic in NotationViewInputController::handleLeftClickRelease, which is quite important because the process of selecting elements is more complex than it may seem). It also solves some problems related to the "Edit element" option  in the context menu that I noticed in the origin PR while testing it.

I didn't respond to the author in time, and that's entirely my fault. Sometimes in order to give a good code review, I have to delve so deeply into an issue that it actually means researching the problem and finding a solution myself. I knew that origin PR had problems (and I wrote about them), but I couldn't advise anything to fix it without trying it myself. And because the original issue has a low priority, it fell out of my focus.

@helloworld12321 I sincerely apologize if this PR offended you. But thank you so much for your help!

**Pull request merged**
