### PR TITLE
glissando_on_tied_notes

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/20570

See: https://github.com/musescore/MuseScore/pull/19921/files#diff-dbddb0383d841774ae083ea615b9f6e0be047107d6ce64676dc31bc062faafe7L125

### CODE REVIEW

**Comment by MarcSabatella** [comment]
I don't suppose the same type of fix could be relevant for falls?  These have never worked correctly for tied notes (see https://github.com/musescore/MuseScore/issues/12971), and unfortunately this PR doesn't in itself fix it.

**Comment by DmitryArefiev** [comment]
Tested #20570 on Win10, Mac13.6 - **FIXED**

**Comment by RomanPudashkin** [comment]
>I don't suppose the same type of fix could be relevant for falls?

No, unfortunately. We need a different solution for that issue

**Comment by Jojo-Schmitz** [comment]
As per https://github.com/orgs/musescore/projects/36 this is awaiting to get ported to 4.2.1

**Pull request merged**
