### PR TITLE
Add SMuFL "Other baroque ornaments" (U+E570–U+E58F) to mscore.ttf

### PR DESCRIPTION
**Pull request by mgavioli**
The following ornaments, of which I know reasonably well the sources, have been exemplated on known sources (and also made uniform with similar existing Emmentaler glyphs):

*) U+E570 Port de voix
*) U+E575 Hook before note
*) U+E576 Hook after note
*) U+E57F Oblique straight line tilted SW-NE
*) U+E580 Oblique straight line tilted NW-SE
*) U+E581 Comma
*) U+E582 Shake
*) U+E583 Vertical line
*) U+E584 Shake (Muffat [but not only!])
*) U+E587 Schleifer
*) U+E588 Pincé (Couperin)
*) U+E589 Tremblement appuyé (Couperin)

The other glyphs in the range have been copied over from Bravura with no modification (they are probably a bit too large for Emmentaler average sizes and weight).

This is preliminary to a better support for Baroque ornament.

- [X] I signed [CLA](https://musescore.org/en/cla)
- [X] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Don't these new glyphs need to get added to fonts/mscore/metadate.json too?

**Comment by mgavioli** [comment]
About `fonts/mscore/metadata.json`: no other ornament occurs in it (only some clefs, flags, note heads and some accidentals), so I cannot see a clear reason to add these ones instead.

About not duplicating glyphs from Bravura: yes, I know it is not **needed**; still, it is seems to me cleaner to add the entire section (which has rather few glyphs anyway) and have all the glyphs together rather then force the user to jump back and forth between the two fonts scrolling pages and pages of Bravura glyphs. It also seems to me that they (or most of them) are likely to require small 'tunings' to suit overall Emmentaler colour and style, which only the actual use can show.

I can easily remove them of course, if a more or less general consensus deems them superfluous.

**Comment by Jojo-Schmitz** [comment]
Maybe I missunderstand the purpose of those `metadata.json` files in general or of `fonts/mscore/metadata.json` in special?

**Comment by mgavioli** [comment]
I has the same (mis-?)understanting: so I went to `mscore/metadata.json` to add the new glyphs, but I found that only a few glyphs, special in a way or another, were listed. Possibly, things used to be in some way and changed 'somewhen'...

**Comment by anatoly-os** [comment]
`metadata.json` contains the adjustments if needed according to SMuFL specification.
The ornaments from this PR don't contain any additional adjustments. Compare, i.e.
https://www.smufl.org/version/latest/glyph/ornamentHookAfterNote/
Screenshot 2020-04-14 at 15 49 38

and

https://www.smufl.org/version/latest/glyph/noteheadPlusBlack/
image

**Pull request merged**
