### PR TITLE
fix #275706: Place all articulations at stem side if direction and anchor is set to automatic

### PR DESCRIPTION
**Pull request by tobik**
I removed the restriction to staccato and tenuto so that now any articulation is placed at the stem side of the note if multiple voices exists

### CODE REVIEW

**Comment by anatoly-os** [comment]
@tobik could you please add related issue number to the title of the PR, add fix #XXXXXX at the beginning of the commit message so the related issue can be closed automatically?
Also, I'm not sure your changes are fully correct. Did you check the case in Behind Bars?

**Comment by tobik** [comment]
@anatoly-os I added the issue number to the PR title and the commit message as requested.

What exactly do you mean with Behind Bars? I checked it behind all sorts of bar lines as you can see in the attached picture. 

articulation-direction-demo3

**Comment by tobik** [comment]
I just checked it with articulations-ref.mscx and there is a issue with articulations defined "Above" in front of a bar. 

I will have to check that!

**Comment by Jojo-Schmitz** [comment]
@tobik "Behind Bars" is a book written by Elaine Gould and it basically describes the standards of music notation

**Comment by tobik** [comment]
I don't have access to this "Behind Bars"
But there are still issues in comparisation with 2.0.3.
1. With direction up and anchor below chord: The direction is still down.
2. With direction up and anchor below staff: The position is above staff.
I will have a look at this too

**Comment by handrok** [comment]
Notice that in current implementation the order of layouting element is importing. Changing order leads to some elusive bugs. I saw it before in my work. 
Layout of some elements is called in getNextMeasure function. Layout of elements which do not participate in autoplacement is called in this function. Even horizontal layout of lyrics is called here (notice vertical layout is called in another place). 
 Chord::layoutArticulations() is called also from getNextMeasure(). And this function layouts only staccato and tenuto. Layout all other articulation are called in  Chord::layoutArticulations2() which is called after layouting slurs.  I am not sure the results of changing order of calling layout articulation. But may be it leads to incorrect placement of elements related to the one note. May be slur with articulation are placed incorrectly. To respond for this question investigation is needed

Let me suggest solution which do not changes the order of calling layout of articulation
Change
if (!(isStaccato || a->isTenuto()))
   continue; 
to 
if (!(isStaccato || a->isTenuto() || a->isStaccatoTenuto))
   continue; 
And add someting like:
bool Articulation::isTenuto() const
      {
      return _symId == SymId::articTenutoStaccatoAbove   || _symId == SymId::articTenutoStaccatoBelow;
      }

Can it solve the original problem?

**Comment by tobik** [comment]
Thank you for the detailed explanation, very appreciated! 

The suggested solution would solve the issue for portato but the issue occurs with any articulation. And there is the additional issue with wrong directions as described above. This is relevant to portato but not staccato or tenuto.

I will have a look at Chord::layoutArticulations2()

**Comment by tobik** [comment]
I checked the failed cases of the travis tests in "Behind Bars" and IMO it is correct with my latest commit and the tests are wrong. 
Gould also says: "The strong accent usually goes above the stave, regardless of stem direction." I will do another commit that implements this exception.

**Comment by Jojo-Schmitz** [comment]
`git reset` to before that commit, re-commit without that file, `git push -f`

**Comment by tobik** [comment]
@Jojo-Schmitz Thank you! Done

**Comment by tobik** [comment]
Test errors:

1.  Articulations in measures with multiple voices have to go to the stem side. 
`<diff -u libmscore/parts/voices-ref.mscx /home/travis/build/musescore/MuseScore/mtest/voices.mscx failed`
This is now true for the two accents in the combined part and for the accent in piano part. 
Articulations in measures with single voice should be placed at head side. This is now true for the accent in the trombone part.

2.  Strong accents should be placed always above the stave according to Gould, p. 117
`<diff -u libmscore/implode_explode/undoExplode01-ref.mscx /home/travis/build/musescore/MuseScore/mtest/undoExplode01-test.mscx failed`
`<diff -u libmscore/compat206/articulations-ref.mscx /home/travis/build/musescore/MuseScore/mtest/articulations-test.mscx failed`
This is now true for the strong accents in both files.

**Comment by anatoly-os** [comment]
@tobik could you please squash all commits?

**Comment by anatoly-os** [comment]
Tests don't look good, unfortunately.

**Comment by tobik** [comment]
Yes thanks, I have seen. A new test is failing where strong accents are at stem side rather then above the staff as suggested by Gould. I fixed this locally but now I am struggling with git. I will try again tonight.

**Comment by tobik** [comment]
I'm afraid I managed to drop my previous changes with my latest commit ;-(

**Comment by dmitrio95** [comment]
@tobik There seems to be no documentation on this but if you want to add something to the automated tests then take a look at the tests in `mtest/libmscore` to see some examples. Still it depends on what do you exactly want to test. If it is only a visual appearance that you want to test then such tests are not yet automated (see `vtest` folder for them).

**Comment by tobik** [comment]
All changes are back in place

**Comment by tobik** [comment]
@dmitrio95 I will have a look at this tests. Thank you. 
@anatoly-os The changes are back in place.

**Comment by Jojo-Schmitz** [comment]
That merge commit should not be there.

**Comment by tobik** [comment]
I resolved the conflict in the browser at github. This created this merge. What can I do?

**Comment by Jojo-Schmitz** [comment]
git reset 9e81dd9 --hard

**Comment by tobik** [comment]
Would you please merge this pull request? I'm editing several scores that only work with this patch.

**Pull request merged**
