### PR TITLE
Update include guards

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Better change those other headers, we try to avoid changing code in thidrparty

**Comment by janisozaur** [comment]
Fair point, I will updated the PR.

**Comment by janisozaur** [comment]
Done.

**Comment by Jojo-Schmitz** [comment]
Thanks. Have you signed the [CLA](https://musescore.org/cla) yet (and under which username)?

**Comment by anatoly-os** [comment]
@janisozaur I don't see you username in the list on 
https://musescore.org/cla page. Could you please complete signing?

**Comment by Jojo-Schmitz** [comment]
@anatoly-os but you did merge @janisozaur's #4073 ;-)

**Comment by anatoly-os** [comment]
@Jojo-Schmitz my fault. I believed him :)

**Comment by Jojo-Schmitz** [comment]
I guessed that :-)

**Comment by anatoly-os** [comment]
@janisozaur please reopen when you sign CLA

**Pull request closed without merging**
