### PR TITLE
Fix wrong checkbox state for frame exclusion from parts

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #20250
Reverts: https://github.com/musescore/MuseScore/pull/19997

### CODE REVIEW

**Comment by mike-spa** [comment]
@bkunda @oktophonie I've added a commit which changes the default behaviour for frames, which are now cloned. Also @miiizen give this a second look when you can, given that you worked a lot on this too

**Review by cbjeukendrup — APPROVED** [review]

**Review by miiizen — APPROVED** [review]

**Review by bkunda — CHANGES_REQUESTED** [review]
Just a couple of things to address if possible: 

1. Vertical text frames don't delete from parts when being deleted from the main score (they should)
2. Text in text frames is not populating across parts

[See video](https://www.dropbox.com/s/6mkoul8gglkqxcp/frame-exclusion-from-parts.mov?dl=0)

Of course, if these things are beyond the scope of this PR, I'll happily approve it on the basis of the corrected checkbox-state interaction and raise them as new issues!

**Comment by mike-spa** [comment]
1. Was caused by [this](https://github.com/musescore/MuseScore/pull/19997), which shouldn't have been merged (my fault for not reviewing it). Now reverted, and is back to working as expected.
2. Fixed.

@bkunda

**Review by oktophonie — APPROVED** [review]

**Comment by mike-spa** [comment]
@bkunda fixed!

**Review by cbjeukendrup — APPROVED** [review]

**Pull request merged**
