### PR TITLE
fix #300694 - Capella .capx import doesn't properly recognize hidden empty staves at start of score

### PR DESCRIPTION
**Pull request by lvinken**
…empty staves at start of score  + collect_artifacts

Resolves: https://musescore.org/en/node/300694

As staffs can be missing from systems in capx files (when they are empty) the staff sequence number in the capx file cannot be used to determine its position in the system. Instead the staff's layout attribute must be matched with the staffLayout's description attribute. Further complication is that a completely empty first staff will lead to a corrupt MuseScore file on import. This is fixed by adding time signatures to empty staves.

Issue discussed with Jojo in private email.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Thanks!. I'll ask the reporter to test the artifact.
Typo: Capelle vs. Capella ;-)

**Comment by lvinken** [comment]
Would be nice to get a confirmation from the original reporter. As far as I can tell the Feliz and Schubert examples import OK. Same goes for MuseScore's testfiles.

**Comment by Jojo-Schmitz** [comment]
BTW: if you rebase and push force now, there will also be artifacts generated for Linux (AppImage) and Mac

**Comment by Jojo-Schmitz** [comment]
Original reported confirmed that the issue is fixed with this.
There are another, entirely unrelated issues though, reg. a) the beaming (should mostly be unbeamed in that Feliz) and b) visibilty (where unison in that Feliz, Alto and Tenor are set to invisible in Capella).

**Pull request merged**
