### PR TITLE
Fix crash when removing instruments in some cases, caused by brackets

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #17390
Resolves: #17392

See commit messages for explanation

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
@DmitryArefiev I rebased it and now it should indeed fix https://github.com/musescore/MuseScore/pull/17405#issuecomment-1531359555 too.

**Comment by DmitryArefiev** [comment]
@cbjeukendrup All mentioned crashes are fixed. 

But I found **another one** with Undo+Redo and additional staves. Can you check it please?



https://user-images.githubusercontent.com/90187801/236423699-21bcb016-b4f1-4725-b8ba-7690a5a7c89e.mp4

**Comment by cbjeukendrup** [comment]
@DmitryArefiev That one I haven't seen before. It seems unrelated to the earlier crashes, but I will investigate a bit more.

**Comment by cbjeukendrup** [comment]
@DmitryArefiev I investigated more, and it turns out that this crash is unrelated to the crash this PR is solving, and it seems a bit more difficult to solve. So I think it is better to do it separately. I've already created an issue for it: #17494

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Cool. Thanks!

**Pull request merged**
