### PR TITLE
fix #288372: S button beside "placement" property of fingering resets the property

### PR DESCRIPTION
**Pull request by Howard-C**
Resolves: https://musescore.org/node/288372.

The independent `inspector_fingering.ui` isn't used anywhere, as `InspectorFingering` directly inherits `InspectorStaffText` and uses the same `.ui` file, therefore the S button still appears for fingering inspector but doesn't point to an existing style.

This patch makes `getPropertyStyle()` for fingering return `Sid::NOSTYLE` if the property is `Pid::PLACEMENT`, so no S button is created for it when intializing inspector.

### CODE REVIEW

**Comment by Howard-C** [comment]
__Note:__ I chose to delete `inspector_fingering.ui` because it is currently incomplete in design, it lacks the "placement" setting, and it simply isn't used anywhere. In order to make "placement" for fingering to be "Auto, Above, Below" later, an independent `.ui` is still necessary, but it's easier to make a copy of `inspector_stafftext.ui` and revise than to change the incomplete `inspector_fingering.ui`. So anyway, that file is best to be deleted for now.

**Comment by dmitrio95** [comment]
Doesn't `inspector_fingering.ui` also need to be removed from `CMakeLists.txt`?
https://github.com/musescore/MuseScore/blob/2a1600845cc07a2a29f312998c877c6169ba45f4/mscore/CMakeLists.txt#L198

**Comment by Howard-C** [comment]
> Doesn't `inspector_fingering.ui` also need to be removed from `CMakeLists.txt`?

My bad.

**Comment by MarcSabatella** [comment]
The Inspector is not the only thing that getPropertyStyle() is used for. I am concerned that changing this will break something about the behavior of fingering, although offhand I can’t say what. Let me think about it further.

**Comment by Howard-C** [comment]
> The Inspector is not the only thing that getPropertyStyle() is used for. I am concerned that changing this will break something about the behavior of fingering, although offhand I can’t say what. Let me think about it further.

But it is true that the "placement" property of fingering doesn't have a linked style, so if you ask me I can't think of anything that will be broken due to this change.

**Comment by MarcSabatella** [comment]
No, there *is* a style for fingering placement.  I'm fuzzy on the details, but as I recall it was needed to make sure the different types of fingering all behaved the right way with respect to automatic placement, or maybe it was something about fingering mode.  I just remember there being a reason it needed to be this way, but I don't recall offhand what it was.  Of course, it's also possible other things have changed since then and the reaosn might no longer need to apply.  Anyhow, further testing and review is required.

And getPropertyStyle() is used in *many* places, both directly and indirectly.

**Comment by Howard-C** [comment]
But all other references of `getPropertyStyle()` in `libmscore` are of different elements, and since `Fingering` is already a `final` class, I don't see anything that can be related. Something in `mscore` might be though as you said so.

**Comment by MarcSabatella** [comment]
See #4702 and study the comments there, and what that code is doing.  This is what needs to be tested - this is where the property got added as a styled property.  My read of this is that the styled property was needed for the "flip" command to function properly.  See in particular this section:

https://github.com/musescore/MuseScore/pull/4702/files#diff-32e6dbba79e3bb125b29f1ec59ab3719R2088

I think what is happening is, absent an "auto" value, we rely on the placement being "styled" to tell us the same basic thing - that the user has not set an explicit placement, so we should calculate it automatically.  Flipping the fingering (via "X") changes it to unstyled (different than nostyle).

So my prediction is that your change will either break the automatic placement - it will cause PropertyFlags() to return NOSTYLE in all cases.  Thus this code right here will never result in calculatePlacement() being called, so the places where the placement is supposed to be below the staff by default (eg, bottom staff of piano) won't work.

**Comment by MarcSabatella** [comment]
The most relevant use of getPropertyStyle() in this context is to determine what gets returned by propertyFlags().  That function is used tons of places throughout the code.  Changing it's behavior always has repercussions that need to be carefully considered.

**Comment by Howard-C** [comment]
With my fix, placement tags will be recorded in `.mscx` files, but the placement doesn't have a problem.

**Comment by MarcSabatella** [comment]
So, you tested adding a fingering to the bottom staff of a piano and verified the fingering shows below?  And this survives relayout as well as save/reload?   If you set a breakpoint on that line I highlighted, what happens?

**Comment by Howard-C** [comment]
Survived all these. And when I set a breakpoint, it is triggered an awful lot of times, way more than the total number of notes in the score. Does this suggest something's wrong?

**Comment by MarcSabatella** [comment]
Hmm, I see what you're saying about why this works, but it still makes me extremely uncomfortable.

It's simply not true that getPropertyStyle() is only used by the Inspector.  It's used in several places in ScoreElement - perhaps most importantly, for propertyDetault() and undoChangeProperty().  Also, as far as I know this would represent the only place in the code we deliberately allow these values to be out of sync (letting propertyFlags() say STYLED or UNSTYLED even though getPropertyStyle says NOSTYLE).  So if nothing else, it's a hack that would need to be thoroughly documented via comments in the code to explain the need for the discrepancy to and to warn about future use of these functions for fingering.  And I'd want to see automated tests for some of the code paths involving those other functions, to be sure some future changes don't break this scheme.  For example, I see propertyDefault() being used in reset, so an automated test for the reset command (Ctrl+R) would be good.  And since it's also used in writeProperty(), make sure there are tests that involve writing the property in all its states - left at default, flipped to the opposite side, and flipped back tot he same side as the default.

I still question whether it's worth it the risk just to fix a minor UI glitch.

**Comment by MarcSabatella** [comment]
Also be sure to add tests involving changing style.  See the use of getPropertyStyle() within ScoreElement::styleChanged().  Here we are explicitly using both propertyFlags() and getPropertyStyle() in a way that relies on their relationship.  You might consider actually testing here for the case where getPropertyStyle() returned NOSTYLE, as I could imagine that actually crashing, if not today, then in some future where the implementation of setProperty or styleValue changes.

**Comment by Howard-C** [comment]
OK, now I see some references in `scoreElement.cpp`, I apologize for not being meticulous.
I agree that the current way to fix this could set off problems in the future, if not now. I'm thinking of another way of letting the existing style `fingeringPlacement` speak for itself, so the property does get customized if the S button is clicked.

**Comment by MarcSabatella** [comment]
No worries, if I thought there was an easy solution, I'd have implemented it in the first place :-)

FWIW, to look at it from a high level perspective:

propertyFlags() normally would tell you if a property is styled or not (where "not" can mean either unstyled or nostyle).  For a property that is styled, that means its value comes from the associated style.  So it's really assumed that any property that is styled, does in fact have a corresponding style, which would be returned by getPropertyStyle().  That is, in short, why it's potentially problematic to have a property that says it is styled but in fact has no corresponding style - who knows where we might now or in the future rely on the fact that styled properties actually have a style.

The basic problem with set as style here is that there are only two values for placement: above and below.  But the default value is and needs to remain something different from this: "auto" depending on voice and/or staff.  I suspect there are other places where this could be helpful, so to me, the change that's really worth contemplating is how to add an "auto" value for placement.  Anything else seems like just more hackery to solve what is, in the end, a very minor glitch.

So to me, if you're looking for relatively easy things to fix, there are things that are both easier and more valuable.  But if you're looking to invest the effort and really do it what it takes to allow one to "set as style" on the placement, might as well do it right.

That said, here's another thought.  Probably most people who request this are not thinking about the bottom piano staff - they are wanting to set fingering below staff for some other reason.  So, let's find out *why* they want fingering below, and see if maybe there isn't a simpler way to get this.  For example, what if we simply added a "fingering below" element to the palette, one in which the placement was explicitly set to below?

**Comment by Howard-C** [comment]
I agree, the default value cannot be a constant, that's why the issue cannot be fixed in the way others are fixed.

And yes, if you agree to implement "Auto" now (you once said this should probably wait until later), I will work on it, and I believe I have the ability to learn and do that.

The explicit "fingering above" and "fingering below" intrigue me, are there existing instances of elements defined that way? I don't care much about the placement of fingerings (not from a programmer's prospective definitely) when I read piano scores, but through a quick browse of a random score, I found that those placements which don't follow the placement principal in MuseScore are rare enough to let users manually adjust to without feeling much trouble. So I would prefer not to change the current automatic mechanism. Maybe it's time to implement that "Auto" thing after all.

**Comment by MarcSabatella** [comment]
I'm not volunteering to implement "auto", but I am saying I'd support someone else working on that :-)

Meanwhile, though, an explicit "fingering below" is trivial - just add the appropriate tag to the palette item within the workspace.  We do this already for expression text, which is just staff text with a different text style and explicitly set below.  In fact, you can do this for fingering already, just add a fingering to your score, flip it below, then add it back to the palette,  Now you have a fingering below.

**Comment by Howard-C** [comment]
Well, even though I know "fingering above/below" is much easier to encode, I still stand for "Auto". I created a forum topic for this: https://musescore.org/en/node/297092, please continue the discussion in that thread. I'll close this PR.

**Pull request closed without merging**
