### PR TITLE
fix #305717: chord symbols attached to fret diagrams don't link to parts

### PR DESCRIPTION
**Pull request by jthistle**
See #6109 - this is a version based on master.

### CODE REVIEW

**Comment by vpereverzev** [comment]
@jeetee looks like PR is hanging (sorry on behalf of the in-house team)
looking forward for rebase

**Comment by jeetee** [comment]
@jthistle will gladly solve that for you and keeps me out of it ;-)

**Comment by jthistle** [comment]
Sorry @jeetee , is that an offer to rebase? If it is, then please go ahead :)

If not, then I'll try to find some time @vpereverzev to do so, thanks for the heads up and don't worry about the delay.

**Comment by jeetee** [comment]
I think you can just close this off, as it looks to me that @anatoly-os already manually merged this in https://github.com/musescore/MuseScore/commit/914d306189a227944e3ecc3e59096b22a6f39ff1

**Comment by Jojo-Schmitz** [comment]
> I think you can just close this off, as it looks to me that @anatoly-os already manually merged this in [914d306](https://github.com/musescore/MuseScore/commit/914d306189a227944e3ecc3e59096b22a6f39ff1)

That though was manually merging #6109

**Comment by Jojo-Schmitz** [comment]
Oh, sorry, you're right (of course ;-)) it is merged manually into **master**, so indeed this PR here can get closed

**Pull request closed without merging**
