### PR TITLE
fixed #14147: Export Audio process can't be cancelled

### LINKED ISSUE #14147: [MU4 Issue] Export Audio process can't be cancelled
**Describe the bug**
After selecting the audio format, clicked export to start the export process. First time I exported.
I discovered it was painful slow and thought I better cancel the export however there is no option to stop this process.
Guess I can hard kill the running process in the OS, but would be nicer if it can just be stopped in the GUI as well.

**To Reproduce**
1. Open a score
2. Open the export menu
3. Set the format to WAV audio
4. Select a part
5. Click Export
6. Select the location to store the file
7. And now try to stop the export

**Expected behavior**
An option to stop the export process would really be nice.

**Screenshots**
image

**Platform information**
 - OS: Windows 10

**Additional context**

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #14147

### CODE REVIEW

**Comment by DmitryArefiev** [comment]
@jessjwilliamson Hi, there is some difference between PR and your mockup. Is it fine the text are centered? (the same as in Save to cloud progress window - https://github.com/musescore/MuseScore/issues/14249#issue-1431657391)

https://github.com/musescore/MuseScore/issues/14147#issuecomment-1381759490

Screenshot 2023-01-19 120114

**Comment by jessjwilliamson** [comment]
> @jessjwilliamson Hi, there is some difference between PR and your mockup. Is it fine the text are centered? (this is the same as in Save to cloud progress window - [#14249 (comment)](https://github.com/musescore/MuseScore/issues/14249#issue-1431657391))
> 
> [#14147 (comment)](https://github.com/musescore/MuseScore/issues/14147#issuecomment-1381759490)
> 
> Screenshot 2023-01-19 120114
> 
> (Also, we can center **Cancel** button to be more balance with centered 'Exporting audio' text)

Spoke to @bkunda about this as there's been some confusion with the UI. With these dialogs if we can make them look more like [this](https://github.com/musescore/MuseScore/issues/14147#issuecomment-1381759490) 
- Rounded corners
- Strokes applied
- Title text aligned to left

That'll be great. @Eism

**Comment by DmitryArefiev** [comment]
Tested #14147 on Win10, Mac12, LinuxMint 22.04 - **FIXED**    

@jessjwilliamson It looks fine now. You can recheck in master after merge

**Comment by jessjwilliamson** [comment]
@eism Can the progress filled colour (in this screenshot, the purple) be placed inside the stroke of the bar? Needs that tweaked. Rest is great! :D 
Screenshot 2023-01-23 at 10 55 12

**Comment by jessjwilliamson** [comment]
Much better! Thank you @Eism!

**Review by vpereverzev — APPROVED** [review]

**Pull request merged**
