### PR TITLE
Fix #81876 addendum - Add clef glyphs to MScore font

### PR DESCRIPTION
**Pull request by mgavioli**
Fix #81876 addendum - Add clef glyphs to MScore and MScoreText fonts

Adds to the MScore and MScoreText fonts the two clef glyphs defined in the main fix ( https://github.com/musescore/MuseScore/pull/2241 ).

Also adds three more clefs with some probability of being added in the (not so distant) future and which presumably do not require any special management code-wise:
- "gClef8vbCClef" U+E056 (and its element "cClefCombining" U+E061)
- "semipitchedPercussionClef1" U+E06B
- "semipitchedPercussionClef2" U+E06C

The `glyphnames.json` includes the two glyphs already included in the main fix, so this fix can be merged after the main fix without mergins problems (or at least so I believe!).

### CODE REVIEW

**Comment by lasconic** [comment]
Could you add them in mscoretext too ?

**Comment by Jojo-Schmitz** [comment]
I've removed the glyphnames.json modification for Emmentaler from my PR, #2241 so no conflict should occur

**Comment by mgavioli** [comment]
@lasconic : yes, I can add those glyphs to MScoreText too. Looking at clefs in MScoreText, is something wrong with glyphs U+E052 and U+E054? Shouldn't they be clefs?

**Comment by mgavioli** [comment]
@lasconic : also U+E06D (shouldn't it be the "TAB" clef?)

**Comment by mgavioli** [comment]
@lasconic : glyphs added to MScoreText too. No `glyphnames.json` for it, is it?

**Comment by lasconic** [comment]
No, it uses the same glyphnames.json, that's why I asked, it's better if they are in sync. Thanks!

**Comment by Jojo-Schmitz** [comment]
@Gootector: Any chance you'd be adding These glyphs to Gonville too?

**Pull request merged**
