### PR TITLE
fix #36981: add partName tag to parts on creation

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
using the same text as in title frame, for use in Header/Footer

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
may need to get some mtests fixed

**Comment by MarcSabatella** [comment]
I'm surprised it's as few tests as it is!  Just ones in chordsymbols and parts.  I have a big PR from last summer with a whole bunch of updates to the parts tests that is now hopelessly out of date but worth updating.  Maybe it makes sense to kill two birds with one stone here.  Next time I'm snowed in, maybe...

**Comment by Jojo-Schmitz** [comment]
a) if you want to grab this change and integrate it into yours, feel free
b) if you can tell me which tests exactly fail and why, I'd be able to fix them (tomorrow)

**Comment by Jojo-Schmitz** [comment]
OK, I think on tst_chordsymbols the only test likely to fail is no_system, as that creates a part, and the -ref file's parts don't have the new metaTag

**Comment by Jojo-Schmitz** [comment]
Hmm, OK, apparently this isn't all, but this time Travis was generous enough to give the details about the failues...
So now I should have got'em all...

**Comment by Jojo-Schmitz** [comment]
Apparently not, and this time without the details I'd need :-(

**Pull request merged**
