### PR TITLE
Listening to MIDI Machine Control messages [welcome for testing]

### PR DESCRIPTION
**Pull request by Igevorse**
MIDI Machine Control (MMC) is a feature that helps to control playback of MuseScore via MIDI by sending special MIDI messages.
For now MuseScore is able to listen to this messages, not send them.
#### New opportunities unlocked:
- Synchronize MuseScore with software that doesn't support JACK Transport
- Control playback of MuseScore even without JACK
#### Supported events:
- System realtime messages:
  - Start (0xFA)
  - Stop (0XFC)
  - Continue (0xFB)
  - Song Position Pointer (SPP) (0xF2)
- System exclusive (SysEx) messages: (0xF0 0x7F <deviceID&gt; 0x06 <command&gt; 0xF7)
  - Stop (command: 1)
  - Pause (9)
  - Play (2)
  - Deferred play (3)
  - Rewind (5)
  - Goto/Locate (0xF0 0x7F &lt;deviceID&gt; 0x06 0x44 0x06 0x01 <hr&gt; <mn&gt; <sc&gt; <fr&gt; <ff&gt; 0xF7) 
#### It works with:
- JACK MIDI
- ALSA MIDI
- PortMidi (partially)
#### Events that are not supported for PortMidi:

System exclusive messages
#### UI changes:
- "Accept MMC messages" checkbox in Preferences->I/O
- Combo box for selecting Device ID
#### Tips
- Since MuseScore is a note editor/engraver, it's better to use SPP message instead of Goto/Locate. SPP operates with MIDI beats while Goto/Locate with time in seconds/frames.
-  Use small MIDI buffer to minimize the delay between applications. For JACK it is 64/128 samples. Using "ALSA Raw-MIDI" MIDI driver instead of "ALSA Sequencer" reduces the delay twice.
- Not all sequencers can handle MIDI realtime messages in real time, so if you want to seek/locate while playing it's better to stop playback, seek and play again.
- There is no restriction on using MMC with JACK Transport, but you can get a delay or other surprises.

Welcome for testing!

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
rebase needed...

**Comment by Igevorse** [comment]
@Jojo-Schmitz rebase is done.

**Comment by Jojo-Schmitz** [comment]
unfortunatly another rebase is needed

**Comment by dmitrio95** [comment]
Archiving this for now, feel free to reopen if there is an interest in adding this feature.

**Pull request closed without merging**
