### PR TITLE
[MU4] Sub menu close animation fix

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #9055
Resolves: #9056
Resolves: #10681
Resolves: #11860

### CODE REVIEW

**Comment by bkunda** [comment]
@Eism this works like a dream on Mac ☺️. Fixed!

But on Windows, I still see an apparent delay when moving from one sub menu to another (particularly noticeable on longer menus):

https://www.dropbox.com/s/vvg5l1pel76gmrr/windows-menu-lag.mp4?dl=0

Tooltips in Windows experience the same problem:

https://www.dropbox.com/s/ei9y4go21dwqkeb/windows-tooltip-lag.mp4?dl=0

**Comment by Eism** [comment]
@bkunda please recheck latest changes

**Comment by bkunda** [comment]
@Eism this issue still occurs in Windows for me

**Comment by Eism** [comment]
@bkunda 
I added animation for tooltips and menus. It should have solved your problem
Please recheck

**Comment by bkunda** [comment]
> @bkunda
> I added animation for tooltips and menus. It should have solved your problem
> Please recheck

@Eism I'm afraid this makes it worse. There should be no need for any additional animation. When the user leaves one menu and moves to another one, the first sub-menu should immediately be replaced by the next one.

You had it perfect in a previous build for MacOS (see below):

https://user-images.githubusercontent.com/86290556/171169365-84fcb553-f34e-41f1-bd90-987c365d024e.mov

If this behaviour can just be replicated for all operating systems, that would be great.

**Comment by Eism** [comment]
Okay, the new solution is ready

@bkunda please recheck 
The problem is that I can't reproduce the bug. My solutions are my guesses. I hope this will be the last one

**Comment by bkunda** [comment]
Ok this is a lot better. 
I still get a tiny lag in Windows, but I am starting to wonder whether this is due to the very slow processing power of my machine.
At any rate, it feels much better in Windows now and it is perfect on my Mac. 
Thanks @Eism! This is actually a really important fix.

**Comment by Tantacrul** [comment]
Wow. This is so much better (tested on MacOS 12)

**Comment by boryskuzmenko** [comment]
@bkunda the issue is reproducible on Win11 and Linux. Are you sure it's OK and we can close this issue?

**Comment by bkunda** [comment]
> 

@boryskuzmenko sorry can you please clarify: are you also still seeing a lag when switching between sub-menus in Windows and Linux? 

If so (and it's not just my slow machine), then we really do need to fix that. 

But maybe I've misunderstood your comment 🙂

**Comment by bkunda** [comment]
> How serious is this lag?
> Can we fix this later? For example, it almost does not reproduce for me.
> This PR fixes a lot of problems with tooltips and menus, and I also optimized the solution from the technical side.

It's pretty minor for me on my Windows machine, although still noticeable. 

Borys's comment made me think he could still reproduce the lag in Windows and Linux, so I'm just hoping he can confirm if this is still the case. 

If other testers  can _almost_ not reproduce it (I.e. it's still there but not a real problem) then perhaps we can merge the present solution because it _is significantly better_, and then raise a new (lower-priority) issue for a future fix to perfect the sub-menus only in those operating systems that remain affected.

**Comment by boryskuzmenko** [comment]
Ok, lets do that. I'll create another issue for that

**Review by RomanPudashkin — APPROVED** [review]

**Comment by boryskuzmenko** [comment]
🟢 **Partly FIXED** 
Tested on macOS 12, Win 11, Ubuntu 20
See the issue https://github.com/musescore/MuseScore/issues/11876 created after closing this PR

**Pull request merged**
