### PR TITLE
CMake: Print Qt version or useful error if it's not installed

### PR DESCRIPTION
**Pull request by shoogle**
Resolves: *No issue in tracker*

Adds a CMake function `fn__required_program()` that can be used to check that a program is installed and present in PATH. If the program is found then it is run with a test argument to check that it works. If it doesn't work, or if it wasn't found, then the build is stopped and a useful error message is displayed on the console. The message can include a URL that points to a webpage where help is available.

Demonstrates use of this function by running `qmake --version` at build time to print the Qt version, or failing with an appropriate error message.

### Qt found and works as expected

QMake and Qt version displayed right after compiler version. (See [line 1005 in Travis build log](https://travis-ci.org/github/musescore/MuseScore/jobs/704938850#L1005-L1006).)
image
Of course the build continues after this.

### Qt not found
image

### Other error
image

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/WorkflowAndGuidelines/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [N/A] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [N/A] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by shoogle** [comment]
## Qt found and works as expected

Output is similar to:

```
QMake version 3.1
Using Qt version 5.9.8 in C:/MuseScore/qt/msvc2017_64/lib
```

And of course the build continues after this. See [AppVeyor build log](https://ci.appveyor.com/project/MuseScore/musescore/builds/33740084#L66).

**Comment by shoogle** [comment]
The help URL is currently set to the [Compilation page](https://musescore.org/en/handbook/developers-handbook/compilation) of the Developer's Handbook, but ideally it would point to a page that's specifically about how to install Qt on each platform. The Linux, MacOS, MSVC and MinGW pages would link to the Qt page rather than copying out those instructions again.

**Comment by Jojo-Schmitz** [comment]
Something went wrong, the GitHub vtests report a failure and the Travis build didn't run at all?

**Comment by shoogle** [comment]
Travis passed but the vtests still fail. I've no idea why that is since I haven't changed any of MuseScore's code.

**Comment by AntonioBL** [comment]
Vtests are completely broken in master since commit f6aa8ff2bde93f6dad0f8d9b29b96e340de5dca4
Apparently, no image is generated, so it is some sort of crash when starting MuseScore in converter mode (or when starting MuseScore at all). I can't directly check at the moment (maybe tomorrow afternoon).
(Note that when the problem will be solved, vtests will probably fail for that build too, since in that case parent commit vtests will not be generated)

**Comment by Jojo-Schmitz** [comment]
Wouldn't this PR also make sense for the 3.x branch?

**Comment by Jojo-Schmitz** [comment]
As far as I can tell it should apply without conflicts

**Comment by Jojo-Schmitz** [comment]
Why has that output `/lib` appended in the success case?

**Comment by shoogle** [comment]
@Jojo-Schmitz, the `--version` option [returns the location of the Qt libraries](https://github.com/qt/qtbase/blob/31048d97ac4ebbacd47e8474887a2bf0c232f2dd/qmake/option.cpp#L221) rather than Qt itself. My guess is that certain Linux distributions like to mess around with the location of Qt and its various components (libraries, plugins, binaries, examples, QML, etc.) so it might not always be the case that all components share a common parent directory, hence they return the [location](https://doc.qt.io/archives/qt-4.8/qlibraryinfo.html#location) of just [one of those components](https://doc.qt.io/archives/qt-4.8/qlibraryinfo.html#LibraryLocation-enum).

**Pull request merged**
