### PR TITLE
Missing gracenote

### PR DESCRIPTION
**Pull request by michaelsiepmann**
I've imported the tune "the clumsy lover" which has an unknown gracenote endari. This is a piobraich gracenote.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
a) Please make is just one commit.
b) Did you sign the [CLA](https://musescore.org/cla)? If so, under which name?
c) Better create an issue on musescore.org first, including the sample BWW (?) file.
   At least clarify the PR- and commit messages to mention that is is a fix for BWW import.

**Comment by Jojo-Schmitz** [comment]
That merge commit doesn't belong there. better use "git pull --rebase upstream master; git push -f` instead

**Comment by cbjeukendrup** [comment]
@michaelsiepmann Is this PR still actual? And could you give some clarification on the questions above?

**Comment by michaelsiepmann** [comment]
Hi,

the problem still exists, MuseScore 4.0.2 crashes with this code:

`Bagpipe Reader:1.0
MIDINoteMappings,(54,56,58,59,61,63,64,66,68,56,58,60,61,63,65,66,68,70,55,57,59,60,62,64,65,67,69)
FrequencyMappings,(370,415,466,494,554,622,659,740,831,415,466,523,554,622,699,740,831,932,392,440,494,523,587,659,699,784,880)
InstrumentMappings,(71,71,45,33,1000,60,70)
GracenoteDurations,(20,40,30,50,100,200,800,1200,250,250,250,500,200)
FontSizes,(90,100,100,80,250)
TuneFormat,(1,0,M,L,500,500,500,500,P,0,0)
TuneTempo,90
"Title",(T,L,0,0,Times New Roman,16,700,0,0,18,0,0,0)
"Type",(Y,C,0,0,Times New Roman,14,400,0,0,18,0,0,0)
"Composer/Arranger",(M,R,0,0,Times New Roman,14,400,0,0,18,0,0,0)
"Footer",(F,R,0,0,Times New Roman,10,400,0,0,18,0,0,0)

& sharpf sharpc 4_4
I! endari E_4 !I
`

endari should create an embellishment starting with an E, Low G, F and finally another Low G.

**Comment by cbjeukendrup** [comment]
Thanks for your comment. One question, in the code you write "E LA F LA", and I guess LA means "Low A", but in your comment you write Low G. What should it be?

And again, have you signed the [CLA](https://musescore.org/cla)? Under which name? This is a prerequisite for us to merge your PR.

**Comment by michaelsiepmann** [comment]
Hi, Low G is correct, the code is wrong.
No, i haven't signed the CLA, can do this later.

**Comment by michaelsiepmann** [comment]
Sorry, mismatched endari and embari.

Endari:
grafik


Embari:
grafik

Endari uses Low A, so the code is correct and my comment is wrong because this was for an embari.

Piobraich is confusing. :-)

**Comment by Jojo-Schmitz** [comment]
So you'd need another code line for Endari? Like this:

    graceMap["embari"] = "E LG F LG";

**Comment by michaelsiepmann** [comment]
I need both

graceMap["endari"] = "E LA F LA";
graceMap["embari"] = "E LG F LG";

**Comment by Jojo-Schmitz** [comment]
Understood. So yet anpother change to this PR is needed.
While at it you should probably rebase it too

**Comment by michaelsiepmann** [comment]
You can also reject this merge-request and insert the two lines on your own,

**Comment by Jojo-Schmitz** [comment]
Why?

**Comment by michaelsiepmann** [comment]
Sorry, I didn't realize, I would close this task. Now, it is obvious, but I didn't thought about it.
You've added the two lines on your own and for me this was finished.
Musescore has changed a lot the last year, so I'd like to restart my fork. This closes the request.

Should I create a new one?

16.03.2023 20:34:44 Joachim Schmitz ***@***.***>:

**Comment by michaelsiepmann** [comment]
See pull-request #16943

**Pull request closed without merging**
