### PR TITLE
Commits rebased from 3.x

### PR DESCRIPTION
**Pull request by Howard-C**
From #5773, #6122, #6240, #6265.

### CODE REVIEW

**Comment by Howard-C** [comment]
Code style check passed (the existing errors are not from this PR)

**Comment by igorkorsukov** [comment]
> Code style check passed (the existing errors are not from this PR)

Try to rebase, I've just fixed a number of issues.

**Comment by Howard-C** [comment]
@igorkorsukov There's still one codestyle inconsistency you missed :-) I added it to this PR.

**Comment by igorkorsukov** [comment]
> @igorkorsukov There's still one codestyle inconsistency you missed :-) I added it to this PR.

Thanks :)

**Comment by Howard-C** [comment]
Vtest failures are intended

**Pull request merged**
