### PR TITLE
Fix #18469: Rename LICENSE.GPL -> LICENSE.txt so Github detects it

### LINKED ISSUE #18469: [GitHub] Use proper license filename
### Issue type

Other type of issue

### Bug description

The current license filename is not detected correctly by GitHub, even if the license is GPLv3.0.
For GitHub to detect it, the license filename must be renamed to `LICENSE`, `LICENSE.md`, or `LICENSE.txt`.

### Steps to reproduce

You can see this at the right top of the repository (screenshot below). You'll see that GitHub found unknown licenses.

### Screenshots/Screen recordings

image

### MuseScore Version

I don't think this applies here.

### Regression

I don't know

### Operating system

Microsoft Windows 10.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chunga2020**
Resolves: #18469

Due to the `.GPL` extension on the license file, GitHub wasn't properly detecting it, considering the code to be under an "Unknown" license.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by cbjeukendrup — APPROVED** [review]

**Comment by Eism** [comment]
Not sure that the problem is in .GPL.
For example, in my fork, the license with .GPL is determined correctly.

I think we should remove the license and then add it again according to this article [Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by shoogle** [comment]
I think it's probably because we have our own text in the license file above the GPL text. I'm not sure there's much we can do about that.

**Comment by chunga2020** [comment]
> Not sure that the problem is in .GPL. For example, in my fork, the license with .GPL is determined correctly. https://github.com/Eism/MuseScore
> 
> I think we should remove the license and then add it again according to this article [Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

@Eism I just downloaded your repo's version and `diff`ed it against my branch's.  Definitely the same.  Interesting

> I think it's probably because we have our own text in the license file above the GPL text. I'm not sure there's much we can do about that.

@shoogle Would [this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license) be a viable solution?  Are there specific reasons we cannot, as the link suggests, offload the details to, say, the README?

**Comment by Eism** [comment]
Merged the PR and I see that the license is displayed correctly in the repository

**Pull request merged**
