### PR TITLE
[MU4] Fix #314612: Erroneous duplicate check (actually 4 times) of an identical condition

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: https://musescore.org/en/node/314612

@psmokotnin : please review

### CODE REVIEW

**Comment by RobFog** [comment]
Errnous → Erronous

**Comment by Jojo-Schmitz** [comment]
I buy the first, but the second

**Review by psmokotnin — APPROVED** [review]

**Comment by psmokotnin** [comment]
@Jojo-Schmitz Thanks for the fix

**Comment by Jojo-Schmitz** [comment]
Guess we'd rather have to thank [maddin200](https://musescore.org/en/user/1622771) for finding this

**Pull request merged**
