### PR TITLE
[MU4] Set maximum flick velocity to 1500 for all listviews in the project

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #10085

### CODE REVIEW

**Review by vpereverzev — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
How about creating a reusable StyledFlickable component that has the correct value for all properties that we use every time? Like `maximumFlickVelocity`, `boundsBehaviour`, `Scrollbar.vertical`, `clip`, etc. 
I think that would make it easier to add new Flickables without forgetting properties, and ensure that all Flickables stay consistent.

**Comment by Eism** [comment]
@cbjeukendrup 
We can't just create a new Flickable component and use it for all views in the project because views are inherited from Flickable.

Ok, we can create a styled component for each view (StyledListView, StyledGridView, StyledFlickable, etc).
And it is better than it looks now

**Comment by cbjeukendrup** [comment]
Ah, of course, that was the catch... Thanks!

**Comment by Eism** [comment]
@cbjeukendrup fixed

**Comment by llui85** [comment]
@Eism Would it be possible to add an setting option to disable the "flick"/smooth scrolling behaviour entirely as well?

**Pull request merged**
