### PR TITLE
fix #95951 use signed chars for BeamMetric to fix ARM type limit issue causing long stems

### PR DESCRIPTION
**Pull request by ericfont**

### CODE REVIEW

**Comment by ericfont** [comment]
jojo, it works both when 650 are signed and regular char.  Should I go make those signed?

**Comment by ericfont** [comment]
I did try both ways for 650...I would think you are right that need to explicilty be signed, although I'm a little perplexed why it doesn't need to be in 650.  I do think making those signed are safer...so let me update PR.

**Comment by ericfont** [comment]
I'm an iditot...did something wrong with rebase...

**Comment by Jojo-Schmitz** [comment]
Yes, I think the line 650 change is for clarity and consistency only. But that is enough of a reason for me ;-)

**Comment by ericfont** [comment]
ok...I've added the signed to line 650 and re-pushed, so should be good now.

**Pull request merged**
