### PR TITLE
Fix #270433: Crash when pasting a note with an articulation if the final note is split between two measures

### PR DESCRIPTION
**Pull request by lyzl**
Issue Reference:
https://musescore.org/en/node/270433#comment-825767

Function Chord::removeMarkings should not delete the Vector but just delete Markings inside. That's the reason caused null reference and application crashed
Old pull request from here #3573

### CODE REVIEW

**Comment by ericfont** [comment]
Usually it is good to provide a mtest, which is a little function which runs command on a simple test score to try to cause the bug to happen, and then compares with a correct score.  Look in mtest directory for examples.

**Comment by lyzl** [comment]
@ericfont  Thanks very much! I will do a mtest in next issue. And the second problem...yeah.. it very strange. It has made by an ”unauthoried“ myself. And the commits can't be squashed. I have no idea how to fix it. Just on the way to solve it.

**Comment by ericfont** [comment]
If you can't merge the 'unauthoried", just create a new pull request and close this one.  So might just want to make a new branch starting from current master so have a clean starting slate.

regarding mtest, it is better to have the mtest in the same commit as the fix too.

**Comment by lyzl** [comment]
@ericfont I think creating a new pull request is better.. Thanks for replying. I will finish it in one or two days.

**Comment by lasconic** [comment]
I close this one then. 

Are you really really sure that we shouldn't delete the markings ? How will they be destroyed? 
Maybe we should clear the vectors as well since qDeleteAll doesn't clear it. See https://doc.qt.io/qt-5/qtalgorithms.html#qDeleteAll

**Pull request closed without merging**
