### PR TITLE
get rid of special casing the z-order of ledger lines and images

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
mtest fix to follow

**Comment by Jojo-Schmitz** [comment]
Outch, this are far more mtest failures than I expected, and very different too.

**Comment by Jojo-Schmitz** [comment]
Now with fixes for the tst_scripting mtest I was expecting to be needed

**Comment by Jojo-Schmitz** [comment]
I wonder whther Change just one of the two elemtets works without causing all These failures. And I have the feeling that one element, if any, got to be `Image`.

**Comment by lasconic** [comment]
All the failures are due to ElementName not being in sync with the element type enum  I believe.

**Comment by Jojo-Schmitz** [comment]
Outch, what a stupid mistake of mine. Let's see whether this is better then...

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/28041 and https://musescore.org/en/node/120466, which lead to the introduction if these special casing

**Pull request merged**
