### PR TITLE
Updated version to 4.00

### PR DESCRIPTION
**Pull request by igorkorsukov**
Last 3.02 builds
* Linux - https://ftp.osuosl.org/pub/musescore-nightlies/linux/4x/testing/MuseScore_MU4_1053141391_last302.zip
* Windows - https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/testing/MuseScore_MU4_1053140762_win_last302.zip
* MacOS - https://ftp.osuosl.org/pub/musescore-nightlies/macos/4x/testing/MuseScore_MU4_1053140094_mac_last302.zip

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I guess before this gets merged we'd need to save the last development build before it as a compatibility build?

**Comment by igorkorsukov** [comment]
> I guess before this gets merged we'd need to save the last development build before it as a compatibility build?

Tell me what do you mean? Where to save?

**Comment by Jojo-Schmitz** [comment]
On the server where the development builds are stored, OSUOSL, make sure it doesn't get 'rolled out' after x futher builds.

**Comment by igorkorsukov** [comment]
saved builds
Last 3.02 builds
* Linux - https://ftp.osuosl.org/pub/musescore-nightlies/linux/4x/testing/MuseScore_MU4_1053141391_last302.zip
* Windows - https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/testing/MuseScore_MU4_1053140762_win_last302.zip
* MacOS - https://ftp.osuosl.org/pub/musescore-nightlies/macos/4x/testing/MuseScore_MU4_1053140094_mac_last302.zip

**Comment by Jojo-Schmitz** [comment]
Thanks

**Review by vpereverzev — APPROVED** [review]

**Pull request merged**
