### PR TITLE
expose class BarLine with property barLineType to scripting

### PR DESCRIPTION
**Pull request by heuchi**
This exposes BarLine and the BarLineType enum the same way as AccidentalType is exposed (using a QmlBarLineType enum).
While trying to use the barLineType property, I noticed that class BarLine was not yet registered in mscore.cpp.

Once again needed for my courtesy accidental plugin.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
We can't use Ms::BarLineType for this?

**Comment by heuchi** [comment]
Unfortunately we can't.
See <a href="http://dev-list.musescore.org/Enum-s-and-plug-ins-td7578860.html">this thread</a> from the developer mailing list.
There has been some discussion about this issue already, but since Werner has recently moved some enums (AccidentalType, AccidentalRole) out of class Accidental (which was a rather large <a href="https://github.com/musescore/MuseScore/commit/e9222d1b45fea28f322b7e1a36bf58c559698bb2">commit</a>), I followed the model he used then.

**Comment by heuchi** [comment]
As requested by Werner I added a test in tst_scripting if BarLineType and QmlBarLineType match.
I hope this is the place to do this.

**Comment by heuchi** [comment]
@lasconic any chance this is going to be included in v2.0.1?

**Comment by lasconic** [comment]
So far I didn't merge anything regarding the new way to expose enums in 2.0.1 or the new scripting tests. So no, unlikely as it is right now.

**Comment by Jojo-Schmitz** [comment]
It also needs a rebase now...

**Pull request closed without merging**
