### PR TITLE
Enable AddressSanitizer for the tests

### PR DESCRIPTION
**Pull request by AntonioBL**

### CODE REVIEW

**Comment by AntonioBL** [comment]
Of course the tests will fail because there are open memory address bugs in current code.

**Comment by AntonioBL** [comment]
I enabled only "make installdebug" since it is already calling "make debug". By not calling "make debug" twice we get ~5 min of compilation time.

**Comment by AntonioBL** [comment]
I updated also PR #4001

**Comment by dmitrio95** [comment]
As #4278 got merged, maybe this PR can also be applied?
@anatoly-os could you please restart the Travis build?

**Comment by AntonioBL** [comment]
It now reports a memory access error for mtest/libmscore/clef_courtesy/tst_clef_courtesy.cpp at line 141 [inside clef_courtesy02()]. I cannot obtain the same report (i.e. everything is fine) when performing the actions of the test via MuseScore GUI, so it could be a problem of dropdata or clef initialization inside the test.

**Comment by AntonioBL** [comment]
And indeed, here:
https://github.com/musescore/MuseScore/blob/d4443a3183c4e8b361bb207c31dfddf1e369a8c7/mtest/libmscore/clef_courtesy/tst_clef_courtesy.cpp#L140
there is a typo: `dropData.element = clef;` should read instead `dropData.dropElement = clef;`

**Comment by Jojo-Schmitz** [comment]
I'd add the fix from #4334  here (too), just to prove that it plugs a memory hole?

**Comment by AntonioBL** [comment]
Ok. If everything went ok, I should have rebased this PR onto https://github.com/musescore/MuseScore/pull/4334
This should not screw the commit history.

**Comment by Jojo-Schmitz** [comment]
You may want to join us on [Telegram](https://t.me/musescoreeditorchat)

**Pull request merged**
