### PR TITLE
Implement "migration" for 4.0 scores

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #18085 

Just show a dialog
Scherm­afbeelding 2023-06-21 om 19 12 03

TODO:
- Use a different text for 4.0 scores than for 3.6 scores
- Use a different video link for _

### CODE REVIEW

**Comment by oktophonie** [comment]
I'd not even be that specific: just "Please note that the appearance of your score may change slightly due to engraving improvements made in this version" (or something like that; this is really a question for @bkunda). One might consider linking to https://musescore.org/en/node/351407 (work in progress) which will describe everything.

**Comment by Tantacrul** [comment]
I'm of the opinion that we do t show this.

The consensus we reached the last time we spoke was that we should only show these kinds of dialogs when a really significant change is made.

Also: the checkbox is in a weird place and the dialog looks slightly weird and disordered.

**Comment by cbjeukendrup** [comment]
FWIW, I think that an important purpose of this dialog, is to make the user aware that they are opening the file in a new version of MuseScore and after doing that it cannot be opened in an old version anymore. (This will become even more important when we _completely_ block opening scores from newer versions, see #18083.)

Of course, the dialog does not (yet) say this explicitly, but it could certainly help creating awareness. 

And it would also explain the behaviour that is described in https://github.com/musescore/MuseScore/issues/18085 (namely, when opening a file from an old version in a new version, this is treated as "import", so when you try to save you'll have to select a new location).

I don't really have a strong opinion about all of this, but just wanted to add these points to the discussion.

**Comment by Tantacrul** [comment]
Similar dialogs are not needed in professional software generally. If you try opening a new score in an old version, you get told it's incompatible and then that's it.

I'm not saying the dialog serves no purpose. I'm saying it serves a niche purpose and therefore should not have to be seen by everybody. Moreover, this is how most software generally works. Scores created in new versions cannot be opened in old versions.

**Comment by cbjeukendrup** [comment]
Whatever we decide, I think it might make sense to match our decision about whether the to show the dialog with our decision about whether to "treat old scores as import", so:
- **Either**: Show that dialog when opening the score AND treat opening old files as import, so when the user presses Ctrl+S, they will get the save location picker dialog, forcing them to save the file in a new location (although the user could just decide to select the location of the old file and overwrite it anyway, but at least consciously)
- **Or**: Don't show a dialog, AND don't treat old files as import, so when the user presses Ctrl+S, the file will just be saved and the old file is overwritten

I propose the following compromise: 
- when the user opens a score from a version where the difference with the current version is "big enough", we do dialog+"treat as import"
- otherwise we do nothing and ignore the fact that it the file was from an older version. 

The only remaining question is: _define "big enough'_. Rather than trying to figure out some universal logic with version numbers, let's keep it simple and hard-code the rule every time we make a release. So for 4.1, the rule is "everything older than 4.0.0 is old enough".

Everyone happy?

(Alternative proposal: get rid of the whole "treat as import" idea, and show a dialog only when we want to. For most users, this would be fine anyway, but (as with everything) there will also be people who will hate it. And in some cases, that even makes some sense: suppose you have a score that looks good in one version, but looks bad in a new version. Normally, you'll just modify the score to look good in the new version, but if you don't have time to do that and you need to print the score real soon, then you'll want to temporarily go back to the old MuseScore version. If the new MuseScore has overwritten the old file so you can't open it in the old version anymore, then you have a problem, but if the new MuseScore had forced you to save the upgraded file somewhere else, then you still have your old file for the old MuseScore.
But: should _we_ take on the burden of taking care of this? Or should we just leave this as the responsibility or the user, like other apps do?)

**Comment by Tantacrul** [comment]
I don't think we should show any dialog and the experience of opening a score should feel completely unchanged. 

I certainly don't think we should change the save flow either. It would be a nightmare for cloud scores in particular.

When we make a seriously large change, a-la 3.6 or 4.0, we potentially show a dialog. Nothing is 4.1 really warrants this.

**Comment by cbjeukendrup** [comment]
About the save flow: good point about cloud scores indeed... 

But currently, it _is_ already the case that when you open an old file and press Ctrl+S you get the "Save as" dialog. 
So you are proposing to change that, and Ctrl+S will ALWAYS just save the file and override the old file, regardless of how old the file was (so, in 4.1, files from 4.1, 4.0, 3.0, whatever, will all get the same treatment when saving with Ctrl+S). Is that right?
(I'd be completely happy with that, I only want to check that I understand what you're saying.)

**Comment by Jojo-Schmitz** [comment]
Seems all(?) the vtest fails are about the end barline, and seems the change is for the better

**Comment by bkunda** [comment]
Ok, there's been a lot of discussion here and I can see a decision has to be made one way or the other.

This solution attempts first of all to solve the problem identified in #18085. I think the problem identified in this issue is not actually that significant from a UX POV: yes, the user is prompted with a dialog to save their score, but only if they try to close the score without interacting with it first. The moment they interact with the score, behaviour is exactly as one would expect it to be when saving and/or closing. 

Further, the solution in this PR doesn't actually solve this problem, nor the other mentioned (related) problem: that of advising the user that their score will, if saved, no longer be openable in an earlier version. Informing users that their aspects of score will change won't necessarily help them to understand that a) their score is being treated as an import, and b) that they won't be able to open it in an earlier version if they hit save. They either have to _infer_ this information for themselves (which only a small number of users will be able to do), or _experience_ it by actually attempting to open the file in an earlier version (which, again, is not going to be a large number of users; most people who have upgraded to 4.1 will not be simultaneously running an older version).  

On reflection, this dialog simply introduces an extra layer of friction when opening a score, which is desirable if the changes to be made to the that score are very significant (and destructive), which for 4.1 won't necessarily be the case (unlike the move to 4.0).  

So I would suggest that:

- We don't need to worry about the user being prompted to save their score if they open it and wish to close it straight away: the friction here is fairly trivial, and it'll only happen once per score. Most likely, the user _will_ begin interacting with their score once they've opened it, and so should expect to be prompted to then save it before closing (if they haven't already saved it first)
- The fact that the score is being treated as an import when opening in a new version is, as @Tantacrul has said, consistent with how software generally works, so I don't think we need to concern ourselves too much with this either. 

And to be consistent with our general design approach, let's:

- Avoid introducing friction unless it is absolutely necessary
- In deciding to do something (or, in this case, not to do something), remain attentive to user feedback; where a significant number of people report confusing behaviour, then we attempt to deal with it.

I vote we park this for now and re-address it later if there is significant concern from users.

**Comment by bkunda** [comment]
Closing as not planned for now

**Pull request closed without merging**
