### PR TITLE
Fix duplicate system objects in parts

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #15371

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

**Comment by vpereverzev** [comment]
@DmitryArefiev check this one please

**Comment by vpereverzev** [comment]
@mike-spa please attach profiler's output before/after changes

**Comment by DmitryArefiev** [comment]
Tested #15371 on Win10, Mac12, LinuxMint 22.04 - **FIXED**

**Comment by mike-spa** [comment]
@vpereverzev as far as I can tell the difference is not measurable.

MASTER:
`Excerpt::cloneStaff2`     tot. 72 ms
`cloneMeasure`              tot. 8 ms

THIS PR:
`Excerpt::cloneStaff2`     tot. 72 ms
`cloneMeasure`              tot. 8 ms

Tested by extracting a part score from a large file.

**Review by vpereverzev — APPROVED** [review]

**Pull request merged**
