### PR TITLE
Update Bravura to 1.204

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Would we also need to change libmscore/sym.{cpp,h} for the qlyphs added in SMuFL 1.20?

### CODE REVIEW

**Comment by lasconic** [comment]
Yes. I have a script for that. The other fonts should be fine right?

**Comment by Jojo-Schmitz** [comment]
The other fonts are unchanged, so should be fine, shouldn't they?

**Comment by lasconic** [comment]
I didn't read the changelog but if there are no change of codepoints as promised, it should be ok.

**Comment by Jojo-Schmitz** [comment]
Hmm, as per metadata.json some code points have changed in Bravura, but I guess that's what that metadata.json is good for?

**Comment by dspreadbury** [comment]
A few of the code points in the optional glyphs range will have changed (i.e. U+F400–U+F8FF) as stylistic alternates etc. have been added (and these are not guaranteed to be stable between releases), but none in the primary glyphs range (U+E000–U+F3FF).

**Comment by Jojo-Schmitz** [comment]
Thanks, Daniel!

**Comment by lasconic** [comment]
SMuFL 1.20 is still a draft, so I guess Bravura may be updated one more time before the release.  I have a PR ready for the addition of the new symbols. Let's wait for SMuFL 1.20 to be released before merging both requests.

**Comment by lasconic** [comment]
See PR #2589

**Comment by lasconic** [comment]
And I changed my mind :) Let's merge and see if we encounter problems.

**Pull request merged**
