### PR TITLE
fix #62341: transpose chords on staff transposition change

### PR DESCRIPTION
**Pull request by MarcSabatella**
This fixes the issue at hand: chords will now transpose correctly when changing the transposition of a staff.  Chords in linked staves/parts are transposed as well.  However, there is currently a pretty serious issue with changing transposition for a staff if linked parts exist for it: https://musescore.org/en/node/62416.  Depending on how that issue is resolved, we might need to revisit how I handle parts here.  We may also need to revisit how key signatures are handled here.  It probably doesn't make sense to merge this PR until we address the parts issue, but I decided to submit it anyhow since it is working as well as it can, so now we'll at least have a record of the code.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
rebase needed ;-)

**Comment by MarcSabatella** [comment]
I have rebased and tested this with the other change that overlapped - my PR #2228 that was merged recently.  The functionality provided by the current PR does work as advertised.  However, the same undo bug that causes instrument change to not be abe to update key signatures - https://musescore.org/en/node/78591 - also causes it to not be able to update chord symbols, since they both rely on the ability to determine the original transposition at a point when that information has already been lost.

Which is to say, in my opinion, this PR is mergeable as is, but we really need to find a fix for that undo bug.  I think any good fix for that bug with respect to undo will automatically fix it for chord symbol transposition as well.  We also need to decide how changes to staff properties should affect linked parts as per https://musescore.org/en/node/62416, but this too is a separate issue.

**Comment by lasconic** [comment]
@wschweer put the undo bug on his todo list.

**Comment by MarcSabatella** [comment]
Investigating the test failure....

**Comment by MarcSabatella** [comment]
The tests did their job well, catching a mistake I made when manually merging to rebase.  FWIW, it didn't actually affect the behavior of this case at hand, but the probem would have become apparent as soon as the aforemewntioned undo bug is fixed.  I've now address the problem so all should be well.

**Comment by MarcSabatella** [comment]
This is on the short list of PR's of mine I'd like to see fixed for 2.0.3.  It's not *crucial* and as mentioned there are still problems with linked parts, but even so, I think it is impoortant to get this common use case working.  The use case I have in mind is this: user creates a lead sheet, then uses Change Instrument to change to alto sax to produce an "Eb" version of the lead sheet, and is surprised to find the notes and key transposed but not the chords.  The workaround is to use Notes / Transpose, so again, it's not *crucial* we fix this for 2.0.3, but I just wanted to advocate for it.

**Pull request merged**
