### PR TITLE
Fix preview in Staff/Part Properties > Advanced

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #9106 

Now, the scaling of the previews in Staff/Part Properties > Advanced and in the Time Sig Properties dialog should be similar to MuseScore 3. This would need to be tested with various kinds of platforms and monitors.

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #9106 on Win10 (FullHD), Mac12 (Retina), LinuxMint 20.2 (FullHD)

It looks small on Win and Linux with FullHD displays:
Capture

@bkunda Can you check this on your 4k display please?

**Comment by cbjeukendrup** [comment]
It seems there is a broader issue with scaling/zoom at the moment in MU4. For example, when zooming to 100%, the size of the notation does not correspond with the size of a physical sheet of paper. This was the case in MU3, and I also fixed this once for MU4, but apparently it is broken again and I haven't figured out why.

**Comment by bkunda** [comment]
> @bkunda Can you check this on your 4k display please?

@DmitryArefiev It's mostly working on my 4k display. Preview staff renders as expected at my screen's recommended monitor scaling (150%). 

The noteheads do some quirky things when you change the scaling. For instance, setting it down to 100% then returning back to 150% seems to leave the noteheads looking very small and disconnected from their stems. But this is rectified by closing and reopening the dialog.

**Comment by DmitryArefiev** [comment]
> It seems there is a broader issue with scaling/zoom at the moment in MU4. For example, when zooming to 100%, the size of the notation does not correspond with the size of a physical sheet of paper. This was the case in MU3, and I also fixed this once for MU4, but apparently it is broken again and I haven't figured out why.

@cbjeukendrup Maybe do you want a separate issue and merge the current PR?

**Comment by cbjeukendrup** [comment]
@DmitryArefiev That seems a good idea. Let's log a general issue about scaling in notation views (because, as I said, in the main notation view, the scaling corresponding to 100% zoom is also not correct).

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Yes, logged #10686 

Thanks

**Pull request merged**
