### PR TITLE
Improve AppImages including fix 104106 use system font settings

### PR DESCRIPTION
**Pull request by shoogle**
More coming so don't merge yet.

### CODE REVIEW

**Comment by lasconic** [comment]
Anything more?

**Comment by shoogle** [comment]
That was the most important thing, but hoping to add another thing in the next hour or so.

**Comment by shoogle** [comment]
Just need to run a quick test on the AppImage once it has built, and then this should be ready to merge.

**Comment by shoogle** [comment]
Tests successful. Looks good to merge.

**Pull request merged**
