### PR TITLE
fixed #18433: App doesn't auto restart properly after Revert to factory settings (Windows only)

### LINKED ISSUE #18433: 4.1 Regression: App doesn't auto restart properly after Revert to factory settings (Windows only)
### Issue type

Choose option...

### Bug description

_No response_

### Steps to reproduce

https://github.com/musescore/MuseScore/assets/90187801/627499f8-7063-439b-a854-913aa4c0fcfc

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.1 nightly master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #18433

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
It was on purpose that there is no splash screen when the user starts a new instance manually. That would be reverted by this PR. So we need a way to know whether the app was launched manually (then we show no splash screen unless it was the first instance) or automatically, by doing a factory reset.

**Comment by Eism** [comment]
@cbjeukendrup 
You contradict what you wrote in this ЗК https://github.com/musescore/MuseScore/pull/18130
> When the user just manually opens a new instance*, just show the normal splash screen

Or perhaps I misunderstood what you meant.

**Comment by DmitryArefiev** [comment]
As I understand, the current PR reverts this result from #18130:

> On @bkunda's request, trying out how it would be if there is no splash screen at all when launching a second instance manually.

@bkunda @cbjeukendrup But maybe we can leave with that for 4.1? (at least it fixes 'Loading new score' issue)
This comparison of **latest 4.1 build** and the **current PR**, which fixes more important bug #18433:




https://github.com/musescore/MuseScore/assets/90187801/59d6134b-dd79-4a68-9191-2a431d7db5ae

**Comment by cbjeukendrup** [comment]
> @cbjeukendrup You contradict what you wrote in this ЗК #18130
> 
> > When the user just manually opens a new instance*, just show the normal splash screen
> 
> Or perhaps I misunderstood what you meant.

Ah, I see; it was decided later to change that, but I hadn't updated the initial PR description.

**Comment by bkunda** [comment]
So I can see this re-instates the splash screen that @cbjeukendrup removed in https://github.com/musescore/MuseScore/pull/18130. Priority for 4.1 should be dealing with the crash that the present PR fixes. We can deal with the matter of the splash screen later. 

@RomanPudashkin over to you if you think this is good to merge for 4.1!

**Pull request merged**
