### PR TITLE
[MU4] Fixed instruments names in the instruments panel

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/pull/8432#pullrequestreview-702245624

### CODE REVIEW

**Comment by RomanPudashkin** [comment]
@shoogle please, check this

**Review by shoogle — CHANGES_REQUESTED** [review]
@RomanPudashkin, almost! We'd like the part name to include information in parentheses that is displayed in the New Score Wizard, such as for "Horn (bass clef)", "Tenor Lute (5-course)", etc.

I suspect you will need to create a new function `formatPartName` that takes the output of [formatSelectedInstrumentTitle](https://github.com/musescore/MuseScore/blob/3c6ad5f14f82834abf302410dc05bcb3a98d77fb/src/instrumentsscene/view/instrumentlistmodel.cpp#L40-L53) and then adds a number on the end if necessary like in [formatInstrumentName](https://github.com/musescore/MuseScore/blob/3c6ad5f14f82834abf302410dc05bcb3a98d77fb/src/notation/internal/notationparts.cpp#L43-L52). The number should match the number in the score.

### Desired result

image


image

image

image

**Comment by RomanPudashkin** [comment]
@shoogle I've updated my solution. Can you check it again, please?

**Review by shoogle — APPROVED** [review]
@RomanPudashkin, perfect, thanks!

**Review by Eism — APPROVED** [review]

**Pull request merged**
