### PR TITLE
fix #9103: Replaced 'To Coda' with 'Al Coda'.

### PR DESCRIPTION
**Pull request by awelch83**
The first time I've been able to contribute and fix something. Though the issue was simple, I'm still proud! When this pull request is merged, I am going to print it, and frame it. :-)

### CODE REVIEW

**Comment by awelch83** [comment]
I don't know why this keeps failing. Am I missing something?

**Comment by MarcSabatella** [comment]
Weird, unless you are pressing "Close and comment" rather than just "Comment", I don't know why that would be happening.

I love seeing this enthusiasm, and I hate to come in and temper it a little, but I have to ask: are you *sure* about this?  I don't think I have ever seen "Al Coda" in a piece of published music, at least not in the English-speaking world.  It's using just the coda sign itelf, or the phrase "To Coda" or the word "To" follow by the coda sign.  Even if it makes logical sense to use Italian here for consistency, it just isn't done out of Italy in this particular  context, in my experience.  Furthermore, even if you wanted it to be in Italian, I don't think "al Coda" would be grammatically correct, although I'd love to hear from a native speaker like @mgavioli .  The "al" in "D.S. al Coda" is usually translated "unti" in this context; it is not the direction to "jump to" the coda.  The correct (but seldom used in published music) phrase for that, according to both the Harvard Dictionary of Music and Elaine Gould in "Behind Bars", is "e poi la Coda".

**Comment by awelch83** [comment]
@MarcSabatella - You're right, I now see. No worries though, in working on this fix, I became more familiar with MuseScore's code, and have learned a few things about debugging. So as a learning experience, for me, this was valuable. Back to the issue tracker I go :)

**Comment by mgavioli** [comment]
Well, for what is worth, _al Coda_ is not grammatical in Italian, the correct wording being _alla Coda_ (feminine noun => feminine preposition), whatever meaning is intended for _al_.

About meaning: I do not understand "unti" as a translation of _al_: "until"? "unto"? There is little doubt that the Italian preposition _a_ (_a_ + _il_ => _al_ (masc.), _a_ + _la_ => _alla_ (fem.) ) means "to" and implies to jump to the coda.

The usual scenario I can figure out (but my experience is mainly with pre-mid-XVIII c, scores) is with a tripartite form, made by a
- {Segno}_ritornello_ {Fine},
- _sviluppo_ {D.S. al Fine}
- {Coda} _coda_

whose intended playing pattern is _ritornello_, _sviluppo_, _ritornello_ again **and then** _coda_ to conclude. This would be precisely and correctly expressed by the wording _D. S. al Fine e poi la Coda_, which is perfectly grammatical in Italian (_e poi_ = "**and then**").

If may be possible that, outside Italy, it had come into usage to shorten the long phrasing _D. S. al Fine e poi la Coda_ into _D. S. al Coda_, but it looks and sound quite funny (and not really understandable) to Italian ears...

**Pull request closed without merging**
