### PR TITLE
fix #105256: allow searching for numerical rehearsal marks

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
also disallow measure number 0 (which by definition doesn't exist anyway) and allow negative page numbers (which are possible, via page number offset).

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Why disallow measure 0?  Isn't that how a pickup measure would normally be numbered?

**Comment by Jojo-Schmitz** [comment]
Because it doesn't work that way, MuseScore internally numbers all measures starting from one and incrementing by one, measure to measure, regardless of pick up measures, manual measure number offset overrides, manual "don't count' or section breaks. Same as the sanity check and the status bar.
And so a measure 0 simply isn't possible in these terms.

**Comment by Jojo-Schmitz** [comment]
an additional method to search for 'logical' measure numbers might be helpful though.

**Comment by MarcSabatella** [comment]
Ah yes.  And indeed, while it's basically good that the measure numbers are absolute, it is a common source of confusion, like when we report corrupt measures in a score and they seem off by one.  So worth thinking about further at some point, in general.

**Pull request merged**
