### PR TITLE
Fix lyrics odd-even style bug

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #23846 

Additionally, this PR also reintroduces the use of `lineSpacing()` for calculating the line height between the different lyrics verses. The metric currently being used was `lineHeight()`, which I'd recently introduced as a way of getting around #22189. Now that that issue has been fixed, `lineSpacing()` is the correct metric to use. This will show up in the vtests as a slight increase in vertical distance between the verses.

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
Especially after this fix, I don't seem to see much benefit in the `m_even` member of Lyrics. What do you think about removing it?

**Comment by Jojo-Schmitz** [comment]
See also #23506

**Comment by mike-spa** [comment]
> Especially after this fix, I don't seem to see much benefit in the `m_even` member of Lyrics. What do you think about removing it?

Oh yes thanks. That was an absolute horror, happy to get rid of it

**Comment by mike-spa** [comment]
> See also #23506, I believe the fix from there is also needed

No it isn't

**Review by cbjeukendrup — APPROVED** [review]

**Pull request merged**
