### PR TITLE
fix #286900 MIDI input menu has no None option

### PR DESCRIPTION
**Pull request by AntonioBL**

### CODE REVIEW

**Comment by AntonioBL** [comment]
This PR tries to symmetrize the behavior of midi input and output, so that midi input can be disabled while still having midi output.
One downside is that this change makes disabled midi input as the default, so users plugging-in a midi interface have to select it in the preference dialog (and then restart the midi interface) before being able to use it for note input. The current behavior instead gets the default midi input device by default.
In case, I think this PR has to be thoroughly tested: I added also the deletion of the timer which was left unhanded, and the closing of all output streams when the midi driver is halted (so that when restarting the freed midi device is still recognized by MuseScore; at the moment after midi-off, midi-on instructions it is no more recognized and the midi driver is not initialized).

**Comment by AntonioBL** [comment]
I updated the PR so that the default behavior is the same as the current one: a midi input device is automatically grabbed unless it is explicitly set to none in the preferences.
If one choose "none midi input device" (i.e. "empty" field in the dropdown menu) and at the end of the session closes MuseScore, then:
- if the following time MuseScore is opened with a midi device present, this preference (i.e. no input midi device) is remembered;
-if the following time MuseScore is opened without a midi device, then the preferences are reset to their default value, and the next time MuseScore is openend with a midi device it is automatically grabbed and a "none midi input" in that case must be again manually selected.

I think thorough tests are needed to see if I managed to cover all possible cases.

**Comment by AntonioBL** [comment]
By request, I am also adding some code lines which should prevent the automatic grabbing of the same MIDI device for both input and output.

As before, real-life tests with actual MIDI devices are needed.

**Comment by AntonioBL** [comment]
From the tests (see the related issue), the "none" preference does not survive at the third launch of the application. I will further work on this.
So this is at the moment still a work in progress, please do not merge yet.

**Comment by AntonioBL** [comment]
The current implementation mainly works.
It probably fails (i.e. it loads the wrong preference) in a complex corner case (see discussion in the related issue).
A remaining doubt is whether or not the "no-device" string, at the moment a " " string should be an explicit and translatable "no device"/"empty" (or similar wording) string.

**Comment by Jojo-Schmitz** [comment]
Rebase needed.
Maybe rebase to 3.x (first)?

**Comment by RomanPudashkin** [comment]
3.x is closed for any changes

**Pull request closed without merging**
