### PR TITLE
[MU3] Fix #307147: Extend Soprano Recorder professional range down to B

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
resolves https://musescore.org/en/node/307147

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Travis build has finished and successfully, no idea what it is being reported as in progress here

**Comment by Spire42** [comment]
The original feature request mentioned that the same problem exists for all types of recorders, not just soprano:

*<cite>On the soprano recorder, low Bs are very much possible and can be produced by covering all the holes and the one at the end by half. All the other denominations can also go an extra semitone lower than MuseScore says by doing this.</cite>*

Might as well do them all in a single PR, right?

(Also, there is no issue in the issue tracker that's being resolved here; just a thread in “Feature request” forum. Is this OK to do?)

**Comment by Jojo-Schmitz** [comment]
It is OK to me ;-) 
If there's an issue with other recorders, fine, I can add it to this PR, but I don't read this from that forum topic?

**Comment by Spire42** [comment]
It's in the subject line of the feature request thread (“recorder”, not “soprano recorder”), and also in the text that I quoted above:

> All the other denominations can also go an extra semitone lower than MuseScore says by doing this.

**Comment by Jojo-Schmitz** [comment]
I read this differently, and other recorders do go a semitone lower in professional settings

**Comment by Jojo-Schmitz** [comment]
Let's close this, before it accidentally get merged ;-)

**Comment by Jojo-Schmitz** [comment]
Let's close this, before it accidentally get merged ;-)

**Pull request closed without merging**
