### PR TITLE
Added shortcut "N" on "Note-input" tooltip.

### PR DESCRIPTION
**Pull request by pratyaksh1610**
Resolves: #16342 

Added the shortcut "N" on "Note-input" tooltip.

https://user-images.githubusercontent.com/76740999/221401035-b64e9cf9-8ce3-4697-977b-5051b7267621.mp4

<br>

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Hmm, that change sort of makes sense, but N is the shortcut already, even without being listed in shortcuts.xml. I wonder why?

**Comment by cbjeukendrup** [comment]
I'm afraid this is not entirely the correct solution, indeed because `N` is already the shortcut for the `note-input` action, so now we would have two actions with the same shortcut. 

Instead, I think we need to look in NoteInputBarModel.cpp: in `NoteInputBarModel::currentNoteInputModeAction()`, we just return the action for the current note input method. This way, the action has the name, icon and shortcut specific to the current note input method. But before returning the action, I think we should modify it to take the shortcut of the generic "toggle note input" action (with code `note-input`). So:
1. Query the action specific to the current note input method from the `uiActionsRegister()`;
2. Query the generic `note-input` action from `uiActionsRegister()`;
3. Change the shortcut of the method-specific action to the shortcut of the generic action;
4. Return the method-specific action.

(Note that we are not modifying the actions that are in the `uiActionsRegister()`, but just the local copy that is used in the NoteInputBarModel. That's exactly what we want.)

**Review by shoogle — CHANGES_REQUESTED** [review]
Please implement @cbjeukendrup's solution.

To understand the problem:

1. Click and hold on the note input button.
2. Choose one of the other note input methods, like Re-pitch.

image

Notice that the main button's icon changes to that of the chosen input method, and the tooltip's name, description, and the displayed shortcut also change.

image

This is desirable except for the shortcut. We want the shortcut for the main button to always be displayed as "N" regardless of the chosen input method.

Inside the menu, the specific shortcut (e.g. Ctrl+Shift+I) should always be displayed next to each mode. "N" shouldn't be displayed as the shortcut for any modes in the menu.

**Comment by limse10** [comment]
Hi, I believe I have fixed this issue with the method described by @cbjeukendrup

Check out #16619 

Thank you!

**Comment by cbjeukendrup** [comment]
@limse10 I will check it. However, in the future, please don't create PRs for issues on which another contributor is already actively working. This can lead to wasted efforts and is very not nice for the other contributor.

**Comment by limse10** [comment]
Ah, I understand. I will take note of that for the future. Thank you @cbjeukendrup and sorry @pratyaksh1610 for any inconvenience caused.

**Comment by cbjeukendrup** [comment]
Closing as replaced by #16619

**Pull request closed without merging**
