### PR TITLE
Updated Windows installer images

### PR DESCRIPTION
**Pull request by HemantAntony**
*(short description of the changes and the motivation to make the changes)*

This PR updates the Windows installer images

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by HemantAntony** [comment]
@jessjwilliamson I wasn't sure how to test this, but I'm pretty sure this should work :)

**Comment by cbjeukendrup** [comment]
@HemantAntony To test:
- Go to https://github.com/HemantAntony/MuseScore/actions/workflows/ci_windows_mu4.yml
- Click 'Enable workflow'
- Click 'Run workflow'
- Choose the `update_windows_installer_images` branch
- Replace 'devel_build' with 'testing_build'
- Leave the other settings as they are and click 'Run workflow'
- Now, a Windows installer should be built, and you can download its artifact when it's ready (and feel free to link it here so that others can test it too)
- If it fails with something about signing or permission, then you can't do much about that; in that case we'll have to merge this and run the workflow from the main repo
- I recommend to disable the CI_Windows_MU4 workflow again after you're ready (otherwise, it will run every night in your repo too, which is a useless waste of resources in GitHub data centers)

**Comment by jessjwilliamson** [comment]
I'm unable to test as I now switched back to mac. If someone is able to show a screenshot or something to show me that'll be appreciated :) Been reassured by Roman it looks good so I trust it should be okay!

**Comment by cbjeukendrup** [comment]
Ah ok. It looks like that's not gonna work anyway, so I'll take care of it.

**Comment by cbjeukendrup** [comment]
Looking perfect here! 🥳
Scherm­afbeelding 2022-09-30 om 18 45 21
Scherm­afbeelding 2022-09-30 om 18 45 28

**Review by cbjeukendrup — APPROVED** [review]

**Pull request merged**
