### PR TITLE
Implemented independent zooming and scrolling per notation

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #7879

### CODE REVIEW

**Comment by DmitryArefiev** [comment]
@cbjeukendrup This ready for testing? (I see branch conflict message)

Tested briefly on Windows, looks fine. Only notice another bug: when switching score to Continuous view it also switches parts.

**Comment by DmitryArefiev** [comment]
> I resolved the conflict!

Tested #7879 on Win10, Mac12, LinuxMint 20.2 - **FIXED**      

> I think it would be good to solve the bug about continuous view separately.

Yes, sure! I'll do it

**Comment by DmitryArefiev** [comment]
Please review (@RomanPudashkin @Eism )

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev I resolved the conflict! I think it would be good to solve the bug about continuous view separately.

Logged #11621 for that

**Comment by RobFog** [comment]
Rebase needed

**Pull request merged**
