### PR TITLE
fix #279964: bend font not connected to style

### PR DESCRIPTION
**Pull request by MarcSabatella**
Resolves: https://musescore.org/en/node/279964

The bend symbol displays a "random" (first in alphabetical order) font.
This is simply because the bendStyle fails to set up
the association between Sid::bendFontFace and Pid::FONT_FACE.
It seems this line was inadvertently removed
when we made the change to merge italic/bold/underline into style.

vtest added, it's the only way I can think to test this

### CODE REVIEW

**Comment by MarcSabatella** [comment]
I went and added two more commits to address what seem to be the two other biggest issues limiting the usefulness of bends in MsueScore 3.  There are other issues remaining, but they strike me as less important.

The second commit resolves https://musescore.org/en/node/286188

The third commit resolves https://musescore.org/en/node/286185

The vtest now addresses all three cases.

**Comment by RobFog** [comment]
Should this go in the 3.3 milestone then?

**Comment by anatoly-os** [comment]
@RobFog not a regression comparing to 3.2.3, so the fix will go to the next patch release.

**Comment by RobFog** [comment]
Alright. Jojo marked the "fix version" for the three issues as 3.3.0 so assumed that was the plan.

**Comment by Jojo-Schmitz** [comment]
Indeed I assumed so. We'll see...

**Comment by Howard-C** [comment]
The commit of this and #5360 do appear in the 3.3rc2 branch, so they're fixed in 3.3.0.

**Pull request merged**
