### PR TITLE
Fix #46281 (Follow text doesn't work for tempo marking with decimal)

### PR DESCRIPTION
**Pull request by johnsonge**
Fixed the bug that caused the tempo to not display properly in the view inspector if the number was a decimal. The issue was caused by an oversight in the defined QRegExp regarding the ability to display decimals.

* Changed QRegExp to accept a decimal and numbers after the decimal place.
* Changed the "toInt()"s to "toDouble()"s so that the field in the view inspector could take in and display the double

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
revision.h should not be in the commit.
Could the regex be made to work to accept a decimal comma too?

**Comment by Jojo-Schmitz** [comment]
* revision.h should not be in the commit. Check the developers' handbook, [Git Workflow, Summary](http://musescore.org/en/developers-handbook/git-workflow#Summary), item 5.
* Looks like this should be just one commit, can you squash it?
* if your commit message starts with "fix #46281", it'd get automagically marked as fixed in the issue tracker once the PR gets merged.

* Could the regex be made to work to accept a decimal comma too? Maybe replacing a comma with a dot Prior to feedi the resulting string to toDoubbe()?

I guess this replaces #1762, doesn't it?

**Comment by johnsonge** [comment]
Ok, I made a revision to allow decimal commas as well. But I'm confused as to how to remove the other file from my pull request

**Comment by andreituicu** [comment]
@johnsonge In the future you should consider creating new branches for fixing issues, or adding feaures instead of using your master. See the git workflow: http://musescore.org/en/developers-handbook/git-workflow .

**Comment by Jojo-Schmitz** [comment]
git reset 5bee9c7                            # to get back to the last 'official' commit
git checkout -b issue-46281            # create a topic branch and switch to it
git add libmscore/tempotext.cpp     # add the modified files, then commit the change
git commit -m "fix #46281: Follow text doesn't work for tempo marking with decimal"
git push -f                                        # force the push

**Comment by andreituicu** [comment]
@Jojo-Schmitz wouldn't this remove his changes? I think he would have to rewrite them in the new branch. He could first create the new branch and move into it, cherry pick his commit and push it to the new branch and only then go back to master and reset.

**Comment by Jojo-Schmitz** [comment]
"git reset SHA" doesn't lose, only if you add a "--hard"

**Comment by lasconic** [comment]
Closed. see https://github.com/musescore/MuseScore/pull/1783

**Pull request closed without merging**
