### PR TITLE
fixed #12791: Num pad not responding for duration selection

### LINKED ISSUE #12791: [MU4 Issue] Num pad not responding for duration selection
**Describe the bug**
Using num pad no longer works for selecting durations. I have checked Num Lock (makes numpad into arrows which navigate around buttons or notes). The problem started after I had been experimenting with using MuseScore with a MIDI keyboard. To remove the MIDI keyboard from the input slot I also clicked "Reset Preferences", so it may be due to that.
I tried re-adding the numbers as shortcuts, but that didn't do it.
Interesting point is that the numpad dot still selects dotted note, and + for ties and / for acciaccaturas still work.

I can only guess that Reset Preferences does this, but haven't been able to test from a starting point again.

**Expected behavior**
Use num pad numbers same as number row to select durations

**Platform information**
 - OS: Windows 10
 - MuseScore 4 Alpha

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #12791
Resolves: #12956
Resolves: #15204
Resolves: #14505

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Could you add Numpad+Enter as an additional shortcut for System Break?
Would fix #12956

**Comment by Eism** [comment]
@Jojo-Schmitz thanks, makes sense for 
And NumPad + dot for dotted duration?
And maybe NumPad ++/- for sharp/flat?
Maybe NumPad + / 

Did not find a sequence *

**Comment by Jojo-Schmitz** [comment]
Double/half duration, W and Q. Also with Shift

**Comment by Jojo-Schmitz** [comment]
OTH instead of flat/sharp I'd rather have NumPad + for Tie, maybe Numpad + - for Slur? Would allow easy note entry with one hand on Numpad and the other on mouse, excatly my favourite workflow

**Comment by Jojo-Schmitz** [comment]
> Why we should use NumPad+/ and NumPad+* for half and double duration?

Because those are otherwise unused? I'm open for better suggestions though. Not using them at all seems a waste.

**Comment by Jojo-Schmitz** [comment]
Maybe acciaccatura/appoggiatura? Might even be better.

**Comment by Eism** [comment]
For other changes please create a separate issue

**Comment by Jojo-Schmitz** [comment]
I'd need to check, but maybe add NumPad + , for those locales/keyboads that use , as the decimal separator

**Comment by Jojo-Schmitz** [comment]
Tested: durations (1-9) work, /, +, - and Enter works, but . (resp. , in my case) does not,
Windows 11, German QWERTZ keyboard, German language settings

Changing to
```
    <SC>
        <key>pad-dot</key>
        <seq>.</seq>
        <seq>Num+.</seq>
        <seq>Num+,</seq>
    </SC>
 ```
makes 'dot' work for me. Needed for all of continental Europe as far as I can tell

NumPad+0 doesn't work for Rest 
```
    <SC>
        <key>rest</key>
        <seq>0</seq>
        <seq>Num+0</seq>
    </SC>
 ```
fixes that. Both are vital shortcuts that did work in MU3 out of the box

So we're almost there ;-)

**Comment by Jojo-Schmitz** [comment]
Great! Now Mac and AZERTY users would need to test I guess

**Review by Jojo-Schmitz — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
Darn, that dreaded spurious unit test failure again...

**Comment by Flying-Roger** [comment]
See my recent post on https://github.com/musescore/MuseScore/issues/15204:

I noticed that there is a discrepancy between the way detects the numeric keypad while editing a score with respect to what it does while defining shortcuts:

while defining a shortcut, pressing 0 on the alphanumerical keyboard or pressing 0 on the numeric keypad has exactly the same effect: "0" is recorded for the shortcut.
while editing a score, pressing 0 on the alphanumerical keyboard does what is defined as "0" in the shortcut xml file, while pressing 0 on the numeric keypath does is not detected as "0", but as "Num+0", thereby requiring a specific definition in the shortcut xml file.
This is a bug : the consequence is that it is impossible to define a shortcut on the numerical keypad via the shortcut definition menu. The workaround is to export the shortcuts in xml, edit the xml to add the Num+x definitions and reimport the xml file.
I see that this topic is noted as "fixed", but I recommend to make sure that the root cause reported here above is also fixed.

**Pull request merged**
