### PR TITLE
fix #42936: beam distance doesn't scale with staff size

### PR DESCRIPTION
**Pull request by MarcSabatella**
This re-fixes the problem without breaking grace notes.  vtest added for both cases.

BTW, when I load the beams-1 vtest, I get different results from the reference, and this has been true for as long as I can remember.  The beam in the master for the first note clears the top staff line by a beam-width or so, but in when I load the file, the beam overlaps the staff line.  I have no idea which is intended or more correct, but I can't figure out why there is a discrepency.  @wschweer?

Here is what I see, with or without my change in this PR:

beams-1-1

### CODE REVIEW

**Comment by wschweer** [comment]
Some time ago i did a small change for calculating the stem length. The current version looks better so i updated the reference file.

**Comment by MarcSabatella** [comment]
I had assumed that initially, but then I noticed that the version with longer stems is what the automated vtests on Travis have been and still are producing.  See for example http://vtest.musescore.org/f471d311/vtest.html, a vtest run on Travis earlier today (after your change).  So somehow, this file still produces a different result on Travis than on our systems.  Maybe still some floating point comparison issues somewhere?

**Comment by lasconic** [comment]
If it helps, travis is running Qt 5.3.1 on Ubuntu 12.04 64 bit, vtest are
rendered using xvfb-run since there is no X server running.


2015-01-02 17:28 GMT+01:00 Marc Sabatella <notifications@github.com>:

**Comment by MarcSabatella** [comment]
It helps me decide not to worry any more about it for now, then :-).  I guess at some point travis will be updated to Qt 5.4 and we'll find out if that's the difference.

**Pull request merged**
