### PR TITLE
fixed path to images of SaveToCloud

### PR DESCRIPTION
**Pull request by igorkorsukov**
Resolves: https://github.com/musescore/MuseScore/issues/21695

### CODE REVIEW

**Review by Eism — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
Shouldn't we investigate why relative paths are no longer working? (I.e. why the path is interpreted relative to `src/project/qml/MuseScore/Project/internal/SaveToCloud/SaveLocationOption.qml` instead of relative to the file in which the path is written, i.e. `src/project/qml/MuseScore/Project/AskSaveLocationTypeDialog.qml`?)

Or have you already investigated it and was the conclusion that there is nothing we can do?

**Comment by igorkorsukov** [comment]
> Shouldn't we investigate why relative paths are no longer working? (I.e. why the path is interpreted relative to `src/project/qml/MuseScore/Project/internal/SaveToCloud/SaveLocationOption.qml` instead of relative to the file in which the path is written, i.e. `src/project/qml/MuseScore/Project/AskSaveLocationTypeDialog.qml`?)
> 
> Or have you already investigated it and was the conclusion that there is nothing we can do?

I haven't researched it, but I believe that in any case it is better to use aliases so that it does not depend on the actual location of the file.
It would be interesting to find out what has changed and why, but this is just interest, nothing more.

**Comment by DmitryArefiev** [comment]
Tested #21695 on Win11, Mac13.6, LinuxUbuntu22.04 - **FIXED**

**Comment by igorkorsukov** [comment]
I found out that we can set the URL relative to the Image component, then it works

image

**Comment by igorkorsukov** [comment]
And that's how it works

image

**Pull request merged**
