### PR TITLE
Add "Guitar (Treble Clef)" to instruments.xml

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
See discussion in https://musescore.org/en/node/38581

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I have the feeling that the need to change the string data (tune an octave up) is just a workaround for (linked) tablature not working properly with transposing instruments.

**Comment by mgavioli** [comment]
Part of the problem is that, if an instrument is defined as transposing, the transposition is active in any of its staves. This is why, in such a case, the string data need to be tuned one octave up: to correct the transposition one octave down defined in the instrument (and applying to all staves of that instrument). In a sense, the problem arises from the fact that tablature __is working__ with transposing instruments.

Another part of the problem is that pitch resulting from octave transposition and pitch resulting from non-octave transposition are stored in different `Note` variables (`Note::ppitch` and `Note::epitch`). I am also not sure if octave transpositions are stored in the staff transposition map or not.

Non-octave transposition has been dealt with in the issue https://musescore.org/en/node/47526 (and another aspect of it in the issue https://musescore.org/en/node/48051; both result fixed and closed since long).

In addition, octave transposition interacts with 8a lines, which are a source of problems with linked staves; I submitted two different fixes for that months ago, but no definitive decision has been made.

This PR might be a temporary work-around, but the matter seems to me quite involved and suffering from separate 'organic' additions and corrections.

Lastly, it is unclear which the user expectations are for these use cases; presumably they are not the same for all users.

**Comment by Jojo-Schmitz** [comment]
Thanks for checking and commenting. I certainly agree that the string data upshift by an octave part of this PR is more of a work around than a real fix. I could make mit 2 commits, so that part could get reverted easier?
Not sure also whether we need the other guitars having a treble clef version too, comments?

**Comment by Jojo-Schmitz** [comment]
see also https://musescore.org/en/node/116591, which adds bass guitar and bass clef vs. bass clef 8vb to the equation

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.org/en/node/17623

**Comment by lasconic** [comment]
Let's see how the workaround work for now...

**Pull request merged**
