### PR TITLE
Fix key signatures regarding concert pitch when cloning staff

### PR DESCRIPTION
**Pull request by cbjeukendrup**
when either the full score is in concert pitch and the part not, or the part is in concert pitch and the score not.

Resolves: #16554

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
The third commit is an attempt to fix an assertion failure that happened sometimes but I still haven't found a way to reproduce it reliably. It must be some permutation of toggling concert pitch in the full score and in the part score, adding instruments and saving/closing/reopening, and adding key signatures. 

The fourth commit fixes an additional bug that still occurred after the second commit: 
1. Create score with transposing instrument and concert C major key sig
8. Turn on concert pitch
9. Save close reopen
10. Turn off concert pitch
11. Create new empty part
12. Make the instrument visible in that part
-> the instrument has the wrong key sig in the part

@mike-spa Since you have worked before on issues that turned out to be related to deleting C major key signatures at the beginning of a score, could you please check if this PR looks good to you?

**Review by mike-spa — APPROVED** [review]
@cbjeukendrup as far as I can see, this looks perfectly coherent with all the other similar fixes I've done (removing a keySig from the score just because it happens to be C is a _very_ wrong idea IMO, so I'm very glad to see it gone).

**Review by oktophonie — APPROVED** [review]

**Comment by RomanPudashkin** [comment]
@cbjeukendrup please pay attention to the failed tests

**Comment by cbjeukendrup** [comment]
@RomanPudashkin Done!

**Review by RomanPudashkin — APPROVED** [review]

**Pull request merged**
