### PR TITLE
fix #300279: Impossible to apply properties to all parts in 3.4.1

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: https://musescore.org/en/node/300279

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
`buttonApplyToAllParts->setEnabled(!cs->isMaster());` could get moved to (or repeated in) either `showEvent()` or `setValues()`, not sure what would be preferred?

So far I moved it to `setValues()`.

**Comment by Jojo-Schmitz** [comment]
Darn, now the Format > Page Properties dialog crashes

**Comment by AntonioBL** [comment]
Well, in master I see this assert crash even without this PR (as expected, since this PR is not modifying that part of the code). I simply have to open Format > Page Settings from a part instead of the main score. Most probably it "crashes" only in a debug build.

**Comment by Jojo-Schmitz** [comment]
Ah, thanks, so not my fault at all, thanks for checking!

**Comment by Jojo-Schmitz** [comment]
Seems to me to make more sense to set it in `showEvent()`

**Pull request merged**
