### PR TITLE
Fix #176671: Slash notehead position needs adjusting

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
3 commits for easy cherry-picking the 1st (for Emmentaler) into 2.2, the 2nd (for Musejazz) into master and possibly ignoring the 3rd (for Bravura, could go into 2.2 and master),

### CODE REVIEW

**Comment by lasconic** [comment]
We don't change Bravura metadata lightly. If it's really really an issue and we are sure it's not our code, we should file an issue upstream. Are we really sure this is the right thing to do?

**Comment by Jojo-Schmitz** [comment]
Here's how these look without the fix
emmentaler
bravura
gonville
musejazz

**Comment by Jojo-Schmitz** [comment]
anehr here's hot it Looks when fixed,

Emmentaler:
emmentalerfixed
Bravura:
bravurafixed
MuseJazz:
musejazzfixed

**Comment by IsaacWeiss** [comment]
Stems thicker in the second set of images?

**Comment by Jojo-Schmitz** [comment]
No, just a different zoom

**Comment by lasconic** [comment]
I checked again, and by the definition stemDownNW and stemUpSE, it seems 1.0 should be ok. I means one space from the center of the glyph. It could be that we are not using the values correctly...

**Comment by Jojo-Schmitz** [comment]
Maybe the thickness of the stem needs to be added or subtracted?

**Comment by lasconic** [comment]
Yes, at least on Y added or substracted depending on the stem direction. Also, stemDownNW and stemUpSE are from the origin of the notehead glyphs... I'm not sure if we take this into account.

**Comment by anatoly-os** [comment]
Current state of stem position for slashes is totally different and I believe the reason is in the way MuseScore postitions the ste, not the symbol properties. I'll have a look at this issue when fixing https://musescore.org/en/node/275922.

**Pull request closed without merging**
