### PR TITLE
Prepare installers for Microsoft Store (+ collect_artifacts)

### PR DESCRIPTION
**Pull request by anatoly-os**
It is time to make an update to Microsoft Store packages

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Almost exactly what #5214 does too?

**Comment by anatoly-os** [comment]
@Jojo-Schmitz almost, indeed. First, I don't want to add ntfs_locker in/decrements to the codebase for other platforms. Second, there is one more place to put those in/decrements.

**Comment by Jojo-Schmitz** [comment]
Reg. 2nd: these are identical in both PRs, 3 places in total.

**Comment by anatoly-os** [comment]
.appx files based on the .msi installers from this PR have been created and published to Win Store.

**Pull request closed without merging**
