### PR TITLE
Fix for issue #16125 | [MU4 Issue] [Workspaces] UI glitch in workspaces window when adding too much workspaces

### PR DESCRIPTION
**Pull request by octopols**
Resolves: #16125 

added `clip: true` property to `src\workspace\qml\MuseScore\Workspace\internal\WorkspacesView.qml` which overrides the `clip: false` property used in `StyledListView` in `src\framework\uicomponents\qml\MuseScore\UiComponents\RadioButtonGroup.qml`

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by octopols** [comment]
https://user-images.githubusercontent.com/90182257/215731746-78a00093-5c6d-4360-b92e-2e58ec69daf3.mp4

**Comment by Jojo-Schmitz** [comment]
Replaced by #16125, riught?

**Comment by octopols** [comment]
> Replaced by #16125, riught?

#16154

**Comment by Jojo-Schmitz** [comment]
Of course...

**Pull request closed without merging**
