### PR TITLE
[MU4] Add support for triple sharp and triple flat

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
SMuFL provides glyphs for triple sharp and triple flat, so they might as well be available to use in MuseScore. This involves adding 14 new TPCs and expanding the range of the AccidentalVal enum class.

This was requested on the forum topic in [Triple sharps and triple flats](https://musescore.org/en/node/304503)  _(sort of, ignore the digressions into politics and key signatures)_.

See https://seanyeh.com/pages/alkans_triple_sharp/ for an example of a triple sharp being used in a piece of music from the Romantic period.

Counterpart for master to #6744.
Finally obsoletes #6002, (@mattmcclinch ?).

### CODE REVIEW

**Comment by mirabilos** [comment]
Don’t forget to add the two new `QT_TRANSLATE_NOOP`s to `fonttools/smufl2sym-in-trans.json` once the PR adding that is merged.

**Comment by Jojo-Schmitz** [comment]
Ah, that is the purpose of that file!

**Comment by mirabilos** [comment]
Joachim Schmitz dixit:

>Ah, that is the purpose of that file!

Yes… which is also documented in length in the commit
message… which I also responded to you in the other PR ☻

**Comment by Jojo-Schmitz** [comment]
Oops. missed it there. Added a response there now...

**Pull request merged**
