### PR TITLE
Fix #109066 : Tempo Slider and Volume slider Left Double click wrong default values

### PR DESCRIPTION
**Pull request by nasehim7**
Fix to Double-click sliders in play panel or synthesizer sets them to zero

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
Can you squash the two commits into one, with the commit message including "Fix #109066", and force push?

**Comment by nasehim7** [comment]
I will try never squashed before :)

**Comment by IsaacWeiss** [comment]
I like to do it from a GUI with GitKraken now, but here are the instructions I first followed: https://github.com/musescore/MuseScore/pull/2378#issuecomment-184348197

**Comment by nasehim7** [comment]
What i basically do for a PR is : 
1. I update my forked repo.
2. Use my commandline to create a branch.
3. Make exact changes on my Account
4. Go for a PR.
For squashing, it says i have unstaged commits. I guess i will have to try it and today is that one fine day.

**Comment by nasehim7** [comment]
I guess i did it finally :)

**Comment by IsaacWeiss** [comment]
Change the message one more time? We prefer "Fix #109066"" because of https://musescore.org/en/developers-handbook/references/development-infrastructure#Mark-issue-as-fixed-automatically.

**Comment by nasehim7** [comment]
Done :)

**Comment by ericfont** [comment]
I tested and made a comment to musescore.org issue tracker: "FYI, I've tested out Animesh's fix, and it fixes the problem. My only (minor) quibble is that double clicking doesn't reset the value to *exactly* the same value as when musescore boots. Ideally I would have liked to have the first time the slider is initialized to be the action which sets the default value for double click. I mentioned this in irc to Animesh, but I said we'll wait and see what lasonic thinks."

**Comment by IsaacWeiss** [comment]
It's not the name of pull request that has the function—it's the message in the commit. https://github.com/musescore/MuseScore/pull/3077/commits/36417ed718c0249a337b12aae0ca44aec17b7ccd is still "Issue #109066 : Tempo Slider and Volume slider Left Double click wron…"

**Comment by nasehim7** [comment]
Okay i will do it the moment i'm back home. :)

**Comment by nasehim7** [comment]
Done :)

**Comment by Jojo-Schmitz** [comment]
"Fix #109066 : Tempo Slider and Volume slider Left Double click wron…" would be even better

**Comment by ericfont** [comment]
I just now discovered that the Synth window's "Save to Score", "Load from Score", "Set as Default", "Load Default" buttons will all save and restore the a value for the master gain.  I'm now thinking that this default value should be the value that will be recalled when double clicking.

So to be consistent with this default, I would have SynthControl::updateGui() call setDclickValue1(synti->gain()) right after the line setGain(synti->gain()).

**Comment by lasconic** [comment]
@nasehim7 can you adapt it according to the latest comment of @ericfont ?

**Comment by nasehim7** [comment]
Yes i can surely do that :)

**Comment by nasehim7** [comment]
@ericfont Tell me if i understand this correctly :
The Volslider is a part of the awl abstract slider class and can have functions like setDclickValue1() but i can't incorporate setDclickValue1(synti->gain()) right after the line setGain(synti->gain()) as it is not declared in the scope. :)

**Comment by ericfont** [comment]
I haven't spent time figuring out the exact code needed, or I would have done this myself.  Hopefully you can find a way to have the update of the default value be able to set the double click value of the main volume slider to the value synti->gain().  There should be a way, but you'll have to look how the objects are organized.

**Comment by nasehim7** [comment]
Okay i get it. On it :)

**Pull request closed without merging**
