### PR TITLE
fix #267760 Screen capture in PDF format doesn't work correctly

### PR DESCRIPTION
**Pull request by AntonioBL**

### CODE REVIEW

**Comment by AntonioBL** [comment]
If I understood correctly what was going on, the QPrinter was initialized in QPrinter::HighResolution mode. From Qt documentation: "On  Windows, sets the printer resolution to that defined for the printer in  use. For PDF printing, sets the resolution of the PDF driver to 1200  dpi."
Therefore, "mag" variable was reading a resolution which was not the 1200 dpi resolution set when the printer was put in pdf-output mode.
I could only test this under Windows (and with this PR the problem appears solved), but I expect that it should solve the problem also under Mac.

Maybe in master the fix would be to exchange the order of the two instructions (so that the resolution is set before calculating the magnification factor):
mag = pdfWriter.logicalDpiX() / DPI;
pdfWriter.setResolution(preferences.exportPdfDpi);

**Comment by lasconic** [comment]
Thanks. Checking on mac

**Comment by lasconic** [comment]
It works on Mac too. Great!

**Comment by lasconic** [comment]
Font is a bit blurry I fixed in the next commit. For master, I tried it here https://github.com/musescore/MuseScore/commit/698ae4c911f23fcdfb1ea60a7f06e564a432f040 and added the same fix for blurry font, but it doesn't solve the problem entirely yet.

**Pull request merged**
