### PR TITLE
[GSoC 2019] Basic chord symbol realization

### PR DESCRIPTION
**Pull request by dmitrio95**
This is a rebased version of PR #5129. So far only rebase to master branch has been done, but some minor code changes (and perhaps commits squashing) will be added here soon.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
with artifacts please

**Comment by MarcSabatella** [comment]
Thanks again for taking on the otherwise thankless task of rebasing and otherwise updating these PR's.  BTW, I made a comment at FOSDEM and feel bad that my meaning may have not come across correctly, so for the record: you are doing an absolutely amazing job; I don't know what we'd do without you!

I'm definitely still up for whatever additional testing or consulting on algorithms you need, let me know when you have it in the state you want it.

**Comment by igorkorsukov** [comment]
from dev chat:   

> Marc Sabatella
> I'm playing https://musescore.com/marcsabatella/jazz-pathetique-2 right now, so great to have this!
   
> J. Edward Sanchez
> I was able to get chord playback working with this piece, but not with one my own. Does anyone  have any idea what I might be doing wrong?
  
> Marc Sabatella
> apparently it doens't like the violin staff, works if the chord is on piano, not sure why
   
>  Joachim Schmitz
>  Probably got to be an instrument capable of chords, Piano, Guitar
  
>   Marc Sabatella
>   I think we had discussed making the playback sound default to piano, or maybe guitar, and maybe at one timer the implementation did that
>   But for now, indeed, if you go to View / Mixer, open up the Vioiin channel strip, and set the Harmony channel to guitar or piano, it works.
  
>   J. Edward Sanchez
>   I can confirm that that works. Probably not a very obvious workaround to most users, but it does work.
   
>  Marc Sabatella
>  I'm not saying that is by design, could be an unintended side effect of the channel implementation we were just discussing.  Or a bug in the original code.  Or maybe I'm still missing something.
>  Right now, I'm not seeing where in the code we are actually making the decision.  As far as I can the play events are getting generated either way.
  
>  J. Edward Sanchez
>  Playing around with it a bit. Looks like the harmony channel gets created the first time a chord is added to an instrument.
  
>  Marc Sabatella
>  yes, and that works, the channel is there, the code that plays the chord is getting the right index, everything looks good up through the code I understand.  but somehow, the even just never gets played.  i'm guessing somehow the renderHarmony flag is getting set to false for that event, but I'm not seeing how, yet
  
> Marc Sabatella
> Peter Hieu if you are around and see this and have any insight (why sounds other than piano or guitar don't seem to work for chord symbol playback, and what the thinking is behind that), let us know
> Hmm, actually, I think it has nothing to do with piano/guitar being special - it's single note dynamics - any "expr" instrument fails
   
> Marc Sabatella
@Spire42 Peter Hieu @igorkorsukov @jthistle  ^^^ unfortunately I'm really ignorant about how SND is implemented, but I guess the code that sends the chord symbol playback events needs to be SND-aware somehow
>  @Spire42 see above, I donb't think we are or should be defaulting to piano, issue is simply that SND sounds don't work right now
   
> J. Edward Sanchez
> OK.
> I was just thinking of what we could do in the event that SND can't be made to work.
  
> Marc Sabatella
> although people writing for violin or voice or whatever probably will be surprised also to hear playback using the same sound, so really we *could* consider an option for a default sound
> I will assume it can be made to work, but it's still worth discussing, probably will need to wait until others are around.  Anyhow, for now, mystery solved.
   
> Marc Sabatella
>  fwiw, I found a crash in my testing, added comment to the PR identifying it.  But aside from that, the chord symbol playback actually helped me find a few typos in my lead sheet, so, a win already!

**Comment by dmitrio95** [comment]
Continued in #5810.

**Pull request closed without merging**
