### PR TITLE
fix #277230 - MuseScore saves a corrupted file after importing a Musi…

### PR DESCRIPTION
**Pull request by lvinken**
…cXML file

Fix overflow in class Fraction's code caused by too large numbers originating from MusicXML files by calculating in 64 bit where required.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Travis CI fails on one mtest, which looks like easy to fox, see https://travis-ci.org/musescore/MuseScore/jobs/453642107#L5574-L5616

**Comment by lvinken** [comment]
Same issue as in PR 4131.

**Comment by lvinken** [comment]
Travis error should be fixed when PR 4131 has been merged and this branch is rebased.

**Comment by lvinken** [comment]
Rebased to current master, as PR 4131 has been merged.

**Pull request merged**
