### PR TITLE
change flats, sharps and naturals to Unicode

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
where they are to be translated, directly in .ui files, escaped in .cpp files, even remove some from translation.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
I'd love to extend this to double flats and double sharps, but unfortunatly their Unicode representations are missing from the vast majority of fonts, so won't render.

**Comment by lasconic** [comment]
And now I remember why we didn't do it earlier. Users on XP and/or Vista complained about flat and sharps not being displayed. That's why we used b and #. We still have 5% of users on XP and vista AFAIK...

**Comment by Jojo-Schmitz** [comment]
Hmm, I'm pretty sure it did work in XP too, I've been usind XP and had those signs in the German translations ever since. I'll try in a VM...

**Comment by Jojo-Schmitz** [comment]
Hmm, I'm pretty sure it did work in XP too, I've been usind XP and had those signs in the German translations ever since. I'll try in a VM...

Edit: No problem in "Virtual Windows XP Mode"

**Comment by Jojo-Schmitz** [comment]
Hmm, I'm pretty sure it did work in XP too, I've been usind XP and had those signs in the German translations ever since. I'll try in a VM...

Edit: in "Virtual Windows XP Mode" the sharps work, naturals and flats don't.

**Comment by Jojo-Schmitz** [comment]
Hmm, I'm pretty sure it did work in XP too, I've been usind XP and had those signs in the German translations ever since. I'll try in a VM...

Edit: in "Virtual Windows XP Mode" the sharps work, naturals and flats don't. :-(

I wonder though why we haven't had any complaints so far from the XP/Vista users, as these signs are used in the translations, at least in de, en_US and en_GB, almost ever since the translations for 2.0 started

**Comment by lasconic** [comment]
Let's stick with what we have for now.

**Pull request closed without merging**
