### PR TITLE
Add definition for continuous glissando for voice

### PR DESCRIPTION
**Pull request by djfun**
Resolves: #15268 (and duplicates)

The definition for "ContinuousGlissando" was copied from the winds articulation profile. That seems to resolve the issue.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by djfun** [comment]
@cbjeukendrup @RomanPudashkin is this going to get merged any time soon?

**Comment by DmitryArefiev** [comment]
@djfun I've tried your build on Win10. **Voices** look fine now, but **Organ** and **Synths still have the problem**
Can you fix please it if it's the same?

https://github.com/musescore/MuseScore/assets/90187801/cfb64866-9e84-406f-a33e-5df38ce2e91d

**Comment by Jojo-Schmitz** [comment]
Can (non-electronic) organs to portamentos?

**Comment by DmitryArefiev** [comment]
In real physical life of course not (the same as piano). But for now, it should just work like in MS3.6.2

**Comment by Jojo-Schmitz** [comment]
Why emulate a 3.6.2 bug?

**Comment by djfun** [comment]
imho: if the option for continuous glissando is available to the user for a certain instrument, the playback should also work (or at least not do strange things like it's doing right now)

Maybe the correct choice for keyboard instruments would be to disable the option for the user, but as long as that's not the case, the better alternative is not having buggy playback.

**Comment by Jojo-Schmitz** [comment]
I think this is the same as with single note dynamics, some instruments can do them, others not. So it should be part of the instrument definition

**Comment by Jojo-Schmitz** [comment]
Until then: Garbage in, garbage out, of you do apply portamatone to an instrument incapable of doing it, wierd things are expected to happen

**Comment by Jojo-Schmitz** [comment]
But here it seems 'All Keyboards Are Created Equal" ;-)

**Comment by DmitryArefiev** [comment]
Tested #15268 #12838 on Win10, Mac13, LinuxUbuntu 22.04 - **FIXED**

**Pull request merged**
