### PR TITLE
[MU4] Fix compiler warning reg. `size_t` vs. `int`

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
@Eism please review ;-)

### CODE REVIEW

**Comment by Eism** [comment]
Hm, static_cast<size_t>(-1) it also not a valid number.
it's better to avoid using size_t to get the index of an element 
just replace it with static int indexOf
and 
return static_cast<size_t>(i);

how I love std :)

**Comment by Jojo-Schmitz** [comment]
Well, an index is always positive, isn't it?

**Comment by Jojo-Schmitz** [comment]
`static_cast<size_t>(-1)` as far as I can tell is FFFF(FFFF), on any two's complement machine?

**Comment by Eism** [comment]
Yes, if an element is found. size_t is needed for dimension, not for indexing if I understood correctly.
I did as in standard Qt containers (QList).

**Comment by igorkorsukov** [comment]
replaced by https://github.com/musescore/MuseScore/pull/7164

**Pull request closed without merging**
