### PR TITLE
fix #19092 - correct full measure rest in parts

### LINKED ISSUE #19092: "This score has become corrupted" message when changing actual measure duration with opened parts
### Issue type

File corruption

### Bug description

Musescore shows "This score has become corrupted and contains errors" message if you change actual measure duration, then return back default values for that measure. This happens if part for that instrument is opened.

Affected versions (which I checked):
4.0.2
4.1.1
4.2.0 (master)

### Steps to reproduce

1. Create empty document (from Treble clef template)
2. Go to Parts -> Select and open Piano part
3. Go back to main score
4. Right click on any measure -> Measure properties - > Measure duration -> Set Actual: 2/8 - > OK
5. Repeat step 4, but set value back to 4/4 - > Ok
6. If you try to save file, Musescore will show message "This score has become corrupted and contains errors"

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/919446/190833d4-e1a0-49e5-9771-94437401bcc6

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232300304, revision: github-musescore-musescore-741c7e6

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009

### PR DESCRIPTION
**Pull request by sammik**
Resolves: #19092 
correct ~~multimeasure~~ fullmeasure rest in parts after changing measure in score

changes to rests needs to be aplied to linked rests (in parts) as well

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

**Comment by sammik** [comment]
Sorry, I reworded commit, as it is "full-measure rest" and not "multimeasure rest".

Nothing else changed.

**Comment by cbjeukendrup** [comment]
@mike-spa Could you take a look at this and check how this will interact with your score/parts interaction PR?

**Comment by mercuree** [comment]
@sammik I can still change actual size for multi-measure rest in parts and it makes score corrupted. Not sure if there is a reason why we can change measure properties for multi-measure rest. Should I create another issue for this?

**Comment by mike-spa** [comment]
@cbjeukendrup @sammik I'm actually surprised that the `DURATION` property is not marked as a linked property (see [here](https://github.com/musescore/MuseScore/blob/master/src/engraving/dom/property.cpp#L248-L249)). I think it should be linked, because I can't think of situations where you'd want durations to mismatch between an item and its clones in parts. Marking it linked (basically just putting "true" in those two lines I've linked) should fix the issue more solidly, I think. In any case, please wait after my parts/score PR is merged before doing that :)

**Comment by sammik** [comment]
> @sammik I can still change actual size for multi-measure rest in parts and it makes score corrupted. Not sure if there is a reason why we can change measure properties for multi-measure rest. Should I create another issue for this?

@mercuree I think, multimeasure rest measure should be unchangeable. 
Please, report it as separate issue. Thank You.

**Comment by sammik** [comment]
I did change @mike-spa proposed: dont find linked chords as duration itself should be linked

I also changed one similar place in `undoChangeChordRestLen`, and removed `findLinkedVoiceElement` function, as it became unused.

@cbjeukendrup

**Comment by Jojo-Schmitz** [comment]
It seems this PR fixes the corruption, but does not always restore a full measure rest. It does only if the measure before contained notes that after won't fix (like a whole note in a 4/4 measure), which then does get replacerd by a while measure rest and stays that way, but in other cases, like a measure containing a whole measure rest already, it doesn't work but changes  to e.g. hape + qarter test when changing 4/4 to 3/4 and half + 2 quarter rests when changing back to 4/4.

Hope I made myself clear?

**Comment by sammik** [comment]
> It seems this PR indeed fixes the corruption, but does not always restore a full measure rest. It does only if the measure before contained notes that after won't fix (like a whole note in a 4/4 measure), which then does get replaced by a whole measure rest and stays that way, but in other cases, like a measure containing a whole measure rest already, it doesn't work, but changes to e.g. half + quarter test when changing 4/4 to 3/4 and half + 2 quarter rests when changing back to 4/4.
> 
> Hope I made myself clear?

@Jojo-Schmitz Its different thing (out of scope of this PR). Design is (if I got it): if there is single rest and measure changes to standard duration, it should be fullmeasure rest. 
Problem is, when changing between even and odd. 
I dont see a way, how to know, wheter there should be fullmeasure, or not, so it is not in that cases.

**Comment by Jojo-Schmitz** [comment]
I see.

**Review by oktophonie — APPROVED** [review]

**Pull request merged**
