### PR TITLE
Fix #232931 follow-up: change behavior of adding breaks from palette

### PR DESCRIPTION
**Pull request by IsaacWeiss**
I think this does no harm; I initially thought it was buggy, but it turned out to be a pre-existing Heisenbug.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
I haven't tested but it looks good!

**Comment by IsaacWeiss** [comment]
@MarcSabatella I also moved the line like you said. ;-) BTW, the Heisenbug http://imgur.com/a/vWbJG was occurring with the shortcut, too, but very rare either way, and not often enough for me to figure out the rule.

**Comment by lasconic** [comment]
Also see https://github.com/musescore/MuseScore/pull/3243

**Comment by lasconic** [comment]
If we want this in 2.2 we now have to port #3243 and #3250

**Pull request merged**
