### PR TITLE
Add missing QT_DEBUG checks

### PR DESCRIPTION
**Pull request by hrw**
Those changes were needed to get 2.0.1 built in Fedora distribution.

Some of checks may be wrong.

### CODE REVIEW

**Comment by lasconic** [comment]
Thank you. Which Fedora version? Does it use Qt 5.5 by any chance?

**Comment by hrw** [comment]
This is Fedora rawhide with Qt 5.5

**Comment by lasconic** [comment]
OK. Then the fix I mentioned should work there too. No need to pull your request. Could you try and see if it's the case?

**Comment by hrw** [comment]
will check, thanks

**Comment by hrw** [comment]
Changeset fixed issue. Thanks

**Pull request closed without merging**
