### PR TITLE
#66851 test cases for forward jumps

### PR DESCRIPTION
**Pull request by ericfont**
added 4 test repeat cases for forward jumps, see comment https://musescore.org/en/node/66851#comment-307766

### CODE REVIEW

**Comment by lasconic** [comment]
Since you are now working on this topic, I close this PR.

**Comment by ericfont** [comment]
the repeat29 test I have works in both 2.0.2 and nightly.  Can I simply reopen PR with that test case only (won't need any code fixes, since it works).  I'm don't want to waste time dealing with other forward repeat cases, because the only one I know who is convinced of their utility is myself.

**Comment by ericfont** [comment]
or maybe should we instead just say that forward jumps are not officially supported behavior?

**Comment by lasconic** [comment]
If you feel it's worth to maintain the behavior, a test is better than none. So sure, make a PR with this test.

**Pull request closed without merging**
