### PR TITLE
Fix for <sound> tag tempo in <measure> for xml import

### PR DESCRIPTION
**Pull request by notationist17**
Not the most elegant solution, but it is a start. Important because Finale 2014 seems to put tempo as a <sound> tag directly in <measure>  and not in <measure><direction> like the current import implementation presumes.

### CODE REVIEW

**Comment by lasconic** [comment]
Thank you for your contribution! Could you sign the MuseScore CLA https://musescore.org/cla ? It's needed in order to pull your code in the main repository.

@lvinken What do you think about this change?

**Comment by lvinken** [comment]
Will have a look, but not on short notice (real life / day-time job
interfering).
Regards, Leon.

**Comment by lasconic** [comment]
Sure, no hurry.

**Comment by notationist17** [comment]
signed the CLA as margus.niitsoo. notationist17 is my old account... moving the fork to my main account 'velochy' as we speak, and will continue to respond here from that account from now on.

**Comment by lvinken** [comment]
Thanks for fixing this, I agree MuseScore should also support sound elements in a measure instead of in a direction in a measure.

A few remarks on the code:
- it does not break anything (no regression)
- for me, it causes a trap, because track is not initialized for TempoText* t
  (preferred solution: use addElemOffset() instead of coding "add text to score" explicitly here)
- replace skipLogCurrElem() by _e.skipCurrentElement()
- use qDebug for debug output (for consistency with the rest of the file) and disable it for production code
- please add a test file for the auto tester

Discussion item: the code creates an empty (thus invisible) tempo text. This makes it hard to handle in the user interface. The current implementation for sound within direction ignores sound without text, which is not completely consistent.

**Comment by velochy** [comment]
Thank you for the comments, @lvinken . Fixed everything except for the automated test. Could you give me some pointers as to how to go about writing the test and maybe point me to a direction of a good example to base it on, for instance. This is my first PR so I don't know anything about the testing system and have no clue even where to start.

**Comment by lvinken** [comment]
Adding auto tests is easy. Create one or more MusicXML files containing the new features (note: aim at having complete test coverage, but not too many or too complex testfiles, as the auto tester runs for every pull request). Add these files to the mtest/musicxml/io directory together with the PDF rendering (for easy visual inspection of the result). The auto tester imports each file, exports it again and compares the two. Note that if the output should differ from the input (which I suspect will be the case for you), also add the expected output as _ref.xml files. Add the tests to the list in tst_mxml_io.cpp. You can run the auto tester manually by using the iotest script.

**Comment by velochy** [comment]
Thank you, @lvinken. Trouble is, it in no way affects rendering, only playback (and midi/audio output). Any way to create tests that compare exported midi files instead?

**Comment by mgavioli** [comment]
You may look at the tests in the mtest/libmscore/midi directory.

**Comment by velochy** [comment]
Thank you for the suggestion, @mgavioli  . However, it seems that this is also not an option as midi export tests are hard-coded to use mscx files and this fixes an xml import bug that does not show up if input is mscx.

Waiting for further guidance on how to proceed with testing...

**Comment by mgavioli** [comment]
@velochy : I do not know the details of your tests as much as you do, so I should probably just trust you... My reasoning is: after importing an MXML file, you have in memory a MuseScore score, from which you can either:

1) export to MIDI
or
2) force the creation of MIDI events for chords/notes/rests (`doLayout()` should do it, but it is better to verify)

At this point, you would be in the same (or similar) situation of the MIDI tests and could proceed accordingly or similarly.

Then, of course, there might be simpler or more straightforward ways, but code which is known to work already exists for this approach and using it might be the quickest way.

**Comment by velochy** [comment]
Thank you @mgavioli but I don't think I understand quite what you are proposing. Am I correct in that you recommend I create a test that 
a) Imports MXML
b) Exports it to midi
c) Tests the midi against the reference?
Such a test would indeed be ideal.

However, I have no idea how to go about creating it, as the automated tests seem to test either 
1) the creation of a proper PDF from a given input XML
or 
2) the creation of a proper MIDI from a given input MSCX
neither of which would test what is needed here.

**Comment by AntonioBL** [comment]
Actually the tests use the function "readScore" defined in mtest/testutils.cpp.
This function can read also an xml file and gives back a MuseScore score (inside testutils.cpp, readScore calls readCreatedScore, which in the case of "xml" extension calls importMusicXml function). Therefore, I think you can simply use the tests which are written for mscx file and substitute the input with a string with the name of the xml file you want to test (and of course use the proper midi reference).

Ciao,
ABL

**Comment by velochy** [comment]
And I'm a bit stuck again, but with a simple question:

how do you actually run the tests in the mtest/libmscore/midi/ directory?

Quick googling seems to produce only tangentially related things (like PR
for test system improvements in git or on message boards).

Is there a "If you want to contribute" guide somewhere that I'm missing? It
would be helpful to have one that would give an overview of style
guidelines, requirements for PR to be accepted and a quick primer on the
testing system used, for newbies like me to get up to speed.

Best,
Margus

**Comment by velochy** [comment]
Got a test added.
Had to change the testing system to accept files with other extensions in the midi tests. Hope that is ok.

**Comment by lasconic** [comment]
For future reference
Building and writing tests
https://github.com/musescore/MuseScore/blob/master/mtest/README.md

Contribution guide, git workflow and so on 
https://musescore.org/en/developers-handbook/

**Comment by velochy** [comment]
Thank you @lasconic . The handbook I've skimmed through before, but the tests readme was new to me. Really useful stuff :)

Let me know if any work still needs to be done.

**Comment by Jojo-Schmitz** [comment]
something went horribly wrong, did you fetch rather than rebase?

**Comment by velochy** [comment]
I did neither, just merged in the latest musescore/master 

Anyways: why is this not merged in yet, considering the last comment on the thread was 5 months ago. I really did not expect this would break anything.

**Comment by Jojo-Schmitz** [comment]
So you merged, you should have rebased instead. See https://musescore.org/en/developers-handbook/git-workflow#Rebase-your-branch-on-the-latest-upstream

**Comment by Jojo-Schmitz** [comment]
is this PR beyond repair? If not, no need to close it.

**Comment by notationist17** [comment]
Frankly, I do not see myself dedicating the required time to figure out how to repair it, since I doubt anyone will go through the trouble to merge it now if they have yet to do it in the 5 months (!!!) it has been ready. 

I am a bit frustrated by this as you can probably tell, but I don't want to take it out on you @Jojo-Schmitz . So could you just tell me, what I should do next time to actually create a PR that is useful and gets merged?

**Comment by Jojo-Schmitz** [comment]
I can't tell you why it hasn't been merged yet, but I can tell you that there are much older PRs that still wait to get mergerd, and that a closed PR will never get merged.

**Comment by lasconic** [comment]
If you need a guilty guy, I'm probably the one to shoot for not having pull this PR. However I understand your frustation... Nothing more to do in order to get merge, except probably pass by once in a while to remember us to merge since it's ready. In the meantime, we did merge 100s of PRs.

**Comment by velochy** [comment]
I found an un-spoiled version of this PR branch in my other computer and created a new PR for it (#2560).

I understand you have your hands full, but having my first PR wait 5 months is not a big motivator for me to contribute more in the future. But I will try to not let that get in the way as best I can, in case I ever find something else I am capable of fixing.

**Comment by lasconic** [comment]
Thank you for your understanding.

**Pull request closed without merging**
