### PR TITLE
fix #286207: single-note dynamics: fortepianos that last longer than a segment play incorrectly

### PR DESCRIPTION
**Pull request by jthistle**
Resolves: https://musescore.org/en/node/286207

Ignore the fact it says 'hack' ;)
There's no other way of fixing this other than quite a significant refactor, unfortunately.

### CODE REVIEW

**Comment by lgmventura** [comment]
Great, @jthistle !!! Thank you! A _segment_ is the period of time between the note-on and another note-on/note-off message in the midi, right?

**Comment by jthistle** [comment]
Umm, not really. The way MuseScore works, a segment is a just a generic element that holds something that usually takes up the whole height of the staff. So, it could be a rest, a chord, a key sig etc. To explain why that is a problem here is a bit complicated, though...

**Comment by lgmventura** [comment]
Thank you for your explanation, @jthistle ! I had a look on the changes you made in the code. Now, it stores the "velocity" (CC) information in a separated variable, which is used to retrieve the velocity information lost when the current segment ends and the next one begins, breaking the loop, right?

**Comment by jthistle** [comment]
No, not really. Basically, what was happening was that for an fp, the final velocity is set when it ends. It could end outside of the segment it started in, which can lead to problems, since the next segment starts with the velocity that the previous segment started as. This creates the volume jump that you experienced. It occurs when you have a relatively short segment, for example a quaver rest in another stave, which affects how dynamics are rendered in other staves.

**Comment by lgmventura** [comment]
Oh, yeah! Now I got it! Exactly what I was experiencing – when a new segment started, the velocity of the longer fp note jumped back to the value it was when the first segment started. Now it's then ready to merge into master, isn't it?

**Comment by jthistle** [comment]
Indeed @anatoly-os ;)

**Pull request merged**
