### PR TITLE
[engraving] Removed Q_OBJECT and Q_GADGET

### PR DESCRIPTION
**Pull request by igorkorsukov**

### CODE REVIEW

**Review by handrok — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
@Jojo-Schmitz Maybe it is because of the `#include "translation.h"` in scorefile.cpp. That makes the translation unit bigger, and apparently too big for MinGW.

**Comment by igorkorsukov** [comment]
Now we can remove `#include "translation.h"` from `scorefile.cpp`, but in the future, we will need it.
I think it's better to disable the unit build for engraving because there are still very large `cpp` files

**Comment by cbjeukendrup** [comment]
Or just reduce the number of files per unit, can't we do that?

**Comment by igorkorsukov** [comment]
> Or just reduce the number of files per unit, can't we do that?

Now the number of files in the unit is a global setting, I don't want to add another setting to setup the module, and there are so many settings :)

I don't think it is necessary to globally reduce the number of files in the unit, in other modules, there are a few lines in each `cpp` file. 
There are a lot of lines of code in the engraving modules in most `cpp` files, they themselves are like units :), so I think disabling the unit build will have little effect for engraving

**Comment by Jojo-Schmitz** [comment]
See https://github.com/musescore/MuseScore/pull/11547#issuecomment-1119503836

**Pull request merged**
