### PR TITLE
fix #100416:playback panel has been redesigned

### PR DESCRIPTION
**Pull request by salilkhandelwal**
redesigned playback panel.

### CODE REVIEW

**Comment by ZackTheCardshark** [comment]
@salilkhandelwal , did you know you don't have to close one pull request, make a new branch, and a open a new pull request if you want to make changes? Just add further commits to the same branch, and the pull request will automatically update. You can also squash the commits together with [<code>git rebase</code> ](https://help.github.com/articles/about-git-rebase/). This would be preferable so, for example, we wouldn't lose the discussion that happened at https://github.com/musescore/MuseScore/pull/2453.

**Comment by ZackTheCardshark** [comment]
I think there is still some work to be done. Here's what I see:
screen shot
Notice how tiny the numbers are. That needs to be fixed.

Also, it appears you've disabled resizing the window?

**Comment by salilkhandelwal** [comment]
@ZackTheCardshark thanks for your review , yes the numbers are looking tiny , I will change it soon .  On the other hand  I am facing problems with resizing , I have tried using spacers as well but it messes up the design when we maximize it

**Comment by salilkhandelwal** [comment]
screenshot from 2016-03-21 09 36 31 , this is the old play panel but notice the empty space we get when we maximize the play panel , I was getting the same thing with the redesigned one as well .. If it is alright that the space remains , I will add the functionality to resize

**Comment by ZackTheCardshark** [comment]
Perhaps there should be a hard maximum size to keep from going too far, but you should allow the user to make the window bigger if they want to. Also, while I think this is a good default size, the old play panel could actually be made smaller. So, I would say reduce the minimum and increase the maximum.

**Comment by lasconic** [comment]
This need more work and more discussions.

**Pull request closed without merging**
