### PR TITLE
Implemented redesigned Beams page of EditStyle dialog

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #9654
Schermafbeelding 2021-11-10 om 01 02 21

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by bkunda** [comment]
Hi @cbjeukendrup!
Wonderful work, as always.
Just a couple of small points from my end:

1. The 'flatten all beams' checkbox no longer toggles correctly:
flatten-beams-doesn't-work

2. The 16th-note icons look a tad larger than I had in the Figma file (28pt). I'd prefer them to be at this size if possible, but if it's a question of uniformity with other similar buttons (e.g. with the straight flags toggle buttons), then I'd understand! 

Many thanks,
Bradley

**Comment by cbjeukendrup** [comment]
Thanks! To be honest, for those radio buttons I just copied the code from the note flags type section, where the icons are 32px. But indeed, on the Beams page they look much better at 28px.
I also noticed that the title of the Beams distance section was wrong (it said "Beam thickness" instead of "Beam distance"), so I just created a small follow-up pull request. 

The "Flatten all beams" checkbox also didn't work before. I think that this is more task for @Nick-Mazuk, who is working on all kinds of beaming problems, if I'm not mistaken.

**Comment by bkunda** [comment]
Good spot on that title discrepancy! I'm quietly ashamed I missed that one...🙄
Thanks for raising this follow-up PR 👍🏻
As for that dodgy checkbox, we'll leave it in @Nick-Mazuk's very capable hands (unless he suggests otherwise). 
Many thanks!
Bradley

**Comment by Nick-Mazuk** [comment]
Yep, I'll make sure all these options work with the new beaming code!

**Comment by Nick-Mazuk** [comment]
Once https://github.com/musescore/MuseScore/pull/9934 and https://github.com/musescore/MuseScore/pull/9937 are merged, the beams code will fully work with with these new options.

**Pull request merged**
