### PR TITLE
fix #299759: [Musicxml Export] - Bad note value export in nested tuplet

### PR DESCRIPTION
**Pull request by lvinken**
Resolves: https://musescore.org/en/node/299759

MusicXML support for nested tuplets was never implemented, mostly due to lack of popular demand. This PR adds support for export. Importing nested tuplets from MusicXML is a bit of a challenge, this has not been implemented yet. 

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by anatoly-os** [comment]
@lvinken compilation failed :(

**Comment by lvinken** [comment]
Don't understand (did a rebase / rebuild without errors), will check.

**Comment by lvinken** [comment]
Think I found it (stupid mistake, don't mix auto with std::initializer_list). Still don't know why it compiles OK using Xcode. Waiting for the build to complete.

**Comment by lvinken** [comment]
No build errors :-)

**Pull request merged**
