### PR TITLE
Penality for note spelling is incorrect for Ab (4 flats)

### PR DESCRIPTION
**Pull request by boblucas**
I'm not sure if it's intentional, so this is a question in the form a fix. It seems to me that the penalization of spellings is very odd compared Eb and Db.

### CODE REVIEW

**Comment by jthistle** [comment]
Hi Bob! Thanks for your pull request. I think @MarcSabatella should be able to answer your question.

By the way, to have your PR accepted, you need to have first [signed the CLA](https://musescore.org/cla). Just comment here what name you have signed it under once that's done.

**Comment by boblucas** [comment]
> Hi Bob! Thanks for your pull request. I think @MarcSabatella should be able to answer your question.
> 
> By the way, to have your PR accepted, you need to have first [signed the CLA](https://musescore.org/cla). Just comment here what name you have signed it under once that's done.

Bob Lucassen

**Comment by jthistle** [comment]
oh wow, that was a while ago. Didn't notice it on a first look through :)

**Comment by MarcSabatella** [comment]
Sorry, I know nothing about this code.  I guess it's used for guessing spelling on MIDI import, or Tool / Respell?

**Comment by boblucas** [comment]
That is correct, there is a reference to a paper that describes the algorithm, this is about penalizing enharmonic spellings where more simple ones are available. I believe the original code is contrary to the paper. And there is no comment or other explanation

**Comment by boblucas** [comment]
@MarcSabatella Is there somebody who does know more about this code and can review this change?

**Comment by MarcSabatella** [comment]
Not offhand,. I'd suggest just browsing the blame/history on GitHub to see who has worked on that area of the code before.

**Comment by boblucas** [comment]
@MarcSabatella , Nobody has made a non-trivial change to the spelling algorithm for the past 7 years at least. Is there someway I could document the change so that somebody like you (or somebody else) could be convinced that this is an ok thing to merge?

**Comment by MarcSabatella** [comment]
The usual process would be, first submit a bug report that clearly demontrates the problem you are trying to solve, and then ideally add an automated test to your PR that proves your code fixes it.  Then add comments to the source explaining the code / data a bit better, and some explanation fo the changes themselves here.

**Comment by boblucas** [comment]
That's fair, but that's too much effort for me. It's  just something I came across while having to grok this code working on something else. I don't suspect many people will notice if its been there for a decade.

**Comment by Jojo-Schmitz** [comment]
A pity you closed it.

**Pull request closed without merging**
