### PR TITLE
banjo tab fifth string fret number issues

### PR DESCRIPTION
**Pull request by laturetab**
Resolves: #316896

Banjo 5th string starts on 5th fret. Valid fret numbers are 0,6,7,8... 
Musescore currently uses 0,1,2,3... 

- [ x] I signed [CLA](https://musescore.org/en/cla)
- [ x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [ x] I made sure the code compiles on my machine
- [ x] I made sure there are no unnecessary changes in the code
- [ x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
That 1st commit should not be there

**Comment by laturetab** [comment]
How do I get rid of it? I have no idea where it came from

**Comment by laturetab** [comment]
how do I get rid

**Comment by cbjeukendrup** [comment]
@laturetab It seems you're still having some trouble with rebasing. This is what you could do:

- Make sure that you are on the 316896-banjofifth branch
- `git rebase -i 3.x`
- Then a file opens with a list of commits. Delete the line about the version number change. Keep the line about _your_ commit. 
- Save and close the file. Git will manage the rebase. 
- Use `git log` to check if it was successful. 
- Finally, use `git push -f` to push the changes to GitHub. _Don't_ create a new PR: this existing one will be updated. 

If you need more help, feel free to join the [MuseScore Developers Chat](https://t.me/musescoreeditorchat) and/or send me a private message on Telegram.

**Comment by laturetab** [comment]
I believe it's ready to go. I got rid of the 2 strange files (my_first_score.mscx and cmakelists.txt) by editing them on github and removing the change. It seemed to work. I had a compile problem on mac/linux (not windows) - added a constructor to initialize string class the standard way - this also worked.

Let me know what's next

**Comment by Jojo-Schmitz** [comment]
Squash the commits into just one

**Comment by laturetab** [comment]
I attempted a squash and it failed horribly. I ended up redoing everything
and making a new PR. This time I deleted everything, including my musescore
fork on github and started over. I ran into no problems. Thanks for your
help with this.

**Comment by Jojo-Schmitz** [comment]
You still have that foreign commeit from 3.6.1 in there. And still multiple commits

**Comment by Jojo-Schmitz** [comment]
Better close this one, that other looks better

**Pull request closed without merging**
