### PR TITLE
Port infer dynamics

### PR DESCRIPTION
**Pull request by miiizen**
The first commit ports: #8347

The second commit creates a cresc/decresc line when the words 'cresc' or decresc are read.  This line is extended until the next dynamic is found and made invisible.  
image

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
A rebase is needed

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
What the heckl is that src/importexport/musicxml/tests/data/testInferredCrescLines.xml ? It seems to be binary junk?

**Comment by Jojo-Schmitz** [comment]
Ah: it is UTF16

**Comment by cbjeukendrup** [comment]
> it is UTF16-LE. Intentional?

That's what Sibelius tends to export... so yes, that needs to be tested.

**Comment by Jojo-Schmitz** [comment]
This PR too is affected by the lack of unit tests running, #22370

**Pull request merged**
