### PR TITLE
Fix GH#15890: Lyrics elision shortcut not working

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: #15890

Works on Windows (11) and a German QWERTZ keyboard, needs to get tested on other setups

### CODE REVIEW

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
On QWERTY, Windows 11 the shortcut works as Ctr+alt+Shift+-

In MS3 the shortcut works without Shift

**Comment by Jojo-Schmitz** [comment]
I found none. Esp. I didn't find the place where Ctrl + Alt + - gets caught, that is the bad news

**Comment by zacjansheski** [comment]
We can go ahead and merge this and fix that later (Shortcut working with shift is better than not working at all)

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/15890 FIXED

**Comment by Jojo-Schmitz** [comment]
Esp. as on QWERZT and QWERTY - and _ are on one key (although at a different position on the keyboard)
What about ARERTY?

**Comment by Jojo-Schmitz** [comment]
Still I'd rather know who or what 'eats' the Ctrl + Alt + -

**Pull request merged**
