### PR TITLE
fix #279259: chord symbol spacing

### PR DESCRIPTION
**Pull request by MarcSabatella**
See https://musescore.org/en/node/279259.  Prior to the initial 3.0, we managed to get chord symbols to space themselves out on adjacent chordrests, by adding them to the chordrest shape.  But this still allowed collisions between chord symbols that were not on adjacent chordrests, as well as chord symbols not attached to chordrests at all.

It seems that without realizing it, the non-adjacent-chordrest problem was mostly fixed with subsequent changes intended for lyrics.  I believe specifically this commit: https://github.com/musescore/MuseScore/commit/54eab63a7f6027b183d987efef2cb435b799490a.  There are some temporary layout glitches (see below), but it does basically work.

So, all we need is to handle the case of chord symbols not attached to chordrests.  As I worked on PR #4769 to address another issue, I realized we could accomplish this quite simple, by adding the chord symbol to the segment shape.

This PR accomplishes that with the one-line change to segment.cpp.  The rest is addressing the temporary layout glitches that are already present with spacing of chord symbols on non-adjacent chordrests.  The bottom line was confusion over whether to layout the chord symbol using the "rendered" text or using the plain text displayed while editing - these give different widths.  Fixing this meant finally refactoring out the bbox() calculation from Harmony::layout() into Harmony::layout1(), which we had kind of known was the right thing to do anyhow.

I've tested and it all seems to work well enough, and doesn't break any of the things the last set of changes to this area of code were fixing.

@dmitrio95 & @mattmcclinch I would value your opinions especially since you've worked on some of this code recently.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Pushed a small change to make sure we relayout on endEdit() even if no changes to the text (otherwise see that same glitch to to the difference between width while editing and width on final render).

**Comment by MarcSabatella** [comment]
Well, shoot - I just discovered that including slurs in the segment shape messes up slur layout, because slurs are trying to avoid segment shapes, and yet chord symbols don't *really* get laid out until after slurs.

But the rest of the changes here are still good, they clean up some pretty glitchy behavior when editing chord symbols with Jazz style selected.  I'll play with this some more and see if I find another way to address the problem of chord symbols with no chordrest to add horizontal space to.  Hmm, maybe it works to just add horizontal space to the segment shape...

**Comment by MarcSabatella** [comment]
The good news is, adding horizontal space does work, and on reflection it the right approach anyhow.  The code involved overlaps the code for PR #4769, but I think I will be able update both PR's to be consistent enough that either could be merged independently.

**Comment by MarcSabatella** [comment]
Updated to use the addHorizontalSpacing() approach, and to structure the code in that section the way as in PR #4769 (which I also updated).  The lines involved are in close enugh proximity that git may still flag a merge conflict, but if so it will a trivial one to resolve.

Here's the result of the changes, which is practically indistinguishable from 2.3.2:

image

It's actually better than 2.3.2 in that the spacing is updated correctly while you are editing the chord symbol.  That was glitchy in 2.3.2 when using Jazz style, just as it is in 3.0.4.

One thing I *didn't* do in this PR is address the issue of chord symbols overlapping the barline.  In 2.3.2, we put extra space as needed between the last note in the measure and the barline to reduce the likelihood of a chord symbol at the end of a measure colliding with one at the beginning of the next.  In 3.0 we no longer do that, meaning if a chord symbol overlaps the barline, you potentialy get a collision (which autoplace dutifully resolves by moving the second chord up, so it's not that bad).  No one was really *happy* with how we handled this in 2.x, so I'm not losing sleep over this change.  But it's something worth looking at some day.

**Comment by anatoly-os** [comment]
A couple of vtests won't harm ;)

Also, rebase is needed. There is possible collision with just merged #4769

**Comment by MarcSabatella** [comment]
OK, I'm on it.

**Comment by MarcSabatella** [comment]
Done.

**Pull request merged**
