### PR TITLE
Fix #303864: Support command-line building using Visual Studio 2019

### PR DESCRIPTION
**Pull request by Spire42**
Resolves: [#303864](https://musescore.org/en/node/303864)

Enhanced the `msvc_build.bat` batch file to support Visual Studio 2019 (in addition to VS2017) and to automatically detect the highest supported installed version of Visual Studio and use it.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by anatoly-os** [comment]
Works for me! Thanks @Spire42. So, am I supposed to merge this one first and #5921 after that?

**Comment by Spire42** [comment]
> Works for me! Thanks @Spire42. So, am I supposed to merge this one first and #5921 after that?

Yes, merge this one first, then wait for @Jojo-Schmitz to remove the old version of `msvc_build.bat` from his PR. When he gives the go signal, you can test his PR and merge.

**Comment by Jojo-Schmitz** [comment]
I've modified #5921 so they can now get merged in any order

**Comment by Jojo-Schmitz** [comment]
OK, so now  #5921 ?  ;-)

**Pull request merged**
