### PR TITLE
Fix #20853: <sound> tag tempo in <measure> for xml import (redo of #2263)

### LINKED ISSUE #20853: Musescore Ask For Help
### Your idea

Can we change the Ask For Help link in musescore from the forum to point to GitHub?

### Problem to be solved

I've been reporting and researching bugs and fixes in the Forum and just discovered GitHub is the authority now.  All of us that missed the line in the manual are still using the forum.  Thanks

### Prior art

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by velochy**
Re-created the PR I closed from my old account notationist17 from my new account.

### CODE REVIEW

**Comment by velochy** [comment]
Continuation of https://github.com/musescore/MuseScore/pull/2263#issuecomment-211985863

**Comment by Jojo-Schmitz** [comment]
The travis fail is not your fault, it fails since d42f0e1. Should be fixed in 4ae2df6, so should pass after you rebased the PR

**Comment by Jojo-Schmitz** [comment]
The travis fail is not your fault, it fails since d42f0e1. Should be fixed in 4ae2df6, so should pass after you rebased the PR.
mtest apparently broke again with  c1195e8  ...

Once that is fixed you'd need to get rid of thet merge commit and squash the remaining 3 commits into one.
It would help if there were a corresponding issue in the issue tracker, and if then the commit message would mention that (as "fix #nnnnn: ...").

**Comment by Jojo-Schmitz** [comment]
mtest is fixed again.

**Comment by lasconic** [comment]
This is related to https://musescore.org/en/node/20853 
The current PR has several issues.
1/ It has some weird commits and need requash 
2/ It creates empty tempo and we should do that or the user cannot remove them
3/ I believe the test case should use mscx or even a roundtrip musicxml (I think I advised the current approach on IRC... sorry for that...).

I will take a closer look and sort it out.

**Comment by lasconic** [comment]
First job was to re enabled the MusicXML tests. Done in #2608

**Comment by lasconic** [comment]
See #2609

**Pull request closed without merging**
