### PR TITLE
Assigning channels

### PR DESCRIPTION
**Pull request by Igevorse**
I can resolve merge conflicts only after merging PR https://github.com/musescore/MuseScore/pull/1171
Please don't merge this commit now. I'll test it hard. Hope, other people will help me.
Assigning channels to staves gives better control over connecting to external synthesizers and saving midi/musicxml files.
The key object here is score->midiMapping that contains our mapping (channel (is Channel*) - > midi port, midi channel).
Instruments can have the same midi port/channel, but anyway they have different channels (Channel* ). That's why mapping has almost no effect on the internal synth (fluid.cpp does not use score->midiMapping).
Also since we can choose ports, there is no need in "Ports: " spinbox in Preferences->I/O. Now we update number of JACK/ALSA MIDI ports automatically when MuseScore does really need it.
Volume, pan, etc. controls (in mixer window) of the Instruments with the same ports and channel are synced, because we can't have different global parameters for a one midi channel. (Ok, we can by sending messages about global volume,pan, etc before every note, but external sequencer can die :(. )
More information about how it works: 
http://igevorse.lited.net/p16.html
http://igevorse.lited.net/p17.html

### CODE REVIEW

**Comment by daeavelwyn** [comment]
Hi, musescore is now in beta 2 state and I wonder if there are some chances this PR will be in the next release ?

**Comment by Igevorse** [comment]
@daeavelwyn 
Hi, there were a lot of changes in MuseScore, so unfortunately, I have to rewrite some places of code (it's not enough to remove merge conflicts). It will take some time, and since te date of release of MuseScore 2.0 is still not set, there are chances this PR will be in the next release.

**Comment by daeavelwyn** [comment]
@Igevorse ok, and do you need help for testing ? As i'm waiting for this option that will let me use musescore as a master piece of my workflow, I would be glade to help :)

**Comment by Igevorse** [comment]
@daeavelwyn yes, the PR should be tested well before merging. It would be cool if you could help with testing.

**Comment by daeavelwyn** [comment]
@Igevorse could you explain me how to merge your work in the last musescore code as I could benefit from last musescore code AND from your work ?

**Comment by Igevorse** [comment]
@daeavelwyn it's impossible for now.
When new PR is released, you will need just to switch to my branch to get all benefits.

**Pull request closed without merging**
