### PR TITLE
Fix #16878: Enforce same lyric alignment stem flip

### LINKED ISSUE #16878: Alignment of left-justified lyrics on whole notes different depending on stem direction
### Issue type

Engraving bug

### Bug description

When a lyric starts on a whole note and is left-justified on it (as it would be for a melisma), the alignment is different according to the stem direction of the chord. There should be no difference.

image
Here, the first note is upstemmed and the second note is downstemmed. (I made the lyrics much smaller than usual to make the difference more obvious.)

It looks like on the second note the lyric is aligned with the left of the bounding box of the notehead. This looks better than the first note to me; in any case, they should both be the same, as changing the stem direction of the note has no other graphical consequences in this case.

### MuseScore Version

OS: Artix Linux, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-230760632, revision: github-musescore-musescore-fdc7952

### Regression

No.

### Operating system

Linux, Windows 11

### PR DESCRIPTION
**Pull request by MengLinMaker**
Resolves: https://github.com/musescore/MuseScore/issues/16878

Bug fix for left and right lyric alignment changes during notehead stem flips.

This solution assumes that lyrics would be attached to ChordRest with normal whole, half, quarter... note.

Left alignment is fixed about a half note width from the Left:
[Recording_16_05_2023_23_07_44.webm](https://github.com/musescore/MuseScore/assets/39476147/fcba4df0-c7c1-49d2-8a96-4c7e1fb4d356)

The solution also applies to right alignment:
[Recording_16_05_2023_23_10_29.webm](https://github.com/musescore/MuseScore/assets/39476147/b1afacdb-018f-49dd-a5bc-d295015a1dd7)

Middle alignment works as usual:
[Recording_16_05_2023_23_16_39.webm](https://github.com/musescore/MuseScore/assets/39476147/42405db7-a1e7-43a8-9849-c61305982fb5)

Note:
Not sure how to get rid of all the previous commits.
Unsure what unit test or vtest is relevant - how do you test UI end to end?

- [X] I signed the [CLA](https://musescore.org/en/cla)
- [X] The title of the PR describes the problem it addresses
- [X] Each commit's message describes its purpose and effects, and references the issue it resolves
- [X] If changes are extensive, there is a sequence of easily reviewable commits
- [X] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [X] There are no unnecessary changes
- [X] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by oktophonie** [comment]
@MengLinMaker Could you bear to rebase this, and also fix the utests and codestyle checks? :)

**Comment by cbjeukendrup** [comment]
The code style check wants you to remove some trailing whitespace (see the "Details" link, where it displays a diff of what you need to change). This check only checks the style of the code itself, but does not check the "commit style". 

The Azure failure was indeed a temporary external failure. When you rebase and force-push, the checks will be performed again, and then they should succeed.

**Comment by MengLinMaker** [comment]
@cbjeukendrup that should fix the code style check.
Waiting for merge.

**Comment by cbjeukendrup** [comment]
@MengLinMaker We still can't merge it because apparently there are still conflicts. You should rebase on top of the latest master:
```
git pull --rebase upstream master
```
And once you have solved the conflicts, do:
```
git push -f
```

**Comment by Jojo-Schmitz** [comment]
Why??

**Comment by MengLinMaker** [comment]
Did I mess something up?
Hmm

**Comment by Jojo-Schmitz** [comment]
Yes, you closed the PR...
Simply reopen it

**Comment by MengLinMaker** [comment]
How do I do that?

**Comment by cbjeukendrup** [comment]
You somehow dropped your commit. To get it back, make sure you have checked out your branch, and do `git reset --hard dd4f99e`. Then try rebasing again, hopefully without dropping the commit. You might want to read some tutorials about how to fix rebase conflicts first.

**Comment by MengLinMaker** [comment]
Hang on a sec, I just opened another pull request #17840.
Not sure how the whole rebase thing works.
I seem to make a much more mess with it.

**Pull request closed without merging**
