### PR TITLE
Inspector facelift

### PR DESCRIPTION
**Pull request by IsaacWeiss**
Various adjustments to alignment and spacing (in many cases to allow for greater compactness), along with some changes to appearance of buttons and horizontal lines, and working on adding more automatic showing/hiding of options based on what other options are checked.

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
Sample before and after comparison (both at minimum width):
screen shot 2018-12-26 at 12 30 23 am screen shot 2019-01-10 at 10 53 04 pm

**Comment by IsaacWeiss** [comment]
Also, when absurdly widened:
screen shot 2019-01-10 at 10 56 40 pm
screen shot 2019-01-10 at 10 56 07 pm

**Comment by anatoly-os** [comment]
Still WIP?

**Comment by IsaacWeiss** [comment]
Yes, a bunch more UI files to do (some have been done but not pushed), but now I know pretty much how to get what I want. Any target date to get into the next release?

**Comment by anatoly-os** [comment]
Next update is about in a week...

**Comment by anatoly-os** [comment]
@IsaacWeiss Hi. This PR is still in WIP state, but Musescore users will be very happy to see this PR merged :)

**Comment by IsaacWeiss** [comment]
Next week. :) Today I literally cannot think 
screen shot 2019-03-07 at 9 58 36 am

**Comment by Jojo-Schmitz** [comment]
rebase needed...

**Comment by IsaacWeiss** [comment]
Next week (Monday) I'm on it.

**Comment by IsaacWeiss** [comment]
All done. Another pass to fix tab order should happen at some point, but all the *visual* improvements are done.

I should mention that I have added automatically hiding or disabling (which one generally depends on how much of a need there was to save space) certain options that depend on other options being enabled, and also that inspector_tuplet.ui was so messed up I'm surprised it wasn't noticed before.

**Comment by IsaacWeiss** [comment]
The big increase in number of lines is because, in choosing what to allow to stretch and what not to, I consistently had to change the parameters of certain elements from their default (and thus unwritten) settings.

**Comment by IsaacWeiss** [comment]
Regardless, WIP label can be removed and I consider this ready to merge.

**Comment by IsaacWeiss** [comment]
Currently doing that pass for tab order. Limitation seems to be that the custom widgets are skipped, but that's the case in the current release as well, so I'll leave that for somebody else.

**Comment by IsaacWeiss** [comment]
Done

**Comment by MarcSabatella** [comment]
Wonderful, the tab order issue has been bugging me to no end!

Meanwhile, there is also #4672 which will likely conflict with this, but to me this current PR is far more important to get in first.

**Comment by IsaacWeiss** [comment]
@anatoly-os any desire for the tab order commit to be squashed with the rest?

**Comment by anatoly-os** [comment]
@IsaacWeiss no, it's ok. Leaving unrelated changes in different commits is a good thing to do.

**Comment by anatoly-os** [comment]
@IsaacWeiss thank you for the amazing work you did! The changes are great and we are one step closer to the better interface design :)

**Comment by Jojo-Schmitz** [comment]
Hmm, the Text Inspector became wider than before, the Note Inspector higher, neither for good reasons IMHO, width being more of an issue than hight I believe

**Comment by MarcSabatella** [comment]
I always set my Inspector to not need scrollbars for the widest element (why can't we figure this out by default, BTW?), so the increase in width for the text is a serious regression to me.  What confuses me is the image in the first comment shows the text inspector getting narrower, as I would have hoped.  So I wonder what happened?

**Comment by IsaacWeiss** [comment]
> the Text Inspector became wider than before
I'm guessing that's because #4739 kept the "Follow staff size" (then "Size follows 'staff space' setting") checkbox on a separate row, and I moved it up a row (with the deletion of the "Font face" label) to be more compact vertically.

> the Note Inspector higher
This should not be the case. Vertical spacing was slightly increased, but (1) the "Line" field was moved to be on the same row as "Fix to line", (2) three rows now disappear when "Play" is unchecked, and (3) the Chord Inspector (which is also present) is definitely less tall.

**Comment by IsaacWeiss** [comment]
Ah, I see, the eight "Select" buttons are farther away. I'll check into it.

**Comment by IsaacWeiss** [comment]
Got it, a spacer's sizeHint was lost.

**Comment by Jojo-Schmitz** [comment]
Exactly. And the Text inspector seems to have become wider because of the bold/italic/underline being in front of the align buttons

**Comment by IsaacWeiss** [comment]
> Exactly. And the Text inspector seems to have become wider because of the bold/italic/underline being in front of the align buttons

Ah, probably. It's still better than before, though, and without labels it's guaranteed not to get worse in translation. I don't like the big waste of empty space if they're placed vertically, as in the original screenshot (imagine without the "Font style:" label)...

**Comment by MarcSabatella** [comment]
Maybe I'm missing something, but wider = worse to me, nothing else actually matters nearly as much.  There must be a way to get the best of both?

**Comment by Jojo-Schmitz** [comment]
@MarcSabatella No, IMHO you're right, width is way more important than height, and the text inspec tpor needed to be come narrower, at least as narrow as it was before the change, definitly not wider

**Comment by IsaacWeiss** [comment]
Regarding the Text Inspector width, I figured out a reasonable solution that I'll make a PR for later.

**Comment by IsaacWeiss** [comment]
#4835 allows the Text Inspector to become narrower again.

**Pull request merged**
