### PR TITLE
reduce nesting levels in `ScoreView::cmd(const char* s)`

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
to work around a limitation of MSVC, see  #5577

### CODE REVIEW

**Comment by mattmcclinch** [comment]
This gives us room for a few more commands, but it leaves us too close to the limit for my liking. I do not see this as a long term solution. It would probably be better to restructure this function, using `Score::cmd()` as an example. See https://github.com/musescore/MuseScore/compare/master...mattmcclinch:restructure-scoreview-cmd for my solution.

**Comment by Jojo-Schmitz** [comment]
Yes, definitely more a short term solution

**Comment by Jojo-Schmitz** [comment]
Maybe something for 3.4, with you solution being something for 3.5?

**Comment by Howard-C** [comment]
That solution doesn't do any harm, why not for 3.4 ;-)

**Comment by Jojo-Schmitz** [comment]
Because it seems a quite complex change, not sure we want to have this in after the Beta for 3.4 is out already

**Comment by Howard-C** [comment]
And that's why we have conflicts more than there need to be. I can't imagine how this kind of restructures can lead to potential problems.

**Comment by jeetee** [comment]
Use #5584 instead of this one.
Although it is a Q&D fix, it's too Dirty for my taste. Leaving off block scope for single line conditional bodies is quite the error prone code style and a no-go in my (embedded influenced) book.

**Comment by Howard-C** [comment]
Error? Isn't it one of MuseScore's coding rules?

**Comment by Jojo-Schmitz** [comment]
When using a decent IDE (which is doing the indentation automagically) this won't be error prone and also ommitting braces for single statements is in the MuseScore coding style.
I do agree however, thast @mattmcclinch's approach in #5584 is much cleaner. But also a much bigger change, so up to @dmitrio95 and/or @anatoly-os to decide whether we want this for 3.4.

**Comment by jeetee** [comment]
I acknowledge its in the coding rules, see Telegram for why it shouldn't be imho ;)

**Comment by Jojo-Schmitz** [comment]
#5577 has meanwhile been changed to not hit that nesting limit, so this PR here probably won't be needed at all.

**Comment by Howard-C** [comment]
So why not close it?

**Comment by Jojo-Schmitz** [comment]
Because a decision of this vs. #5584 is still pending

**Comment by mattmcclinch** [comment]
Have you verified that this achieves the intended result? Upon examination it does not look like this accomplishes anything at all.

**Comment by Jojo-Schmitz** [comment]
I did, together with the previous changes from #5577, and it worked

**Comment by Jojo-Schmitz** [comment]
I did, together with the previous changes from #5577, and it worked

**Comment by Howard-C** [comment]
I think #5584 will inevitably be the better choice, given that this PR "does not accomplish anything at all" (besides removing braces and spaces) but #5584 really changes code structure.

**Comment by Jojo-Schmitz** [comment]
No, you're right, I tested again and it indeed doesn't buy a single adddition slot, There are 2 slots left, no more, before and after my change.

**Pull request closed without merging**
