### PR TITLE
run_lupdate.sh: don't forget .h, .mm and, most notably, .ui files

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: https://discord.com/channels/818804595450445834/818852942882275379/997602246252564491

That brings the total number of strings from 3660 to 4819...

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Unfortunately, there is no way to set the context explicitly for .ui files. I'm not planning to spend much time going through these strings from .ui files, since they are unchanged since MU3, and the .ui files will be removed in the future anyway.

**Review by igorkorsukov — APPROVED** [review]

**Comment by igorkorsukov** [comment]
> By the way, @igorkorsukov, since these strings and their contexts should largely be exactly the same as in MU3, is there any chance that we can do some Transifex magic to restore these translations from MU3? That would save the translators tons of work... or will Transifex still somehow remember the old translations, once we put back these strings?

I think the translation will be keeped if the context doesn't change.

**Comment by cbjeukendrup** [comment]
That sounds hopeful! I'll merge this PR then. Is it okay if I run `CI_Run_lupdate_to_tx` after that?

**Comment by igorkorsukov** [comment]
> That sounds hopeful! I'll merge this PR then. Is it okay if I run `CI_Run_lupdate_to_tx` after that?

Yes, you can run lupdate to tx

**Pull request merged**
