### PR TITLE
Trivial musicxml fixes 2 master

### PR DESCRIPTION
**Pull request by lvinken**
Resolves:
https://musescore.org/en/node/298080
https://musescore.org/en/node/299492

Improve MusicXML export to facilitate easier braille transcription.
Master equivalent to pull request 6485 for 3.x ("Trivial musicxml fixes 2 3.x")

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/WorkflowAndGuidelines/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by lvinken** [comment]
Made a mistake in formatting one of the files, will fix this and push -f.

**Comment by lvinken** [comment]
Done. The remaining issue is in a file i do not own and did not touch, I am not going to change that.

**Comment by Jojo-Schmitz** [comment]
A rebase should fix the build issues

**Comment by lvinken** [comment]
Rebase done, all OK. Thanks, Jojo.

**Review by oktophonie — APPROVED** [review]

**Pull request merged**
