### PR TITLE
fix #123436: continues barlines

### PR DESCRIPTION
**Pull request by MichaelFroelich**
Fixes bug 123436 in which barlines reverted to the normal type for newly added instruments

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
why 3 commints? And the commit message should start with `fix #123436`

**Comment by MichaelFroelich** [comment]
> why 3 commits? And the commit message should start with `fix #123436`

I created the PR a little early, that's all. All other commits will have fix #123436

**Comment by jeetee** [comment]
@MichaelFroelich see http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html for help on how to squash your 3 commits into 1 (looking at the total changes, a single commit would be preferred here).
Also give the new commit a message that starts with "fix #123436". The PR title is nice, but the commit hook that automatically marks the issue as fixed in our issue tracker looks to commit messages only.

**Comment by Jojo-Schmitz** [comment]
the musicxml mtests on Travis CI are not happy

**Comment by MichaelFroelich** [comment]
I think it's because of the point I branched from, I'll rebase/merge etc around when I squash the commits

**Pull request closed without merging**
