### PR TITLE
Update templates and Getting_Started.mscz

### PR DESCRIPTION
**Pull request by ZackTheCardshark**
Templates organized and cleaned up, a few new ones added, templates CMakeLists.txt cleaned up, Getting Started score updated with corrections and new info

### CODE REVIEW

**Comment by lasconic** [comment]
Looks like the new templates are not created using mscore --template-mode 
So they have pagelayout information A4 or Letter hardcoded. The ones that should be A4 or Letter depending on the country should be opened and resave with mscore --template-mode

**Comment by ZackTheCardshark** [comment]
Template mode—I never knew about that. Okay. Is that two hyphens for "--template-mode"?

As to the Band category, the idea is that other band templates, such as brass band and marching band, will be added in the future, but establishing the category in the first place (with Concert Band as the most essential) was a priority for me. You can see the discussion that led into this at http://musescore.org/en/node/53891.

**Comment by ZackTheCardshark** [comment]
In case it's not obvious (because I didn't add a description to it), commit 20c8f8f has been added with the templates saved in template mode. I believe that makes everything ready to go.

**Comment by lasconic** [comment]
Thanks for the heads up. 
As you can see if you go here https://github.com/musescore/MuseScore/pull/2121/commits and click on your name, github can't recognize you. If you want to make sure that all your commits are linked to your name, you will need to setup your email address or github private one. See https://help.github.com/articles/setting-your-email-in-git/

If I remember correctly you are using the Mac github client right? So you can't squash commits together?
Would you mind if I do it before pushing them? Not sure if I can keep the authorship of the changes though.

**Comment by ZackTheCardshark** [comment]
It seems to work fine:
git
And I did as Thomas recommended at https://github.com/musescore/MuseScore/pull/2111—though, as I said, those are not actually email addresses of mine. My own primary email is also set up, though.

I am using the GitHub application for Mac, yes, but I'm entirely learning this by ear, and I haven't figured out how to squash commits together. Do whatever makes it easier to merge.

**Comment by lasconic** [comment]
Merged 2ab95b0

**Pull request closed without merging**
