### PR TITLE
fix macosx build on travis-ci

### PR DESCRIPTION
**Pull request by lasconic**

### CODE REVIEW

**Comment by AntonioBL** [comment]
I think I maybe found how to make the builds work again.
See:
https://github.com/AntonioBL/MuseScore/commits/fix-travis-macos
and successful Travis log:
https://travis-ci.org/AntonioBL/MuseScore/jobs/165192585
Maybe just using `rvm --default use 2.1.5` is enough instead of uninstalling 2.0.0.

**Comment by AntonioBL** [comment]
Apparently, it works only when uninstalling ruby 2.0.0, since in that case it is no more finding "psych", it outputs this to the console (seen also in the above link):
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/yaml.rb:4:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/xcpretty-0.2.3/lib/xcpretty/syntax.rb:5: warning: already initialized constant Rouge
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rouge-1.10.1/lib/rouge.rb:7: warning: previous definition of Rouge was here
```
I tried with reinstalling yaml with (deprecated) `rvm pgk` and also to install psych (`gem install psych`), but nothing apparently worked.
See logs for the commits of https://github.com/AntonioBL/MuseScore/commits/fix-travis-macos

**Comment by lasconic** [comment]
Ok, then let's do it. I will cleanup this PR and merge it. Thank you for the research.
Any news on the Windows side?

**Comment by AntonioBL** [comment]
As you have seen, an Appveyor build substantially works, but I am not satisfied because it almost reaches the time limit even after patching gcc for precompiled headers, and tests cannot be run.
In the last weeks I was experimenting with mxe (http://mxe.cc) on Ubuntu 14.04 (available on Travis) for cross-compilation.
An example: https://github.com/zer0main/battleship/blob/master/build/windows/requirements.sh
Unfortunately, the precompiled builds have only Qt 5.5.1.
I thus built mxe from github source with "posix" on, shared libraries; Qt version is 5.7. It worked and with some adjustments I was also able to cross-compile MuseScore 8similarly to the msys compilation). The compilation time is definitely smaller than under Windows native. I also managed to have the tests run (at the moment they do not compile under Windows or cross-compilation because of a linking order problem in poppler dependency of one of the tests).
I am trying to understand what could be the best thing to do to port everything to Travis. maybe the best is just to zip the mxe folder and upload in the cloud, then download and unzip to the proper folder and launch the scripts. I saw that Travis is counting time limit per single job and not per build.
What do you think?

**Comment by lasconic** [comment]
It's a possible solution but how do we handle the packaging?

**Comment by AntonioBL** [comment]
Well, actually I was not yet able to make it work under Windows, to my shame.
Maybe in cross-compile WiX Toolset could be run under wine: https://appdb.winehq.org/objectManager.php?sClass=application&iId=9522 ?

**Pull request merged**
