### PR TITLE
Do not update Inspector if not visible.

### PR DESCRIPTION
**Pull request by riban-bw**
Reduces delay / lag of selecting an element.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
You'd need to sign the [CLA](http://musescore.org/cla)

**Comment by lasconic** [comment]
Hi Riban,
Thank you for implementing this simple trick! It will indeed speed up edition.
As Jojo suggested, I need you to sign the MuseScore CLA https://musescore.org/cla in order to pull your code.

**Comment by lasconic** [comment]
Thanks for signing the CLA.

**Comment by lasconic** [comment]
And merged! Thank you contribution and congrats for your first commit on MuseScore. Always up for a chat on #musescore on freenode.net if you need help contributing.

**Comment by thomasbonte** [comment]
Great patch @riban-bw!

**Pull request merged**
