### PR TITLE
test shamisen font changes

### PR DESCRIPTION
**Pull request by lasconic**
Just a test to give Arcandius a binary to test with. https://musescore.org/en/node/270063

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Would it harm to have this in 2.2?

**Comment by lasconic** [comment]
I don't like changing fonts at the last minute, so many bad things can happen ...

**Comment by mgavioli** [comment]
About this new feature, please see [this comment of mines](https://musescore.org/en/node/270063#comment-825413) on the forum.

**Comment by lasconic** [comment]
OK. I will comment there. But to sum it up, don't worry. This is an experiment so Arcandius understand how far guitar tablature is from shamisen tablature.

**Comment by Arcandius** [comment]
My actual version files:
[MusescoreShamisen0.6.zip](https://github.com/musescore/MuseScore/files/1887167/MusescoreShamisen0.6.zip)

**Comment by lasconic** [comment]
See https://github.com/musescore/MuseScore/pull/3632

**Pull request closed without merging**
