### PR TITLE
44071 44081 template issue

### PR DESCRIPTION
**Pull request by alcinos**
Fix http://musescore.org/en/node/44071 and http://musescore.org/en/node/44081 + some minor improvements

### CODE REVIEW

**Comment by thomasbonte** [comment]
Hey alcinos, before we can consider merging your pull request, we kindly ask you to sign the MuseScore CLA at http://musescore.org/en/cla . If you have questions, don't hesitate to ask.

**Comment by thomasbonte** [comment]
Thanks for signing the CLA alcinos.

**Comment by alcinos** [comment]
I thought that signing it wasn't required for such small contributions, but anyways I've done it. However, I don't get why the Travis build is failing (looks like a timeout of the compilation process…)

**Comment by thomasbonte** [comment]
Without looking at it, it may fail because the Travis server doesn't have enough resources and therefore it times out. This typically happens on highly trafficked days.

**Comment by alcinos** [comment]
Okay. I modified a bit the code to handle the case where the folders set in preference are empty, or don't contain any valid templates

**Pull request merged**
