### PR TITLE
Fix #74536 - MScoreText: dynamics kerning, ottava glyphs, clean-up

### PR DESCRIPTION
**Pull request by mgavioli**
__References__:
dynamics kerning: https://musescore.org/en/node/74536
ottava glyphs: https://musescore.org/en/node/68271

Fixes:
- __Completed__ kerning of __dynamics__ glyphs, for a total of 13 kerning pairs, as many as in the original symbol font.
- __Added__ the glyphs in the SMuFL ranges U+E510-E51F (ottava) and U+EC90-EC98 (supplemental ottava) on reqeust by @lasconic .
- __Cleaned__ all glyphs of the MScoreText font, correcting a few wrong outline directions, adding all missing extrema (about two hundreds glyphs) and all-non integral coordinates. The exceptions being the three glyphs U+E651, U+E652, U+E655 (pedal 'P', pedal 'e', pedal 'star') which are possibly too complex/small to observe all the guide lines.

Test on kerning are welcome: this font kerns correctly on my Linux Mint 17.1 (Qt 5.3) system, while the previous version did not kern at all. Are we still fighting platform-dependent kerning issues?

### CODE REVIEW

**Comment by lasconic** [comment]
Kern correctly on Mac OSX 10.10.5, with Qt 5.4. Test on Windows in a few hours.

**Comment by mgavioli** [comment]
I forgot to mention: ottava glyphs are borrowed from the same URW Century Schoolbook L font used for this purpose by  Lilypond, scaled to be slightly smaller than the time signature digits, as Bravura glyphs are.

**Comment by MarcSabatella** [comment]
FWIW, it seems to kern fine on my Ubuntu system.  I tried all the dynamics on the palette and they all look good.  But I don't understand why the previous version doesn't for you - the "ff" fix at least made a few days ago worked as expected for me.

**Comment by MarcSabatella** [comment]
The ottav glyphs look pretty small at the default size, BTW - the Ottava text style defaults to 12pt.

**Comment by lasconic** [comment]
I can confirm that the ottava glyphs are too small. Select a chordrest, double clic ottava in the palette to test it. A comparison with BravuraText show that the height of the symbol is around 500 in mscoreText and around 800 in bravuraText. @mgavioli could you make them a bit bigger, to match BravuraText and then hopefully Lilypond style?

Kerning is ok on Windows 8.1 using Qt 5.4. So it's ok on the 3 platforms! Great!

**Comment by mgavioli** [comment]
@lasconic @MarcSabatella : working on making ottava glyphs larger...

**Comment by lasconic** [comment]
Could you squash the two commits?

**Comment by mgavioli** [comment]
Ottava glyphs rebuilt to have the same height of similar glyphs in Bravura Text. Commits squashed.

**Pull request merged**
