### PR TITLE
clean up exported svg, remove redundant g elements

### PR DESCRIPTION
**Pull request by heslil**
Some of the issues discussed on https://musescore.org/en/node/61746 are resolved by this PR.

This PR cleans up the svg files by
* removing the redundant `<g>` elements,
* removing font attributes, as everything is rendered in the svg, no text is used,
* removing the 'default' attributes set in a global `<g>`, as it's never used,
* and removing the extra blank line between `<g>` elements.

The svg of a test score using the original code was about 170 kB, and with these modifications, the new svg is about 120 kB.

It is easy to spot the differences by looking at a the segment of the two svg files. 
*The original svg:*
```xml
<desc>Generated by MuseScore 2.1.0</desc>
<defs>
</defs>
<g fill="none" stroke="black" stroke-width="1" fill-rule="evenodd" stroke-linecap="square" stroke-linejoin="bevel" >

<g fill="none" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="bevel" transform="matrix(3.125,0,0,3.125,161.86,1035.82)"
font-family="FreeSerif" font-size="11" font-weight="400" font-style="normal" 
>
</g>

<g fill="#000000" fill-opacity="1" stroke="none" transform="matrix(3.125,0,0,3.125,144.722,1035.82)"
font-family="FreeSerif" font-size="11" font-weight="400" font-style="normal" 
>
<path vector-effect="none" fill-rule="nonzero" d="M2.01562,-6.53125 C1.88021,-6.53125 1.61458,-6.44792 1.21875,-6.28125 L1.21875,-6.4375 L3.1875,-7.4375 L3.28125,-7.42188 L3.28125,-0.8125 C3.28125,-0.552083 3.34635,-0.380208 3.47656,-0.296875 C3.60677,-0.213542 3.89062,-0.171875 4.32812,-0.171875 L4.32812,0 L1.29688,0 L1.29688,-0.171875 C1.71354,-0.182292 1.99219,-0.239583 2.13281,-0.34375 C2.27344,-0.447917 2.34375,-0.671875 2.34375,-1.01562 L2.34375,-6 C2.34375,-6.35417 2.23438,-6.53125 2.01562,-6.53125 M9.40625,-2.15625 C9.40625,-2.55208 9.32031,-2.90104 9.14844,-3.20312 C8.97656,-3.50521 8.76823,-3.73958 8.52344,-3.90625 C8.27865,-4.07292 8.00521,-4.21094 7.70312,-4.32031 C7.40104,-4.42969 7.13802,-4.5 6.91406,-4.53125 C6.6901,-4.5625 6.49479,-4.57812 6.32812,-4.57812 C6.23438,-4.57812 6.1875,-4.60938 6.1875,-4.67188 C6.1875,-4.69271 6.19271,-4.70833 6.20312,-4.71875 L7.40625,-7.28125 L9.70312,-7.28125 C9.81771,-7.28125 9.90885,-7.29948 9.97656,-7.33594 C10.0443,-7.3724 10.1198,-7.44792 10.2031,-7.5625 L10.2969,-7.48438 L9.89062,-6.57812 C9.85938,-6.51562 9.77083,-6.48438 9.625,-6.48438 L7.46875,-6.48438 L7.01562,-5.53125 C8.08854,-5.34375 8.88542,-5.03385 9.40625,-4.60156 C9.92708,-4.16927 10.1875,-3.53125 10.1875,-2.6875 C10.1875,-2.25 10.1198,-1.86198 9.98438,-1.52344 C9.84896,-1.1849 9.67448,-0.911458 9.46094,-0.703125 C9.2474,-0.494792 9.00521,-0.322917 8.73438,-0.1875 C8.46354,-0.0520833 8.20052,0.0390625 7.94531,0.0859375 C7.6901,0.132812 7.43229,0.15625 7.17188,0.15625 C6.76562,0.15625 6.44271,0.09375 6.20312,-0.03125 C5.96354,-0.15625 5.84375,-0.322917 5.84375,-0.53125 C5.84375,-0.8125 6,-0.953125 6.3125,-0.953125 C6.52083,-0.953125 6.78646,-0.838542 7.10938,-0.609375 C7.43229,-0.380208 7.6875,-0.265625 7.875,-0.265625 C8.3125,-0.265625 8.67708,-0.447917 8.96875,-0.8125 C9.26042,-1.17708 9.40625,-1.625 9.40625,-2.15625 "/>
</g>

<g fill="none" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="bevel" transform="matrix(3.125,0,0,3.125,161.86,1035.82)"
font-family="FreeSerif" font-size="11" font-weight="400" font-style="normal" 
>
</g>
```

*The svg after modifying the code:*
```xml
<desc>Generated by MuseScore 2.1.0</desc>
<defs>
</defs>
<g fill="#000000" fill-opacity="1" stroke="none" transform="matrix(3.125,0,0,3.125,144.722,1035.82)" >
<path vector-effect="none" fill-rule="nonzero" d="M2.01562,-6.53125 C1.88021,-6.53125 1.61458,-6.44792 1.21875,-6.28125 L1.21875,-6.4375 L3.1875,-7.4375 L3.28125,-7.42188 L3.28125,-0.8125 C3.28125,-0.552083 3.34635,-0.380208 3.47656,-0.296875 C3.60677,-0.213542 3.89062,-0.171875 4.32812,-0.171875 L4.32812,0 L1.29688,0 L1.29688,-0.171875 C1.71354,-0.182292 1.99219,-0.239583 2.13281,-0.34375 C2.27344,-0.447917 2.34375,-0.671875 2.34375,-1.01562 L2.34375,-6 C2.34375,-6.35417 2.23438,-6.53125 2.01562,-6.53125 M9.40625,-2.15625 C9.40625,-2.55208 9.32031,-2.90104 9.14844,-3.20312 C8.97656,-3.50521 8.76823,-3.73958 8.52344,-3.90625 C8.27865,-4.07292 8.00521,-4.21094 7.70312,-4.32031 C7.40104,-4.42969 7.13802,-4.5 6.91406,-4.53125 C6.6901,-4.5625 6.49479,-4.57812 6.32812,-4.57812 C6.23438,-4.57812 6.1875,-4.60938 6.1875,-4.67188 C6.1875,-4.69271 6.19271,-4.70833 6.20312,-4.71875 L7.40625,-7.28125 L9.70312,-7.28125 C9.81771,-7.28125 9.90885,-7.29948 9.97656,-7.33594 C10.0443,-7.3724 10.1198,-7.44792 10.2031,-7.5625 L10.2969,-7.48438 L9.89062,-6.57812 C9.85938,-6.51562 9.77083,-6.48438 9.625,-6.48438 L7.46875,-6.48438 L7.01562,-5.53125 C8.08854,-5.34375 8.88542,-5.03385 9.40625,-4.60156 C9.92708,-4.16927 10.1875,-3.53125 10.1875,-2.6875 C10.1875,-2.25 10.1198,-1.86198 9.98438,-1.52344 C9.84896,-1.1849 9.67448,-0.911458 9.46094,-0.703125 C9.2474,-0.494792 9.00521,-0.322917 8.73438,-0.1875 C8.46354,-0.0520833 8.20052,0.0390625 7.94531,0.0859375 C7.6901,0.132812 7.43229,0.15625 7.17188,0.15625 C6.76562,0.15625 6.44271,0.09375 6.20312,-0.03125 C5.96354,-0.15625 5.84375,-0.322917 5.84375,-0.53125 C5.84375,-0.8125 6,-0.953125 6.3125,-0.953125 C6.52083,-0.953125 6.78646,-0.838542 7.10938,-0.609375 C7.43229,-0.380208 7.6875,-0.265625 7.875,-0.265625 C8.3125,-0.265625 8.67708,-0.447917 8.96875,-0.8125 C9.26042,-1.17708 9.40625,-1.625 9.40625,-2.15625 "/>
</g>
```

### CODE REVIEW

**Comment by lasconic** [comment]
Looks good.
For your next contribution, it's better to create an issue in the issue tracker so we can refer to it in the future. Then use "fix #XXXX" in the commit message with XXXX the issue number.

**Comment by heslil** [comment]
Thanks! sure will do that next time.

**Comment by sidewayss** [comment]
I notice that there was a systematic change from *d->stream to stateStream, yet not everywhere.  Why the change, and why not everywhere?  Could you please provide some additional documentation or explanation of your changes?  I am making further modifications to this file - I got it working for 2.0.2, and now I've gotten it to work with these changes, but I would still really appreciate some additional understanding of what changed.  Thanks.

**Comment by heslil** [comment]
This commit implements a simplistic state machine. If you go through the commit, it should be easy to see how the new code aggregates the attributes and sends them to the file only when needed.

**Comment by sidewayss** [comment]
I've gotten my code to function properly, including the further elimination of svg group elements and extra lines.  Thanks for doing the heavy lifting in the file streamlining process.

**Pull request merged**
