### PR TITLE
Fix #83111: Expose lyrics ticks to plugin framework

### PR DESCRIPTION
**Pull request by CombatCube**

### CODE REVIEW

**Comment by mgavioli** [comment]
I suspect that making the `Lyrics.ticks` property plugin-writable requires making `Lyrics::setTicks()` more robust or providing a qml-specific method for dealing with `Lyrics::_ticks`. What if the ticks of lyric syllable are changed to overlap a following syllable?

Probably a similar reasoning affects `Lyrics.syllabic` too. If fact, the two properties are connected: for instance, a syllable with `Lyrics::_syllabic` equal to `BEGIN` or `MIDDLE` should have ticks enough to reach the next syllable, not less, not more.

**Comment by Jojo-Schmitz** [comment]
@CombatCube: if you spell the commit mesaage like "fix #83111 ..:" the corresponding issue gets closed automagically if and when the PR gets merged. Same for #2253 ...

**Comment by CombatCube** [comment]
Renamed the commit.

**Comment by lasconic** [comment]
Just talk this one through with Werner. According to us, it's not a good idea to expose setTicks for lyrics. The plugin programmer can easily crash MuseScore with setTicks(-42) or setTicks(10000000). We would prefer to use the Cursor interface for this, since the Cursor should always be on a valid segment and have something like "deleteLyric", "addLyric", "getLyric".
I close this pull request.

**Pull request closed without merging**
