### PR TITLE
fix #272172: Remove tuplets after inserting measures causes corruption/crash

### PR DESCRIPTION
**Pull request by mattmcclinch**
See [Remove tuplets after inserting measures causes corruption/crash](https://musescore.org/en/node/272172).

### CODE REVIEW

**Comment by anatoly-os** [comment]
According to the codestyle in master, we avoid using Q* constainers and prefer STL ones. With std::set we have to use [count(obj) != 0] instead of contains(obj).

**Comment by mattmcclinch** [comment]
Thanks for the tip! That's much nicer than using std::find().

**Comment by mattmcclinch** [comment]
I changed this to use std::set instead of QSet. But I do not like the idea of counting the number of times an object appears in a set. The set either contains the object or it does not.

**Comment by anatoly-os** [comment]
std::set is optimized in this place and never slower than find().

**Comment by anatoly-os** [comment]
@mattmcclinch did you check whether your fix work with an embedded tuplets?

**Comment by anatoly-os** [comment]
Manually merged to 2.3 as well. Thank you!

**Pull request merged**
