### PR TITLE
[MU4] audio_buffer_upgrade

### PR DESCRIPTION
**Pull request by vpereverzev**
Resolves: #12483
Resolves: #11190
Resolves: #12918
Resolves: #14474

### CODE REVIEW

**Comment by vpereverzev** [comment]
@Tantacrul @DmitryArefiev 
Please check mentioned issues on the following "non-debug" builds:
- MAC - https://github.com/musescore/MuseScore/suites/9403045111/artifacts/443768789
- WIN - https://github.com/musescore/MuseScore/suites/9402404037/artifacts/443719995

**Comment by vpereverzev** [comment]
@Tantacrul @DmitryArefiev 
Another set of builds, it's slightly performant on my machine comparing to the builds from above:
- WIN - https://github.com/musescore/MuseScore/suites/9417801459/artifacts/444885402
- MAC- https://github.com/musescore/MuseScore/suites/9417818476/artifacts/444895098

**Comment by DmitryArefiev** [comment]
> @Tantacrul @DmitryArefiev Another set of builds, it's slightly performant on my machine comparing to the builds from above:
> 
>     * WIN - https://github.com/musescore/MuseScore/suites/9417801459/artifacts/444885402
> 
>     * MAC- https://github.com/musescore/MuseScore/suites/9417818476/artifacts/444895098

Yes, it's really better on **Windows10** with Mixer opened


https://user-images.githubusercontent.com/90187801/203054560-1793cad1-523d-4a0a-8b9f-41852ead58ab.mp4

**Comment by shoogle** [comment]
Works for me on Windows 11. Fixes stuttering over Bluetooth and normal headphones as well as HDMI output. Fixes the issue with output frequency greater than 48 kHz. Also improves performance when opening the Mixer. 👏

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Tantacrul** [comment]
CELEBRATIONS!

**Pull request merged**
