### PR TITLE
Completely block opening files from newer versions

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Basically remove the "Open anyway" button

Resolves: #18083 

Scherm­afbeelding 2023-07-03 om 01 29 32

Here is a fake too-new MuseScore file to test it: [too_new.mscz.zip](https://github.com/musescore/MuseScore/files/11931731/too_new.mscz.zip)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Why? Forcing users to upgrade IMHO is not the way to go

**Comment by cbjeukendrup** [comment]
This is not forcing users to upgrade; this is only blocking "downgrades", which are basically asking for trouble. Newer files will not work well in older versions, and when you later open the broken file in a newer version again, you'll have a broken score that is going to have all kinds of issues that are going to cause us unnecessary headaches. That's the rationale.

**Comment by Jojo-Schmitz** [comment]
For that a serious warning should be enough

**Comment by Jojo-Schmitz** [comment]
Maybe treat them as import, in an attempt to avoid overwriting the higher version score (although we all know that users will find a way to do it anyway and then blame it on MuseScore)

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #18083 on Win10, Mac13, LinuxUbuntu 22.04.

@cbjeukendrup Seems to be fine. Only on **Windows** the location path has **wrong style slash**

Capture

I can log it separately

**Comment by cbjeukendrup** [comment]
@DmitryArefiev That should be fixed now!

**Comment by DmitryArefiev** [comment]
@cbjeukendrup Looks good now!

Tested #18083 on Win10, Mac13, LinuxUbuntu 22.04 - **FIXED**

**Comment by jeetee** [comment]
Note that this breaks years long tradition and user expectancy that MuseScore allows downgrades of files between minor releases. (as is evidenced by currently nightly 4.2 files no longer opening in 4.1, while they open without major issues in 4.0 ...)

**Pull request merged**
