### PR TITLE
fix #268842: Need a space option in lyrics paste that doesn't advance to new note

### PR DESCRIPTION
**Pull request by mattmcclinch**
See [issue #268842](https://musescore.org/en/node/268842).

This will convert the + character to a non-breaking space when pasting lyrics.

This is for MuseScore 2.2. Pasting lyrics in 3.0 is not implemented yet.

### CODE REVIEW

**Comment by mattmcclinch** [comment]
Oops, doesn't work in conjunction with - or _

**Comment by lasconic** [comment]
Could be a rabbit hole ... what if I want to paste "Toi + moi" under three notes ? You need an escape char for + ...

**Comment by mattmcclinch** [comment]
I hadn't thought that anyone would want to paste a plus sign in a lyric. I guess I was mistaken.

**Comment by mattmcclinch** [comment]
Now this uses \ to escape special characters.
Special characters are - _ \ and whitespace.

**Comment by Jojo-Schmitz** [comment]
Alternative to #3426

**Comment by lasconic** [comment]
We have a good solution with the non breaking space.

**Pull request closed without merging**
