### PR TITLE
add number of semitones in transpose dialog intervals comboxbox

### PR DESCRIPTION
**Pull request by lasconic**

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
I would rather not have the italics, but this is a good idea.

**Comment by lasconic** [comment]
What about having the "most common" intervals first (major, minor, perfect) and then the augmented/diminished?

**Comment by Jojo-Schmitz** [comment]
I like it as is, the unusual ones in italics

**Comment by IsaacWeiss** [comment]
Having italic items in a menu mixed in with regular ones is just not done. If they must be distinguished, then why not put them in two groups, with a separator in between?

**Comment by Jojo-Schmitz** [comment]
It is done, in mscore/transposedialog.cpp

**Comment by lasconic** [comment]
OK. It let it sink a bit. I believe italics is not really good, especially for people with dyslexia. So I would remove it. Also, I'm not sure it's a good idea to add the number of semitones to the translations... So this experiment is more or less a failure. I will close this PR.

**Pull request closed without merging**
