### PR TITLE
fix #65571 mensural time sigs not shown in scores

### PR DESCRIPTION
**Pull request by AntonioBL**

### CODE REVIEW

**Comment by mgavioli** [comment]
Are you sure? That part of the code did not change from several months; for instance it was already so in December 2014 and it was working correctly; and master was working correctly a few weeks ago.

The bug is probably elsewhere.

**Comment by AntonioBL** [comment]
@mgavioli : Actually, the change that broke this was https://github.com/musescore/MuseScore/commit/eff562ee3f6 since it changed the behavior of the default branch of the " switch (s[i].toLatin1()) ". Before that commit, the default was  d += s[i] so even if the characters were not recognized as Latin1 they were added to the time sig string.
Note that a more easy fix could simply be to reinstate the  d += s[i] default. This would also add the possibility to use other characters in the time signature (for example, note duration characters, alphabetic symbols etc...).

**Comment by mgavioli** [comment]
@AntonioBL : Indeed!

Is there any recognizable reason why that `d += s[i];` has been removed?

The patch was related with freetype but I fail to see any obvious connection.

**Comment by AntonioBL** [comment]
@mgavioli : ok, I will update the PR with those cases.
@wschweer : thank you for the explanation. I was thinking the change was related to the bounding box / spacing of symbols, as you confirmed.

**Comment by AntonioBL** [comment]
Here it is, updated and rebased :-)

**Comment by mgavioli** [comment]
I run a few tests on existing 2.0 scores as well as on creating new scores with current master code and this patch did work correctly in all of them.

@AntonioBL : Thanks!

**Pull request merged**
