### PR TITLE
Dark Theme Feature

### PR DESCRIPTION
**Pull request by shivam2509**
The Site will be available in DARK theme also.
1 toggle button will be available to enable dark mode.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Lots of merge confticts, and lots of foreign commits (3973 in total!) that don't belong into this PR

**Comment by cbjeukendrup** [comment]
Also, making a pull request from a master branch to a 3.x-like branch is probably not what you want.

**Comment by Jojo-Schmitz** [comment]
Oops, I didn't even notice that!

**Comment by Jojo-Schmitz** [comment]
That'd be simple to fix, just rebase onto updstream/master, here on GitHub.

**Comment by RomanPudashkin** [comment]
I'll close your PR, but you can create a new one after fixing rebasing problems. Thanks!

**Pull request closed without merging**
