### PR TITLE
[MU4] Workspaces

### PR DESCRIPTION
**Pull request by igorkorsukov**
This is the basic implementation of workspace.
It is needed in order to get the workspace programming interface.
Further development of workspace will depend on the details of what workspace will be for the user,
how he will interact with them, etc. (designers decide)
As these issues are resolved, it will be possible to refine the workspaces.

From a technical point of view, the idea is that in the workspace we can save anything, while so that workspace does not link all the modules between themselves. Therefore the `IWorkspace` interface is pretty abstract.
As part of the work on palettes, palette tree reading will be added.

The system turned out to be a little more complicated than I would like. Perhaps if the data were stored in `json`, then it would be simpler, it would not be necessary to make separate readers and writers, and from workspace it would be possible to return data in the form of a collection tree (vectors and maps)

### CODE REVIEW

**Comment by Howard-C** [comment]
What do the abbreviations in file names mean, `srw`, `rw`, `wr`?

**Comment by Howard-C** [comment]
Also, if you're interested, you could post your thoughts about workspaces in https://musescore.org/en/node/305747 and discuss with the community,

**Comment by igorkorsukov** [comment]
> What do the abbreviations in file names mean, `srw`, `rw`, `wr`?

RW - ReadWrite

 `srw`, `rw`, `wr` - in which exact places in the code did you pay attention to this?

**Comment by igorkorsukov** [comment]
> Also, if you're interested, you could post your thoughts about workspaces in https://musescore.org/en/node/305747 and discuss with the community,

I agree with your suggestion.
I myself at moment do not have time to discuss the workspace UI/UX.
But I think @Tantacrul will think about workspace and possibly discuss this topic with the community.
Therefore, at the moment, nothing related to UI/UX has been done.

**Comment by Howard-C** [comment]
> `srw`, `rw`, `wr` - in which exact places in the code did you pay attention to this?

OK, I misread `srw`, but what about `wr` in `workspacetoolbarwr.h`? Also, why is `wsfile.cpp` not `workspacefile.cpp`?

**Comment by Tantacrul** [comment]
@Howard-C - I do have a lot of thoughts about where we can take Workspaces although we're not planning on altering existing functionality right now. For the moment, the only thing to do for MS4 is alter some of the defaults a little (advanced / beginner)

**Comment by igorkorsukov** [comment]
> > `srw`, `rw`, `wr` - in which exact places in the code did you pay attention to this?
> 
> OK, I misread `srw`, but what about `wr` in `workspacetoolbarwr.h`? Also, why is `wsfile.cpp` not `workspacefile.cpp`?

Removed the abbreviations.

**Pull request merged**
