### PR TITLE
fix #276460: Crash when opening the Advanced Style Properties

### PR DESCRIPTION
**Pull request by mattmcclinch**
See https://musescore.org/en/node/276460.

This updates mscore/data/std_sample.mscx and mscore/data/tab_sample.mscx to the new file format, preventing a crash when opening Avdanced Style Properties.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Maybe saving those files when having used the -t option? Should get rid of the page size settings for example.
See also #3977

**Comment by mattmcclinch** [comment]
Aren't the page size settings important? They were present in the "3.00" version of the files.

**Comment by Jojo-Schmitz** [comment]
Not 100% sure, but I don't think they are needed

**Comment by mattmcclinch** [comment]
I still think that the page size settings are important, as they limit the amount of space around the picture.

**Comment by Jojo-Schmitz** [comment]
Ah, now I see, these are not the standard A4 settings, but something much smaller. So yes, indeed we need to keep them, sorry for the noise

**Pull request merged**
