### PR TITLE
[MU4] Code style fixes for ove module

### PR DESCRIPTION
**Pull request by Howard-C**
- Change member variables from "var_" to "_var"
- Code style fixes
- Rename OVE namespace to ovebase

### CODE REVIEW

**Comment by igorkorsukov** [comment]
It would be better to change to `m_var`
https://github.com/musescore/MuseScore/wiki/CodeGuidelines#declaring-variables

**Comment by Howard-C** [comment]
> It would be better to change to `m_var`
> https://github.com/musescore/MuseScore/wiki/CodeGuidelines#declaring-variables

Done

**Comment by Howard-C** [comment]
@igorkorsukov If you can confirm that all my changes are good to go, I can squash the commits into one. Or you can use Squash + Merge

**Review by igorkorsukov — APPROVED** [review]

**Comment by Howard-C** [comment]
Done :)

**Comment by igorkorsukov** [comment]
> Done :)

Cool!! :)

**Pull request merged**
