### PR TITLE
fix #180966: Show and hide fingerings in tablature staves for 3.0

### PR DESCRIPTION
**Pull request by MarkusLutz63**
I have corrected my code, so that it now shows and hides fingerings. Seems to work quite fine, but I'm not sure, if I should have left one of my earlier changes in the code.
BTW - if that would be wished, it would be easy to change the place of the variable in the ui in order to also be able to hide fingerings in normal staff.

### CODE REVIEW

**Comment by MarkusLutz63** [comment]
Is there a problem with the code? It would help to parallelize the behaviour of 2.1 and 3.0, as then in 3.0 also the fingerings would be handled always, but only shown if the staff variable is set to on.

**Comment by Jojo-Schmitz** [comment]
Needs a rebase

**Comment by lasconic** [comment]
I would like @wschweer input here. I know he doesn't like adding elements and make them completely invisible and I guess he changed the implementation in MuseScore 3 for this reason. So if we really want the same behavior in 3.0 than in 2.1, we will need to recreate all the fingerings in the tablature based on the standard staff when linked, or to find a way to link the "visible" flag with the staff style value for fingerings in tablature...

**Comment by lasconic** [comment]
I asked Werner
*I don't like #3056: there should be no feature to switch on/off fingering in tablature, its too confusing and does not fit anywhere. We have already the concept of layers which is underdeveloped (or also should be dropped).
Imagine you have switched fingering off. Then you drop a fingering and nothing happens. Then you switch it on and magically the (wrong) number appears.
Then implement it as a tablature fingering layer*

**Comment by MarkusLutz63** [comment]
I still think that "showing and hiding fingerings" (like in 2.1 btw) is a much better solution than the code that now had been merged.
If you had been using fingerings, but don't want to see them, it is much easier, how I did it now (in #3065). The fingerings then are still there - but you can switch them on or off - maybe a little bit magical. 
For sure it would be possible to disable dropping or attaching them, if "show fingerings" is turned off.

The disadvantage of the currently merged solution (fix #180966) is, that you cannot disable showing already attached fingerings. You would have to delete them, if you don't want to see them.
With "showing fingerings" you can really enable or disable seeing them.   

I could even try to set the variable to showing, if someone drags fingerings. But possibly that person only wants to attach it to the linked notation line ... (so this would be problematic also). 

Unfortunately I don't know, how to implement it as a (tablature) fingering layer ...
For me (and others too) it is important to have the possibility to use fingering in tablature, as normally lute tablature seldom is used as linked staff. It is also senseful to have the possibility to turn already set fingerings off (but leave them saved). 

And one last question: Wouldn't it be senseful to also show and hide fingerings in normal notation?

**Comment by dmitrio95** [comment]
Needs actualization for current master

**Pull request closed without merging**
