### PR TITLE
fix #276569: slur handles blacked out

### PR DESCRIPTION
**Pull request by jthistle**
Fixes: https://musescore.org/en/node/276569

### CODE REVIEW

**Comment by jthistle** [comment]
For some reason, replacing the ternary operator with a normal if else fixes this. Any idea why this might be @mattmcclinch?

**Comment by mattmcclinch** [comment]
`QPainter` has two separate methods: `void setBrush(const QBrush &brush)` and `void setBrush(Qt::BrushStyle style)`. The method that gets called is determined at the time of compilation by the type of the parameter. The result of `Grip(i) == ed.curGrip ? MScore::frameMarginColor : Qt::NoBrush` is a `QColor`, since the ternary operator cannot return two different types, and a `QColor` can be constructed from the value `Qt::NoBrush`. So the method that gets selected by the compiler as a result of the ternary operator is `void setBrush(const QBrush &brush)`, since a `QBrush` can be constructed from a `QColor`. But when `Grip(i) != ed.curGrip` we really want to call `void setBrush(Qt::BrushStyle style)` with a value of `Qt::NoBrush`, rather than `void setBrush(const QBrush &brush)` with a value of a `Brush` constructed from a `QColor` constructed from the value `Qt::NoBrush`.

**Comment by Jojo-Schmitz** [comment]
That is worth a corresponding comment in the code

**Comment by jthistle** [comment]
@Jojo-Schmitz completely. I'll add one when I have a moment.

@mattmcclinch That makes sense, thanks very much! Honestly, I'm amazed by how you work out these kinds of things :)

**Comment by Jojo-Schmitz** [comment]
Agreed, excellent analysis and explanation

**Comment by jthistle** [comment]
Explanation added. Let me know if anyone thinks it needs clarification.

**Pull request merged**
