### PR TITLE
Fix #320818: Chord symbols with a bass extension don't export to MusicXML correctly (nor import back)

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves: https://musescore.org/en/node/320818

As per https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/harmony/ MusicXML expects `bass` before `degree` (and after `kind` and `inversion`), but before this PR got it after `degree`.

This PR does not fix the import of such a 'broken' MusicXML...

Same issue and fix applies to Mu3, see jojo-schmitz#119

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
@lvinken, @MarcSabatella I'd appreciate a review from you

**Comment by MarcSabatella** [comment]
This seems like it should fix the issue for most cases, but will cause the bass to not be written at all in the case of an empty "kind" (basically, an unrecognized chord symbol).  As I discuss in https://musescore.org/en/node/320818#comment-1191238, it would probably be better to also copy this code to the else clause of https://musescore.org/en/node/320818#comment-1191238, after the kind is written.

**Comment by Jojo-Schmitz** [comment]
OK, let's do that then, thanks.

**Comment by lvinken** [comment]
After a quick inspection, the changes look OK to me. Caveats: I am not very familiar (anymore) with this code and I did not build it to verify the output.

**Comment by Jojo-Schmitz** [comment]
Thanks for checking

**Comment by Jojo-Schmitz** [comment]
Can this please get reviewd and merged?

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
Could you please add some test file to verify this fix?

**Comment by Jojo-Schmitz** [comment]
OK, testing, with the unit test first (to see it fail)
Fix to follow (to see it succeed)

**Comment by Jojo-Schmitz** [comment]
OK, it failed, but not the way I wanted/expected it to fail...
Next test to follow

**Comment by Jojo-Schmitz** [comment]
There we go, the unit tests fails before the fix and succeeds after...

**Comment by cbjeukendrup** [comment]
Thanks!

**Pull request merged**
