### PR TITLE
fix #269280: Playback when adding an accidental

### PR DESCRIPTION
**Pull request by mattmcclinch**
See [issue #269280](https://musescore.org/en/node/269280).

### CODE REVIEW

**Comment by MarcSabatella** [comment]
I'm fine with the proposed playback, but not a fan of dedicating a new command to such an specific use case (removing an accidental from a selected note) that is already well-handled by other commands (arrow keys, ordinary delete).  It's harmless enough I guess, but more useful might be to turn the other accidental commands into toggles?

**Comment by lasconic** [comment]
It would have been great to have two different commits and two different issues for two different features.

**Comment by mattmcclinch** [comment]
I updated this pull request to only provide the "playback when adding an accidental" feature.

**Comment by lasconic** [comment]
Thank you.

**Comment by Jojo-Schmitz** [comment]
This one seems good enough to make it into 2.2 too, doesn't it?

**Comment by mattmcclinch** [comment]
I just realized this doesn't work when adding accidentals from the palette. `setPlayNote(true)` should be moved to the end of `void Score::changeAccidental(Note* note, AccidentalType accidental)`

**Pull request merged**
