### PR TITLE
extend notehead vtests, all types and brackets

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Emmentaler vtest reference image generated using the font from PR #2283

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Emmentaler vtest reference image would need to get regenerated once PR #2283 got merged

**Comment by Jojo-Schmitz** [comment]
These vtests show that there are 
* no special brevis heads for Do, Re, Mi, Fa, Sol, La, Ti, they look identicaL to the Normal brevis
* the heads for brevis and whole note for Cross, Diamond, Triangle (only in Emmmentaler), Slash and XCircle (only in Emmentaler) look identical
* the Normal and Sol heads for half and quarter note in Gonville look identical
* all heads for Alt.Brevis but the brevis itself, look identical to Normal heads (this not being too much of a surprise, I guess)

**Comment by Jojo-Schmitz** [comment]
rebased and created emmentaler-10-ref.png using the font from PR #2283

**Comment by lasconic** [comment]
* *the brevis heads for Do, Re, Mi, Fa, Sol, La, Ti look identical to the Normal brevis*
I believe it's ok. SMuFL doesn't define brevis for shape notes noteheads.

* *the Normal and Sol heads for half and quarter note in Gonville look identical*
Could be a bug or a design decision.

* *all heads for Alt.Brevis but the brevis itself, look identical to Normal heads (this not being too much of a surprise, I guess)*
Indeed, that's correct.

**Pull request merged**
