### PR TITLE
fix #288169, #287889: draw lines when there are two hooks and draw hooks solid

### PR DESCRIPTION
**Pull request by peterhieuvu**
Previously hook drawing was a bit messed up. There were options for T hooks for beginning and end, but only end T hooks actually were drawn. Additionally, the points were stored in a 4 element array when, with a T hook and regular hook, there would actually be 5 elements. Adding the functionality for beginning T hooks would require 6 array elements. This space deficit created a few issues that go away by properly setting the size of the array. Additionally, drawing hooks as solid ended up only working in specific cases so it was implemented to work for all types and combinations of hooks.

### CODE REVIEW

**Comment by peterhieuvu** [comment]
Changed the approach completely. Now all custom hooks and lines will be drawn so that the strokes end on a dash (with dash spacing adjusted slightly to allow for this). It's a lot of code for the change, but I believe it is a well behaved solution that gives consistent results.

**Comment by MarcSabatella** [comment]
Looks like just the right amount of code to me :-).  I haven't tested yet, but this is to me a good approach if others agree.  In practice, I assume the adjustment is normally quite small for the lines themselves, potentially larger for the hooks.

A good reason to do this rather than something like just going with standard line types for the hooks is that some people create lines that are mostly hook, and in that case they will want their custom lines.

**Comment by peterhieuvu** [comment]
Sounds good! And yeah it barely affects the actual lines but does make it look cleaner. For the hooks, huge spacings end up getting squashed down so that at least two dashes can fit (if possible). My old approach kind of ruined the look of the custom line since it broke the flow, but this does look a lot better. Thanks for the suggestion!

**Comment by anatoly-os** [comment]
@peterhieuvu could you please add visual tests for this PR?

**Comment by peterhieuvu** [comment]
I believe I have added visual tests!

**Pull request merged**
