### PR TITLE
Fix GH#16625: Rename margin to padding

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
picking up where #16654 left

Resolves: #16625

### CODE REVIEW

**Comment by bkunda** [comment]
@RomanPudashkin I've tested this in macOS.
🟢 FIXED

**Review by cbjeukendrup — COMMENTED** [review]
See my reply at https://github.com/musescore/MuseScore/pull/16654#issuecomment-1552199374

**Comment by Jojo-Schmitz** [comment]
If there are still other places, i didn't find them.
Will have another look, but after the weekend.

**Comment by Jojo-Schmitz** [comment]
You mean those?

**Comment by cbjeukendrup** [comment]
Yep, and thanks for spotting those in editstyle.ui too!

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
@bkunda Now the similar properties for frames for Text objects have been renamed too: go to Properties > Text > More, select the rectangular frame option, and see that the "margin" property has been renamed to "padding". Do you want to re-test this?

**Comment by Jojo-Schmitz** [comment]
As this PR changes strings, I'd rather get it merged soon...

**Comment by bkunda** [comment]
> @bkunda Now the similar properties for frames for Text objects have been renamed too: go to Properties > Text > More, select the rectangular frame option, and see that the "margin" property has been renamed to "padding". Do you want to re-test this?

Tested in macOS. I'm happy with this change.
Thanks!

**Pull request merged**
