### PR TITLE
fix #86636 : MusicXML import of tuplets yields elements with 0 duration

### PR DESCRIPTION
**Pull request by AntonioBL**

### CODE REVIEW

**Comment by lasconic** [comment]
@lvinken Not sure if you get notified about these PRs. If you are around and want to have a look, be my guest! No hurry.

**Comment by lvinken** [comment]
Will do, don't know when.

**Comment by lvinken** [comment]
Works correctly, no comments at all. Thanks, Leon.

**Comment by lasconic** [comment]
Thank you for your feedback Leon.

**Pull request merged**
