### PR TITLE
fix #277370: measure numbers wrongly positioned

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
most probably a regression caused by d77183b

### CODE REVIEW

**Comment by anatoly-os** [comment]
I'm not sure this is a correct way of fixing the broken positions according to the @wschweer 's plans to fix it. @wschweer could you please comment whether this fix correct or not?

**Comment by Jojo-Schmitz** [comment]
I believe the alignment changes from `Align::LEFT | Align::BASELINE` to `Align::HCENTER | Align::BOTTOM` are correct, as these are the settings used in 2.x, but indeed the change of the y-offset may be wrong. It doesn't work well with non-5-line staves for example.

**Comment by wschweer** [comment]
The wrong vertical position of measure numbers was caused by a program bug. Its fixed in latest version. I changed the horizontal alignment back to "center" but believe the vertical alignment should be "baseline" as this is more reliable than "top" or "bottom".

**Comment by Jojo-Schmitz** [comment]
I don't see the change from `Align::LEFT` to `Align::HCENTER` in c761892

**Comment by wschweer** [comment]
oops, forgot it... its in the next commit

**Pull request closed without merging**
