### PR TITLE
Export/Import Settings (#100571)

### PR DESCRIPTION
**Pull request by syrma**
This adds the possibility to import or export preferences from/to a file. It doesn't include shortcuts as I am currently working on feature to import/export them independently.

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
With the goal of making MuseScore "smarter, faster, **easier**," this seems like a good candidate. @syrma, did you ever get the shortcuts export/import worked out?

**Comment by RobFog** [comment]
This sounds like a neat idea.

**Comment by Jojo-Schmitz** [comment]
Rebase needed

**Comment by RobFog** [comment]
The author of the PR stated in the issue: "I am still working on the possibility to import/export shortcuts for an another patch. So far, the export works fine. However, after using the import, the application stops responding to the keyboard until it is restarted." That would make this "work in progress", right, @anatoly-os ? 😄

**Comment by anatoly-os** [comment]
I'm not sure the author is around to continue development, @syrma?

**Comment by syrma** [comment]
@anatoly-os I apologize, unfortunately I didn't manage to make it work, and circumstances led to me stopping the work. I might come back to it sometime later if no one tackles the problem but this is currently discontinued.

**Pull request closed without merging**
