### PR TITLE
Build MuseScore with Qt-5.6 on Windows

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
but without startcenter, similar to the newlayout branch

### CODE REVIEW

**Comment by lasconic** [comment]
As explained, 5.6 is used in the new layout branch. We will move to 5.6 when/if this branch is merged to master.

**Comment by Jojo-Schmitz** [comment]
Yes, I know, this PR is more or less ment to a) show what is needed on Windows and b) to replace #2131

**Comment by lasconic** [comment]
I knew you know ;) just adding it here for the benefits of other not reading IRC :)

**Comment by Jojo-Schmitz** [comment]
I know you knew I knew ;-)

**Comment by briff** [comment]
Could you check if https://musescore.org/en/node/82021 (Text hinting causes ugly output) is fixed with Qt 5.6. That version should have DirectWrite enabled by default, which supports turning off hinting.

**Comment by Jojo-Schmitz** [comment]
@briff: now you can check yourself, master branch just switched to using Qt 5.6.

**Comment by Jojo-Schmitz** [comment]
There are a few leftovers from ths PR that probably need to go into master. Will check and report.

**Comment by Jojo-Schmitz** [comment]
see #2545

**Pull request closed without merging**
