### PR TITLE
Removing " Look in: styles"  when not appropriate

### PR DESCRIPTION
**Pull request by BrunoVernay**
Palette an DrumSet namely

### CODE REVIEW

**Comment by anatoly-os** [comment]
Hi. Congratulations with the first PR! Welcome aboard.
You need to sign CLA, so we can merge the PR: https://musescore.org/en/cla.

**Comment by Jojo-Schmitz** [comment]
I disagrees, they need to be looked up somewhere and "styles" seems the most natural place for them currently

**Comment by Jojo-Schmitz** [comment]
True, but the parent directory is a `/usr/` directory too, and all your PR does it send you there

**Comment by lasconic** [comment]
This code is only called when Native Dialog are not used, so only by default on Linux. 
The "urls" variables is used to set up shortcuts to given directories in the sidebar of the File Dialog. To me, it's perfectly fine removing the "/usr/xxx/styles" from palette and drumset file dialog. We don't install palettes nor drumset files in this directory.

**Comment by Jojo-Schmitz** [comment]
In that case I ofcourse withdraw my disagreement :-)

**Comment by BrunoVernay** [comment]
I was going to double check, but again I am always too slow or too quick :-) 
I signed the CLA stuff. 
Now there is an open question: should MuseScore have a preconfigured Palette, DrumSet ... directory  or does it left the user manage  and organize its files ?

(I would say that there are already too many directories: images, templates, plugins, extensions, styles ...)

**Comment by BrunoVernay** [comment]
If I am not mistaken, this could be merged. It is affected to me, but I do not see what I am supposed to do :-)

**Comment by anatoly-os** [comment]
@BrunoVernay which user name did you use in CLA?

**Comment by BrunoVernay** [comment]
BrnVrn ... https://musescore.com/brnvrn   (same user name but without vowels)

**Comment by BrunoVernay** [comment]
Kool Thanks !!

**Pull request merged**
