### PR TITLE
Fix shortcut conflicts with MacOS

### PR DESCRIPTION
**Pull request by efu98**
Resolves: #13951 

Sets the shortcut file name depending if running on MacOS or not

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
In Mu3 this used to be covered at install time by the setup wizzard, along with the AZERTY versions

**Comment by cbjeukendrup** [comment]
@efu98 I think you can still simply use global static variables, like this:
```c++
#ifdef Q_OS_MAC
static const mu::io::path_t SHORTCUTS_DEFAULT_FILE_PATH(":/data/shortcuts-Mac.xml");
#else
static const mu::io::path_t SHORTCUTS_DEFAULT_FILE_PATH(":/data/shortcuts.xml");
#endif
```
(at the top of the file.)
So you don't need to create extra fields and methods for it.

**Comment by efu98** [comment]
@cbjeukendrup Thank you, it's so much better to do it like this! I've changed my code :)

**Review by cbjeukendrup — APPROVED** [review]
Thanks @efu98! This looks great now. 
I added a few more shortcuts-Mac.xml fixes myself.

One question though: under which musescore.org username did you sign the [CLA](https://musescore.org/cla)? I can't find you in the list of users who signed.

**Comment by efu98** [comment]
Hi! Sorry! I thought I signed the CLA already. I think it should be all good now :)

**Pull request merged**
