### PR TITLE
Update Style dialog from MuseScore 3

### PR DESCRIPTION
**Pull request by cbjeukendrup**
It is not yet completely ready, but basically is works again (without crashing) and it contains all of the options from MuseScore 3.

I also performed some related code style updates.

photo_2021-02-10 14 26 22

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Review by igorkorsukov — APPROVED** [review]

**Comment by igorkorsukov** [comment]
I merge this PR, we will make the necessary improvements as a separate PR

**Comment by cbjeukendrup** [comment]
> I merge this PR, we will make the necessary improvements as a separate PR

Yeah, that's okay, there's definitely more to do! 🙂

**Comment by IsaacWeiss** [comment]
Just a note based on the screenshot that this appears to have removed access to the style options I added last summer for multimeasure rests and measure repeats.

**Comment by Marr11317** [comment]
It also crashes when no score is open.

**Comment by cbjeukendrup** [comment]
> Just a note based on the screenshot that this appears to have removed access to the style options I added last summer for multimeasure rests and measure repeats.

That's not good! I'll bring it back ASAP!

**Comment by cbjeukendrup** [comment]
@IsaacWeiss I brought back the multi-measure rest options.

The Measure Repeat options from PR #6365 must have been lost earlier. I can't really find out why and when. @igorkorsukov Do you know something about that? 

Looking at the monstrous diff, I'm afraid that that will be a bit more difficult to bring back...

**Comment by igorkorsukov** [comment]
> Do you know something about that?

I think something like this happened:
1. The master had code MU3
2. In the master, we started to do MU4, but by default, the MU3 interface was launched
3. At some point, the forms were transferred (copied) and adapted for use in MU3 (here https://github.com/musescore/MuseScore/tree/master/src/notation/view/widgets)
4. Old forms have been changed
5. MU4 was developed to the point that it was possible to switch to it.
6. We switched to MU4 and deleted the MU3 code - accordingly, we lost the changes that were made in the old MU3 forms after they were transferred to MU4

We need to find and restore changes them

**Comment by IsaacWeiss** [comment]
I thought MU4 means QML, and this still looks like an old MU3 UI file?

**Comment by cbjeukendrup** [comment]
@IsaacWeiss For the time being, some old dialogs will still be used. When the most essential things are done, those dialogs will be redesigned/rewritten, but that does not have priority at this moment AFAIK.

**Comment by IsaacWeiss** [comment]
If that's the case, I'm having trouble understanding how something could have gotten lost.

**Comment by cbjeukendrup** [comment]
It seems to be a little different than Igor said. 

This piece of git log explains everything: (`git log -- mscore/editstyle.ui`)
Schermafbeelding 2021-02-15 om 18 04 48

1. In 5ac4d300de6a874313c62e173ac48cd7930a2807, Elnur moved editstyle.* in its entirety to the mu4 dir.

2. In a810c2a4eb5e3efd3279c3001ac79c85de403e1c, Roman added a new copy of editstyle.* to the mscore dir, _and_ modified the version in the mu4 dir.

3. In bcadc255a9133eec4ab1eeb1d4a78bb2c855c52d, Isaac's work was finally merged, but into the wrong version of editstyle.*, namely the one in the mscore dir.

4. In 1fb7138d14e27b4bdb7adf92013c2944b9f4b561, Igor deleted the mscore dir, and Isaac's work (and maybe some things Jojo did) were gone.

Conclusion: we need to "redo" those three commits by Jojo and Isaac in the new version of editstyle.*;

**Comment by IsaacWeiss** [comment]
> In bcadc25, Isaac's work was finally merged, but into the wrong version of editstyle.*, namely the one in the mscore dir.

Aha! That makes sense, thanks for explaining.

**Comment by cbjeukendrup** [comment]
If I have time this week, I will try to "redo" Isaac's and Jojo's changes. (Or is anybody else already looking into it?)

**Pull request merged**
