### PR TITLE
Fix saving scores opened by relative pathname from cmdline

### PR DESCRIPTION
**Pull request by mirabilos**
https://musescore.org/en/node/150956

The patch was tested against the 2.1 release and committed relative to the 2.2 branch.

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
As far as I can see it should apply cleanly to master too

**Comment by Jojo-Schmitz** [comment]
If you make the commit message starting with `fix #150956:`, that issue will get marked as fixed automagically once ths PR gets merged

**Comment by mirabilos** [comment]
Thanks, I’ve updated the commit message.

As `scorefile.cpp` didn’t change between 2.1 and 2.2 it should work; master does contain some changes, but (in the function affected) only in the way things were translated, so it will likely just work there as well, yes.

**Comment by Jojo-Schmitz** [comment]
Yes, I manually checked that this PR should not cause merge conflits with master, so should cherrypick cleanly

**Comment by mirabilos** [comment]
@lasconic can we pretty please have this in 2.2? I’ve been carrying it in the Debian package since like forever…

**Comment by lasconic** [comment]
Merged, also on master https://github.com/musescore/MuseScore/commit/28a54f39633df533805a4f0d05946a80f41e0f24

**Comment by mirabilos** [comment]
Thanks!

**Pull request merged**
