### PR TITLE
fix #291491: support tuplets in rebaseMinDistance

### PR DESCRIPTION
**Pull request by MarcSabatella**
See https://musescore.org/en/node/291491.  Support for autoplace of tuplets was added recently and is mostly good from what I can tell, but unfortunately min distance isn't being managed correctly, because the code currently relies on placement() which is not defined for tuplets.  I discuss several possible solutions in the issue thread, but this one is the simplest for now, we can always revisit this later to make things more general.

### CODE REVIEW

**Comment by MarcSabatella** [comment]
Second commit simply reduces the default min distance, which I feel was too high and was resulting in tuplets being too far away by default (noticeably further away than prior to the change to autoplace tuplets) and thus leading to people resorting to manual adjustment when it shouldn't have been necessary.

**Comment by MarcSabatella** [comment]
Hmm, now I see the "above" parameter was only added recently, maybe it makes more sense to just pass that to rebaseMinDistance().

**Comment by dmitrio95** [comment]
> Hmm, now I see the "above" parameter was only added recently, maybe it makes more sense to just pass that to rebaseMinDistance().

Yes, I added it in the same PR #5118 in order to make it possible to support autoplacement for tuplets without explicit special-casing in the autoplacement code itself. Other options were to set a correct placement value for a tuplet on layout (which caused issues with extra `<placement>` tags in MSCX files) and overriding `placement()` function which I didn't feel to be a good solution since `placement()` is supposed to return the same as `getProperty(Pid::PLACEMENT)` call would.

It would be logical if `rebaseMinDistance` used the same placement value as other parts of autoplacement code so I would support the idea of passing the `above` parameter from autoplacement functions to `rebaseMinDistance`.

**Comment by MarcSabatella** [comment]
Working on making autoplace use the shape rather than bbox and also fix a couple of other issues with tuplet autoplace:

- double-click and adjusting the handle causes it to fly away from the staff
- autoplace is preventing the "avoid staves" style setting from being honored (it always avoids the staff)

**Comment by MarcSabatella** [comment]
As far as I can tell, all is working correctly now.  I have tested a number of cases:

- default position above/below staff (should look more or less same as 3.1 if no articulations)
- behavior on adjust above/below staff (min distance should decrease as you move into skyline)
- behavior when moving onto staff from above or below (min distance should go to -999)
- behavior when adjusting handles
- behavior when disabling Format / Style / Tuplets / Avoid staves
- making sure this all works for staves >1

The only things that are not completely ideal from my perspective:

1) I couldn't see an easy way to get meaningful autoplace results with avoid staves turned off.  Would have been nice to still avoid notes & articulations but not avoid the staff, but that's not feasiable without moving to something like the way we autoplace slurs, where we look for collisions segment by segment instead of using the skyline.

2) If the bracket angle is steep, we'll leave too much room, because even using the shape rather than the bbox(), we still draw a rectangle around the bracket section.  But at least user can manually adjust, or just disable autoplace for those cases where it is an issue.  Seems a fair tradeoff for what we gain.

**Pull request merged**
