### PR TITLE
Fix #10791: focus is setted when switch from instruments and template…

### LINKED ISSUE #10791: When the New Score dialog is triggered, the search bar should automatically be in focus
**Describe the bug**
When the **New Score** dialog is triggered, the search bar should automatically be in focus so users can immediately begin typing.

image

### PR DESCRIPTION
**Pull request by tzarjakob**
… options but not when the wizard is opened directly

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
The reason that it does not work when opening the dialog, is probably here:
https://github.com/musescore/MuseScore/blob/57f790d6ed2fee969547daababf30bb21bb7c70c/src/project/qml/MuseScore/Project/NewScoreDialog.qml#L62

First, focus is set to the search field, but then, by that line, focus is set back to something else. So, you need to remove or change that line.

If that does not fix the problem, do the following:
1. in StyledDialogView.qml, add a property like this:
    ```qml
    property bool isDoActiveFirstControlOnOpen: true
    ```
2. Also in StyledDialogView.qml, modify the `onOpened` handler:
    ```qml
    onOpened: {
        if (root.isDoActiveFirstControlOnOpen) {
            Qt.callLater(navSec.requestActive)
        }
    }
    ```
3. In NewScoreDialog.qml and in InstrumentsDialog.qml, add `isDoActiveFirstControlOnOpen: false`.

---

Also, I think you should not modify TextInputField for this. Specifically, I don't really feel good about putting `forceActiveFocus()` inside the property getter of the `focus` property. Instead, do the following:
1. In InstrumentsView.qml and TitleListView.qml, add a function like this:
   ```qml
    function focusSearchField() {
        searchField.navigation.requestActive()
    }
    ```
4. In ChooseInstrumentsPage.qml and CreateFromTemplatePage.qml, add a function like this:
   ```qml
    function focusOnFirst() {
        instrumentsView.focusSearchField() // templatesView in CreateFromTemplatePage.qml
    }
    ```
5. In ChooseInstrumentsAndTemplatesPage.qml, find the Loader and add the following:
   ```qml
        onLoaded: {
            if (item && item.focusOnFirst) {
                Qt.callLater(item.focusOnFirst)
            }
        }
    ```
That way, whenever a different page is loaded, the `focusOnFirst` function of that new page will be called.
It's slightly more work, but a bit more correct.

**Comment by tzarjakob** [comment]
Thank you, very useful. I've cleaned up and I'll fix the problem according to your advice. Soon I'll share the update.

**Comment by RobFog** [comment]
Instead of closing the pull request, you can mark it as a draft.

**Comment by tzarjakob** [comment]
Yes, I wanted to clean up (don't want to keep changes), but you are right, could have been marked as draft

**Comment by Jojo-Schmitz** [comment]
Better not use your master branch, but rather some topic branch

**Comment by Eism** [comment]
Hey @tzarjakob 
I agree with @cbjeukendrup and I prefer the second version of the fixes he suggested
If it's not difficult for you, please implement it in #10791

**Comment by tzarjakob** [comment]
I have already implemented following his advice in #10920 but I don't see a second version of his suggestions.

**Comment by Eism** [comment]
@tzarjakob 
Ah, I got it

**Pull request closed without merging**
