### PR TITLE
file extensions in lowercase (only)

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Should be got got master and 2.2.

Once merged and released the handbook needs to get amended, https://musescore.org/en/handbook/file-formats-0#band-in-a-box and https://musescore.org/en/handbook/file-formats-0#guitar-pro

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
Redundant with https://github.com/musescore/MuseScore/pull/3253?

**Comment by Jojo-Schmitz** [comment]
Ah, very true, @lasconic and I were not sure anymore where it got discussed and what the outcome was.
There's a part however you didn't change in your PR, the one in mtest for mtest/biab/tst_biab.cpp (and the renaming of mtest/biab/chords.SGU to mtest/biab/chords.sgu, which is missing in my PR for some reason

**Comment by Jojo-Schmitz** [comment]
Ah, very true, @lasconic and I were not sure anymore where it got discussed and what the outcome was.
 There's a part however you didn't change in your PR, the one for mtest/biab/tst_biab.cpp (and the renaming of mtest/biab/chords.SGU to mtest/biab/chords.sgu, which is missing in my PR for some reason)
Mind to add these changes to your PR? Then I'll close mine...

**Comment by Jojo-Schmitz** [comment]
Well, actually here's the proof that this change isn't save, at least not the SGU vs. sgu part (and due to my renaming not having been part of the commit)

**Comment by Jojo-Schmitz** [comment]
Ooops, closed by accident

**Comment by Jojo-Schmitz** [comment]
It should be save, all extensions get transformed to lowercase in MuseScore, just not in that one mtest

**Comment by Jojo-Schmitz** [comment]
Darn, I can't get the file rename become part of the commit.

**Comment by Jojo-Schmitz** [comment]
Anyway, that part isn't really needed, so #3253 should cover everything neccessary

**Pull request closed without merging**
