### PR TITLE
Fix # 104896: add sackbuts to instruments.xml

### PR DESCRIPTION
**Pull request by ZackTheCardshark**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
There' s a bit more needed, compare with #2515

**Comment by Jojo-Schmitz** [comment]
There' s a bit more needed, namely some additions to  share/instruments/instrumentsxml.h, compare with #2515

**Comment by ZackTheCardshark** [comment]
Ah, for the translations. I see there is a README in share/instruments that says
<code>
If instruments.xml is modified
* run `generateTs.py` and lupdate.sh
* push the new file updated ts en_US file to transifex
</code>
I don't see lupdate.sh, but I ran the Python script. It successfully filled in the extra lines in instrumentsxml.h, but also made a change to the Guiro (the U became Ü). Is that a problem?

**Comment by Jojo-Schmitz** [comment]
I never ran that script, but did the changes manually, don't have Python on my Windows machine.
Not sure, I think for compatibility we're not supposed to use anything bug 7-but ASCII in .cpp and .h files, Guiro is translated to Güiro on Transifex for that reason I believe.

**Comment by Jojo-Schmitz** [comment]
I never ran that script, but did the changes manually, don't have Python on my Windows machine.
Not sure, I think for compatibility with compilers on other platforms we're not supposed to use anything but 7-but ASCII in .cpp and .h files, "Guiro" is translated to "Güiro" on Transifex for that reason I believe.
I'd rather drop that part of the change.

**Comment by Jojo-Schmitz** [comment]
Yes, for translations.
I never ran that script, but did the changes manually, don't have Python on my Windows machine.
Not sure, I think for compatibility with compilers on other platforms we're not supposed to use anything but 7-but ASCII in .cpp and .h files, "Guiro" is translated to "Güiro" on Transifex for that reason I believe.
On the other hand I do see that quite a few "♭" are in, also non-7-bit ASCII, even UTF-8, so you can just leave the "ü" in too, I guess. @lasconic?

**Comment by lasconic** [comment]
I don't really care, the Guiro is also used elsewhere in the code. And the ü was a problem there. So for consistency I removed it. Maybe I should change the python script to replace ü per u.

**Comment by Jojo-Schmitz** [comment]
Shouldn't the python scipt also replace ♭ with b then?

**Comment by ZackTheCardshark** [comment]
FWIW, I changed it back to a plain "u" and squashed commits.

**Comment by Jojo-Schmitz** [comment]
@lasconic : I think since C++11 we could use stuff like `u8"Güiro"`` in C++ code files. So that python script could do this for us, maybe?

**Comment by Jojo-Schmitz** [comment]
@lasconic : I think since C++11 we could use stuff like `u8"Güiro"` in C++ code files. Same for all the strings containing a ♭. See http://en.cppreference.com/w/cpp/language/string_literal
So that python script could do this for us, maybe?

OTH this file is never touched by a compiler, just by lupdate, which is UTF-8 proof, so we won't run into any compatibility problem ever.

**Comment by lasconic** [comment]
We had no problem with Güiro in instruments.xml I believe. It was with the one in the code. So we changed both to get the same string everywhere.

**Comment by Jojo-Schmitz** [comment]
We could change "Guiro" in the code to `u8"Güiro"`

**Comment by Jojo-Schmitz** [comment]
We could change "Guiro" in the code to `u8"Güiro"`, see #2533

**Pull request merged**
