### PR TITLE
fix #100596

### PR DESCRIPTION
**Pull request by abhinavaggarwal**
https://musescore.org/en/node/100596

### CODE REVIEW

**Comment by lasconic** [comment]
It seems that @mgavioli did this on purpose here https://github.com/musescore/MuseScore/commit/df838b14274748a0d8242fcb33d9fc0d848791de 
but since there is no other context, it's hard to know exactly why. I will comment further in the issue tracker.

**Comment by mgavioli** [comment]
I do not fully remember all the details, but I kind of reconstruct something like this:

1) If an item has to be pre-selected in that combo when the dialogue box is open, it should be the one corresponding to the current settings, not just a default one (there are already methods in `StaffType` to check if a set of settings corresponds to the structure of an existing staff type)

2) But what to do if the current settings do not correspond to any preset (i.e. a custom staff type)?

**Comment by lasconic** [comment]
Ok. Thanks.
So, no selection was better than a suboptimal selection (like the first one, whatever it is). It seems that some users find it odd that nothing is selected.
So we can use 1/ to do a first selection. And in the case of 2/ select nothing or the first one.

**Comment by mgavioli** [comment]
To me, the 'proper' solution would seem adding another item to the drop list, labelled "Custom" and unselectable by the user, to be programmatically selected on dlg open if no preset matches the current settings.

This **was** I how initially implemented it in one or another of the several incarnations of this dlg box. But there were objections (which I no longer remember, sorry).

IIRC (and it has not been removed in the meantime ;) ), something rather similar **is** implemented (by me!) in some other dlg box.

**Comment by lasconic** [comment]
Let's try to move forward, not backward.

Why would we add a "Custom" element in this list. The user would reset to a custom template? Can you explain?

The simplest case:
* create a score for flute
* Go to this dialog, and change some settings (time signature visiblity)
* Decide you want to restore to default template (there is only standard)
* Go back to the dialog, select standard, and press reset to style

We could save the user a click and select standard by default instead of nothing.

A bit more complex
* Create a score for lute tablature
* Go to this dialog, and change some settings (time signature visiblity)
* Decide you want to restore to default template (there is a long list of templates available, standard and many tablatures one)
* We would need to auto select "Tab 6str french". How can we know that? Looking into the instrument template?

**Comment by mgavioli** [comment]
My expectation when opening this dlg box, would be this combo to be set at the preset matching the current settings, if any. If the settings have been customized and do not match any preset, I would expect the combo to display some notice of this, either a greyed out (unselectable) "Custom" text or nothing at all. But these are just my expectations.

I am not sure that, at least for use cases I am familiar with, any preset really qualifies as default, to be proposed unconditionally as "panic button".

**Comment by dmitrio95** [comment]
As discussed above, this solution is not good for the case of tablature staves, for example, and the current way was implemented intentionally in https://github.com/musescore/MuseScore/commit/df838b14274748a0d8242fcb33d9fc0d848791de. The better solution would probably be to create another item in that list but that should probably be implemented in another pull request.

**Pull request closed without merging**
