### PR TITLE
Revised & translated the sources in instuments_ko.ts file to Korean

### PR DESCRIPTION
**Pull request by lighteko**
I translated every sources in instruments_ko.ts file to Korean. There were several unnatural translations, so I fixed them as well.

- [X] I signed the [CLA](https://musescore.org/en/cla)
- [X] The title of the PR describes the problem it addresses
- [X] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [X] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [X] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
Translations are done on Transifex, not via PRs

**Comment by Jojo-Schmitz** [comment]
@cbjeukendrup might be able to grab this and upload to Transifex on one go and that way save you the work from having to do it all again there?

**Comment by cbjeukendrup** [comment]
Yes, that seems to have worked. @lighteko thanks for your work! Please check at https://app.transifex.com/musescore/musescore/translate/#ko/instruments if everything looks right there. It would be great if you could leave a comment here to assure us that it worked.
In 15 minutes from now, you can see the results in MuseScore Studio by going to Preferences > General, and clicking "Check for language updates" (and then restarting the program).

**Comment by lighteko** [comment]
@Jojo-Schmitz  @cbjeukendrup  Thank you for your effort! I really appreciate it. Next time, I'll make sure to work in Transifex.

**Pull request closed without merging**
